table metadata_heatmap_items
	lineageTag: b3e1347c-dd81-42f6-bb5e-f578f33b1e2d

	column 'col.trueai_kpi1_min' = ```
			
			var _ref = metadata_heatmap_items[KPI 1_Reference Values]          // get the ref 
			var _sd = metadata_heatmap_items[KPI 1_SD]                         // get the SD
			var res = _ref - (_sd*2)            // apply the min formula
			RETURN
			res
			```
		lineageTag: 3a70afd3-69ef-4e49-83ff-06f2634aff67
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.trueai_kpi1_max' = ```
			
			var _ref = metadata_heatmap_items[KPI 1_Reference Values]          // get the ref 
			var _sd = metadata_heatmap_items[KPI 1_SD]                         // get the SD
			var res = (_ref + (_sd*2))            // apply the max formula
			RETURN
			res
			```
		lineageTag: c0af637e-4da7-4257-9ede-ac7fb18b3052
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.trueai_kpi2_min' = ```
			
			var _ref = metadata_heatmap_items[KPI 2_Reference Values]          // get the ref 
			var _sd = metadata_heatmap_items[KPI 2_SD]                         // get the SD
			var res = _ref - (_sd*2)            // apply the min formula
			RETURN
			res
			```
		lineageTag: 074b3f35-8dbf-45b1-8c1b-ea333a7d00dc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.trueai_kpi2_max' = ```
			
			var _ref = metadata_heatmap_items[KPI 2_Reference Values]          // get the ref 
			var _sd = metadata_heatmap_items[KPI 2_SD]                         // get the SD
			var res = (_ref + (_sd*2))            // apply the max formula
			RETURN
			res
			```
		lineageTag: 5a469298-3c61-4b1a-86f9-7ac342e53903
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_doc_id
		dataType: string
		lineageTag: 752adb02-7429-4cce-b8d4-2f432c1e5ccc
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 71db5dcb-1c37-4e29-9653-dd5fb97e9d68
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	column _sys_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: dcc94d11-1ddc-4fa4-a8d6-38718b59f780
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: ba33c338-d155-4355-978e-16568e5f168f
			defaultHierarchy: LocalDateTable_fce9eb30-8d54-4988-8dee-82919042a3c4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_def_short
		dataType: string
		lineageTag: 93d48b46-c3a4-409b-a48f-872c207cc74d
		summarizeBy: none
		sourceColumn: heatmap_kpi1_def_short

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_def_long
		dataType: string
		lineageTag: 8145b5c7-b703-44b3-a464-60728e58446d
		summarizeBy: none
		sourceColumn: heatmap_kpi1_def_long

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_def_short
		dataType: string
		lineageTag: 8cd0b4bf-2217-4f72-ba0b-08071ab21857
		summarizeBy: none
		sourceColumn: heatmap_kpi2_def_short

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_def_long
		dataType: string
		lineageTag: 2c76c2f2-e7ba-4174-a592-3b301b22018e
		summarizeBy: none
		sourceColumn: heatmap_kpi2_def_long

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_ref
		dataType: string
		lineageTag: f6f06b4b-bfe3-4789-bb68-17d83bdc503d
		summarizeBy: none
		sourceColumn: heatmap_kpi1_ref

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_ref
		dataType: string
		lineageTag: e311faca-2aa9-4802-87d9-ceecf6ecc394
		summarizeBy: none
		sourceColumn: heatmap_kpi2_ref

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi_screen
		dataType: string
		lineageTag: 76836dd8-e5f5-4cb0-b68b-28128fae2cda
		summarizeBy: none
		sourceColumn: heatmap_kpi_screen

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_whats_better
		dataType: string
		lineageTag: 3482c24d-0431-4767-99c7-6b71905f4cab
		summarizeBy: none
		sourceColumn: heatmap_kpi1_whats_better

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_whats_better
		dataType: string
		lineageTag: c401bef1-93fa-446f-b4bb-8e628ed8f7b6
		summarizeBy: none
		sourceColumn: heatmap_kpi2_whats_better

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_ai_score_name
		dataType: string
		lineageTag: bba1457c-d83d-4879-9622-7bf8667614e7
		summarizeBy: none
		sourceColumn: heatmap_kpi1_ai_score_name

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_ai_score_name
		dataType: string
		lineageTag: e3349ddb-0101-4f2e-bdfa-593bab7f8aa4
		summarizeBy: none
		sourceColumn: heatmap_kpi2_ai_score_name

		annotation SummarizationSetBy = Automatic

	column heatmap_sort_column
		dataType: string
		lineageTag: d7348a5a-d6d9-4f99-a3ae-44ff99d064a6
		summarizeBy: none
		sourceColumn: heatmap_sort_column

		annotation SummarizationSetBy = Automatic

	column heatmap_growth_category
		dataType: string
		lineageTag: 15f9993c-73a3-4e83-ae16-725266133152
		summarizeBy: none
		sourceColumn: heatmap_growth_category

		annotation SummarizationSetBy = Automatic

	column heatmap_name
		dataType: string
		lineageTag: 30530caf-27e0-45f5-85bb-b7ab5f1e5bbc
		summarizeBy: none
		sourceColumn: heatmap_name

		annotation SummarizationSetBy = Automatic

	column heatmap_description
		dataType: string
		lineageTag: ca268644-02bd-4abe-8dc3-3eadec50f92c
		summarizeBy: none
		sourceColumn: heatmap_description

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_weight
		dataType: double
		lineageTag: a11bf39e-c2a3-4372-9c73-f5ca7c977b35
		summarizeBy: sum
		sourceColumn: heatmap_kpi1_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column heatmap_kpi1_numerator_definition
		dataType: string
		lineageTag: 3963e288-b88e-4c64-9477-80b151d29fda
		summarizeBy: none
		sourceColumn: heatmap_kpi1_numerator_definition

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_denominator_definition
		dataType: string
		lineageTag: 60588511-5b61-4b18-aa97-e3df4fc53229
		summarizeBy: none
		sourceColumn: heatmap_kpi1_denominator_definition

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_numerator_definition
		dataType: string
		lineageTag: 942e0565-c288-4e37-88ed-e8ae4e75f5b5
		summarizeBy: none
		sourceColumn: heatmap_kpi2_numerator_definition

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_denominator_definition
		dataType: string
		lineageTag: 266ad626-5ea8-482f-a6ab-89b8ac4fbae0
		summarizeBy: none
		sourceColumn: heatmap_kpi2_denominator_definition

		annotation SummarizationSetBy = Automatic

	column heatmap_sort
		dataType: double
		lineageTag: c551b3c9-656c-4710-ad81-920462694f05
		summarizeBy: sum
		sourceColumn: heatmap_sort

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column heatmap_kpi1_min_factor
		dataType: string
		lineageTag: b2accbd0-cc41-4b4c-be1c-e29f0daf83ca
		summarizeBy: none
		sourceColumn: heatmap_kpi1_min_factor

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_min_factor
		dataType: string
		lineageTag: b3f2bcd5-02d9-41b0-8562-4aace95671d0
		summarizeBy: none
		sourceColumn: heatmap_kpi2_min_factor

		annotation SummarizationSetBy = Automatic

	column item_vs_all_relative_weight
		dataType: double
		lineageTag: cb550410-0b0f-4ed5-9195-2ff593505f54
		summarizeBy: sum
		sourceColumn: item_vs_all_relative_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prerequisites
		dataType: string
		lineageTag: 9a80d2f8-0e1d-4078-baae-f4bc9c4980ed
		summarizeBy: none
		sourceColumn: prerequisites

		annotation SummarizationSetBy = Automatic

	column further_research
		dataType: string
		lineageTag: 58437078-831b-4e1d-8dc0-2e8ea35829d6
		summarizeBy: none
		sourceColumn: further_research

		annotation SummarizationSetBy = Automatic

	column transformation_ideas
		dataType: string
		lineageTag: 0a6cb553-fe7c-4a8f-a003-f35c3cb9bab7
		summarizeBy: none
		sourceColumn: transformation_ideas

		annotation SummarizationSetBy = Automatic

	column kpi1_related
		dataType: string
		lineageTag: 5d8b8642-fa88-4d22-890f-c4f510603dbc
		summarizeBy: none
		sourceColumn: kpi1_related

		annotation SummarizationSetBy = Automatic

	column kpi2_related
		dataType: string
		lineageTag: 2f685eb9-6378-403b-a216-2d4542cad2d4
		summarizeBy: none
		sourceColumn: kpi2_related

		annotation SummarizationSetBy = Automatic

	partition metadata_heatmap_items = m
		mode: import
		source = ```
				let
				  
				  dbTable = getDBTable("metadata_heatmap_items"),     // get the right table
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				      {"_sys_doc_id", type text}, 
				      {"heatmap_kpi1_def_short", type text}, 
				      {"heatmap_kpi1_def_long", type text}, 
				      {"heatmap_kpi2_def_short", type text}, 
				      {"heatmap_kpi2_def_long", type text}, 
				      {"heatmap_kpi1_ref", type text}, 
				      {"heatmap_kpi2_ref", type text}, 
				      {"heatmap_kpi_screen", type text}, 
				      {"heatmap_kpi1_whats_better", type text}, 
				      {"heatmap_kpi2_whats_better", type text}, 
				      {"heatmap_kpi1_ai_score_name", type text}, 
				      {"heatmap_kpi2_ai_score_name", type text}, 
				      {"heatmap_sort_column", type text}, 
				      {"heatmap_growth_category", type text}, 
				      {"heatmap_name", type text}, 
				      {"heatmap_description", type text}, 
				      {"heatmap_kpi1_weight", type number}, 
				      {"heatmap_kpi1_numerator_definition", type text}, 
				      {"heatmap_kpi1_denominator_definition", type text}, 
				      {"heatmap_kpi2_numerator_definition", type text}, 
				      {"heatmap_kpi2_denominator_definition", type text}, 
				      {"heatmap_sort", type number}, 
				      {"heatmap_kpi1_min_factor", type text}, 
				      {"heatmap_kpi2_min_factor", type text}, 
				      {"prerequisites", type text}, 
				      {"further_research", type text}, 
				      {"transformation_ideas", type text},
				      {"_sys_is_active", type logical},           
				      {"_sys_modified_on", type datetime},
				      {"item_vs_all_relative_weight", type number}
				
				    }),
				    kpi1Related = Table.AddColumn(dbTableTyped, "kpi1_related", each [_sys_doc_id] & "-" & "1"),
				    kpi1RelatedTyped = Table.TransformColumnTypes(kpi1Related,{{"kpi1_related", type text}}),
				    kpi2Related = Table.AddColumn(kpi1RelatedTyped, "kpi2_related", each [_sys_doc_id] & "-" & "2"),
				    kpi2RelatedTyped = Table.TransformColumnTypes(kpi2Related,{{"kpi2_related", type text}})
				in
				    kpi2RelatedTyped
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

