table metadata_graphics
	lineageTag: 082acf99-4fd2-4404-830d-dcb1f51e99f5

	column _sys_base64
		dataType: string
		lineageTag: f41f5d29-49ae-4ab5-a734-78009136dfb6
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: _sys_base64

		annotation SummarizationSetBy = Automatic

	column _sys_dimensions
		dataType: string
		lineageTag: 539ff6df-d240-4b3d-ad81-a215e436a857
		summarizeBy: none
		sourceColumn: _sys_dimensions

		annotation SummarizationSetBy = Automatic

	column _sys_doc_id
		dataType: string
		lineageTag: a0004065-cabb-4a5c-bc6a-f0864c564bb4
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_name
		dataType: string
		lineageTag: fe3e7ddb-3940-4735-8929-15d84b0a1ab3
		summarizeBy: none
		sourceColumn: _sys_name

		annotation SummarizationSetBy = Automatic

	column _sys_url
		dataType: string
		lineageTag: 5dbfb125-46b7-409d-af0f-94bcfd63a6be
		summarizeBy: none
		sourceColumn: _sys_url

		annotation SummarizationSetBy = Automatic

	column notes
		dataType: string
		lineageTag: 7a87b03d-7afa-47de-bed8-4cbb36947ae8
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	column _sys_is_active
		dataType: string
		lineageTag: 29282e56-8a1b-4be9-8878-1bcdf741dde3
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	column _sys_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: ff207ee0-7f2a-4e0c-87fc-d350c288bb7a
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: bea26321-0e74-4ae4-b03e-c1f1d9f81ab1
			defaultHierarchy: LocalDateTable_6bae1749-e5f3-4230-894a-f019b9181ac4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition metadata_graphics = m
		mode: import
		source =
				let
				  dbTable = getDBTable("metadata_graphics"), // get the right table
				
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				    {"_sys_base64", type text},
				    {"_sys_dimensions", type text},
				    {"_sys_doc_id", type text},
				    {"_sys_name", type text},
				    {"_sys_url", type text},
				    {"notes", type text}
				
				
				
				  })
				in
				    dbTableTyped

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

