table opps_histories
	lineageTag: 651a6d1f-3df5-4883-8c2e-20a09ee08d51

	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: 359b51d0-00a6-45f7-b5ab-cabf28dc75af
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 9c17fcbb-5bb5-4935-9112-1d61accdf5b9
			defaultHierarchy: LocalDateTable_bf6ac88e-8d01-4fd3-8a93-551b06d48c18.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5f6385a8-e90c-4191-bd1b-a4432dcdec32
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 6d61c84c-7833-4379-8c3e-3a0e63adf6bd
			defaultHierarchy: LocalDateTable_f5d0cb44-94be-4fc4-8fcb-e0dd53717304.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 23a8ff37-e375-4104-aae4-b00a4cffec0c
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 3b0b6bbf-f274-4589-8a32-a516efaf9a75
			defaultHierarchy: LocalDateTable_ca44fe76-ebe1-4b98-990b-91376b138414.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_doc_id
		dataType: string
		lineageTag: f083e95d-4724-43a0-a5a8-76e0e63e472c
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column crm_booking_amt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 661701ca-43b0-4c10-8ba0-96a1c8746f5d
		summarizeBy: sum
		sourceColumn: crm_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column crm_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: cfe39f8a-af77-4d9e-b657-c40bfa34fc00
		summarizeBy: none
		sourceColumn: crm_close_date

		variation Variation
			isDefault
			relationship: 85138ade-8435-441a-ba1d-d27377105c2d
			defaultHierarchy: LocalDateTable_80a6c06d-8757-4180-ac20-b251a29179ef.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 8e322db4-7f5f-452d-87c0-2bcb6213861b
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: e3732f58-b3f5-4aa1-a66d-67d73c015040
			defaultHierarchy: LocalDateTable_0c75db12-e0fe-4ca2-b1c8-f885e19c28e6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: d7ae15fc-9f33-4cfb-996d-377f30674fdf
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_opp_id
		dataType: string
		lineageTag: d82f1197-89ae-46ae-9ef8-6a3809fbefcf
		summarizeBy: none
		sourceColumn: crm_opp_id

		annotation SummarizationSetBy = Automatic

	column crm_stage_name
		dataType: string
		lineageTag: 21e3ec45-f85e-4811-ad44-b4701a6aed56
		summarizeBy: none
		sourceColumn: crm_stage_name

		annotation SummarizationSetBy = Automatic

	column crm_stage_num
		dataType: string
		lineageTag: 6fe3b63b-7334-41fe-a8ea-0d269d565348
		summarizeBy: none
		sourceColumn: crm_stage_num

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 891d6654-62b1-4799-82b7-82c5c9cd8279
		summarizeBy: sum
		sourceColumn: trueai_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column trueai_can_be_excluded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f42076a4-746b-4f53-b483-b75aa20f84f5
		summarizeBy: none
		sourceColumn: trueai_can_be_excluded

		annotation SummarizationSetBy = Automatic

	column trueai_current_prob_of_win
		dataType: double
		lineageTag: 5b1e8546-afe1-4e3b-bb04-0edb291bac53
		summarizeBy: sum
		sourceColumn: trueai_current_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_is_closed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d034b711-4dab-4d61-bc07-f25601ca65b9
		summarizeBy: none
		sourceColumn: trueai_is_closed

		annotation SummarizationSetBy = Automatic

	column trueai_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6d403900-eda9-4a9e-95b4-05dc10286a5a
		summarizeBy: none
		sourceColumn: trueai_is_won

		annotation SummarizationSetBy = Automatic

	column trueai_stage
		dataType: string
		lineageTag: 98a6ab11-a82a-4fab-9799-751f859d2333
		summarizeBy: none
		sourceColumn: trueai_stage

		annotation SummarizationSetBy = Automatic

	column trueai_step_sequence
		dataType: int64
		formatString: 0
		lineageTag: 837667df-bdce-4f53-a341-f40a2704469e
		summarizeBy: sum
		sourceColumn: trueai_step_sequence

		annotation SummarizationSetBy = Automatic

	column trueai_owner_prep_factor
		dataType: double
		lineageTag: cb5c48d9-93ac-4a6b-bb20-0ec86aeda588
		summarizeBy: sum
		sourceColumn: trueai_owner_prep_factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_owner_act_capt_lvl
		dataType: double
		lineageTag: cc002ce1-9aa4-4172-9d34-38a8c4809f88
		summarizeBy: sum
		sourceColumn: trueai_owner_act_capt_lvl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_owner_act_capt_lvl_conf
		dataType: double
		lineageTag: 86957507-93b9-4863-ab26-ea1b539b8c86
		summarizeBy: sum
		sourceColumn: trueai_owner_act_capt_lvl_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_count
		dataType: int64
		formatString: 0
		lineageTag: 07ade8c0-91f0-41f1-9121-e7fe1e876133
		summarizeBy: sum
		sourceColumn: trueai_act_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_auto_email_count
		dataType: int64
		formatString: 0
		lineageTag: 25dd7608-3524-42e2-a35f-0124941bbc68
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_auto_email_dur
		dataType: double
		lineageTag: b8a71482-448f-4567-bbb0-e8c89dd60151
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_auto_email_eng_count
		dataType: int64
		formatString: 0
		lineageTag: a967afe3-1c14-466a-b53e-302e57c414c0
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_call_count
		dataType: int64
		formatString: 0
		lineageTag: 85fa740b-0bc3-4afe-a778-54ce0f9f687d
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_call_dur
		dataType: double
		lineageTag: 814fabed-41db-4aab-8d21-4e751bce93d7
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_call_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 7e2651fb-4752-4d7b-ae1a-53e66a7040ba
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_dur
		dataType: double
		lineageTag: a4dd646c-471d-4377-9a8b-83d8f3819ba1
		summarizeBy: sum
		sourceColumn: trueai_act_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_email_count
		dataType: int64
		formatString: 0
		lineageTag: a26af861-047a-4ee0-867d-b3d107c80170
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_email_dur
		dataType: double
		lineageTag: 399ddcde-10e7-4c4e-973d-8ec03a125a6b
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_email_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 14999b0e-1d38-4ad8-9f27-7bb43d3f1b31
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 522ee33e-3be5-4744-87b5-369412c62255
		summarizeBy: sum
		sourceColumn: trueai_act_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_eng_dur
		dataType: double
		lineageTag: af98ebbf-41a1-4c89-8797-7d1fd1966cbc
		summarizeBy: sum
		sourceColumn: trueai_act_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_meeting_count
		dataType: int64
		formatString: 0
		lineageTag: d1d1c846-d581-4838-956d-ceba00fa42a9
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_meeting_dur
		dataType: double
		lineageTag: dfc6eea0-4a4f-4299-9cb9-86db9b6ca3f0
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_meeting_eng_count
		dataType: int64
		formatString: 0
		lineageTag: a7e7f5cb-8599-4c09-b1dd-de2d7ccf7f42
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_nd_count
		dataType: int64
		formatString: 0
		lineageTag: 02ee43fa-01cd-4caf-bab3-57d320a69845
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_nd_dur
		dataType: double
		lineageTag: f679a9e7-ce20-4bd6-a05c-b620f6c6da4d
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_nd_eng_count
		dataType: int64
		formatString: 0
		lineageTag: db0f4d12-3e89-4ae9-879d-c348a09d9789
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_no_interaction_count
		dataType: int64
		formatString: 0
		lineageTag: 0aadc490-4e9b-4694-af5f-50abce3d985a
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_no_interaction_dur
		dataType: double
		lineageTag: 40a527f2-7956-4791-9754-a1b905f0f77f
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_no_interaction_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 434130a8-be03-46d3-9f34-102949eb920b
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_social_count
		dataType: int64
		formatString: 0
		lineageTag: 4374c8cf-eae8-4b15-8895-e3207d891a24
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_social_dur
		dataType: double
		lineageTag: 86223a7e-c550-4a93-a03d-82f0efd24760
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_social_eng_count
		dataType: int64
		formatString: 0
		lineageTag: ce37f406-8a14-4031-9ec4-ff35964bfacf
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_adj_dur
		dataType: double
		lineageTag: f2128947-22d5-4056-af6e-48a310043fa6
		summarizeBy: sum
		sourceColumn: trueai_act_adj_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_adj_eng_dur
		dataType: double
		lineageTag: bcdcb0db-c50e-4425-bd98-596aea83b5a7
		summarizeBy: sum
		sourceColumn: trueai_act_adj_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_adj_dur_rule
		dataType: string
		lineageTag: 4783670d-af3b-43c1-aa37-e060d46ea43c
		summarizeBy: none
		sourceColumn: trueai_act_adj_dur_rule

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: 90e5cf57-e55d-42d0-8c3c-090b37abfd4f
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: a5919006-a74e-4583-bda1-62925915bcf1
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: ceb17f0e-f0ad-47d8-979a-31ea49374862
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: dbbac59b-2fc2-4646-ba62-738ef20f6c31
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: 6b5b547c-55ef-48ef-ba6d-279a9d78e8a4
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: double
		lineageTag: dcdd4797-5997-46d2-890e-54bbae8ff72a
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num2
		dataType: double
		lineageTag: 8b90995b-7830-4355-826b-494428caa6e8
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num3
		dataType: double
		lineageTag: 83a9d63d-4e37-48bc-8d5e-7ab7aeec8431
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num4
		dataType: double
		lineageTag: ccd5d325-b227-4db5-9fac-e3c7023f5392
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num5
		dataType: double
		lineageTag: 5c490103-a70f-455c-bb1c-e518c532430d
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num6
		dataType: double
		lineageTag: ee8d0cb2-f8b5-4328-b49a-d714e9692f0c
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num7
		dataType: double
		lineageTag: 573d1f5f-52cb-4abf-949a-2f863e0960ee
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 16e02b02-401a-4ef6-84f1-53211588f807
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5761b8d0-4a37-4483-87c7-c8929deba433
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt_rule
		dataType: int64
		formatString: 0
		lineageTag: 1f2a1150-4b0b-47b8-8b7d-caefebf0c31b
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_rule

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt_currency_rule
		dataType: int64
		formatString: 0
		lineageTag: 5391d11f-c53a-49d1-ba22-b8fcb3b9f707
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_currency_rule

		annotation SummarizationSetBy = Automatic

	column crm_stage_id
		dataType: string
		lineageTag: b2401557-bdd8-4701-95b8-5bad5ade786f
		summarizeBy: none
		sourceColumn: crm_stage_id

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_id
		dataType: string
		lineageTag: d76e6a11-7407-4631-b112-b792eeb78219
		summarizeBy: none
		sourceColumn: crm_pipeline_id

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_name
		dataType: string
		lineageTag: 8bff2659-867d-43e5-8638-925d1825970e
		summarizeBy: none
		sourceColumn: crm_pipeline_name

		annotation SummarizationSetBy = Automatic

	column trueai_stage_id
		dataType: string
		lineageTag: 149b5f92-4ff4-41f1-b655-6f7ce15ea9a5
		summarizeBy: none
		sourceColumn: trueai_stage_id

		annotation SummarizationSetBy = Automatic

	column trueai_stage_name
		dataType: string
		lineageTag: aac7de1f-b2b8-4310-b3d7-bbee646f5f67
		summarizeBy: none
		sourceColumn: trueai_stage_name

		annotation SummarizationSetBy = Automatic

	column trueai_pipeline_name
		dataType: string
		lineageTag: d07f6efb-e26a-47aa-8728-6fa6d7f9177f
		summarizeBy: none
		sourceColumn: trueai_pipeline_name

		annotation SummarizationSetBy = Automatic

	partition opps_histories = m
		mode: import
		source =
				let
				
				
				    dbTable = getDBTable("opps_histories"), // get the right table
				
				
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{{"_sys_as_of", type datetime}, {"_sys_doc_id", type text}, {"_sys_filt_end_date", type date}, {"_sys_filt_start_date", type date}, {"crm_booking_amt", Currency.Type}, {"crm_close_date", type datetime}, {"crm_created_on", type datetime}, {"crm_creator_id", type text}, {"crm_opp_id", type text}, {"crm_stage_name", type text}, {"crm_stage_num", type text}, {"trueai_act_adj_dur", type number}, {"trueai_act_adj_dur_rule", type text}, {"trueai_act_adj_eng_dur", type number}, {"trueai_act_count", Int64.Type}, {"trueai_act_dur", type number}, {"trueai_act_eng_count", Int64.Type}, {"trueai_act_eng_dur", type number}, {"trueai_act_type_auto_email_count", Int64.Type}, {"trueai_act_type_auto_email_dur", type number}, {"trueai_act_type_auto_email_eng_count", Int64.Type}, {"trueai_act_type_call_count", Int64.Type}, {"trueai_act_type_call_dur", type number}, {"trueai_act_type_call_eng_count", Int64.Type}, {"trueai_act_type_email_count", Int64.Type}, {"trueai_act_type_email_dur", type number}, {"trueai_act_type_email_eng_count", Int64.Type}, {"trueai_act_type_meeting_count", Int64.Type}, {"trueai_act_type_meeting_dur", type number}, {"trueai_act_type_meeting_eng_count", Int64.Type}, {"trueai_act_type_nd_count", Int64.Type}, {"trueai_act_type_nd_dur", type number}, {"trueai_act_type_nd_eng_count", Int64.Type}, {"trueai_act_type_no_interaction_count", Int64.Type}, {"trueai_act_type_no_interaction_dur", type number}, {"trueai_act_type_no_interaction_eng_count", Int64.Type}, {"trueai_act_type_social_count", Int64.Type}, {"trueai_act_type_social_dur", type number}, {"trueai_act_type_social_eng_count", Int64.Type}, {"trueai_booking_amt", Currency.Type}, {"trueai_can_be_excluded", type logical}, {"trueai_current_prob_of_win", type number}, {"trueai_is_closed", type logical}, {"trueai_is_won", type logical}, {"trueai_owner_act_capt_lvl", type number}, {"trueai_owner_act_capt_lvl_conf", type number}, {"trueai_owner_prep_factor", type number}, {"trueai_stage", type text}, {"trueai_step_sequence", Int64.Type}, {"cust_bool1", type logical}, {"cust_bool2", type logical}, {"cust_num1", type number}, {"cust_num2", type number}, {"cust_num3", type number}, {"cust_num4", type number}, {"cust_num5", type number}, {"cust_num6", type number}, {"cust_num7", type number}, {"cust_text1", type text}, {"cust_text2", type text}, {"cust_text3", type text}, {"cust_text4", type text}, {"cust_text5", type text}})
				in
				    dbTableTyped

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

