table users
	lineageTag: a820f8fc-c2ef-41f8-bc42-b46f25fc4f43

	column crm_division
		dataType: string
		lineageTag: 33550b93-126b-487d-9e30-5ec88ff36709
		summarizeBy: none
		sourceColumn: crm_division

		annotation SummarizationSetBy = Automatic

	column crm_username
		dataType: string
		lineageTag: bbcdda99-fb1d-4cc2-bafb-c79586cedb19
		summarizeBy: none
		sourceColumn: crm_username

		annotation SummarizationSetBy = Automatic

	column crm_email
		dataType: string
		lineageTag: a6335290-93dc-42cd-a2ce-2de9c5137a5b
		summarizeBy: none
		sourceColumn: crm_email

		annotation SummarizationSetBy = Automatic

	column crm_language_locale
		dataType: string
		lineageTag: 40e21f33-6ae5-46a7-8c18-06e4354f88b1
		summarizeBy: none
		sourceColumn: crm_language_locale

		annotation SummarizationSetBy = Automatic

	column crm_last_login_time
		dataType: dateTime
		formatString: General Date
		lineageTag: b24275a3-13db-4e05-ab17-2e6a117711e6
		summarizeBy: none
		sourceColumn: crm_last_login_time

		variation Variation
			isDefault
			relationship: 8a82df05-2884-4426-baf5-765dc77dc229
			defaultHierarchy: LocalDateTable_11fc6c4a-c432-4ad2-a5ac-2daa6b506406.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_locale
		dataType: string
		lineageTag: 399b4143-6c76-4299-ae26-393cf9c2a963
		summarizeBy: none
		sourceColumn: crm_locale

		annotation SummarizationSetBy = Automatic

	column crm_profile_url
		dataType: string
		lineageTag: ea0574d9-3f71-4e27-a708-f214d2215cc9
		summarizeBy: none
		sourceColumn: crm_profile_url

		annotation SummarizationSetBy = Automatic

	column crm_time_zone
		dataType: string
		lineageTag: 01e66e1b-d600-4838-9c3b-3a63028092c1
		summarizeBy: none
		sourceColumn: crm_time_zone

		annotation SummarizationSetBy = Automatic

	column crm_role
		dataType: string
		lineageTag: 7b0b30a3-2da8-4109-8f97-646b7e68c951
		summarizeBy: none
		sourceColumn: crm_role

		annotation SummarizationSetBy = Automatic

	column crm_title
		dataType: string
		lineageTag: eaf0edd9-7aac-46e2-80c7-dbaa5ffb69eb
		summarizeBy: none
		sourceColumn: crm_title

		annotation SummarizationSetBy = Automatic

	column crm_user_type
		dataType: string
		lineageTag: 44f73047-d35f-44cc-be40-abe2bcc9e958
		summarizeBy: none
		sourceColumn: crm_user_type

		annotation SummarizationSetBy = Automatic

	column trueai_hire_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e049536e-c0ac-4f78-b6f0-c63e8bbb1225
		summarizeBy: none
		sourceColumn: trueai_hire_date

		variation Variation
			isDefault
			relationship: 9d1627e3-bf9f-4029-8b9a-076a51d6ea6c
			defaultHierarchy: LocalDateTable_fdd4e3a5-c429-413b-90c0-7eca8a366125.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_termination_date
		dataType: dateTime
		formatString: General Date
		lineageTag: de59aad4-b3c0-436e-b48b-95ba59e20c6e
		summarizeBy: none
		sourceColumn: trueai_termination_date

		variation Variation
			isDefault
			relationship: de2e6583-4e38-4e0b-a75a-32379330c4e4
			defaultHierarchy: LocalDateTable_7bca1e78-af76-46a2-abd5-5551bd7bd92d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_role
		dataType: string
		lineageTag: c529d258-39f0-42a3-b481-829244963fba
		summarizeBy: none
		sourceColumn: trueai_role

		annotation SummarizationSetBy = Automatic

	column trueai_title
		dataType: string
		lineageTag: 376df9b2-b031-4756-8088-e7fdf9d4d8f0
		summarizeBy: none
		sourceColumn: trueai_title

		annotation SummarizationSetBy = Automatic

	column trueai_user_role
		dataType: string
		lineageTag: 7c85b453-efa0-4534-911c-b80405c92a1d
		summarizeBy: none
		sourceColumn: trueai_user_role

		annotation SummarizationSetBy = Automatic

	column trueai_group
		dataType: string
		lineageTag: 6bbe1ba9-9650-4c21-9a9b-0422c0e0ecf5
		summarizeBy: none
		sourceColumn: trueai_group

		annotation SummarizationSetBy = Automatic

	column trueai_direct_reports
		dataType: int64
		formatString: 0
		lineageTag: a596de3f-dc32-4c2d-849e-db481ba399df
		summarizeBy: sum
		sourceColumn: trueai_direct_reports

		annotation SummarizationSetBy = Automatic

	column 'col.full_name' = ```
			
			var temp = If(ISBLANK(users[crm_last_name]), users[crm_username], users[crm_first_name] &  " " &  users[crm_last_name])
			var res = If(ISBLANK(temp) , users[_sys_doc_id], temp)
			return res 
			
			```
		lineageTag: 5284bfa4-c869-4767-84ab-9b6b570b3292
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column trueai_billable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f46ad3aa-2365-433f-8b9c-7adb2231a002
		summarizeBy: none
		sourceColumn: trueai_billable

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_function
		dataType: string
		lineageTag: 0d89d05f-f1b4-42a2-983f-f4ed89a0fd43
		summarizeBy: none
		sourceColumn: trueai_user_role_function

		annotation SummarizationSetBy = Automatic

	column _sys_co_id
		dataType: string
		lineageTag: 21c2f4fd-d14d-405b-a51e-0600b6b12cf6
		summarizeBy: none
		sourceColumn: _sys_co_id

		annotation SummarizationSetBy = Automatic

	column _sys_doc_id
		dataType: string
		lineageTag: 791e1cc0-6c74-4f01-868c-f55b8f5ee8cd
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 507dfd0c-728b-4908-8bbf-f73803919eff
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 1b72813c-c0ae-4f32-8779-3df624029021
			defaultHierarchy: LocalDateTable_10b22189-e4e1-42ec-8b3b-f6fb67455a41.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 702c91e3-fb50-48f6-99d3-636cac2d7e7e
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 42bf69f3-7f64-4543-8d01-bbd82362c15c
			defaultHierarchy: LocalDateTable_bcdb1ae0-18e4-4576-97fd-f7253c4c8684.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column crm_addr_city
		dataType: string
		lineageTag: aa8ac2b0-3271-40d0-937c-9e09fe837d25
		summarizeBy: none
		sourceColumn: crm_addr_city

		annotation SummarizationSetBy = Automatic

	column crm_addr_country
		dataType: string
		lineageTag: 3580cd0b-0f8d-426a-a2fc-075246a27c1a
		summarizeBy: none
		sourceColumn: crm_addr_country

		annotation SummarizationSetBy = Automatic

	column crm_addr_postal_code
		dataType: string
		lineageTag: 849021dd-df38-40a1-846d-154f6aa72bf0
		summarizeBy: none
		sourceColumn: crm_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column crm_addr_state
		dataType: string
		lineageTag: a1c0a18c-9d12-4180-a18a-d54a38f19998
		summarizeBy: none
		sourceColumn: crm_addr_state

		annotation SummarizationSetBy = Automatic

	column crm_addr_street
		dataType: string
		lineageTag: e3d9fd7c-dbd5-4e19-a76c-ff6f923beced
		summarizeBy: none
		sourceColumn: crm_addr_street

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: dc67ed0c-7d23-495a-9899-653b97ab66ff
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_first_name
		dataType: string
		lineageTag: 7e813078-a7a7-4689-80d7-2a8211520d01
		summarizeBy: none
		sourceColumn: crm_first_name

		annotation SummarizationSetBy = Automatic

	column crm_last_name
		dataType: string
		lineageTag: 6ca68d5c-6db2-48db-bbce-23964fd059e1
		summarizeBy: none
		sourceColumn: crm_last_name

		annotation SummarizationSetBy = Automatic

	column trueai_performance_lvl_reached_on
		dataType: dateTime
		formatString: General Date
		lineageTag: c3c53cf0-8280-4304-9007-d8205d5762ff
		summarizeBy: none
		sourceColumn: trueai_performance_lvl_reached_on

		variation Variation
			isDefault
			relationship: 28a75ebe-a5e4-4fbc-99b0-044c9df44436
			defaultHierarchy: LocalDateTable_cf296a2c-5039-4cf5-bd9a-9e7256874848.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_role_conf
		dataType: double
		lineageTag: 4ce9e3fc-0b4c-4200-ac9e-17b575758f70
		summarizeBy: sum
		sourceColumn: trueai_role_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_tenure
		dataType: int64
		formatString: 0
		lineageTag: 30591baf-9f33-429f-b8fd-60b8f3baa884
		summarizeBy: sum
		sourceColumn: trueai_tenure

		annotation SummarizationSetBy = Automatic

	column trueai_title_conf
		dataType: double
		lineageTag: 0f0638cb-da83-42fd-9c19-5fdf20ff0d23
		summarizeBy: sum
		sourceColumn: trueai_title_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_tot_reports
		dataType: int64
		formatString: 0
		lineageTag: 6f314795-3d34-4a56-8259-436ba10a3956
		summarizeBy: sum
		sourceColumn: trueai_tot_reports

		annotation SummarizationSetBy = Automatic

	column trueai_user_behavior
		dataType: string
		lineageTag: de5fcc3b-d910-4038-928f-d142d5856649
		summarizeBy: none
		sourceColumn: trueai_user_behavior

		annotation SummarizationSetBy = Automatic

	column trueai_user_behavior_conf
		dataType: double
		lineageTag: f8e010a1-6949-49ba-a4c2-75b8088c5862
		summarizeBy: sum
		sourceColumn: trueai_user_behavior_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_user_role_dept
		dataType: string
		lineageTag: c7ea8e16-de9b-4389-9551-70b985299cb1
		summarizeBy: none
		sourceColumn: trueai_user_role_dept

		annotation SummarizationSetBy = Automatic

	column trueai_group_conf
		dataType: double
		lineageTag: c676a029-1893-4a2f-8580-4b85d9bc6028
		summarizeBy: sum
		sourceColumn: trueai_group_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_ext_match_rule
		dataType: int64
		formatString: 0
		lineageTag: 78b0c4aa-3536-426b-93e3-3a4b6da90e5e
		summarizeBy: sum
		sourceColumn: trueai_ext_match_rule

		annotation SummarizationSetBy = Automatic

	column trueai_group_rule
		dataType: int64
		formatString: 0
		lineageTag: e9e2cb1f-a694-417b-9079-9ba06f078d8b
		summarizeBy: sum
		sourceColumn: trueai_group_rule

		annotation SummarizationSetBy = Automatic

	column trueai_addr_city
		dataType: string
		lineageTag: d7b7eccf-beb2-4440-a08b-01c14c727940
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	column trueai_addr_country
		dataType: string
		lineageTag: ff420cf6-7b9d-411e-b0fb-f70bbfc2fcfb
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	column trueai_addr_lat
		dataType: double
		lineageTag: 010f522c-b361-4624-b017-ed6e252ef6b3
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_long
		dataType: double
		lineageTag: 10551388-b7aa-4c30-8925-313a80e87cb9
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_postal_code
		dataType: string
		lineageTag: d9b98359-7422-462d-ba9f-a628064d7fb7
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column trueai_addr_state
		dataType: string
		lineageTag: fd994afc-6429-4007-a384-3bc714862275
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	column trueai_addr_street
		dataType: string
		lineageTag: 1ba6c4c0-5cd7-4053-a4fb-28a100bddf11
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	column trueai_ext_match_id
		dataType: string
		lineageTag: 8ad060d6-ced0-4b02-9070-1421d9fb244c
		summarizeBy: none
		sourceColumn: trueai_ext_match_id

		annotation SummarizationSetBy = Automatic

	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: c705fd98-ba8a-41d9-86dc-4005e182817a
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 3467c93b-9844-4885-9907-cb79f2726412
			defaultHierarchy: LocalDateTable_12527c07-e036-4ec0-b10b-6600c21c3b86.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 0741d8ef-3c76-4e73-b25d-7ef62ecc915a
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 63cd6fa3-7e76-4745-b291-446e40bdb6af
			defaultHierarchy: LocalDateTable_f0cf6cc9-5ee9-4705-818d-c4f33f09bd59.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 21034a18-d33c-45bc-acf7-8687e304b8af
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 2f16c93f-9bfd-4c40-b5f1-d2874aced0b9
			defaultHierarchy: LocalDateTable_a0e8b777-79ef-461b-813b-047844e22f9d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_dept
		dataType: string
		lineageTag: b1adb23a-ffe8-4776-b067-feb6f7839717
		summarizeBy: none
		sourceColumn: crm_dept

		annotation SummarizationSetBy = Automatic

	column crm_mgr_id
		dataType: string
		lineageTag: a287d758-3b46-4653-8bfa-c6cb71484663
		summarizeBy: none
		sourceColumn: crm_mgr_id

		annotation SummarizationSetBy = Automatic

	column trueai_is_mgr
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 98ffd90e-edd3-46f2-8b9e-a436a72f5e73
		summarizeBy: none
		sourceColumn: trueai_is_mgr

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_id
		dataType: string
		lineageTag: 3025d949-05a7-4743-8cd5-4fd17ae5c606
		summarizeBy: none
		sourceColumn: trueai_mgr_id

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_id_conf
		dataType: double
		lineageTag: 9c390422-c0b8-45b0-abb2-db1869528e15
		summarizeBy: sum
		sourceColumn: trueai_mgr_id_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_mgr_id_rule
		dataType: int64
		formatString: 0
		lineageTag: 3613a970-c8e6-4ab5-9cc4-4742aab688c1
		summarizeBy: sum
		sourceColumn: trueai_mgr_id_rule

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_ids
		dataType: string
		lineageTag: 93a1896e-269e-4cee-ad85-23e4cd42c1fb
		summarizeBy: none
		sourceColumn: trueai_mgr_ids

		annotation SummarizationSetBy = Automatic

	column trueai_is_dummy
		dataType: string
		lineageTag: 01a0b479-3af7-4fff-b816-3b323f3dba82
		summarizeBy: none
		sourceColumn: trueai_is_dummy

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_alias
		dataType: string
		lineageTag: f7c34dc6-fb9a-4481-a583-b8567263c9dd
		summarizeBy: none
		sourceColumn: trueai_user_role_alias

		annotation SummarizationSetBy = Automatic

	column trueai_test
		dataType: string
		lineageTag: 0b561e2f-fd8e-4eb8-8940-b7d4a80897a4
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	column trueai_test_conf
		dataType: double
		lineageTag: df636566-4561-4591-9b39-5e16eeb5b1d4
		summarizeBy: sum
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_test_rule
		dataType: string
		lineageTag: 0e1fc552-3d23-4901-9002-a3eb8fbedc0f
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	column trueai_test_debug
		dataType: string
		lineageTag: 24f109f3-bda1-4c23-9f98-cbc404e72267
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: 087a355d-86dc-4ae1-95a7-d3873458c273
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: 878ea6e9-a2c4-4e2d-a535-9a42be801070
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: 533e948f-dfaa-47d4-8224-38fd6f0eca4c
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: f281920b-e74a-4af9-b700-e3291b61a86d
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: 0416d3d5-2565-4137-ad42-d7411870a4c5
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: double
		lineageTag: b6c02f24-69ba-4814-809b-c6d1837edfff
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num2
		dataType: double
		lineageTag: 85786ba7-cc65-461c-85e6-7ea2e828f8f3
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num3
		dataType: double
		lineageTag: c64603f1-6253-477f-879f-7295633883cc
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num4
		dataType: double
		lineageTag: fc0b19af-680b-4e05-b527-9186afb7170c
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num5
		dataType: double
		lineageTag: 7408bf56-7cfa-4d9c-93b8-ff9ff8c72cec
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num6
		dataType: double
		lineageTag: ce3038e7-1450-4f64-ac54-f464b6cc5b12
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num7
		dataType: double
		lineageTag: 2e6ef431-e771-4f4f-9181-cc74e87a3bf0
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_bool1
		dataType: string
		lineageTag: 2d1956fd-8fbc-4fc2-b75f-44651e65c76b
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: string
		lineageTag: bc2ad23a-3c55-4113-909b-b60abef096f3
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	column crm_deep_link
		dataType: string
		lineageTag: 33c006d7-9057-4e63-aee2-26ae803dfc0b
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	column trueai_full_name
		dataType: string
		lineageTag: 01eed8e1-cd81-4cf9-8c45-92a0c382c651
		summarizeBy: none
		sourceColumn: trueai_full_name

		annotation SummarizationSetBy = Automatic

	partition users-325b18c0-2983-4ccf-ad12-2466298e6bdc = m
		mode: import
		source = ```
				let
				dbTable = getDBTable("users"), // get the right table
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				   {"_sys_as_of", type datetime},
				{"_sys_co_id", type text},
				{"_sys_doc_id", type text},
				{"_sys_filt_end_date", type date},
				{"_sys_filt_start_date", type date},
				{"_sys_last_modified_on", type datetime},
				{"crm_addr_city", type text},
				{"crm_addr_country", type text},
				{"crm_addr_postal_code", type text},
				{"crm_addr_state", type text},
				{"crm_addr_street", type text},
				{"crm_created_on", type datetime},
				{"crm_creator_id", type text},
				{"crm_dept", type text},
				{"crm_division", type text},
				{"crm_email", type text},
				{"crm_first_name", type text},
				{"crm_language_locale", type text},
				{"crm_last_login_time", type datetime},
				{"crm_last_name", type text},
				{"crm_locale", type text},
				{"crm_mgr_id", type text},
				{"crm_profile_url", type text},
				{"crm_role", type text},
				{"crm_time_zone", type text},
				{"crm_title", type text},
				{"crm_user_type", type text},
				{"crm_username", type text},
				{"trueai_addr_city", type text},
				{"trueai_addr_country", type text},
				{"trueai_addr_lat",  type number},
				{"trueai_addr_long",  type number},
				{"trueai_addr_postal_code", type text},
				{"trueai_addr_state", type text},
				{"trueai_addr_street", type text},
				{"trueai_billable", type logical},
				{"trueai_direct_reports", Int64.Type},
				{"trueai_ext_match_id", type text},
				{"trueai_ext_match_rule", Int64.Type},
				{"trueai_group", type text},
				{"trueai_group_conf",  type number},
				{"trueai_group_rule", Int64.Type},
				{"trueai_hire_date", type datetime},
				{"trueai_is_mgr", type logical},
				{"trueai_mgr_id", type text},
				{"trueai_mgr_id_conf",  type number},
				{"trueai_mgr_id_rule", Int64.Type},
				{"trueai_mgr_ids", type text},
				{"trueai_performance_lvl_reached_on", type datetime},
				{"trueai_role", type text},
				{"trueai_role_conf",  type number},
				{"trueai_tenure", Int64.Type},
				{"trueai_termination_date", type datetime},
				{"trueai_title", type text},
				{"trueai_title_conf",  type number},
				{"trueai_tot_reports", Int64.Type},
				{"trueai_user_behavior", type text},
				{"trueai_user_behavior_conf",  type number},
				{"trueai_user_role", type text},
				{"trueai_user_role_dept", type text},
				{"trueai_user_role_function", type text}
				
				
				   
				    }),
				
				dbTableTypedRenamed = Table.RenameColumns(dbTableTyped,{ // rename one more time to not have to redo column names in reports
				
				
				
				
				})
				in
				dbTableTypedRenamed
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

