createOrReplace

	table opps_histories
		lineageTag: 07d56b6f-87b3-4b9b-adc4-29e315b54257

		measure 'meas.opps_histories_crm_stage_names' = ```
				
				-- concats all the crm values for trueai value
				
				-- summarize the currect context and sort by count desc
				var tbl_summarized = TOPN(10,SUMMARIZE(CALCULATETABLE(opps_histories), [trueai_stage_name], "count", Count(opps_histories[_sys_doc_id]) ),[count], DESC)
				
				-- use the summarized data and concat
				var str_crm_vals = CONCATENATEX(tbl_summarized,  [trueai_stage_name], ", ") 
				
				var res = str_crm_vals -- output string
				return res
				```
			lineageTag: 9b8b993f-71ab-40d8-a9a4-e750ffd6b366

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column _sys_doc_id
			dataType: string
			lineageTag: 0df2d9e6-ac25-4fc6-bf01-9d5af3c2733c
			summarizeBy: none
			sourceColumn: _sys_doc_id

			annotation SummarizationSetBy = Automatic

		column _sys_filt_end_date
			dataType: dateTime
			formatString: Short Date
			lineageTag: d2913d42-0c38-4ed0-8864-c413c74c5d31
			summarizeBy: none
			sourceColumn: _sys_filt_end_date

			variation Variation
				isDefault
				relationship: 42779ac8-437f-4d19-bac2-409e71fcb66a
				defaultHierarchy: LocalDateTable_d544b3f8-1703-433d-a2ff-c8a2c4711105.'Date Hierarchy'

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column _sys_filt_start_date
			dataType: dateTime
			formatString: Short Date
			lineageTag: b0650a47-e99c-49f0-9e84-3e03a31975ce
			summarizeBy: none
			sourceColumn: _sys_filt_start_date

			variation Variation
				isDefault
				relationship: f8e32bb0-8a65-4203-a9b8-c3c98ecb46dd
				defaultHierarchy: LocalDateTable_dbc13316-a312-4017-a911-74d3b8a625dd.'Date Hierarchy'

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column crm_booking_amt
			dataType: double
			lineageTag: e5ebb408-a882-4c4b-9bb8-64df5a5dbc5e
			summarizeBy: sum
			sourceColumn: crm_booking_amt

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column crm_close_date
			dataType: dateTime
			formatString: Short Date
			lineageTag: 5a6f3b4b-b115-49e0-8027-48a574436cfe
			summarizeBy: none
			sourceColumn: crm_close_date

			variation Variation
				isDefault
				relationship: 63f1f19a-ebd3-429b-8594-70b2eaa09b5c
				defaultHierarchy: LocalDateTable_206ed198-93c2-4e29-ac2e-b924e74f7a92.'Date Hierarchy'

			annotation SummarizationSetBy = Automatic

		column crm_creator_id
			dataType: string
			lineageTag: 056df7cd-e55a-4415-84b5-49afe9f47ca8
			summarizeBy: none
			sourceColumn: crm_creator_id

			annotation SummarizationSetBy = Automatic

		column crm_opp_id
			dataType: string
			lineageTag: 979943d3-5484-4f3d-ae46-afefbdf1aec2
			summarizeBy: none
			sourceColumn: crm_opp_id

			annotation SummarizationSetBy = Automatic

		column crm_stage_name
			dataType: string
			lineageTag: 85510259-368d-4434-9d66-4c21f882db2b
			summarizeBy: none
			sourceColumn: crm_stage_name

			annotation SummarizationSetBy = Automatic

		column crm_stage_num
			dataType: string
			lineageTag: e9f25c48-4d76-4c20-8428-5750f63daffe
			summarizeBy: none
			sourceColumn: crm_stage_num

			annotation SummarizationSetBy = Automatic

		column trueai_booking_amt
			dataType: double
			lineageTag: 085b50cb-4cc3-4dce-aa0d-7c9690c48a67
			summarizeBy: sum
			sourceColumn: trueai_booking_amt

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_can_be_excluded
			dataType: boolean
			formatString: """TRUE"";""TRUE"";""FALSE"""
			lineageTag: d654069e-44ae-4142-9e4b-73c50048fcc8
			summarizeBy: none
			sourceColumn: trueai_can_be_excluded

			annotation SummarizationSetBy = Automatic

		column trueai_step_sequence
			dataType: int64
			formatString: 0
			lineageTag: 323d6cc1-5d8f-4959-b760-441e0f893cd1
			summarizeBy: sum
			sourceColumn: trueai_step_sequence

			annotation SummarizationSetBy = Automatic

		column trueai_act_count
			dataType: int64
			formatString: 0
			lineageTag: 6314e6bf-3fba-489b-86de-c552e5292e14
			summarizeBy: sum
			sourceColumn: trueai_act_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_auto_email_count
			dataType: int64
			formatString: 0
			lineageTag: a01358b2-30db-478a-9c14-83f59a77d767
			summarizeBy: sum
			sourceColumn: trueai_act_type_auto_email_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_auto_email_dur
			dataType: double
			lineageTag: ffce0d13-d9ff-45b9-bd71-c4efa9a97fd5
			summarizeBy: sum
			sourceColumn: trueai_act_type_auto_email_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_auto_email_eng_count
			dataType: int64
			formatString: 0
			lineageTag: 11869790-7fb6-4a6b-b0c4-4c146ba7420e
			summarizeBy: sum
			sourceColumn: trueai_act_type_auto_email_eng_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_call_count
			dataType: int64
			formatString: 0
			lineageTag: 401e3152-0f4e-403a-8c19-cf2603b6f953
			summarizeBy: sum
			sourceColumn: trueai_act_type_call_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_call_dur
			dataType: double
			lineageTag: c67b6e57-3f82-43fd-9ff2-e369726d8c48
			summarizeBy: sum
			sourceColumn: trueai_act_type_call_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_call_eng_count
			dataType: int64
			formatString: 0
			lineageTag: 4f95c24b-857b-46df-880c-23d9bad389a6
			summarizeBy: sum
			sourceColumn: trueai_act_type_call_eng_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_dur
			dataType: double
			lineageTag: c0b2837f-915c-440b-bef7-aaa58a43d4a3
			summarizeBy: sum
			sourceColumn: trueai_act_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_email_count
			dataType: int64
			formatString: 0
			lineageTag: c682f2c4-e2a2-4ec0-9354-b6bed6a69b2b
			summarizeBy: sum
			sourceColumn: trueai_act_type_email_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_email_dur
			dataType: double
			lineageTag: f339f3d9-4fb3-475b-a963-005f8cc9a0a1
			summarizeBy: sum
			sourceColumn: trueai_act_type_email_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_email_eng_count
			dataType: int64
			formatString: 0
			lineageTag: c9b85cc5-1d9e-44e8-a63d-5cec8070d052
			summarizeBy: sum
			sourceColumn: trueai_act_type_email_eng_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_eng_count
			dataType: int64
			formatString: 0
			lineageTag: ff0b297b-c4c8-4964-b867-569618897be7
			summarizeBy: sum
			sourceColumn: trueai_act_eng_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_eng_dur
			dataType: double
			lineageTag: 90166fb8-5dc6-460e-af19-29055f91fc57
			summarizeBy: sum
			sourceColumn: trueai_act_eng_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_meeting_count
			dataType: int64
			formatString: 0
			lineageTag: 7387a8b7-e012-4960-9983-4809cd5a51f3
			summarizeBy: sum
			sourceColumn: trueai_act_type_meeting_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_meeting_dur
			dataType: double
			lineageTag: a03e1148-5e92-4367-8d8f-7b9524643f95
			summarizeBy: sum
			sourceColumn: trueai_act_type_meeting_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_meeting_eng_count
			dataType: int64
			formatString: 0
			lineageTag: 3532a5b4-076a-4961-9efb-7ece60361024
			summarizeBy: sum
			sourceColumn: trueai_act_type_meeting_eng_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_nd_count
			dataType: int64
			formatString: 0
			lineageTag: 2187abe7-6518-4f7f-8690-ed84f83a78cf
			summarizeBy: sum
			sourceColumn: trueai_act_type_nd_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_nd_dur
			dataType: double
			lineageTag: ae6f8939-86d7-4379-80c5-56a2c0ade46d
			summarizeBy: sum
			sourceColumn: trueai_act_type_nd_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_nd_eng_count
			dataType: int64
			formatString: 0
			lineageTag: 6ef285a3-2e3d-402e-9788-2e1e662b3975
			summarizeBy: sum
			sourceColumn: trueai_act_type_nd_eng_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_no_interaction_count
			dataType: int64
			formatString: 0
			lineageTag: d810e2b0-37db-48c0-adf6-9c4953395590
			summarizeBy: sum
			sourceColumn: trueai_act_type_no_interaction_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_no_interaction_dur
			dataType: double
			lineageTag: c164afca-de54-4273-a11d-cdd3f351667c
			summarizeBy: sum
			sourceColumn: trueai_act_type_no_interaction_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_no_interaction_eng_count
			dataType: int64
			formatString: 0
			lineageTag: 2b7df90f-f8e0-48f6-b01a-29ca8663c778
			summarizeBy: sum
			sourceColumn: trueai_act_type_no_interaction_eng_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_social_count
			dataType: int64
			formatString: 0
			lineageTag: 709fea30-325a-4ac4-b4c4-be352e76b834
			summarizeBy: sum
			sourceColumn: trueai_act_type_social_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_type_social_dur
			dataType: double
			lineageTag: 1a036555-ae73-4474-8495-89b6d47007f4
			summarizeBy: sum
			sourceColumn: trueai_act_type_social_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_type_social_eng_count
			dataType: int64
			formatString: 0
			lineageTag: a3d3f678-4065-4a03-acb0-4c6be8b413d4
			summarizeBy: sum
			sourceColumn: trueai_act_type_social_eng_count

			annotation SummarizationSetBy = Automatic

		column trueai_act_adj_dur
			dataType: double
			lineageTag: cd3737b5-44e3-43b2-a063-c548c27990dd
			summarizeBy: sum
			sourceColumn: trueai_act_adj_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_adj_dur_rule
			dataType: int64
			formatString: 0
			lineageTag: 599518d8-6fc2-4931-9310-54ae19c21a5c
			summarizeBy: sum
			sourceColumn: trueai_act_adj_dur_rule

			annotation SummarizationSetBy = Automatic

		column _sys_as_of
			dataType: dateTime
			formatString: mm/dd/yyyy
			lineageTag: cbd603c0-2001-4b54-8d08-0b2d89072572
			summarizeBy: none
			sourceColumn: _sys_as_of

			variation Variation
				isDefault
				relationship: 89c39e1b-f25f-4293-8aeb-8944bfe0b153
				defaultHierarchy: LocalDateTable_15ae63b0-038c-479c-bd9f-141fe4754f95.'Date Hierarchy'

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isCustom":true}

		column crm_created_on
			dataType: dateTime
			formatString: General Date
			lineageTag: 989bd814-1af7-4676-8a37-98c0f9260ded
			summarizeBy: none
			sourceColumn: crm_created_on

			variation Variation
				isDefault
				relationship: ec5b152c-9113-4050-943d-b306f6f24148
				defaultHierarchy: LocalDateTable_e96f0efa-acf5-477d-9d97-977d0a6c3ee4.'Date Hierarchy'

			annotation SummarizationSetBy = Automatic

		column trueai_current_prob_of_win
			dataType: double
			lineageTag: 28a41ce6-8f20-45e3-ba85-429a44d6b082
			summarizeBy: sum
			sourceColumn: trueai_current_prob_of_win

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_is_closed
			dataType: boolean
			formatString: """TRUE"";""TRUE"";""FALSE"""
			lineageTag: a4ac141a-4cb8-44ac-b158-b4b769f5fe52
			summarizeBy: none
			sourceColumn: trueai_is_closed

			annotation SummarizationSetBy = Automatic

		column trueai_is_won
			dataType: boolean
			formatString: """TRUE"";""TRUE"";""FALSE"""
			lineageTag: cf48caff-8280-4e94-be9d-f88ed20b9278
			summarizeBy: none
			sourceColumn: trueai_is_won

			annotation SummarizationSetBy = Automatic

		column trueai_stage
			dataType: string
			lineageTag: b6c3e2d4-79f9-49c3-8d79-8811b2c17cc3
			summarizeBy: none
			sourceColumn: trueai_stage

			annotation SummarizationSetBy = Automatic

		column trueai_owner_prep_factor
			dataType: double
			lineageTag: adc753e9-d5c9-4362-af8c-c10a590b9c1a
			summarizeBy: sum
			sourceColumn: trueai_owner_prep_factor

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_owner_act_capt_lvl
			dataType: double
			lineageTag: bce7f35c-fbf3-4c5b-ba5a-b40270454af9
			summarizeBy: sum
			sourceColumn: trueai_owner_act_capt_lvl

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_owner_act_capt_lvl_conf
			dataType: double
			lineageTag: 63bfd8a9-3430-44b0-8fb7-9ad95ac8316d
			summarizeBy: sum
			sourceColumn: trueai_owner_act_capt_lvl_conf

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column trueai_act_adj_eng_dur
			dataType: double
			lineageTag: 21175541-9932-456d-8d04-4309ab6cc426
			summarizeBy: sum
			sourceColumn: trueai_act_adj_eng_dur

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column cust_text1
			dataType: string
			lineageTag: a82af9ac-153b-4c55-9a4b-343cd5046bfb
			summarizeBy: none
			sourceColumn: cust_text1

			annotation SummarizationSetBy = Automatic

		column cust_text2
			dataType: string
			lineageTag: 85e50253-9b2a-4e1f-9980-1a2c6c74521f
			summarizeBy: none
			sourceColumn: cust_text2

			annotation SummarizationSetBy = Automatic

		column cust_text3
			dataType: string
			lineageTag: 4ea7ac74-835a-4464-9f1a-be7099415532
			summarizeBy: none
			sourceColumn: cust_text3

			annotation SummarizationSetBy = Automatic

		column cust_text4
			dataType: string
			lineageTag: be23089e-8d7a-4705-b9c5-390d26e44b35
			summarizeBy: none
			sourceColumn: cust_text4

			annotation SummarizationSetBy = Automatic

		column cust_text5
			dataType: string
			lineageTag: 7d66181a-42a5-4abf-a1a6-350b0299b194
			summarizeBy: none
			sourceColumn: cust_text5

			annotation SummarizationSetBy = Automatic

		column cust_num1
			dataType: double
			lineageTag: d4ae46f5-e6e9-4725-8634-b7cdb0442c52
			summarizeBy: sum
			sourceColumn: cust_num1

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column cust_num2
			dataType: double
			lineageTag: d7c4dc6a-e2da-4c16-85c6-7f5de2bbda59
			summarizeBy: sum
			sourceColumn: cust_num2

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column cust_num3
			dataType: double
			lineageTag: 5f4a0aa8-b447-4a71-b769-8607f536a894
			summarizeBy: sum
			sourceColumn: cust_num3

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column cust_num4
			dataType: double
			lineageTag: 213e6a16-0331-4ddc-b21e-7b648c475837
			summarizeBy: sum
			sourceColumn: cust_num4

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column cust_num5
			dataType: double
			lineageTag: 5d833189-b4bf-4c68-b24b-d2233a096250
			summarizeBy: sum
			sourceColumn: cust_num5

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column cust_num6
			dataType: double
			lineageTag: 8b20bfa4-9165-4d3a-946b-ab5d993f8992
			summarizeBy: sum
			sourceColumn: cust_num6

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column cust_num7
			dataType: double
			lineageTag: 718eca18-2276-43d0-94e7-e0e652db90c3
			summarizeBy: sum
			sourceColumn: cust_num7

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column cust_bool1
			dataType: boolean
			formatString: """TRUE"";""TRUE"";""FALSE"""
			lineageTag: a98003f1-d1e9-4ffc-b473-e07330b5717d
			summarizeBy: none
			sourceColumn: cust_bool1

			annotation SummarizationSetBy = Automatic

		column cust_bool2
			dataType: boolean
			formatString: """TRUE"";""TRUE"";""FALSE"""
			lineageTag: ba0c5e41-76eb-4c42-8c0a-2ec526f51738
			summarizeBy: none
			sourceColumn: cust_bool2

			annotation SummarizationSetBy = Automatic

		column crm_pipeline_id
			dataType: string
			lineageTag: cc49c736-f0cf-49cc-9c05-d2be4f2de1e7
			summarizeBy: none
			sourceColumn: crm_pipeline_id

			annotation SummarizationSetBy = Automatic

		column crm_pipeline_name
			dataType: string
			lineageTag: e3b313fe-7466-4f97-bb04-f9e9a60d39ae
			summarizeBy: none
			sourceColumn: crm_pipeline_name

			annotation SummarizationSetBy = Automatic

		column trueai_booking_amt_rule
			dataType: int64
			formatString: 0
			lineageTag: dd78a01d-19bb-4caf-89e1-7c0c0bef84e4
			summarizeBy: sum
			sourceColumn: trueai_booking_amt_rule

			annotation SummarizationSetBy = Automatic

		column trueai_booking_amt_currency_rule
			dataType: int64
			formatString: 0
			lineageTag: d78fdf72-8c53-4714-ac6a-fc35429134ce
			summarizeBy: sum
			sourceColumn: trueai_booking_amt_currency_rule

			annotation SummarizationSetBy = Automatic

		column crm_stage_id
			dataType: string
			lineageTag: 12afdc5d-bccb-412a-996d-31e897350bdd
			summarizeBy: none
			sourceColumn: crm_stage_id

			annotation SummarizationSetBy = Automatic

		column trueai_stage_id
			dataType: string
			lineageTag: aaf5b157-5815-4cf3-8265-73223b463e16
			summarizeBy: none
			sourceColumn: trueai_stage_id

			annotation SummarizationSetBy = Automatic

		column trueai_stage_name
			dataType: string
			lineageTag: ebdd284b-42d6-4cd7-891f-125f8541f5d5
			summarizeBy: none
			sourceColumn: trueai_stage_name

			annotation SummarizationSetBy = Automatic

		column trueai_pipeline_name
			dataType: string
			lineageTag: f616caf9-50b8-4694-b614-80950a46cf88
			summarizeBy: none
			sourceColumn: trueai_pipeline_name

			annotation SummarizationSetBy = Automatic

		partition opps_histories-1b9ec0c7-7b53-45bc-9e90-1f4b49c10e4a = m
			mode: import
			source =
					let
					
					
					    dbTable = getDBTable("opps_histories"), // get the right table
					
					
					    dbTableTyped = Table.TransformColumnTypes(dbTable,{
					{"_sys_as_of", type datetime},
					{"_sys_doc_id", type text},
					{"_sys_filt_end_date", type date},
					{"_sys_filt_start_date", type date},
					{"crm_booking_amt", type number},
					{"crm_close_date", type datetime},
					{"crm_created_on", type datetime},
					{"crm_creator_id", type text},
					{"crm_opp_id", type text},
					{"crm_pipeline_id", type text},
					{"crm_pipeline_name", type text},
					{"crm_stage_id", type text},
					{"crm_stage_name", type text},
					{"crm_stage_num", type text},
					{"cust_bool1", type logical},
					{"cust_bool2", type logical},
					{"cust_num1", type number},
					{"cust_num2", type number},
					{"cust_num3", type number},
					{"cust_num4", type number},
					{"cust_num5", type number},
					{"cust_num6", type number},
					{"cust_num7", type number},
					{"cust_text1", type text},
					{"cust_text2", type text},
					{"cust_text3", type text},
					{"cust_text4", type text},
					{"cust_text5", type text},
					{"trueai_act_adj_dur", type number},
					{"trueai_act_adj_dur_rule", Int64.Type},
					{"trueai_act_adj_eng_dur", type number},
					{"trueai_act_count", Int64.Type},
					{"trueai_act_dur", type number},
					{"trueai_act_eng_count", Int64.Type},
					{"trueai_act_eng_dur", type number},
					{"trueai_act_type_auto_email_count", Int64.Type},
					{"trueai_act_type_auto_email_dur", type number},
					{"trueai_act_type_auto_email_eng_count", Int64.Type},
					{"trueai_act_type_call_count", Int64.Type},
					{"trueai_act_type_call_dur", type number},
					{"trueai_act_type_call_eng_count", Int64.Type},
					{"trueai_act_type_email_count", Int64.Type},
					{"trueai_act_type_email_dur", type number},
					{"trueai_act_type_email_eng_count", Int64.Type},
					{"trueai_act_type_meeting_count", Int64.Type},
					{"trueai_act_type_meeting_dur", type number},
					{"trueai_act_type_meeting_eng_count", Int64.Type},
					{"trueai_act_type_nd_count", Int64.Type},
					{"trueai_act_type_nd_dur", type number},
					{"trueai_act_type_nd_eng_count", Int64.Type},
					{"trueai_act_type_no_interaction_count", Int64.Type},
					{"trueai_act_type_no_interaction_dur", type number},
					{"trueai_act_type_no_interaction_eng_count", Int64.Type},
					{"trueai_act_type_social_count", Int64.Type},
					{"trueai_act_type_social_dur", type number},
					{"trueai_act_type_social_eng_count", Int64.Type},
					{"trueai_booking_amt", type number},
					{"trueai_booking_amt_currency_rule", Int64.Type},
					{"trueai_booking_amt_rule", Int64.Type},
					{"trueai_can_be_excluded", type logical},
					{"trueai_current_prob_of_win", type number},
					{"trueai_is_closed", type logical},
					{"trueai_is_won", type logical},
					{"trueai_owner_act_capt_lvl", type number},
					{"trueai_owner_act_capt_lvl_conf", type number},
					{"trueai_owner_prep_factor", type number},
					{"trueai_pipeline_name", type text},
					{"trueai_stage", type text},
					{"trueai_stage_id", type text},
					{"trueai_stage_name", type text},
					{"trueai_step_sequence", Int64.Type}
					})
					in
					    dbTableTyped

		annotation PBI_ResultType = Table

		annotation PBI_NavigationStepName = Navigation

