/// Table cal_start_dates.
table cal_start_dates
	lineageTag: ae9642a0-a112-45e3-b507-ecb9caa9b8db

	/// Measure meas.last_selected_date.
	/// Purpose: Returns the last selected date from cal_start_dates[Date].
	/// Calculation Logic: Uses CALCULATE with MAX and ALLSELECTED.
	/// Dynamic Behavior: Respects current filter context; CALCULATE modifies context with ALLSELECTED(cal_start_dates[Date]) and responds to filters on cal_start_dates[Date].
	/// Format/Type: Short Date
	measure 'meas.last_selected_date' = CALCULATE(MAX(cal_start_dates[Date]), ALLSELECTED(cal_start_dates[Date]))
		formatString: Short Date
		lineageTag: 3ad297b1-22f7-40a4-8425-5df3ba7e89dd

	/// Measure meas.sel_date.
	/// Purpose: Returns the selected start date as the max of cal_start_dates[Date] in ALLSELECTED.
	/// Calculation Logic: Uses VAR/RETURN with CALCULATETABLE, ALLSELECTED, and MAXX.
	/// Dynamic Behavior: Respects current filter context; CALCULATETABLE/ALLSELECTED adjusts context and responds to filters on cal_start_dates[Date].
	/// Format/Type: General Date
	measure 'meas.sel_date' = ```
			
			
			VAR res = MAXX (CALCULATETABLE(ALLSELECTED ( cal_start_dates )), cal_start_dates[Date]) // get the selected start dagte
			Return res
			
			
			```
		formatString: General Date
		lineageTag: 5d852ccf-922b-4cb7-be6a-ebb1a108c831

	/// Column Date.
	column Date
		formatString: General Date
		lineageTag: e292d391-2e45-4024-8177-05337f8ae572
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		variation Variation
			isDefault
			relationship: d7ce477d-fdc8-49b6-bdd1-bec68fc4d16d
			defaultHierarchy: LocalDateTable_64251fda-5098-4d5c-a76a-3f9e72cb0712.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column date_as_integer.
	column date_as_integer
		lineageTag: 74ea12fb-7a88-4d81-84ab-406dab2550b7
		summarizeBy: none
		isNameInferred
		sourceColumn: [date_as_integer]

		annotation SummarizationSetBy = Automatic

	/// Column year.
	column year
		formatString: 0
		lineageTag: b6d1fe74-c00d-4760-8a77-3d543dfeaef6
		summarizeBy: sum
		isNameInferred
		sourceColumn: [year]

		annotation SummarizationSetBy = Automatic

	/// Column month_number.
	column month_number
		lineageTag: 7aae1aef-b3c3-4261-a414-08e0a5c6c3f1
		summarizeBy: none
		isNameInferred
		sourceColumn: [month_number]

		annotation SummarizationSetBy = Automatic

	/// Column year_month_number.
	column year_month_number
		lineageTag: cd8e6483-b0c9-4dca-93b8-b69bebc22cf0
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_month_number]

		annotation SummarizationSetBy = Automatic

	/// Column year_week_number.
	column year_week_number
		lineageTag: cabfaa9d-1640-416a-9095-35b5d107ca0b
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_week_number]

		annotation SummarizationSetBy = Automatic

	/// Column year_day_number.
	column year_day_number
		lineageTag: 56cdd24a-08ff-4f26-8376-aea2a7895e6d
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_day_number]

		annotation SummarizationSetBy = Automatic

	/// Column year_month_short.
	column year_month_short
		lineageTag: a35c3b85-1140-4f81-99fb-f6fb209636e5
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_month_short]

		annotation SummarizationSetBy = Automatic

	/// Column month_name_short.
	column month_name_short
		lineageTag: e3058241-2980-4b0f-8ac4-9c8510eb86ea
		summarizeBy: none
		isNameInferred
		sourceColumn: [month_name_short]

		annotation SummarizationSetBy = Automatic

	/// Column month_name_long.
	column month_name_long
		lineageTag: fcd56e2b-1a9e-4cfd-b883-9a1d442801df
		summarizeBy: none
		isNameInferred
		sourceColumn: [month_name_long]

		annotation SummarizationSetBy = Automatic

	/// Column day_of_week_number.
	column day_of_week_number
		formatString: 0
		lineageTag: 2c589fec-a119-4348-8eef-3644c518ff2c
		summarizeBy: sum
		isNameInferred
		sourceColumn: [day_of_week_number]

		annotation SummarizationSetBy = Automatic

	/// Column day_of_week.
	column day_of_week
		lineageTag: 3712e823-bcac-42b6-8682-8038fd18af7b
		summarizeBy: none
		isNameInferred
		sourceColumn: [day_of_week]

		annotation SummarizationSetBy = Automatic

	/// Column day_of_week_short.
	column day_of_week_short
		lineageTag: 2831509d-9ec3-41d5-946a-8db0c72976e7
		summarizeBy: none
		isNameInferred
		sourceColumn: [day_of_week_short]

		annotation SummarizationSetBy = Automatic

	/// Column quarter.
	column quarter
		lineageTag: 4419e8dc-318f-4d24-bcc6-3afc57c46623
		summarizeBy: none
		isNameInferred
		sourceColumn: [quarter]

		annotation SummarizationSetBy = Automatic

	/// Column year_quarter.
	column year_quarter
		lineageTag: 8eda9987-ce6d-4648-9d19-581757f18461
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_quarter]

		annotation SummarizationSetBy = Automatic

	/// Column first_of_week_date.
	column first_of_week_date
		formatString: General Date
		lineageTag: 1b2e2619-219a-4072-80a2-186a18557e65
		summarizeBy: none
		isNameInferred
		sourceColumn: [first_of_week_date]

		variation Variation
			isDefault
			relationship: dfde6312-b575-4ccf-b45c-2f8935daa805
			defaultHierarchy: LocalDateTable_f6b32d38-f776-4a05-bf96-8d6746a94ef1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column first_of_month_date.
	column first_of_month_date
		formatString: General Date
		lineageTag: 5fc2e463-5686-439a-bbcb-db1866d7db4e
		summarizeBy: none
		isNameInferred
		sourceColumn: [first_of_month_date]

		variation Variation
			isDefault
			relationship: 2acf2e3a-d5de-46f6-9142-3e73c55e3911
			defaultHierarchy: LocalDateTable_cd821b5b-2623-43e4-b67f-57d579fc400e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column first_of_qtr_date.
	column first_of_qtr_date
		formatString: General Date
		lineageTag: 9edd31e2-5101-4a05-8b66-645cba8c5eed
		summarizeBy: none
		isNameInferred
		sourceColumn: [first_of_qtr_date]

		variation Variation
			isDefault
			relationship: ab35bc36-2dcb-4ecf-8219-32b8e7118354
			defaultHierarchy: LocalDateTable_eac03e5a-b6e1-46fa-8ca6-cef33f39ff4d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column first_of_year_date.
	column first_of_year_date
		formatString: General Date
		lineageTag: b99342a4-79b7-4c56-a387-f77b1438d71e
		summarizeBy: none
		isNameInferred
		sourceColumn: [first_of_year_date]

		variation Variation
			isDefault
			relationship: 411b2aa7-4d01-4b61-a661-7b1fb2a0cf57
			defaultHierarchy: LocalDateTable_82a62bb9-fee2-48e0-b573-28db66754990.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition cal_start_dates-ed59135e-9d02-4178-b470-7aef50310dc6 = calculated
		mode: import
		source = ```
				
				var min_date =  MAX(date(2000,01,01) ,  min(ssr[_sys_filt_start_date])) // get the first date that we have data for but never before 2000
				var max_date = max(ssr[_sys_as_of]) // get the last date (as _of) that we have data for
				var cal_tbl  =ADDCOLUMNS (
				CALENDAR (min_date, max_date),
				"date_as_integer", FORMAT ( [Date], "YYYYMMDD" ),
				"year", YEAR ( [Date] ),
				"month_number", FORMAT ( [Date], "MM" ),
				"year_month_number", FORMAT ( [Date], "YYYY/MM" ),
				"year_week_number", FORMAT ( [Date], "YYYY/0w" ),
				"year_day_number", FORMAT ( [Date], "YYYY/ddd" ),
				"year_month_short", FORMAT ( [Date], "YYYY/mmm" ),
				"month_name_short", FORMAT ( [Date], "mmm" ),
				"month_name_long", FORMAT ( [Date], "mmmm" ),
				"day_of_week_number", WEEKDAY ( [Date] ),
				"day_of_week", FORMAT ( [Date], "dddd" ),
				"day_of_week_short", FORMAT ( [Date], "ddd" ),
				"quarter", "Q" & FORMAT ( [Date], "Q" ),
				"year_quarter", FORMAT ( [Date], "YYYY" ) & "/Q" & FORMAT ( [Date], "Q" ),
				"first_of_week_date",    [DATE] -WEEKDAY([DATE])+1,
				"first_of_month_date",  Date(year([Date]),Month([date]), 1),
				"first_of_qtr_date",  Date(year([Date]), 
				    SWITCH( Month([date]) , 1, 1, 2,1,3,1,4,4,5,4,6,4,7,7,8,7,9,7,10,10,11,10,12,10)
				,1),
				"first_of_year_date",  Date(year([Date]),1, 1)
				
				
				)
				
				
				return cal_tbl
				```

	annotation PBI_Id = 13d47d900d504cfe87f6c8586c28a4df

