/// Table DimDiscountTier.
table DimDiscountTier
	lineageTag: d1e7c278-7137-41ac-bc16-0582c183411d

	/// ?? Purpose: Compute the measure result from the DAX expression.
	/// ?? Dependencies: See model references
	/// ?? Dynamic Behavior: Respects current filter context.
	/// ?? Format/Type: Text
	measure 'meas._debug_fmt' = 
			
			SELECTEDMEASUREFORMATSTRING()
		lineageTag: afa61a44-37da-429c-86ea-b496b23bc27c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// ?? Purpose: Compute the measure result from the DAX expression.
	/// ?? Dependencies: See model references
	/// ?? Dynamic Behavior: Respects current filter context.
	/// ?? Format/Type: Text
	measure 'meas._test_number' = 1234567
		lineageTag: 20d49b41-72fd-47ec-bc75-85d87b5589f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// ?? Purpose: Compute the measure result from the DAX expression.
	/// ?? Dependencies: See model references
	/// ?? Dynamic Behavior: Respects current filter context.
	/// ?? Format/Type: Whole number
	measure 'meas._debug_force_number' = 123456789
		formatString: 0
		lineageTag: faff23ba-fe38-43f1-a139-c0c92547e0e1

	/// ?? Purpose: Compute the measure result from the DAX expression.
	/// ?? Dependencies: See model references
	/// ?? Dynamic Behavior: Respects current filter context.
	/// ?? Format/Type: Text
	measure 'meas._debug_force_format_string' = SELECTEDMEASUREFORMATSTRING()
		lineageTag: 91ffa358-58aa-44a9-ab83-08206caed3ae

	/// ?? Purpose: Compute the measure result from the DAX expression.
	/// ?? Dependencies: See model references
	/// ?? Dynamic Behavior: Respects current filter context.
	/// ?? Format/Type: Text
	measure 'meas._debug_force_format_source' = 
			
			IF(
			    ISBLANK(SELECTEDMEASUREFORMATSTRING()),
			    "NO FORMAT",
			    "FORMAT APPLIED"
			)
		lineageTag: 9da28072-fae9-43ec-ba72-05729747f739

	/// ?? Purpose: Compute the measure result from the DAX expression.
	/// ?? Dependencies: See model references
	/// ?? Dynamic Behavior: Respects current filter context.
	/// ?? Format/Type: Text
	measure 'meas._debug_selected_format' = 
			
			SELECTEDVALUE(metadata_performance_metrics_old[metric_format])
		lineageTag: ccb9e224-3654-43b5-af52-7f92e3b88925

	/// Column trueai_discount_pct_tier.
	column trueai_discount_pct_tier
		lineageTag: 3880bd55-15c2-4d7d-ba2f-271e04aaaefc
		isDefaultLabel
		summarizeBy: none
		isNameInferred
		sourceColumn: opps[trueai_discount_pct_tier]
		sortByColumn: SortKey

		annotation SummarizationSetBy = Automatic

	/// Column CleanLabel.
	column CleanLabel
		lineageTag: 692944ff-0505-4c76-8019-6108e675f9f8
		summarizeBy: none
		isNameInferred
		sourceColumn: [CleanLabel]

		annotation SummarizationSetBy = Automatic

	/// Column TierStart.
	column TierStart
		lineageTag: a9f87cc7-c69c-4c28-9a42-93699b4c91c0
		summarizeBy: none
		isNameInferred
		sourceColumn: [TierStart]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column TierEnd.
	column TierEnd
		lineageTag: 8942837c-7e67-448d-98cb-ac33466db44a
		summarizeBy: none
		isNameInferred
		sourceColumn: [TierEnd]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column SortKey.
	column SortKey
		lineageTag: 5b27784c-bb4f-4cee-8b23-f71530ccddfc
		summarizeBy: none
		isNameInferred
		sourceColumn: [SortKey]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimDiscountTier = calculated
		mode: import
		source =
				
				VAR Tiers =
				    DISTINCT ( opps[trueai_discount_pct_tier] )
				RETURN
				ADDCOLUMNS (
				    Tiers,
				
				    -- Clean label (remove special chars)
				    "CleanLabel",
				        VAR Raw = opps[trueai_discount_pct_tier]
				        VAR Step1 = SUBSTITUTE ( Raw, "%", "" )
				        VAR Step2 = SUBSTITUTE ( Step1, "+", "" )
				        VAR Step3 = SUBSTITUTE ( Step2, "<", "" )
				        VAR Step4 = SUBSTITUTE ( Step3, ">", "" )
				        VAR Clean = SUBSTITUTE ( Step4, " ", "" )
				        RETURN Clean,
				
				    -- TierStart
				    "TierStart",
				        VAR Raw = opps[trueai_discount_pct_tier]
				        VAR Step1 = SUBSTITUTE ( Raw, "%", "" )
				        VAR Step2 = SUBSTITUTE ( Step1, "+", "" )
				        VAR Step3 = SUBSTITUTE ( Step2, "<", "" )
				        VAR Step4 = SUBSTITUTE ( Step3, ">", "" )
				        VAR Clean = SUBSTITUTE ( Step4, " ", "" )
				        VAR Dash = FIND ( "-", Clean, 1, 0 )
				        RETURN VALUE (
				            IF ( Dash > 0,
				                LEFT ( Clean, Dash - 1 ),
				                Clean
				            )
				        ),
				
				    -- TierEnd
				    "TierEnd",
				        VAR Raw = opps[trueai_discount_pct_tier]
				        VAR Step1 = SUBSTITUTE ( Raw, "%", "" )
				        VAR Step2 = SUBSTITUTE ( Step1, "+", "" )
				        VAR Step3 = SUBSTITUTE ( Step2, "<", "" )
				        VAR Step4 = SUBSTITUTE ( Step3, ">", "" )
				        VAR Clean = SUBSTITUTE ( Step4, " ", "" )
				        VAR Dash = FIND ( "-", Clean, 1, 0 )
				        RETURN
				            IF (
				                Dash > 0,
				                VALUE ( RIGHT ( Clean, LEN ( Clean ) - Dash ) ),
				                IF ( RIGHT ( Raw, 1 ) = "+",
				                    1000000,
				                    VALUE ( Clean )
				                )
				            ),
				
				    -- SortKey (local recalculation)
				    "SortKey",
				        VAR Raw = opps[trueai_discount_pct_tier]
				        VAR Step1 = SUBSTITUTE ( Raw, "%", "" )
				        VAR Step2 = SUBSTITUTE ( Step1, "+", "" )
				        VAR Step3 = SUBSTITUTE ( Step2, "<", "" )
				        VAR Step4 = SUBSTITUTE ( Step3, ">", "" )
				        VAR Clean = SUBSTITUTE ( Step4, " ", "" )
				        VAR Dash = FIND ( "-", Clean, 1, 0 )
				        VAR StartVal =
				            VALUE (
				                IF (
				                    Dash > 0,
				                    LEFT ( Clean, Dash - 1 ),
				                    Clean
				                )
				            )
				        VAR EndVal =
				            IF (
				                Dash > 0,
				                VALUE ( RIGHT ( Clean, LEN ( Clean ) - Dash ) ),
				                IF ( RIGHT ( Raw, 1 ) = "+",
				                    1000000,
				                    VALUE ( Clean )
				                )
				            )
				        RETURN StartVal * 1000 + EndVal
				)

	annotation PBI_Id = 1477bee9ac284f8a920b7c8d0ee3d5e9

