/// Table DimDiscountTier.
table DimDiscountTier
	lineageTag: d1e7c278-7137-41ac-bc16-0582c183411d

	/// Measure meas._test_number.
	/// Purpose: Returns the measure value from its DAX expression.
	/// Calculation Logic: Uses the DAX expression as written.
	/// Dynamic Behavior: Respects current filter context.
	/// Format/Type: Unspecified
	measure 'meas._test_number' = 1234567
		lineageTag: 20d49b41-72fd-47ec-bc75-85d87b5589f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.debug_kpi1_score_name_dbgf' =
			
			SELECTEDVALUE(metadata_heatmap_items[heatmap_kpi1_ai_score_name], "<blank or multi>")
		lineageTag: 2c09cfd4-7369-4e51-9a16-fdc605450b19

	/// Column trueai_discount_pct_tier.
	column trueai_discount_pct_tier
		lineageTag: 3880bd55-15c2-4d7d-ba2f-271e04aaaefc
		isDefaultLabel
		summarizeBy: none
		isNameInferred
		sourceColumn: opps[trueai_discount_pct_tier]
		sortByColumn: SortKey

		annotation SummarizationSetBy = Automatic

	/// Column CleanLabel.
	column CleanLabel
		lineageTag: 692944ff-0505-4c76-8019-6108e675f9f8
		summarizeBy: none
		isNameInferred
		sourceColumn: [CleanLabel]

		annotation SummarizationSetBy = Automatic

	/// Column TierStart.
	column TierStart
		lineageTag: a9f87cc7-c69c-4c28-9a42-93699b4c91c0
		summarizeBy: none
		isNameInferred
		sourceColumn: [TierStart]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column TierEnd.
	column TierEnd
		lineageTag: 8942837c-7e67-448d-98cb-ac33466db44a
		summarizeBy: none
		isNameInferred
		sourceColumn: [TierEnd]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column SortKey.
	column SortKey
		lineageTag: 5b27784c-bb4f-4cee-8b23-f71530ccddfc
		summarizeBy: none
		isNameInferred
		sourceColumn: [SortKey]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimDiscountTier = calculated
		mode: import
		source =
				
				VAR Tiers =
				    DISTINCT ( opps[trueai_discount_pct_tier] )
				RETURN
				ADDCOLUMNS (
				    Tiers,
				
				    -- Clean label (remove special chars)
				    "CleanLabel",
				        VAR Raw = opps[trueai_discount_pct_tier]
				        VAR Step1 = SUBSTITUTE ( Raw, "%", "" )
				        VAR Step2 = SUBSTITUTE ( Step1, "+", "" )
				        VAR Step3 = SUBSTITUTE ( Step2, "<", "" )
				        VAR Step4 = SUBSTITUTE ( Step3, ">", "" )
				        VAR Clean = SUBSTITUTE ( Step4, " ", "" )
				        RETURN Clean,
				
				    -- TierStart
				    "TierStart",
				        VAR Raw = opps[trueai_discount_pct_tier]
				        VAR Step1 = SUBSTITUTE ( Raw, "%", "" )
				        VAR Step2 = SUBSTITUTE ( Step1, "+", "" )
				        VAR Step3 = SUBSTITUTE ( Step2, "<", "" )
				        VAR Step4 = SUBSTITUTE ( Step3, ">", "" )
				        VAR Clean = SUBSTITUTE ( Step4, " ", "" )
				        VAR Dash = FIND ( "-", Clean, 1, 0 )
				        RETURN VALUE (
				            IF ( Dash > 0,
				                LEFT ( Clean, Dash - 1 ),
				                Clean
				            )
				        ),
				
				    -- TierEnd
				    "TierEnd",
				        VAR Raw = opps[trueai_discount_pct_tier]
				        VAR Step1 = SUBSTITUTE ( Raw, "%", "" )
				        VAR Step2 = SUBSTITUTE ( Step1, "+", "" )
				        VAR Step3 = SUBSTITUTE ( Step2, "<", "" )
				        VAR Step4 = SUBSTITUTE ( Step3, ">", "" )
				        VAR Clean = SUBSTITUTE ( Step4, " ", "" )
				        VAR Dash = FIND ( "-", Clean, 1, 0 )
				        RETURN
				            IF (
				                Dash > 0,
				                VALUE ( RIGHT ( Clean, LEN ( Clean ) - Dash ) ),
				                IF ( RIGHT ( Raw, 1 ) = "+",
				                    1000000,
				                    VALUE ( Clean )
				                )
				            ),
				
				    -- SortKey (local recalculation)
				    "SortKey",
				        VAR Raw = opps[trueai_discount_pct_tier]
				        VAR Step1 = SUBSTITUTE ( Raw, "%", "" )
				        VAR Step2 = SUBSTITUTE ( Step1, "+", "" )
				        VAR Step3 = SUBSTITUTE ( Step2, "<", "" )
				        VAR Step4 = SUBSTITUTE ( Step3, ">", "" )
				        VAR Clean = SUBSTITUTE ( Step4, " ", "" )
				        VAR Dash = FIND ( "-", Clean, 1, 0 )
				        VAR StartVal =
				            VALUE (
				                IF (
				                    Dash > 0,
				                    LEFT ( Clean, Dash - 1 ),
				                    Clean
				                )
				            )
				        VAR EndVal =
				            IF (
				                Dash > 0,
				                VALUE ( RIGHT ( Clean, LEN ( Clean ) - Dash ) ),
				                IF ( RIGHT ( Raw, 1 ) = "+",
				                    1000000,
				                    VALUE ( Clean )
				                )
				            )
				        RETURN StartVal * 1000 + EndVal
				)

	annotation PBI_Id = 1477bee9ac284f8a920b7c8d0ee3d5e9

