table heatmap_graphics
	lineageTag: 72fd232e-e375-4bf2-be4e-fac7a282cc80

	column _sys_base64
		dataType: string
		lineageTag: 04a3dd89-4920-47c9-b386-3ecc98b919cc
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: _sys_base64

		annotation SummarizationSetBy = Automatic

	column _sys_dimensions
		dataType: string
		lineageTag: 3b22d8a1-ed52-4ffd-9531-6e5cb45f6f83
		summarizeBy: none
		sourceColumn: _sys_dimensions

		annotation SummarizationSetBy = Automatic

	column _sys_doc_id
		dataType: int64
		formatString: 0
		lineageTag: 0bc2e776-d489-451d-9ab3-03e669b08c69
		summarizeBy: sum
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_name
		dataType: string
		lineageTag: 5cbb2b4c-cc13-4157-8886-fd076111947a
		summarizeBy: none
		sourceColumn: _sys_name

		annotation SummarizationSetBy = Automatic

	column _sys_url
		dataType: string
		lineageTag: 94ce15ff-8935-41f6-bdc0-2d85f57c55a4
		summarizeBy: none
		sourceColumn: _sys_url

		annotation SummarizationSetBy = Automatic

	column notes
		dataType: string
		lineageTag: b33f9213-5481-47ac-a03f-e56ac6e56794
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: ad8c6f4b-219d-4c3d-be5c-99b7abccde06
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition heatmap_graphics = m
		mode: import
		source =
				let
				    // JSON data as a single text string
				    jsonText = "
				    [
				        {
				        ""_sys_base64"": ""data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsSAAALEgHS3X78AAAH0ElEQVR4nO1bW2yURRQ+rjyYcGmNDxDbxGZpNrYPdp9aIolUF+HJWIovovSSGC1FpV5atYIgIEIbtV6o8iJLCTzZbRsxEezKJcG05cFdHqzZyAoJNfBgpFwS32q+v\/Nv\/p3\/dmb+f7kkfskm2+7\/z8w5c86Z75yZuW9ubo5KjXQu30hE+JQTUVx0h+914nuWiK6J7xnx\/VQiFj1V6rGVRAHpXL6KiJqIqM0ipC6gnCQRjSZi0YthjzU0BaRz+XIhdFcIQrsByhgQyrim10QxAitACN4lPmVhDIqBWaGIgaCKCKSAdC4PE99BRI8EGUQAXEL\/iVg0qduElgKEj6PTVaWRSxmnEW90YkRE9YV0Lt8kIvXdIjyJsWTE2JSgpIB0Lg9zH7mNvq4CjGlEjJENtgukc3mYfOtdICgHhxKxaBvnQZYF3GPCA61izL7wtYBSCH9l5jJdnZkp\/L20ooKWVVSG2YUJX0vwVEA6l8dauyXICG5ev05nx3+i7NQEXZiepgu\/T7s+u\/zRGlpeU0N19Sto5eqnadGSJUG6NvFhIhZ1jQuuChARdUS31+zUJA0nv6Vf0uO6TdCadc20tvk5qqtv0G5DYF0iFh11+sFRAWKdz+hE+wvTv9H+Pbvp\/NSk9mhlPFbfQD17+4K4CZhj3IknuAXBpI7wQ19+Tq80PROq8ADae\/GpVUb7migTMtlgswBBbw+q9AM\/f2vjBk\/\/dgPMvOW1LUZQzE5OGPHCqx1Yw8793+jGh3aZNhcpQCQ2F1VmHyb\/QWcHXf1rhvG0HS2vvm4owAqsEqnkQTo+Mky3btywvYNg+cnhozpKgCtUWRMo2QWUMjrM\/JsbN2gL7wb4euf72+jIz2fo8cRq21OwEFgc+ldEmZCxgIIFqM5+ELO34sDo97S8ptbzGbhF37vdNmvQtIQiK7BaQJPK7A\/u2RVY+O6P+3yFB8AJPj18lBYuXlz0f\/SvERjLhKwGrApgJxGYkRMjKdWObVjbvJ79LBTlpITUUNLgHIoouIGhgHQuH1cpagx+tEtZ2DAAJewcPGBrqe+dbtXW64TMBQtgZU4k1vqwg54KwAqxcliB8RxPDas2ZchsKqCR+5ZGR67QJTZOcUOjLUPmiIj+rCoufD\/M2R\/66guDR3AB5b\/w5BO0fXOH7Q2MSzEWwA3KI5aNCl+cHT8RVGYbbjoQHSdAuP73ejwn4HjqO9Xu4wtUzB8WoAtQ2LjI6ky6C5KDWgBLAZMTjGeUV4NGKKCK8yRMVSYiEICb7lr5u0x9OVjIIDuwDtBohayxKsJVwJWZYtPDetyzt99gY36AooIWN0CGOLg6oxSjDAWUc56UgxUiMYRCnr70YW8zhpUMH1JKMG3ArHKUzXEVKyK6+3iLBCODIg6MHaNNvVsNP3fD13t2GxFcg7UVsEaBOTKxaoHum9WWtRiWsL613fggSYKQWDEQ7KxxAz6KBAoWU9fQYNT+llUW+6tXgRRuAEWGCW0FuKWiUAYGavqsUyYHRSCXcMsnnGoEJNwACRSWw7CgvDVm4g9mJghFdPZuU2obBMkt30ACZWSRjHjAQUTsuSvjlkIxQiXrM4EsD0uaW3uIO6PnfrVlh5zl0oLTEcvRFE\/UNawo+jloLYADDvGSuUk1o75gBVsBTowtCDPkwM\/KnFYURde4GBH1f18gAMnrfSlyAyv8zFnuH8IrEi6+AsiBjcECuIVJP7LE6c8Kc8vNCo0dpAwUwD6KJgcz+F+KyfB69vUrjQyR3ovTo1\/Z\/5vb2pX6gOwRUR1lrQRgfTLbA8XlWAFmx6nELQOWgkqv18qB1UGm1hiX4tZZFrKbPIBtBa0SQcEsgOhwgORJXraswC4Rljc\/UwZHkGdfHhcDhsymAtinrDA42Qq4yQ4ClFsqjJkHYfILYuhHTsExHg3\/N2Q2FJCIRTPiyBkLm3u32h4DR+fUC93WaSjGT3i0L+cC82l5H3foJi4JmYuo8AD3bcSCTQ5KAEfXLZoiOfIC2nXKAWA1GtvmBVmtCkiKbSMWkPnBZ2VgkPBRlX275pY2VyHQDmKMk\/DzByiUafas1eXv37FjfkMo+tCD\/\/759z8PqNQIV65eY0RkmRZPZzN08odjVF1baxMMf5vvwHyff7mDXnrbObvDOr+9s4POn5uy\/QbhEVQ1sC8Ri\/5ovhZ4exzADLmltmBnza3t7DM\/JsHx2oAJILxte9zpgAT2zT5TbRkDRhrrBbMyvLSisqgQcuUyTo1dpszUpO\/pErdaARNvJGLRoljndkYoo1MqQ3KCfbpSbJ1hmQSbDHBgCsTHtgfiVhBpUwmIJjC4IyfPGLPkRXhUgHbQHtoNIPys2\/6n1zE55bNCVpi+DM6uUzswY4dOMcUBtrNBJvwOSoZyShRRH7s2KK2jlIY836oUk1lWGwcla8M8JEl+p0U5R2VxwPDZsEZzmzGWiEU9j9BziqJtunXDO4ws59yDrwLEmglyNHYPCY+xNnLuEyldmblHjs2z7woASvsCouF2nSXyNmBWRHu28IDupam4SChKdT9QFVlxaYpd3zQR9Npclzhed6fuEM2Ka3PsVF7G\/xcnQ7462yWWnlJdpLwkXC+w4CZKdXm6URxHbQpBGRAaZCyp4+N+KPn1eXH7BEETH7PYgu+yu8CsTQFRscX3TClujBdARP8BNN2anciv+i8AAAAASUVORK5CYII="",
				        ""_sys_dimensions"": ""65x65"",
				        ""_sys_name"": ""growth_segm_sam"",
				        ""_sys_url"": ""https:\/\/res.cloudinary.com\/cien\/image\/upload\/v1739809800\/SegmSAM_v3cg17.png"",
				        ""notes"": ""PBI Reports"",
				        ""category"": ""Segmentation & SAM"",
				        ""_sys_doc_id"": 1
				        },
				        {
				        ""_sys_base64"": ""data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABBCAYAAABhNaJ7AAAACXBIWXMAAAsSAAALEgHS3X78AAAGKUlEQVR4nN1cP3MbRRR\/59GEythFqMKMhDsqi4oKImZMRWaiUNFF\/gBRxDcQnwBFXyByBVU4z5CKFLpQQcO5oiLIM1CRwiIVNMf8bnetvdPe7d+TJX4zGkvy3d77\/96+3VWUZRltHMOop3zkNJtvmpRmBTCMOkTU4y+8v2t4Z0JECyKa569ptmiKxPACYEyPiKhPRO1Ao14SUUxEk9DCCCeAYdTnjJtq2RUJF0QcYjB\/ATB\/ngXUtilgFQPfuOEuAGbqsw1oXIeEC8LJNfacHjmMYOrpFjBPnIaU02QNOwsYRodc6\/cbYsYX59warkzHMRcAYx7+dnwzvBnjIk+7hkIwc4Fh1OV5eduZJ07jgtOshV4AbCBo\/qBpygPiIKfZQAj1LsDMPr2BFBcKSJXdOnfQWcB8h5knTnttnVAtgGE02xGf1+GYhtGk6hq1C7Cy9rubo7kRPFCVz+sCYH6\/2LGgZ4JlPiMtxQOVC4z\/h8wT52lc\/rJoAay+\/33DhG0a78nzhlbp4WsSssHVP0Tp69UNvTthWVv8TbR4w94f3iLqvuM0zDgvlzlWFuCp\/fFPRJOUaPnv6ruDW0SzT4n6R66jMkCw\/edEyZ\/F7+\/eIZqdEHXeth7y2grkGOCs\/dFLoq9+LjIP4POD50SzX11HZsz3nq0zD+C77jfsGluSxRtZAH0XAmGWTy40T3vpRGQOWNXF6+r\/Q8ijH62HvXYBJgCW950iv4l2QeRcocFQ48e\/WQ97wHm+tgAn7QNpjXYK1\/3lNv7lG\/01ZdczRBgBdPbNrjt8y\/UJjSFfm2jxKaNz4WOailSZAG4x\/2M1DtJmWVD3j4jOX9WPfXzblNoC2sh8rXy66IHB+\/pABSbkVBW\/YoFRZd6Pj4nGH64EMerqBTD52Jn+3h5fsfHC\/PNqLYhcLYCghtRY5dvIKEh7ImvAKp6eqK8F8D+PgqsTZY\/y+XKQ7i6Yg3ZBPDQOwmAhAjD5T54V72nvs2vLeR5WE3+2+ox0C0sTQbd7m1mHQxEkIwkqAB3kggZVYnxvpT0IbfCiaO6\/fOFc7poiafm6AAiH1qGhMqAdaApM4DpZy\/Bb2XTh83AVVHbCPTCuuBfWU5VKEWAdBZUHQeeWFwgc\/KDPw9mj9XpBdg0BCAHMiMpSFE+o9M5qCiKU4XAZCNAy3bbdVoY48whmjkVIJVQMmNQacB1MmGzhLABo3hRwjzITVaWxXPoKFzEto+FithOvPd4qsgIeYqN5MIB40JaE0P9+3acRBOX02HuX\/bUpo5EpLLDc431\/K6gCnglRcsECAX7wLcsMMN3OrOjnqB9gAbbCrivIFEidXMC2rgdREAIC3MNS8IPZwn9lzeeNlBMW\/dFosQHutUHLZZl7xItnlzl+3sHZX+8eCchdHriOKlvUwbL7lKIQQnfka3tW\/KCqHzzyuSu+bLnEgBCAG9lqtwGkrCk6jBrfLChrXJfWRAXZP\/Ku9esxzSIhgEbnA6qOsSkQEyYfNeIa5zTN+iILBNlyVga0jtpe1TE2BbIE0qVPZ7kC+aqxWBiJQwdC0c4u52WR3+uAeQM6RbLQTl+wvwHjRq50eWEkDrn5CR0fuV3usogB14H1CCDHLwZB+ou5+eONXAjNvIflKK8VYKaGrpFtQENrTO4GwSJsC6MKXPO6EgBbO78MMXosNTVEVecKmLxcPcaa\/qABLuV9AqrF0ae+TyinOZdpqgy54kTJjM8eblBYAlRtkEh9t8aAYV0n1wcerbKEplnhrIJqMuS05VQGTN6xV68FYoJHTaDZICHANhU99iEUZmo5N9cCjHsstT+habam3CoB7Mq2WFNUbp9V9wPYhQOXbtEWYlm3gbq6ITLNUnkdfYcx4LwoUd8RYvnydIeZP9UdrdG3xKbZbEeFcMppr4VZT3D3hGDEPGB7YqTHZ1HbupFymW\/2sDhIZdcVZgN3+UGlbUPCt8ZbnSLzOTU25lXjTVvDkp8jdNrm53dukG2uxIMfug\/ihbP8+R6nScOcHGWxYbTB02Rn+Zw+wGHrsGeHmzk3LNDI+eHmTo+z3Wd9vh3NteOc8DlJXFfN+WBzvx\/ABIJJlvq3A1YAw1dNMVwAEf0HxWFoh5jCzIQAAAAASUVORK5CYII="",
				        ""_sys_dimensions"": ""65x65"",
				        ""_sys_name"": ""growth_coaching"",
				        ""_sys_url"": ""https:\/\/res.cloudinary.com\/cien\/image\/upload\/v1739809799\/repperf_iptizx.png"",
				        ""notes"": ""PBI Reports"",
				        ""category"": ""Rep Performance"",
				        ""_sys_doc_id"": 5
				        },
				        {
				        ""_sys_base64"": ""data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABBCAYAAABhNaJ7AAAACXBIWXMAAAsSAAALEgHS3X78AAAFxklEQVR4nN1cPXAaRxR+x1C5EYXTRqiLK5GkdoyrpDNOTcakscugNk5BEacNat0Ija5OUBdXRkkbj6GKO0HaqIDG7WW+e7tiOe64vdt3B+ibYQ7t7i373r7f\/ZEXBAGVAt9rElFdfYAGEdXU9zkRjdX3afhpB6MyhlUcA5jgFhHheZyzlwkRgRHDohgiywDfw+x2iahDRAdyHYdYENGAiPrUDqZSncowgGe7R0SPJAZlgavw9wSkwo0BPOODEgmP4iqUNgeJqOT+ad\/DjF9vkXhSv32txpIL2SWAZ33oYNiKwiQ0uhmlIZsE+F5LuatdI57UmMZqjNawZ4DvwbL\/XoB1l8RBOEYeqxXsGMAdnu0w4VGc2TIhnQH7R7yGFRM2M2B\/iddIZUKyF\/C9hgpDd1nnbbAIw\/F2MI5rG88A36spa3+4\/fGLYKKYMI92lqQCvTtEPCkXGRssrUsAx\/VvSxpY2XgczR\/iJKB\/J0lnrNG2ygC2mLsY5UnhOOoVVlXA96YSuj\/4i+j715vbHNwjGv1I1Cjf0syoHehVKUMCmDPOw5l\/JOr66e0WH4mav9j3O70hGv3DT0ccmvlC1ejLOn7ehJqa2SgTwJjJv+tMsEFUon74mqjfdhpmV2W0SgU4xb12Iz0ZIL75ap0BQHCx+V3M+NHJevn7n53V5wips1aBTClkFmwi3gbT\/+IbQR0cEdJcKAPiiD97nq2P+ifx5c0HbmOLMkB8WSuJ+M7DbP3U77POm3j2UMR7hDR7wQWJR35pxHvfLcvTbIDGeMZij5kXdJ2Pq2qHRgxSMx8FiC4gZmhUjK0qZ9gSjyDIfJJydbUXLB31E55xjeE7LkMd2qCtEOoVKQnIMvOIEw7v85OURYef13HB7Iao1V\/223nNZaRiB7QVCIiARv59AQNZxR6iPP11KdJxLg0EQwrwiQuYhn9LjJy9gJMHkND52r34crjApDohe+AmAVIGr\/PVqj0gFe6CeBD66LPVuuNPReIA4ABuMNfmoLS1R3\/9P\/g7Zj7aD+rQBkwBw5IkIytyM6DxUt7VbQPVMD\/OkQbnIR7uTM8yRLj37bIOhlDPMiQA2Z6eZVj87sVSAvCekA2YVNWRlMzdab2EONoS\/9RYkLr6wE8QM1VuT1t71CEJGr3kv6FqM8PtjT6wFxFQg3nVolEs9OBsoWfeRP8NM2Dw57qrC5lww4yYRXw+2oKhAio3r6jNj72DkBEcV5QKFI7uN+u\/0FVZXpwbhIohE4StQNRoAm2F3OAYXqDQ1SATLkaw9xurg7ARPNJLYiKrwXuGcHVYG0HYgWcS48cs60wOol03xBflqCclAaYYbyEQCm2floCWOv3hhOjqrbn2D+I\/\/2m1dx0\/hGJ\/suoJzJVfuEHtNkmFwuNXzgx4Su1gyLlAOxiqbWQnQE9NgCC4OoqpM8vi3ODpG2YMGGcSTyoI05KUEwtF88rW2MCVAVF\/Tcaq7jwmpdVlcXX63aS6pHJL3NJqMsB5U\/TJF+tlrS\/5Gee2NtXB9ellsKiLTHonA25pXTKAz9edu\/Q6eLGaukKPtf+H6zJXd9HuVscfsD3QhIL4YZe\/w9gNni9jAbRB23okNsiAc\/MsYXRztLSYYIs4MhmwuiDCFad3mPjT6EnSuBWhnoRH2EHM4o7JrDOADxKJ7BTvGDr2h6TYR94lVThNuluw+bS47+3qwegsmFA7SNz7SFsVbqozdvuKiaIhEen3Bdg1jvfwxOgi3PVKuT+Qvi\/AHeybJOiToamLPfY3Rvj47GgPbELisdg42O8McYdN13C5YJxnIR7Id2uMj9T1d8guLMKTX+0gc0abb2+Qfwiu5TLX+7K4VMYuVzrvfnGy\/EuTGiKXJ+WuzjIjkMQ+kekwEZfq+qzIfob85WmOG1oqn5DyGBO1ijOUvDcMFHt9npnRVPZCf9IM50IFXvozkibaRHn\/P8AEMyZ6OAv\/M6CUXapbENH\/SClwWkkFesIAAAAASUVORK5CYII="",
				        ""_sys_dimensions"": ""65x65"",
				        ""_sys_name"": ""growth_existing_customer"",
				        ""_sys_url"": ""https:\/\/res.cloudinary.com\/cien\/image\/upload\/v1739809799\/existing_yeaoch.png"",
				        ""notes"": ""PBI Reports"",
				        ""category"": ""Existing Customers"",
				        ""_sys_doc_id"": 4
				        },
				        {
				        ""_sys_base64"": ""data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsSAAALEgHS3X78AAAGzElEQVR4nN1b309cRRQ+S0g1oc2uYjDWxN20QmIEwaYm+AJY4xNGSF\/kqXDre6X9A7ys79of73bZPtWXBkz7ZCxLn0gkdVeamICtuyZCJKGFSJPSNLnmG2bW2dl77879Mbvg97LtsnfufN+cOXPOmZmE4zhkEolsboCIRogInxn+mfR45Q4RFYmozD8Ljm0VjfbPhACJbG6KiMY5cS+yuoAoBSKac2xrNva+xiVAIpvD6M5w4lFJewFizOE9jm2V42gwsgAS8ck4OhQA+TiECC1AIptLEdE0EdnReERGloiuOLa1HYpHGAES2RzmNuZj2jQ7TVSIaMqxrULQB9uCPpDI5mDuCweIPPG+LPC+BYK2BXCTx6iPmWQSA+AbpnWnhJYAnDzMq7\/1\/LRQwhKsI0LDKXAIyRPva4H33Re+AhxS8gJaIjSygCutIn\/\/\/Vv01Vv3ozbTzzl4wlOARDY33YLghmE4uUHvdTymL48\/oFT786jNTXIurnAVgCcwl6O+OSxAHEi2P6exzlgi3sucUx28LGDOHD1\/ZF7+hz7rrFR\/I8SIAa6JVJ0APJhoepADU8ec\/6nvTs33mAp3++7Q5OurUV\/R7xYo1cQBPLEpGszm6oARB\/FzXWsNf7vz4ghdXe+lr\/88FfZ1yCYzcnygWsBMM8kD\/R2PtcgT9wkRHWNSXRWqFsDXyydhW44CELpw\/AEz8\/RLu64t3dt5g\/Kb3ZT\/uyeOV74irEC2AM+lwjS2XxxhZn3y5wn6Ym2o5m0w+7eXP6czK6Nxka\/hKgsw1SoBZIBkZe9o9Zv8Zg+Vnx2L+zVVrkyARDY3fpDS22t\/9f737\/V3TbwiLeICYQEjJt4iA9Hdww9u0vWexYZODKMO08e8NzD6AswKhADjpt5CnDzWdzg4ePxb7\/zo+3v4hPNrw3Tx0aDnbyAi2omwIjDObXztN2r+tpLUDCU3mCh+mN9KU+lpp+cvJrtWWcQYIVTGNMi08Y0KYwDRIReyqihBceHN\/RA5Yqg8YFwArxBWxwrcIEJmES+IrDEkzAqAMNcvygtiBWjr2xNL9PD0zbo6wTcnlmhr8Ab7e0CfwARoWDYKC7Wj8OwyglgBfodoMelBMMmjyYBWlTImgNvoX\/pjkC1tMnTNFwESIsJr6711Qu7wSBJ\/h\/MMgFSCZq7HsjnY37HFzA8jAPL4lON6RHcIdcWSKOPGZjdb7+H1sQQuKiKpQPu\/n\/6++u1rS+fYc2HQHpbsWGeFRpIblGrfY46oEUQKC3IQQxbHzU9gVCFIee8olXY7WRosALF+2EqzZRDihSUPhBIABQqvuegGEJYTGYjxXfc932fQPnwES4261tj\/5ToABIEAV6WwOQwCb42JzgWBWsBQEx4djCjODZb08cqob7CkA1jAIpxskIfgyNyCm1+fvkpFmO2zY6yD29yM3QB\/AJ+B6YQ5jSkx0LHFfISbwPIUkEWIiMVQU+Dsb5\/Q3b7brnP\/0qMPteekcHiCCIImuSAqgBpBQO+ujTZ+HicQ0PEzK5+yEZexX8C8zUY1KEDezS+AfIyFEBXlUAKQJIK6rosqbhARWkQeYAIEPlQgsC\/CKFuKZGAO64qA+kCLyAOFNl4Gj4Tzq8OuIqie2w1uoWuTyAPFNl4dLUVtCSKoPqGosURVlIpPE8mXwF3EAbGcv1NXBZ01uqD4EK+yuAEwzkKAyHuBWMtlINCRl0OYOkpYyBDllFUNiHSmTUxgnJkA\/KxdpGmgjpwwbRCHQ0QChDUeAoicHkIUd2utJK0IaQglcb5QDoV9DxI0gurMkMRgxEFcjRqTvKoDIdQRb9IUqHJVN0e3w+4NYjnT3eNrBMT4MYS5Xqg4tpURf1OTodBWkNEYOawSajHDtS2z06CGY40Ajm3N8FOXgeGWHAmAOEb11C9n6eTyBMsO\/YQwOA0w+t4CcMS2SQoPj3UdxIVJVzdClyfqgicBgxZQx831oGQim5sLeiIUVVmRxoI4SOoENG4HJAz5gHnHtup2wLwESPEkSdshijKZWv3RhagJUDx5voq6kyECnkdl+Ynwhbh70iJ85HWS3LMkxh+4+D8gb\/kdo294WDqRzc226sBkDMg7tuV78KNhUZQ3kD9ApHTRkDygVRU+hCJokQe0y+K8QStSt5oDS5c8EPjO0AG8LySACHY86EXLwBsj3KNiS30+6LMGgb4MhLllGune4AGwhtC3xQRiuTnKr8o285B1hV+ajFzKi\/XuMD9vOGXwZhlMfdaxrdiO85u6PJ3ix9CiXqCuXpzml6dD3Q71g\/Hr8wA\/lSmuzuOzWpFRgARMXJ0vm746T0T0L4PyFr91fvgqAAAAAElFTkSuQmCC"",
				        ""_sys_dimensions"": ""65x65"",
				        ""_sys_name"": ""growth_new_logo"",
				        ""_sys_url"": ""https:\/\/res.cloudinary.com\/cien\/image\/upload\/v1739809799\/Newlogo_pytuae.png"",
				        ""notes"": ""PBI Reports"",
				        ""category"": ""New Logo Selling"",
				        ""_sys_doc_id"": 3
				        },
				        {
				        ""_sys_base64"": ""data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABBCAYAAABhNaJ7AAAACXBIWXMAAAsSAAALEgHS3X78AAAGtUlEQVR4nN1cTUxUVxQ+JbOQBFFYdUAijT+LalNqwyR14UyTNppo0mltsCYugOiCupCp4k5L6a5in11YFhDApAliWjskNIGkSYGFTcYUIcUuaEkhtbyu1NEmdEfzXe4d73vz\/ubNfQ9mvmTC5M2bN\/f77jnnnnvuvby0vr5OYUHL6An+U01EtNP0s0+JaA5vUrHoVFhtCkwALaODYJKIEpzw6wU+Yp4LAjHSqVj0aRDtVCqARLqViOLKHryBaSIaVi2GEgE48U7+2qGkZfbIEtENvFQIUZQAIRM3Q4kQvgXQMnqSm2TYxM2AEK2pWDTt58sFC8B7HcTf8\/ODAeIWLLFQayhIAC2jN3HyhUb0sDDPrWFOuQCc\/NQWMHk3wCUSXkWo8HKTltExrD0oAfLE2\/iAt9kVrhbAg933YbQ8ALzvFhwdBSghs7eDqzvYCsCj\/XIJkxeACI12o4NTDEiXAXniHGzdwFIALaN3B5DLbybinFMe8lxAy+iNRPRnGZGX8UoqFl2WL1hZwHDozQoPedwMAvCCRTmZvhlxqSjDEDHdYOknxeKP2Xu0MDXB\/q7+\/ht72p5Db1HseAs1nzhFM7f7KTM+mvus5uVdtPfNw9R8ooX2HjqsujndvEjDkIsBXJmfVBOf7L9OS7M\/296zraqa\/vv3me3nEOrouYuqhXhblN1kF\/CUOnrB2vNnNNLTSV93fOhIHnAiD+D7eA6eh+cqQo4rswCe9DxR8ezH+l802NWWM2cZMO3augZae561\/BzWUL\/\/AP29+NBSmLp9r9L5vrtUub1aRVNrkByJGJBU8USQ7z3zbl7jZTNGL97s+MDwOYifvnqDXosfy137dXqCJvt7DULhPb6rSARW0BEWkHYrcNzsOGlrzh\/3fcvI9Z55J69nk6nP6MhH59h7Qd58j\/i+FRBDJgeuF8zu6NmLTHQHjKVi0aSwgITTnV4hE0Ovnu\/7jpm0E\/nTVzTHAAcStdFdNPJ5SkUTZTDOFXzGpyTnh48KeCWPYdANuAf3KsYOcI+o6n1ivXWJVhcfsvG7NtqQuz7Sc8GWvFkcO3fAvTV1DbT0yws3RMy5\/8OdYpqcgACNxTxBBoKYHMgARPSFmUnDNTvyboAwsjjIM4oUYGcFX7YKDEuz9wyPRnByIl9ZFeoMPOGpJqga6Dkr8gicq4sLobYlErQF7DH5MxvSBqzvRf6AaA+3SX7SE2SzBBorgq76YCRAIuQEZIgyZkYHWN6hMPW1w+5QXKD9iyHDECnAMsArGl365kdqPt5i+AxJF9wE1hAkzNPhQIC0FSSR3q5yQrh2MH4sN1wiFYa1pLVPc03YSH1P5qXJKhHhVdNQQq\/VMCkDKXNNtIHN\/MR8An+HLrd7SW39YKVCbEvZKoBAyCLNLoPgqXhKDCz7cgE07rH+KNdL6S+vUuV2oxHV7zvgO5LDFTDjQwYpJ1FIejCVbr82lPcdxBPMGbwmVQIVfOWnIIBYnM\/wiPsqgpb8QiTH7NBvjyFGgOiRU2cN1yEIUmAz0B4fgk9F+OpPQRjsanet5JCi+bsgBUEFIIA81yDuIttuF\/wbzAUKjgEyeVHlkSHXDSACLAG9KWaHhQAWhNFDhkiXIYJcU\/TSKSbMRbBwqGV015EAPm0GJiZWkfn++Khh\/v7kn0dsOJOnyAIIbLhmLprU7z\/Ihr\/By23s+wKIP+IZEKD92iDNjPTTmok84oELsuDuuSJUKJDAgLTcK3LpC2aM4CmCHBIhRrirLXcN1iWTNxdZigSrCAkBUCXND60BiFAMvBZQPKItFYsOi1TY1w4rN2wMZ\/ljuh8080UURcgKzkwAvnZ+KzgR7tpOiGDWVhD3Qzz0PNxDIXK7TeWVoSa+DygwIJovTE8w\/6+sqmaxAL3KKjvjd9h1BFYEREW1fzu8IXaNGJbHtYw+VeaLo8B0KhbN1UHN0+FAFke3GAwcDQLwBcOxMiY\/Zj6LYFUQ6eRRstyQ5dwMyBOAbyEpR1foNm+PAZy2ySnPDjcRLOuz+nmnmiCyw5UyID\/vtPfBVgCeKCRLPB6IswS2W+gdq8I8WUiUqAiedo27lsVLVATPW+Y9rQuUmAjqzwvQCxEaeVDZqpjnG6PVnxiRoWV0TM0ubDERvkrFonmJjhuKOTWW4FtPdxfZ8GKxwiO9r+O2RR+c1DJ6J88cN+PcILK7ogoFKk+OtvJcO2iLWOEHJoc3\/eSoFfgZI\/FSZRWihJX2e0DSDoEen+diNEknyL0KkpVOjs+pJi0j7P8fAFeRd6SIyowcwEA4kKPyeSCi\/wGFcErRz8FAcgAAAABJRU5ErkJggg=="",
				        ""_sys_dimensions"": ""65x65"",
				        ""_sys_name"": ""growth_sales_mkt"",
				        ""_sys_url"": ""https:\/\/res.cloudinary.com\/cien\/image\/upload\/v1739809799\/SalesMKT_yvidm0.png"",
				        ""notes"": ""PBI Reports"",
				        ""category"": ""Sales & Marketing Alignment"",
				        ""_sys_doc_id"": 2
				        }
				    ]
				
				
				    ",
				
				    // Parse JSON text
				    ParsedJson = Json.Document(jsonText),
				
				    // Convert JSON list to table
				    TableData = Table.FromList(ParsedJson, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				
				    // Expand records to columns
				    ExpandData = Table.ExpandRecordColumn(TableData, "Column1", {
				        "_sys_base64",
				        "_sys_dimensions",
				        "_sys_doc_id",
				        "_sys_name",
				        "_sys_url",
				        "notes",
				        "category"
				    }),
				    #"Changed Type" = Table.TransformColumnTypes(ExpandData,{{"_sys_base64", type text}, {"_sys_dimensions", type text}, {"_sys_doc_id", Int64.Type}, {"_sys_name", type text}, {"_sys_url", type text}, {"notes", type text}, {"category", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

