/// Table last_refresh_date.
table last_refresh_date
	lineageTag: 516a6aac-c291-4178-a025-061cf7c74376

	/// ?? Purpose: Compute the measure result from the DAX expression.
	/// ?? Dependencies: See model references
	/// ?? Dynamic Behavior: Modifies filter context via CALCULATE filters.
	/// ?? Format/Type: Text
	measure 'meas.last_refresh_date' = CALCULATE(MAX(last_refresh_date[Last Refresh Date]))
		formatString: General Date
		lineageTag: 577e8dc9-a3c4-473d-96ad-cba88bbc8500

	/// Column 'Last Refresh Date'.
	column 'Last Refresh Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b5f6711-64d2-4b0c-abd6-89a6a0274024
		summarizeBy: none
		sourceColumn: Last Refresh Date

		variation Variation
			isDefault
			relationship: 0bf98a18-9d72-4fc0-8d18-336649b84a4c
			defaultHierarchy: LocalDateTable_f72d3125-1ca6-47f1-9505-053937281ad6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition last_refresh_date = m
		mode: import
		source =
				let
				    Source = DateTimeZone.UtcNow(),
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Last Refresh Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

