/// Table last_refresh_date.
table last_refresh_date
	description: "TODO: provide business definition for this table. Related to LocalDateTable_f72d3125-1ca6-47f1-9505-053937281ad6 ('Last Refresh Date' -> Date). Supports measures such as meas.last_refresh_date."
	lineageTag: 516a6aac-c291-4178-a025-061cf7c74376

	/// Measure meas.last_refresh_date.
	/// Purpose: Returns a value derived from last_refresh_date[Last Refresh Date].
	/// Calculation Logic: Uses CALCULATE, MAX.
	/// Dynamic Behavior: Respects current filter context. CALCULATE modifies filter context using its filter arguments. Responds to filters on last_refresh_date[Last Refresh Date].
	/// Format/Type: General Date
	measure 'meas.last_refresh_date' = CALCULATE(MAX(last_refresh_date[Last Refresh Date]))
		description: "TODO: provide business definition for this measure."
		formatString: General Date
		lineageTag: 577e8dc9-a3c4-473d-96ad-cba88bbc8500

	/// Column 'Last Refresh Date'.
	column 'Last Refresh Date'
		description: "Date/time when 'last."
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b5f6711-64d2-4b0c-abd6-89a6a0274024
		summarizeBy: none
		sourceColumn: Last Refresh Date

		variation Variation
			isDefault
			relationship: 0bf98a18-9d72-4fc0-8d18-336649b84a4c
			defaultHierarchy: LocalDateTable_f72d3125-1ca6-47f1-9505-053937281ad6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition last_refresh_date = m
		mode: import
		source =
				let
				    Source = DateTimeZone.UtcNow(),
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Last Refresh Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

