table managers_direct
	lineageTag: 53033c38-7bc9-4974-89e6-b4c77b910e9a

	column _sys_co_id
		dataType: string
		lineageTag: 8a76afea-4c7b-4512-936d-3278e170c043
		summarizeBy: none
		sourceColumn: _sys_co_id

		annotation SummarizationSetBy = Automatic

	column _sys_doc_id
		dataType: string
		lineageTag: e1270b54-af1b-4972-87df-457e8b459b96
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 623f97ae-9c54-4f80-9487-4d02d2f00b01
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: c618870b-ee74-4c44-bff2-dde566c65b30
			defaultHierarchy: LocalDateTable_b757fccc-aa49-4f76-9bad-7aaf1dc6b28b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 96540ee2-cf1f-446e-a66e-98618190da3d
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: e55c86c2-5ea9-47c5-a931-a497ed73082a
			defaultHierarchy: LocalDateTable_61e2a260-d025-4e5b-87c3-d6a748ad3858.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_addr_city
		dataType: string
		lineageTag: c4c0846c-c8f1-47c6-97f7-8571d8a91992
		summarizeBy: none
		sourceColumn: crm_addr_city

		annotation SummarizationSetBy = Automatic

	column crm_addr_country
		dataType: string
		lineageTag: e955c7f1-1705-4831-bba0-1670e9e2c7e5
		summarizeBy: none
		sourceColumn: crm_addr_country

		annotation SummarizationSetBy = Automatic

	column crm_addr_postal_code
		dataType: string
		lineageTag: 6d88fc01-425a-44ce-b4db-89385cdeeca9
		summarizeBy: none
		sourceColumn: crm_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column crm_addr_state
		dataType: string
		lineageTag: 618f3f5c-c943-4ea3-a601-12f858488325
		summarizeBy: none
		sourceColumn: crm_addr_state

		annotation SummarizationSetBy = Automatic

	column crm_addr_street
		dataType: string
		lineageTag: 7277970a-24aa-45c5-9470-8bb17ca7f703
		summarizeBy: none
		sourceColumn: crm_addr_street

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: 05c63235-e80f-4c76-a58c-7a53c621e3cb
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_division
		dataType: string
		lineageTag: 16a7f4d5-24ab-430b-bafd-9411172c67b3
		summarizeBy: none
		sourceColumn: crm_division

		annotation SummarizationSetBy = Automatic

	column crm_email
		dataType: string
		lineageTag: afec466c-b176-433e-b410-f6ceef631da5
		summarizeBy: none
		sourceColumn: crm_email

		annotation SummarizationSetBy = Automatic

	column crm_first_name
		dataType: string
		lineageTag: 92d45002-5e46-4303-8bd1-d8873e48d861
		summarizeBy: none
		sourceColumn: crm_first_name

		annotation SummarizationSetBy = Automatic

	column crm_language_locale
		dataType: string
		lineageTag: 2f4ae592-92ae-4e20-b72b-1ff179717c2c
		summarizeBy: none
		sourceColumn: crm_language_locale

		annotation SummarizationSetBy = Automatic

	column crm_last_login_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 04298ac0-efda-4deb-a08d-dbc9d447148e
		summarizeBy: none
		sourceColumn: crm_last_login_time

		variation Variation
			isDefault
			relationship: 1284282d-5776-4f9a-bba1-73b17abd8bfa
			defaultHierarchy: LocalDateTable_c9b31d5b-a7dc-4404-ad45-48e17362770c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_last_name
		dataType: string
		lineageTag: 2dc3c9bd-610d-4e92-a51f-13c024016c7b
		summarizeBy: none
		sourceColumn: crm_last_name

		annotation SummarizationSetBy = Automatic

	column crm_locale
		dataType: string
		lineageTag: 92c9b4a6-6684-4db5-b12b-2119c1eb30d3
		summarizeBy: none
		sourceColumn: crm_locale

		annotation SummarizationSetBy = Automatic

	column crm_profile_url
		dataType: string
		lineageTag: 2ce61a71-2372-4c2e-a36c-183666490c19
		summarizeBy: none
		sourceColumn: crm_profile_url

		annotation SummarizationSetBy = Automatic

	column crm_role
		dataType: string
		lineageTag: 84b82687-0e5b-411f-933a-693b507555df
		summarizeBy: none
		sourceColumn: crm_role

		annotation SummarizationSetBy = Automatic

	column crm_time_zone
		dataType: string
		lineageTag: 36a9e5e9-b2ca-4cc3-99a5-5c9901a8defe
		summarizeBy: none
		sourceColumn: crm_time_zone

		annotation SummarizationSetBy = Automatic

	column crm_title
		dataType: string
		lineageTag: 14f44cba-c41b-493c-91ad-be3f92a4443a
		summarizeBy: none
		sourceColumn: crm_title

		annotation SummarizationSetBy = Automatic

	column crm_user_type
		dataType: string
		lineageTag: 90c4cd63-ed46-4c49-b4e2-f34afd62f316
		summarizeBy: none
		sourceColumn: crm_user_type

		annotation SummarizationSetBy = Automatic

	column crm_username
		dataType: string
		lineageTag: 5c9cf81f-d32a-4665-b608-af48026d0f09
		summarizeBy: none
		sourceColumn: crm_username

		annotation SummarizationSetBy = Automatic

	column trueai_billable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2cc84ebb-7056-45b2-a2ba-17b14d048beb
		summarizeBy: none
		sourceColumn: trueai_billable

		annotation SummarizationSetBy = Automatic

	column trueai_direct_reports
		dataType: int64
		formatString: 0
		lineageTag: 08787aec-777c-4fba-b456-10b5ab7c1431
		summarizeBy: sum
		sourceColumn: trueai_direct_reports

		annotation SummarizationSetBy = Automatic

	column trueai_ext_match_rule
		dataType: string
		lineageTag: bee13ecd-68fd-435a-bdbd-b9ffe4c09e0e
		summarizeBy: none
		sourceColumn: trueai_ext_match_rule

		annotation SummarizationSetBy = Automatic

	column trueai_group
		dataType: string
		lineageTag: 17553aff-954d-46ce-820e-bc7d5db28d8b
		summarizeBy: none
		sourceColumn: trueai_group

		annotation SummarizationSetBy = Automatic

	column trueai_group_conf
		dataType: string
		lineageTag: 3b30e284-6548-4fde-8281-b5a1dc5a4493
		summarizeBy: none
		sourceColumn: trueai_group_conf

		annotation SummarizationSetBy = Automatic

	column trueai_group_rule
		dataType: string
		lineageTag: 5da85e7a-f79c-499b-8c91-0649acfcf3ac
		summarizeBy: none
		sourceColumn: trueai_group_rule

		annotation SummarizationSetBy = Automatic

	column trueai_hire_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06678879-d9bf-4afd-8a4a-f0951302c43a
		summarizeBy: none
		sourceColumn: trueai_hire_date

		variation Variation
			isDefault
			relationship: 51d6366c-e6f2-40e0-b15d-34ce8a69dddb
			defaultHierarchy: LocalDateTable_097ce628-90f9-407d-90e7-33bef95bf0ac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_performance_lvl_reached_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 575c374a-15aa-4e2b-9852-c50f5ad8b754
		summarizeBy: none
		sourceColumn: trueai_performance_lvl_reached_on

		variation Variation
			isDefault
			relationship: fcb254e9-9108-4918-b147-93aead261026
			defaultHierarchy: LocalDateTable_eb68bad1-b968-411e-b92f-f36c6abbd19d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_role
		dataType: string
		lineageTag: 0775b16f-ccdb-4fa4-a7d8-08b78f29b841
		summarizeBy: none
		sourceColumn: trueai_role

		annotation SummarizationSetBy = Automatic

	column trueai_role_conf
		dataType: double
		formatString: 0
		lineageTag: d4a2769e-0e3f-43dd-b0bd-f486be0a65cf
		summarizeBy: sum
		sourceColumn: trueai_role_conf

		annotation SummarizationSetBy = Automatic

	column trueai_tenure
		dataType: int64
		formatString: 0
		lineageTag: 6d1b1e23-7891-477a-8222-5e7e17615586
		summarizeBy: sum
		sourceColumn: trueai_tenure

		annotation SummarizationSetBy = Automatic

	column trueai_termination_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4a41eb86-4641-4897-97e2-69cee3a5d4d1
		summarizeBy: none
		sourceColumn: trueai_termination_date

		variation Variation
			isDefault
			relationship: 9fa496b8-6125-4b3b-81af-328959d946ab
			defaultHierarchy: LocalDateTable_d580d19a-fbcd-41a7-bbf5-46be58c9fdd5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_title
		dataType: string
		lineageTag: 2ff7dd22-2797-467d-9f14-b3c871ce5612
		summarizeBy: none
		sourceColumn: trueai_title

		annotation SummarizationSetBy = Automatic

	column trueai_title_conf
		dataType: double
		lineageTag: 06a01d8a-dab4-49cf-b86c-7b42c04a8682
		summarizeBy: sum
		sourceColumn: trueai_title_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_tot_reports
		dataType: int64
		formatString: 0
		lineageTag: 23dd8540-8e04-47a2-a342-26dae23787d7
		summarizeBy: sum
		sourceColumn: trueai_tot_reports

		annotation SummarizationSetBy = Automatic

	column trueai_user_behavior
		dataType: string
		lineageTag: 97a69330-2992-4aa7-82d1-a60f295acb2a
		summarizeBy: none
		sourceColumn: trueai_user_behavior

		annotation SummarizationSetBy = Automatic

	column trueai_user_behavior_conf
		dataType: double
		lineageTag: 6d299d76-d42f-48c1-a238-32076e557861
		summarizeBy: sum
		sourceColumn: trueai_user_behavior_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_user_role
		dataType: string
		lineageTag: 272e6fc0-5321-448e-8fb4-92fc1562ccee
		summarizeBy: none
		sourceColumn: trueai_user_role

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_dept
		dataType: string
		lineageTag: 819edbd5-d2ac-4c52-a727-bb2032a348ba
		summarizeBy: none
		sourceColumn: trueai_user_role_dept

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_function
		dataType: string
		lineageTag: b89695ec-a721-47f4-b913-d8e49d0484e2
		summarizeBy: none
		sourceColumn: trueai_user_role_function

		annotation SummarizationSetBy = Automatic

	column trueai_ext_match_id
		dataType: string
		lineageTag: b257ff6c-4e86-4614-9bbf-2bdfca628a4e
		summarizeBy: none
		sourceColumn: trueai_ext_match_id

		annotation SummarizationSetBy = Automatic

	column trueai_addr_city
		dataType: string
		lineageTag: 1b85e3d4-7155-4f6e-bdb6-e05f8f2902b8
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	column trueai_addr_country
		dataType: string
		lineageTag: 6e4bc7fd-884c-4b5c-baaa-778f09b5928d
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	column trueai_addr_lat
		dataType: string
		lineageTag: 3797fc80-44ad-4e0a-a8ce-d5dacfd9262f
		summarizeBy: none
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

	column trueai_addr_long
		dataType: string
		lineageTag: 6401de0e-f956-42ea-b8ff-1b2f1e9512f1
		summarizeBy: none
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

	column trueai_addr_postal_code
		dataType: string
		lineageTag: 6b768078-ea14-41d5-b7bf-b9e83b425988
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column trueai_addr_state
		dataType: string
		lineageTag: 75f79fa3-7ead-49bb-a9d5-b1dfe12ae634
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	column trueai_addr_street
		dataType: string
		lineageTag: 1c48dead-e345-4135-a0c9-2d67d3142c6b
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: 17915642-645f-4275-95e6-53b79b7ede6a
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 5bf8ffb1-8569-4786-ae1c-88c3b41c9d9c
			defaultHierarchy: LocalDateTable_a198dea3-dde3-44d8-b645-36f8d3790251.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_last_modified_on
		dataType: string
		lineageTag: b8fbcb13-97f2-4378-9555-48c34593b475
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 540c72f5-4358-4d7b-9132-bf24bdcb3bd3
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 0c5da524-b587-433f-b648-4a78398b8cb2
			defaultHierarchy: LocalDateTable_4b0abab5-87f0-413c-868d-a82099802455.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_dept
		dataType: string
		lineageTag: 9f8d7276-96c8-43f8-812d-ae1562726417
		summarizeBy: none
		sourceColumn: crm_dept

		annotation SummarizationSetBy = Automatic

	column crm_mgr_id
		dataType: string
		lineageTag: 51d9f208-7b32-4cbc-a440-807e9d849186
		summarizeBy: none
		sourceColumn: crm_mgr_id

		annotation SummarizationSetBy = Automatic

	column trueai_is_mgr
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b0ea420d-84a0-4017-9241-2479bbd2671b
		summarizeBy: none
		sourceColumn: trueai_is_mgr

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_id
		dataType: string
		lineageTag: 052b78d5-7d5a-4ec7-b7a3-94cd2f3070c7
		summarizeBy: none
		sourceColumn: trueai_mgr_id

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_id_conf
		dataType: string
		lineageTag: 62c37da3-6848-4b89-842a-5ee4fd95368d
		summarizeBy: none
		sourceColumn: trueai_mgr_id_conf

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_id_rule
		dataType: string
		lineageTag: c99158b1-d6d3-4f68-aa65-86bde16b9bbc
		summarizeBy: none
		sourceColumn: trueai_mgr_id_rule

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_ids
		dataType: string
		lineageTag: 434dd815-8d99-4056-8101-0b5232f9c3b4
		summarizeBy: none
		sourceColumn: trueai_mgr_ids

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_alias
		dataType: string
		lineageTag: f1d37f09-62b5-4644-b791-e897775cb229
		summarizeBy: none
		sourceColumn: trueai_user_role_alias

		annotation SummarizationSetBy = Automatic

	column trueai_is_dummy
		dataType: string
		lineageTag: b24e7398-2eee-47d3-9cba-591b9926da1c
		summarizeBy: none
		sourceColumn: trueai_is_dummy

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: 1d7aa8df-3ca0-451b-9aaa-f98495425b1b
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: a53be9d8-8210-42ed-9ed4-47aec66394aa
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: d98dc69e-2688-4e44-a8ba-d54b278914ed
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: 07a81abe-bb0e-48df-ae64-c8858ad2d436
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: 493857ae-aec7-4668-accc-24186b2e2cbe
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: string
		lineageTag: 62d5254a-b2d1-4812-89b6-a129471da009
		summarizeBy: none
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

	column cust_num2
		dataType: string
		lineageTag: c5daf791-b992-4e18-80bc-4c87b800cff6
		summarizeBy: none
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

	column cust_num3
		dataType: string
		lineageTag: 5e24c89d-494a-44a8-aef6-3e7450bf7394
		summarizeBy: none
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

	column cust_num4
		dataType: string
		lineageTag: 57aca1e0-23fe-4533-a06e-b0ceb36ef7b0
		summarizeBy: none
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

	column cust_num5
		dataType: string
		lineageTag: e5917e61-d66d-44b3-9f8a-25e79e0f3e87
		summarizeBy: none
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

	column cust_num6
		dataType: string
		lineageTag: 89f30695-80cf-4e9a-9dbe-9b926a36722f
		summarizeBy: none
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

	column cust_num7
		dataType: string
		lineageTag: b63fe935-4fe1-40ac-b93a-085bb4450606
		summarizeBy: none
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

	column cust_bool1
		dataType: string
		lineageTag: 6ab04f4a-efa4-40f5-a3a4-daeb52e9fed5
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: string
		lineageTag: 78f27d86-1a2f-486c-ac57-a7aeffd7a755
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	column crm_deep_link
		dataType: string
		lineageTag: ffc4f014-6838-451f-8188-bc98973033c8
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	column trueai_full_name
		dataType: string
		lineageTag: db456047-809a-4f98-af93-00ed71829515
		summarizeBy: none
		sourceColumn: trueai_full_name

		annotation SummarizationSetBy = Automatic

	column 'col.crm_full_name_title' = managers_direct[crm_first_name] & " " & managers_direct[crm_last_name] & ", " & managers_direct[crm_title]
		lineageTag: 792a07ef-e808-4b47-93a5-661f429da43a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column trueai_ramping_status
		dataType: string
		lineageTag: f4e745ec-34b2-46ea-9500-f8281290fd75
		summarizeBy: none
		sourceColumn: trueai_ramping_status

		annotation SummarizationSetBy = Automatic

	column trueai_test
		dataType: string
		lineageTag: 9d65749b-594c-4c36-8672-ef289049ae55
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	column trueai_test_conf
		dataType: string
		lineageTag: 425ca55f-9071-4a03-b1d3-470542c86e27
		summarizeBy: none
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

	column trueai_test_rule
		dataType: string
		lineageTag: 1215e9c6-6a19-407f-9f63-6294a28ff64c
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	column trueai_test_debug
		dataType: string
		lineageTag: 7232c540-b811-4171-aa7b-0e1b04ae20dd
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	partition managers_direct-4bf5ea7b-5ada-4a70-ba18-531be04737c5 = m
		mode: import
		source =
				let
				
				  dbTable = getDBTable("users"), // get the right table
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{{"_sys_as_of", type datetime}, {"_sys_co_id", type text}, {"_sys_doc_id", type text}, {"_sys_filt_end_date", type datetime}, {"_sys_filt_start_date", type datetime}, {"crm_addr_city", type text}, {"crm_addr_country", type text}, {"crm_addr_postal_code", type text}, {"crm_addr_state", type text}, {"crm_addr_street", type text}, {"crm_created_on", type datetime}, {"crm_creator_id", type text}, {"crm_dept", type text}, {"crm_division", type text}, {"crm_email", type text}, {"crm_first_name", type text}, {"crm_language_locale", type text}, {"crm_last_login_time", type datetime}, {"crm_last_name", type text}, {"crm_locale", type text}, {"crm_mgr_id", type text}, {"crm_profile_url", type text}, {"crm_role", type text}, {"crm_time_zone", type text}, {"crm_title", type text}, {"crm_user_type", type text}, {"crm_username", type text}, {"trueai_billable", type logical}, {"trueai_direct_reports", Int64.Type}, {"trueai_group", type text}, {"trueai_hire_date", type datetime}, {"trueai_is_mgr", type logical}, {"trueai_mgr_id", type text}, {"trueai_mgr_ids", type text}, {"trueai_performance_lvl_reached_on", type datetime}, {"trueai_role", type text}, {"trueai_role_conf", type number}, {"trueai_tenure", Int64.Type}, {"trueai_termination_date", type datetime}, {"trueai_title", type text}, {"trueai_title_conf", type number}, {"trueai_tot_reports", Int64.Type}, {"trueai_user_behavior", type text}, {"trueai_user_behavior_conf", type number}, {"trueai_user_role", type text}, {"trueai_user_role_dept", type text}, {"trueai_user_role_function", type text}, {"trueai_ext_match_rule", type text}, {"trueai_group_rule", type text}, {"trueai_mgr_id_rule", type text}})
				in
				    dbTableTyped

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

