/// Table managers_total.
table managers_total
	lineageTag: bae60098-d84b-46ee-9b2b-8c1b145727ec

	/// Column _sys_co_id.
	column _sys_co_id
		dataType: string
		lineageTag: 265906cc-d14f-4069-9ec0-94d943a386d4
		summarizeBy: none
		sourceColumn: _sys_co_id

		annotation SummarizationSetBy = Automatic

	/// Column _sys_doc_id.
	column _sys_doc_id
		dataType: string
		lineageTag: 590abd96-6bd8-4660-97e7-0e364c5fd70b
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Column _sys_filt_end_date.
	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 793dad58-95a9-4fe7-abb6-e8adf6c403b8
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: b8c994fd-682d-49c7-8d0a-b76626180157
			defaultHierarchy: LocalDateTable_3b5894cd-27ee-48ce-903a-7ec09fe33b90.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column _sys_filt_start_date.
	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 991849ba-2082-445b-b8bc-f1bac46cb5ea
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: aa3d8898-4724-4ae9-81af-e32b3562e0fd
			defaultHierarchy: LocalDateTable_0e7e76d8-1e4d-4c7c-884a-6d7a8d5aa123.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column crm_addr_city.
	column crm_addr_city
		dataType: string
		lineageTag: 8e8eed5e-43ba-4544-96a7-6e870ba6cabd
		summarizeBy: none
		sourceColumn: crm_addr_city

		annotation SummarizationSetBy = Automatic

	/// Column crm_addr_country.
	column crm_addr_country
		dataType: string
		lineageTag: d80a1ca3-8be5-462c-bdcc-35efd4036c0f
		summarizeBy: none
		sourceColumn: crm_addr_country

		annotation SummarizationSetBy = Automatic

	/// Column crm_addr_postal_code.
	column crm_addr_postal_code
		dataType: string
		lineageTag: 9d8caf77-838a-4b18-8818-46dd5bdbc5fa
		summarizeBy: none
		sourceColumn: crm_addr_postal_code

		annotation SummarizationSetBy = Automatic

	/// Column crm_addr_state.
	column crm_addr_state
		dataType: string
		lineageTag: 67ddba38-1650-4628-8671-72f2476faeda
		summarizeBy: none
		sourceColumn: crm_addr_state

		annotation SummarizationSetBy = Automatic

	/// Column crm_addr_street.
	column crm_addr_street
		dataType: string
		lineageTag: dc4d0e9c-0783-4600-aacc-00bbda23df1a
		summarizeBy: none
		sourceColumn: crm_addr_street

		annotation SummarizationSetBy = Automatic

	/// Column crm_creator_id.
	column crm_creator_id
		dataType: string
		lineageTag: 6b67960d-eeba-4fe3-b031-b814eb76a6b3
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	/// Column crm_division.
	column crm_division
		dataType: string
		lineageTag: 2ff684df-ecab-423f-8566-6cd48085f664
		summarizeBy: none
		sourceColumn: crm_division

		annotation SummarizationSetBy = Automatic

	/// Column crm_email.
	column crm_email
		dataType: string
		lineageTag: 73331434-8478-4d10-b5ce-fa71a2d9a53a
		summarizeBy: none
		sourceColumn: crm_email

		annotation SummarizationSetBy = Automatic

	/// Column crm_first_name.
	column crm_first_name
		dataType: string
		lineageTag: 7665aeca-7249-4137-b2fc-68654d94c3da
		summarizeBy: none
		sourceColumn: crm_first_name

		annotation SummarizationSetBy = Automatic

	/// Column crm_language_locale.
	column crm_language_locale
		dataType: string
		lineageTag: 1d72d219-4304-4f2e-a93f-6ecdb3b7ce1c
		summarizeBy: none
		sourceColumn: crm_language_locale

		annotation SummarizationSetBy = Automatic

	/// Column crm_last_login_time.
	column crm_last_login_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 2673983d-72cd-4612-a29d-cb53323c7ac4
		summarizeBy: none
		sourceColumn: crm_last_login_time

		variation Variation
			isDefault
			relationship: 1ce058fe-ba2b-4dcf-8539-b6e51b818391
			defaultHierarchy: LocalDateTable_032ecec0-e14d-4d62-8ffc-0e2043a3076a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column crm_last_name.
	column crm_last_name
		dataType: string
		lineageTag: 60e08c33-ee3e-4ff0-822f-d7ff09f2facb
		summarizeBy: none
		sourceColumn: crm_last_name

		annotation SummarizationSetBy = Automatic

	/// Column crm_locale.
	column crm_locale
		dataType: string
		lineageTag: 6df09d57-64cf-4f1e-8ed7-0af36c341244
		summarizeBy: none
		sourceColumn: crm_locale

		annotation SummarizationSetBy = Automatic

	/// Column crm_profile_url.
	column crm_profile_url
		dataType: string
		lineageTag: 5f90bbcb-39df-4322-9d43-58ab6a68dfa4
		summarizeBy: none
		sourceColumn: crm_profile_url

		annotation SummarizationSetBy = Automatic

	/// Column crm_role.
	column crm_role
		dataType: string
		lineageTag: 59544475-3abe-4259-a639-9d3c81c0c135
		summarizeBy: none
		sourceColumn: crm_role

		annotation SummarizationSetBy = Automatic

	/// Column crm_time_zone.
	column crm_time_zone
		dataType: string
		lineageTag: 6cda9eeb-40f0-4ab5-abb5-81d1b89dfbdf
		summarizeBy: none
		sourceColumn: crm_time_zone

		annotation SummarizationSetBy = Automatic

	/// Column crm_title.
	column crm_title
		dataType: string
		lineageTag: 452cbe3a-756d-43ff-be80-316d6aa87174
		summarizeBy: none
		sourceColumn: crm_title

		annotation SummarizationSetBy = Automatic

	/// Column crm_user_type.
	column crm_user_type
		dataType: string
		lineageTag: def4de5c-3054-4a8f-bae6-b03f79757c27
		summarizeBy: none
		sourceColumn: crm_user_type

		annotation SummarizationSetBy = Automatic

	/// Column crm_username.
	column crm_username
		dataType: string
		lineageTag: f11eb1c2-f071-4c38-9aac-f3cef33af9a0
		summarizeBy: none
		sourceColumn: crm_username

		annotation SummarizationSetBy = Automatic

	/// Column trueai_billable.
	column trueai_billable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8ff6b341-f718-4dbe-9c84-118a8d33fbac
		summarizeBy: none
		sourceColumn: trueai_billable

		annotation SummarizationSetBy = Automatic

	/// Column trueai_direct_reports.
	column trueai_direct_reports
		dataType: int64
		formatString: 0
		lineageTag: 5d09cf7c-d349-46e3-b66e-ef29058ee6e9
		summarizeBy: sum
		sourceColumn: trueai_direct_reports

		annotation SummarizationSetBy = Automatic

	/// Column trueai_ext_match_rule.
	column trueai_ext_match_rule
		dataType: string
		lineageTag: 6b05cd02-bb5c-46ae-8276-d80be2083d94
		summarizeBy: none
		sourceColumn: trueai_ext_match_rule

		annotation SummarizationSetBy = Automatic

	/// Column trueai_group.
	column trueai_group
		dataType: string
		lineageTag: d82cca52-43f0-4cab-98ed-3daeb9a2e74a
		summarizeBy: none
		sourceColumn: trueai_group

		annotation SummarizationSetBy = Automatic

	/// Column trueai_group_conf.
	column trueai_group_conf
		dataType: string
		lineageTag: ead09ea6-0cca-43f5-8c56-070e27c14517
		summarizeBy: none
		sourceColumn: trueai_group_conf

		annotation SummarizationSetBy = Automatic

	/// Column trueai_group_rule.
	column trueai_group_rule
		dataType: string
		lineageTag: 9fe283ea-d508-48d9-807c-2fd38b145b69
		summarizeBy: none
		sourceColumn: trueai_group_rule

		annotation SummarizationSetBy = Automatic

	/// Column trueai_hire_date.
	column trueai_hire_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0215cf3-f7d5-4cc9-af47-78f5c709edd7
		summarizeBy: none
		sourceColumn: trueai_hire_date

		variation Variation
			isDefault
			relationship: af757c40-b306-45ce-9c11-0b9eda7f7009
			defaultHierarchy: LocalDateTable_2cb1e131-7707-4826-b7bc-6ce26c9410bb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column trueai_performance_lvl_reached_on.
	column trueai_performance_lvl_reached_on
		dataType: dateTime
		formatString: General Date
		lineageTag: d080afeb-0e88-46c9-b1d9-bb13109aaa43
		summarizeBy: none
		sourceColumn: trueai_performance_lvl_reached_on

		variation Variation
			isDefault
			relationship: 5b331221-0a29-4cff-83ce-caf7bf002417
			defaultHierarchy: LocalDateTable_48859e01-5b68-4322-9036-de3062c9c81a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column trueai_role.
	column trueai_role
		dataType: string
		lineageTag: bb88148c-bf0d-4bd0-bdc9-0601bb6e88b1
		summarizeBy: none
		sourceColumn: trueai_role

		annotation SummarizationSetBy = Automatic

	/// Column trueai_role_conf.
	column trueai_role_conf
		dataType: double
		formatString: 0
		lineageTag: c37f98d6-f264-4ecf-9ff0-194ed4f60845
		summarizeBy: sum
		sourceColumn: trueai_role_conf

		annotation SummarizationSetBy = Automatic

	/// Column trueai_tenure.
	column trueai_tenure
		dataType: int64
		formatString: 0
		lineageTag: 7d3dce78-d02b-4b91-9363-e63a971db115
		summarizeBy: sum
		sourceColumn: trueai_tenure

		annotation SummarizationSetBy = Automatic

	/// Column trueai_termination_date.
	column trueai_termination_date
		dataType: dateTime
		formatString: General Date
		lineageTag: dfc22fea-bbfb-481d-966c-dff7de35fcc6
		summarizeBy: none
		sourceColumn: trueai_termination_date

		variation Variation
			isDefault
			relationship: 23917ca3-3250-4450-9c0c-14d78d46b55f
			defaultHierarchy: LocalDateTable_f06a2fa1-388c-474d-a3a0-2bf137ff06d4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column trueai_title.
	column trueai_title
		dataType: string
		lineageTag: 9eda1a0e-3533-4f4f-91f4-79084c93a13e
		summarizeBy: none
		sourceColumn: trueai_title

		annotation SummarizationSetBy = Automatic

	/// Column trueai_title_conf.
	column trueai_title_conf
		dataType: double
		lineageTag: 1a038410-6b07-41aa-86ed-706209e3b199
		summarizeBy: sum
		sourceColumn: trueai_title_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column trueai_tot_reports.
	column trueai_tot_reports
		dataType: int64
		formatString: 0
		lineageTag: 84e071a7-0568-46c0-991a-3053309f332b
		summarizeBy: sum
		sourceColumn: trueai_tot_reports

		annotation SummarizationSetBy = Automatic

	/// Column trueai_user_behavior.
	column trueai_user_behavior
		dataType: string
		lineageTag: 1dad99cb-bc68-4132-9646-495da058d78b
		summarizeBy: none
		sourceColumn: trueai_user_behavior

		annotation SummarizationSetBy = Automatic

	/// Column trueai_user_behavior_conf.
	column trueai_user_behavior_conf
		dataType: double
		lineageTag: 683b07b3-ff57-4646-94f0-fb56b861d65b
		summarizeBy: sum
		sourceColumn: trueai_user_behavior_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column trueai_user_role.
	column trueai_user_role
		dataType: string
		lineageTag: 07809288-a56c-41c7-8d6e-10ec0f59ff64
		summarizeBy: none
		sourceColumn: trueai_user_role

		annotation SummarizationSetBy = Automatic

	/// Column trueai_user_role_function.
	column trueai_user_role_function
		dataType: string
		lineageTag: 819444c8-ef96-45ff-a46d-1127dad28dbc
		summarizeBy: none
		sourceColumn: trueai_user_role_function

		annotation SummarizationSetBy = Automatic

	/// Column trueai_ext_match_id.
	column trueai_ext_match_id
		dataType: string
		lineageTag: ab1752ca-641d-449c-8780-fa095c259277
		summarizeBy: none
		sourceColumn: trueai_ext_match_id

		annotation SummarizationSetBy = Automatic

	/// Column trueai_addr_city.
	column trueai_addr_city
		dataType: string
		lineageTag: 17bee56d-de2c-410a-b5b0-1afa64b937e8
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	/// Column trueai_addr_country.
	column trueai_addr_country
		dataType: string
		lineageTag: 909587ea-2f7e-4881-8f97-e67bd83bc108
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	/// Column trueai_addr_lat.
	column trueai_addr_lat
		dataType: string
		lineageTag: 1f59d1c0-ff67-4320-a5d5-a13720a36583
		summarizeBy: none
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

	/// Column trueai_addr_long.
	column trueai_addr_long
		dataType: string
		lineageTag: d5ae8cf7-f22a-4a5c-bfc4-c63144addb4e
		summarizeBy: none
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

	/// Column trueai_addr_postal_code.
	column trueai_addr_postal_code
		dataType: string
		lineageTag: ae56a79a-6ffe-4c7d-a3c6-b72a1496a7c4
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	/// Column trueai_addr_state.
	column trueai_addr_state
		dataType: string
		lineageTag: 2973b9b3-5646-40bc-b391-0d83d1b9a85b
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	/// Column trueai_addr_street.
	column trueai_addr_street
		dataType: string
		lineageTag: e7af5217-4f94-4041-8a65-a0ed6d3e569d
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	/// Column _sys_as_of.
	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: 01c4d45a-745f-4cb6-b7e7-1f1acbfad955
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: cfb760d6-75b0-4fb4-836f-0ebc3608b162
			defaultHierarchy: LocalDateTable_5917abda-dc67-44a0-94a1-8678a3226c8d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column _sys_last_modified_on.
	column _sys_last_modified_on
		dataType: string
		lineageTag: 5099ac15-aca1-4362-8db0-abca097fedaf
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		annotation SummarizationSetBy = Automatic

	/// Column crm_created_on.
	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: dc9d3a00-e31a-4a6c-afaa-53f1e44cda1b
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: a2eb8793-deeb-40e4-912a-3753aed4dbc9
			defaultHierarchy: LocalDateTable_5a83a7a4-1474-4283-a2a1-94176cdb67f8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column crm_mgr_id.
	column crm_mgr_id
		dataType: string
		lineageTag: 2afa1516-9a51-4ff1-b4f7-abbd18249c5e
		summarizeBy: none
		sourceColumn: crm_mgr_id

		annotation SummarizationSetBy = Automatic

	/// Column trueai_is_mgr.
	column trueai_is_mgr
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 36020f96-ee07-4ab9-8d40-c49913104866
		summarizeBy: none
		sourceColumn: trueai_is_mgr

		annotation SummarizationSetBy = Automatic

	/// Column trueai_mgr_id.
	column trueai_mgr_id
		dataType: string
		lineageTag: 4601aa99-7f93-4fc3-8523-aa8ec205a8d7
		summarizeBy: none
		sourceColumn: trueai_mgr_id

		annotation SummarizationSetBy = Automatic

	/// Column trueai_mgr_id_conf.
	column trueai_mgr_id_conf
		dataType: string
		lineageTag: 8a99b0b9-a24d-44cc-bc78-d045a0df7871
		summarizeBy: none
		sourceColumn: trueai_mgr_id_conf

		annotation SummarizationSetBy = Automatic

	/// Column trueai_mgr_id_rule.
	column trueai_mgr_id_rule
		dataType: string
		lineageTag: a23a3287-09c6-48d5-a9d2-8b6c267293d8
		summarizeBy: none
		sourceColumn: trueai_mgr_id_rule

		annotation SummarizationSetBy = Automatic

	/// Column trueai_mgr_ids.
	column trueai_mgr_ids
		dataType: string
		lineageTag: 9edfc1e6-1337-4ec0-ad0f-98550f579e34
		summarizeBy: none
		sourceColumn: trueai_mgr_ids

		annotation SummarizationSetBy = Automatic

	/// Column trueai_user_role_alias.
	column trueai_user_role_alias
		dataType: string
		lineageTag: d509693b-d023-4191-a8f2-c39bd13ad345
		summarizeBy: none
		sourceColumn: trueai_user_role_alias

		annotation SummarizationSetBy = Automatic

	/// Column trueai_is_dummy.
	column trueai_is_dummy
		dataType: string
		lineageTag: 1a03b307-5dc0-4786-b0cc-9051f8b2ef7a
		summarizeBy: none
		sourceColumn: trueai_is_dummy

		annotation SummarizationSetBy = Automatic

	/// Column trueai_test.
	column trueai_test
		dataType: string
		lineageTag: 7dc89770-0cd1-4bf1-bbd3-afb4a8329bdb
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	/// Column trueai_test_conf.
	column trueai_test_conf
		dataType: string
		lineageTag: 8e14bb63-0f0a-4a2e-ac01-03df035fb4e4
		summarizeBy: none
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

	/// Column trueai_test_rule.
	column trueai_test_rule
		dataType: string
		lineageTag: 135cffad-591b-4abd-b2e1-4843241ab7e4
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	/// Column trueai_test_debug.
	column trueai_test_debug
		dataType: string
		lineageTag: f97e3f65-06dc-4363-a992-b2de0f0128b8
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	/// Column cust_text1.
	column cust_text1
		dataType: string
		lineageTag: 4055c002-fd11-4060-8739-ae9c5e258665
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	/// Column cust_text2.
	column cust_text2
		dataType: string
		lineageTag: a358027e-9e42-440d-8ded-f0d3840151e5
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	/// Column cust_text3.
	column cust_text3
		dataType: string
		lineageTag: 0da4c891-486c-4a2c-9574-0531aa33d3b6
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	/// Column cust_text4.
	column cust_text4
		dataType: string
		lineageTag: 2f4e28c5-8f72-4884-a53d-09d374cf4995
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	/// Column cust_text5.
	column cust_text5
		dataType: string
		lineageTag: 1c8f88b9-f53b-4d46-850b-02a2459cbfc5
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	/// Column cust_num1.
	column cust_num1
		dataType: string
		lineageTag: ca15375e-3a45-4a85-b0d1-13b649c21567
		summarizeBy: none
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

	/// Column cust_num2.
	column cust_num2
		dataType: string
		lineageTag: 3a058f8a-1b66-4036-86c7-76fac432f470
		summarizeBy: none
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

	/// Column cust_num3.
	column cust_num3
		dataType: string
		lineageTag: f037801e-f665-4d0a-a054-92503e65f3eb
		summarizeBy: none
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

	/// Column cust_num4.
	column cust_num4
		dataType: string
		lineageTag: 851dfcb4-1267-46c3-bce5-85031d3ff625
		summarizeBy: none
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

	/// Column cust_num5.
	column cust_num5
		dataType: string
		lineageTag: 7a895c66-514e-4601-8dd1-ddfbc4c51ed1
		summarizeBy: none
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

	/// Column cust_num6.
	column cust_num6
		dataType: string
		lineageTag: 19a7fa22-e2e7-4861-bd79-5a2452670c18
		summarizeBy: none
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

	/// Column cust_num7.
	column cust_num7
		dataType: string
		lineageTag: 5305c33d-2835-4433-bbea-762e30818729
		summarizeBy: none
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

	/// Column cust_bool1.
	column cust_bool1
		dataType: string
		lineageTag: 314c34ac-53b0-4b19-a314-2073fc9adad7
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	/// Column cust_bool2.
	column cust_bool2
		dataType: string
		lineageTag: 34226511-a655-448e-9caa-84de7fc3a1ab
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	/// Column crm_deep_link.
	column crm_deep_link
		dataType: string
		lineageTag: 11798ff7-85e8-4095-801c-db622bb3bbdc
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	/// Column trueai_full_name.
	column trueai_full_name
		dataType: string
		lineageTag: 8d9cfe56-4809-4209-a4ed-32c97eb44ef3
		summarizeBy: none
		sourceColumn: trueai_full_name

		annotation SummarizationSetBy = Automatic

	/// Column trueai_ramping_status.
	column trueai_ramping_status
		dataType: string
		lineageTag: 681b6bb4-b625-44b4-81d3-98a27457dd06
		summarizeBy: none
		sourceColumn: trueai_ramping_status

		annotation SummarizationSetBy = Automatic

	/// Column crm_department.
	column crm_department
		dataType: string
		lineageTag: 40f11553-dcaa-4303-9369-d83dc74428f0
		summarizeBy: none
		sourceColumn: crm_department

		annotation SummarizationSetBy = Automatic

	/// Column trueai_user_role_department.
	column trueai_user_role_department
		dataType: string
		lineageTag: 4d1fdc1d-650b-454e-9725-61f96efc8863
		summarizeBy: none
		sourceColumn: trueai_user_role_department

		annotation SummarizationSetBy = Automatic

	partition managers_total-1e9c1d18-8951-48a4-935b-6c298a055af3 = m
		mode: import
		source = ```
				let
				  dbTable = getDBTable("users"), // get the right table
				
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{
				    {"_sys_as_of", type datetime}, 
				    {"_sys_co_id", type text}, 
				    {"_sys_doc_id", type text}, 
				    {"_sys_filt_end_date", type datetime}, 
				    {"_sys_filt_start_date", type datetime},
				     {"crm_addr_city", type text}, 
				     {"crm_addr_country", type text}, 
				     {"crm_addr_postal_code", type text}, 
				     {"crm_addr_state", type text}, 
				     {"crm_addr_street", type text}, 
				     {"crm_created_on", type datetime}, 
				     {"crm_creator_id", type text}, 
				     {"crm_department", type text}, 
				     {"crm_division", type text}, 
				     {"crm_email", type text}, 
				     {"crm_first_name", type text}, 
				     {"crm_language_locale", type text}, 
				     {"crm_last_login_time", type datetime}, 
				     {"crm_last_name", type text}, 
				     {"crm_locale", type text},
				      {"crm_mgr_id", type text},
				     {"crm_profile_url", type text}, 
				      {"crm_role", type text}, 
				     {"crm_time_zone", type text}, 
				      {"crm_title", type text}, 
				      {"crm_user_type", type text}, 
				      {"crm_username", type text},
				      {"trueai_billable", type logical},
				        {"trueai_direct_reports", Int64.Type}, 
				         {"trueai_group", type text}, 
				         {"trueai_hire_date", type datetime},
				         {"trueai_is_mgr", type logical},
				         {"trueai_mgr_id", type text},
				         {"trueai_mgr_ids", type text}, 
				         {"trueai_performance_lvl_reached_on", type datetime}, 
				         {"trueai_role", type text}, 
				         {"trueai_role_conf", type number}, 
				         {"trueai_tenure", Int64.Type}, 
				         {"trueai_termination_date", type datetime}, 
				         {"trueai_title", type text},
				          {"trueai_title_conf", type number}, 
				          {"trueai_tot_reports", Int64.Type}, 
				          {"trueai_user_behavior", type text}, 
				          {"trueai_user_behavior_conf", type number}, 
				          {"trueai_user_role", type text}, {"trueai_user_role_department", type text}, {"trueai_user_role_function", type text}, {"trueai_ext_match_rule", type text}, {"trueai_group_rule", type text}})
				in
				    dbTableTyped
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

