/// Reference list of definitions for all AI-generated predictive and descriptive scores, including value ranges and interpretations.
table metadata_ai_scores
	lineageTag: 8c96acad-793d-4bbe-aa0a-cbaa0c12a741

	/// Measure meas.ai_scores_accts_industry.
	measure 'meas.ai_scores_accts_industry' = ```
			
			 
			var res =  [meas.ai_scores_accts_industry_factor1_value] //only one factor
			
			RETURN res
			
			```
		displayFolder: _ai_scores
		lineageTag: 39d3ccd2-4aed-49b7-b32f-ac492b682508

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_accts_leadsource.
	measure 'meas.ai_scores_accts_leadsource' =
			
			var res =  [meas.ai_scores_accts_leadsource_factor1_value] //only one factor
			
			RETURN res
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 6edc7b57-1ed7-4b22-a243-e12a42d84457

	/// Measure meas.ai_scores_adj_duration.
	measure 'meas.ai_scores_adj_duration' =
			
			
			var res =  [meas.ai_scores_adj_duration_factor1_value] //only one factor
			
			RETURN res
		displayFolder: _ai_scores
		lineageTag: bee85b55-4935-465e-8db3-e6991a3963ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_booking_calibration.
	measure 'meas.ai_scores_booking_calibration' = ```
			
			
			
			var factor1 = [meas.ai_scores_booking_calibration_factor1_value]
			var factor2 = [meas.ai_scores_booking_calibration_factor2_value] 
			
			var res  = ((factor1 - ABS(factor1 - factor2))/factor1) + 0
			RETURN res
			```
		displayFolder: _ai_scores
		lineageTag: fe57f762-597f-4e7c-9903-2ed634cc1ca7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_ci_act_capt_lvl_conf.
	measure 'meas.ai_scores_ci_act_capt_lvl_conf' = ```
			
			var res = [meas.ai_scores_ci_act_capt_lvl_conf_factor1_value]
			RETURN res
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 1ae2915d-2f9a-429a-b17f-33652be146a2

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ci_closing_ability.
	measure 'meas.ai_scores_ci_closing_ability' = ```
			
			var res = [meas.ai_scores_ci_closing_ability_factor1_value]
			RETURN res
			
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 4888116b-57c6-429e-8d22-8967a530b922

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ci_deal_maxing.
	measure 'meas.ai_scores_ci_deal_maxing' =
			var res = [meas.ai_scores_ci_deal_maxing_factor1_value]
			RETURN res
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 0e74b849-e97e-41d2-a4ee-873849a195d4

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ci_discovery_skill.
	measure 'meas.ai_scores_ci_discovery_skill' = ```
			
			var res = [meas.ai_scores_ci_discovery_skill_factor1_value]
			RETURN res
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 05f956cc-5b30-4db1-b18d-36e82949a976

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ci_engagement_ability.
	measure 'meas.ai_scores_ci_engagement_ability' =
			
			var res = [meas.ai_scores_ci_engagement_ability_factor1_value]
			RETURN res
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: d1d117c0-9de0-4ac1-87a1-4d782ed1f5e2

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ci_time_alloc.
	measure 'meas.ai_scores_ci_time_alloc' =
			
			var res = [meas.ai_scores_ci_time_allocation_factor1_value]
			RETURN res
		displayFolder: _ai_scores
		lineageTag: b6e53d64-157d-4cbc-8e38-cd45f65edd04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_ci_time_management.
	measure 'meas.ai_scores_ci_time_management' =
			var res = [meas.ai_scores_ci_time_management_factor1_value]
			RETURN res
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 38e27337-d1d7-4a2d-9f40-6ae4a69a77cd

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ci_work_effort.
	measure 'meas.ai_scores_ci_work_effort' =
			var res = [meas.ai_scores_ci_work_effort_factor1_value]
			RETURN res
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: deabf2f9-57f3-4a97-9dea-2b23763af9ec

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_general_score.
	measure 'meas.ai_scores_general_score' =
			
			var res = [meas.ai_scores_general_score_factor1_value]            // get the factor value 1
			
			RETURN res
		displayFolder: _ai_scores
		lineageTag: d1e3c7ab-a026-4e6f-a235-6a3dc9a158a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_leads_industry.
	measure 'meas.ai_scores_leads_industry' = ```
			 
			var res =  [meas.ai_scores_leads_industry_factor1_value] //only one factor
			
			RETURN res
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: c3045d71-e4f5-44c6-ad52-00ff64d08878

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_leads_leadsource.
	measure 'meas.ai_scores_leads_leadsource' = ```
			 
			var res =  [meas.ai_scores_leads_leadsource_factor1_value] //only one factor
			
			RETURN res
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: b002e3a1-c0f2-4749-83d7-a51aeeaf582b

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_line_items_products.
	measure 'meas.ai_scores_line_items_products' = ```
			
			var _won_ratio_raw = [meas.ai_scores_line_items_products_factor1_value]
			var _lost_ratio_raw = [meas.ai_scores_line_items_products_factor2_value]
			
			// Normalize if factors are already expressed as percentages
			var _won_ratio = IF(_won_ratio_raw > 1, _won_ratio_raw / 100, _won_ratio_raw)
			var _lost_ratio = IF(_lost_ratio_raw > 1, _lost_ratio_raw / 100, _lost_ratio_raw)
			
			var _won_weight = 0.70           // won weight
			var _lost_weight = 0.30         // lost deals ratio
			
			var score = (_won_ratio * _won_weight) + (_lost_ratio * _lost_weight)
			var res = MIN(MAX(ROUND(score * 100, 0), 0), 100)
			
			RETURN
			res
			
			
			```
		displayFolder: _ai_scores
		lineageTag: 4c75bc0f-737e-476b-96b1-b0128b90af70

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_list_price.
	measure 'meas.ai_scores_list_price' = ```
			
			var total_list_items = [meas.ai_scores_list_price_items_factor1_value]
			var total_list_items_non_default = [meas.ai_scores_list_price_items_non_default_factor2_value]
			var total_list_items_default = total_list_items- total_list_items_non_default
			 
			var score = DIVIDE(total_list_items_non_default, total_list_items )* 0.49 + DIVIDE(total_list_items_default, total_list_items) // penalize non default scores
			
			RETURN  score
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: e67aca4d-ec1b-45f3-8cbe-5d652675365b

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_opps_history.
	measure 'meas.ai_scores_opps_history' = ```
			
			VAR factor1 = [meas.ai_scores_opps_history_factor1_value]
			VAR factor2 = [meas.ai_scores_opps_history_factor2_value]
			    
			VAR res =  MIN(DIVIDE ( factor1, factor2, 0 ) ,1)
			RETURN res
			```
		formatString: 0.0
		displayFolder: _ai_scores
		lineageTag: 32567516-5874-4226-8182-cabb1f40e3b7

	/// Measure meas.ai_scores_opps_industry.
	measure 'meas.ai_scores_opps_industry' = ```
			
			var score =  [meas.ai_scores_opps_industry_factor1_value]
			
			RETURN score
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 1dd141b1-c365-410b-bf6d-92c294828494

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_opps_leadsource.
	measure 'meas.ai_scores_opps_leadsource' = ```
			
			var score =  [meas.ai_scores_opps_leadsource_factor1_value]
			
			RETURN score
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 43a832da-356c-4608-a410-ede250550799

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_performance_tiers.
	measure 'meas.ai_scores_performance_tiers' = ```
			
			var score =  [meas.ai_scores_performance_tiers_factor1_value]
			
			RETURN score
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 78a3895d-3611-4430-9285-08fd177c3411

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_potential_acv.
	measure 'meas.ai_scores_potential_acv' = ```
			var score = [meas.ai_scores_potential_acv_factor1_value]
			
			RETURN score
			
			```
		displayFolder: _ai_scores
		lineageTag: 3edc768e-8bd8-4721-9657-09aca139c796

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_pred_existing_customer_selling.
	measure 'meas.ai_scores_pred_existing_customer_selling' = ```
			
			
			var factor1 = [meas.ai_scores_existing_customer_selling_factor1_value]
			var factor2 =  [meas.ai_scores_existing_customer_selling_factor2_value]
			var normalized_factor1  = (MAX((factor1-0.5),0)) + 0.5  // realize that 0.5 is useless, but boost back up so good is not 0.5
			var normalized_factor2  = MAX(factor2, 0) // avoid neg numbers from factor2
			var score  = ((normalized_factor2 + factor1)/2) 
			
			
			RETURN score
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: a9831dbf-5682-4d58-a09e-79f6ce0ad1b2

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_pred_new_logo_selling.
	measure 'meas.ai_scores_pred_new_logo_selling' = ```
			var factor1 = [meas.ai_scores_new_logo_selling_factor1_value]
			var factor2 =  [meas.ai_scores_new_logo_selling_factor2_value]
			var normalized_factor1  = (MAX((factor1-0.5),0)) + 0.5  // realize that 0.5 is useless, but boost back up so good is not 0.5
			var normalized_factor2  = MAX(factor2, 0) // avoid neg numbers from factor2
			var score  = ((normalized_factor2 + factor1)/2) 
			
			
			RETURN score
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 3ba649b8-a4e2-40c5-bf3f-1f5bb9013d4d

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_pred_post_sales_support.
	measure 'meas.ai_scores_pred_post_sales_support' = ```
			var factor1 = [meas.ai_scores_post_sales_support_factor1_value]
			var factor2 =  [meas.ai_scores_post_sales_support_factor2_value]
			var normalized_factor1  = (MAX((factor1-0.5),0)) + 0.5  // realize that 0.5 is useless, but boost back up so good is not 0.5
			var normalized_factor2  = MAX(factor2, 0) // avoid neg numbers from factor2
			var score  = ((normalized_factor2 + factor1)/2) 
			
			
			RETURN score
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: a05cab4f-fb40-4494-a49f-2f96bd1b3638

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_pred_prospecting.
	measure 'meas.ai_scores_pred_prospecting' = ```
			var factor1 = [meas.ai_scores_prospecting_factor1_value]
			var factor2 =  [meas.ai_scores_prospecting_factor2_value]
			var normalized_factor1  = (MAX((factor1-0.5),0)) + 0.5  // realize that 0.5 is useless, but boost back up so good is not 0.5
			var normalized_factor2  = MAX(factor2, 0) // avoid neg numbers from factor2
			var score  = ((normalized_factor2 + factor1)/2) 
			
			
			RETURN score
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: afb705db-0fbb-45c5-a1b2-b2608189e2fc

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ramping.
	measure 'meas.ai_scores_ramping' = ```
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			var applicable_rows_tbl = CALCULATETABLE(users_history, users_history[col.ci.perf_ramping_status] ="Ramping" ,  LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <  toDate   && if(isblank([trueai_termination_date]), date(2100,1,1),[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			var _cnt = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, users_history[_sys_user_id]))) // get a disctinct count of users from that filter context 
			var ramp_rate  = MIN(_cnt/3, 1)       // get the minimum if there is no ramping reps 
			var perf_score =  CALCULATE(
			    AVERAGE(users_history[ci_perf_qtly_performance_tier_conf]),       // get the avg perf conf
			    users_history[col.ci.perf_ramping_status] ="Ramping"
			)
			var score = (ramp_rate * perf_score)
			var res = score 
			RETURN
			res
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 822304c1-edef-4bc0-9017-2b3f2f278fc0

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_rep_org_calibration.
	measure 'meas.ai_scores_rep_org_calibration' =
			
			VAR factor1 = [meas.ai_scores_rep_org_calibration_factor1_value]
			VAR factor2 = [meas.ai_scores_rep_org_calibration_factor2_value]
			VAR factor3 = [meas.ai_scores_rep_org_calibration_factor3_value]
			
			-- weight to apply
			VAR w = 2
			
			-- Build a table with named columns, then remove blanks
			VAR temp_tbl =
			    FILTER (
			        SELECTCOLUMNS (
			            {
			                (factor1, w),
			                (factor2, w),
			                (factor3, w)
			            },
			            "Value", [Value1],
			            "Weight", [Value2]
			        ),
			        NOT ISBLANK ( [Value] )
			    )
			
			-- Weighted score calculation
			VAR _adj = SUMX ( temp_tbl, [Value] * [Weight] )
			VAR _wt = SUMX ( temp_tbl, [Weight] )
			VAR raw_score = DIVIDE ( _adj, _wt )
			
			-- Clamp score between 0 and 1
			VAR safe = MIN ( MAX ( raw_score, 0 ), 1 )
			
			RETURN safe
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 65e27ada-7d1f-40df-8bd5-50a4fa39c4d5

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_revenue_calibration.
	measure 'meas.ai_scores_revenue_calibration' =
			
			
			var factor1 = [meas.ai_scores_revenue_calibration_factor1_value]
			VAR factor2 = [meas.ai_scores_revenue_calibration_factor2_value]
			var score = (factor1 - ABS(factor1 - factor2))/factor1
			
			var res = IF(
			    factor1=BLANK() || factor1=0, 0, score
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 8a9703ba-19d0-4204-b805-7268fdae0e11

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ssr_industry.
	measure 'meas.ai_scores_ssr_industry' = ```
			
			
			var _conf = [meas.ai_scores_ssr_industry_factor1_value]
			RETURN 
			_conf
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: a6abcf69-3766-4bdd-a60f-4984323b5532

	/// Measure meas.ai_scores_ssr_leadsource.
	measure 'meas.ai_scores_ssr_leadsource' = ```
			var _conf = [meas.ai_scores_ssr_leadsource_factor1_value]
			RETURN 
			_conf
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 1d6becd4-7779-4caa-8d84-d7fdf6c1e334

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_success_factor_analysis.
	measure 'meas.ai_scores_success_factor_analysis' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var  train_score= MAXX(latest_row, companies_history[di_success_prob_training_score])     // get the latest train score
			var  validation_score= MAXX(latest_row, companies_history[di_success_prob_validation_score])     // get the latest validation score
			
			var boost_expo = 0.65 // to get closer to one if good score after the score has been calcualted
			var train_score_norm  = MAX(train_score, 0) // avoid neg
			var validation_score_norm  = (MAX((validation_score-0.5),0)) + 0.5  // realize that 0.5 is useless, but boost back up so good is not 0.5
			var score  = ((train_score_norm + validation_score_norm)/2) ^ boost_expo  // avg of both normalized score + boosting
			
			
			RETURN score
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: c40817e6-7a7d-4281-a04b-007ed3fc01ae

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_vi.
	measure 'meas.ai_scores_vi' =
			
			var factor1 = [meas.ai_scores_vi_step_diff_factor1_value]      // get the factor 1
			var factor2 = [meas.ai_scores_vi_tuning_share_diff_factor2]         // get factor 2
			var score = (1 - ABS(factor1+factor2)/2)
			var _conf = score
			RETURN
			_conf
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: cfeadcc9-0cb2-4247-9637-d0de514fa8d2

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_ci_time_allocation_factor2_value.
	measure 'meas.ai_scores_ci_time_allocation_factor2_value' =
			
			BLANK()
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: fe8e4dc4-c3c2-464d-b0f2-7bd0aa9e848e

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_existing_customer_selling_factor2_value.
	measure 'meas.ai_scores_existing_customer_selling_factor2_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var existing_cust_r2 = MAXX(latest_row, companies_history[di_pred_existing_customer_selling_r2])     // get the latest r2 for existing customer
			RETURN existing_cust_r2
			
			```
		displayFolder: _factor2_value
		lineageTag: b34ca4b8-d776-45ed-abf4-257a00ba6cb3

	/// Measure meas.ai_scores_line_items_products_factor2_value.
	measure 'meas.ai_scores_line_items_products_factor2_value' = ```
			
			var lost_deals = CALCULATE(
			    COUNT(opps[_sys_doc_id]),                // get the won deals
			    opps[trueai_is_won]=False
			)
			VAR lost_deals_w_line = CALCULATE(
			        DISTINCTCOUNT(opp_line_items[crm_opp_id]), 
			        opps[trueai_is_won] = False                      // get the won 
			)
			var res = DIVIDE(lost_deals_w_line,lost_deals,0)         // won ratio
			RETURN res
			
			
			
			
			
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: 322eccea-e9fc-4cd4-a1b6-b6fe7ce95cc0

	/// Measure meas.ai_scores_list_price_items_non_default_factor2_value.
	measure 'meas.ai_scores_list_price_items_non_default_factor2_value' =
			
			var total_list_items = CALCULATE(
			    count(opp_line_items[trueai_list_price]),      // non default list price items count
			    opp_line_items[trueai_list_price_rule] <> 103007
			)
			
			RETURN total_list_items+0
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: c5ff1078-9327-4f70-a364-ff94ac70d80d

	/// Measure meas.ai_scores_new_logo_selling_factor2_value.
	measure 'meas.ai_scores_new_logo_selling_factor2_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var new_logo_r2 = MAXX(latest_row, companies_history[di_pred_new_logo_r2])     // get the latest r2 for new_logo_selling
			RETURN new_logo_r2
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: 4c4ee231-057d-4fa7-89af-0d13823b5247

	/// Measure meas.ai_scores_post_sales_support_factor2_value.
	measure 'meas.ai_scores_post_sales_support_factor2_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var post_sales_r2 = MAXX(latest_row, companies_history[di_pred_post_sales_r2])     // get the latest r2 for post sales support
			RETURN post_sales_r2
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: 231f7961-a090-4d9f-be9c-c8b5b2f33117

	/// Measure meas.ai_scores_prospecting_factor2_value.
	measure 'meas.ai_scores_prospecting_factor2_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var prospect_r2 = MAXX(latest_row, companies_history[di_pred_prospecting_r2])     // get the latest r2 for prospecting
			RETURN prospect_r2
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: f066aabf-c00d-4d88-b0a5-6779029d7b86

	/// Measure meas.ai_scores_ramping_perf_conf_factor2_value.
	measure 'meas.ai_scores_ramping_perf_conf_factor2_value' = ```
			
			var _perf = CALCULATE(
			    AVERAGE(users_history[ci_perf_qtly_performance_tier_conf]),       // get the avg perf conf
			    users_history[col.ci.perf_ramping_status] ="Ramping"
			)
			RETURN _perf+0
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: 2efec14a-78b8-40f8-97f9-9640fb62a3b6

	/// Measure meas.ai_scores_success_factor_analysis_factor2_value.
	measure 'meas.ai_scores_success_factor_analysis_factor2_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var  valid_score= MAXX(latest_row, companies_history[di_success_prob_validation_score])     // get the latest validation score
			RETURN valid_score
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: 41c60942-a8ee-4d5f-9a96-1574649cd7d0

	/// Measure meas.ai_scores_vi_tuning_share_diff_factor2.
	measure 'meas.ai_scores_vi_tuning_share_diff_factor2' = ```
			
			var diff2 = [meas.ssr_history_vi_tuning_shares_diff]        // diff 2
			
			RETURN diff2
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: 42241314-6700-4f39-8ab0-197a961b6fc8

	/// Measure meas.ai_scores_accts_industry_factor1_value.
	measure 'meas.ai_scores_accts_industry_factor1_value' =
			
			var _avg = CALCULATE(
			    AVERAGE(ssr[trueai_industry_conf])         // get the accounts average industry conf
			)
			RETURN
			_avg
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: c64dac32-b1b6-4e5c-8888-326add4a49eb

	/// Measure meas.ai_scores_accts_leadsource_factor1_value.
	measure 'meas.ai_scores_accts_leadsource_factor1_value' =
			
			var _avg = CALCULATE(
			    AVERAGE(ssr[trueai_leadsource_conf])         // get the accounts average leadsource conf
			)
			RETURN
			_avg
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 4af4dbbd-e95b-4791-af28-13336540d499

	/// Measure meas.ai_scores_adj_duration_factor1_value.
	measure 'meas.ai_scores_adj_duration_factor1_value' = ```
			
			VAR _tbl = CALCULATETABLE(ssr_history, ssr_history[step_name] in {"Prospecting", "New Logo Selling", "Post-Sales Support","Existing Customer Selling"}) // Get the current table context but exclude the unthcouded stage etc
			VAR res = AVERAGEX(
			    _tbl,
			     SWITCH(
			        ssr_history[stkhlds_all_adj_dur_rule],
			        "133002", 0.4,  // 133002 is industry avg, not reliable
			        "133001", 0.7,   // 133001 is peer avg, okay
			        "133003", 0.97,   // 133003 is the best info from the owner
			        "133004", 0.86    // 133004 is good data but not from the primary owner
			    )
			)
			
			RETURN 
			res
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 78730502-80ca-4cce-b42d-5234fd16169f

	/// Measure meas.ai_scores_ci_act_capt_lvl_conf_factor1_value.
	measure 'meas.ai_scores_ci_act_capt_lvl_conf_factor1_value' = ```
			
			var _avg = CALCULATE(
			    AVERAGE(users_history[ci_act_capt_lvl_conf]), users[trueai_user_role_function] in {"AM", "AE", "SDR"}        // get the users_history average ci_act_capt_lvl
			)
			RETURN _avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 1da7cd80-ae31-496a-abfd-cdada445fdba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_ci_closing_ability_factor1_value.
	measure 'meas.ai_scores_ci_closing_ability_factor1_value' = ```
			
			var res = CALCULATE(
			    AVERAGE(users_history[ci_sb_closing_ability_conf]), users[trueai_user_role_function] in {"AM", "AE"} )        // get the avg closing ability conf / just for AM/AE roles
			RETURN res 
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: cbcac673-2f14-4dbc-a705-37568fd63a3c

	/// Measure meas.ai_scores_ci_deal_maxing_factor1_value.
	measure 'meas.ai_scores_ci_deal_maxing_factor1_value' =
			
			var _avg = CALCULATE(
			    AVERAGE(users_history[ci_sb_deal_maxing_conf]), users[trueai_user_role_function] in {"AM", "AE"}        // get the avg deal maximizing conf
			)
			RETURN
			_avg
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 641533dd-85cb-40a0-8913-51d2d2fd5f8d

	/// Measure meas.ai_scores_ci_discovery_skill_factor1_value.
	measure 'meas.ai_scores_ci_discovery_skill_factor1_value' = ```
			
			var res = CALCULATE(
			    AVERAGE(users_history[ci_sb_discov_skills_conf]), users[trueai_user_role_function] in {"AM", "AE", "SDR"} )        // get the avg closing ability conf / just for AM/AE SDR roles
			RETURN res 
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 3c99cf6e-6884-423f-9b93-d1b1dd48eac0

	/// Measure meas.ai_scores_ci_engagement_ability_factor1_value.
	measure 'meas.ai_scores_ci_engagement_ability_factor1_value' =
			
			var _avg = CALCULATE(
			    AVERAGE(users_history[ci_sb_engmt_ability_conf]),        // get the avg engagement ability conf
			    users[trueai_user_role_function] in  {"AE", "AM", "SDR"}
			)
			RETURN
			_avg
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 4346bd13-950f-4f44-bc11-c472b65fe848

	/// Measure meas.ai_scores_ci_time_allocation_factor1_value.
	measure 'meas.ai_scores_ci_time_allocation_factor1_value' = ```
			
			
			var res = CALCULATE(
			    AVERAGE(users_history[ci_time_alloc_conf]), users[trueai_user_role_function] in {"AM", "AE", "SDR"} )        // get the avg closing ability conf / just for AM/AE roles
			RETURN res 
			
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: ea5332c7-0de2-4daf-8cb7-1c2b6695ba96

	/// Measure meas.ai_scores_ci_time_management_factor1_value.
	measure 'meas.ai_scores_ci_time_management_factor1_value' = ```
			
			var _avg = CALCULATE(
			    AVERAGE(users_history[ci_sb_time_management_conf]) , users[trueai_user_role_function] in {"AM", "AE", "SDR"}      // get the avg time mgmt conf
			)
			
			RETURN _avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 5fdf05a9-0d69-418c-9ca9-866fcfecf9a3

	/// Measure meas.ai_scores_ci_work_effort_factor1_value.
	measure 'meas.ai_scores_ci_work_effort_factor1_value' = ```
			
			var res = CALCULATE(
			    AVERAGE(users_history[ci_sb_work_effort_conf]), users[trueai_user_role_function] in {"AM", "AE", "SDR"} )        // get the avg closing ability conf / just for AM/AE roles
			RETURN res 
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: d3d8bc69-199e-4596-bab3-1674f5efd4cb

	/// Measure meas.ai_scores_existing_customer_selling_factor1_value.
	measure 'meas.ai_scores_existing_customer_selling_factor1_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var existing_cust_auc = MAXX(latest_row, companies_history[di_pred_existing_customer_selling_auc])     // get the latest auc for existing customer
			RETURN existing_cust_auc
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 95206c4e-d225-4f46-ab3d-a9ff209b1848

	/// Measure meas.ai_scores_general_score_factor1_value.
	measure 'meas.ai_scores_general_score_factor1_value' = ```
			
			var res = CALCULATE(MAX(ssr_history_stakeholders[_sys_doc_id])) // gwet current data
			
			RETURN  if (res = BLANK(),BLANK(),1 ) // return blank if no current data
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: bcd663d2-58e2-4db4-ae3c-6ce46b4ca129

	/// Measure meas.ai_scores_leads_industry_factor1_value.
	measure 'meas.ai_scores_leads_industry_factor1_value' = ```
			
			var _avg = CALCULATE(
			    AVERAGE(ssr[trueai_industry_conf])         // get the leads average industry conf
			)
			RETURN _avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 08cd9b25-205a-48a8-bb2f-79b8052291e6

	/// Measure meas.ai_scores_leads_leadsource_factor1_value.
	measure 'meas.ai_scores_leads_leadsource_factor1_value' = ```
			
			var _avg = CALCULATE(
			    AVERAGE(ssr[trueai_leadsource_conf])         // get the leads average leadsource conf
			)
			RETURN _avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 39ebb921-3dc1-4a39-aa86-8581d8d29be8

	/// Measure meas.ai_scores_line_items_products_factor1_value.
	measure 'meas.ai_scores_line_items_products_factor1_value' = ```
			
			var won_deals = CALCULATE(
			    COUNT(opps[_sys_doc_id]),                // get the won deals
			    opps[trueai_is_won]=True
			)
			VAR _won_deals_w_line = CALCULATE(
			        DISTINCTCOUNT(opp_line_items[crm_opp_id]), 
			        opps[trueai_is_won] = True                      // get the won 
			)
			var _won_ratio = DIVIDE(_won_deals_w_line,won_deals,0)         // won ratio
			RETURN _won_ratio
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 49312bdd-1105-4544-9f95-f257873fbe76

	/// Measure meas.ai_scores_list_price_items_factor1_value.
	measure 'meas.ai_scores_list_price_items_factor1_value' = ```
			
			var total_list_items = CALCULATE(count(opp_line_items[trueai_list_price]))      // get all the list_price count 
			
			RETURN
			total_list_items+0
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 60811fc7-afd2-43dd-9e9a-2762cd8a5d74

	/// Measure meas.ai_scores_new_logo_selling_factor1_value.
	measure 'meas.ai_scores_new_logo_selling_factor1_value' =
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var new_logo_auc = MAXX(latest_row, companies_history[di_pred_new_logo_auc])     // get the latest auc for new_logo_selling
			RETURN
			FORMAT(new_logo_auc, "0.00")
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: e12ed20f-f892-45c4-aad8-7bcf1b703801

	/// Measure meas.ai_scores_opps_history_factor1_value.
	measure 'meas.ai_scores_opps_history_factor1_value' = ```
			
			
			var tbl_won_open_pipeline =
			FILTER(
			open_pipeline,
			open_pipeline[opp_is_won] = TRUE()
			)
			
			var tbl_summarized =
			SUMMARIZE(
			tbl_won_open_pipeline,
			open_pipeline[crm_opp_id],
			"unique_trueai_stage_id",
			DISTINCTCOUNT(open_pipeline[trueai_stage_id])
			)
			
			var res = AVERAGEX(tbl_summarized, [unique_trueai_stage_id])
			RETURN res
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 88220627-b28d-4a2f-a86e-a370dad00ede

	/// Measure meas.ai_scores_opps_industry_factor1_value.
	measure 'meas.ai_scores_opps_industry_factor1_value' = ```
			
			var _avg = CALCULATE(
			    AVERAGE(opps[trueai_industry_conf])         // get the opps average industry conf
			)
			RETURN _avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 93bc9da7-c7b8-40f5-b584-8add5eb22f45

	/// Measure meas.ai_scores_opps_leadsource_factor1_value.
	measure 'meas.ai_scores_opps_leadsource_factor1_value' = ```
			
			var _avg = CALCULATE(
			    AVERAGE(opps[trueai_leadsource_conf])         // get the opps average leadsource conf
			)
			RETURN _avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 72f92283-eb2d-4c76-9654-2f099e1c3dd3

	/// Measure meas.ai_scores_performance_tiers_factor1_value.
	measure 'meas.ai_scores_performance_tiers_factor1_value' = ```
			
			var perf_avg = CALCULATE(AVERAGE(users_history[ci_perf_qtly_performance_tier_conf]), users[trueai_user_role_function] in {"AM", "AE", "SDR"} )        // get the avg performance tier conf
			RETURN perf_avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: aabc3ea3-550c-4c76-8199-1a09266b4e3c

	/// Measure meas.ai_scores_post_sales_support_factor1_value.
	measure 'meas.ai_scores_post_sales_support_factor1_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var post_sales_auc = MAXX(latest_row, companies_history[di_pred_post_sales_auc])     // get the latest auc for post sales support
			RETURN post_sales_auc
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 4174000b-df69-4da9-a282-a6b9eb96248a

	/// Measure meas.ai_scores_potential_acv_factor1_value.
	measure 'meas.ai_scores_potential_acv_factor1_value' =
			
			// as we don't have some field to calculate the factor I am using here temporary variable for visualization purpose. need to apply the actual field while available
			var temp = CALCULATE(AVERAGE(ssr[trueai_complt_all]))    // temp value for factor analysis
			RETURN
			temp
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: c765acfb-e0f7-4ce1-9cca-f1cd0c47a018

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_prospecting_factor1_value.
	measure 'meas.ai_scores_prospecting_factor1_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var prospect_auc = MAXX(latest_row, companies_history[di_pred_prospecting_auc])     // get the latest auc for prospecting
			RETURN prospect_auc
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 0972da0d-d92d-40d3-88b6-31b91bae569f

	/// Measure meas.ai_scores_ramping_count_rate_factor1_value.
	measure 'meas.ai_scores_ramping_count_rate_factor1_value' = ```
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, users_history[col.ci.perf_ramping_status] ="Ramping" ,  LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <  toDate   && if(isblank([trueai_termination_date]), date(2100,1,1),[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			
			var _cnt = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, users_history[_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			var res  = MIN(_cnt/3, 1)       // get the minimum if there is no ramping reps 
			RETURN
			res+0
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 9efba05e-5ee4-4205-805d-1baca8e33807

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_rep_org_calibration_factor1_value.
	measure 'meas.ai_scores_rep_org_calibration_factor1_value' =
			
			VAR latest_table =
			    CALCULATETABLE(
			        TOPN(1, companies_history, companies_history[_sys_processed_as_of], DESC),
			        ALL(companies_history)   -- remove filters to get real latest row
			    )
			
			VAR users_match_hr_id = MAXX(latest_table, [users_match_hr_id])
			VAR users_hr_file     = MAXX(latest_table, companies_history[users_hr_file])
			
			RETURN
			IF(
			    users_hr_file = 0 || ISBLANK(users_hr_file),
			    BLANK(),  -- no HR file uploaded → ignore this factor
			    DIVIDE(users_match_hr_id, users_hr_file, 0)  -- HR file exists → always return value (0–1)
			)
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: cb095a91-0df2-4e56-81a5-262990050f8f

	/// Measure meas.ai_scores_revenue_calibration_factor1_value.
	measure 'meas.ai_scores_revenue_calibration_factor1_value' = ```
			
			var latest_table = CALCULATETABLE(TOPN(1,companies_history,companies_history[_sys_processed_as_of],DESC)) 
			var _booking_amt = MAXX(latest_table,companies_history[ttm_ref_date_revenue]) 
			RETURN
			_booking_amt
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: e880eab7-5c90-4b09-a777-fa47ae818adc

	/// Measure meas.ai_scores_ssr_industry_factor1_value.
	measure 'meas.ai_scores_ssr_industry_factor1_value' = ```
			
			var _avg = CALCULATE(
			    AVERAGE(ssr[trueai_industry_conf])         // get the ssr average industry conf
			)
			RETURN _avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 90726119-0ec7-4e1e-91ee-7bbfd2da9356

	/// Measure meas.ai_scores_ssr_leadsource_factor1_value.
	measure 'meas.ai_scores_ssr_leadsource_factor1_value' = ```
			
			var _avg = CALCULATE(
			    AVERAGE(ssr[trueai_leadsource_conf])         // get the ssr average leadsource conf
			)
			RETURN _avg
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: a4de2f14-f93d-469e-ad22-6155c5cc7c9a

	/// Measure meas.ai_scores_success_factor_analysis_factor1_value.
	measure 'meas.ai_scores_success_factor_analysis_factor1_value' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,companies_history, companies_history[_sys_processed_as_of], DESC))  // get the latest row
			var  train_score= MAXX(latest_row, companies_history[di_success_prob_training_score])     // get the latest train score
			RETURN train_score
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: a48317f5-a775-4463-bc5c-264b79724b39

	/// Measure meas.ai_scores_vi_step_diff_factor1_value.
	measure 'meas.ai_scores_vi_step_diff_factor1_value' = ```
			
			var diff1 = [meas.ssr_history_step_diff]        // diff 1
			RETURN diff1
			
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 88399f1d-a2a5-4dc6-85ab-5d9be411da54

	/// Measure meas.ai_score.
	measure 'meas.ai_score' =
			
			VAR score_id =
			    MAX( metadata_ai_scores[_sys_doc_id] )
			
			/* ===========================================================
			   1) GET RAW METRIC VALUE (may not be numeric)
			   =========================================================== */
			VAR raw_val =
			    SWITCH(
			        score_id,
			        "1",  [meas.ai_scores_pred_prospecting],
			        "2",  [meas.ai_scores_pred_new_logo_selling],
			        "3",  [meas.ai_scores_pred_post_sales_support],
			        "4",  [meas.ai_scores_pred_existing_customer_selling],
			        "5",  [meas.ai_scores_success_factor_analysis],
			        "6",  [meas.ai_scores_potential_acv],
			        "7",  [meas.ai_scores_list_price],
			        "8",  [meas.ai_scores_line_items_products],
			        "9",  [meas.ai_scores_opps_history],
			        "10", [meas.ai_scores_accts_industry],
			        "11", [meas.ai_scores_accts_leadsource],
			        "12", [meas.ai_scores_leads_industry],
			        "13", [meas.ai_scores_leads_leadsource],
			        "14", [meas.ai_scores_opps_industry],
			        "15", [meas.ai_scores_opps_leadsource],
			        "16", [meas.ai_scores_ssr_industry],
			        "17", [meas.ai_scores_ssr_leadsource],
			        "18", [meas.ai_scores_general_score],
			        "19", [meas.ai_scores_ci_act_capt_lvl],
			        "20", [meas.ai_scores_ci_act_capt_lvl_conf],
			        "21", [meas.ai_scores_ci_time_alloc],
			        "22", [meas.ai_scores_adj_duration],
			        "23", [meas.ai_scores_ci_closing_ability],
			        "24", [meas.ai_scores_ci_discovery_skill],
			        "25", [meas.ai_scores_ci_engagement_ability],
			        "26", [meas.ai_scores_ci_work_effort],
			        "27", [meas.ai_scores_ci_deal_maxing],
			        "28", [meas.ai_scores_performance_tiers],
			        "29", [meas.ai_scores_ramping],
			        "30", [meas.ai_scores_ci_time_management],
			        "31", [meas.ai_scores_vi],
			        "32", [meas.ai_scores_rep_org_calibration],
			        "33", [meas.ai_scores_booking_calibration],
			        "34", [meas.ai_scores_revenue_calibration],
			        "35", [meas.ai_scores_general_score],
			        BLANK()
			    )
			
			/* ===========================================================
			   2) ENSURE RAW VALUE IS NUMERIC (ELIMINATE TEXT/NaN)
			   =========================================================== */
			VAR pre_boost_val =
			    VAR n = VALUE(raw_val)
			    RETURN IF(ISNUMBER(n), n, 0)
			
			/* ===========================================================
			   3) READ BOOST EXPONENT (may also be non-numeric!)
			   =========================================================== */
			VAR boost_raw = MAX(metadata_ai_scores[boost_expo])
			VAR boost = IF(ISNUMBER(boost_raw), boost_raw, 1)
			
			/* ===========================================================
			   4) APPLY BOOST SAFELY (avoid fractional exponent on <=0)
			   =========================================================== */
			VAR boost_is_fraction = boost <> INT(boost)
			VAR safe_post_boost_val =
			    IF(
			        pre_boost_val <= 0 && boost_is_fraction,
			        pre_boost_val,
			        POWER(ABS(pre_boost_val), boost)
			    )
			
			/* ===========================================================
			   5) SCALE TO 0–100
			   =========================================================== */
			VAR result_score = safe_post_boost_val * 100
			
			RETURN result_score + 0
		formatString: 0
		lineageTag: a0c3cd02-2e23-4742-8929-8b59cae71b90

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_score_formula.
	measure 'meas.ai_score_formula' =
			
			var meas_name = [meas.ai_score_measure_name]
			var expr =
			    MAXX(
			        FILTER(INFO.VIEW.MEASURES(), [Name] = meas_name),
			        [Expression]
			    )
			RETURN expr
		lineageTag: b83e36cc-b2c7-44c0-9dd6-2b8a99ddc64e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_score_measure_name.
	measure 'meas.ai_score_measure_name' = ```
			
			var score_name = MAX(metadata_ai_scores[score_name])
			
			var res = SWITCH(
			    score_name,
			    "Prospecting Success Predictions", "meas.ai_scores_pred_prospecting",   
			    "New Logo Selling Success Predictions", "meas.ai_scores_pred_new_logo_selling",    // score_id 2
			    "Post-Sales Support Success Predictions", "meas.ai_scores_pred_post_sales_support",    // score_id 3
			    "Existing Customer Selling Success Predictions", "meas.ai_scores_pred_existing_customer_selling",    // score_id 4
			    "Success Factor Analysis", "meas.ai_scores_factor_analysis",                      // score id 5
			    "Potential ACV", "meas.ai_scores_potential_acv",                      // score id 6
			    "List Price", "meas.ai_scores_all_list_price",                      // score id 7
			    "Line Item Products", "meas.ai_scores_line_items_products",                      // score id 8
			    "Accounts Industry Consolidation", "meas.ai_scores_accts_industry",                // score id 9 
			    "Accounts Lead Source Consolidation", "meas.ai_scores_accts_leadsource",                // score id 10 
			    "Leads Industry Consolidation", "meas.ai_scores_leads_industry",                // score id 11 
			    "Leads Lead Source Consolidation", "meas.ai_scores_leads_leadsource",                // score id 12 
			    "Opps Industry Consolidation", "meas.ai_scores_opps_industry",                // score id 13 
			    "Opps Lead Source Consolidation", "meas.ai_scores_opps_leadsource",                // score id 14 
			    "SSR Industry Consolidation", "meas.ai_scores_ssr_industry",                // score id 15 
			    "SSR Lead Source Consolidation", "meas.ai_scores_ssr_leadsource",                // score id 16 
			    "Opportunities History", "meas.ai_scores_opps_history",                // score id 17 
			    "Leads & Accounts Completeness  Data Present","meas.ai_scores_general_score",
			    "Activity Capture Level", "meas.ai_scores_ci_act_capt_lvl",                // score id 18 
			    "Time Allocation", "meas.ai_scores_ci_time_alloc",                // score id 19 
			    "Adjusted Duration", "meas.ai_scores_adj_duration",                // score id 20 
			    "Closing Ability", "meas.ai_scores_ci_closing_ability",                  // score_id 21 
			    "Discovery Skill", "meas.ai_scores_ci_discovery_skill",               // score_id 22 
			    "Engagement Ability", "meas.ai_scores_ci_engagement_ability",                      // score_id 23 
			    "Work Effort", "meas.ai_scores_ci_work_effort",                      // score_id 24 
			    "Deal Maximizing", "meas.ai_scores_ci_deal_maxing",                        // score_id 25 
			    "Performance Tiers", "meas.ai_scores_performance_tiers",                            // score_id 26 
			    "Ramping Success", "meas.ai_scores_ramping",                                  // score_id 27 
			    "Time Management", "meas.ai_scores_ci_time_management",                // score_id 28 
			    "VI Amount", "meas.ai_scores_vi",               // score_id 24 
			    "Rep Organization Calibration", "meas.ai_scores_rep_org_calibration",
			    "Bookings Calibration", "meas.ai_scores_booking_calibration",
			    "Revenue Calibration", "meas.ai_scores_revenue_calibration",
			    BLANK()
			)
			RETURN
			res
			```
		lineageTag: c8ba0855-de67-44fd-a49b-64d5bee7ddc8

	/// Measure meas.ai_scores_factor1_name.
	measure 'meas.ai_scores_factor1_name' =
			
			var factor_name = MAX(metadata_ai_scores[factor_1_name])
			RETURN factor_name
		lineageTag: b59e2b3c-8a05-46b9-96ad-9ebdb059374c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_factor1_value.
	measure 'meas.ai_scores_factor1_value' = ```
			
			var score_name = MAX(metadata_ai_scores[score_name])
			
			var res = SWITCH(
			    score_name,
			    "Prospecting Success Predictions", [meas.ai_scores_prospecting_factor1_value],    // score_id 1
			    "New Logo Selling Success Predictions", [meas.ai_scores_new_logo_selling_factor1_value],    // score_id 2
			    "Post-Sales Support Success Predictions", [meas.ai_scores_post_sales_support_factor1_value],    // score_id 3
			    "Existing Customer Selling Success Predictions", [meas.ai_scores_existing_customer_selling_factor1_value],    // score_id 4
			    "Success Factor Analysis", [meas.ai_scores_success_factor_analysis_factor1_value],                      // score id 5
			    "Potential ACV", [meas.ai_scores_potential_acv_factor1_value],                      // score id 6
			    "List Price", [meas.ai_scores_list_price_items_factor1_value],                      // score id 7
			    "Line Item Products", [meas.ai_scores_line_items_products_factor1_value],                      // score id 8
			    "Opportunities History", [meas.ai_scores_opps_history_factor1_value],
			    "Accounts Industry Consolidation", [meas.ai_scores_accts_industry_factor1_value],                // score id 9 
			    "Accounts Lead Source Consolidation", [meas.ai_scores_accts_leadsource_factor1_value],                // score id 10 
			    "Leads Industry Consolidation", [meas.ai_scores_leads_industry_factor1_value],                // score id 11 
			    "Leads Lead Source Consolidation", [meas.ai_scores_leads_leadsource_factor1_value],                // score id 12 
			    "Opps Industry Consolidation", [meas.ai_scores_opps_industry_factor1_value],                // score id 13 
			    "Opps Lead Source Consolidation", [meas.ai_scores_opps_leadsource_factor1_value],                // score id 14 
			    "SSR Industry Consolidation", [meas.ai_scores_ssr_industry_factor1_value],                // score id 15 
			    "SSR Lead Source Consolidation", [meas.ai_scores_ssr_leadsource_factor1_value],                // score id 16 
			    "Activity Capture Level", FORMAT([meas.ai_scores_ci_act_capt_lvl_factor1_value],"0.00"),                // score  18 
			    "Activity Capture Level Confidence", [meas.ai_scores_ci_act_capt_lvl_conf_factor1_value],
			    "Time Allocation", FORMAT([meas.ai_scores_ci_time_allocation_factor1_value],"#,0"),                // score id 19 
			    "Adjusted Duration", FORMAT([meas.ai_scores_adj_duration_factor1_value],"0.00"),                // score id 20 
			    "Closing Ability", [meas.ai_scores_ci_closing_ability_factor1_value],                  // score_id 21 
			    "Discovery Skill", [meas.ai_scores_ci_discovery_skill_factor1_value],               // score_id 22 
			    "Engagement Ability", [meas.ai_scores_ci_engagement_ability_factor1_value],                      // score_id 23 
			    "Work Effort", [meas.ai_scores_ci_work_effort_factor1_value],                      // score_id 24 
			    "Deal Maximizing", [meas.ai_scores_ci_deal_maxing_factor1_value],                        // score_id 25 
			    "Performance Tiers", [meas.ai_scores_performance_tiers_factor1_value],                            // score_id 26 
			    "Ramping Success", [meas.ai_scores_ramping_count_rate_factor1_value],                                  // score_id 27 
			    "Time Management", [meas.ai_scores_ci_time_management_factor1_value],                // score_id 28 
			    "VI Amount", [meas.ai_scores_vi_step_diff_factor1_value],               // score_id 24 
			    "Rep Organization Calibration", FORMAT([meas.ai_scores_rep_org_calibration_factor1_value],"#,0"),
			    "Bookings Calibration", FORMAT([meas.ai_scores_booking_calibration_factor1_value],"$#,0"),
			    "Revenue Calibration", FORMAT([meas.ai_scores_revenue_calibration_factor1_value],"$#,0"),
			    "Leads & Accounts Completeness  Data Present", [meas.ai_scores_general_score_factor1_value]
			    
			)
			
			RETURN
			res
			```
		formatString: 0.00
		lineageTag: 822233b1-79ae-4d66-b6a1-307424c79baf

	/// Measure meas.ai_scores_factor2_name.
	measure 'meas.ai_scores_factor2_name' =
			
			var factor_name = MAX(metadata_ai_scores[factor_2_name])
			RETURN factor_name
		lineageTag: 0f4f2c54-fdd9-493c-a042-f0fbf0f14a03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_factor2_value.
	measure 'meas.ai_scores_factor2_value' = ```
			
			var score_name = MAX(metadata_ai_scores[score_name])
			
			var res = SWITCH(
			    score_name,
			    "Prospecting Success Predictions", [meas.ai_scores_prospecting_factor2_value],    // score_id 1
			    "New Logo Selling Success Predictions", [meas.ai_scores_new_logo_selling_factor2_value],    // score_id 2
			    "Post-Sales Support Success Predictions", [meas.ai_scores_post_sales_support_factor2_value],    // score_id 3
			    "Existing Customer Selling Success Predictions", [meas.ai_scores_existing_customer_selling_factor2_value],    // score_id 4
			    "Success Factor Analysis", [meas.ai_scores_success_factor_analysis_factor2_value],                      // score id 5
			    "List Price", [meas.ai_scores_list_price_items_non_default_factor2_value],                      // score id 7
			    "Line Item Products", [meas.ai_scores_line_items_products_factor2_value],                      // score id 8
			    "Opportunities History", [meas.ai_scores_opps_history_factor2_value],
			    "Time Allocation", FORMAT([meas.ai_scores_ci_time_allocation_factor2_value],"#,0"),                // score id 19  
			    "Ramping Success", [meas.ai_scores_ramping_perf_conf_factor2_value],                                  // score_id 27 
			    "VI Amount", [meas.ai_scores_vi_tuning_share_diff_factor2],               // score_id 24 
			    "Rep Organization Calibration", [meas.ai_scores_rep_org_calibration_factor2_value],
			    "Bookings Calibration", FORMAT([meas.ai_scores_booking_calibration_factor2_value], "$#,0"),
			    "Revenue Calibration", FORMAT([meas.ai_scores_revenue_calibration_factor2_value], "$#,0")
			    
			)
			
			RETURN
			res
			```
		formatString: 0.00
		lineageTag: dbbfb553-82bb-444e-b9f9-7523d6960fe1

	/// Measure meas.ai_scores_factor3_name.
	measure 'meas.ai_scores_factor3_name' =
			
			var factor_name = MAX(metadata_ai_scores[factor_3_name])
			RETURN factor_name
		lineageTag: 2a2a1c88-f694-4c0e-9a4d-141ad9979f50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_factor3_value.
	measure 'meas.ai_scores_factor3_value' = ```
			
			var score_name = MAX(metadata_ai_scores[score_name])
			
			var res = SWITCH(
			    score_name,
			    "Rep Organization Calibration", FORMAT([meas.ai_scores_rep_org_calibration_factor3_value],"#,0")
			    
			)
			
			RETURN
			res
			```
		lineageTag: a87d35b5-2f1a-49fd-bfbb-73176fec4bcf

	/// Measure meas.ai_scores_text.
	measure 'meas.ai_scores_text' = ```
			
			
			var score = [meas.ai_score]
			
			var score_text = IF(
			    score > 94, "Excellent", 
			        If(score > 84,  "Great", 
			            If(score > 74 ,"Good", 
			                if(score> 49, "Fair", "Limited" 
			            )
			        )
			    )
			)  // use the legend
			
			
			RETURN  score_text
			
			```
		lineageTag: 7492dfc0-7677-44be-a2c6-b97c45c16627

	/// Measure meas.average_ai_score.
	measure 'meas.average_ai_score' =
			
			var avg_score =
			    AVERAGEX(
			        metadata_ai_scores,
			        [meas.ai_score]
			    )
			RETURN MIN(MAX(avg_score, 0), 100)
		formatString: 0
		lineageTag: a540bda0-c8a6-460b-9f46-e51c34c67745

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_scores_revenue_calibration_factor2_value.
	measure 'meas.ai_scores_revenue_calibration_factor2_value' = ```
			
			var latest_table = CALCULATETABLE(TOPN(1,companies_history,companies_history[_sys_processed_as_of],DESC))   
			var _booking_amt = MAXX(latest_table,companies_history[di_amt_won_last12months]) 
			RETURN
			_booking_amt
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: 2782ec74-5646-4f66-a3b1-f2a0983bfd8f

	/// Measure meas.ai_scores_booking_calibration_factor1_value.
	measure 'meas.ai_scores_booking_calibration_factor1_value' = ```
			
			var latest_table = CALCULATETABLE(TOPN(1,companies_history,companies_history[_sys_processed_as_of],DESC))  
			var _booking_amt = MAXX(latest_table,companies_history[ttm_ref_date_bookings]) 
			RETURN _booking_amt
			```
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: 698f1c2b-2a28-46b9-897c-859800ef5cc5

	/// Measure meas.ai_scores_rep_org_calibration_factor2_value.
	measure 'meas.ai_scores_rep_org_calibration_factor2_value' =
			
			VAR latest_table =
			    CALCULATETABLE(
			        TOPN(1, companies_history, companies_history[_sys_processed_as_of], DESC),
			        ALL(companies_history)       -- Remove external filters
			    )
			
			VAR _hr_file              = MAXX(latest_table, companies_history[users_hr_file])
			VAR _total_users          = MAXX(latest_table, companies_history[users_sales])
			VAR _non_match_won        = MAXX(latest_table, companies_history[users_non_match_hr_id_won_deals])
			VAR _non_match_pipe       = MAXX(latest_table, companies_history[users_non_match_hr_id_pipeline])
			
			VAR _bad_users = _non_match_won + _non_match_pipe
			
			RETURN
			IF(
			    _hr_file = 0 || ISBLANK(_hr_file),
			    BLANK(),   -- no HR file -> ignore this factor
			    VAR _safe_total = MAX(_total_users, 1)    -- avoid divide-by-zero
			    VAR score = 1 - DIVIDE(_bad_users, _safe_total * 2, 0)
			    RETURN MIN(MAX(score, 0), 1)  -- clamp 0–1
			)
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: 6c5c7bdc-4060-4389-8523-828fd2b65c3a

	/// Measure meas.ai_scores_rep_org_calibration_factor3_value.
	measure 'meas.ai_scores_rep_org_calibration_factor3_value' = ```
			
			var latest_table = CALCULATETABLE(TOPN(1,companies_history,companies_history[_sys_processed_as_of],DESC))  
			VAR total_users = MAXX(latest_table, companies_history[users_sales]) +0 
			var users_match_hr_id_nd_role = MAXX(latest_table, companies_history[users_match_hr_id_nd_role])  +0           // get the number of reps w ND role             
			var users_match_hr_id_nd_group = MAXX(latest_table, companies_history[users_non_match_hr_id_nd_group]) +0        
			var res = 1-DIVIDE(users_match_hr_id_nd_role + users_match_hr_id_nd_group, total_users * 2 )
			RETURN res
			```
		formatString: 0
		displayFolder: _factor3_value
		lineageTag: d1d45c90-f785-41cf-bb10-2ebace480a90

	/// Measure meas.ai_scores_booking_calibration_factor2_value.
	measure 'meas.ai_scores_booking_calibration_factor2_value' = ```
			
			var latest_table = CALCULATETABLE(TOPN(1,companies_history,companies_history[_sys_processed_as_of],DESC))  
			var _won_amt = MAXX(latest_table,companies_history[di_amt_won_last12months]) 
			
			RETURN _won_amt
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: fe0ca8bb-d25a-4122-958a-cd48c5152bbd

	/// Measure meas.ai_scores_rep_org_calibration_test.
	measure 'meas.ai_scores_rep_org_calibration_test' = ```
			
			var latest_table = CALCULATETABLE(TOPN(1,companies_history,companies_history[_sys_processed_as_of],DESC))       // grt the most latest row
			var _total_users = MAXX(latest_table,companies_history[users])          // total users
			
			var users_match_hr_id = MAXX(latest_table, [users_match_hr_id])         // total matched reps
			var users_hr_file = MAXX(latest_table, companies_history[users_hr_file])           // reps in hr file
			
			var users_non_match_hr_id_won_deals = MAXX(latest_table, companies_history[users_non_match_hr_id_won_deals])        // non match won deals reps
			var users_non_match_hr_id_pipeline = MAXX(latest_table, companies_history[users_non_match_hr_id_pipeline])          // non match pipeline gen reps
			var users_non_match_hr_id_leads = MAXX(latest_table, companies_history[users_non_match_hr_id_leads])          // non match lead gen reps count
			var users_match_hr_id_nd_role = MAXX(latest_table, companies_history[users_match_hr_id_nd_role])                  // non match reps with role
			var users_match_hr_id_nd_group = 0
			
			var matched_reps_score = DIVIDE(users_match_hr_id,users_hr_file,0)
			var won_deals_score = (1 - DIVIDE(users_non_match_hr_id_won_deals, _total_users, 0))
			var pipeline_gen_score = (1 - DIVIDE(users_non_match_hr_id_pipeline, _total_users, 0))
			var lead_gen_score = (1 - DIVIDE(users_non_match_hr_id_leads, _total_users, 0))               //raw score calculation for each
			var reps_w_role_score = (1 - DIVIDE(users_match_hr_id_nd_role,users_hr_file,0))
			//var reps_w_group_ratio = DIVIDE(reps_group,_hr_file_users,0)
			
			VAR Row1 = ROW ( "Value", matched_reps_score, "Weight", 3 )
			VAR Row2 = ROW ( "Value", won_deals_score, "Weight", 2 )
			VAR Row3 = ROW ( "Value", pipeline_gen_score, "Weight", 1 )          //raw score and weight  added in the table  for each reps count
			VAR Row4 = ROW ( "Value", lead_gen_score, "Weight", 1 )
			VAR Row5 = ROW ( "Value", reps_w_role_score, "Weight", 2 )
			VAR temp_tbl =
			    UNION ( Row1, Row2, Row3, Row4, Row5 )          //creating the table
			
			var _adj_calib = SUMX(temp_tbl, [Value]*[Weight])           // get the adjusted raw score
			var _importance = SUMX(temp_tbl, [Weight])                  // sum of the total weight
			var raw_score = DIVIDE(_adj_calib, _importance,0)                 // get the score
			
			var boost_expo = 0.9            // we use this to get the closer one value
			var score = raw_score^boost_expo     // boosting the actual 
			var res = MIN(MAX(ROUND(score*100,0),0),100)
			RETURN
			matched_reps_score
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6e7ee0ed-34bf-446a-9ffe-e98ccb212335

	/// Measure meas.ai_scores_sales_process.
	measure 'meas.ai_scores_sales_process' = ```
			
			var _count = CALCULATE(count(ssr_history[_sys_doc_id]) )
			var total_rules_applied=  If(IsBlank(_count), 0,_count)
			
			var tbl_crm_rules = calculateTable(SELECTCOLUMNS(filter(metadata_rule_list, metadata_rule_list[col.rule_is_std_crm] = true), "_sys_doc_id]", "" & [_sys_doc_id])) // get a list of just the CRM rules
			//var dd = COUNTROWS(tbl_crm_rules) // check the count
			var filt = filter(ssr_history, 
			 (
			     ssr_history[step_owner_rule] & "" IN tbl_crm_rules  &&  
			     ssr_history[step_outcome_rule] & "" IN tbl_crm_rules &&   
			      ssr_history[step_end_rule] & "" IN tbl_crm_rules  
			) 
			) // look for NONE crm rules and exclude lead gen 
			var sdt_rules_applied =  CALCULATE(count(ssr_history[_sys_doc_id]) , filt) // get the count based on correct filter
			
			
			var avg_conf_non_crm = .85  // get the avg non crm conf
			var diff = (total_rules_applied - sdt_rules_applied  ) * avg_conf_non_crm  // create a diff model
			var adjusted_ratio= divide (sdt_rules_applied +diff ,  total_rules_applied) // add the diff for the new ratio
			// return as an int between 0-100
			
			return adjusted_ratio
			```
		displayFolder: _ai_scores
		lineageTag: bf45a0b8-077c-4b33-8150-8a029a875a9f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_ci_act_capt_lvl.
	measure 'meas.ai_scores_ci_act_capt_lvl' = ```
			
			var res = [meas.ai_scores_ci_act_capt_lvl_factor1_value]
			RETURN res
			
			```
		displayFolder: _ai_scores
		lineageTag: 57ff7f58-82c2-482d-b0b1-7a497dc64707

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.ai_scores_sales_process_any_rules_count_factor1_value.
	measure 'meas.ai_scores_sales_process_any_rules_count_factor1_value' =
			
			
			var total_rules_applied = CALCULATE(count(ssr_history[_sys_doc_id]) )
			var res=  If(IsBlank(total_rules_applied), 0,total_rules_applied)
			
			RETURN
			res
		formatString: 0
		displayFolder: _factor1_value
		lineageTag: 7483e4d7-59d2-431f-bd68-8c9daf3d0758

	/// Measure meas.ai_scores_sales_process_any_rules_std_count_factor2_value.
	measure 'meas.ai_scores_sales_process_any_rules_std_count_factor2_value' = ```
			
			
			var tbl_crm_rules = calculateTable(SELECTCOLUMNS(filter(metadata_rule_list, metadata_rule_list[col.rule_is_std_crm] = true), "_sys_doc_id]", "" & [_sys_doc_id])) // get a list of just the CRM rules
			//var dd = COUNTROWS(tbl_crm_rules) // check the count
			var filt = filter(ssr_history, 
			 (
			     ssr_history[step_owner_rule] & "" IN tbl_crm_rules  &&  
			     ssr_history[step_outcome_rule] & "" IN tbl_crm_rules &&   
			      ssr_history[step_end_rule] & "" IN tbl_crm_rules  
			) 
			) // look for NONE crm rules and exclude lead gen 
			var sdt_rules_applied =  CALCULATE(count(ssr_history[_sys_doc_id]) , filt) // get the count based on correct filter
			var res = sdt_rules_applied // return the res
			
			
			return If(IsBlank(res), 0,res)
			```
		formatString: 0
		displayFolder: _factor2_value
		lineageTag: 6463e2f9-58fc-4643-a70b-240574b500e0

	/// Measure meas.ai_scores_ci_act_capt_lvl_factor1_value.
	measure 'meas.ai_scores_ci_act_capt_lvl_factor1_value' =
			
			var _avg = CALCULATE(
			    AVERAGE(users_history[ci_act_capt_lvl]), users[trueai_user_role_function] in {"AM", "AE", "SDR"} )        // get the users_history average ci_act_capt_lvl
			
			RETURN
			_avg
		formatString: 0.00
		displayFolder: _factor1_value
		lineageTag: a74ee032-d271-4caa-8059-cb32dde336dc

	/// Measure meas.ai_scores_opps_history_factor2_value.
	measure 'meas.ai_scores_opps_history_factor2_value' = ```
			
			
			var tbl_won_open_pipeline =FILTER(
			        open_pipeline, 
			        open_pipeline[opp_is_won] = TRUE()
			    ) // get the won deal history
			    
			var tbl_summarized = SUMMARIZE(tbl_won_open_pipeline, [crm_opp_id], "unique_trueai_stage_ids", DISTINCTCOUNT(open_pipeline[trueai_stage_id])) // get distinct count
			var count_sum_tbl = COUNTROWS(tbl_summarized) 
			var the_20_pct_ordinal = ROUND(count_sum_tbl * 0.8,0) // get the top 20th% item
			var top_tbl_summarized = TOPN(the_20_pct_ordinal, tbl_summarized, [unique_trueai_stage_ids], ASC)
			var top_stage_count = MAXX(top_tbl_summarized, [unique_trueai_stage_ids]) // get teh avg stages
			var res = MAX(top_stage_count, 3) // at least 3 since we may have nothing
			RETURN res
			
			
			
			```
		formatString: 0.00
		displayFolder: _factor2_value
		lineageTag: fbd3245f-7c2f-401f-b3b5-6a3f19fa62ff

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Measure meas.ai_score_text_value.
	measure 'meas.ai_score_text_value' =
			
			VAR _score = [meas.average_ai_score]
			VAR _label =
			    SWITCH(
			        TRUE(),
			        _score >= 95, "Excellent",
			        _score >= 85, "Great",
			        _score >= 75, "Good",
			        _score >= 50, "Fair",
			        _score >= 0,  "Limited",
			        BLANK()
			    )
			RETURN
			    IF(ISBLANK(_label), " - ", _label)
		lineageTag: 8989505c-ff92-4181-ba3d-07b1e14dd582

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Unique AI score identifier
	column _sys_doc_id
		dataType: string
		lineageTag: 0553404d-2d1b-483d-8165-0cda87efe66e
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Is Active
	column _sys_is_active
		dataType: string
		lineageTag: 3237ca1e-6587-4d4d-b895-9838a49499c0
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// Modified On Date
	column _sys_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: e4929e32-cf6f-4149-93db-f3d771d03c10
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: 48b7e184-c69d-4bd1-b42e-0b05677f044d
			defaultHierarchy: LocalDateTable_69fd8ce2-ea49-4d03-91e4-9a7d63e1ec7e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Category
	column category
		dataType: string
		lineageTag: fb019989-fe9b-424c-8fd3-a7e7f2aae590
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	/// Score Name
	column score_name
		dataType: string
		lineageTag: a8567782-46a4-4de2-bc50-2652ade448ac
		summarizeBy: none
		sourceColumn: score_name

		annotation SummarizationSetBy = Automatic

	/// Description
	column description
		dataType: string
		lineageTag: b6dd3403-84ad-4b86-a3e7-cced39219da9
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	/// Sort
	column sort
		dataType: int64
		formatString: 0
		lineageTag: a3bb9fb1-37ee-4f8e-bf36-e15a8efb9f3f
		summarizeBy: sum
		sourceColumn: sort

		annotation SummarizationSetBy = Automatic

	/// Factor 1 Name
	column factor_1_name
		dataType: string
		lineageTag: 9bfc524c-cd48-47a6-94b6-101d507330c9
		summarizeBy: none
		sourceColumn: factor_1_name

		annotation SummarizationSetBy = Automatic

	/// Factor 2 Name
	column factor_2_name
		dataType: string
		lineageTag: dfae5997-5f65-44ee-93e9-bc73ea5040c0
		summarizeBy: none
		sourceColumn: factor_2_name

		annotation SummarizationSetBy = Automatic

	/// Factor 3 Name
	column factor_3_name
		dataType: string
		lineageTag: a32a4896-9e4b-45df-8798-6f6e728817be
		summarizeBy: none
		sourceColumn: factor_3_name

		annotation SummarizationSetBy = Automatic

	/// Notes
	column notes
		dataType: string
		lineageTag: 24d91298-91c6-46ec-96da-f286ca9607d6
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	/// Boost Expo
	column boost_expo
		dataType: double
		lineageTag: 7754aa79-c7fb-4e29-b06f-8bfdc3b32657
		summarizeBy: sum
		sourceColumn: boost_expo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Weight
	column weight
		dataType: double
		lineageTag: 788f39e0-5905-4e80-9abe-f87980071ba5
		summarizeBy: sum
		sourceColumn: weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition metadata_ai_scores = m
		mode: import
		source = ```
				let
				    dbTable = getDBTable("metadata_ai_scores"),      // get the right table
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"_sys_doc_id", type text},
				        {"_sys_is_active", type text},
				        {"_sys_modified_on", type datetime},
				        {"boost_expo", type number},
				        {"category", type text},
				        {"description", type text},
				        {"factor_1_name", type text},
				        {"factor_2_name", type text},
				        {"factor_3_name", type text},
				        {"notes", type text},
				        {"score_name", type text},
				        {"sort", Int64.Type},
				        {"weight", type number}       
				        })
				   
				in
				   dbTableTyped
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

