/// Reference list of static normalized values used across various entities.
table metadata_reference_values
	lineageTag: 69ddee42-4a9a-47f9-9700-a7bf171b9dd2

	/// Unique reference value identifier
	column _sys_doc_id
		dataType: string
		lineageTag: 3bd45705-6703-4deb-8bb6-6e22abce6fe6
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Added On Date
	column _sys_added_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 844b4b68-e9c0-42ab-b2ef-3b80f42cd2af
		summarizeBy: none
		sourceColumn: _sys_added_on

		variation Variation
			isDefault
			relationship: ae19e386-54e5-4584-9ca5-aaea28e1cb1b
			defaultHierarchy: LocalDateTable_06f69b28-80f3-4f09-95f9-6ec385e667c3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Added By ID
	column _sys_added_by
		dataType: string
		lineageTag: 8aefbac0-b57f-402d-a528-2c0f544c64e3
		summarizeBy: none
		sourceColumn: _sys_added_by

		annotation SummarizationSetBy = Automatic

	/// Modified On Date
	column _sys_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 8f1ba464-4fef-405a-956f-3aa65f2255ad
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: a9de31e6-5c77-4526-879c-6a508dad0157
			defaultHierarchy: LocalDateTable_38e8101a-141b-46c1-9471-98caf2d04337.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Value Category
	column value_category
		dataType: string
		lineageTag: 436a4d63-a731-4e26-b26e-1972c4b4de69
		summarizeBy: none
		sourceColumn: value_category

		annotation SummarizationSetBy = Automatic

	/// Related To Record
	column related_to_record
		dataType: string
		lineageTag: 97a97d79-605d-4a4a-a435-d0cf24c4bbde
		summarizeBy: none
		sourceColumn: related_to_record

		annotation SummarizationSetBy = Automatic

	/// Value Name
	column value_name
		dataType: string
		lineageTag: 8f3595ce-21ed-4a28-a3be-d32de9ef8692
		summarizeBy: none
		sourceColumn: value_name

		annotation SummarizationSetBy = Automatic

	/// Value
	column value
		dataType: double
		lineageTag: 72f0dffe-a7ff-41e2-9cc4-90a27a62fafb
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Supporting Value 1 Name
	column supporting_value_1_name
		dataType: string
		lineageTag: 83f0c01d-ef27-4abb-971a-a3e438aa249c
		summarizeBy: none
		sourceColumn: supporting_value_1_name

		annotation SummarizationSetBy = Automatic

	/// Supporting Value 1
	column supporting_value_1
		dataType: double
		lineageTag: df22a15c-f81f-40cc-94a3-42003794698d
		summarizeBy: sum
		sourceColumn: supporting_value_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Supporting Value 2 Name
	column supporting_value_2_name
		dataType: string
		lineageTag: e32f0cf5-d393-4a5f-99de-83598e68d1fe
		summarizeBy: none
		sourceColumn: supporting_value_2_name

		annotation SummarizationSetBy = Automatic

	/// Supporting Value 2
	column supporting_value_2
		dataType: double
		lineageTag: 6be4bc92-87d8-487e-8d5b-196e4ca2bec0
		summarizeBy: sum
		sourceColumn: supporting_value_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Supporting Value 3 Name
	column supporting_value_3_name
		dataType: string
		lineageTag: 2df106ae-c74b-4fe6-9c47-998c9077229e
		summarizeBy: none
		sourceColumn: supporting_value_3_name

		annotation SummarizationSetBy = Automatic

	/// Supporting Value 3
	column supporting_value_3
		dataType: double
		lineageTag: b95c555f-7f43-438a-9003-12a58cf47617
		summarizeBy: sum
		sourceColumn: supporting_value_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Applies To Industry
	column applies_to_industry
		dataType: string
		lineageTag: dea20cd4-beef-4471-bc6f-0c3073f52b72
		summarizeBy: none
		sourceColumn: applies_to_industry

		annotation SummarizationSetBy = Automatic

	/// Applies To Company Size
	column applies_to_co_size
		dataType: string
		lineageTag: b5b57bee-47d0-4872-9842-b47ae9209a03
		summarizeBy: none
		sourceColumn: applies_to_co_size

		annotation SummarizationSetBy = Automatic

	/// Applies To Geo
	column applies_to_geo
		dataType: string
		lineageTag: 92578207-8364-4083-91cb-f74239227066
		summarizeBy: none
		sourceColumn: applies_to_geo

		annotation SummarizationSetBy = Automatic

	/// Comments
	column comments
		dataType: string
		lineageTag: 65963845-9904-463c-818f-bdac57d775da
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	/// Is Active
	column _sys_is_active
		dataType: string
		lineageTag: 3648cd6e-e5a5-4233-815e-bba7ef323a2d
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	partition metadata_reference_values = m
		mode: import
		source = ```
				let
				  
				  dbTable = getDBTable("metadata_reference_values"),          // get the right table
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				    {"_sys_added_by", type text},
				    {"_sys_added_on", type datetime},
				    {"_sys_doc_id", type text},
				    {"_sys_is_active", type text},
				    {"_sys_modified_on", type datetime},
				    {"applies_to_co_size", type text},
				    {"applies_to_geo", type text},
				    {"applies_to_industry", type text},
				    {"comments", type text},
				    {"related_to_record", type text},
				    {"supporting_value_1", type number},
				    {"supporting_value_1_name", type text},
				    {"supporting_value_2", type number},
				    {"supporting_value_2_name", type text},
				    {"supporting_value_3", type number},
				    {"supporting_value_3_name", type text},
				    {"value", type number},
				    {"value_category", type text},
				    {"value_name", type text}
				    })     
				
				in
				    dbTableTyped
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

