table metadata_heatmap_items
	description: "One row per metadata_heatmap_item record. Source fields include System prefixes. Related to LocalDateTable_297e7bff-d1e4-4d4f-b1d9-3c09c0eda60a (_sys_modified_on -> Date). Supports measures such as meas.ai_score_kpi1, meas.ai_score_kpi2."
	lineageTag: 00dab9dc-0c89-4db4-8a5a-7354e75406d2

	measure 'meas.ai_score_kpi1' =
			
			description: "TODO: provide business definition for this measure."
			VAR _name   = MAX(metadata_heatmap_items[heatmap_kpi1_ai_score_name])
			VAR _score  = [meas.kpi1_ai_score_trust_value]
			VAR _bucket = [meas.KPI1_AI_score_bucket]
			
			VAR res =
			    IF(
			        ISBLANK(_name),
			        "--",
			        FORMAT(_score, "0") & " - " & _bucket
			    )
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 3b88c8ca-43e4-40ba-8362-3348a24d070e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.ai_score_kpi2' =
			
			description: "TODO: provide business definition for this measure."
			VAR _name   = MAX(metadata_heatmap_items[heatmap_kpi2_ai_score_name])
			VAR _score  = [meas.kpi2_ai_score_trust_value]
			VAR _bucket = [meas.KPI2_AI_score_bucket]
			
			VAR res =
			    IF(
			        ISBLANK(_name),
			        "--",
			        FORMAT(_score, "0") & " - " & _bucket
			    )
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: afcfa086-1bb4-48c3-b064-9bd05417b189

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp1_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			VAR _total_acct_count = CALCULATE(
			    [meas.ssr_history_step_count],          // get the total accts count for Prospecting step only
			    ssr_history[step_name]="Prospecting"
			)
			
			RETURN
			_total_acct_count
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 0a99df9f-cd82-4b43-acad-10af0b179a0e

	measure 'meas.calc_hyp1_kpi1_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			VAR _tot_bkt_count = CALCULATE(
			    [meas.ssr_history_step_count],
			    quality_buckets[bucket]  in {"Highest", "High", "Mid"},     // get the step count for prospecting step and highest, high and mid bucket
			    ssr_history[step_name] = "Prospecting"
			)
			
			
			RETURN
			_tot_bkt_count
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 4fdce0e4-d890-4fab-8ef1-bd76e1c78945

	measure 'meas.calc_hyp1_kpi2_denominator' = ```
			
			
			VAR _low_time_count = CALCULATE(
			    [meas.ssr_history_duration_hrs_per_acct_prospecting],
			    quality_buckets[bucket] in {"Lowest", "Low"}     // get the time spent for Lowest  and Low bucket 
			    )
			
			
			RETURN
			_low_time_count
			```
			description: "Ratio based on quality_buckets[bucket]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: e2019b74-ff23-4e80-8854-042de62a3987

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp1_kpi2_nominator' = ```
			
			
			VAR _high_time_count = CALCULATE(
			    [meas.ssr_history_duration_hrs_per_acct_prospecting],
			    quality_buckets[bucket] in {"Highest", "High"}     // get the time spent for highest  and high bucket for prospecting step
			    
			    
			    )
			
			RETURN
			_high_time_count
			```
			description: "Ratio based on quality_buckets[bucket]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 46cd1fb9-f419-497f-a5a8-a663dc49af66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp10_kpi1_denominator' = ```
			
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			var previous_year = current_year-1                                      // get the previous year
			
			var _predicted_rate = CALCULATE(
			    [meas.ssr_history_success_prob_avg],
			    YEAR(cal_end_dates[Date])=previous_year,                 // get the current year average predicted win rate
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Renewal"
			)
			
			var _initial_booking_amt = CALCULATE(
			    [meas.ssr_history_booking_amt],
			    YEAR(cal_end_dates[Date])=previous_year,                 // get the current year initial booking amt
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Renewal"
			)
			
			
			var res = _predicted_rate* _initial_booking_amt                 // get the multiplication 
			
			
			RETURN
			res
			```
			description: "Ratio of cal_end_dates[Date] to ssr_history[step_name]. Respects the current filter context."
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: 704a4419-4798-4281-a7bb-d64381ce2921

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp10_kpi1_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			
			
			var _predicted_rate = CALCULATE(
			    [meas.ssr_history_success_prob_avg],
			    YEAR(cal_end_dates[Date])=current_year,                 // get the previous year average predicted win rate
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Renewal"
			)
			
			var _initial_booking_amt = CALCULATE(
			    [meas.ssr_history_booking_amt],
			    YEAR(cal_end_dates[Date])=current_year,                 // get the previous year initial booking amt
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Renewal"
			)
			
			
			var res = _predicted_rate*_initial_booking_amt              // get the multiply
			
			
			RETURN
			res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: be522573-f280-4c9a-a108-40867d653e39

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp10_kpi2_denominator' =
			
			description: "TODO: provide business definition for this measure."
			1
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: a3f0e472-91bf-4369-80f8-b524bc29e4f7

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp10_kpi2_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var res =  CALCULATE(
			    AVERAGE(
			        ssr_history[step_success_prob]          // get the avg step success prob for new logo sale
			    ),
			    ssr_history[opp_sale_type]="Renewal"
			)
			
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 8edcf5a7-186d-41c5-b707-eaa4b0f3458c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp11_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			CALCULATE(
			    [meas.ssr_history_won_amt]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: e630514f-bd4b-47f7-b3f9-0618e2449769

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp11_kpi1_nominator' =
			
			description: "TODO: provide business definition for this measure."
			CALCULATE(
			    [meas.ssr_history_won_amt_new_logo]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: 4af1eb44-6528-40d5-b1b6-0a1e8f13bb48

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp11_kpi2_denominator' = ```
			
			var dur = calculate(
			    sum(ssr_history[stkhlds_all_adj_dur]), 
			    ssr_history[step_name] in { "Post-Sales Support" , "Existing Customer Selling"},
			    ssr_history[step_outcome]="Closed Won"
			    ) / 3600 // turn to hours
			RETURN
			dur
			```
			description: "Ratio of ssr_history[stkhlds_all_adj_dur] to ssr_history[step_name]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 1d168300-0541-4367-8840-d6390141052a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp11_kpi2_nominator' = ```
			
			var dur = calculate(
			    sum(ssr_history[stkhlds_all_adj_dur]), 
			    ssr_history[step_name] in { "New Logo Selling" , "Prospecting"},
			    ssr_history[step_outcome]="Closed Won"
			    ) / 3600 // turn to hours
			RETURN
			dur
			```
			description: "Ratio of ssr_history[stkhlds_all_adj_dur] to ssr_history[step_name]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: c14d161b-2500-444c-a344-1061043c8c97

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp12_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			CALCULATE(
			    DISTINCTCOUNT(ssr_history[_sys_doc_id]),
			    ssr_history[step_name]="Post-Sales Support"
			)
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: c1db5e3d-50fc-4bdb-9d79-83a71f26aec9

	measure 'meas.calc_hyp12_kpi1_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var _max_date = [meas.context_date_max]
			var rept_tbl = CALCULATETABLE(
			    ssr,
			    KEEPFILTERS(ssr[trueai_churned_on]=BLANK() || ssr[trueai_churned_on] >= DATE(YEAR(_max_date)+1,01,01)),
			    KEEPFILTERS(ssr[trueai_churned_on]=BLANK()),
			    ssr_history[step_name]="Existing Customer Selling",     // keep the date filter and ignore the context filter and get the attempted cross sale count
			    ssr_history[opp_existing_customer_selling_cross_sale]=TRUE(),
			    ALL(cal_end_dates)
			)
			var res = CALCULATE(
			    COUNTROWS(rept_tbl)
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 0a79c4ce-7c0d-4ca1-b49a-fafc90e62ef5

	measure 'meas.calc_hyp12_kpi2_denominator' =
			
			description: "TODO: provide business definition for this measure."
			var _min_date =  MAX(date(2000,01,01) ,  min(ssr[_sys_filt_start_date]))            // get the coid min date
			var _max_date = [meas.context_date_max]             //. get the context max date
			
			var rept_tbl = CALCULATETABLE(
			    ssr,
			    KEEPFILTERS(ssr[trueai_first_purchase] >= _min_date  && ssr[trueai_first_purchase] < DATE(YEAR(_max_date)+1,1,1)),
			    KEEPFILTERS(ssr[trueai_churned_on]=BLANK() || ssr[trueai_churned_on] >= DATE(YEAR(_max_date)+1,01,01)),     // count of attempted cross sale filtered by the not inculding the churn and first purchase as per discussed logic
			    ALL(cal_end_dates)
			)
			var res = CALCULATE(
			    COUNTROWS(rept_tbl)
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 2c03f897-4cef-4821-bf3e-51b93a1f2b33

	measure 'meas.calc_hyp12_kpi2_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var _max_date = [meas.context_date_max]
			var rept_tbl = CALCULATETABLE(
			    ssr,
			    KEEPFILTERS(ssr[trueai_churned_on]=BLANK() || ssr[trueai_churned_on] >= DATE(YEAR(_max_date)+1,01,01)),
			    KEEPFILTERS(ssr[trueai_churned_on]=BLANK()),
			    ssr_history[step_name]="Existing Customer Selling",     // keep the date filter and ignore the context filter and get the attempted cross sale count
			    ssr_history[opp_existing_customer_selling_cross_sale]=TRUE(),
			    ALL(cal_end_dates)
			)
			var res = CALCULATE(
			    COUNTROWS(rept_tbl)
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 4c7ac747-8024-4d3c-a408-41770d0a8626

	measure 'meas.calc_hyp13_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			var _churn_accts = CALCULATE(
			    [meas.ssr_history_rev_churned_count]
			)
			
			RETURN
			ABS(_churn_accts)
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: fabcffde-cdf1-41d1-b159-b2e977e25bf2

	measure 'meas.calc_hyp13_kpi1_nominator' =
			
			description: "TODO: provide business definition for this measure."
			CALCULATE(
			    [meas.ssr_history_rev_new_count],
			    ssr_history[step_name]="New Logo Selling"
			)
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 1cf71006-c5d3-42e3-8535-827dbf3b2fc2

	measure 'meas.calc_hyp13_kpi2_denominator' =
			
			description: "TODO: provide business definition for this measure."
			var churned_amt = CALCULATE(
			    [meas.ssr_history_rev_churned_amt]          // get the churned account revenue
			)
			var res = churned_amt * -1          // multiply with -1 to get the positive amount
			RETURN
			res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: 05394b18-b29e-4db6-9384-0de0e97bd8fa

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp13_kpi2_nominator' = ```
			
			CALCULATE(
			    [meas.ssr_history_rev_new_amt]          // get the new accounts revenue amount 
			)
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: da8e236e-6a24-48da-8ee6-1a611b459718

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp14_kpi1_denominator' = ```
			
			var rep_time_tbl = CALCULATETABLE(
			    users_history, 
			    users_history[trueai_user_role_function] in {"AE","AM","SDR"} && users_history[ci_time_alloc_tot] >0        // get the temporary table for AE, AM and SDR role with reps having Time Allocation
			)
			var reps_w_timalloc = COUNTROWS (rep_time_tbl )
			
			var denom_role_total_time =  SUMX(
			    rep_time_tbl,           // sum up the total time allocation count 
			    [ci_time_alloc_tot]
			) 
			
			var res = DIVIDE(denom_role_total_time,reps_w_timalloc)         ///  time allocation per reps having time allocation
			RETURN
			res
			```
			description: "Ratio of users_history[trueai_user_role_function] to users_history[ci_time_alloc_tot]. Respects the current filter context."
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: d5c76d82-bb7f-435b-b389-744e450f8832

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp14_kpi1_nominator' = ```
			
			
			var rep_time_tbl = CALCULATETABLE(
			    users_history, 
			    users_history[trueai_user_role_function] in {"AE","AM","SDR"} && users_history[ci_time_alloc_tot] >0        // get the temporary table for AE, AM and SDR role with reps having Time Allocation
			)
			var reps_w_timalloc = COUNTROWS (rep_time_tbl )         // get the reps count having TA 
			
			var nom_role_purposeful_time = SUMX(
			    rep_time_tbl , 
			    SWITCH( [trueai_user_role_function], 
			    "AE",  [ci_time_alloc_prospecting] + [ci_time_alloc_new_logo],      // sum the time for the specified role function 
			    "AM" ,  [ci_time_alloc_post_sales] +  [ci_time_alloc_existing_customer_selling],
			    "SDR", [ci_time_alloc_prospecting]
			    )
			) 
			
			var res = DIVIDE(nom_role_purposeful_time,reps_w_timalloc)         /// purposed time allocation per reps having time allocation
			RETURN
			res
			```
			description: "Ratio of users_history[trueai_user_role_function] to users_history[ci_time_alloc_tot]. Respects the current filter context."
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: 5595efb9-166a-4222-aa34-65bf6b9ca265

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp14_kpi2_denominator' =
			
			description: "TODO: provide business definition for this measure."
			var post_sales = CALCULATE(
			    SUM(
			        users_history[ci_time_alloc_post_sales]             // get the post-sales support time alloc for AE Role
			    ),
			    users_history[trueai_user_role_function]="AE"
			)
			
			var existing_ = CALCULATE(
			    SUM(
			        users_history[ci_time_alloc_existing_customer_selling]
			    ),
			    users_history[trueai_user_role_function]="AE"               // get the existing customer selling  time alloc for AE Role
			)
			
			var res = post_sales + existing_
			
			RETURN
			res
		formatString: 0.0
		displayFolder: heatmap_kpis
		lineageTag: c9dbb365-bde6-4eb0-bae6-8eeb74613c7c

	measure 'meas.calc_hyp14_kpi2_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var prospec = CALCULATE(
			    SUM(
			        users_history[ci_time_alloc_prospecting]
			    ),
			    users_history[trueai_user_role_function]="AE"           // bget the prospecting time for AE role
			)
			
			var new_logo = CALCULATE(
			    SUM(
			        users_history[ci_time_alloc_new_logo]
			    ),
			    users_history[trueai_user_role_function]="AE"           // get the new logo time for AE role
			)
			
			var res = prospec + new_logo
			
			RETURN
			res
		formatString: 0.0
		displayFolder: heatmap_kpis
		lineageTag: 643a00ea-deba-4986-b186-f8f7048c731e

	measure 'meas.calc_hyp15_kpi1_denominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    [meas.data_logs_ci_perf_tier_count],
			    users_history[trueai_user_role_function] in {"AE", "AM"} && users_history[col.ci.perf_annual_performance_tier] in {"Overperformer", "Performer", "Underperformer"}
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: cc7b9bf9-6447-46cb-bf74-dfa311febaa2

	measure 'meas.calc_hyp15_kpi1_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    [meas.data_logs_ci_perf_tier_count],
			    users_history[trueai_user_role_function] in {"AE", "AM"} && users_history[col.ci.perf_annual_performance_tier]="Underperformer"
			)
			
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 7b65ae01-96ae-4c47-acb2-ae4b1041bc89

	measure 'meas.calc_hyp15_kpi2_denominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    [meas.data_logs_ci_perf_tier_count],
			    users_history[trueai_user_role]="Account Manager" && users_history[col.ci.perf_annual_performance_tier] in {"Overperformer", "Performer", "Underperformer"}
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: cb0c4148-2551-4666-9cd0-e49494ecf651

	measure 'meas.calc_hyp15_kpi2_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    [meas.data_logs_ci_perf_tier_count],
			    users_history[trueai_user_role]="Account Manager" && users_history[col.ci.perf_annual_performance_tier]="Underperformer"
			)
			
			
			RETURN
			res+0
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 573183b8-be1d-4adc-aa60-6ecd3b69eee6

	measure 'meas.calc_hyp16_kpi1_denominator' = ```
			
			
			var fromDate = [meas.context_date_min]           /// current context min date
			var toDate = [meas.context_date_max]             // current context max date
			var analysisAsOfDate = MAX(companies_history[_sys_as_of])  // get the most recent asof date
			
			var res = CALCULATE(
			    DISTINCTCOUNT(users_history[_sys_user_id]), 
			    users_history[trueai_hire_date] >= fromDate &&  users_history[trueai_hire_date]  <= toDate
			    && users_history[trueai_hire_date] + 365 <= analysisAsOfDate   // rep has had at least 365 days to ramp 
			    && users_history[trueai_user_role_function] in {"AE", "AM"}         // include AE and AM only
			)       
			RETURN
			IF(
			    ISBLANK(res), 0, res
			)
			```
			description: "Ratio of companies_history[_sys_as_of] to users_history[_sys_user_id]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: ede571ac-5980-40db-a817-75dfeda344db

	measure 'meas.calc_hyp16_kpi1_nominator' = ```
			
			var fromDate = [meas.context_date_min]           /// current context min date
			var toDate = [meas.context_date_max]             // current context max date
			var analysisAsOfDate = MAX(companies_history[_sys_as_of])  // get the most recent asof date
			
			var perf_reps = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_hire_date] >= fromDate 
			           && users_history[trueai_hire_date] <= toDate                    // rep hired in the analysis period
			           && users_history[trueai_hire_date] + 365 <= analysisAsOfDate   // rep has had at least 365 days to ramp (enough time has passed)
			           && users_history[col.perf_date_first_reached] < users_history[trueai_hire_date] + 365  // rep reached perf within a year of hire
			           && if(isblank(users_history[trueai_termination_date]), date(2100,1,1), users_history[trueai_termination_date]) > users_history[trueai_hire_date] + 365     // did not get terminated within a year
			           && users_history[trueai_user_role_function] in {"AE", "AM"}     // only for AE and AM
			           )
			
			var res = if(ISBLANK(perf_reps), 0, perf_reps)
			
			RETURN
			res
			```
			description: "Ratio of companies_history[_sys_as_of] to users_history[_sys_user_id]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 37ceb688-71dc-4f26-8a47-4a7e2dc21b03

	measure 'meas.calc_hyp16_kpi2_denominator' =
			
			description: "TODO: provide business definition for this measure."
			// var res =  CALCULATE(
			//     [meas.data_logs_user_count_bop],        // get the total AE & AM EOP
			//     users[trueai_user_role_function] in {"AE", "AM"},
			//     users_history[col.ci.perf_qtly_performance_tier] <>"Underperformer"
			// )
			
			// RETURN
			// res
			CALCULATE(
			    [meas.calc_hyp16_kpi2_nominator],
			    SAMEPERIODLASTYEAR(cal_end_dates[Date])
			)
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 2f3b14fa-0b24-427d-8491-770d5db0b0c1

	measure 'meas.calc_hyp16_kpi2_nominator' = ```
			
			// var res =  CALCULATE(
			//     [meas.data_logs_user_count_eop],        // get the total AE & AM EOP
			//     users[trueai_user_role_function] in {"AE", "AM"},
			//     users_history[col.ci.perf_qtly_performance_tier] <>"Underperformer"
			
			// )
			
			// RETURN
			// res
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(
			    users_history, 
			    LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]),  // get only the last entry in each filter context period (e.g. a year)
			    users_history[trueai_user_role_function] in {"AE", "AM"}
			)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <=  toDate   && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			
			var res = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, [_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			return res // return the res :)
			```
			description: "Ratio of users[trueai_user_role_function] to users_history[_sys_filt_start_date]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 052238c5-75fb-4e30-bb3d-e50bfaab934c

	measure 'meas.calc_hyp17_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			var res =  CALCULATE(
			    [meas.ssr_history_rev_avg_won_amt],        // get the won amount for new logo selling step
			    ssr_history[step_name]="New Logo Selling",
			    SAMEPERIODLASTYEAR(cal_end_dates[Date])
			
			)
			
			RETURN
			res
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: heatmap_kpis
		lineageTag: c7fcb0f0-1f0c-4d35-84c3-54659cb5d6ff

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp17_kpi1_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var res =  CALCULATE(
			    [meas.ssr_history_rev_avg_won_amt],        // get the won amount for new logo selling step
			    ssr_history[step_name]="New Logo Selling"
			
			)
			
			RETURN
			res
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: heatmap_kpis
		lineageTag: bf195886-7dd7-4da5-8d6c-8b0bd08db71b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp18_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			var res =  CALCULATE(
			    [meas.ssr_history_rev_avg_won_amt],        // get the won amount for new logo selling step
			    ssr_history[step_name]="Existing Customer Selling",
			    SAMEPERIODLASTYEAR(cal_end_dates[Date])
			
			)
			
			RETURN
			res
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: heatmap_kpis
		lineageTag: d2593140-3d00-42d5-949e-99dc9ace3367

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp18_kpi1_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var res =  CALCULATE(
			    [meas.ssr_history_rev_avg_won_amt],        // get the won amount for new logo selling step
			    ssr_history[step_name]="Existing Customer Selling"
			
			)
			
			RETURN
			res
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: heatmap_kpis
		lineageTag: 42188e79-66a8-4384-ab31-da6313bc9f68

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp2_kpi1_denominator' = ```
			1             // hard coded 1 as the def 
			
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 4155af46-f425-4f5e-a4bf-7bdec764c1ce

	measure 'meas.calc_hyp2_kpi1_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    AVERAGE(
			        'ssr'[trueai_crm_complt_all]            // get the average of the crm completeness score
			    )
			)
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: d7d09f80-d4a2-4083-9ead-ad641f1e9f10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp2_kpi2_denominator' = 1             // get the hardcoded 1 value
		description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 02753d25-0261-4e07-aa42-b8bc3895f3a6

	measure 'meas.calc_hyp2_kpi2_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var contact_ai = CALCULATE(
			    AVERAGE(
			        completeness_summary[trueai_completeness_contact]
			    ),      // get the contact info average score for entity Leads
			    completeness_summary[entity]="Leads"
			)
			
			var contact_method = CALCULATE(
			    AVERAGE(
			        completeness_summary[trueai_completeness_contact_method]
			    ),              // get the contact method average score for entity Leads
			    completeness_summary[entity]="Leads"
			)
			
			var res  = (contact_ai + contact_method)/2
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 31333bb7-6174-41a1-a236-4d0874c8357a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp3_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			// var res = CALCULATE(
			//     [meas.ssr_history_success_count],
			//      ssr_history[step_name] in {"New Logo Selling"}
			// )
			
			var res  = [meas.ssr_history_rev_ending_count]
			
			RETURN
			res
		formatString: #,0
		displayFolder: heatmap_kpis
		lineageTag: cf0c83b2-844f-4447-b1e5-b0b5e966321d

	measure 'meas.calc_hyp3_kpi1_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var _max_date = [meas.context_date_max]
			var filt_ssr = CALCULATETABLE(ssr, cal_end_dates[Date] > date(1900,1,1) && cal_end_dates[Date] < _max_date) // get rid of date context
			
			
			var res = CALCULATE(
			    COUNTX(filt_ssr, [_sys_doc_id]),
			    ssr_history[step_outcome]  in {"Prospecting","Converted",  "Abandoned", "Ignored", "Untouched"}
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 6ad6c3a0-b0c8-4a09-965e-b6d5e21b682a

	measure 'meas.calc_hyp3_kpi2_denominator' =
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    [meas.ssr_history_accts_per_rep_new_business_sold_to],
			    users_history[trueai_user_role_function] in {"AE", "SDR"}
			)
			RETURN
			res
		formatString: ##0
		displayFolder: heatmap_kpis
		lineageTag: 10788f12-8798-4329-946b-17f02498e9b0

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.calc_hyp3_kpi2_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    [meas.ssr_history_accts_per_rep_new_business_prospected_to],
			    users_history[trueai_user_role_function] in {"AE", "SDR"}
			)
			RETURN
			res
		formatString: ##0
		displayFolder: heatmap_kpis
		lineageTag: ee668dcd-b5bd-4442-af33-db64f078215a

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.calc_hyp4_kpi1_denominator' = 1            // get the hard coded 1 as the def
		description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: a91d2b23-97d3-4cff-9c3b-e5deb4c57af2

	measure 'meas.calc_hyp4_kpi1_nominator' = ```
			
			var res =CALCULATE( 
			    [meas.ssr_history_leads_probability_of_conversion], 
			    ssr[trueai_leadsource_is_inbound]=True,
			    users[trueai_user_role_dept]="MKT"
			)
			
			RETURN
			res
			```
			description: "TODO: provide business definition for this measure."
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: heatmap_kpis
		lineageTag: e163a6de-b533-43c2-adaa-76488d1a39f0

	measure 'meas.calc_hyp4_kpi2_denominator' = ```
			1                 // hardcode 
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: ce114243-6a30-48d8-9fbd-fe9e903a07fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp4_kpi2_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    [meas.ssr_history_leads_probability_of_conversion],
			    ssr[col.trueai_leadsource_inbound_outbound] = "Inbound"     // get the inbound lead avg
			)
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 5688001a-d7b3-4c56-9882-5650fd669f0e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp5_kpi1_denominator' = ```
			1                 // get the hard code 1 
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: ##0
		displayFolder: heatmap_kpis
		lineageTag: efac8dcd-9dbb-4d62-8fc3-afbcea3c24de

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.calc_hyp5_kpi1_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			VAR res = CALCULATE(
			    [meas.ssr_history_inbound_leads_touched_avg_days],      // get the avg. # days to first touch
			    ssr[col.trueai_time_to_touch_days] <= 21
			)
			
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 9fd9b39f-bd8c-443d-adcc-2348ceeadb5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp5_kpi2_denominator' = ```
			1                 // get the hard code 1 
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 7937c831-057f-4a6c-abbd-e7e218e1facf

	measure 'meas.calc_hyp5_kpi2_nominator' = ```
			1               // hard code 
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: d7eaf4c0-47aa-448a-829f-7f62d33f1034

	measure 'meas.calc_hyp6_kpi1_denominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    AVERAGE(ssr_history[stkhlds_all_contacts_count]),
			    ssr_history[step_outcome] = "Closed Lost",
			    ssr_history[opp_lost_stage] in {"Mid", "Late"}
			)
			
			RETURN
			res
		formatString: 0.00
		displayFolder: heatmap_kpis
		lineageTag: f295c26c-bcaf-4b13-8bff-9277558c2ed4

	measure 'meas.calc_hyp6_kpi1_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    AVERAGE(
			        ssr_history[stkhlds_all_contacts_count]
			    ),
			    ssr_history[step_outcome]="Closed Won",
			    ssr_history[step_name]="New Logo Selling"       // filter with New Logo and Won outcome
			)
			
			RETURN
			res
		formatString: 0.00
		displayFolder: heatmap_kpis
		lineageTag: b1e18f58-111a-4608-ac1a-e36589c3f396

	measure 'meas.calc_hyp6_kpi2_denominator' = ```
			
			
			var won_deals_count = CALCULATE(
			    [meas.total_opps_count],
			    opps[trueai_is_won]=false,                   // total won deals
			    ssr_history[step_name]="New Logo Selling",
			    ssr_history[opp_lost_stage] in {"Mid", "Late"}
			)
			
			var stkhlds = CALCULATE(
			    SUM(
			        ssr_history[stkhlds_all_contacts_count]
			    ),
			    opps[trueai_is_won] = false,                         // get won stkhlds for New Logo 
			    ssr_history[step_name] = "New Logo Selling",
			    ssr_history_stakeholders[trueai_title_seniority] in {"Executive", "Senior Executive"},
			    ssr_history[opp_lost_stage] in {"Mid", "Late"}
			)
			
			
			var res = DIVIDE(
			    stkhlds, won_deals_count                // get the average
			)
			
			
			RETURN
			res
			```
			description: "Ratio of opps[trueai_is_won] to ssr_history[step_name]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 69d4c320-930d-4a21-ac85-4986fd14efc3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp6_kpi2_nominator' = ```
			
			
			var won_deals_count = CALCULATE(
			    [meas.total_opps_count],
			    opps[trueai_is_won]=true,                   // total won deals
			    ssr_history[step_name]="New Logo Selling"
			)
			
			var stkhlds = CALCULATE(
			    SUM(
			        ssr_history[stkhlds_all_contacts_count]
			    ),
			    opps[trueai_is_won] = true,                         // get won stkhlds for New Logo 
			    ssr_history[step_name] = "New Logo Selling",
			    ssr_history_stakeholders[trueai_title_seniority] in {"Executive", "Senior Executive"}
			)
			
			
			var res = DIVIDE(
			    stkhlds, won_deals_count                // get the average
			)
			
			
			RETURN
			res
			```
			description: "Ratio of opps[trueai_is_won] to ssr_history[step_name]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 9251a96e-3794-48c0-b70a-f8e08c61e578

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp7_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			CALCULATE(
			    [meas.ssr_history_step_cycle_avg],      // step cycle avg count for Closed Won
			    ssr_history[step_outcome] = "Closed Lost" && ssr_history[step_name]="New Logo Selling"
			
			)
		displayFolder: heatmap_kpis
		lineageTag: 3d75dffa-062f-4a4a-8ad2-2b342713efd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp7_kpi1_nominator' =
			
			description: "TODO: provide business definition for this measure."
			CALCULATE(
			    [meas.ssr_history_step_cycle_avg],          // get the step cycle avg for Lost outcome
			    ssr_history[step_outcome] = "Closed Won" && ssr_history[step_name]="New Logo Selling"
			
			)
		displayFolder: heatmap_kpis
		lineageTag: dd71a2d9-451b-4e3d-ad57-47da1a2faf82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp7_kpi2_denominator' = ```
			
			
			```
			description: "TODO: provide business definition for this measure."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: e6059bfc-35f7-4576-987d-1d271ce4c3d4

	measure 'meas.calc_hyp7_kpi2_nominator' = ```
			
			
			```
			description: "TODO: provide business definition for this measure."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: a86082ad-7e3d-4c3c-a28d-29c5b00a105e

	measure 'meas.calc_hyp8_kpi1_denominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			var previous_year = current_year-1                                  // get the previous year
			
			var _predicted_rate = CALCULATE(
			    [meas.ssr_history_success_prob_avg],
			    YEAR(cal_end_dates[Date])=previous_year,                 // get the previous year average predicted win rate
			    ssr_history[step_name]="New Logo Selling"
			)
			
			var _initial_booking_amt = CALCULATE(
			    [meas.ssr_history_booking_amt],
			    YEAR(cal_end_dates[Date])=previous_year,                 // get the previous year initial booking amt
			    ssr_history[step_name]="New Logo Selling"
			)
			
			
			var res = _predicted_rate * _initial_booking_amt                // multiply
			
			
			RETURN
			res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: 8b8573cf-d12a-4e1d-bab8-cf1d1bda750b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp8_kpi1_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			
			
			var _predicted_rate = CALCULATE(
			    [meas.ssr_history_success_prob_avg],
			    YEAR(cal_end_dates[Date])=current_year,                 // get the current year average predicted win rate
			    ssr_history[step_name]="New Logo Selling"
			)
			
			var _initial_booking_amt = CALCULATE(
			    [meas.ssr_history_booking_amt],
			    YEAR(cal_end_dates[Date])=current_year,                 // get the current year initial booking amt
			    ssr_history[step_name]="New Logo Selling"
			)
			
			
			var res =  _predicted_rate * _initial_booking_amt           // get multiply
			
			
			RETURN
			res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: 940f319f-d959-4e80-b3d5-2af60ac7d189

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp8_kpi2_denominator' =
			
			description: "TODO: provide business definition for this measure."
			1
		formatString: #,0.00
		displayFolder: heatmap_kpis
		lineageTag: 862b30cb-ac72-4b90-95f7-d6397ae31dcc

	measure 'meas.calc_hyp8_kpi2_nominator' =
			
			
			description: "TODO: provide business definition for this measure."
			var res =  CALCULATE(
			    AVERAGE(
			        ssr_history[step_success_prob]          // get the avg step success prob for new logo sale
			    ),
			    ssr_history[opp_sale_type]="New Logo Sale"
			)
			
			
			RETURN
			res
		formatString: #,0.00
		displayFolder: heatmap_kpis
		lineageTag: c3a0fb3b-026f-4ece-bcda-e0534d501623

	measure 'meas.calc_hyp9_kpi1_denominator' =
			
			description: "TODO: provide business definition for this measure."
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			var previous_year = current_year-1                                      // get the previous year
			
			var _predicted_rate = CALCULATE(
			    [meas.ssr_history_success_prob_avg],
			    YEAR(cal_end_dates[Date])=previous_year,                 // get the current year average predicted win rate
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Existing Customer Sale"
			)
			
			var _initial_booking_amt = CALCULATE(
			    [meas.ssr_history_booking_amt],
			    YEAR(cal_end_dates[Date])=previous_year,                 // get the current year initial booking amt
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Existing Customer Sale"
			)
			
			
			var res = _predicted_rate* _initial_booking_amt             // multiply
			
			
			RETURN
			res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: e3e184c6-109f-42ac-b538-c923b6c598c4

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp9_kpi1_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			
			
			var _predicted_rate = CALCULATE(
			    [meas.ssr_history_success_prob_avg],
			    YEAR(cal_end_dates[Date])=current_year,                 // get the previous year average predicted win rate
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Existing Customer Sale"
			)
			
			var _initial_booking_amt = CALCULATE(
			    [meas.ssr_history_booking_amt],
			    YEAR(cal_end_dates[Date])=current_year,                 // get the previous year initial booking amt
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Existing Customer Sale"
			)
			
			
			var res = _predicted_rate*_initial_booking_amt                  // get the multiply value
			
			
			RETURN
			res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: heatmap_kpis
		lineageTag: 6863cb18-f7a3-4170-a304-6e512ecb2ead

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.calc_hyp9_kpi2_denominator' =
			
			description: "TODO: provide business definition for this measure."
			1
		displayFolder: heatmap_kpis
		lineageTag: 20424cf6-be84-4e2d-97b7-7a6840cf7d8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp9_kpi2_nominator' =
			
			description: "TODO: provide business definition for this measure."
			var res =  CALCULATE(
			    AVERAGE(
			        ssr_history[step_success_prob]          // get the avg step success prob for new logo sale
			    ),
			    ssr_history[opp_sale_type]="Existing Customer Sale"
			)
			
			
			RETURN
			res
		formatString: #,0.00
		displayFolder: heatmap_kpis
		lineageTag: 5ff90036-d407-4de3-b5e4-39f54e4104cd

	measure 'meas.check_kpi1_kpi2_weight' =
			
			description: "TODO: provide business definition for this measure."
			var _kpi1 = [meas.getKPI1Weight]
			var _kpi2 = [meas.getKPI2Weight]
			var res = IF(
			    _kpi1+_kpi2 = 1.00,
			    "ok",
			    "error"
			)
			
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: b82cee2a-7f09-480f-9db9-da6a1fac29ad

	measure 'meas.getHeatmapConditionalColor' = ```
			
			var _ai_score = [meas.getHeatmapKPI_AIScore]        // get the validated and not validated
			var _heatmapScore = [meas.getHeatmapScore]          // get the heatmap score
			var res = IF(
			                _ai_score = "Limited",
			                1,
			                IF(
			                    _ai_score in {"Fair","Good", "Great", "Excellent"} && _heatmapScore >=0 && _heatmapScore < 30, 2,
			                    IF(
			                         _ai_score in {"Fair","Good", "Great", "Excellent"} && _heatmapScore >=30 && _heatmapScore < 45, 3,
			                        IF(
			                             _ai_score in {"Fair","Good", "Great", "Excellent"} && _heatmapScore >=45 && _heatmapScore < 50, 4,
			                            IF(
			                                 _ai_score in {"Fair","Good", "Great", "Excellent"}&& _heatmapScore >=50 && _heatmapScore < 65, 5,
			                                IF(
			                                     _ai_score in {"Fair","Good", "Great", "Excellent"} && _heatmapScore >=65 && _heatmapScore < 80, 6,
			                                    IF(
			                                         _ai_score in {"Fair","Good", "Great", "Excellent"} && _heatmapScore >=80 && _heatmapScore <= 100, 7
			                                    )
			                                )
			                            )
			                        )
			                    )
			                )
			)
			
			RETURN
			res
			
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: ac5452d6-99a7-4005-9ef0-0e28aa4df057

	measure 'meas.getHeatmapConditionalColor_new' = ```
			
			// var _ai_score = [meas.getHeatmapKPI_AIScore]        // get the validated and not validated
			var _heatmapScore = [meas.heatmap_details_score_new]          // get the heatmap score
			var res = SWITCH(
			    TRUE(),
			    _heatmapScore="ND",1,
			    _heatmapScore="N/A",2,
			    _heatmapScore >=0 && _heatmapScore < 30,3,
			    _heatmapScore >=30 && _heatmapScore < 45,4,
			    _heatmapScore >=45 && _heatmapScore < 50,5,
			    _heatmapScore >=50 && _heatmapScore < 65,6,
			    _heatmapScore >=65 && _heatmapScore < 80,7,
			    _heatmapScore >=80 && _heatmapScore <= 100,8
			)
			
			RETURN
			res
			
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: beaacaea-29c3-43ad-bfca-8228a3d91f8c

	measure 'meas.getHeatmapKPI_AIScore' =
			
			description: "TODO: provide business definition for this measure."
			VAR kpi1 = [meas.kpi1_ai_score_trust_value]   -- 0–100 scale
			VAR kpi2 = [meas.kpi2_ai_score_trust_value]   -- 0–100 scale
			
			-- KPI2 is truly missing only when it returns BLANK
			VAR _kpi2_missing =
			    ISBLANK(kpi2)
			
			VAR _combined =
			    IF(
			        _kpi2_missing,
			        kpi1,                                -- use only KPI1
			        ROUND( (kpi1 + kpi2) / 2, 0 )        -- average 0–100 scores
			    )
			
			VAR res =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_combined) || _combined < 50, "Limited",
			        _combined < 75, "Fair",
			        _combined < 85, "Good",
			        _combined < 95, "Great",
			        "Excellent"
			    )
			
			RETURN
			    res
		formatString: 0.00
		displayFolder: heatmap_kpis
		lineageTag: c5d815dd-024f-4300-b354-bfb72811632a

	measure 'meas.getHeatmapKPI1_formula_used' =
			
			
			description: "TODO: provide business definition for this measure."
			var _better = MAX(metadata_heatmap_items[heatmap_kpi1_whats_better])           // get ghe what's better
			var _kpi = FORMAT([meas.getKPI1],"0.00")                   // get the KPI1
			var _sd = [meas.trueai_kpi1_sd]             // standard deviation
			var _ref_value = [meas.trueai_kpi1_ref_value]       // reference value
			var _min = [meas.trueai_kpi1_min]                   // get the kpi min value
			var _max = [meas.trueai_kpi1_max]                   // get the Max value
			var _kpi_score = [meas.getKPI1_score]                // get the KPI Score
			
			var txt = "Normalizing this value and multiplying by 100 gives us the KPI 1 Score: "
			
			var _higher =txt & "(KPI 1 Value "& _kpi &" – Min Value "& _min & " ) /  (Max Value " & _max & " - Min Value "& _min &") * 100 =KPI 1 Score" & _kpi_score
			var _lower = txt & "(KPI 1 Value "&_kpi & " -" & "Max Value "& _max & " ) / (Min Value " & _min & " - Max Value "& _max & ") * 100 =KPI 1 Score"& _kpi_score
			var _center = txt &"1/(1+ABS(KPI  1 Value "& _kpi &" - Reference Value"& _ref_value &")/Standard Deviation"& _sd &") * 100 = KPI 1 Score "&_kpi_score
			
			var res = SWITCH(
			    _better,
			    "Higher", _higher,
			    "Lower", _lower,
			    "Center", _center
			)
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 8f1c15a2-ad3f-4746-a959-8c3b429b688c

	measure 'meas.getHeatmapKPI2_formula_used' =
			
			
			description: "TODO: provide business definition for this measure."
			var _better = MAX(metadata_heatmap_items[heatmap_kpi2_whats_better])           // get ghe what's better
			var txt = "Normalizing this value and multiplying by 100 gives us the score: "
			var _higher =txt & "(KPI – Min) /  (Max-Min) * 100 = Score"
			var _lower = txt & "(KPI1 - Max) / (Min - Max) * 100 = Score"
			var _center = txt &"1 / ( 1 + ABS(KPI - Reference)/Standard Deviation) * 100 = Score"
			
			var res = SWITCH(
			    _better,
			    "Higher", _higher,
			    "Lower", _lower,
			    "Center", _center
			)
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 1d1dc947-d1c0-400f-86a8-0429ae6ab4df

	measure 'meas.getHeatmapRawScore' = ```
			
			var _kpi1 = [meas.getKPI1_score]           // get the KPI 1 score
			var _kpi2 = [meas.getKPI2_score]           // get the KPI2 score
			
			var _weight1 = MAX(metadata_heatmap_items[heatmap_kpi1_weight])         // get the KPI1 weight
			var _weight2 = [meas.heatmap_details_kpi2_weight_value]       // KPI2 weight
			
			var score = (_kpi1*_weight1)+(_kpi2*_weight2)     // apply th formula
			
			
			var res =score 
			
			RETURN
			res
			```
			description: "Ratio based on metadata_heatmap_items[heatmap_kpi1_weight]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: fb55813b-ed6c-45d6-bc3c-4252b8a3c2ad

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getHeatmapScore' = ```
			
			
			VAR _ai_score = [meas.getHeatmapKPI_AIScore]            // get the AI Model Score
			VAR res  = MAX([meas.getHeatmapRawScore],0)
			VAR score = ROUND(res/5, 0)*5
			
			VAR final_output = 
			    IF(
			        _ai_score = "Limited", 
			        "ND",   // Exclude rows where AI Score is "Limited"
			        score  
			    )
			
			RETURN
			final_output
			
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 32d061c2-e221-4e48-b5fb-9df0c7b9dea0

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKP2_Score_chng' = ```
			
			
			var cy_kpi2 = [meas.getKPI2_score_cy]          // get the current year KPI1
			var sply_kpi2 = [meas.getKPI2_score_sply]          // get the previous year KPI1
			
			var res = DIVIDE(
			    (cy_kpi2 - sply_kpi2),
			    sply_kpi2                     // get the improvemnet compared to cy 
			)
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 391739a4-9509-45be-8f03-0de6addbdffd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI1' =
			
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			
			var _nominator = CALCULATE(
			    [meas.getKPI1Nominator_Value],            // get the nominator filtering with hypothesis id
			    metadata_heatmap_items[_sys_doc_id]=hyp_id
			)
			
			var _denominator = CALCULATE(
			    [meas.getKPI1Denominator_Value],
			    metadata_heatmap_items[_sys_doc_id]=hyp_id               // get the denominator filtering with hypo id
			)
			
			var res = DIVIDE(_nominator, _denominator)             // get the ratio
			
			
			RETURN
			res
		formatString: 0.00
		displayFolder: heatmap_kpis
		lineageTag: c5d21b27-914c-43e0-853f-bed9a89a6731

	measure 'meas.getKPI1_score' =
			
			description: "TODO: provide business definition for this measure."
			var _kpi = [meas.getKPI1]         // get teh KPI 1
			var _sd = [meas.trueai_kpi1_sd]       // SD
			var _ref = [meas.trueai_kpi1_ref_value]     // reference value
			
			var _better = CALCULATE(MAX(metadata_heatmap_items[heatmap_kpi1_whats_better]))
			
			var _min_value = [meas.trueai_kpi1_min]           // get the min value
			var _max_value =  [meas.trueai_kpi1_max]           // get the max
			
			var res = SWITCH(
			    _better,
			    "Higher", ((_kpi - _min_value)/(_max_value - _min_value)),
			    "Lower", ((_kpi - _max_value) /(_min_value - _max_value)),
			    "Center", 1 / (1 + ABS((_kpi - _ref )) / _sd )
			)
			
			var score = MIN( MAX(ROUND(res*100, 0), 0), 100 )       // get the intger number between 0 to 100
			
			RETURN
			score
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 56e90775-a3ca-4a56-acc5-2bf74bbcdb47

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKPI1_Score_change_pct' = ```
			
			
			var cy = [meas.getKPI1_score]            // get the integer KPI 1 score
			var _sply  = CALCULATE(
			    [meas.getKPI1_score],              // get the existing measure forKPI 1 score            // get the KPI 1 score same period last year
			    SAMEPERIODLASTYEAR(cal_end_dates[Date])           
			)
			var res = DIVIDE((cy - _sply), _sply)           // get the ratio
			
			
			RETURN
			res
			```
			description: "Ratio based on cal_end_dates[Date]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 2ba7d4a8-2640-4a50-b2da-d2d2369e505d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI1_score_cy' = ```
			
			var max_date = [meas.context_date_max]              // get the selected max date
			var start_date_cy = DATE(
			    YEAR(EDATE(max_date, -3)),
			    MONTH(EDATE(max_date, -3))+1,
			    1            // calculate the start date (3 months prior)
			)
			
			var res  = CALCULATE(
			    [meas.getKPI1_score],              // get the existing measure forKPI 1 score
			    cal_end_dates[Date] >= start_date_cy && cal_end_dates[Date] <= max_date           
			)
			
			
			RETURN
			res
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: a06892ee-f6a3-48ce-94ad-82a5e03b8545

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKPI1_score_cy_5q' =
			
			
			description: "TODO: provide business definition for this measure."
			VAR _max_date = [meas.context_date_max] // Get the max date in the dataset
			var _min_date = EDATE([meas.context_date_min],-3)           // get the 3 months back from the context min date
			
			var res = CALCULATE(
			    [meas.getKPI1_score_cy],
			    cal_end_dates[Date] >= _min_date && cal_end_dates[Date] <= _max_date
			)
			
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: a15d1bdd-6026-4e65-b838-ead839d1798e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKPI1_score_delta' = ```
			
			
			var cy_kpi1 = [meas.getKPI1_score_cy]          // get the current year KPI1
			var sply_kpi1 = [meas.getKPI1_score_sply]          // get the previous year KPI1
			
			
			// var res = DIVIDE(
			//     (cy_kpi1 - sply_kpi1),
			//     sply_kpi1                     // get the improvemnet compared to cy 
			// )
			
			var res = (cy_kpi1 - sply_kpi1)
			
			
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: dbb0abc2-cd27-4da8-a138-08a8fc3ab7e4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI1_score_sply' = ```
			
			var max_date = [meas.context_date_max]              // get the selected max date
			var start_date_sply = DATE(
			    YEAR(EDATE(max_date, -3)),
			    MONTH(EDATE(max_date, -3))+1,
			    1            // calculate the start date (3 months prior)
			)
			
			var startdate_lastyear = DATE(YEAR(start_date_sply)- 1, MONTH(start_date_sply), DAY(start_date_sply))          //adjust the start date to last year
			var maxdate_lastyear = DATE(YEAR(max_date) - 1, MONTH(max_date), DAY(max_date))                 //  adjust the max date to the last year
			
			
			
			var res  = CALCULATE(
			    [meas.getKPI1_score],              // get the existing measure
			    cal_end_dates[Date] >= startdate_lastyear && cal_end_dates[Date] <= maxdate_lastyear           
			)
			
			
			RETURN
			res
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 964defbf-305a-45e0-8e50-c383bb10c554

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKPI1Denominator' =
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])
			
			var res = SWITCH(
			    hyp_id,
			    "1", FORMAT([meas.calc_hyp1_kpi1_denominator],"##,#0"" Accounts"),    // hypothesis 1
			    "2", FORMAT([meas.calc_hyp2_kpi1_denominator], "0"),            // hypothesis 2
			    "3", FORMAT([meas.calc_hyp3_kpi1_denominator], "##,#0"" Accounts"),     // hypothesis 3
			    "4", FORMAT([meas.calc_hyp4_kpi1_denominator],"0"),      // hypothesis 4
			    "5", FORMAT([meas.calc_hyp5_kpi1_denominator], "0"),     // hyposthesis 5
			    "6", FORMAT([meas.calc_hyp6_kpi1_denominator],"0.0"" contacts"),           // hypothesis 6
			    "7", FORMAT([meas.calc_hyp7_kpi1_denominator],"#,##0"" days"""),          // hypothesis 7
			    "8", FORMAT([meas.calc_hyp8_kpi1_denominator], "$##,#0"),         // hypothesis 8
			    "9", FORMAT([meas.calc_hyp9_kpi1_denominator],"$##,#0"),                // hypothesis 9
			    "10", FORMAT([meas.calc_hyp10_kpi1_denominator], "$##,#0"),             // hypothesis 10
			    "11", FORMAT([meas.calc_hyp11_kpi1_denominator], "$##,#0"),             // hypothesis 11
			    "12", FORMAT([meas.calc_hyp12_kpi1_denominator], "##,#0"" Accounts"),             // hypothesis 12
			    "13", FORMAT([meas.calc_hyp13_kpi1_denominator], "##,#0"" Accounts"),                              // hypothesis 13
			    "14", FORMAT([meas.calc_hyp14_kpi1_denominator],  "##,#0"" hr"),             // hypothesis 14
			    "15", FORMAT([meas.calc_hyp15_kpi1_denominator], "##,#0"" Reps"),                              // hypothesis 15
			    "16", FORMAT([meas.calc_hyp16_kpi1_denominator],  "##,#0"" Reps"),                              // hypothesis 16
			    "17", FORMAT([meas.calc_hyp17_kpi1_denominator], "$##,#0"),                              // hypothesis 15
			    "18", FORMAT([meas.calc_hyp18_kpi1_denominator], "$##,#0"),
			    BLANK()
			
			)
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 5ebd342f-55ac-4317-af7d-b48548d6e186

	measure 'meas.getKPI1Denominator_Value' = ```
			
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", [meas.calc_hyp1_kpi1_denominator],   // hypothesis 1
			    "2", [meas.calc_hyp2_kpi1_denominator],           // hypothesis 2
			    "3", [meas.calc_hyp3_kpi1_denominator],      // hypothesis 3
			    "4", [meas.calc_hyp4_kpi1_denominator],     // hypothesis 4
			    "5", [meas.calc_hyp5_kpi1_denominator],     // hyposthesis 5
			    "6", [meas.calc_hyp6_kpi1_denominator],           // hypothesis 6
			    "7", [meas.calc_hyp7_kpi1_denominator],          // hypothesis 7
			    "8", [meas.calc_hyp8_kpi1_denominator],         // hypothesis 8
			    "9", [meas.calc_hyp9_kpi1_denominator],               // hypothesis 9
			    "10", [meas.calc_hyp10_kpi1_denominator],            // hypothesis 10
			    "11", [meas.calc_hyp11_kpi1_denominator],            // hypothesis 11
			    "12", [meas.calc_hyp12_kpi1_denominator],             // hypothesis 12
			    "13", [meas.calc_hyp13_kpi1_denominator],                              // hypothesis 13
			    "14", [meas.calc_hyp14_kpi1_denominator],              // hypothesis 14
			    "15", [meas.calc_hyp15_kpi1_denominator],                              // hypothesis 15
			    "16", [meas.calc_hyp16_kpi1_denominator],                              // hypothesis 16
			    "17", [meas.calc_hyp17_kpi1_denominator],                              
			    "18", [meas.calc_hyp18_kpi1_denominator], 
			    BLANK()
			
			)
			RETURN
			res
			```
			description: "Ratio based on metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 378f79ca-4a50-4154-ae0e-cd5990d3941d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI1Nominator' = ```
			
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", FORMAT([meas.calc_hyp1_kpi1_nominator],"##,#0"" Accounts"),    // hypothesis 1
			    "2", FORMAT([meas.calc_hyp2_kpi1_nominator], "0%"),            // hypothesis 2
			    "3", FORMAT([meas.calc_hyp3_kpi1_nominator], "##,#0"" Accounts"),     // hypothesis 3
			    "4", FORMAT([meas.calc_hyp4_kpi1_nominator],"0%"),      // hypothesis 4
			    "5", FORMAT([meas.calc_hyp5_kpi1_nominator], "0.0"" Days"),     // hyposthesis 5
			    "6", FORMAT([meas.calc_hyp6_kpi1_nominator],"0.0"" contacts"),           // hypothesis 6
			    "7", FORMAT([meas.calc_hyp7_kpi1_nominator],"#,##0"" days"""),          // hypothesis 7
			    "8", FORMAT([meas.calc_hyp8_kpi1_nominator], "$##,#0"),         // hypothesis 8
			    "9", FORMAT([meas.calc_hyp9_kpi1_nominator],"$##,#0"),                // hypothesis 9
			    "10", FORMAT([meas.calc_hyp10_kpi1_nominator], "$##,#0"),             // hypothesis 10
			    "11", FORMAT([meas.calc_hyp11_kpi1_nominator], "$##,#0"),             // hypothesis 11
			    "12", FORMAT([meas.calc_hyp12_kpi1_nominator], "##,#0"" Accounts"),             // hypothesis 12
			    "13", FORMAT([meas.calc_hyp13_kpi1_nominator], "##,#0"" Accounts"),                              // hypothesis 13
			    "14", FORMAT([meas.calc_hyp14_kpi1_nominator],  "##,#0"" hr"),             // hypothesis 14
			    "15", FORMAT([meas.calc_hyp15_kpi1_nominator], "##,#0"" Reps"),                              // hypothesis 15
			    "16", FORMAT([meas.calc_hyp16_kpi1_nominator],  "##,#0"" Reps"),                              // hypothesis 16
			    "17", FORMAT([meas.calc_hyp17_kpi1_nominator], "$##,#0"),                              
			    "18", FORMAT([meas.calc_hyp18_kpi1_nominator],  "$##,#0"),                        
			    BLANK()
			
			)
			RETURN
			res
			```
			description: "Ratio based on metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 971414e6-3fc2-4a28-a100-9c9594cfc293

	measure 'meas.getKPI1Nominator_Value' = ```
			
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			RETURN 
			SWITCH(
			    hyp_id,
			    "1", [meas.calc_hyp1_kpi1_nominator],    
			    "2", [meas.calc_hyp2_kpi1_nominator],    
			    "3", [meas.calc_hyp3_kpi1_nominator],    
			    "4", [meas.calc_hyp4_kpi1_nominator],    
			    "5", [meas.calc_hyp5_kpi1_nominator],    
			    "6", [meas.calc_hyp6_kpi1_nominator],    
			    "7", [meas.calc_hyp7_kpi1_nominator],    
			    "8", [meas.calc_hyp8_kpi1_nominator],    
			    "9", [meas.calc_hyp9_kpi1_nominator],    
			    "10", [meas.calc_hyp10_kpi1_nominator],    
			    "11", [meas.calc_hyp11_kpi1_nominator],    
			    "12", [meas.calc_hyp12_kpi1_nominator],    
			    "13", [meas.calc_hyp13_kpi1_nominator],    
			    "14", [meas.calc_hyp14_kpi1_nominator],    
			    "15", [meas.calc_hyp15_kpi1_nominator],    
			    "16", [meas.calc_hyp16_kpi1_nominator], 
			    "17", [meas.calc_hyp17_kpi1_nominator],    
			    "18", [meas.calc_hyp18_kpi1_nominator], 
			    BLANK()
			)
			
			```
			description: "Ratio based on metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: d5a164d0-184c-42b3-9a27-bb2d29c8cb9f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKPI1Weight' =
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])               // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "2", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "3", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "4", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "5", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "6", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "7", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "8", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "9", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "10", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "11", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "12", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "13", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "14", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "15", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    "16", MAX(metadata_heatmap_items[heatmap_kpi1_weight]),    // KPI 1 weight score
			    BLANK()
			
			)
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 841707c7-2092-4b4d-b836-acae9cca49f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI2' =
			
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			
			var _nominator = CALCULATE(
			    [meas.getKPI2Nominator_Value],            // get the nominator filtering with hypothesis id
			    metadata_heatmap_items[_sys_doc_id]=hyp_id
			)
			
			var _denominator = CALCULATE(
			    [meas.getKPI2Denominator_Value],
			    metadata_heatmap_items[_sys_doc_id]=hyp_id               // get the denominator filtering with hypo id
			)
			
			var res = DIVIDE(_nominator, _denominator)             // get the ratio
			
			
			RETURN
			res
		formatString: 0.00
		displayFolder: heatmap_kpis
		lineageTag: eb377ea0-25bc-4d63-8303-98284f115819

	measure 'meas.getKPI2_score' =
			
			description: "TODO: provide business definition for this measure."
			var _kpi = [meas.getKPI2]         // get teh KPI 1
			var _sd = CALCULATE(MAX(metadata_heatmap_items[col.kpi2_std_value]))       // SD
			var _ref = CALCULATE(MAX(metadata_heatmap_items[col.kpi2_ref_value]))      // reference value
			
			var _better = CALCULATE(MAX(metadata_heatmap_items[heatmap_kpi2_whats_better]))
			
			var _min_value = [meas.trueai_kpi2_min]           // get the min value
			var _max_value =  [meas.trueai_kpi2_max]           // get the max
			
			var res = SWITCH(
			    _better,
			    "Higher", ((_kpi - _min_value)/(_max_value - _min_value)),
			    "Lower", ((_kpi - _max_value) /(_min_value - _max_value)),
			    "Center", 1 / (1 + ABS((_kpi - _ref )) / _sd )
			)
			
			var score = MIN( MAX(ROUND(res*100, 0), 0), 100 )       // get the intger number between 0 to 100
			RETURN
			score
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 6fa13fa4-bfcf-4746-8573-808f7e6536d6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKPI2_Score_change_pct' = ```
			
			var cy = [meas.getKPI2_score]            // get the integer KPI 2 score
			var _sply  = CALCULATE(
			    [meas.getKPI2_score],              // get the existing measure forKPI 2 score            // get the KPI 2 score same period last year
			    SAMEPERIODLASTYEAR(cal_end_dates[Date])           
			)
			var res = DIVIDE((cy - _sply), _sply)           // get the ratio
			
			
			RETURN
			res
			```
			description: "Ratio based on cal_end_dates[Date]. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: c07674bd-6dfa-4ade-a107-6543968acf32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI2_score_cy' = ```
			
			var kpi2_def = MAX(metadata_heatmap_items[heatmap_kpi2_def_short])
			var max_date = [meas.context_date_max]              // get the selected max date
			var start_date_cy = DATE(
			    YEAR(EDATE(max_date, -3)),
			    MONTH(EDATE(max_date, -3))+1,
			    1            // calculate the start date (3 months prior)
			)
			
			var res  = CALCULATE(
			    [meas.getKPI2_score],              // get the existing measure forKPI 1 score
			    cal_end_dates[Date] >= start_date_cy && cal_end_dates[Date] <= max_date           
			)
			
			var _new_res = IF(
			    kpi2_def=BLANK(),
			    BLANK(),
			    res
			)
			
			
			
			RETURN
			_new_res
			```
			description: "Ratio of metadata_heatmap_items[heatmap_kpi2_def_short] to cal_end_dates[Date]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 0fb54a2f-621d-4280-bd05-3b6e8cc47070

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKPI2_score_cy_5q' =
			
			
			description: "TODO: provide business definition for this measure."
			VAR _max_date = [meas.context_date_max] // Get the max date in the dataset
			var _min_date = EDATE([meas.context_date_min],-3)
			
			var res = CALCULATE(
			    [meas.getKPI2_score_cy],
			    cal_end_dates[Date] >= _min_date && cal_end_dates[Date] <= _max_date
			)
			
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 40e03981-6b77-412e-9aac-a187087fac4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI2_score_delta' = ```
			
			
			var cy_kpi2 = [meas.getKPI2_score_cy]          // get the current year KPI2
			var sply_kpi2 = [meas.getKPI2_score_sply]          // get the previous year KPI2
			// var res = DIVIDE(
			//     (cy_kpi2 - sply_kpi2),
			//     sply_kpi2                     // get the improvemnet compared to cy 
			// )
			
			var res = (cy_kpi2 - sply_kpi2)
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0.00
		displayFolder: heatmap_kpis
		lineageTag: 73e232a7-67ee-4456-b32d-f251ec0fb84d

	measure 'meas.getKPI2_score_sply' = ```
			
			var kpi2_def = MAX(metadata_heatmap_items[heatmap_kpi2_def_short])          // check if we have kpi2
			var max_date = [meas.context_date_max]              // get the selected max date
			var start_date_sply = DATE(
			    YEAR(EDATE(max_date, -3)),
			    MONTH(EDATE(max_date, -3))+1,
			    1            // calculate the start date (3 months prior)
			)
			
			var startdate_lastyear = DATE(YEAR(start_date_sply)- 1, MONTH(start_date_sply), DAY(start_date_sply))          //adjust the start date to last year
			var maxdate_lastyear = DATE(YEAR(max_date) - 1, MONTH(max_date), DAY(max_date))                 //  adjust the max date to the last year
			
			
			
			var res  = CALCULATE(
			    [meas.getKPI2_score],              // get the existing measure
			    cal_end_dates[Date] >= startdate_lastyear && cal_end_dates[Date] <= maxdate_lastyear           
			)
			
			
			var _new_res = IF(
			    kpi2_def=BLANK(),
			    BLANK(),
			    res
			)
			
			
			
			RETURN
			_new_res
			```
			description: "Ratio of metadata_heatmap_items[heatmap_kpi2_def_short] to cal_end_dates[Date]. Respects the current filter context."
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 2c60c622-567c-4c75-ada9-21ea5a08354c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.getKPI2Denominator' =
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", FORMAT([meas.calc_hyp1_kpi2_denominator],"#,##0"" hrs"""),                      // hypothesis 1 kpi 2 Nominator
			    //"2", FORMAT([meas.calc_hyp2_kpi2_denominator], "0%"),                                       // hypothesis 2
			    //"3", FORMAT(heatmap[meas.calc_hyp3_kpi2_denominator],"##,#0"" Accounts"),                                // get the hyp3 kpi 2
			    //"4", FORMAT(heatmap[meas.calc_hyp4_kpi2_denominator], "0"),                             // hypothesis 4
			    //"5", FORMAT([meas.calc_hyp5_kpi2_denominator], "##,#"),                                     // hypothesis 5
			    "6", FORMAT([meas.calc_hyp6_kpi2_denominator],"0.00"),                               // hypothesis 6
			    //"7", FORMAT(heatmap[meas.calc_hyp7_kpi2_denominator], "#,##0"" days"""),                    // hypothesis 7
			    "8", FORMAT([meas.calc_hyp8_kpi2_denominator], "0"),                                       // hypothesis 8
			    "9", FORMAT([meas.calc_hyp9_kpi2_denominator], "0"),                                       // hypothesis 9
			    "10", FORMAT([meas.calc_hyp10_kpi2_denominator], "0"),                                     // hypothesis 10
			    "11", FORMAT([meas.calc_hyp11_kpi2_denominator], "#,##0"" hrs"""),                          // hypothesis 11
			    "12", FORMAT([meas.calc_hyp12_kpi2_denominator], "##,#0"" Accounts"),                                  // hypothesis 12
			    "13", FORMAT([meas.calc_hyp13_kpi2_denominator], "$##,#0"),                                 // hypothesis 13
			    //"14", FORMAT([meas.calc_hyp14_kpi2_denominator], "##,#0"" hrs"),                                  // hypothesis 14
			    //"15", FORMAT([meas.calc_hyp15_kpi2_denominator],"##,#0"" Reps"),                                   // hypothesis 15
			    "16", FORMAT([meas.calc_hyp16_kpi2_denominator], "##,#0"" Reps"),                                  // hypothesis 16
			    BLANK()
			
			)
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 7e2bf85f-31d7-479c-8795-09b41f05e5aa

	measure 'meas.getKPI2Denominator_Value' =
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", [meas.calc_hyp1_kpi2_denominator],                      // hypothesis 1 kpi 2 Nominator
			    //"2", [meas.calc_hyp2_kpi2_denominator],                                       // hypothesis 2
			    //"3", [meas.calc_hyp3_kpi2_denominator],                                // get the hyp3 kpi 2
			    //"4", [meas.calc_hyp4_kpi2_denominator],                            // hypothesis 4
			    //"5",[meas.calc_hyp5_kpi2_denominator],                                     // hypothesis 5
			    "6", [meas.calc_hyp6_kpi2_denominator],                              // hypothesis 6
			    //"7", [meas.calc_hyp7_kpi2_denominator],                     // hypothesis 7
			    "8", [meas.calc_hyp8_kpi2_denominator],                                       // hypothesis 8
			    "9", [meas.calc_hyp9_kpi2_denominator],                                        // hypothesis 9
			    "10", [meas.calc_hyp10_kpi2_denominator],                                     // hypothesis 10
			    "11", [meas.calc_hyp11_kpi2_denominator],                          // hypothesis 11
			    "12", [meas.calc_hyp12_kpi2_denominator],                                  // hypothesis 12
			    "13", [meas.calc_hyp13_kpi2_denominator],                                  // hypothesis 13
			    //"14", [meas.calc_hyp14_kpi2_denominator],                                  // hypothesis 14
			    //"15", [meas.calc_hyp15_kpi2_denominator],                                  // hypothesis 15
			    "16", [meas.calc_hyp16_kpi2_denominator],                                   // hypothesis 16
			    BLANK()
			
			)
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 34685723-f6e9-44b3-addb-02c908eadb54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI2Nominator' =
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", FORMAT([meas.calc_hyp1_kpi2_nominator],"#,##0"" hrs"""),                      // hypothesis 1 kpi 2 Nominator
			    //"2", FORMAT([meas.calc_hyp2_kpi2_nominator], "0%"),                                       // hypothesis 2
			    //"3", FORMAT(heatmap[meas.calc_hyp3_kpi2_Nominator],"##,#0"" Accounts"),                                // get the hyp3 kpi 2
			    //"4", FORMAT(heatmap[meas.calc_hyp4_kpi2_nominator], "0%"),                             // hypothesis 4
			    //"5", FORMAT([meas.calc_hyp5_kpi2_Nominator], "##,#"),                                     // hypothesis 5
			    "6", FORMAT([meas.calc_hyp6_kpi2_nominator],"0.00"),                               // hypothesis 6
			    //"7", FORMAT(heatmap[meas.calc_hyp7_kpi2_nominator], "#,##0"" days"""),                    // hypothesis 7
			    "8", FORMAT([meas.calc_hyp8_kpi2_nominator], "0.00"),                                       // hypothesis 8
			    "9", FORMAT([meas.calc_hyp9_kpi2_nominator], "0.00"),                                       // hypothesis 9
			    "10", FORMAT([meas.calc_hyp10_kpi2_nominator], "0.00"),                                     // hypothesis 10
			    "11", FORMAT([meas.calc_hyp11_kpi2_nominator], "#,##0"" hrs"""),                          // hypothesis 11
			    "12", FORMAT([meas.calc_hyp12_kpi2_nominator], "##,#0"" Accounts"),                                  // hypothesis 12
			    "13", FORMAT([meas.calc_hyp13_kpi2_nominator], "$##,#0"),                                 // hypothesis 13
			    //"14", FORMAT([meas.calc_hyp14_kpi2_Nominator], "##,#0"" hrs"),                                  // hypothesis 14
			    //"15", FORMAT([meas.calc_hyp15_kpi2_nominator],"##,#0"" Reps"),                                   // hypothesis 15
			    "16", FORMAT([meas.calc_hyp16_kpi2_nominator], "##,#0"" Reps"),                                  // hypothesis 16
			    BLANK()
			
			)
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 009d3b0a-0454-41cf-addc-1dd4d180965e

	measure 'meas.getKPI2Nominator_Value' =
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])           // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", [meas.calc_hyp1_kpi2_nominator],                      // hypothesis 1 kpi 2 Nominator
			    //"2", [meas.calc_hyp2_kpi2_nominator],                                      // hypothesis 2
			    //"3",[meas.calc_hyp3_kpi2_Nominator],                                // get the hyp3 kpi 2
			    //"4", [meas.calc_hyp4_kpi2_nominator],                             // hypothesis 4
			    //"5", [meas.calc_hyp5_kpi2_Nominator],                                    // hypothesis 5
			    "6", [meas.calc_hyp6_kpi2_nominator],                             // hypothesis 6
			    //"7", [meas.calc_hyp7_kpi2_nominator],                     // hypothesis 7
			    "8", [meas.calc_hyp8_kpi2_nominator],                                        // hypothesis 8
			    "9", [meas.calc_hyp9_kpi2_nominator],                                       // hypothesis 9
			    "10", [meas.calc_hyp10_kpi2_nominator],                                      // hypothesis 10
			    "11", [meas.calc_hyp11_kpi2_nominator],                           // hypothesis 11
			    "12", [meas.calc_hyp12_kpi2_nominator],                                   // hypothesis 12
			    "13", [meas.calc_hyp13_kpi2_nominator],                                  // hypothesis 13
			    //"14", [meas.calc_hyp14_kpi2_Nominator],                                  // hypothesis 14
			    //"15", [meas.calc_hyp15_kpi2_nominator],                                   // hypothesis 15
			    "16", [meas.calc_hyp16_kpi2_nominator],                                   // hypothesis 16
			    BLANK()
			
			)
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: fa0b3179-8264-4d13-98cb-51ec62e0ac9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI2Weight' =
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])               // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "2", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "3", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "4", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "5", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "6", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "7", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "8", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "9", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "10", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "11", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "12", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "13", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "14", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "15", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    "16", MAX(metadata_heatmap_items[col.kpi2_weight]),    // KPI 1 weight score
			    BLANK()
			
			)
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 3aa983b0-fd01-443b-a92a-dc5e385431b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_booking_growth_rate' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual for current year
			var dates_tbl_cur =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_ytd &&  cal_end_dates[Date] <= end_date)
			var cur_tbl = FILTER(
			    dates_tbl_cur,
			    ssr_history[step_name] in {"New Logo Selling", "Existing Customer Selling"} && ssr_history[step_success]=True
			)
			var res_cur = SUMX(cur_tbl, ssr_history[opp_won_amt]) + 0
			
			-- get data for overridden date periods but still contextual for current year
			var dates_tbl_sply =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_ytd_sply &&  cal_end_dates[Date] <= end_date_sply)
			var sply_tbl = FILTER(
			    dates_tbl_sply,
			    ssr_history[step_name] in {"New Logo Selling", "Existing Customer Selling"} && ssr_history[step_success]=True
			)
			var res_sply = SUMX(sply_tbl, ssr_history[opp_won_amt]) + 0
			var res = DIVIDE((res_cur-res_sply),res_sply,0)
			return 
			res
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		formatString: 0%;-0%;0%
		displayFolder: heatmap_kpis
		lineageTag: 192bf663-1795-4b03-9ced-03ed2f8f2db8

	measure 'meas.heatmap_rounded_score' =
			
			
			description: "TODO: provide business definition for this measure."
			VAR res  = MAX([meas.getHeatmapRawScore],0)     // get the raw score into rounded score with 5 step
			VAR score = ROUND(res/5, 0)*5
			RETURN
			score
		displayFolder: heatmap_kpis
		lineageTag: ec026e3f-2bd0-461d-a9c7-ea838cbd882c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_trust_data_pi' = ```
			
			// KPI1 Model Score + KPI2 AI Model Score / 2
			
			var _kpi1 = [meas.kpi1_ai_score_trust_value]           // get AI score for kpi1
			var _kpi2 = [meas.kpi2_ai_score_trust_value]           // get AI score for kpi2
			
			var res = IF(
			    _kpi2=BLANK(), 
			     "(" & _kpi1  & ") / 1 = "& FORMAT((_kpi1 + _kpi2)/1,"0"), 
			    "(" & _kpi1 & " + " & _kpi2 & ") / 2 = "& FORMAT((_kpi1 + _kpi2)/2,"0")
			)
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: f5eae470-d0e5-43cf-8357-e08d13a73fa1

	measure 'meas.how_kpi1_calculated' =
			
			description: "TODO: provide business definition for this measure."
			var _nominator = [meas.getKPI1Nominator]            // get nominator
			var _denominator = [meas.getKPI1Denominator]            // get denominator
			
			var _nom_def = [meas.heatmap_details_kpi1_nominator_def]            // get the nominator definition
			var _denom_def = [meas.heatmap_details_kpi1_denominator_def]        // denominator definition
			
			var _kpi = FORMAT([meas.getKPI1],"0.00")                   // get the KPI
			
			//"[nominator value] nominator def / {denominator value] denominator def = [result]"
			var res = _nominator & " " & _nom_def & " / " & _denominator & " " & _denom_def &" = " & _kpi
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: fc92f66a-02e9-4c72-a0fa-a8ce03c657c9

	measure 'meas.how_kpi1_component_considered' =
			
			
			description: "TODO: provide business definition for this measure."
			var _weight =MAX(metadata_heatmap_items[heatmap_kpi1_weight])          // get ghe weight
			
			var res = "This component is weighted at "&  FORMAT(_weight, "0%") &" of the total score"
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: c51f000c-47cc-4615-9a69-e9727b13e8f5

	measure 'meas.how_kpi1_score_calculation' =
			
			
			description: "TODO: provide business definition for this measure."
			var _better = MAX(metadata_heatmap_items[heatmap_kpi1_whats_better])           // get ghe what's better
			var _kpi = FORMAT([meas.getKPI1],"0.00")                   // get the KPI1
			var _sd = FORMAT([meas.trueai_kpi1_sd],"0.00")             // standard deviation
			var _ref_value = FORMAT([meas.trueai_kpi1_ref_value],"0.00")       // reference value
			var _min = FORMAT([meas.trueai_kpi1_min],"0.00")                 // get the kpi min value
			var _max = FORMAT([meas.trueai_kpi1_max],"0.00")                   // get the Max value
			var _kpi_score = FORMAT([meas.getKPI1_score],"0.00")                // get the KPI Score
			
			
			var _higher ="("&_kpi &" – "& _min & " ) /  (" & _max & " -  "& _min &") * 100 = " & _kpi_score
			var _lower = "("&_kpi & " -" & ""& _max & " ) / ( " & _min & " - "& _max & ") * 100 = "& _kpi_score
			var _center = "1/(1+ABS("& _kpi &" - "& _ref_value &")/"& _sd &") * 100 = "&_kpi_score
			
			var res = SWITCH(
			    _better,
			    "Higher", _higher,
			    "Lower", _lower,
			    "Center", _center
			)
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 31f0e696-1f5f-4297-9a1f-49ad3127f589

	measure 'meas.how_kpi2_calculated' =
			
			description: "TODO: provide business definition for this measure."
			var _nominator = [meas.getKPI2Nominator]            // get nominator
			var _denominator = [meas.getKPI2Denominator]            // get denominator
			
			var _nom_def = [meas.heatmap_details_kpi2_nominator_def]            // get the nominator definition
			var _denom_def = [meas.heatmap_details_kpi2_denominator_def]        // denominator definition
			
			var _kpi = FORMAT([meas.getKPI2],"0.00")                   // get the KPI2
			
			//"[nominator value] nominator def / {denominator value] denominator def = [result]"
			// var res = _nominator & " " & _nom_def & " / " & _denominator & " " & _denom_def & " = " & _kpi
			var res =IF(
			    _nominator = BLANK() && _denominator= BLANK(),
			    "--",
			    _nominator & " " & _nom_def & " / " & _denominator & " " & _denom_def & " = " & _kpi
			)
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: e239f32c-ec6c-49e7-8a94-d143371ed4b2

	measure 'meas.how_kpi2_component_considered' = ```
			
			var _nominator = [meas.getKPI2Nominator]            // get nominator
			var _denominator = [meas.getKPI2Denominator]            // get denominator
			
			var _wt =[meas.heatmap_details_kpi2_weight_value]          // get ghe weight
			var _weight = IF(
			    _nominator=BLANK() && _denominator=BLANK(),
			    0,
			    _wt
			)
			
			var res = "This component is weighted at "&  FORMAT(_weight, "0%") &" of the total score"
			  
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 87c7dedd-91ea-4fac-a6ef-fc084ea8d3bb

	measure 'meas.how_kpi2_score_calculation' =
			
			
			description: "TODO: provide business definition for this measure."
			var _better = MAX(metadata_heatmap_items[heatmap_kpi2_whats_better])           // get ghe what's better
			var _kpi = FORMAT([meas.getKPI2],"0.00")                   // get the KPI2
			var _sd = format([meas.trueai_kpi2_sd],"0.00")             // standard deviation
			var _ref_value = format([meas.trueai_kpi2_ref_value],"0.00")       // reference value
			var _min = format([meas.trueai_kpi2_min],"0.00")                   // get the kpi min value
			var _max = format([meas.trueai_kpi2_max],"0.00")                   // get the Max value
			var _kpi_score = format([meas.getKPI2_score],"0.00")                // get the KPI Score
			
			
			var _higher ="("&_kpi &" – "& _min & " ) /  (" & _max & " -  "& _min &") * 100 = " & _kpi_score
			var _lower = "("&_kpi & " -" & ""& _max & " ) / ( " & _min & " - "& _max & ") * 100 = "& _kpi_score
			var _center = "1/(1+ABS("& _kpi &" - "& _ref_value &")/"& _sd &") * 100 = "&_kpi_score
			
			var res = SWITCH(
			    _better,
			    "Higher", _higher,
			    "Lower", _lower,
			    "Center", _center
			)
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 76422327-e4ca-4141-9c31-7c2f02c60b0b

	measure 'meas.hypothesis_final_score' =
			
			description: "TODO: provide business definition for this measure."
			//(Score 1 x Weighting 1)  + (Score 2 x Weighting 2) / (Score 1 + Score 2) = Final Score
			
			var _kpi1_score = [meas.getKPI1_score]           // get the KPI1 Score
			var _kpi2_score = [meas.getKPI2_score]           // get the KPI2 score
			
			var _kpi1_weight = MAX(metadata_heatmap_items[heatmap_kpi1_weight])             // get the kpi1 weight
			var _kpi2_weight = [meas.heatmap_details_kpi2_weight_value]             // get the kpi2 weigt
			
			var score  = ( _kpi1_score * _kpi1_weight ) + ( _kpi2_score  * _kpi2_weight )
			
			
			var res = "("& _kpi1_score &" * " & _kpi1_weight& ")" & "+ (" & _kpi2_score& " * "& _kpi2_weight & ") = " & FORMAT(score,"0")
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: d92599db-4cbe-4973-9a04-9a9748d1ed13

	measure 'meas.hypothesis_is_confirmed' = ```
			
			var _score = [meas.heatmap_details_score_new]
			
			var res = IF(
			    _score in {"ND", "N/A"},
			    "",
			    IF(
			        _score < 45, 
			        "Yes",
			        ""
			    )
			)
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 4862d608-0767-4531-ae8e-d5058865bd0a

	measure 'meas.KPI1_AI_score_bucket' =
			
			description: "TODO: provide business definition for this measure."
			VAR _score = [meas.kpi1_ai_score_trust_value]   -- 0-100 score
			
			RETURN
			SWITCH(
			    TRUE(),
			    _score >= 95, "Excellent",
			    _score >= 85, "Great",
			    _score >= 75, "Good",
			    _score >= 50, "Fair",
			    _score >= 0,  "Limited",
			    BLANK()
			)
		displayFolder: heatmap_kpis
		lineageTag: 97a5e09a-34cc-450c-bf60-8dbdd581d164

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.kpi1_ai_score_trust' =
			
			
			description: "TODO: provide business definition for this measure."
			var _score_name = MAX(metadata_heatmap_items[heatmap_kpi1_ai_score_name])            // get the AI Score name
			var _score = [meas.kpi1_ai_score_trust_value]                  // get the AI score value
			var _bucket = [meas.KPI1_AI_score_bucket]                         // bucket name
			var res = IF(
			    _bucket="-",
			    _score_name & "(" & _score & " - "& ")",
			    _score_name & "("  & _score & " - " & _bucket & " )"
			)
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 2200dbd9-a4a1-43e7-b931-78e9f303cbb6

	measure 'meas.kpi1_ai_score_trust_value' =
			
			description: "TODO: provide business definition for this measure."
			VAR _score_name =
			    MAX(metadata_heatmap_items[heatmap_kpi1_ai_score_name])
			
			-- underlying normalized value (0–1)
			VAR _raw =
			    SWITCH(
			        TRUE(),
			        _score_name = "Adjusted Duration",                      [meas.ai_scores_adj_duration],
			        _score_name = "AI Score Not Needed (insight always available)", 1,
			        _score_name = "SSR Leadsource Consolidation",           [meas.ai_scores_ssr_leadsource],
			        _score_name = "Sales Process",                          [meas.ai_scores_sales_process],
			        _score_name = "Activity Capture Levels",                [meas.ai_scores_ci_act_capt_lvl],
			        _score_name = "Bookings Calibration",                   [meas.ai_scores_booking_calibration],
			        _score_name = "Revenue Calibration",                    [meas.ai_scores_revenue_calibration],
			        _score_name = "Line-Item Products",                     [meas.ai_scores_line_items_products],
			        _score_name = "Performance Tiers",                      [meas.ai_scores_performance_tiers],
			        _score_name = "Ramping Success",                        [meas.ai_scores_ramping],
			        _score_name = "Prospecting Success Predictions",        [meas.ai_scores_pred_prospecting],
			        _score_name = "Existing Customer Success Predictions",  [meas.ai_scores_pred_existing_customer_selling],
			        _score_name = "Rep Org. Calibration",                   [meas.ai_scores_rep_org_calibration],
			        _score_name = "New Logo Success Predictions",           [meas.ai_scores_pred_new_logo_selling]
			    )
			
			-- scale 0–1 → 0–100
			VAR _scaled = _raw * 100
			
			-- preserve BLANK instead of converting to 0
			VAR _capped =
			    IF(
			        ISBLANK(_scaled),
			        BLANK(),
			        MAX(0, MIN(_scaled, 100))
			    )
			
			RETURN
			    _capped
		displayFolder: heatmap_kpis
		lineageTag: 33ed841f-d4d2-4575-95cd-c4a06c7ee262

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.kpi1_score_cy' = ```
			
			
			var res  = CALCULATE(
			    [meas.getKPI1_score_cy] ,  
			    REMOVEFILTERS('cal_end_dates'),  
			    'cal_end_dates'[Date] >= EDATE(TODAY(), -15)
			)
			
			RETURN
			res
			```
			description: "TODO: provide business definition for this measure."
		displayFolder: heatmap_kpis
		lineageTag: 7fbde2b1-730f-41a7-ab42-57a7ce963ac3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.KPI2_AI_score_bucket' =
			
			description: "TODO: provide business definition for this measure."
			VAR _score = [meas.kpi2_ai_score_trust_value]   -- 0-100 score
			
			RETURN
			SWITCH(
			    TRUE(),
			    _score >= 95, "Excellent",
			    _score >= 85, "Great",
			    _score >= 75, "Good",
			    _score >= 50, "Fair",
			    _score >= 0,  "Limited",
			    BLANK()
			)
		displayFolder: heatmap_kpis
		lineageTag: 5248f2f7-65f4-4b40-b2d7-284c0fd05fba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.kpi2_ai_score_trust' =
			
			description: "TODO: provide business definition for this measure."
			var _score_name = MAX(metadata_heatmap_items[heatmap_kpi2_ai_score_name])            // get the AI Score name
			var _score = [meas.kpi2_ai_score_trust_value]                  // get the AI score value
			var _bucket = [meas.KPI2_AI_score_bucket]                         // bucket name
			var res = IF(
			    _bucket="-",
			    _score_name & "(" & _score & " - "& ")",
			    _score_name & "("  & _score & " - " & _bucket & " )"
			)
			
			RETURN
			res
		displayFolder: heatmap_kpis
		lineageTag: 218b2659-eb4c-43fd-b080-5245eeb846bb

	measure 'meas.kpi2_ai_score_trust_value' =
			
			description: "TODO: provide business definition for this measure."
			VAR _score_name =
			    MAX(metadata_heatmap_items[heatmap_kpi2_ai_score_name])
			
			-- underlying normalized value (0–1)
			VAR _raw =
			    SWITCH(
			        TRUE(),
			        _score_name = "Adjusted Duration",                      [meas.ai_scores_adj_duration],
			        _score_name = "AI Score Not Needed (insight always available)", 1,   -- normalized
			        _score_name = "SSR Leadsource Consolidation",           [meas.ai_scores_ssr_leadsource],
			        _score_name = "Sales Process",                          [meas.ai_scores_sales_process],
			        _score_name = "Activity Capture Levels",                [meas.ai_scores_ci_act_capt_lvl],
			        _score_name = "Bookings Calibration",                   [meas.ai_scores_booking_calibration],
			        _score_name = "Revenue Calibration",                    [meas.ai_scores_revenue_calibration],
			        _score_name = "Line-Item Products",                     [meas.ai_scores_line_items_products],
			        _score_name = "Performance Tiers",                      [meas.ai_scores_performance_tiers],
			        _score_name = "Ramping Success",                        [meas.ai_scores_ramping],
			        _score_name = "Prospecting Success Predictions",        [meas.ai_scores_pred_prospecting],
			        _score_name = "Existing Customer Success Predictions",  [meas.ai_scores_pred_existing_customer_selling],
			        _score_name = "Rep Org. Calibration",                   [meas.ai_scores_rep_org_calibration],
			        _score_name = "New Logo Success Predictions",           [meas.ai_scores_pred_new_logo_selling]
			    )
			
			-- scale 0–1 → 0–100
			VAR _scaled = _raw * 100
			
			-- cap between 0 and 100
			VAR _capped =
			    IF(
			        ISBLANK(_scaled),
			        BLANK(),
			        MAX(0, MIN(_scaled, 100))
			    )
			
			RETURN
			    _capped
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 9a0c2441-1cdd-4190-a24e-05a59c2ff85b

	measure 'meas.loading' =
			
			description: "TODO: provide business definition for this measure."
			COUNTROWS(metadata_heatmap_items)
		formatString: 0
		displayFolder: heatmap_kpis
		lineageTag: 32c9100b-4e13-4ed1-9283-2bfb66f30457

	measure Measure_SVGArrow = ```
			
			VAR _Value = ROUND([meas.kpi_combined_score]*100,0)          -- Get the value for the arrows to reflect
			
			-- Assigning angles based on thresholds
			VAR Angle =
			    SWITCH(TRUE(),
			        _Value <= -50, 270,   
			        _Value <= -25, 240,   
			        _Value <= -10, 210,   
			        _Value < 0, 180,      
			        _Value <= 1, 0,       
			        _Value <= 9, 30,      
			        _Value <= 25, 60,     
			        _Value <= 60, 90,     
			        120                   
			    )
			
			-- Assigning colors to each category (Ensuring proper string formatting)
			VAR Color =
			    SWITCH(TRUE(),
			        _Value >= 60, "#336600",   
			        _Value >= 26, "#71A43D",   
			        _Value >= 10, "#99CC66",   
			        _Value >= 1, "#FFC107",    
			        _Value >= -1, "#6C757D",   
			        _Value >= -9, "#FF5733",   
			        _Value >= -24, "#DC3545",  
			        _Value >= -49, "#8B0000",  
			        "#4B0000"                  
			    )
			
			-- Ensuring Color Variable is properly enclosed in the SVG string
			VAR SVG =
			    "<svg width='20' height='20' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'>
			        <g transform='rotate(" & FORMAT(Angle, "0") & ",12,12)'>
			            <polygon points='12,2 22,22 2,22' style='fill:"&Color&";'/>
			        </g>
			    </svg>"
			
			-- Encode as Image URL
			
			VAR EncodedSVG = "data:image/svg+xml;utf8," & SUBSTITUTE(SVG, "#", "%23")
			RETURN EncodedSVG
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_kpis
		lineageTag: 8ddfe7c9-1f4c-4a5b-be2b-3085de702e7a
		dataCategory: ImageUrl

	measure Measure_SVGArrow_KPIscore =
			
			description: "TODO: provide business definition for this measure."
			VAR _Value = ([meas.kpi_combined_score])          -- Get the value for the arrows to reflect
			
			-- Assigning angles based on thresholds
			VAR Angle =
			    SWITCH(TRUE(),
			        _Value <= -0.60, 60, --Worsening Significantly
			        _Value <= -0.25, 30, --Worsening Moderately
			        _Value <= -0.09, 20, --Worsening Slightly
			        _Value <= 0.01, 0,    --No Change
			        _Value <= 0.01, 0,    --No Change
			        _Value <= 0.09, 350,  -- Improving Slightly
			        _Value <= 0.25, 330,  --Improving Moderately
			        _Value <= 0.60, 300,  --Improving Significantly
			        280
			    )
			-- Assigning colors to each category (Ensuring proper string formatting)
			VAR Color =
			    SWITCH(TRUE(),
			        _Value >= 0.60, "#669933", --Improving Significantly
			        _Value >= 0.26, "#91C159", --Improving Moderately
			        _Value >= 0.10, "#CBE0AF", --Improving Slightly
			        _Value >= 0.01, "#CCCCCC", --No Change
			        _Value >= -0.01, "#CCCCCC",  --No Change
			        _Value >= -0.09, "#F487A4",  --Worsening Slightly
			        _Value >= -0.24, "#F21D4B",  --WOrsening Moderately
			        _Value >= -0.60, "#AA0742",  --Worsening Significantly
			        "#66052D"
			    )
			-- Ensuring Color Variable is properly enclosed in the SVG string
			-- Arrow SVG (Using `path` for an arrow shape)
			VAR SVG =
			    "<svg width='20' height='20' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'>
			        <g transform='rotate(" & FORMAT(Angle, "0") & ",12,12)'>
			            <path d='M12 2 L22 12 L12 22 L12 16 L2 16 L2 8 L12 8 Z' fill='" & Color & "' />
			        </g>
			    </svg>"
			-- Encode as Image URL
			VAR EncodedSVG = "data:image/svg+xml;utf8," & SUBSTITUTE(SVG, "#", "%23")
			RETURN EncodedSVG
		displayFolder: heatmap_kpis
		lineageTag: a5609215-403a-4975-aace-d8ba8ce1029b
		dataCategory: ImageUrl

	measure 'meas.combined_score_concatenated' = ```
			
			
			var TrendValue = [meas.kpi_combined_score]                     // get the improvemnet compared to cy 
			var res = 
			    SWITCH(
			        TRUE(),
			        TrendValue < -0.50, "Worsening Drastically",
			        TrendValue >= -0.50 && TrendValue < -0.25, "Worsening Significantly",
			        TrendValue >= -0.25 && TrendValue < -0.10, "Worsening Moderately",
			        TrendValue >= -0.10 && TrendValue < 0.00, "Worsening Slightly",
			        TrendValue = 0.00, "No Change",
			        TrendValue > 0.00 && TrendValue <= 0.09, "Improving Slightly",
			        TrendValue > 0.09 && TrendValue <= 0.25, "Improving Moderately",
			        TrendValue > 0.25 && TrendValue <= 0.60, "Improving Significantly",
			        TrendValue > 0.60, "Improving Drastically"
			
			    )
			
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: ebd32c62-605c-42f8-8017-b9a0abb52860

	measure 'meas.combined_score_top' = ```
			
			
			var TrendValue =[meas.kpi_combined_score]    //IF([meas.kpi_combined_score]=BLANK(), "ND",[meas.kpi_combined_score])                      // get the improvemnet compared to cy 
			var _conditional_text =
			    SWITCH(
			        TRUE(),
			        TrendValue >= 0 && TrendValue <= 2, "No Change",
			        TrendValue > 2 && TrendValue <= 5, "Small Increase",
			        TrendValue > 5 && TrendValue <= 15, "Moderate Increase",
			        TrendValue > 15, "Significant Increase",
			        TrendValue < 0 && TrendValue >= -2, "No Change",
			        TrendValue < -2 && TrendValue >= -5, "Small Decrease",
			        TrendValue < -5 && TrendValue >= -15, "Moderate Decrease",
			        TrendValue < -15, "Significant Decrease"
			    )
			
			
			var _trend_format_score = FORMAT(TrendValue, "+0;-0;0")
			var res = "Combined KPIs Score: "& _conditional_text & " ( "& _trend_format_score &" )"
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: a3305cd5-6792-42be-a8a4-5aee98f30e2d

	measure 'meas.combined_score_top_w_text' = ```
			
			
			var TrendValue =[meas.kpi_combined_score]    //IF([meas.kpi_combined_score]=BLANK(), "ND",[meas.kpi_combined_score])                      // get the improvemnet compared to cy 
			var _conditional_text =
			    SWITCH(
			        TRUE(),
			        TrendValue >= 0 && TrendValue <= 2, "No Change",
			        TrendValue > 2 && TrendValue <= 5, "Small Increase",
			        TrendValue > 5 && TrendValue <= 15, "Moderate Increase",
			        TrendValue > 15, "Significant Increase",
			        TrendValue < 0 && TrendValue >= -2, "No Change",
			        TrendValue < -2 && TrendValue >= -5, "Small Decrease",
			        TrendValue < -5 && TrendValue >= -15, "Moderate Decrease",
			        TrendValue < -15, "Significant Decrease"
			    )
			
			
			var _trend_format_score = FORMAT(TrendValue, "+0;-0;0")
			var res =  _conditional_text & " ("& _trend_format_score &")"
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: 3599cd98-ae04-4ff2-9cde-33071e1b56f6

	measure 'meas.getKPI1_value_cy' = ```
			
			var max_date = [meas.context_date_max]              // get the selected max date
			var start_date_cy = DATE(
			    YEAR(EDATE(max_date, -3)),
			    MONTH(EDATE(max_date, -3))+1,
			    1            // calculate the start date (3 months prior)
			)
			
			var res  = CALCULATE(
			    [meas.getKPI1],              // get the existing measure
			    cal_end_dates[Date] >= start_date_cy && cal_end_dates[Date] <= max_date           
			)
			
			
			RETURN
			res
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: 012c93f0-46cd-4199-9581-8d3d9a87e3f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI1_value_delta' = ```
			
			
			var cy_kpi1 = [meas.getKPI1_value_cy]          // get the current year KPI1
			var sply_kpi1 = [meas.getKPI1_value_sply]          // get the previous year KPI1
			
			var res = DIVIDE(
			    (cy_kpi1 - sply_kpi1),
			    sply_kpi1                     // get the improvemnet compared to cy 
			)
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: #,0%;-#,0%;0%
		displayFolder: heatmap_trends
		lineageTag: 0e464e43-63e4-4b50-bfbc-e61c2408b93c

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.getKPI1_value_sply' = ```
			
			var max_date = [meas.context_date_max]              // get the selected max date
			var start_date_sply = DATE(
			    YEAR(EDATE(max_date, -3)),
			    MONTH(EDATE(max_date, -3))+1,
			    1            // calculate the start date (3 months prior)
			)
			
			var startdate_lastyear = DATE(YEAR(start_date_sply)- 1, MONTH(start_date_sply), DAY(start_date_sply))          //adjust the start date to last year
			var maxdate_lastyear = DATE(YEAR(max_date) - 1, MONTH(max_date), DAY(max_date))                 //  adjust the max date to the last year
			
			
			
			var res  = CALCULATE(
			    [meas.getKPI1],              // get the existing measure
			    cal_end_dates[Date] >= startdate_lastyear && cal_end_dates[Date] <= maxdate_lastyear           
			)
			
			
			RETURN
			res
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: 30d6a378-5a68-4453-97a9-084ac89d7a61

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI2_value_cy' = ```
			
			var max_date = [meas.context_date_max]              // get the selected max date
			var start_date_cy = DATE(
			    YEAR(EDATE(max_date, -3)),
			    MONTH(EDATE(max_date, -3))+1,
			    1            // calculate the start date (3 months prior)
			)
			
			var res  = CALCULATE(
			    [meas.getKPI2],              // get the existing measure
			    cal_end_dates[Date] >= start_date_cy && cal_end_dates[Date] <= max_date           
			)
			
			RETURN
			res
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: 6d4ee461-57ca-4f0c-aba6-b810ef408dc8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.getKPI2_value_delta' = ```
			
			
			var cy_kpi2 = [meas.getKPI2_value_cy]          // get the current year KPI2
			var sply_kpi2 = [meas.getKPI2_value_sply]          // get the previous year KPI2
			
			var res = DIVIDE(
			    (cy_kpi2 - sply_kpi2),
			    sply_kpi2                     // get the improvemnet compared to cy 
			)
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: #,0%;-#,0%;0%
		displayFolder: heatmap_trends
		lineageTag: 9f151747-cef7-4a0c-9701-7a0b65736d5f

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.getKPI2_value_sply' = ```
			
			
			var max_date = [meas.context_date_max]              // get the selected max date
			
			var start_date_sply = DATE(
			    YEAR(EDATE(max_date, -3)),
			    MONTH(EDATE(max_date, -3))+1,
			    1            // calculate the start date (3 months prior)
			)
			
			var startdate_lastyear = DATE(YEAR(start_date_sply)- 1, MONTH(start_date_sply), DAY(start_date_sply))          //adjust the start date to last year
			var maxdate_lastyear = DATE(YEAR(max_date) - 1, MONTH(max_date), DAY(max_date))                 //  adjust the max date to the last year
			
			var res  = CALCULATE(
			    [meas.getKPI2],              // get the existing measure
			    cal_end_dates[Date] >= startdate_lastyear && cal_end_dates[Date] <= maxdate_lastyear           
			)
			
			
			RETURN
			res
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: 09a753ec-6b78-4e46-82b0-b93fbcaaaabc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.kpi_combined_score' =
			
			description: "TODO: provide business definition for this measure."
			var _trend_value1 = [meas.getKPI1_score_delta]
			var _trend_value2 = [meas.getKPI2_score_delta]
			
			var _weight1 = [meas.heatmap_details_kpi1_weight_value]         // get the weight of kpi1
			// var _weight2 = IF([meas.heatmap_details_kpi2_weight_value]="-", 0,[meas.heatmap_details_kpi2_weight_value])         // weight of kpi2
			var _weight2 = [meas.heatmap_details_kpi2_weight_value]         // weight of kpi2
			
			
			var res = (_trend_value1*_weight1)+(_trend_value2*_weight2)         // get the trend score
			
			RETURN
			res
		formatString: 0
		displayFolder: heatmap_trends
		lineageTag: 346b19c9-4b92-4823-b341-9801f224cb33

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.kpi_combined_score_calculation' =
			
			description: "TODO: provide business definition for this measure."
			var _trend_value1 = [meas.getKPI1_score_delta]
			var _trend_value2 = [meas.getKPI2_score_delta]
			
			var _weight1 = [meas.heatmap_details_kpi1_weight_value]         // get the weight of kpi1
			// var _weight2 = IF([meas.heatmap_details_kpi2_weight_value]="-", 0,[meas.heatmap_details_kpi2_weight_value])         // weight of kpi2
			var _weight2 = [meas.heatmap_details_kpi2_weight_value]         // weight of kpi2
			
			var score = (_trend_value1*_weight1)+(_trend_value2*_weight2)         // get the trend score
			
			var res =IF(
			    _trend_value2=BLANK(),
			    " (" &  FORMAT(_trend_value1, "0") & " * " & _weight1   & ") = " & FORMAT(score,"0.00"),
			    " (" &  FORMAT(_trend_value1, "0") & " * " & _weight1 & ") + (" &  FORMAT(_trend_value2, "0")  & " * " & _weight2 & ") = " & FORMAT(score,"0")
			)
			
			
			RETURN
			res
		displayFolder: heatmap_trends
		lineageTag: 75955dc4-4369-4eee-a186-115f6a0636fb

	measure 'meas.kpi_score_combined_text' =
			
			
			
			description: "TODO: provide business definition for this measure."
			var _trend_value1 = [meas.getKPI1_score_delta]
			var _trend_value2 = [meas.getKPI2_score_delta]
			
			var _weight1 = [meas.heatmap_details_kpi1_weight_value]         // get the weight of kpi1
			var _weight2 = IF([meas.heatmap_details_kpi2_weight_value]="-", 0, [meas.heatmap_details_kpi2_weight_value])         // weight of kpi2
			
			
			var score = (_trend_value1*_weight1)+(_trend_value2*_weight2)         // get the trend score
			
			
			var res = IF(
			                score = BLANK(),
			                "ND",
			                FORMAT(score, "+0;-0;0")
			            )
			
			RETURN
			res
		displayFolder: heatmap_trends
		lineageTag: bade9fbf-e307-4f87-99de-a48021ba6da4

	measure 'meas.kpi1_score_change_text' = ```
			
			
			var TrendValue = [meas.getKPI1_score_delta]                     // get the improvemnet compared to cy 
			
			var _txt = SWITCH(
			        TRUE(),
			        TrendValue >= 0 && TrendValue <= 2, "No Change",
			        TrendValue > 2 && TrendValue <= 5, "Small Increase",
			        TrendValue > 5 && TrendValue <= 15, "Moderate Increase",
			        TrendValue > 15, "Significant Increase",
			        TrendValue < 0 && TrendValue >= -2, "No Change",
			        TrendValue < -2 && TrendValue >= -5, "Small Decrease",
			        TrendValue < -5 && TrendValue >= -15, "Moderate Decrease",
			        TrendValue < -15, "Significant Decrease"
			    )
			var res = _txt & " (" & FORMAT(TrendValue,"+0;-0;0") &")"
			
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: cd7479a8-e3b2-4925-ad74-ca0c38d8a387

	measure 'meas.kpi1_score_last_3_month' =
			
			description: "TODO: provide business definition for this measure."
			var _score = [meas.getKPI1_score_cy]
			var res = "KPI 1 Score for 3 Last Months of Period: "& _score
			RETURN
			res
		displayFolder: heatmap_trends
		lineageTag: fdea832f-7c4e-40c9-87ef-a377231c364d

	measure 'meas.kpi1_score_last_3_prior_month' =
			
			description: "TODO: provide business definition for this measure."
			var _score = [meas.getKPI1_score_sply]       // get the sply kpi score
			var res = "KPI 1 Score for 3 Months Prior to Period: "&_score
			
			RETURN
			res
		displayFolder: heatmap_trends
		lineageTag: 46cd0271-0303-4967-8e15-7ea70985805f

	measure 'meas.kpi1_value_delta_concatenated' = ```
			
			var _better = [meas.heatmap_details_kpi1_whats_better]          // get the what's better value 
			var kpi1_ref_value = [meas.trueai_kpi1_ref_value]               // get the ref value
			
			var TrendValue = [meas.getKPI1_value_delta]
			
			var res = 
			    SWITCH(
			        TRUE(),
			        -- Case 1: Higher is better
			        _better = "Higher" && TrendValue < -0.50, "Worsening Drastically",
			        _better = "Higher" && TrendValue >= -0.50 && TrendValue < -0.25, "Worsening Significantly",
			        _better = "Higher" && TrendValue >= -0.25 && TrendValue < -0.10, "Worsening Moderately",
			        _better = "Higher" && TrendValue >= -0.10 && TrendValue < 0.00, "Worsening Slightly",
			        _better = "Higher" && TrendValue = 0.00, "No Change",
			        _better = "Higher" && TrendValue > 0.00 && TrendValue <= 0.09, "Improving Slightly",
			        _better = "Higher" && TrendValue > 0.09 && TrendValue <= 0.25, "Improving Moderately",
			        _better = "Higher" && TrendValue > 0.25 && TrendValue <= 0.60, "Improving Significantly",
			        _better = "Higher" && TrendValue > 0.60, "Improving Drastically",
			        -- Case 2: Lower is better (reverse logic)
			        _better = "Lower" && TrendValue > 0.50, "Worsening Drastically",
			        _better = "Lower" && TrendValue <= 0.50 && TrendValue > 0.25, "Worsening Significantly",
			        _better = "Lower" && TrendValue <= 0.25 && TrendValue > 0.10, "Worsening Moderately",
			        _better = "Lower" && TrendValue <= 0.10 && TrendValue > 0.00, "Worsening Slightly",
			        _better = "Lower" && TrendValue = 0.00, "No Change",
			        _better = "Lower" && TrendValue < 0.00 && TrendValue >= -0.09, "Improving Slightly",
			        _better = "Lower" && TrendValue < -0.25 && TrendValue >= -0.60, "Improving Significantly",
			        _better = "Lower" && TrendValue < -0.09 && TrendValue >= -0.25, "Improving Moderately",
			        _better = "Lower" && TrendValue < -0.60, "Improving Drastically",
			        -- Case 3: Center is better (difference from reference value)
			        _better = "Center" && (TrendValue - kpi1_ref_value) > 0 && (TrendValue - kpi1_ref_value) < 0.10, "Improving Slightly",
			        _better = "Center" && (TrendValue - kpi1_ref_value) >= 0.10 && (TrendValue - kpi1_ref_value) < 0.25, "Improving Moderately",
			        _better = "Center" && (TrendValue - kpi1_ref_value) >= 0.25 && (TrendValue - kpi1_ref_value) <= 0.60, "Improving Significantly",
			        _better = "Center" && (TrendValue - kpi1_ref_value) > 0.60, "Improving Drastically",
			        _better = "Center" && (TrendValue - kpi1_ref_value) == 0, "No Change",
			        _better = "Center" && (TrendValue - kpi1_ref_value) < 0 && (TrendValue - kpi1_ref_value) > -0.10, "Worsening Slightly",
			        _better = "Center" && (TrendValue - kpi1_ref_value) <= -0.10 && (TrendValue - kpi1_ref_value) > -0.25, "Worsening Moderately",
			        _better = "Center" && (TrendValue - kpi1_ref_value) <= -0.25 && (TrendValue - kpi1_ref_value) > -0.50, "Worsening Significantly",
			        _better = "Center" && (TrendValue - kpi1_ref_value) <= -0.50, "Worsening Drastically",
			        "Unknown"
			    )
			
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: ff61e00f-77b6-4280-bfd9-61062d3b0b81

	measure 'meas.kpi1_value_delta_top' =
			
			
			description: "TODO: provide business definition for this measure."
			var _better = [meas.heatmap_details_kpi1_whats_better]          // get the what's better
			var kpi1_ref_value = [meas.trueai_kpi1_ref_value]              // get the ref value
			
			var delta = [meas.getKPI1_value_delta]
			
			var center_value = (delta - kpi1_ref_value)
			var _conditional_text = [meas.kpi1_value_delta_concatenated]            // get the concated text KPI2
			
			
			var _trend_format_score = IF(
			                                _better = "Center",
			                                FORMAT(center_value, "+0%;-0%;0%"),
			                                FORMAT(delta, "+0%;-0%;0%")
			)
			var res = "Trend: "& _conditional_text & " ( "& _trend_format_score &" )"
			RETURN
			res
		displayFolder: heatmap_trends
		lineageTag: 69b45e42-cece-488e-9f78-3305b4e09945

	measure 'meas.kpi2_score_change_text' = ```
			
			var _kpi2_def = MAX(metadata_heatmap_items[heatmap_kpi2_def_short])
			var TrendValue = [meas.getKPI2_score_delta]                     // get the improvemnet compared to cy 
			var _txt = SWITCH(
			        TRUE(),
			        TrendValue >= 0 && TrendValue <= 2, "No Change",
			        TrendValue > 2 && TrendValue <= 5, "Small Increase",
			        TrendValue > 5 && TrendValue <= 15, "Moderate Increase",
			        TrendValue > 15, "Significant Increase",
			        TrendValue < 0 && TrendValue >= -2, "No Change",
			        TrendValue < -2 && TrendValue >= -5, "Small Decrease",
			        TrendValue < -5 && TrendValue >= -15, "Moderate Decrease",
			        TrendValue < -15, "Significant Decrease"
			    )
			var res = _txt & " (" & FORMAT(TrendValue,"+0;-0;0") &")"
			
			var new_res = IF(
			    _kpi2_def=BLANK(),
			    "--",
			    res
			)
			
			RETURN
			new_res
			```
			description: "Ratio based on metadata_heatmap_items[heatmap_kpi2_def_short]. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: 116d096d-daee-464d-b7fc-e9deb322ba5b

	measure 'meas.kpi2_score_last_3_month' =
			
			description: "TODO: provide business definition for this measure."
			var _score = [meas.getKPI2_score_cy]
			var res = "KPI 2 Score for 3 Last Months of Period: "& _score
			RETURN
			res
		displayFolder: heatmap_trends
		lineageTag: 61bd716e-e0b3-4b6e-a8a8-bdec62433a99

	measure 'meas.kpi2_score_last_3_prior_month' =
			
			description: "TODO: provide business definition for this measure."
			var _score = [meas.getKPI2_score_sply]       // get the sply kpi score
			var res = "KPI 2 Score for 3 Months Prior to Period: "&_score
			
			RETURN
			res
		displayFolder: heatmap_trends
		lineageTag: d7f76b54-5b09-4a14-bc15-17fca51741bb

	measure 'meas.kpi2_value_delta_concatenated' = ```
			
			var _better = [meas.heatmap_details_kpi2_whats_better]          // get the what's better value 
			var kpi2_ref_value = [meas.trueai_kpi2_ref_value]               // get the ref value
			
			var TrendValue = [meas.getKPI2_value_delta]
			
			var res = 
			    SWITCH(
			        TRUE(),
			        -- Case 1: Higher is better
			        _better = "Higher" && TrendValue < -0.50, "Worsening Drastically",
			        _better = "Higher" && TrendValue >= -0.50 && TrendValue < -0.25, "Worsening Significantly",
			        _better = "Higher" && TrendValue >= -0.25 && TrendValue < -0.10, "Worsening Moderately",
			        _better = "Higher" && TrendValue >= -0.10 && TrendValue < 0.00, "Worsening Slightly",
			        _better = "Higher" && TrendValue = 0.00, "No Change",
			        _better = "Higher" && TrendValue > 0.00 && TrendValue <= 0.09, "Improving Slightly",
			        _better = "Higher" && TrendValue > 0.09 && TrendValue <= 0.25, "Improving Moderately",
			        _better = "Higher" && TrendValue > 0.25 && TrendValue <= 0.60, "Improving Significantly",
			        _better = "Higher" && TrendValue > 0.60, "Improving Drastically",
			        -- Case 2: Lower is better (reverse logic)
			        _better = "Lower" && TrendValue > 0.50, "Worsening Drastically",
			        _better = "Lower" && TrendValue <= 0.50 && TrendValue > 0.25, "Worsening Significantly",
			        _better = "Lower" && TrendValue <= 0.25 && TrendValue > 0.10, "Worsening Moderately",
			        _better = "Lower" && TrendValue <= 0.10 && TrendValue > 0.00, "Worsening Slightly",
			        _better = "Lower" && TrendValue = 0.00, "No Change",
			        _better = "Lower" && TrendValue < 0.00 && TrendValue >= -0.09, "Improving Slightly",
			        _better = "Lower" && TrendValue < -0.25 && TrendValue >= -0.60, "Improving Significantly",
			        _better = "Lower" && TrendValue < -0.09 && TrendValue >= -0.25, "Improving Moderately",
			        _better = "Lower" && TrendValue < -0.60, "Improving Drastically",
			        -- Case 3: Center is better (difference from reference value)
			        _better = "Center" && (TrendValue - kpi2_ref_value) > 0 && (TrendValue - kpi2_ref_value) < 0.10, "Improving Slightly",
			        _better = "Center" && (TrendValue - kpi2_ref_value) >= 0.10 && (TrendValue - kpi2_ref_value) < 0.25, "Improving Moderately",
			        _better = "Center" && (TrendValue - kpi2_ref_value) >= 0.25 && (TrendValue - kpi2_ref_value) <= 0.60, "Improving Significantly",
			        _better = "Center" && (TrendValue - kpi2_ref_value) > 0.60, "Improving Drastically",
			        _better = "Center" && (TrendValue - kpi2_ref_value) = 0, "No Change",
			        _better = "Center" && (TrendValue - kpi2_ref_value) < 0 && (TrendValue - kpi2_ref_value) > -0.10, "Worsening Slightly",
			        _better = "Center" && (TrendValue - kpi2_ref_value) <= -0.10 && (TrendValue - kpi2_ref_value) > -0.25, "Worsening Moderately",
			        _better = "Center" && (TrendValue - kpi2_ref_value) <= -0.25 && (TrendValue - kpi2_ref_value) > -0.50, "Worsening Significantly",
			        _better = "Center" && (TrendValue - kpi2_ref_value) <= -0.50, "Worsening Drastically",
			        "Unknown"
			    )
			
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: heatmap_trends
		lineageTag: b34434a0-aacf-41e9-aed9-3cc19f02356a

	measure 'meas.kpi2_value_delta_top' =
			
			description: "TODO: provide business definition for this measure."
			var _better = [meas.heatmap_details_kpi2_whats_better]          // get the what's better
			var kpi2_ref_value = [meas.trueai_kpi2_ref_value]              // get the ref value
			
			var delta = [meas.getKPI2_value_delta]
			
			var center_value = (delta - kpi2_ref_value)
			var _conditional_text = [meas.kpi2_value_delta_concatenated]            // get the concated text KPI2
			
			
			var _trend_format_score = IF(
			                                _better = "Center",
			                                FORMAT(center_value, "+0%;-0%;0%"),
			                                FORMAT(delta, "+0%;-0%;0%")
			)
			var res = "Trend: "& _conditional_text & " ( "& _trend_format_score &" )"
			RETURN
			res
		displayFolder: heatmap_trends
		lineageTag: 25995e7c-3f62-4905-9909-8c53d7baacc8

	measure 'meas.calc_hyp1_kpi1_denominator_count' =
			
			description: "TODO: provide business definition for this measure."
			VAR _total_acct_count = CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_name]="Prospecting"
			)
			
			var res = COUNTROWS(_total_acct_count)
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: c69313b3-0a69-4109-92c5-cc353d4c8e25

	measure 'meas.calc_hyp1_kpi2_denominator_count' = ```
			
			var filtered_tbl = CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_name] = "Prospecting"
			) 
			VAR _low_time_count = CALCULATE(
			    COUNTROWS(filtered_tbl),
			    quality_buckets[bucket] in {"Lowest", "Low"}     // get the time spent for Lowest  and Low bucket 
			    )
			
			RETURN
			_low_time_count
			```
			description: "Ratio of ssr_history[step_name] to quality_buckets[bucket]. Respects the current filter context."
		displayFolder: _record_counts
		lineageTag: eb15004c-8fa6-49ca-9ed4-6a4d6a40eda3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp10_kpi1_denominator_count' = ```
			
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			var previous_year = current_year-1                                      // get the previous year
			
			var filter_tbl = CALCULATETABLE(
			    ssr_history,
			    YEAR(cal_end_dates[Date])=previous_year,                 
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Renewal"
			)
			var res = COUNTROWS(filter_tbl)
			RETURN
			res
			```
			description: "Ratio of cal_end_dates[Date] to ssr_history[step_name]. Respects the current filter context."
		formatString: 0
		displayFolder: _record_counts
		lineageTag: f48894f2-6c56-46ab-b50a-ff8d093003ef

	measure 'meas.calc_hyp10_kpi2_nominator_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var rep_tbl =  CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Renewal"
			)
			
			var res = COUNTROWS(rep_tbl)
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: f3c7712c-d6c4-46e8-86b7-6a4d2f390849

	measure 'meas.calc_hyp11_kpi1_nominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var filter_tbl = CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_name] = "New Logo Selling"
			)
			
			var res = COUNTROWS(filter_tbl)
			
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 69b076b7-815e-4ad9-873a-3acccc17bfad

	measure 'meas.calc_hyp11_kpi2_nominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var rep_tbl = CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_name] in { "New Logo Selling" , "Prospecting"}
			)
			var res = COUNTROWS(rep_tbl)
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 691af78d-4c5a-4343-8669-55e06c78d81e

	measure 'meas.calc_hyp12_kpi1_denominator_count' = ```
			
			CALCULATE(
			    DISTINCTCOUNT(ssr_history[_sys_doc_id]),
			    ssr_history[step_name]="Post-Sales Support"
			)
			
			```
			description: "Distinct count of ssr_history[_sys_doc_id]. Respects the current filter context."
		formatString: 0
		displayFolder: _record_counts
		lineageTag: b7954f1d-5555-478b-85fa-3b2e7a876227

	measure 'meas.calc_hyp12_kpi2_denominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var _min_date =  MAX(date(2000,01,01) ,  min(ssr[_sys_filt_start_date]))            // get the coid min date
			var _max_date = [meas.context_date_max]             //. get the context max date
			
			var rept_tbl = CALCULATETABLE(
			     ssr,
			    KEEPFILTERS(ssr[trueai_first_purchase] >= _min_date  && ssr[trueai_first_purchase] < DATE(YEAR(_max_date)+1,1,1)),
			    // KEEPFILTERS(ssr[trueai_churned_on]=BLANK() || ssr[trueai_churned_on] >= DATE(YEAR(_max_date)+1,01,01)),     // count of attempted cross sale filtered by the not inculding the churn and first purchase as per discussed logic
			    ALL(cal_end_dates)
			)
			var res = CALCULATE(
			    COUNTROWS(rept_tbl)
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 62c2ba1a-dfde-4ae3-be11-43a80a44a57d

	measure 'meas.calc_hyp13_kpi1_nominator_count' = ```
			
			var period_start = [meas.context_date_min]
			var period_end = [meas.context_date_max]
			var period_in_months =  DATEDIFF(period_start, period_end + 1, month) * -1
			var prev_period_start = EDATE(period_start,period_in_months)
			var prev_period_end =   EDATE(period_end,period_in_months)
			
			 var overridden_dates_tbl =  CALCULATETABLE(ssr , cal_end_dates[Date] >=  date(1900,1,1) &&  cal_end_dates[Date] < date(2100,1,1)) -- get current filter context except all dates
			
			// get the tables - break out of filter context (AKK) and override based on first purch and churn
			var starting_custs =  Filter((overridden_dates_tbl), ssr[trueai_first_purchase] <= period_start && ssr[trueai_churned_on]  >= period_start)  // client before start of period,  churn after period started
			var ending_custs =  Filter((overridden_dates_tbl), ssr[trueai_first_purchase] <= period_end && ssr[trueai_churned_on]  >= period_end)  // // client before end of period, churn after  period ended
			
			var new_cnt = CALCULATE(
			    COUNTROWS( EXCEPT(ending_custs,starting_custs )),
			    ssr_history[step_name]="New Logo Selling"
			)
			
			var res = new_cnt 
			return IF(isblank(res), 0, res)
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		formatString: 0
		displayFolder: _record_counts
		lineageTag: f042f1a8-38b9-41de-8ce5-49c58f482621

	measure 'meas.calc_hyp13_kpi2_nominator_count' = ```
			
			// get the period dates based on current filter contetxt 
			var period_start = [meas.context_date_min]
			var period_end = [meas.context_date_max]
			var period_in_months =  DATEDIFF(period_start, period_end + 1, month) * -1
			var prev_period_start = EDATE(period_start,period_in_months)
			var prev_period_end =   EDATE(period_end,period_in_months)
			
			 var overridden_dates_tbl =  CALCULATETABLE(ssr , cal_end_dates[Date] >=  date(1900,1,1) &&  cal_end_dates[Date] < date(2100,1,1)) -- get current filter context except all dates
			
			// get the tables - break out of filter context (AKK) and override based on first purch and churn
			var starting_custs =  Filter((overridden_dates_tbl), ssr[trueai_first_purchase] <= period_start && ssr[trueai_churned_on]  >= period_start)  // client before start of period,  churn after period started
			var retained_custs = Filter((overridden_dates_tbl), ssr[trueai_first_purchase] <= period_start && ssr[trueai_churned_on]  >= period_end)  // client before start of period,  churn after period end
			var churned_custs = Filter((overridden_dates_tbl), ssr[trueai_churned_on] >= period_start && ssr[trueai_churned_on] <= period_end)  // churned after period started, before period ended
			var ending_custs =  Filter((overridden_dates_tbl), ssr[trueai_first_purchase] <= period_end && ssr[trueai_churned_on]  >= period_end)  // // client before end of period, churn after  period ended
			
			// get the values based on temp tables
			var starting_cnt = COUNTROWS(starting_custs)
			var starting_amt = CALCULATE(SUM(ssr_history[opp_won_amt]),  cal_end_dates[date] >= prev_period_start &&  cal_end_dates[date] <= prev_period_end ,starting_custs) // look at last years rev for these 
			var retained_cnt = COUNTROWS(retained_custs)
			var retained_amt = CALCULATE(SUM(ssr_history[opp_won_amt]),  cal_end_dates[date] >= prev_period_start &&  cal_end_dates[date] <= prev_period_end ,EXCEPT(starting_custs, churned_custs)) // look at last years rev for these 
			var new_cnt = COUNTROWS( EXCEPT(ending_custs,starting_custs ))
			
			
			// assign the res
			var res = new_cnt 
			return IF(isblank(res), 0, res)
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		formatString: #,0
		displayFolder: _record_counts
		lineageTag: cfd519b5-6ede-4292-9f46-44b95f4b4ab6

	measure 'meas.calc_hyp14_kpi1_nominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var res = CALCULATE(
			    DISTINCTCOUNT(users_history[_sys_user_id]),     // get the distinct rep
			    users_history[trueai_user_role_function] in {"AE", "AM", "SDR"} &&
			    users_history[ci_time_alloc_tot]>0
			)
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 89e9a30e-5645-434f-8501-5cf5fc4fa908

	measure 'meas.calc_hyp15_kpi1_denominator_count' = ```
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(
			    users_history, 
			    LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]),  // get only the last entry in each filter context period (e.g. a year)
			    users_history[trueai_user_role_function] in {"AE", "AM"}
			)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <=  toDate   && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			
			var res = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, [_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			return 
			res 
			```
			description: "Ratio of users_history[_sys_filt_start_date] to users_history[_sys_filt_start_date]. Respects the current filter context."
		displayFolder: _record_counts
		lineageTag: 32e5c37f-044e-460b-9d78-cb0e235699e5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp16_kpi1_denominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var _current = [meas.calc_hyp16_kpi1_nominator]             // get current year count
			var _sply = [meas.calc_hyp16_kpi1_denominator]              // get the sply count
			var res = _current+_sply
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: daa84179-808f-41bd-af81-9300c78f8f08

	measure 'meas.calc_hyp16_kpi2_denominator_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var _current = [meas.calc_hyp16_kpi2_nominator]         // get the current year count
			var _sply = [meas.calc_hyp16_kpi2_denominator]          // get the sply count
			var res = _current + _sply
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 55ddd544-50b7-4723-8a00-101c8c3ad282

	measure 'meas.calc_hyp17_kpi1_denominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var filter_tbl =  CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_name]="New Logo Selling",
			    SAMEPERIODLASTYEAR(cal_end_dates[Date])
			)
			
			var res = COUNTROWS(filter_tbl)
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 1c9b5f5e-906a-4d90-b6f0-b0463933370b

	measure 'meas.calc_hyp18_kpi1_nominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var filter_tbl =  CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_name]="Existing Customer Selling"
			)
			
			var res = COUNTROWS(filter_tbl)
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 55e0401e-3d03-476c-8c00-2cb04c885156

	measure 'meas.calc_hyp2_kpi1_nominator_count' = ```
			
			var contact_ai = CALCULATETABLE(
			    ssr      // get the count of ssr records
			   
			)
			
			
			var res  = COUNTROWS(contact_ai)
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: _record_counts
		lineageTag: baedc44c-944c-4ab7-8093-a224304ed2bd

	measure 'meas.calc_hyp2_kpi2_nominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var contact_ai = CALCULATETABLE(
			    completeness_summary,      // get the contact info average score for entity Leads
			    completeness_summary[entity]="Opps"
			)
			
			
			var res  = COUNTROWS(contact_ai)
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: b02bd641-139d-4276-adb8-c6c901653894

	measure 'meas.calc_hyp3_kpi1_nominator_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var _max_date = [meas.context_date_max]
			var filt_ssr = CALCULATETABLE(ssr, cal_end_dates[Date] > date(1900,1,1) && cal_end_dates[Date] < _max_date) // get rid of date context
			
			var res = CALCULATE(
			    COUNTROWS(filt_ssr),
			    ssr_history[step_outcome]  in {"Prospecting","Converted",  "Abandoned", "Ignored", "Untouched"}
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: eefe37e8-4970-4a1b-9cfa-586868f976d0

	measure 'meas.calc_hyp4_kpi1_nominator_count' = ```
			
			
			var lead_gen_tbl = CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_name] = "Lead Gen",  // all the applicable lead gen steps
			    ssr[col.trueai_leadsource_is_inbound]=True,
			    users[trueai_user_role_dept] = "MKT"
			)
			
			VAR res = COUNTROWS(lead_gen_tbl)
			return 
			res
			```
			description: "Ratio of ssr_history[step_name] to users[trueai_user_role_department]. Respects the current filter context."
		displayFolder: _record_counts
		lineageTag: bedb7fc8-0d75-4e72-9f03-563aa2c57ce4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp5_kpi1_nominator_count' = ```
			
			
			var start_date = [meas.filter_date_min]
			var end_date =[meas.filter_date_max]
			var filt_ssr = CALCULATETABLE(ssr, cal_end_dates[Date] > date(1900,1,1) && cal_end_dates[Date] < date(2100,1,1)) // get rid of date context
			
			--var filt_ssr_hist = Filter(filt_ssr, ssr[_sys_doc_id] in SELECTColumn([_sys_ssr_id], inbound_leads)
			var test_tbl = filter(filt_ssr, ssr[trueai_first_touch] >=  start_date &&  ssr[trueai_first_touch] < end_date && ssr[trueai_leadsource_is_inbound]=true && ssr[col.trueai_time_to_touch_days] <21) // get the new date range
			var touch_cnt = COuntX(test_tbl, ssr[trueai_first_touch]   )
			var res = touch_cnt
			return res
			
			```
			description: "Ratio of cal_end_dates[Date] to cal_end_dates[Date]. Respects the current filter context."
		displayFolder: _record_counts
		lineageTag: 95db4d26-6726-4bd6-bb28-3453b6e57eaa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.calc_hyp6_kpi1_denominator_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var filt_tbl = CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_outcome] = "Closed Lost",
			    ssr_history[opp_lost_stage] in {"Mid", "Late"}
			)
			
			var res = COUNTROWS(filt_tbl)
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 8f45dc84-4de4-46ce-b2c5-d9b452eef3cd

	measure 'meas.calc_hyp6_kpi2_denominator_count' = ```
			
			
			var rep_tbl = CALCULATETABLE(
			    ssr_history,                
			    ssr_history[step_name]="New Logo Selling"            // total won deals
			)
			
			
			var res = COUNTROWS(rep_tbl)
			
			RETURN
			res
			```
			description: "Ratio based on ssr_history[step_name]. Respects the current filter context."
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 1493add7-708e-480e-a481-304506a62501

	measure 'meas.calc_hyp7_kpi1_denominator_count' =
			
			description: "TODO: provide business definition for this measure."
			// CALCULATE(
			//     [meas.ssr_history_step_cycle_avg],      // step cycle avg count for Closed Won
			//     ssr_history[step_outcome] = "Closed Won" && ssr_history[step_name]="New Logo Selling"
			
			// )
			
			var filter_tbl = CALCULATETABLE(
			    ssr_history,
			    ssr_history[step_outcome] = "Closed Won" && ssr_history[step_name]="New Logo Selling"
			)
			var res = COUNTROWS(filter_tbl)
			return res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 9baaef80-3c12-4584-ab0f-9f55c21e5117

	measure 'meas.calc_hyp8_kpi1_denominator_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			var previous_year = current_year-1                                  // get the previous year
			
			var filter_tbl = CALCULATETABLE(
			    ssr_history,
			    YEAR(cal_end_dates[Date])=previous_year,                 // get the previous year initial booking amt
			    ssr_history[step_name]="New Logo Selling"
			)
			
			var res = COUNTROWS(filter_tbl)
			
			RETURN
			res
		formatString: #,0
		displayFolder: _record_counts
		lineageTag: b0794092-3393-43a9-a18c-337a39522e24

	measure 'meas.calc_hyp8_kpi2_nominator_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var rep_tbl =  CALCULATETABLE(
			    ssr_history,
			    ssr_history[opp_sale_type]="New Logo Sale"
			)
			
			var res = COUNTROWS(rep_tbl)
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 9a9eb62e-ac18-4cce-a384-90b2e1490f56

	measure 'meas.calc_hyp9_kpi1_denominator_count' =
			
			description: "TODO: provide business definition for this measure."
			var current_year = CALCULATE(YEAR([meas.context_date_max]))            // get the current year
			var previous_year = current_year-1                                      // get the previous year
			
			var filter_tbl = CALCULATETABLE(
			    ssr_history,
			    YEAR(cal_end_dates[Date])=previous_year,                 // get the current year initial booking amt
			    ssr_history[step_name]="Existing Customer Selling",
			    ssr_history[opp_sale_type]="Existing Customer Sale"
			)
			var res = COUNTROWS(filter_tbl)
			
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 394f3bb3-ea5d-4742-99e2-c704095af5d5

	measure 'meas.calc_hyp9_kpi2_nominator_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var rep_tbl =  CALCULATETABLE(
			    ssr_history,
			    ssr_history[opp_sale_type]="Existing Customer Sale"
			)
			
			var res = COUNTROWS(rep_tbl)
			RETURN
			res
		formatString: 0
		displayFolder: _record_counts
		lineageTag: cade3c66-2b12-481e-aed4-73a217bcc1fa

	measure 'meas.heatmap_combined_record_count_flag' =
			
			description: "TODO: provide business definition for this measure."
			var kpi1_flag = [meas.heatmap_kpi1_record_count_flag]           // kpi1 flag
			var kpi2_flag = [meas.heatmap_kpi2_record_count_flag]                // kpi2 flag
			
			var res = IF(
			    kpi1_flag=True && kpi2_flag=True,
			    "True",
			    IF(
			        kpi1_flag=True && kpi2_flag="-",
			        "True",
			        "False"
			    )
			)
			
			RETURN
			res
		displayFolder: _record_counts
		lineageTag: 0ac0e6d9-d2e3-4330-9efb-43a42e4c5af9

	measure 'meas.heatmap_kpi1_min_record_count' =
			
			description: "TODO: provide business definition for this measure."
			MAX(metadata_heatmap_items[col.kpi1_min_count])
		formatString: 0
		displayFolder: _record_counts
		lineageTag: 5a80b3e0-7039-4227-856d-7455ff499866

	measure 'meas.heatmap_kpi1_min_record_factor_name' =
			
			description: "TODO: provide business definition for this measure."
			MAX(metadata_heatmap_items[heatmap_kpi1_min_factor])
		displayFolder: _record_counts
		lineageTag: f83afb88-9cca-4105-b0cf-9488ea325afc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_kpi1_record_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])               // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", [meas.calc_hyp1_kpi1_denominator_count],
			    "2",[meas.calc_hyp2_kpi1_nominator_count],
			    "3", [meas.calc_hyp3_kpi1_nominator_count],
			    "4", [meas.calc_hyp4_kpi1_nominator_count],
			    "5", [meas.calc_hyp5_kpi1_nominator_count],
			    "6", [meas.calc_hyp6_kpi1_denominator_count],
			    "7", [meas.calc_hyp7_kpi1_denominator_count],
			    "8", [meas.calc_hyp8_kpi1_denominator_count],
			    "9", [meas.calc_hyp9_kpi1_denominator_count],
			    "10", [meas.calc_hyp10_kpi1_denominator_count],
			    "11", [meas.calc_hyp11_kpi1_nominator_count],
			    "12", [meas.calc_hyp12_kpi1_denominator_count],
			    "13", [meas.calc_hyp13_kpi1_nominator_count],
			    "14", [meas.calc_hyp14_kpi1_nominator_count],
			    "15", [meas.calc_hyp15_kpi1_denominator_count],
			    "16", [meas.calc_hyp16_kpi1_denominator_count],
			    "17",[meas.calc_hyp17_kpi1_denominator_count],
			    "18", [meas.calc_hyp18_kpi1_nominator_count],
			    BLANK()
			
			)
			RETURN
			COALESCE(res, 0)
		formatString: #,0;-#,0;"--"
		displayFolder: _record_counts
		lineageTag: d70ed8d0-e264-4abd-b1a3-e725f54f4a93

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.heatmap_kpi1_record_count_flag' =
			
			description: "TODO: provide business definition for this measure."
			var _min_count = [meas.heatmap_kpi1_min_record_count]           // min record count
			var _record_count = [meas.heatmap_kpi1_record_count]                // records count
			
			
			var res = SWITCH(
			    True(),
			    _record_count > _min_count,True,
			    _record_count < _min_count, False,
			    "-"
			)
			
			RETURN
			res
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: _record_counts
		lineageTag: a9f25ec6-c408-4eee-9685-4920d93e1913

	measure 'meas.heatmap_kpi2_min_record_count' = ```
			
			var _min_count = MAX(metadata_heatmap_items[col.kpi2_min_count])
			var res= 
			    IF(
			        MAX(metadata_heatmap_items[heatmap_kpi2_def_short])=BLANK(),
			        BLANK(),
			        _min_count
			    )
			
			RETURN
			COALESCE(res, 0)
			```
			description: "TODO: provide business definition for this measure."
		formatString: #,0;-#,0;"-"
		displayFolder: _record_counts
		lineageTag: 031e3150-1620-4548-900b-52381a4a963d

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.heatmap_kpi2_min_record_factor_name' =
			
			description: "TODO: provide business definition for this measure."
			MAX(metadata_heatmap_items[heatmap_kpi2_min_factor])
		displayFolder: _record_counts
		lineageTag: 275a2a40-dbe3-4c51-a8c2-70a04f2c253a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_kpi2_record_count' =
			
			
			description: "TODO: provide business definition for this measure."
			var hyp_id = MAX(metadata_heatmap_items[_sys_doc_id])               // get the current hypothesis id
			
			var res = SWITCH(
			    hyp_id,
			    "1", [meas.calc_hyp1_kpi2_denominator_count],
			    "6", [meas.calc_hyp6_kpi2_denominator_count],
			    "8", [meas.calc_hyp8_kpi2_nominator_count],
			    "9", [meas.calc_hyp9_kpi2_nominator_count],
			    "10", [meas.calc_hyp10_kpi2_nominator_count],
			    "11", [meas.calc_hyp11_kpi2_nominator_count],
			    "12", [meas.calc_hyp12_kpi2_denominator_count],
			    "13", [meas.calc_hyp13_kpi2_nominator_count],
			    "16", [meas.calc_hyp16_kpi2_denominator_count],
			    BLANK()
			
			)
			RETURN
			COALESCE(res, 0)
		formatString: #,0;-#,0;"--"
		displayFolder: _record_counts
		lineageTag: fe502b9a-70b3-478d-b620-1ac9387cdf4c

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.heatmap_kpi2_record_count_flag' =
			
			description: "TODO: provide business definition for this measure."
			var _min_count = [meas.heatmap_kpi2_min_record_count]           // min record count
			var _record_count = [meas.heatmap_kpi2_record_count]                // records count
			
			
			var res = SWITCH(
			    True(),
			    _record_count > _min_count,True,
			    _record_count < _min_count, False,
			    "-"
			)
			
			RETURN
			res
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: _record_counts
		lineageTag: fede0149-a27c-4331-9a92-a7fe220056a8

	measure 'meas.heatmap_details_ai_model_score_validation' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _score = CALCULATE(
			                        [meas.getHeatmapKPI_AIScore],      // get the heatmap AI model score validation 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_score
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 3823e4af-be2c-415b-b6f6-baee1a77173e

	measure 'meas.heatmap_details_description' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _desc = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_description]),      // get the heatmap hypothesis description 
			                       metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_desc
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_description]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 73b77dc9-f6f7-4ab0-a07f-1ef78533366c

	measure 'meas.heatmap_details_getKPI1_denominator_value' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _name = CALCULATE(
			                        [meas.getKPI1Denominator],      // get the heatmap denominator 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_name
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 2006ef4b-ae7f-4300-806a-9e7952f4efd0

	measure 'meas.heatmap_details_getKPI1_nominator_value' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _name = CALCULATE(
			                        [meas.getKPI1Nominator],      // get the heatmap name 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_name
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: f1897176-1e3a-4363-ad10-af5a021e2aa0

	measure 'meas.heatmap_details_getKPI1_Score_value' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _kpi = CALCULATE(
			                        [meas.getKPI1_score],      // get the heatmap kpi 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_kpi
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 9f841190-6ae2-4ad7-91c0-faa7833705eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_getKPI1_value' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _kpi = CALCULATE(
			                        [meas.getKPI1],      // get the heatmap kpi 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_kpi
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 8c733b05-fb2d-4291-b22b-b1356cdd8626

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_getKPI2_denominator_value' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _name = CALCULATE(
			                        [meas.getKPI2Denominator],      // get the heatmap denominator 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_name
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: dd897f1a-6017-4973-b4a5-b19880b9c3d9

	measure 'meas.heatmap_details_getKPI2_nominator_value' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _name = CALCULATE(
			                        [meas.getKPI2Nominator],      // get the heatmap name 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_name
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 7d6c585f-e2b3-44f0-88a3-4f06a5c78b5f

	measure 'meas.heatmap_details_getKPI2_Score_value' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _kpi = CALCULATE(
			                        [meas.getKPI2_score],      // get the heatmap kpi 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			COALESCE(_kpi,0)
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[_sys_doc_id]. Respects the current filter context."
		formatString: #,0;-#,0;"-"
		displayFolder: _heatmap_details
		lineageTag: 70262dee-2ff3-405e-a55e-8479ff439a3f

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.heatmap_details_getKPI2_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _kpi = CALCULATE(
			                        [meas.getKPI2],      // get the heatmap kpi 2
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_kpi
		displayFolder: _heatmap_details
		lineageTag: 41282103-ae3d-43cb-83cf-7e4d530e77a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_growth_category' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _category = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_growth_category]),      // get the growth category name 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_category
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_growth_category]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 20148111-0f79-4b3f-a97e-ad59a318d172

	measure 'meas.heatmap_details_growth_category_base64' = ```
			
			
			var _category_name = [meas.heatmap_details_growth_category]      // get the growth category name 
			
			var _img = CALCULATE(
			    MAX(heatmap_graphics[_sys_base64]),
			    heatmap_graphics[category]=_category_name
			)
			
			RETURN
			_img
			```
			description: "Ratio of heatmap_graphics[_sys_base64] to heatmap_graphics[category]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 08e61c1e-1c35-40a5-8d63-92c8e00ed769
		dataCategory: ImageUrl

	measure 'meas.heatmap_details_growth_category_hypo_name' = ```
			
			
			var _category = [meas.heatmap_details_growth_category]      // get the growth category name 
			  
			var _name = [meas.heatmap_details_name]                     // get the hypothesis name
			
			var res =  _category & " - " &  _name               // get the concatenated hypothesis name and growth category
			
			RETURN      
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 8d27fc0f-a80e-4340-99e4-43515c79268b

	measure 'meas.heatmap_details_hypothesis_confirmed' =
			
			
			description: "TODO: provide business definition for this measure."
			var _score = [meas.hypothesis_is_confirmed]         // get the is_confirmed status
			var res = IF(
			    _score="",
			    "No",       // get the No for blank
			    _score
			)
			
			RETURN
			res
		displayFolder: _heatmap_details
		lineageTag: cfd6f61e-74af-44e6-8ee1-93a6aae0c254

	measure 'meas.heatmap_details_hypothesis_id' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			
			RETURN
			h_id
		displayFolder: _heatmap_details
		lineageTag: 4ac3ede1-91e6-479a-b9d6-a50c62308f97

	measure 'meas.heatmap_details_kpi_report_location' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _screen = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi1_ref]),      // get the heatmap hypothesis kpi report location 
			                  metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_screen
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_kpi1_ref]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: ca53c191-23f0-4169-8a77-5edc54fa723c

	measure 'meas.heatmap_details_kpi_screen' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _screen = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi_screen]),      // get the heatmap hypothesis kpi screen 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_screen
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_kpi_screen]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 0459d7a1-0329-461f-a711-ab04bbf7cf15

	measure 'meas.heatmap_details_kpi1_ai_score_name' = ```
			
			var _name = MAX(metadata_heatmap_items[heatmap_kpi1_ai_score_name])
			var res = IF(
			    _name=BLANK(),
			    "--",
			    _name
			)
			
			RETURN
			res
			
			```
			description: "TODO: provide business definition for this measure."
		displayFolder: _heatmap_details
		lineageTag: a347f181-264f-470f-85f8-3bcfeb3dbc30

	measure 'meas.heatmap_details_kpi1_calculation' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _nominator = FORMAT([meas.getKPI1Nominator],"0.00")            // kpi nominator
			var _denominator = FORMAT([meas.getKPI1Denominator], "0.00")        // get the kpi denominator
			var _kpi = FORMAT([meas.getKPI1],"0.00")                           // get the KPI score
			var _nom_def = [meas.heatmap_details_kpi1_nominator_def]            // nominator def
			var _deno_def = [meas.heatmap_details_kpi1_denominator_def]         // denominator def
			
			var res = _nom_def &" " & _nominator & " divided by " & _denominator &" "& _deno_def & " = KPI1 Value "& _kpi
			
			
			RETURN
			res
		displayFolder: _heatmap_details
		lineageTag: 4296d4a9-19f5-4ec4-9f12-b6e83ef7aa0d

	measure 'meas.heatmap_details_kpi1_def_short' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _def = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi1_def_short]),      // get the heatmap kpi1 def short 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_def
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_kpi1_def_short]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 394ab51d-753b-419b-bcc5-a004a1f8ca86

	measure 'meas.heatmap_details_kpi1_denominator_def' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _def = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi1_denominator_definition]),      // get the heatmap kpi1 denominator def 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_def
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_kpi1_denominator_definition]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: fd65597b-475d-4e6e-89e8-0e460f5c2c62

	measure 'meas.heatmap_details_kpi1_long_def' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi1_def_long]),      // get the heatmap kpi1 long definition
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
		displayFolder: _heatmap_details
		lineageTag: bf773ab0-deb4-4aa9-9ce4-c47130bccaf5

	measure 'meas.heatmap_details_kpi1_max_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _max = CALCULATE(
			                        MAX(metadata_heatmap_items[col.trueai_kpi1_max]),      // get the heatmap kpi1 max value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_max
		displayFolder: _heatmap_details
		lineageTag: f0d1dc4e-d34d-4ee0-84b5-141a090e32ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi1_min_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _min = CALCULATE(
			                        MAX(metadata_heatmap_items[col.trueai_kpi1_min]),      // get the heatmap kpi1 min value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_min
		displayFolder: _heatmap_details
		lineageTag: e23a40eb-96cf-45a0-a014-8c3655371397

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi1_nominator_def' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _def = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi1_numerator_definition]),      // get the heatmap kpi1 nomination def
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_def
		displayFolder: _heatmap_details
		lineageTag: 5ac7e9b5-0b9c-4ae9-afe4-0d3229adcf48

	measure 'meas.heatmap_details_kpi1_reference_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _ref = CALCULATE(
			                        MAX(metadata_heatmap_items[col.kpi1_ref_value]),      // get the heatmap kpi1 reference value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_ref
		displayFolder: _heatmap_details
		lineageTag: bdd87e8b-8275-441c-95d3-e7b2fa1a2832

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi1_score_calculation' =
			
			
			description: "TODO: provide business definition for this measure."
			var _ref_value = [meas.trueai_kpi1_ref_value]                       // get the ref value
			var _sd_value = [meas.trueai_kpi1_sd]                               // get the SD
			var _max_value = [meas.trueai_kpi1_max]                             // max value
			var _min_value = [meas.trueai_kpi1_min]                             // min value
			
			var res = "The applicable Reference Value for this company’s Industry/Size is:  " & _ref_value &  " , based on a normal distribution, with a Standard Deviation of: "& _sd_value &", which gives a Max Value  (+2x STD.Dev) of: "&  _max_value &"  and a Min Value (-2x STD.Dev) of: "& _min_value &" ."
			
			
			RETURN
			res
		displayFolder: _heatmap_details
		lineageTag: 0ea1adc4-60b2-4b4b-b860-ad290d346b79

	measure 'meas.heatmap_details_kpi1_score_trend_calculation' =
			
			description: "TODO: provide business definition for this measure."
			var _cy = [meas.getKPI1_score_cy]           // cy kpi 1 score
			var _sply = [meas.getKPI1_score_sply]           // sply kpi 1 score
			var _trend = [meas.getKPI1_score_delta]          // change
			var res = "( "& _cy & " - " & _sply & " )  = " & FORMAT(_trend, "0")
			
			 RETURN
			 res
		displayFolder: _heatmap_details
		lineageTag: f7adf0d6-94f6-4f5d-adfc-f358d72ed96d

	measure 'meas.heatmap_details_kpi1_standard_dev_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[col.kpi1_std_value]),      // get the heatmap kpi1 sd value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
		displayFolder: _heatmap_details
		lineageTag: 097ed9a2-aec9-4845-81ee-eab6b69d6619

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi1_value_trend' =
			
			description: "TODO: provide business definition for this measure."
			var _cy = [meas.getKPI1_value_cy]                // get the current trend for kpi1
			var _sply = [meas.getKPI1_value_sply]            // get the sply trend for kpi1
			var res = (_cy - _sply)                         // get the difference
			
			RETURN
			res
		formatString: 0.00
		displayFolder: _heatmap_details
		lineageTag: 91e5d540-a947-48ea-b746-81ab3348444a

	measure 'meas.heatmap_details_kpi1_weight_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi1_weight]),      // get the heatmap kpi1 weight value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
		displayFolder: _heatmap_details
		lineageTag: 905281ee-18e5-4e36-9971-5726731b7278

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi1_whats_better' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi1_whats_better]),      // get the heatmap kpi1 what's better 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_kpi1_whats_better]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: c0e7dfa8-f958-4410-8581-26d52b5b04a9

	measure 'meas.heatmap_details_kpi2_ai_score_name' = ```
			
			var _name = MAX(metadata_heatmap_items[heatmap_kpi2_ai_score_name])
			var res = IF(
			    _name=BLANK(),
			    "--",
			    _name
			)
			
			RETURN
			res
			
			```
			description: "TODO: provide business definition for this measure."
		displayFolder: _heatmap_details
		lineageTag: 0e93d603-885b-4c37-82e1-9a5e1a01ece2

	measure 'meas.heatmap_details_kpi2_calculation' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _nominator = FORMAT([meas.getKPI2Nominator],"0.00")            // kpi nominator
			var _denominator = FORMAT([meas.getKPI2Denominator], "0.00")        // get the kpi denominator
			var _kpi = FORMAT([meas.getKPI2],"0.00")                           // get the KPI score
			var _nom_def = [meas.heatmap_details_kpi2_nominator_def]            // nominator def
			var _deno_def = [meas.heatmap_details_kpi2_denominator_def]         // denominator def
			
			var res = _nom_def &" " & _nominator & " divided by " & _denominator &" "& _deno_def & " = KPI1 Value "& _kpi
			
			
			RETURN
			res
		displayFolder: _heatmap_details
		lineageTag: bbbbf49e-84b0-405b-94a0-b9699f1f63fd

	measure 'meas.heatmap_details_kpi2_def_short' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _def = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi2_def_short]),      // get the heatmap kpi2 def short 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_def
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_kpi2_def_short]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 30d76455-b65c-4a7d-8754-de2a715441fb

	measure 'meas.heatmap_details_kpi2_denominator_def' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _def = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi2_denominator_definition]),      // get the heatmap kpi2 denominator def 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_def
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_kpi2_denominator_definition]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: c46ef1b6-8631-4ce8-903d-8055c619f9a6

	measure 'meas.heatmap_details_kpi2_long_def' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi2_def_long]),      // get the heatmap kpi2 long definition
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
		displayFolder: _heatmap_details
		lineageTag: 9977d727-1bcf-4ed6-9447-36d1652a85c9

	measure 'meas.heatmap_details_kpi2_max_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[col.trueai_kpi2_max]),      // get the heatmap kpi2 max value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
		displayFolder: _heatmap_details
		lineageTag: 65c1f74a-7972-4216-8ddd-3d54f63e8f83

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi2_min_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[col.trueai_kpi2_min]),      // get the heatmap kpi2 min value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
		displayFolder: _heatmap_details
		lineageTag: e34f49a3-ce4a-4ac8-8db4-95b3d7aa78cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi2_nominator_def' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _def = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi2_numerator_definition]),      // get the heatmap kpi1 nomination def
			                    metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_def
		displayFolder: _heatmap_details
		lineageTag: 89bee71b-48c2-43ea-a0a2-fff2f2f67a88

	measure 'meas.heatmap_details_kpi2_reference_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _ref = CALCULATE(
			                        MAX(metadata_heatmap_items[col.kpi2_ref_value]),      // get the heatmap kpi2 reference value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_ref
		displayFolder: _heatmap_details
		lineageTag: d2c09b17-eb05-43df-9835-b69ec7f1d968

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi2_score_calculation' =
			
			
			description: "TODO: provide business definition for this measure."
			var _ref_value = IF([meas.trueai_kpi2_ref_value]=BLANK(), "--", [meas.trueai_kpi2_ref_value])                       // get the ref value
			var _sd_value = IF([meas.trueai_kpi2_sd]=BLANK(), "--", [meas.trueai_kpi2_sd])                               // get the SD
			var _max_value = IF([meas.trueai_kpi2_max]=BLANK(), "--", [meas.trueai_kpi2_max])                             // max value
			var _min_value = IF([meas.trueai_kpi2_min]=BLANK(), "--", [meas.trueai_kpi2_min] )                             // min value
			
			var res = "The applicable Reference Value for this company’s Industry/Size is:  " & _ref_value &  " , based on a normal distribution, with a Standard Deviation of: "& _sd_value &", which gives a Max Value  (+2x STD.Dev) of: "&  _max_value &"  and a Min Value (-2x STD.Dev) of: "& _min_value &" ."
			
			
			RETURN
			res
		displayFolder: _heatmap_details
		lineageTag: 9619bd9d-62e7-4624-86f5-43ac566fb432

	measure 'meas.heatmap_details_kpi2_score_trend_calculation' =
			
			description: "TODO: provide business definition for this measure."
			var _cy = [meas.getKPI2_score_cy]           // cy kpi 2 score
			var _sply = [meas.getKPI2_score_sply]          // sply kpi 2 score
			var _trend =[meas.getKPI2_score_delta]          // change
			
			var res = "( "& _cy & " - " & _sply & " ) " & "  = " & FORMAT(_trend, "0")
			
			
			RETURN
			res
		displayFolder: _heatmap_details
		lineageTag: 45c1c6cc-5cc6-45d8-ad8c-78beef6aa712

	measure 'meas.heatmap_details_kpi2_standard_dev_value' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[col.kpi2_std_value]),      // get the heatmap kpi2 sd value
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
		displayFolder: _heatmap_details
		lineageTag: a5cf861b-75f9-4edc-b1bd-967b1ce6ce16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi2_value_trend' =
			
			description: "TODO: provide business definition for this measure."
			var _cy = [meas.getKPI2_value_cy]                // get the current trend for kpi2
			var _sply = [meas.getKPI2_value_sply]            // get the sply trend for kpi2
			var res = (_cy - _sply)                         // get the difference
			
			RETURN
			res
		formatString: 0.00
		displayFolder: _heatmap_details
		lineageTag: b158669c-632e-4d76-b203-4a45f2372e98

	measure 'meas.heatmap_details_kpi2_weight_value' =
			
			
			description: "TODO: provide business definition for this measure."
			var _weight = [meas.getKPI2Weight]
			var res = IF(
			    _weight=BLANK(),
			    0,
			    _weight
			)
			RETURN
			res
		displayFolder: _heatmap_details
		lineageTag: 40784f41-380e-443c-a943-aa6ef660716a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.heatmap_details_kpi2_whats_better' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _sd = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_kpi2_whats_better]),      // get the heatmap kpi2 what's better 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_sd
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_kpi2_whats_better]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 577d42bf-a950-4890-9d5f-6c89af45b21d

	measure 'meas.heatmap_details_name' = ```
			
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _name = CALCULATE(
			                        MAX(metadata_heatmap_items[heatmap_name]),      // get the heatmap name 
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_name
			```
			description: "Ratio of metadata_heatmap_items[_sys_doc_id] to metadata_heatmap_items[heatmap_name]. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 1cd40324-e502-4c67-8b92-b7fd641664d1

	measure 'meas.heatmap_details_score' =
			
			description: "TODO: provide business definition for this measure."
			var h_id = SELECTEDVALUE(metadata_heatmap_items[_sys_doc_id])            // get the selected  hypothesis id
			var _score = CALCULATE(
			                        [meas.getHeatmapScore],      // get the heatmap score
			                        metadata_heatmap_items[_sys_doc_id]=h_id
			)
			
			RETURN
			_score
		displayFolder: _heatmap_details
		lineageTag: 45751bd8-38d1-4513-abb8-7e525f8523a8

		annotation PBI_FormatHint = {"isText":true}

	measure 'meas.heatmap_details_score_new' = ```
			
			VAR _flag = [meas.heatmap_combined_record_count_flag]           // get the flag
			VAR _ai_score = [meas.getHeatmapKPI_AIScore]            // get the AI Model Score
			
			// VAR final_output = 
			//     IF(
			//         _ai_score = "Limited", 
			//         "ND",
			//         IF(
			//             _flag="False",
			//             "N/A",
			//             ROUND(MAX([meas.getHeatmapRawScore],0)/5, 0)*5
			//         )
			//     )
			
			var res = SWITCH(
			    TRUE(),
			    _ai_score = "Limited", "ND",
			    _flag="False", "N/A",
			    ROUND(MAX([meas.getHeatmapRawScore],0)/5, 0)*5
			)
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0
		displayFolder: _heatmap_details
		lineageTag: c89d5a22-85e2-47cc-baa5-1c4e10677a55

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.heatmap_details_score_w_na_nd' = ```
			
			VAR _flag = [meas.heatmap_combined_record_count_flag]           // get the flag
			VAR _ai_score = [meas.getHeatmapKPI_AIScore]            // get the AI Model Score
			VAR score = [meas.heatmap_rounded_score]                // get the rounded heatmap score
			
			VAR final_output = 
			    IF(
			        _ai_score = "Limited", 
			        BLANK(),
			        IF(
			            _flag="False",
			            BLANK(),
			            score
			        )
			    )
			
			RETURN
			final_output
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: fa1fd00c-d1dc-4959-8aab-d635d44041cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.hypothesis_is_confirmed_details' = ```
			
			VAR _score = [meas.getHeatmapScore]         // Get the heatmap score
			VAR _ai_score = [meas.getHeatmapKPI_AIScore] // AI Score
			
			VAR res = 
			        IF(
			            _ai_score = "Limited", 
			            "ND",
			            IF(
			                _ai_score IN {"Fair", "Good", "Great", "Excellent"} && _score < 45, 
			                "Yes", 
			                "No"
			            )
			        )
			
			
			RETURN res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 32d5ad33-d04f-4627-bf87-c5f1db82716e

	measure 'meas.trueai_kpi1_max' = ```
			
			var _ref = MAX(metadata_heatmap_items[col.kpi1_ref_value])         // get the ref 
			var _sd = MAX(metadata_heatmap_items[col.kpi1_std_value])                       // get the SD
			var res = (_ref + (_sd*2))            // apply the max formula
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: b1c4db19-9c6d-402b-a739-fc201eeec4f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_kpi1_min' = ```
			
			var _ref = MAX(metadata_heatmap_items[col.kpi1_ref_value])          // get the ref 
			var _sd = MAX(metadata_heatmap_items[col.kpi1_std_value])                         // get the SD
			var res = (_ref - (_sd*2))            // apply the max formula
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 83ef0179-26de-4e24-870b-8748502a2e10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_kpi1_ref_value' =
			
			description: "TODO: provide business definition for this measure."
			MAX(metadata_heatmap_items[col.kpi1_ref_value])
		displayFolder: _heatmap_details
		lineageTag: 6e3b2d46-495a-4f93-b6aa-f53730470cca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_kpi1_sd' =
			
			description: "TODO: provide business definition for this measure."
			MAX(metadata_heatmap_items[col.kpi1_std_value])
		displayFolder: _heatmap_details
		lineageTag: 9b583b49-e2fb-4d17-b47c-c0a52e5bb8c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_kpi2_max' = ```
			
			var _ref = MAX(metadata_heatmap_items[col.kpi2_ref_value])          // get the ref 
			var _sd = MAX(metadata_heatmap_items[col.kpi2_std_value])                         // get the SD
			var res = (_ref + (_sd*2))            // apply the max formula
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 1f369401-854a-4ea6-b56e-8755434db79f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_kpi2_min' = ```
			
			var _ref = MAX(metadata_heatmap_items[col.kpi2_ref_value])          // get the ref 
			var _sd = MAX(metadata_heatmap_items[col.kpi2_std_value])                         // get the SD
			var res = (_ref - (_sd*2))            // apply the max formula
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 355715ff-5fc6-4835-8eba-50cb707003ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_kpi2_ref_value' =
			
			description: "TODO: provide business definition for this measure."
			MAX(metadata_heatmap_items[col.kpi2_ref_value])
		displayFolder: _heatmap_details
		lineageTag: 967dff67-5f68-4ea4-a55b-82e8c570fd23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_kpi2_sd' =
			
			description: "TODO: provide business definition for this measure."
			MAX(metadata_heatmap_items[col.kpi2_std_value])
		displayFolder: _heatmap_details
		lineageTag: 164e05ce-6bfd-4ea3-b7fd-f5789d75d345

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.get_category_base64' =
			
			description: "TODO: provide business definition for this measure."
			var _category = [meas.get_growth_category]      // get the growth category from heatmap
			
			var res = CALCULATE(
			    MAX(heatmap_graphics[_sys_base64]),
			    heatmap_graphics[category]=_category
			)
			
			RETURN
			res
		lineageTag: e381f718-dd25-4795-8a73-57885db37678
		dataCategory: ImageUrl

	measure 'meas.get_growth_category' =
			
			description: "TODO: provide business definition for this measure."
			CALCULATE(MAX(metadata_heatmap_items[heatmap_growth_category]))
		lineageTag: 6d1d5b18-060c-4037-a92e-ca0be00f740d

	measure 'meas.heatmap_details_score_used_analysis' = ```
			
			var _score = [meas.heatmap_details_score_new]               // get the score
			var res = IF(
			    _score in { "N/A", "ND"},
			    "No", 
			    "Yes"
			)
			
			
			RETURN
			res
			```
			description: "Ratio measure. Respects the current filter context."
		displayFolder: _heatmap_details
		lineageTag: 3f964261-276e-4f11-89e2-1e15ddb0a58a

	column _sys_doc_id
		description: "System: Identifier for doc."
		dataType: string
		lineageTag: b1c1d145-d1f2-4f53-84c5-6cbf379cc931
		summarizeBy: none
		sourceColumn: _sys_doc_id
		sortByColumn: heatmap_sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_def_short
		description: "Text label for heatmap kpi1 def short."
		dataType: string
		lineageTag: 33bd3954-a70c-438f-baf0-46e36ac40a80
		summarizeBy: none
		sourceColumn: heatmap_kpi1_def_short

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_def_long
		description: "Text label for heatmap kpi1 def long."
		dataType: string
		lineageTag: 55c56a8c-14a6-4857-8803-2cfb8bafbf6e
		summarizeBy: none
		sourceColumn: heatmap_kpi1_def_long

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_def_short
		description: "Text label for heatmap kpi2 def short."
		dataType: string
		lineageTag: effa3b57-0abd-45b1-819c-f904dc7dc739
		summarizeBy: none
		sourceColumn: heatmap_kpi2_def_short

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_def_long
		description: "Text label for heatmap kpi2 def long."
		dataType: string
		lineageTag: 79c1ffc7-1c8a-46e8-b5b0-45c744bb4111
		summarizeBy: none
		sourceColumn: heatmap_kpi2_def_long

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_ref
		description: "Text label for heatmap kpi1 ref."
		dataType: string
		lineageTag: 869a4249-4260-454e-904a-7c007c5202dd
		summarizeBy: none
		sourceColumn: heatmap_kpi1_ref

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_ref
		description: "Text label for heatmap kpi2 ref."
		dataType: string
		lineageTag: 00f04268-7224-4fda-b688-761179cdfb8a
		summarizeBy: none
		sourceColumn: heatmap_kpi2_ref

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi_screen
		description: "Text label for heatmap kpi screen."
		dataType: string
		lineageTag: a1e287b9-7883-4ee5-9d5a-5722e987cbc1
		summarizeBy: none
		sourceColumn: heatmap_kpi_screen

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_whats_better
		description: "Text label for heatmap kpi1 whats better."
		dataType: string
		lineageTag: 540de604-4eae-4939-9d4f-d79fcd50fe79
		summarizeBy: none
		sourceColumn: heatmap_kpi1_whats_better

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_whats_better
		description: "Text label for heatmap kpi2 whats better."
		dataType: string
		lineageTag: a4e38b6a-888f-4b15-ada3-53e251840e25
		summarizeBy: none
		sourceColumn: heatmap_kpi2_whats_better

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_ai_score_name
		description: "Text label for heatmap kpi1 ai score name."
		dataType: string
		lineageTag: c1d7829a-d2a3-4f26-a3e0-2e8c4777ef1e
		summarizeBy: none
		sourceColumn: heatmap_kpi1_ai_score_name

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_ai_score_name
		description: "Text label for heatmap kpi2 ai score name."
		dataType: string
		lineageTag: fe44d6cd-b690-4cba-bc3f-01555c4a3a83
		summarizeBy: none
		sourceColumn: heatmap_kpi2_ai_score_name

		annotation SummarizationSetBy = Automatic

	column heatmap_sort_column
		description: "Text label for heatmap sort column."
		dataType: string
		lineageTag: 432367fa-64cd-47e6-b727-fc8cf53389e3
		summarizeBy: none
		sourceColumn: heatmap_sort_column

		annotation SummarizationSetBy = Automatic

	column heatmap_growth_category
		description: "Text label for heatmap growth category."
		dataType: string
		lineageTag: 93218fb8-47c2-4e10-a6a7-67feed1b0482
		summarizeBy: none
		sourceColumn: heatmap_growth_category

		annotation SummarizationSetBy = Automatic

	column heatmap_name
		description: "Text label for heatmap name."
		dataType: string
		lineageTag: 085cc0d7-9313-4ba9-8222-4079bdc9a8b2
		summarizeBy: none
		sourceColumn: heatmap_name

		annotation SummarizationSetBy = Automatic

	column heatmap_description
		description: "Text label for heatmap description."
		dataType: string
		lineageTag: dab4eded-524f-447e-81f8-4bf345f51b67
		summarizeBy: none
		sourceColumn: heatmap_description

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_weight
		description: "Numeric value for heatmap kpi1 weight."
		dataType: double
		lineageTag: 718a0889-6105-4192-ae42-e91bae391508
		summarizeBy: sum
		sourceColumn: heatmap_kpi1_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column heatmap_kpi1_numerator_definition
		description: "Count of heatmap kpi1 numerator definition."
		dataType: string
		lineageTag: 5b52af48-6e57-405a-85af-a094e7b6ba9d
		summarizeBy: none
		sourceColumn: heatmap_kpi1_numerator_definition

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi1_denominator_definition
		description: "Text label for heatmap kpi1 denominator definition."
		dataType: string
		lineageTag: 1f73e59b-e4f4-4687-bbd2-a5172762b3b4
		summarizeBy: none
		sourceColumn: heatmap_kpi1_denominator_definition

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_numerator_definition
		description: "Count of heatmap kpi2 numerator definition."
		dataType: string
		lineageTag: 55752c88-05b0-4682-b5bd-62c6d844a599
		summarizeBy: none
		sourceColumn: heatmap_kpi2_numerator_definition

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_denominator_definition
		description: "Text label for heatmap kpi2 denominator definition."
		dataType: string
		lineageTag: 75f27b27-44a5-42d4-a1bd-b25c7bf6ca24
		summarizeBy: none
		sourceColumn: heatmap_kpi2_denominator_definition

		annotation SummarizationSetBy = Automatic

	column heatmap_sort
		description: "Numeric value for heatmap sort."
		dataType: int64
		lineageTag: bc6ed6ee-6ff2-41c9-8f12-06fc67064117
		summarizeBy: sum
		sourceColumn: heatmap_sort

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column heatmap_kpi1_min_factor
		description: "Text label for heatmap kpi1 min factor."
		dataType: string
		lineageTag: ef920e12-fe0d-41f5-9f4b-eaf0a01ed638
		summarizeBy: none
		sourceColumn: heatmap_kpi1_min_factor

		annotation SummarizationSetBy = Automatic

	column heatmap_kpi2_min_factor
		description: "Text label for heatmap kpi2 min factor."
		dataType: string
		lineageTag: 23b2f25c-fcb3-478d-961a-3a12fcf94b25
		summarizeBy: none
		sourceColumn: heatmap_kpi2_min_factor

		annotation SummarizationSetBy = Automatic

	column prerequisites
		description: "Text label for prerequisites."
		dataType: string
		lineageTag: db8f00fa-6409-4f66-927f-e9d9c379a141
		summarizeBy: none
		sourceColumn: prerequisites

		annotation SummarizationSetBy = Automatic

	column further_research
		description: "Text label for further research."
		dataType: string
		lineageTag: 075b0426-ddbc-44e6-99a6-ae455bd3d3af
		summarizeBy: none
		sourceColumn: further_research

		annotation SummarizationSetBy = Automatic

	column transformation_ideas
		description: "Text label for transformation ideas."
		dataType: string
		lineageTag: df3cb100-5846-426c-bca1-0d0f03297838
		summarizeBy: none
		sourceColumn: transformation_ideas

		annotation SummarizationSetBy = Automatic

	column kpi1_related
		description: "Text label for kpi1 related."
		dataType: string
		lineageTag: aab12e14-6ca9-4b37-8a51-9007a2984b71
		summarizeBy: none
		sourceColumn: kpi1_related

		annotation SummarizationSetBy = Automatic

	column kpi2_related
		description: "Text label for kpi2 related."
		dataType: string
		lineageTag: d820e703-2992-414f-8f8c-3184625a517b
		summarizeBy: none
		sourceColumn: kpi2_related

		annotation SummarizationSetBy = Automatic

	column 'col.kpi1_ref_value' = ```
			description: "Amount for col kpi1 ref value."
			
			
			VAR _h_kpi1 = metadata_heatmap_items[kpi1_related]
			VAR res = 
			        MAXX(
			            FILTER(
			            metadata_reference_values,
			            metadata_reference_values[related_to_record] = _h_kpi1
			        ),
			            
			        metadata_reference_values[value]
			        )
			        
			RETURN
			    res
			
			```
		lineageTag: 4b0d35e3-ff75-4723-a76b-29fb1ae757cb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.kpi2_ref_value' = ```
			description: "Amount for col kpi2 ref value."
			
			
			VAR _h_kpi2 = metadata_heatmap_items[kpi2_related]              // current table kpi2 related id
			VAR res = 
			        MAXX(
			            FILTER(
			            metadata_reference_values,
			            metadata_reference_values[related_to_record] = _h_kpi2          // get the related ref value from the other table
			        ),
			            
			        metadata_reference_values[value]
			        )
			        
			RETURN
			    res
			
			```
		lineageTag: 5cca69b8-ad59-476c-b36d-b9793619edfd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.kpi1_std_value' = ```
			description: "Amount for col kpi1 std value."
			
			
			VAR _h_kpi1 = metadata_heatmap_items[kpi1_related]          // get the current table id
			VAR res = 
			        MAXX(
			            FILTER(
			            metadata_reference_values,
			            metadata_reference_values[related_to_record] = _h_kpi1              // filter the table with curent tbl id
			        ),
			            
			        metadata_reference_values[supporting_value_1]           // get the standard dev
			        )
			        
			RETURN
			    res
			
			```
		lineageTag: e368a914-f448-4352-8bd9-0f94bd7a3fc8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.kpi2_std_value' = ```
			description: "Amount for col kpi2 std value."
			
			
			VAR _h_kpi2 = metadata_heatmap_items[kpi2_related]          // get the current table id
			VAR res = 
			        MAXX(
			            FILTER(
			            metadata_reference_values,
			            metadata_reference_values[related_to_record] = _h_kpi2              // filter the table with curent tbl id
			        ),
			            
			        metadata_reference_values[supporting_value_1]           // get the standard dev
			        )
			        
			RETURN
			    res
			
			```
		lineageTag: 9ad71d2b-19b2-4c4e-969a-69d39ff345fe
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.kpi1_min_count' = ```
			description: "Count of col kpi1 min count."
			
			
			VAR _h_kpi1 = metadata_heatmap_items[kpi1_related]          // get the current table id
			VAR res = 
			        MAXX(
			            FILTER(
			            metadata_reference_values,
			            metadata_reference_values[related_to_record] = _h_kpi1              // filter the table with curent tbl id
			        ),
			            
			        metadata_reference_values[supporting_value_2]           // get the min count
			        )
			        
			RETURN
			    res
			
			```
		lineageTag: 8e16094e-5d2a-4548-82a1-91e1d23eb5a0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.kpi2_min_count' = ```
			description: "Count of col kpi2 min count."
			
			
			VAR _h_kpi2 = metadata_heatmap_items[kpi2_related]          // get the current table id
			VAR res = 
			        MAXX(
			            FILTER(
			            metadata_reference_values,
			            metadata_reference_values[related_to_record] = _h_kpi2              // filter the table with curent tbl id
			        ),
			            
			        metadata_reference_values[supporting_value_2]           // get the min count
			        )
			        
			RETURN
			    res
			
			```
		lineageTag: 74c2bccd-f5b4-4f50-82c0-51995dca4346
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.trueai_kpi1_max' = ```
			description: "Unclear: Value for col trueai kpi1 max."
			
			
			var _ref = [col.kpi1_ref_value]         // get the ref 
			var _sd = [col.kpi1_std_value]                       // get the SD
			var res = (_ref + (_sd*2))            // apply the max formula
			RETURN
			res
			```
		lineageTag: 3bf0cf9d-410b-4555-bb55-edc1ab2f1036
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.trueai_kpi1_min' = ```
			description: "Unclear: Value for col trueai kpi1 min."
			
			
			var _ref = [col.kpi1_ref_value]         // get the ref 
			var _sd = [col.kpi1_std_value]                       // get the SD
			var res = (_ref - (_sd*2))            // apply the max formula
			RETURN
			res
			```
		lineageTag: 1b1f3f34-2045-4b77-a98b-e69b6723dd88
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.trueai_kpi2_max' = ```
			description: "Unclear: Value for col trueai kpi2 max."
			
			
			var _ref = [col.kpi2_ref_value]         // get the ref 
			var _sd = [col.kpi2_std_value]                       // get the SD
			var res = (_ref + (_sd*2))            // apply the max formula
			RETURN
			res
			```
		lineageTag: d7b0cf95-9c53-4af4-831e-6e741d73d762
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.trueai_kpi2_min' = ```
			description: "Unclear: Value for col trueai kpi2 min."
			
			
			var _ref = [col.kpi2_ref_value]         // get the ref 
			var _sd = [col.kpi2_std_value]                       // get the SD
			var res = (_ref - (_sd*2))            // apply the max formula
			RETURN
			res
			```
		lineageTag: 4cc4e239-289a-4b8a-aa6c-cb4bf5fa8cc0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.kpi2_weight' =
			description: "Unclear: Value for col kpi2 weight."
			
			(1 - metadata_heatmap_items[heatmap_kpi1_weight])
		lineageTag: 1d160f1d-f891-46d5-972d-de255b052ceb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_is_active
		description: "System: Indicates whether is active."
		dataType: string
		lineageTag: a8ba6197-5a56-4086-81cf-d49d5a849a88
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	column _sys_modified_on
		description: "System: Date/time when modified on."
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c941bda-9f2f-4e19-ae57-872600f8bbba
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: 6f65d663-0e9f-45c9-9940-4cb987a83661
			defaultHierarchy: LocalDateTable_297e7bff-d1e4-4d4f-b1d9-3c09c0eda60a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column item_vs_all_relative_weight
		description: "Numeric value for item vs all relative weight."
		dataType: double
		lineageTag: d361a526-0159-4049-8b3c-4410a2907ecf
		summarizeBy: sum
		sourceColumn: item_vs_all_relative_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition metadata_heatmap_items = m
		mode: import
		source = ```
				let
				  
				  dbTable = getDBTable("metadata_heatmap_items"),     // get the right table
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				     {"_sys_doc_id", type text},
				{"_sys_is_active", type text},
				{"_sys_modified_on", type datetime},
				{"further_research", type text},
				{"heatmap_description", type text},
				{"heatmap_growth_category", type text},
				{"heatmap_kpi1_ai_score_name", type text},
				{"heatmap_kpi1_def_long", type text},
				{"heatmap_kpi1_def_short", type text},
				{"heatmap_kpi1_denominator_definition", type text},
				{"heatmap_kpi1_min_factor", type text},
				{"heatmap_kpi1_numerator_definition", type text},
				{"heatmap_kpi1_ref", type text},
				{"heatmap_kpi1_weight", type number},
				{"heatmap_kpi1_whats_better", type text},
				{"heatmap_kpi2_ai_score_name", type text},
				{"heatmap_kpi2_def_long", type text},
				{"heatmap_kpi2_def_short", type text},
				{"heatmap_kpi2_denominator_definition", type text},
				{"heatmap_kpi2_min_factor", type text},
				{"heatmap_kpi2_numerator_definition", type text},
				{"heatmap_kpi2_ref", type text},
				{"heatmap_kpi2_whats_better", type text},
				{"heatmap_kpi_screen", type text},
				{"heatmap_name", type text},
				{"heatmap_sort", Int64.Type},
				{"heatmap_sort_column", type text},
				{"item_vs_all_relative_weight", type number},
				{"prerequisites", type text},
				{"transformation_ideas", type text}
				
				    }),
				    kpi1Related = Table.AddColumn(dbTableTyped, "kpi1_related", each [_sys_doc_id] & "-" & "1"),
				    kpi1RelatedTyped = Table.TransformColumnTypes(kpi1Related,{{"kpi1_related", type text}}),
				    kpi2Related = Table.AddColumn(kpi1RelatedTyped, "kpi2_related", each [_sys_doc_id] & "-" & "2"),
				    kpi2RelatedTyped = Table.TransformColumnTypes(kpi2Related,{{"kpi2_related", type text}, {"heatmap_sort", Int64.Type}})
				in
				    kpi2RelatedTyped
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

