/// Table metadata_performance_metrics.
table metadata_performance_metrics
	lineageTag: e03bd1ba-d50a-4a2a-ad32-fdb814190b1a

	/// Column sys_doc_id.
	column sys_doc_id
		dataType: string
		lineageTag: 2874dadc-9eaf-4499-ab80-13980e11f9b7
		summarizeBy: none
		sourceColumn: sys_doc_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_name.
	column metric_name
		dataType: string
		lineageTag: ce50a669-43b4-419d-97be-a6a17826aebc
		summarizeBy: none
		sourceColumn: metric_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_group.
	column metric_group
		dataType: string
		lineageTag: c643d235-5b9c-4311-8a55-5c738e03638d
		summarizeBy: none
		sourceColumn: metric_group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_prefix.
	column metric_prefix
		dataType: string
		lineageTag: 55e43ef4-8c66-4d06-88ef-b1f70bbe58cd
		summarizeBy: none
		sourceColumn: metric_prefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_format.
	column metric_format
		dataType: string
		lineageTag: e844f6ba-6896-4590-ab74-d01b47eda941
		summarizeBy: none
		sourceColumn: metric_format

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column measure_ref.
	column measure_ref
		dataType: string
		lineageTag: e92896b6-d8b8-4079-bb23-25b56791d93e
		summarizeBy: none
		sourceColumn: measure_ref

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column sort_order.
	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 12d9bbda-148a-49c5-ba25-30e56e42a780
		summarizeBy: sum
		sourceColumn: sort_order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column description.
	column description
		dataType: string
		lineageTag: 20c5f49a-6f14-4562-93ca-98f3f12c554a
		summarizeBy: none
		sourceColumn: description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_sort.
	column metric_sort
		dataType: string
		lineageTag: e61e535f-a66c-4103-ac6c-b5f69e506073
		summarizeBy: none
		sourceColumn: metric_sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column _sys_is_active.
	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cf30131f-cfe2-4a69-a07e-ba26389359ab
		summarizeBy: none
		sourceColumn: _sys_is_active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column _sys_modified_on.
	column _sys_modified_on
		dataType: string
		lineageTag: 897386bf-2864-48ec-965f-4f9c8037cee4
		summarizeBy: none
		sourceColumn: _sys_modified_on

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_prio.
	column metric_prio
		dataType: string
		lineageTag: 765b1b82-e6dd-466d-8b59-29d9c09784d4
		summarizeBy: none
		sourceColumn: metric_prio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_category.
	column metric_category
		dataType: string
		lineageTag: be132760-29a8-4fe8-8d0c-c4fe1125a70f
		summarizeBy: none
		sourceColumn: metric_category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column notes.
	column notes
		dataType: string
		lineageTag: aed8b62e-e7c1-4a82-b41b-98a18d752d3d
		summarizeBy: none
		sourceColumn: notes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column peer_measure_ref.
	column peer_measure_ref
		dataType: string
		lineageTag: c3eb0a2c-3ca4-421b-9db4-bc205a55aabd
		summarizeBy: none
		sourceColumn: peer_measure_ref

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition metadata_performance_metrics = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tVvrbty4FX4VYhYBHCB2Z8a3pMD+GF+QNZo4ru1kW+wuBFqiZ7SWRIGUxvGiP/oOfcM+SQ9JiaKoC6lZFxjEzpA8Ot+ncyXpX36ZcZzMF7N3s/vbr5fwYzlfHu8vlvvzBZr/dS4+8KUY/yleb8Q0WuAEnVH6FGdrjn6mGVqlxQGM3BJeJgWH3+5wQji6IeyRshRnIdHrUpqRArMXtMVJSRB9RDTPKSvKLC5iWFNscIE2eEvQAyEZ4mUYEs4fyyR5QWFCOYkQ5uiZZgdK5EH98POSMZKFL/DrVZonJCVZAZPjDKUE8wPOWbCJeUHZSwCrA5wWMHNk6P7sQgBZfbq8+9d8DgT99k5RtXRQJcY/kyguU/ilRdM5LbPCyZOc5SSm4uI5LjYICz4QLYuQpkRwAZ8f3s09mQgrrUYHLTaWmo1DBxuHJhs3tABdYjCD1fk3JxGXvIhTLFTfy+uFbxHOshIEhDQrGA6Lxo5wkiD4IgaGWsy9A+RhUkbwGoBEYA1ltEAvpKityG08BSsJjgOtRYDDbc3YwJhF2KEm7MhB2JFJmPKZn0GPWyAC7b1562QN/heCJngtSVHvMg5BSo85MSlJAQUjiqURiWWFfG5lY62FjXkdzH+doTe/znzMLM4CBgB6rawZszg70pwdOzg77nL2Jc+5p8OpBVmZPhAmwHM5x6ILbO1JoSs2BOVxTpI4czubJDIAWW03635tYT+W2OExXpG5cbBKr25E1iOfSQH2wEcCsnAkmkOMaVMQSh8pIA5XJCieLComhOF65VAstsYVQzdXN5efrq4vm5gsSJoUk5u48kWg1MzcqVwjXc3FXSOjylBI2LCK2h3mHrB0o8z0RuFseWOGO7mVeFTDUqXIoKONzu6Su9TkTgvxNVdd3+uh8Vo73c4G55fo0nVaNOAHU17/tC45h5qcSeF8tV0fWEa3gji9F+EX/tbF1WpLmIjqTaASy/qIk1UCIykGASMhC+xMSBg0tbbB4O06ENMDiNdcpJeaP/e0Ln8qtEO2nhbeViK9x8WLNq4zAlhjyswxO8A1fDESUhYJn5WGhNWKWP7KKPiwLiGEnOIlN9PdkJEVT5sk4gEshcxfWKY1MKgIWZ3fX327uv9nE8oEIT6h7BN9NhFfwptOuJOOxtmEaSQm/oSu1wDq4cXws4LgdDJ8KXmchPaULhVLTcWkwGMAJoUouSfwkVZLRFUZlaEAiLOosRfoOGyTmcxM9YxxbuxJXXYONTuTIs9FCYE+hhT0Ey2ZmxrlOVG1SFTQaCMWvht1IyuJbdhwbDGDbv2YYCM1c413OVHRhJHttGhyDS3ANXlGZyWHyAXur5u1vevrs3Y8robQPQQFdMYIforoc2YMqOppTTLCZFnwyGiKMpAeloAiJYyrXi2jKGfAO3qon8pIIuHxTZwLBuHZ7jpKlI5Z9mCWTu2vFEu3l98ur78axZIgaVKxdC4C4/4dSZqW/xWI4SBPDOIoigV2MLacUeF6kNAYDLNtHIoYRBH5DmYg5moiBUn/kCr58SRjeyCM1aarM9JhbalZmxSMLoCDNcMRmUjaLREcCD8FAA8tBlWvJv4vGWzMKi9ZuMFcjCT0mbB9cEXWS6cg7kI+x4O1qIZgk2YPdDg71JxNClG3YCLP+M+ZGeachrG0M+ltTMgUwx0r0hsI/KB+th8vTKlps9L+usNJE6Im9bIrtdlxS0QtLNS/JVuSAdC91e2tZ4RSMuI/AIdu8ZgWyCqB0qiq7ZN+juCJfgxhxmx2mq86zBxrZk4czJyYzHyBQoX95WsWkUdZ5f4Zq5F7IRGFeCN2hh5FFRhnEHqgfs0izCLtiaIkRGECVhY/Qhcno/ZBrYxn0I46MTsaouZEU3PqoOa0RU1G9u/jdGrsaXOi8hfN9rWpQO4HwYUQXBWIDGcchw0LGRGP9eMBZAVCls2G9X2Hk1PNyXsHJ+9NTi6/56CsCKzTSFk1CephLKF1sxR8BY+sdh1JbDmT1sePLVJPt+myBzp8vdd8fXDw9aEdjOsA8RnU3kAP3hRHn71DT722G24s+qrAw8sHHrI4lyYlMpfmTAjzjT9pN/6kw/HnQ03QYt4laHFiFo/ztkVVb7xTPvpxo0rsUaOySkecNWY2XD2Cy3YqyLifKR6Ag/eUkfb3NmdARL0z247ZJ2BR+4sPQzFbFNuf6Jo2tuR1cLRK5YmIpKQjYiZbjnAca88JTwDpOoC2l86GT4HMOdb+7Ilm4NTBwOk4A3pv/42TBz0VEvgADxEJ4xQnHjSY8Eb354cmWoScakLeOwhpxWVxLKaxXBCceNpE07vr1UKUlKCogAxO1jIr91EBcTNgeaE67wYevPeoEuE5zaLhvabhg4OGVrj9QWqvQ8p5XYDVePwdpAlLf9ZB6lgT1GEoqLq2MY8ZW2RR9aGmygq8XaoGAq9maUcf6gpqc5brkzQf1irP6DLQS9fY7DZPTbBdLFw8LV7PphoHG5bg72Vdsxh2tfG5Fjn6WH6xdJHT2tYwwKJ70S/vLX78evMOLX+Efw5//HLjPmi9Jbn5DborcFF2aNFvnyREbCwGYFUxlT/qlYFo2INMHV624VXn7A9z56s3wV3EPKRbwl7Q3VMsd0nkT45+LeewGNV7f0LZc4rDjXi7V6AyeCqUIBLdwApkyUZ3IWXEJ/ngOOBiLg/COIhqKQGvNPSZI9T625lxG+Nh7nrrS7XsMluDGwuN0OohTuLi5VVJ6Yrv56UXJ9GLA6x1a6BqEzh0QD1Uy84TKveC/h84LdkTQIZqZS/CwxrhkQPhkVomwg/6jL/HafyHyiyvaN5t2RMQigAVpLBSatSgO6rRHTvQHatlP1P2hC4fITgUr4rMkDsB1TOsCkitTYPquEbl0wCIKWLb4DPOKkt/VWSW7Ano5EZDamrVIDypEboKfPX5Jhs4aJsJNLKR1uH1UA48wAbZwnCqj6k9jU8fO38kmbxZZ3w36z2VNm6cNEXoDaM8h3Qnt/izCN1QXuyrHHpXyqPqmV2VznqqJN0O21dBxKdG5mmArZsxq+3aCaw+bld9ugVzMMsPXF8Rx+KW3j59I3ys2wIeb8ReIV/LaovjBD8kZEjz9il+tS3RQ7dPdyfYi36H6s2+YuMmvXeZN4hW3xr9PmY2Pu3ZrLqxcfk9l7WbbDSq9tfPePRKPaduQGbdFqMPxeilHQOPXw9lW8dEW/qib5k0NzA8jEkeZgdxZGns1c3A56PeFPtEcMSdOnfnO21FXvtJxGwRc/Tpe60tZs76u8pyhLFYSESrUApRtlBZLQRvTkt44Xxgtq1quCHhk9r7+wjlE24ifKWVq/pVH0mDzhxjGnVmTlPHVaFWLlVR46VR3+RpSrmKytotcj+F7InTlHElK/X5uzivAx/T0dAw+EHFxhZNUTIsfIuF5jYWzouSEfC3LUnQ3ur809tmOJYK9twxGVs+XsOVnDDeBPrtWtRy8n4VSAqSbWLh8SwRgLkDVF+U8QFQM60v1xRYbuaLG3cUYWW6CMtpsjJ9BG1U9ecMSdalFxOOZ+WgmtJoCiJZSd/lQlXAUAtorXIqLnZKoaUdA+BZQ/wgd5/qu20u3Y3ZiJOREm30OpqppmeJIB98s6HizisI9dbVWIJSHA0XNZbCuVgHpp4kFq/eNYB8vHFNzkvdej7a4E7cG1LVvs5mKuub/uXD6wN2L03lZPN24wC7lkJeG4j1M+7ENZMEiS037KuXucZDvV5G5fWWBIgFGb20unLw4tBAcX3hq/v1haGxr7JZ1KuiKyMvjkzHMlpJUO7A27vMFtSPa5VWmslB3sjoBeLKk4tjk+v6nOquuvs2BU1n8a6Q9BlWHx5XnlycmC+m09NPez/d5Tu/JhAlL/HxXlSudLk4NdNN57Bjl9c1LGVXjN1DkT6orsS6MDOr2Hdi4mLLFGR60a5A4kpAr/6ujLuou3KzUjNd3QNGt2qLWyIQDOaDEW6gQjNDRRvT0pWUl/M+TLXD7wpIB4yd0Bj3HkworpS9XPS+Hu3pO7+dJlbs9nJ0gLAAOU+Pln2AOt69M7CupN0Ajp2613i3sdch4szeytZfWPvUnYlq65eK4qtTIYz3nKCa5zmeeuI5I2J/x6lZNU/8WQvrsloQXqB9ZJDax/M2DuTdrCDUDzXU9jyTU+pcQDu+JcxDcT1T9JH9jE7UPjKeXet/TlO/g+WZ3AdF/ScTulUX4uJM2bb8rt7CqfZCq78sHTrf4MaSpuW/QhHN5NzTAj1l9Bk9i8u6V4hvaJlECNqgsEya7VATmqdNfSTgMcJNwVtxhv777/+gO6XdWYNjCJzX4p0RdU+s+APU/jizoXraYaOt66V1Z77Ga0ljHvpa3D3JxKYQREl5i1TeAIXl4C84I7S+aCEuYRR6ZlrPbLnKvXKVZ6L+MFLc9q65jXCBRabjgSpUlKha49/+Bw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [sys_doc_id = _t, _sys_is_active = _t, _sys_modified_on = _t, sort_order = _t, metric_prio = _t, metric_name = _t, metric_category = _t, metric_group = _t, description = _t, metric_prefix = _t, metric_format = _t, notes = _t, measure_ref = _t, peer_measure_ref = _t, metric_sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"sys_doc_id", type text}, {"_sys_is_active", type logical}, {"_sys_modified_on", type text}, {"sort_order", Int64.Type}, {"metric_prio", type text}, {"metric_name", type text}, {"metric_category", type text}, {"metric_group", type text}, {"description", type text}, {"metric_prefix", type text}, {"metric_format", type text}, {"notes", type text}, {"measure_ref", type text}, {"peer_measure_ref", type text}, {"metric_sort", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Tot. Amt.","Total-Amount",Replacer.ReplaceText,{"metric_prefix"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Recurring Monthly Bookings (MRR)","Monthly Recurring Bookings (MRR)",Replacer.ReplaceText,{"metric_name"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Total-Amount","Tot-Amt",Replacer.ReplaceText,{"metric_prefix"})
				in
				    #"Replaced Value2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

