table metadata_performance_metrics
	lineageTag: e03bd1ba-d50a-4a2a-ad32-fdb814190b1a

	column sys_doc_id
		dataType: string
		lineageTag: 2874dadc-9eaf-4499-ab80-13980e11f9b7
		summarizeBy: none
		sourceColumn: sys_doc_id

		annotation SummarizationSetBy = Automatic

	column metric_name
		dataType: string
		lineageTag: ce50a669-43b4-419d-97be-a6a17826aebc
		summarizeBy: none
		sourceColumn: metric_name

		annotation SummarizationSetBy = Automatic

	column metric_group
		dataType: string
		lineageTag: c643d235-5b9c-4311-8a55-5c738e03638d
		summarizeBy: none
		sourceColumn: metric_group

		annotation SummarizationSetBy = Automatic

	column metric_prefix
		dataType: string
		lineageTag: 55e43ef4-8c66-4d06-88ef-b1f70bbe58cd
		summarizeBy: none
		sourceColumn: metric_prefix

		annotation SummarizationSetBy = Automatic

	column metric_format
		dataType: string
		lineageTag: e844f6ba-6896-4590-ab74-d01b47eda941
		summarizeBy: none
		sourceColumn: metric_format

		annotation SummarizationSetBy = Automatic

	column measure_ref
		dataType: string
		lineageTag: e92896b6-d8b8-4079-bb23-25b56791d93e
		summarizeBy: none
		sourceColumn: measure_ref

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 12d9bbda-148a-49c5-ba25-30e56e42a780
		summarizeBy: sum
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 20c5f49a-6f14-4562-93ca-98f3f12c554a
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column metric_sort
		dataType: string
		lineageTag: e61e535f-a66c-4103-ac6c-b5f69e506073
		summarizeBy: none
		sourceColumn: metric_sort

		annotation SummarizationSetBy = Automatic

	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cf30131f-cfe2-4a69-a07e-ba26389359ab
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	column _sys_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 897386bf-2864-48ec-965f-4f9c8037cee4
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: 45b06e23-f712-4fc4-a619-13c0faa3f374
			defaultHierarchy: LocalDateTable_ca1343be-9e50-4f99-9bb9-5a612386ee2f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column metric_prio
		dataType: string
		lineageTag: 765b1b82-e6dd-466d-8b59-29d9c09784d4
		summarizeBy: none
		sourceColumn: metric_prio

		annotation SummarizationSetBy = Automatic

	column metric_category
		dataType: string
		lineageTag: be132760-29a8-4fe8-8d0c-c4fe1125a70f
		summarizeBy: none
		sourceColumn: metric_category

		annotation SummarizationSetBy = Automatic

	column notes
		dataType: string
		lineageTag: aed8b62e-e7c1-4a82-b41b-98a18d752d3d
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	column peer_measure_ref
		dataType: string
		lineageTag: c3eb0a2c-3ca4-421b-9db4-bc205a55aabd
		summarizeBy: none
		sourceColumn: peer_measure_ref

		annotation SummarizationSetBy = Automatic

	partition metadata_performance_metrics = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1jjClrTUZRPauc3RvtMsKcaJtVV5lUKGvlWYevVqG96o/edit?gid=0#gid=0"),
				    Sheet1_Table = Source{[name="Sheet1",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Table, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sys_doc_id", type text}, {"metric_name", type text}, {"metric_group", type text}, {"metric_category", type text}, {"description", type text}, {"metric_prefix", type text}, {"metric_format", type text}, {"notes", type text}, {"measure_ref", type text}, {"_sys_is_active", type logical}, {"metric_sort", type text}, {"sort_order", Int64.Type}, {"_sys_modified_on", type datetime}, {"metric_prio", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

