table metadata_performance_metrics
	lineageTag: e03bd1ba-d50a-4a2a-ad32-fdb814190b1a

	column sys_doc_id
		dataType: string
		lineageTag: 2874dadc-9eaf-4499-ab80-13980e11f9b7
		summarizeBy: none
		sourceColumn: sys_doc_id

		annotation SummarizationSetBy = Automatic

	column metric_name
		dataType: string
		lineageTag: ce50a669-43b4-419d-97be-a6a17826aebc
		summarizeBy: none
		sourceColumn: metric_name

		annotation SummarizationSetBy = Automatic

	column metric_group
		dataType: string
		lineageTag: c643d235-5b9c-4311-8a55-5c738e03638d
		summarizeBy: none
		sourceColumn: metric_group

		annotation SummarizationSetBy = Automatic

	column metric_subgroup
		dataType: string
		lineageTag: 37f56080-992c-41b8-b831-60b06f8072b8
		summarizeBy: none
		sourceColumn: metric_subgroup

		annotation SummarizationSetBy = Automatic

	column metric_prefix
		dataType: string
		lineageTag: 55e43ef4-8c66-4d06-88ef-b1f70bbe58cd
		summarizeBy: none
		sourceColumn: metric_prefix

		annotation SummarizationSetBy = Automatic

	column metric_format
		dataType: string
		lineageTag: e844f6ba-6896-4590-ab74-d01b47eda941
		summarizeBy: none
		sourceColumn: metric_format

		annotation SummarizationSetBy = Automatic

	column metric_format_type
		dataType: string
		lineageTag: fe6f42f4-5a41-4ea6-8b96-81e2259bb2e4
		summarizeBy: none
		sourceColumn: metric_format_type

		annotation SummarizationSetBy = Automatic

	column measure_ref
		dataType: string
		lineageTag: e92896b6-d8b8-4079-bb23-25b56791d93e
		summarizeBy: none
		sourceColumn: measure_ref

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 12d9bbda-148a-49c5-ba25-30e56e42a780
		summarizeBy: sum
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 498ba713-ceec-46cc-b208-3db4cbcc4051
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 20c5f49a-6f14-4562-93ca-98f3f12c554a
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column metric_sort
		dataType: string
		lineageTag: e61e535f-a66c-4103-ac6c-b5f69e506073
		summarizeBy: none
		sourceColumn: metric_sort

		annotation SummarizationSetBy = Automatic

	partition metadata_performance_metrics = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rZX7T9swEMf/lagbEpOg65KWx49pqQQShCrlsQlQ5CVHG5HYke2Uddofv3MebjriFhhSpCT2PT65++Z8d9cRJOl96+x1rpgkiTVk7CmmM2HdMmq5qezizpQkIKwJ8EfGU0JDwLUbkuTqjtfnT3s9vI1yzoGGS3xMgYiuEDyYx0IyvgyeGQ1IKnGryORfj0vXqXs+nv7p9RDgYa9EsXF5DWLEcioNFPUeXiWEl6fA49DEEFb2djuFrSkcXJ4wCVTGWBR3dPPuMkieA4mDrA4WkHCBe047gaMJ+rh8WqJbtzG1fCLB2t35YgCpTcp4vW6vt6M+AXiIackMWisS04CXPv12nL7GGeDyZZaJ/2qHVBILWJbpRgza8w6KvFmcFcqcxBkkMYVaj/r9AiRGF2+WY1YFaNXk5GwyPj/zxitZKg67+H6glk4+zcMQhKir3gL1np4wzLHiE2WOuku2EdTWoE6TpW5IC9xbfp10lsoVVN07x0jjaBqlK3cx61rrtXNnqOWILMWXdriTHL84ZlTzWfcdZX7feQm6XjGymAXKMkBti6rIfSNoqW8SykJnbijjRSyXumx64Q1lk0/zJBIBSdSfLnWx1jXmjq7Obs6ufqw0phjsZspxSuJEfAwEqFiG4ddEsTWKs54YpBrHHwOTltEMMmriOBqn39CEdcpybmB5oZuuUs6ctwqnqfCocgzmRei+kalUDIdFoRgPpOXBszXMBYoPh4E+uXY9b6jE7cMCaA7WkAN5itgzLbzQI/6tnryheWKpOUnpz9Yh5Y9vxt51Y0YpItXYEWdC7E8hWR3lWym+F/abQUIVN8CToB6atonH1jyqsyeYbMZJBNtwLuUcuHIo3jaQRHXECsQxgTgapF/kpPBMtlalMqufNqPw0rgC6ZtAVppRx51LaY4cPoQYEUmsGmPX9X2TZLS1CuD7m7EI5xXSwIQ00EgHde2/XtMIHlHG0WtbVd836TeqSA5MJAea5FCFpLB/Fadb1eIxut+sCfopt80wDM8HiVYV0qEJ6VAjHeHG+FdGqFCDZwuTNvzneQMR1GYV0pEJ6UgjHTfVYF0wKufJsjF3Ll4noottIkq1iI5NUMedh4e/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [sys_doc_id = _t, metric_name = _t, metric_group = _t, metric_subgroup = _t, metric_prefix = _t, metric_format = _t, metric_format_type = _t, measure_ref = _t, sort_order = _t, is_active = _t, description = _t, metric_sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"sys_doc_id", type text}, {"metric_name", type text}, {"metric_group", type text}, {"metric_subgroup", type text}, {"metric_prefix", type text}, {"metric_format", type text}, {"metric_format_type", type text}, {"measure_ref", type text}, {"sort_order", Int64.Type}, {"is_active", type logical}, {"description", type text}, {"metric_sort", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

