/// Table metadata_performance_metrics.
table metadata_performance_metrics
	lineageTag: e03bd1ba-d50a-4a2a-ad32-fdb814190b1a

	/// Column sys_doc_id.
	column sys_doc_id
		dataType: string
		lineageTag: 2874dadc-9eaf-4499-ab80-13980e11f9b7
		summarizeBy: none
		sourceColumn: sys_doc_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_name.
	column metric_name
		dataType: string
		lineageTag: ce50a669-43b4-419d-97be-a6a17826aebc
		summarizeBy: none
		sourceColumn: metric_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_group.
	column metric_group
		dataType: string
		lineageTag: c643d235-5b9c-4311-8a55-5c738e03638d
		summarizeBy: none
		sourceColumn: metric_group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_prefix.
	column metric_prefix
		dataType: string
		lineageTag: 55e43ef4-8c66-4d06-88ef-b1f70bbe58cd
		summarizeBy: none
		sourceColumn: metric_prefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_format.
	column metric_format
		dataType: string
		lineageTag: e844f6ba-6896-4590-ab74-d01b47eda941
		summarizeBy: none
		sourceColumn: metric_format

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column measure_ref.
	column measure_ref
		dataType: string
		lineageTag: e92896b6-d8b8-4079-bb23-25b56791d93e
		summarizeBy: none
		sourceColumn: measure_ref

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column sort_order.
	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 12d9bbda-148a-49c5-ba25-30e56e42a780
		summarizeBy: sum
		sourceColumn: sort_order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column description.
	column description
		dataType: string
		lineageTag: 20c5f49a-6f14-4562-93ca-98f3f12c554a
		summarizeBy: none
		sourceColumn: description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_sort.
	column metric_sort
		dataType: string
		lineageTag: e61e535f-a66c-4103-ac6c-b5f69e506073
		summarizeBy: none
		sourceColumn: metric_sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column _sys_is_active.
	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cf30131f-cfe2-4a69-a07e-ba26389359ab
		summarizeBy: none
		sourceColumn: _sys_is_active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column _sys_modified_on.
	column _sys_modified_on
		dataType: string
		lineageTag: 897386bf-2864-48ec-965f-4f9c8037cee4
		summarizeBy: none
		sourceColumn: _sys_modified_on

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_prio.
	column metric_prio
		dataType: string
		lineageTag: 765b1b82-e6dd-466d-8b59-29d9c09784d4
		summarizeBy: none
		sourceColumn: metric_prio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_category.
	column metric_category
		dataType: string
		lineageTag: be132760-29a8-4fe8-8d0c-c4fe1125a70f
		summarizeBy: none
		sourceColumn: metric_category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column notes.
	column notes
		dataType: string
		lineageTag: aed8b62e-e7c1-4a82-b41b-98a18d752d3d
		summarizeBy: none
		sourceColumn: notes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column peer_measure_ref.
	column peer_measure_ref
		dataType: string
		lineageTag: c3eb0a2c-3ca4-421b-9db4-bc205a55aabd
		summarizeBy: none
		sourceColumn: peer_measure_ref

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition metadata_performance_metrics = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("vZh7b9o6FMC/SsTVpE1qWYDSx/4LD6lIhVaUdnfaqsg3OQOriR3ZDgxpH/7aBJyHC0mUbhISkc/JOf75PHzg+/cWR4HdaZ21FvOnsfyyO+1Ot921u33Ltr/sPnJVKdzi5UrpUYECa0DpKyZLbn2lxHJC0ZaSOfA4EFw+PaIAuPUA7CdlISIeqPdWYCXvqlf0+05IYyISu+2DpWHMGBBvKx8nYRRACESAb2FihYB4m3PmrjAXlG3dDSUuCpWBE6LFYKR25dyNH3/btsR9OUvAu2XgSmEKPo5D+ZCDHu73fZp6BNxjOBJYvrGkUrwCptbl558zuyKft3d1Ulhg7GrGXhljL8v4QIXcDJZhcobPTfBKYihYDAi70cGdi7z1AfGIrEDY04QXZYQXWcLb5PCsr3IrcyTA+vjhU8M4tu0fLevDj1aVeGLiMun1zXCmsgLrhWbtl7H2s6xJwd1HEf+T+SqUF5dGUT5TzeUCVX9HFeGoWgNKcxRHEGACZuPRkikIhj3eKEWzoYn2ho/1moI8AX2YPIzvJrNx2nMUa72ecx8BsTTWY+x5wPkubxuA10tZKreQAvJkC0eT+KS2eS5dfS41+9QB2Mzr2mdR4QzCZShSqqMN+W01k7qnqev1Lme9bFv5lHCWsoP5aMs/NTsEmQ7KytGMyMcVrZeuUndly+ICLXUqlKuZp5F0N+SJmn3A8QReY7HVOTCAFVpjyrKypkkgXleBz10UqGtIFEJ/RJggOsPF5Hmy+JaWv0KsVP53dJNlGIcIB/zvAILydRozr2LCdjVsvZrOIIFQg9bfIQ4Tb6eZi0omdU9T16vpUSybowK4pTFrirxr6yt2vIyz3crfe3ZXO79lchM5KVwG65qFOwNhzWBjDWIuu4S8z/Rk/XE2G+Qb2V5kLbYRWAMG6NWnG3LiIKSF8rtdTSWE/Je9zvNLCex8/DyePWUucMVa7wIfMsr5+SME6Y+mZnz/7oxVQ/SUc1fOjVAkNSQGcFcD16vikdz+kiEf3ol3tJNWgPUPjousRYGB2tOo9Up3DgQ26L0Cu7NWDZUljoug+WUDMy3Xer8iHEJiSTkHT+5MIc1hDSSWc4cznzesVmmhGjJirIibLhmofY16WYZ6mUW9F3Jfn5+IDz9lZ/LfKbI7qxWbkm/0JP8Y5KWGvCqDvMpBEjhf4PC9ClSaU9aq8VE5FQqpXaQsrBusV5r1uoz1Oss6/hUhwnHmL6dmsNpeNVw4qBd5iwID+FoD35QB3+R70qFKp5SIVbDNXK7TxuU6rVquoVmu4fFyvTnAduwUtnP55iBh58MrZxVFYIwSDYcISs6NQQK/zcpdIsNoThPF9SK1JHl5+R8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [sys_doc_id = _t, _sys_is_active = _t, _sys_modified_on = _t, sort_order = _t, metric_prio = _t, metric_name = _t, metric_category = _t, metric_group = _t, description = _t, metric_prefix = _t, metric_format = _t, notes = _t, measure_ref = _t, peer_measure_ref = _t, metric_sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"sys_doc_id", type text}, {"_sys_is_active", type logical}, {"_sys_modified_on", type text}, {"sort_order", Int64.Type}, {"metric_prio", type text}, {"metric_name", type text}, {"metric_category", type text}, {"metric_group", type text}, {"description", type text}, {"metric_prefix", type text}, {"metric_format", type text}, {"notes", type text}, {"measure_ref", type text}, {"peer_measure_ref", type text}, {"metric_sort", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Tot. Amt.","Total-Amount",Replacer.ReplaceText,{"metric_prefix"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Recurring Monthly Bookings (MRR)","Monthly Recurring Bookings (MRR)",Replacer.ReplaceText,{"metric_name"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Total-Amount","Tot-Amt",Replacer.ReplaceText,{"metric_prefix"})
				in
				    #"Replaced Value2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

