/// Table metadata_performance_metrics.
table metadata_performance_metrics
	lineageTag: e03bd1ba-d50a-4a2a-ad32-fdb814190b1a

	/// Column sys_doc_id.
	column sys_doc_id
		dataType: string
		lineageTag: 2874dadc-9eaf-4499-ab80-13980e11f9b7
		summarizeBy: none
		sourceColumn: sys_doc_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_name.
	column metric_name
		dataType: string
		lineageTag: ce50a669-43b4-419d-97be-a6a17826aebc
		summarizeBy: none
		sourceColumn: metric_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_group.
	column metric_group
		dataType: string
		lineageTag: c643d235-5b9c-4311-8a55-5c738e03638d
		summarizeBy: none
		sourceColumn: metric_group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_prefix.
	column metric_prefix
		dataType: string
		lineageTag: 55e43ef4-8c66-4d06-88ef-b1f70bbe58cd
		summarizeBy: none
		sourceColumn: metric_prefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_format.
	column metric_format
		dataType: string
		lineageTag: e844f6ba-6896-4590-ab74-d01b47eda941
		summarizeBy: none
		sourceColumn: metric_format

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column measure_ref.
	column measure_ref
		dataType: string
		lineageTag: e92896b6-d8b8-4079-bb23-25b56791d93e
		summarizeBy: none
		sourceColumn: measure_ref

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column sort_order.
	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 12d9bbda-148a-49c5-ba25-30e56e42a780
		summarizeBy: sum
		sourceColumn: sort_order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column description.
	column description
		dataType: string
		lineageTag: 20c5f49a-6f14-4562-93ca-98f3f12c554a
		summarizeBy: none
		sourceColumn: description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_sort.
	column metric_sort
		dataType: string
		lineageTag: e61e535f-a66c-4103-ac6c-b5f69e506073
		summarizeBy: none
		sourceColumn: metric_sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column _sys_is_active.
	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cf30131f-cfe2-4a69-a07e-ba26389359ab
		summarizeBy: none
		sourceColumn: _sys_is_active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column _sys_modified_on.
	column _sys_modified_on
		dataType: string
		lineageTag: 897386bf-2864-48ec-965f-4f9c8037cee4
		summarizeBy: none
		sourceColumn: _sys_modified_on

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_prio.
	column metric_prio
		dataType: string
		lineageTag: 765b1b82-e6dd-466d-8b59-29d9c09784d4
		summarizeBy: none
		sourceColumn: metric_prio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column metric_category.
	column metric_category
		dataType: string
		lineageTag: be132760-29a8-4fe8-8d0c-c4fe1125a70f
		summarizeBy: none
		sourceColumn: metric_category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column notes.
	column notes
		dataType: string
		lineageTag: aed8b62e-e7c1-4a82-b41b-98a18d752d3d
		summarizeBy: none
		sourceColumn: notes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Column peer_measure_ref.
	column peer_measure_ref
		dataType: string
		lineageTag: c3eb0a2c-3ca4-421b-9db4-bc205a55aabd
		summarizeBy: none
		sourceColumn: peer_measure_ref

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition metadata_performance_metrics = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tVttb9y4Ef4rxB4COEDs7q7fkgL3Yf2CnNHEcW0n1+LuINASvauzJAqktI4P/dD/0H/YX9IhKVEU9UJqzwUW9lokh/M8mhnOkPQvv8w4TuaL2bvZ/e3XS/i1nC+P9xfL/fkCzf86Fx94KNp/itcb0Y0WOEFnlD7F2Zqjn2mGVmlxAC23hJdJweHbHU4IRzeEPVKW4iwkelxKM1Jg9oK2OCkJoo+I5jllRZnFRQxjig0u0AZvCXogJEO8DEPC+WOZJC8oTCgnEcIcPdPsQIk8qCc/LxkjWfgCX6/SPCEpyQroHGcoJZgfcM6CTcwLyl4CGB3gtICeI033ZxcCyOrT5d2/5nMg6Ld3iqqlgyrR/plEcZnClxZN57TMCidPspeTmIqL57jYICz4QLQsQpoSwQV8fng392QirLQabbTYWGo2Dh1sHJps3NACdInBDFbn35xEXPIiTrFQfS+vB75FOMtKEBDSrGA4LBo7wkmC4EEMDLWYewfIw6SM4DUAicAaymiBXkhRW5HbeApWEhwHWosAh9uasYE2i7BDTdiRg7AjkzDlMz+DHrdABNp789bJGvwVgiZ4LUlR7zIOQUqPOTEpSQEFI4qlEYlhhZy3srHWwMa8Dua/ztCbX2c+ZhZnAQMAvVbWtFmcHWnOjh2cHXc5+5Ln3NPh1ICsTB8IE+C57GPRBbb2pNAVG4LyOCdJnLmdTRIZgKy2m3UfW9iPJXaYxisyNw5W6dWNyLrlMynAHvhIQBaORHOIMW0KQukjBcThigTFk0XFhDBcjxyKxVa7Yujm6uby09X1ZROTBUmTYnITV74IlJqZO7XWSFdzcdfIqFYoJGxYRe0Ocw9YulFmeqNwtrwxw53cSkzVsFQpMuhoo7275C41udNCfM1V1/d6aLzWTrezwfktdOk6LRrwg0tef7cuOYeanEnhfLVdH1hGt4I4vRfhF/7WxdVqS5iI6k2gEsP6iJNZAiMpBgEjIQvsTEgYNLW2weDtOhDdA4jXXCwvNX/ubl3+VGiH1XpaeFuJ5T0uXrRxnRHAGlNmttkBruGLkZCySPisNCSsRsTyK6PgwzqFEHKKl9xc7oaMrHjaJBEPYCis/IVlWgONipDV+f3Vt6v7fzahTBDiE8o+0WcT8SW86YQ76WicTZhGYuJP6HoNoB5eDD8rCE4nw5eSx0lod+lSsdRUTAo8BmBSiJR7Ah9pNURklVEZCoA4ixp7gYrDNpnJzFRzjHNjd+qyc6jZmRR5LkoI9DEsQT/RkrmpUZ4TVYNEBo02YuC7UTeyFrENG44tZtCtpwk2UjNXe5cTFU0Y2U6LJtdQAlyTZ3RWcohc4P66WNu7vj5rx+OqCd1DUEBnjOCniD5nRoPKntYkI0ymBY+MpigD6WEJKFLCuKrVMopyBryjh3pWRhIJj2/iXDAIc7vzKJE6ZtmDmTq1HymWbi+/XV5/NZIlQdKkZOlcBMb9O5I0Jf8rEMNBnmjEURQL7GBsOaPC9WBBY9DMtnEoYhBF5DuYgeiriRQk/UOq5MeTjO2BMFabrk5Lh7WlZm1SMLoADtYMR2QiabdEcCD8FAA8tBhUtZr4WzLYmFVesnCDuWhJ6DNh++CKrJdOQdyFnMeDtaiGYJNmN3Q4O9ScTQpRt2Aiz/jPmRnmnIaxtDPpbUzIFM0dK9IbCPygntuPF6bUtFlpP+5w0oSoSbXsSm123BKRCwv1b8mWZAB0b3V76xmhlIz4D8ChSzymBbJKoDSqavuknyOY0Y8hzJjNTvOow8yxZubEwcyJycwXSFTYX75mEXmUWe6fsRq5FxJRiDdiZ+hRZIFxBqEH8tcswizSnihSQhQmYGXxI1RxMmof1Mp4Bu2oE7OjIWpONDWnDmpOW9RkZP8+TqfGnjYnav2i2b42FVj7QXAhBFcJIsMZx2HDQkbEtH48gKxAyLLZsJ53ODnVnLx3cPLe5OTyew7KisA6jZRVs0A9jC1o3VUKHsGU1a4jiS1n0vr4sUXq7jZddkOHr/earw8Ovj60g3EdID6D2huowZvk6LN36KnHdsONRV8VeHj5wEMW59KkxMqlORPCfONP2o0/6XD8+VATtJh3CVqcmMnjvG1R1RvvpI9+3KgUe9SorNQRZ42ZDWeP4LKdDDLuZ4oH4OA9aaT93OYMiKh3Ztsx+wQsan/xYShmi2T7E13Txpa8Do5WqTwRkZR0RMxkyRGOY+054QlguQ6g7KWz4VMgs4+1P3uiGTh1MHA6zoDe23/j5EF3hQV8gIeIhHGKEw8aTHij+/NDHS1CTjUh7x2EtOKyOBbTWC4ITjxtoqnd9WghSkpQVMAKTtZyVe6jAuJmwPJCVd4NPHjvUSXCs5tFw3tNwwcHDa1w+4PUXoeU8zoBq/H4O0gTlv6sg9SxJqjDUFBVbWMeMzbIoupDTZUVeLtUDQRezdKOPtQV1OYs1ydpPqxVntFloJeusd5tnppgu1i4eFq8nk01DjYswd/LumYx7GrjfS1y9LH8Yukip7WtYYBF96Je3lv8+PXmHVr+CD8Of/xy4z5ovSW5+QTdFbgoK1p4AvU2U9+7Slen5w9z5ws1Vb6IeUi3hL2gu6dY7n3I3xz9Ws5hMKp39IQK5xSHG/HOruB9gP9BYiF1HhiBLNnoLqSM+CwpOA646MuDMA6iWkrAKw19+gi1/nZm3LF4mLve5VINu8zW4JxCI7R6iJO4eHlVUrri+3npxUn04ABr3Rqo2gQOHVAP1bDzhModnv8HTkv2BJChGtmL8LBGeORAeKSGiaCCPuPvcRr/odaLVzTvtuwJCEXYCVIYKTVq0B3V6I4d6I7VsJ8pe0KXjxAsildFZsidgOoZRgWk1qZBdVyj8knrRRexGfAZZ5WlvyoyS/YEdHL7IDW1ahCe1Ahdabv6fJNlGRTDBMrTSOvweigHJrBBtjCc6sNnT+PTh8kfSSbvyxnPZr1nzcY9kia1vGGU5ySUuYA4HruhvNhXK+NdKQ+gZ3auOevJfXSRa1/wEJ8amacBtu67rLZrJ7D6EF1V3xbMmZXS9Glv6iwOuy29fapB+Fh3ADzeiD1CvpbVFscJfkjIkObts/lqs6GHbp+aTbAX/Q45mX1xxk167zBvEK1qNPp9zGx8iq5ZdQ/j8rswZtBK1ARVUetnPHqk7lOXFbNu4dCHYvQqjoHHrzKyrWOiLX3Rd0eaexUexiSPqIM4sjT2qlHg81FvdX0iOOJOnbv9nbYiL/MkoreIOfpMvdYWM2f+Xa1yhLFYSESrUApRtlBZLQRvTkt44Xygt61quCHhk9rR+wjpE24ifKWVK/tVH0mDXjnGNOr0nKaOK0OtXKqixkujvs7TlHIllbVb5H4K2R2nKeNarNTn7+IUDnxMR0PD4AcVGxs0Rcmw8E0WmjtWOC9KRsDftiRBe6vzT2+b5lgq2HNzZGz4eA5XcsJ4E+i3a5HLyVtTIClItomFxzNFAOYOUH39xQdAzbS+MlNguUUv7tFRhJXpIiy7ycz0EbRR2Z8zJFlXWUw4npmDKkqjKYhkJn2XC1UBQy2gNcqpuNj/hJJ2DIBnDvGD3FOqb6y5dDd6I05GUrTRS2ammp4pgpz4ZkPFTVYQ6q2rMQSlOBpOaiyFczEOTD1JLF69cwA5vXH5zUvduj/a4E7cG1LVvqRmKuu7/MvJ62NzL01lZ/PO4gC7lkJe24L1HHfi8kiCxJYb9tXLHOOhXi+j8tJKAsSCjF5aXWvw4tBAcX3hq/v1haGxr7JZ1Kuia0VeHJmOZZSSoNyBt3eZJagf12pZaToHeSOjF4hrnVwcm1zXp0931Y22KWg6g3eFpE+m+vC41snFifliOjX9tPfTHb7zawJR8moe70XlWi4Xp+Zy0znC2OV1DUvZFWP3qKMPqmthXZgrq9h3YuK6yhRketCuQOJKQK/+rhV3UVflZqZmuroHjG7WFrdEIGjMByPcQIZmhoo2pqVrUV7O+zDVDr8rIB0wdkJj3GYwobiW7OWi9/VoT9/57TSxYreXowOEBch5erTsA9Tx7p2BdSXtBnDsLL3Gu429DhFn9la2fmDtU3c6qq1fKpKvToYwXnOCap7neGrGc0bE/o5Ts6qf+GcV1mW1ILxA+8ggtY/nbRzIG1dBqCc11PY8k1PqXEA5viXMQ3HdU9SR/YxO1D4y5q71P6ep38HyTO6Dov6TCV2qC3FxpmxbPqu3cKq90Or/RYfON7gxpCn5r1BEM9n3tEBPGX1Gz+IK7hXiG1omEYIyKCyTZjvUhOZpUx8JeIxwU/BWnKH//vs/6E5pd9bgGALnNXhnRN0TK/4AuT/ObKiedtho63pp3Z6v8VrSmIe+FndPMrEpBFFS3g2V9zphOPgLzgitr0+IqxWF7pnWPVuucq9c5Zmof3cUd7hrbiNcYLHS8UAlKkpUrfFv/wM=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [sys_doc_id = _t, _sys_is_active = _t, _sys_modified_on = _t, sort_order = _t, metric_prio = _t, metric_name = _t, metric_category = _t, metric_group = _t, description = _t, metric_prefix = _t, metric_format = _t, notes = _t, measure_ref = _t, peer_measure_ref = _t, metric_sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"sys_doc_id", type text}, {"_sys_is_active", type logical}, {"_sys_modified_on", type text}, {"sort_order", Int64.Type}, {"metric_prio", type text}, {"metric_name", type text}, {"metric_category", type text}, {"metric_group", type text}, {"description", type text}, {"metric_prefix", type text}, {"metric_format", type text}, {"notes", type text}, {"measure_ref", type text}, {"peer_measure_ref", type text}, {"metric_sort", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Tot. Amt.","Total-Amount",Replacer.ReplaceText,{"metric_prefix"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Recurring Monthly Bookings (MRR)","Monthly Recurring Bookings (MRR)",Replacer.ReplaceText,{"metric_name"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Total-Amount","Tot-Amt",Replacer.ReplaceText,{"metric_prefix"})
				in
				    #"Replaced Value2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

