/// Reference list for high-level AI score groupings (e.g., Momentum, Risk) used in reporting dashboards.
table metadata_ai_scores_analysis_categories
	lineageTag: 2a9487c6-d810-48ea-ac55-50ee75f3d4b8

	/// Measure meas.analysis_cat_weighted_avg.
	measure 'meas.analysis_cat_weighted_avg' = ```
			
			var sum_prod = SUMX(
			    metadata_ai_scores,
			    [meas.ai_score] * [meas.metadata_score_weighting_pct]
			) // get teh sum product of the weighting and the score
			var sum_weights = SUMX(
			    metadata_ai_scores,
			     [meas.metadata_score_weighting_pct]
			) // get the sum of weighting
			var res = DIVIDE( sum_prod, sum_weights)
			
			return res
			
			
			```
		description: "Purpose: Compute the measure result from the DAX expression and current filter context.\nCalculation Logic: VAR blocks define intermediate values (sum_prod, sum_weights, res) used later in the expression. Dependencies: Measures: [meas.ai_score], [meas.metadata_score_weighting_pct].\nDynamic Behavior: No explicit conditional branching detected.\nFormat/Type: 0"
		formatString: 0
		lineageTag: 9c3ab88f-1120-4e1e-8193-01bbd2fc7a88

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Unique AI score identifier
	column _sys_doc_id
		dataType: string
		lineageTag: 5742a150-e24a-4953-909b-bc950f37c3a2
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Is Active
	column _sys_is_active
		dataType: string
		lineageTag: e2eaa130-5b11-481d-b866-fbdd3c13d589
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// Modified On Date
	column _sys_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 61f0b517-3109-4e17-b7b6-49f5c75bf372
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: 479f8ce4-5a2f-482e-9aef-4f5aad9df7bf
			defaultHierarchy: LocalDateTable_848334f2-7363-498f-99e2-531cd4676b50.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Category Name
	column category_name
		dataType: string
		lineageTag: 9ec99825-cecd-48e6-a9e7-1a2b29bd08f1
		summarizeBy: none
		sourceColumn: category_name

		annotation SummarizationSetBy = Automatic

	/// Description
	column description
		dataType: string
		lineageTag: 7b6718be-dd28-460a-b722-e5c0fe4461ea
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	/// Sort Order
	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 1d85e3c5-f341-4183-b510-a8e243d4793e
		summarizeBy: sum
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	partition metadata_ai_scores_analysis_categories = m
		mode: import
		source =
				let
				    metadata_ai_scores_analysis_categories = getDBTable("metadata_ai_scores_analysis_categories"),
				    #"Changed Type" = Table.TransformColumnTypes(metadata_ai_scores_analysis_categories,{
				        {"_sys_doc_id", type text},
				        {"_sys_is_active", type text},
				        {"_sys_modified_on", type datetime},
				        {"category_name", type text},
				        {"description", type text},
				        {"sort_order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

