table metadata_aliasing
	lineageTag: 5369c9af-f905-41c3-b40f-56d9d04e79b6

	column model
		dataType: string
		lineageTag: 859c91ed-f537-48ef-8ce9-34620c79b42e
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column alias
		dataType: string
		lineageTag: e4800297-606f-4773-b4f4-c807f537ab34
		summarizeBy: none
		sourceColumn: alias

		annotation SummarizationSetBy = Automatic

	column label
		dataType: string
		lineageTag: b1cdd9a8-e717-4f0a-ab14-cf95a5a8c2fc
		summarizeBy: none
		sourceColumn: label

		annotation SummarizationSetBy = Automatic

	partition metadata_aliasing = m
		mode: import
		source =
				let
				
				
				    dbTable = getDBTable("metadata_aliasing"), // get the right table
				
				
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"model", type text}
				    })
				in
				    dbTableTyped

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

