/// Reference list mapping individual predictive scores to their broader analysis categories.
table metadata_ai_scores_category_links
	lineageTag: bfb0fc91-05e3-45e9-bdff-3b40f89bcf3f

	/// Measure meas.metadata_score_weighting_pct.
	measure 'meas.metadata_score_weighting_pct' = ```
			
			var curr_weight = CALCULATE(SUM(metadata_ai_scores_category_links[weighting]))
			var all_weights = CALCULATE(SUM(metadata_ai_scores_category_links[weighting]), metadata_ai_scores[score_name] <> "" )
			var res = DIVIDE(curr_weight, all_weights)
			return res 
			```
		formatString: 0%;-0%;0%
		lineageTag: a935c4b2-c445-4a96-9f7a-e650a735168b

	/// Unique AI score identifier
	column _sys_doc_id
		dataType: string
		lineageTag: 0ece1910-f4fb-4fe2-a605-6e0f6df1f2be
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Is Active
	column _sys_is_active
		dataType: string
		lineageTag: ac344033-67e1-44e5-809c-5b9e6026d641
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// Modified On Date
	column _sys_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 7052c511-4c34-4634-85b7-fe555e140486
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: 02348fc6-5c40-49f2-97dc-3f770860058a
			defaultHierarchy: LocalDateTable_8b551090-ebee-4d90-9b8b-ef1838732e1b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Score ID
	column score_id
		dataType: int64
		formatString: 0
		lineageTag: 8bcc2c1a-fbb2-4c61-9554-045ba36c9435
		summarizeBy: none
		sourceColumn: score_id

		annotation SummarizationSetBy = Automatic

	/// Analysis Category ID
	column analysis_category_id
		dataType: string
		lineageTag: aa076781-8c5d-4913-bcbc-79df68d39d4c
		summarizeBy: none
		sourceColumn: analysis_category_id

		annotation SummarizationSetBy = Automatic

	/// Weighting
	column weighting
		dataType: int64
		formatString: 0
		lineageTag: 907a8a0b-f71f-4401-97f2-4a9d20f9d329
		summarizeBy: sum
		sourceColumn: weighting

		annotation SummarizationSetBy = Automatic

	/// Notes
	column notes
		dataType: string
		lineageTag: 38057cfb-b926-4920-a702-03f01ed8f13e
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	partition metadata_ai_scores_category_links = m
		mode: import
		source =
				let
				    Source = getDBTable("metadata_ai_scores_category_links"),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"_sys_doc_id", type text},
				        {"_sys_is_active", type text},
				        {"_sys_modified_on", type datetime},
				        {"analysis_category_id", type text},
				        {"notes", type text},
				        {"score_id", Int64.Type},
				        {"weighting", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

