table opp_line_items
	lineageTag: 686ea3a9-2296-4d86-bcfd-80415925b6e8

	measure 'meas.opp_line_item_discount_amt' = ```
			
			var res = ([meas.opp_line_item_total_price_before_discount]-[meas.opp_line_item_total_price_after_discount])*-1  // use the existing measures and multiply by -1  
			RETURN
			res
			```
		formatString: -$#,##0;-$#,##0;$0
		displayFolder: discount opp
		lineageTag: c58a9bec-10b0-4753-95d5-905afcfe0653

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.opp_line_item_discount_pct' =
			
			
			var res = DIVIDE(([meas.opp_line_item_discount_amt]*-1), [meas.opp_line_item_total_price_before_discount]) // the diff / original. Turn discount back positive
			
			RETURN
			res
		formatString: 0%;-0%;0%
		displayFolder: discount opp
		lineageTag: dd1dba57-2410-444e-b287-68ada1efc23c

	measure 'meas.discount_line_opps' =
			
			IF([meas.opp_line_item_discount_pct] = 0, 0,BLANK())
		formatString: 0
		displayFolder: discount opp
		lineageTag: 55bd8ea0-eb11-461f-b799-99a4f1e6e0ac

	measure 'meas.opp_line_item_dis_pct' =
			
			var orig_cost = SUMX(opp_line_items, [trueai_list_price]*[trueai_qty])              // get the original cost
			var actual_cost = SUMX(opp_line_items, [trueai_unit_price]*[trueai_qty])            // get the actual cost
			var res = DIVIDE(orig_cost -actual_cost, orig_cost)             // get the pct
			RETURN res
		formatString: 0%;-0%;0%
		displayFolder: discount opp
		lineageTag: b5f83928-e12e-4884-aa64-e29f8c0e2b70

	measure 'meas.opp_line_item_total_price_after_discount' =
			
			
			var tbl = CALCULATETABLE(opp_line_items)        // get the calculatd table
			var new_price = SUMX(tbl, [trueai_unit_price] * [trueai_qty])  // calculating the new price
			RETURN
			new_price
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: discount opp
		lineageTag: 982b866e-1a68-4089-9f0b-fff63419a571

	measure 'meas.opp_lines_item_discount_pct' = ```
			
			
			var tbl = CALCULATETABLE(opp_line_items)        // get the opp line items virtual table
			var orig_cost = SUMX(tbl, [col.trueai_list_price] * [crm_qty])      // get the original cost
			var actual_cost = SUMX(tbl, [col.trueai_unit_price] * [crm_qty])        // get the actual cost
			var res = DIVIDE(actual_cost - orig_cost, orig_cost)        // get the pct 
			RETURN ABS(res)
			```
		formatString: 0%;-0%;0%
		displayFolder: discount opp
		lineageTag: 92f502aa-be60-41d1-a075-d98ed0682e74

	measure 'meas.delta_expected_booking_amt' = ```
			
			var wonAmt = [meas.ssr_history_won_amt]     // get the won amt 
			var pct = [meas.opps_delta_expected_pct]        // get the delta-expected pct
			
			var res = wonAmt * pct
			RETURN res
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: discount opp
		lineageTag: fdd8ec9f-4d49-4be5-9806-37f53f5183ba

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_average_discount_pct' =
			
			ABS(CALCULATE(AVERAGE(opps[trueai_discount_pct])))     // get the abs of avg discount pct
		displayFolder: discount opp
		lineageTag: 4521bdd7-92e5-4444-a254-49f7cccf9560

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_avg_deals_amt' =
			
			var Amt = [meas.ssr_history_won_amt] - [meas.opps_deal_discount_amt]        // get the difference amt
			var totdeals = [meas.ssr_history_step_count]            // total deals count
			var res = DIVIDE(Amt, totdeals)
			RETURN res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: discount opp
		lineageTag: 52ee46c4-60c9-4a29-b4f2-aea0ea173086

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_deal_discount_amt' = ```
			
			// var pct = ABS([meas.opps_average_discount_pct])
			// var wonAmt = [meas.ssr_history_won_amt]
			// var disAmt = wonAmt * pct
			
			var pct = ABS([meas.opp_line_item_discount_pct])        // geting the abs value of opp line items discount pct
			var wonAmt = [meas.ssr_history_won_amt]     // won amount 
			var disAmt = wonAmt * pct
			
			RETURN disAmt
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: discount opp
		lineageTag: a7e40876-f224-4016-b137-855d4e4bb99c

	measure 'meas.opps_deals_pct' =
			
			var stepCount = [meas.ssr_history_step_count]       // calculating the step count
			var disdeals = CALCULATE(count(opps[_sys_doc_id]), opps[trueai_discount_pct_tier] <> BLANK())  // gt the count of opps that has discount tier
			
			var res = DIVIDE(stepCount, disdeals)           // getb the pct
			
			RETURN res
		formatString: 0%;-0%;0%
		displayFolder: discount opp
		lineageTag: c7df8b8f-3864-41d9-94e5-b44b2836158f

	measure 'meas.opps_delta_expected_pct' =
			
			VAR SuccessRate =
			    CALCULATE(
			        [meas.ssr_history_success_rate],
			        KEEPFILTERS(opps)
			    )
			VAR ExpectedRate =
			    CALCULATE(
			        [meas.ssr_history_success_prob_avg],
			        KEEPFILTERS(opps)
			    )
			RETURN
			    SuccessRate - ExpectedRate
		formatString: 0%;-0%;0%
		displayFolder: discount opp
		lineageTag: 9d875de2-fc0a-47b4-86e6-f717b75bf26f

	measure 'meas.opps_tot_deals' =
			
			CALCULATE(COUNT(opps[_sys_doc_id]), opps[trueai_discount_pct_tier] <> BLANK()) // get the total deals count
		formatString: 0
		displayFolder: discount opp
		lineageTag: ba127637-f77b-4fbe-8646-8ee9fea3c6a3

	measure 'meas.opp_line_items_avg_discount_pct' =
			CALCULATE(
			    AVERAGE(
			        opps[trueai_discount_pct]      // get the average discount pct
			    )
			)
		displayFolder: discount opp
		lineageTag: e2d54ef3-1fa1-4cc1-9829-3af4c599ee90

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opp_line_item_total_price_before_discount' =
			
			var tbl = CALCULATETABLE(opp_line_items)        // get the calculatd table
			var orig_cost = SUMX(tbl, [trueai_list_price] * [trueai_qty])  // calculating the original price
			RETURN orig_cost
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: discount opp
		lineageTag: 568debc5-0da7-4041-92d2-ee578af4f58b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opp_line_items_trueai_list_price' =
			
			CALCULATE(
			    MAX(opp_line_items[trueai_list_price])
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: discount opp
		lineageTag: 317da6da-348b-4ea6-96ac-5b2f9dc328a9

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.avg_discount_pct_change' =
			
			VAR MinVisibleDate =
			    CALCULATE(
			        MIN('cal_end_dates'[Date]),
			        ALLSELECTED('cal_end_dates')
			    )
			VAR MaxVisibleDate =
			    CALCULATE(
			        MAX('cal_end_dates'[Date]),
			        ALLSELECTED('cal_end_dates')
			    )
			
			VAR StartValue =
			    CALCULATE(
			        [meas.opp_line_items_avg_discount_pct],
			        KEEPFILTERS('cal_end_dates'[Date] = MinVisibleDate)
			    )
			
			VAR EndValue =
			    CALCULATE(
			        [meas.opp_line_items_avg_discount_pct],
			        KEEPFILTERS('cal_end_dates'[Date] = MaxVisibleDate)
			    )
			
			RETURN
			    EndValue - StartValue
		lineageTag: 60809788-e731-4fbf-a298-65c5f0ddb9d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opp_line_items_trueai_total_price' =
			
			CALCULATE(
			    SUM ( opp_line_items[trueai_total_price] )
			)
		lineageTag: 06d38a15-526f-4563-8dc8-9d781cfd3b81

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_doc_id
		dataType: string
		lineageTag: 2343c249-79f2-4cdb-bda4-9d09f792ce18
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_ssr_id
		dataType: string
		lineageTag: 45b4092f-a962-4ca4-870c-80008d021727
		summarizeBy: none
		sourceColumn: _sys_ssr_id

		annotation SummarizationSetBy = Automatic

	column crm_currency
		dataType: string
		lineageTag: 30d46d4f-10aa-4bb0-87f5-51e87dca5509
		summarizeBy: none
		sourceColumn: crm_currency

		annotation SummarizationSetBy = Automatic

	column crm_description
		dataType: string
		lineageTag: 5c24954f-db51-48c4-bb6e-3311b911d0c4
		summarizeBy: none
		sourceColumn: crm_description

		annotation SummarizationSetBy = Automatic

	column crm_list_price
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 430885fa-3057-4803-b587-f6a95dbaabb9
		summarizeBy: sum
		sourceColumn: crm_list_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column crm_name
		dataType: string
		lineageTag: b2ba0f34-770d-42be-84e8-951ff7e57ce0
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	column crm_opp_id
		dataType: string
		lineageTag: 7e7b3852-a801-4db2-a7ca-01c57f936c0b
		summarizeBy: none
		sourceColumn: crm_opp_id

		annotation SummarizationSetBy = Automatic

	column crm_product_code
		dataType: string
		lineageTag: 7f9f9b23-3c64-49aa-86d7-c1340079f055
		summarizeBy: none
		sourceColumn: crm_product_code

		annotation SummarizationSetBy = Automatic

	column crm_product_id
		dataType: string
		lineageTag: 8726f1fb-0dd7-4b21-891e-a0286af6840e
		summarizeBy: none
		sourceColumn: crm_product_id

		annotation SummarizationSetBy = Automatic

	column crm_qty
		dataType: int64
		formatString: 0
		lineageTag: 53fbef33-de61-4576-8276-54d0b1c486ac
		summarizeBy: sum
		sourceColumn: crm_qty

		annotation SummarizationSetBy = Automatic

	column crm_total_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 41397175-6fce-498d-a3ef-6bad17a2b2f1
		summarizeBy: sum
		sourceColumn: crm_total_price

		annotation SummarizationSetBy = Automatic

	column crm_unit_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e79d467c-249c-45c9-9d65-1c4eca47488c
		summarizeBy: sum
		sourceColumn: crm_unit_price

		annotation SummarizationSetBy = Automatic

	column trueai_total_price
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 92956dc1-0e28-46d6-8804-f81350306f51
		summarizeBy: sum
		sourceColumn: trueai_total_price

		annotation SummarizationSetBy = Automatic

	column trueai_total_price_rule
		dataType: int64
		formatString: 0
		lineageTag: 7511b56b-cdd0-4419-a641-5f160b7f9abe
		summarizeBy: sum
		sourceColumn: trueai_total_price_rule

		annotation SummarizationSetBy = Automatic

	column 'col.trueai_list_price' = [crm_list_price]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b1ca80d0-9500-44bd-a852-8abf5dbdfd6f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'col.trueai_unit_price' = [crm_unit_price]
		lineageTag: b7387413-52ef-4af2-a4fd-d43d72c14f84
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.trueai_prod_category' = "Other"
		lineageTag: ef2adbd1-8667-47a4-956e-6ef1fa55f1c5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'col.trueai_unit_cogs' = 0.5 * opp_line_items[col.trueai_list_price]
		lineageTag: 27d05765-419c-4300-9dbb-a0563138c373
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_as_of
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6509b0e6-1fa8-431d-9d8b-310e3fe0526e
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: f7987a4b-f621-4eec-b713-b2377a1412d5
			defaultHierarchy: LocalDateTable_094cc317-136e-43e7-a1df-9d2f6927bfe2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_is_deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3943022f-5d9f-4628-a95a-c5c43eca10be
		summarizeBy: none
		sourceColumn: _sys_is_deleted

		annotation SummarizationSetBy = Automatic

	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: ff643a83-58ac-4ad5-b46b-05102aa5e1dc
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 583a6909-96d4-4d6f-bfc5-996cdb35ca40
			defaultHierarchy: LocalDateTable_51d4de53-eac0-4d81-b266-78974241e512.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: Short Date
		lineageTag: 30b9898e-bb66-4677-9c36-de7eaae46edd
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 82789530-0c0d-407a-82e6-c2617b7ec1c0
			defaultHierarchy: LocalDateTable_00c8eda7-d2cc-47a6-abb2-7588d268f093.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: be8192e9-68ad-46eb-b89a-3946284dba99
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: a122c0f9-0155-4eb5-be12-57d6f7f71f26
			defaultHierarchy: LocalDateTable_42236937-b08e-45f5-99d6-61ddf2fcce75.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_list_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3a0c83d8-53c9-4f3f-8e64-88c43a548886
		summarizeBy: sum
		sourceColumn: trueai_list_price

		annotation SummarizationSetBy = Automatic

	column trueai_list_price_rule
		dataType: int64
		formatString: 0
		lineageTag: ada4dde4-f242-4112-9bc7-1b7a26b17e3d
		summarizeBy: sum
		sourceColumn: trueai_list_price_rule

		annotation SummarizationSetBy = Automatic

	column trueai_qty
		dataType: double
		formatString: 0
		lineageTag: f3130fe1-63fe-4ca1-85e9-900f72859b9d
		summarizeBy: sum
		sourceColumn: trueai_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column trueai_discount_amt
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 7ff6eee9-d3ac-41b1-9635-935a8752d990
		summarizeBy: sum
		sourceColumn: trueai_discount_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column trueai_discount_pct
		dataType: double
		lineageTag: c2794a63-c525-4c11-99a1-ebe3144c5463
		summarizeBy: sum
		sourceColumn: trueai_discount_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_unit_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 25d88bfc-00a2-4d6c-912d-77ab6ec85ca7
		summarizeBy: sum
		sourceColumn: trueai_unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column trueai_unit_price_rule
		dataType: int64
		formatString: 0
		lineageTag: 110cb8f5-6138-40bc-86cb-3b889f78371f
		summarizeBy: sum
		sourceColumn: trueai_unit_price_rule

		annotation SummarizationSetBy = Automatic

	column 'col.line_items_trueai_list_price' = CALCULATE(MAXX(opp_line_items, opp_line_items[trueai_list_price]))
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 957f84b4-b608-4324-8b7a-065e1faaa0bd
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column cust_text1
		dataType: string
		lineageTag: b39b9cba-b1cf-41e3-84b2-58d07416bdc6
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: 21abdf8a-4c2b-4c1b-8875-2beb1d104e7e
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: 6d5a8016-c913-4ff4-813f-0b9a33b7e180
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: 4faa4045-e7f5-4d01-97d7-a13f48c87ec0
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: 99f759f1-a19a-4728-99c4-9cb6245f1ea2
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: double
		lineageTag: b36f438d-0c39-4d52-97c5-e1444b691c86
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num2
		dataType: double
		lineageTag: 8f87418e-d529-4d8f-9f83-cc7f1ae21d00
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num3
		dataType: double
		lineageTag: 46d48d39-0750-4cd7-a6a3-53e1e05220d3
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num4
		dataType: double
		lineageTag: 9f01b746-3170-4bcb-b404-9021531c5bca
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num5
		dataType: double
		lineageTag: 8be602d6-8751-4757-9c5d-ba0f2448287c
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num6
		dataType: double
		lineageTag: 879fb808-e9e6-4386-9122-aee59165c598
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num7
		dataType: double
		lineageTag: ce7b7fdf-9880-4781-ab86-682487292f37
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cb0c2cd9-f44b-451f-bcb0-ceed5cca7b1c
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4281878e-6c1f-4c07-94db-23ca8c456ddd
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	column trueai_revenue_type_context
		dataType: string
		lineageTag: e4cdd869-5199-4fe7-848b-a5de41a8f86f
		summarizeBy: none
		sourceColumn: trueai_revenue_type_context

		annotation SummarizationSetBy = Automatic

	column trueai_revenue_type
		dataType: string
		lineageTag: 3e6c36eb-2060-4657-a0ac-093356801632
		summarizeBy: none
		sourceColumn: trueai_revenue_type

		annotation SummarizationSetBy = Automatic

	column trueai_revenue_type_rule
		dataType: int64
		formatString: 0
		lineageTag: 8131a728-b9cb-469c-b11c-9177707bc153
		summarizeBy: sum
		sourceColumn: trueai_revenue_type_rule

		annotation SummarizationSetBy = Automatic

	column trueai_product_type
		dataType: string
		lineageTag: 182d0d5f-d7b1-415a-8220-27fb312999a5
		summarizeBy: none
		sourceColumn: trueai_product_type

		annotation SummarizationSetBy = Automatic

	partition opp_line_items-a38b7f9b-295e-4d28-beee-b13ba9cbe459 = m
		mode: import
		source =
				let
				
				
				
				    dbTable = getDBTable("opp_line_items"), // get the right table
				
				     dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"_sys_as_of", type datetime},
				{"_sys_doc_id", type text},
				{"_sys_is_deleted", type logical},
				{"_sys_last_modified_on", type datetime},
				{"_sys_ssr_id", type text},
				{"crm_created_on", type datetime},
				{"crm_currency", type text},
				{"crm_description", type text},
				{"crm_list_price", type number},
				{"crm_modified_on", type datetime},
				{"crm_name", type text},
				{"crm_opp_id", type text},
				{"crm_product_code", type text},
				{"crm_product_id", type text},
				{"crm_qty", Int64.Type},
				{"crm_total_price", type number},
				{"crm_unit_price", type number},
				{"cust_bool1", type logical},
				{"cust_bool2", type logical},
				{"cust_num1", type number},
				{"cust_num2", type number},
				{"cust_num3", type number},
				{"cust_num4", type number},
				{"cust_num5", type number},
				{"cust_num6", type number},
				{"cust_num7", type number},
				{"cust_text1", type text},
				{"cust_text2", type text},
				{"cust_text3", type text},
				{"cust_text4", type text},
				{"cust_text5", type text},
				{"trueai_discount_amt", type number},
				{"trueai_discount_pct", type number},
				{"trueai_list_price", type number},
				{"trueai_list_price_rule", Int64.Type},
				{"trueai_product_type", type text},
				{"trueai_qty", type number},
				{"trueai_revenue_type", type text},
				{"trueai_revenue_type_context", type text},
				{"trueai_revenue_type_rule", Int64.Type},
				{"trueai_total_price", type number},
				{"trueai_total_price_rule", Int64.Type},
				{"trueai_unit_price", type number},
				{"trueai_unit_price_rule", Int64.Type}
				})
				in
				    dbTableTyped

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

