table opps
	lineageTag: 94b5d4f0-c14b-4b61-8e6f-fc611c85e6de

	measure 'meas.opps_count' = CALCULATE(Count(opps[_sys_doc_id]))  // count of opportunity
		formatString: #,0
		displayFolder: _success_metrics
		lineageTag: 2cc843ff-f70c-4756-bc7f-55b6fe32f6b0

	measure 'meas.opps_won_amt' = CALCULATE(SUM(opps[trueai_booking_amt]),opps[trueai_is_won] = True ) // get the won opps  booking amount
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: dba34eb5-a79e-4e3d-83c2-2494b57fe4d4

		annotation PBI_FormatHint = {"currencyCulture":""}

	measure 'meas.opps_won_count' = CALCULATE(Count(opps[_sys_doc_id]),opps[trueai_is_won] = True )// count of won opps
		formatString: #,0
		displayFolder: _success_metrics
		lineageTag: d06a26ea-8130-4af3-99b3-4a9e2d505033

	measure 'meas.opps_lost_count' = CALCULATE(Count(opps[_sys_doc_id]),opps[trueai_is_won] = False ) // get the lost opps count
		formatString: #,0
		displayFolder: _success_metrics
		lineageTag: 8a99d981-2d57-4959-a3a1-1438b9c03dc9

	measure 'meas.opps_won_new_logo_existing_cust_count' = ```
			
			CALCULATE(
			    Count(opps[_sys_doc_id]),           // count of won opps for step new logo and existing customer 
			    opps[trueai_is_won] = True,
			    ssr_history[step_name] in {"New Logo Selling", "Existing Customer Selling"}
			)
			```
		formatString: #,0
		displayFolder: _success_metrics
		lineageTag: d581aaf4-aff3-4ab8-ac67-5e6ec53b0421

	measure 'meas.opps_new_logo_existing_customer_selling_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			    ssr_history[step_name] in {"New Logo Selling", "Existing Customer Selling"}
			    ) 
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: 7514faf0-42d0-4b93-ae3c-94eceb969fcd

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_existing_customer_selling_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			     ssr_history[step_name] in {"Existing Customer Selling"}
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 111331cb-f7bd-4425-b319-a1c0b7cdd742

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_new_logo_selling_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			    ssr_history[step_name] = "New Logo Selling"
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 9eab312a-8420-4bdd-ab53-bf08169e77e5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_post_sales_support_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			     ssr_history[step_name] in {"Post-Sales Support"}
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 6fec311e-00d4-437b-b8e5-82a3661b84be

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_prospecting_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			     ssr_history[step_name] in {"Prospecting"}
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: c0905b74-1adb-4d7d-8437-3d27281bc94b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_all_step_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			     ssr_history[step_name] in {"New Logo Selling", "Prospecting", "Existing Customer Selling", "Post-Sales Support"}
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: e4c8572b-5411-4add-9f95-1ad840289871

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_trueai_booking_amt' = ```
			
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),
			    FILTER(
			        opps,
			        COUNTROWS(RELATEDTABLE(opp_line_items)) > 0     // get the opps booking amt  
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: 20fc4bb7-bc67-44ca-be7d-258a4215b929

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opp_line_items_trueai_booking_amt' =
			
			CALCULATE(
			    SUM(opp_line_items[trueai_total_price]),
			    RELATEDTABLE(opps)
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 7fc77c41-4348-493f-aefa-925c01369030

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opp_book_amt_opp_line_book_amt_diff' =
			
			var opps_amt = [meas.opps_trueai_booking_amt]   // get the opps booking amt
			var oli_amt = [meas.opp_line_items_trueai_booking_amt]          // get the oli booking amt
			var res  = opps_amt - oli_amt
			
			RETURN
			res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 9b5b3012-7465-4d5d-8268-e028e13a1c72

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_crm_booking_amt' =
			
			CALCULATE(
			    SUM(
			        opps[crm_booking_amt]
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: 3c033b02-a215-4b6c-a54f-4391f82c7cb0

	measure 'meas.open_opps_is_open' = ```
			
			var  asof_date = date(2024,1,1) // the "current" date
				
			// filter down only open opps and associated history steps for that period (include anything started on or before the as if date and not finished on as of date
			var res = CALCULATE(
			    DISTINCTCOUNT(opps[_sys_doc_id]), 
			    opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date 
			)
			return res 
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 386df656-540e-4d43-90bf-29fe8a75c043

	measure 'meas.open_opps_order' = ```
			
			
			
				// get th date we care about 
				var  asof_date = date(2024,1,1) // the "current" date
				
				// filter down only open opps and associated history steps for that period (include anything started on or before the as if date and not finished on as of date
				var tbl_curr_open_opps= CALCULATETABLE((opps),  opps[_sys_doc_id] <> "123"   && opps[trueai_stage] <> "123"   && opps[crm_stage_name] <> "123"  && opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date )
			
			
			    // wnsure that end date is unique otherwise weird results
				var tbl_curr_open_opps_unique_end_date = ADDCOLUMNS(tbl_curr_open_opps,
						"oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(00, "00")
				)
					
				// determine the number of prior steps present for the same opps
				var tbl_curr_open_opps_prior_oh_entries = 
				ADDCOLUMNS(
			    tbl_curr_open_opps_unique_end_date,
			    "opp_id_count", 
			    VAR CurrentOppID = (opps[_sys_doc_id])
				var tblTemp = tbl_curr_open_opps_unique_end_date
			    RETURN COUNTX(filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID &&  opps[_sys_filt_end_date] <= asof_date  ),[_sys_doc_id] ))
			
			    var oh_cnt = MAXx(tbl_curr_open_opps_prior_oh_entries, [opp_id_count])
			
			    return oh_cnt
			
			
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: f94ab53f-b321-4774-ade9-7010b94d9687

	measure 'meas.open_opps_rec' = ```
			
				var  asof_date = date(2024,1,1) // the "current" date
				
				// filter down only open opps and associated history steps for that period (include anything started on or before the as if date and not finished on as of date
				var tbl_curr_open_opps= CALCULATETABLE(opps, opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date )
			
			
			
			var res  = countx(tbl_curr_open_opps, IF( LEFT([_sys_doc_id], 1) = "A", [_sys_doc_id], blank()) )
			return res 
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 8896c5d8-5860-4419-9167-539af4c288e4

	measure 'meas.open_opps_step_by_step' = ```
			
			
			var  asof_date = date(2024,1,1) // the "current" date
			var ff =  CALCULATETABLE(opps)
			var tbl_curr_open_opps= FIlter((ff),  opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date )
			
			
			    // wnsure that end date is unique otherwise weird results
				var tbl_curr_open_opps_unique_end_date = ADDCOLUMNS(tbl_curr_open_opps,
						"oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(00, "00")
			            // "oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(opps[_trueai_step_sequence], "00")
				)
					
				// determine the number of prior steps present for the same opps
				var tbl_curr_open_opps_prior_oh_entries = 
				ADDCOLUMNS(
			    tbl_curr_open_opps_unique_end_date,
			    "oh_doc_id", 
			    VAR CurrentOppID = (opps[_sys_doc_id])
				var tblTemp = tbl_curr_open_opps_unique_end_date
			    var doc_id =  MAXX(TOPN(1,filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID &&  opps[_sys_filt_end_date] <= asof_date  ), opps[_sys_filt_end_date],FALSE), opps[_sys_doc_id])
			    var doc_id2 =  MAXX(TOPN(1,filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID  ), opps[_sys_filt_end_date],True), opps[_sys_doc_id])
			    var res_doc_id =If (doc_id = BLANK(), doc_id2, doc_id)
			    RETURN res_doc_id)
			
			
			
			    var filter_tbl = FILTER(tbl_curr_open_opps_prior_oh_entries, [oh_doc_id] =[_sys_doc_id])
			
			    var res =    CALCULATE(count(opps[_sys_doc_id]), filter_tbl )
			    return res
			
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 5c8c0dc1-4e98-4864-84aa-d8e220345f38

	measure 'meas.open_opps_step_by_step_amt' =
			
			
			var tbl = filter((opps), LEFT(opps[_sys_doc_id],1) = "B")
			
			var res = CALCULATE(sum(opps[trueai_booking_amt]),tbl)
			
			return res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _open_opps_pipeline
		lineageTag: 97534504-33cc-4e7a-bf25-44005419fd32

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.open_opps_step_by_step_slicer' = ```
			
			
			
			var  asof_date = date(2024,1,1) // the "current" date
			var tbl_curr_open_opps =  CALCULATETABLE(opps , opps[_sys_doc_id] <> "abc" && opps[_sys_doc_id] <> "abc" && opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date )
			
			
			    // wnsure that end date is unique otherwise weird results
				var tbl_curr_open_opps_unique_end_date = ADDCOLUMNS(tbl_curr_open_opps,
						"oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(00, "00")
			            // "oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(open_opps[oh_trueai_step_sequence], "00")
				)
					
				// determine the number of prior steps present for the same opps
				var tbl_curr_open_opps_prior_oh_entries = 
				ADDCOLUMNS(
			    tbl_curr_open_opps_unique_end_date,
			    "oh_doc_id", 
			    VAR CurrentOppID = (opps[_sys_doc_id])
				var tblTemp = tbl_curr_open_opps_unique_end_date
			    var doc_id =  MAXX(TOPN(1,filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID &&  opps[_sys_filt_end_date] <= asof_date  ), opps[_sys_filt_end_date],FALSE), opps[_sys_doc_id])
			    var doc_id2 =  MAXX(TOPN(1,filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID  ), opps[_sys_filt_end_date],True), opps[_sys_doc_id])
			    var res_doc_id =If (doc_id = BLANK(), doc_id2, doc_id)
			    RETURN res_doc_id)
			
			
			
			    var filter_tbl = FILTER(tbl_curr_open_opps_prior_oh_entries, [oh_doc_id] =[_sys_doc_id])
			
			    var res =    MAXX(filter_tbl,  [oh_doc_id])
			    return res
			
			```
		displayFolder: _open_opps_pipeline
		lineageTag: d6a78e90-d5b6-4c05-8a4a-81b5971753f0

	measure 'meas.ssr_history_opps_is_open' = ```
			
			var  asof_date = [meas.sel_date] // the "current" date
				
			// filter down only open opps and associated history steps for that period (include anything started on or before the as if date and not finished on as of date
			var res = CALCULATE(
			    count(opps[_sys_doc_id]), 
			    opps[_sys_filt_end_date] > asof_date &&  opps[_sys_filt_start_date] < asof_date 
			)
			return res 
			```
		formatString: 0
		displayFolder: _opps
		lineageTag: 10a98a67-885b-4ca7-aa63-5dd5d2e57d1b

	measure 'meas.total_opp_count' = count(opps[_sys_doc_id])
		formatString: 0
		displayFolder: _opps
		lineageTag: d17e8206-08e5-44bc-bc7a-e2ebbf39d72c

	measure 'meas.opps_name' =
			CALCULATE(
			    MAX(opps[crm_name])
			)
		lineageTag: ca7bd717-4604-47eb-963c-306b7343bb15

	measure 'meas.opps_booking_lost_amt' = CALCULATE(SUM(opps[trueai_booking_amt]),opps[trueai_is_won] = False ) // get the lost opps  booking amount
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: 1ffbc42c-1acf-476e-8a06-e9f51390f25f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.opps_avg_deal_size_amt' = CALCULATE(Average(opps[trueai_booking_amt]), opps[trueai_booking_amt] > 0 )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 415c9aee-bf6f-4607-9601-ebe0db8d3162

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.count_of_crm_deep_link' =
			
			DISTINCTCOUNT(opps[crm_deep_link])
		formatString: 0
		lineageTag: 212bd76d-4e51-41b4-ba2f-ea7b7160fc31

	measure 'meas.opps_cust_num1' =
			
			SUM(opps[cust_num1])
		displayFolder: _opps_verification
		lineageTag: 52f7557f-90ac-41af-8fa1-3f5be2fac8a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_cust_num2' =
			
			SUM(opps[cust_num2])
		displayFolder: _opps_verification
		lineageTag: 0e1671dd-07af-4b69-864a-e3d37e2f37bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_cust_num3' =
			
			SUM(opps[cust_num3])
		displayFolder: _opps_verification
		lineageTag: 4c3ed9b3-6d46-4b41-8e94-7092d0cc5c0b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_cust_num4' =
			
			SUM(opps[cust_num4])
		displayFolder: _opps_verification
		lineageTag: f5381680-13e5-4c8d-b8e5-8bc82968b744

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_cust_num5' =
			
			SUM(opps[cust_num5])
		displayFolder: _opps_verification
		lineageTag: c92f1116-77c7-483c-8af8-925d042d1abf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_cust_num6' =
			
			SUM(opps[cust_num6])
		displayFolder: _opps_verification
		lineageTag: 5ee9da03-25c8-4b34-837e-90be69bf79ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_cust_num7' =
			
			SUM(opps[cust_num7])
		displayFolder: _opps_verification
		lineageTag: 7f545910-d104-48da-ab5c-7e6bdf38eb9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.won_amt' = CALCULATE(sum(opps[trueai_booking_amt]), opps[trueai_is_won] = true)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 79ef7551-1b06-4a8a-8b63-141ca9196a8c

	measure 'meas.won_count' = CALCULATE(count(opps[trueai_booking_amt]), opps[trueai_is_won] = true)
		formatString: #,0
		displayFolder: _opps
		lineageTag: ec154535-f996-4fb0-a39a-ee15e2abb37c

	measure 'meas.opps_booking_amt_total' = ```
			
			CALCULATE(
			    [meas.opps_booking_amt],
			    ALLSELECTED() 
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 3e4fd190-bb25-4c89-a94b-61cc9b045123

	measure 'meas.lost_count' = CALCULATE(count(opps[trueai_booking_amt]), opps[trueai_is_won] = false)
		formatString: #,0
		displayFolder: _opps
		lineageTag: 00e5941e-43c3-4a97-92c3-a7760510aba7

	measure 'meas.opps_booking_amt_avg' = CALCULATE(AVERAGE((opps[trueai_booking_amt])))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 4a249f2a-182f-4d9d-a156-f5a27543751b

	measure 'meas.opps_sales_cycle_avg_days' = ```
			
			var res = CALCULATE(AVERAGE(opps[col.trueai_days]))
			return res 
			```
		formatString: #,##0" Days"
		displayFolder: _opps
		lineageTag: 575eeaba-caa4-408c-9594-805b91564343

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.lost_amt' = CALCULATE(sum(opps[trueai_booking_amt]), opps[trueai_is_won] = false)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: bf734b04-1e82-434c-8912-c972ddb30ac3

	measure 'meas.opps_lost_amt_in_stage_pct' = DIVIDE([meas.opps_booking_lost_amt],[meas.opps_booking_amt])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _success_metrics
		lineageTag: 8ade373a-56e3-49bd-8f59-3c84379ba6f8

	measure 'meas.opps_booking_amt' = CALCULATE( sum(opps[trueai_booking_amt]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 4529b0ce-1347-4c49-81c8-a51245ee0275

	measure 'meas.opps_booking_lost_amt_pct' = DIVIDE([meas.opps_booking_lost_amt], [meas.opps_booking_amt_total])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _success_metrics
		lineageTag: 585994fc-6fc1-4e21-bae3-2ee24c6e8902

	measure 'meas.opps_max_stages' =
			
			CALCULATE (
			    sum( opps[col.trueai_opp_stages_recorded] )
			)
		formatString: 0
		displayFolder: _success_metrics
		lineageTag: 40d5b9b3-a8b1-495b-95bb-dd379d53e138

	measure 'meas.opps_win_rate_value' = DIVIDE([meas.won_amt],[meas.opps_booking_amt_total])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _success_metrics
		lineageTag: a94c7b43-59b3-4861-97be-92d7b828c957

	measure 'meas.opps_booking_amt_stage' = ```
			[meas.opps_booking_amt_total] - [meas.opps_booking_amt] 
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 04beffda-c477-4ae0-8bee-c4cf2fa5db12

	measure 'meas.opps_booking_amt_reached_next_stage' = ```
			
			VAR curIdx =
			    MAX ( open_pipeline[trueai_sort_id] )
			VAR nextIdx =
			    CALCULATE (
			        MINX (
			            FILTER ( ALL ( open_pipeline[trueai_sort_id] ),
			                open_pipeline[trueai_sort_id] > curIdx
			            ),
			            open_pipeline[trueai_sort_id]
			        )
			    )
			RETURN
			IF (
			    ISBLANK ( nextIdx ),
			    BLANK(),
			    CALCULATE (
			        [meas.opps_booking_amt],
			        REMOVEFILTERS (
			            open_pipeline[trueai_sort_id],
			            open_pipeline[trueai_stage],
			            open_pipeline[trueai_stage_name],
			            open_pipeline[trueai_stage_num]
			        ),
			        open_pipeline[trueai_stage_name] <> "Closed Lost",
			         open_pipeline[trueai_stage_name] <> "Closed Won",
			        TREATAS ( { nextIdx }, open_pipeline[trueai_sort_id] )
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: aa23b27a-3667-4817-9d76-eca8052fa0b2

	measure 'meas.opps_total_crm_booking_amt' = SUM(opps[crm_booking_amt])
		lineageTag: 9f546c8e-a727-4045-b9a7-e88973fb9cd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_optimal_disc_level' = ```
			
			// --- Virtual Table 1: TierBase ---
			VAR TierBase =
			    // Create a summarized table grouping all Opportunities by their Discount Tier.
			    SUMMARIZE(
			        opps,
			        opps[trueai_discount_pct_tier], // The grouping key (e.g., "10-20%", "5%+").
			        "TierLabel", MAX(opps[trueai_discount_pct_tier]), // Get the label for display.
			        "DeltaVal", [meas.opps_delta_expected_pct] // Calculate the Delta value for each tier group.
			    )
			    
			// --- Virtual Table 2: TierParsed ---
			VAR TierParsed =
			    // Clean up the Tier Labels to prepare them for numerical extraction.
			    ADDCOLUMNS(
			        TierBase,
			        // Remove '%' and '+' symbols (e.g., "10-20%" becomes "10-20").
			        "CleanText", SUBSTITUTE(SUBSTITUTE([TierLabel], "%", ""), "+", ""),
			        // Find the position of the dash to separate the range start/end.
			        "DashPos", FIND("-", SUBSTITUTE(SUBSTITUTE([TierLabel], "%", ""), "+", ""), 1, 0)
			    )
			
			// --- Virtual Table 3: TierBounded ---
			VAR TierBounded =
			    // Extract the numerical start and end bounds of each tier.
			    ADDCOLUMNS(
			        TierParsed,
			        // Calculate the starting percentage (TierStart).
			        "TierStart",
			            IF(
			                [DashPos] > 0, // Check if it is a range (e.g., "10-20").
			                VALUE(LEFT([CleanText], [DashPos] - 1)), // Extract value before the dash.
			                VALUE([CleanText]) // Single value tier (e.g., "5").
			            ),
			        // Calculate the ending percentage (TierEnd).
			        "TierEnd",
			            IF(
			                [DashPos] > 0, // Check if it is a range.
			                VALUE(RIGHT([CleanText], LEN([CleanText]) - [DashPos])), // Extract value after the dash.
			                // Handle single-value tiers: if it ends with '+', treat the end as very high (1,000,000).
			                IF(RIGHT([TierLabel], 1) = "+", 1000000, VALUE([CleanText]))
			            )
			    )
			
			// --- Virtual Table 4: TierRanked ---
			VAR TierRanked =
			    // Add sorting and ranking columns based on the tier boundaries.
			    ADDCOLUMNS(
			        TierBounded,
			        // Create a robust numerical key for sorting (TierStart * 1000 + TierEnd).
			        // This ensures tiers are always sorted correctly, e.g., "5-10" comes before "10-15".
			        "SortKey", [TierStart] * 1000 + [TierEnd],
			        // Rank the tiers based on the SortKey.
			        "Rank", RANKX(TierBounded, [TierStart] * 1000 + [TierEnd], , ASC, DENSE)
			    )
			
			---
			
			// 1. Calculate Baseline and Threshold
			// Calculate the average DeltaVal for the first two lowest-ranked tiers.
			VAR Baseline =
			    AVERAGEX(
			        FILTER(TierRanked, [Rank] <= 2), 
			        [DeltaVal]
			    )
			
			// Define the threshold: Baseline plus the 5% (0.05) increase target.
			VAR Threshold = Baseline + 0.05
			
			---
			
			// 2. Find the Optimal Tier's SortKey
			// Find the *minimum* SortKey (i.e., the first/lowest tier) that meets both conditions:
			// a) Its DeltaVal is >= the calculated Threshold.
			// b) Its Rank is > 2 (it's not one of the baseline tiers).
			VAR OptimalSortKey =
			    MINX(
			        FILTER(
			            TierRanked, 
			            [DeltaVal] >= Threshold && [Rank] > 2
			        ),
			        [SortKey]
			    )
			
			// 3. Look up the Label using the Optimal SortKey
			// Use the found OptimalSortKey to pull the actual TierLabel.
			// MAXX is used here to safely pull a single corresponding text value.
			VAR ResultLabel =
			    MAXX(
			        FILTER(
			            TierRanked, 
			            [SortKey] = OptimalSortKey
			        ),
			        [TierLabel]
			    )
			
			RETURN
			    // Returns the Tier Label (e.g., "20-30%") of the first tier
			    // that exceeds the 5% improvement threshold.
			    ResultLabel
			```
		lineageTag: 66645cae-a7a3-415a-869b-7803897fe2f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_optimal_discount_deal_count_pct' =
			
			-- Step 1: Get the result from your existing "Optimal Discount Level" measure
			VAR BestTier = [meas.opps_optimal_disc_level]   -- e.g. returns "30–40%"
			
			-- Step 2: Count deals in that tier
			VAR OptimalTierDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS({ BestTier }, opps[trueai_discount_pct_tier])  -- apply tier filter at opp_line_items level
			    )
			
			-- Step 3: Count total deals across all tiers
			VAR TotalDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        ALL(opps[trueai_discount_pct_tier])
			    )
			
			-- Step 4: Return % of deals in the optimal tier
			RETURN
			    DIVIDE(OptimalTierDeals, TotalDeals)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4088315a-082d-4abf-93a2-2fafde065533

	measure 'meas.opps_over_discounted_deal_pct' =
			
			-- Step 1: Get the optimal discount tier (e.g. "30-40%" or "40%+")
			VAR BestTier = [meas.opps_optimal_disc_level]
			
			-- Step 2: Clean and parse the upper bound of that tier
			VAR BestTierClean =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TRIM(BestTier), "–", "-"), "—", "-"), " ", "")
			VAR BestTierUpper =
			    VAR parts = SUBSTITUTE(BestTierClean, "%", "")
			    VAR dashPos = SEARCH("-", parts, 1, BLANK())
			    VAR upperText =
			        SWITCH(
			            TRUE(),
			            NOT ISBLANK(dashPos), MID(parts, dashPos + 1, LEN(parts) - dashPos),  -- "30-40%" → "40"
			            RIGHT(parts, 1) = "+", LEFT(parts, LEN(parts) - 1),                   -- "40%+"   → "40"
			            TRUE(), parts                                                        -- "0%"     → "0"
			        )
			    RETURN VALUE(upperText)
			
			-- Step 3: Build a lookup of all tiers with numeric upper bounds
			VAR Tiers =
			    ADDCOLUMNS(
			        VALUES(opps[trueai_discount_pct_tier]),
			        "Upper",
			            VAR clean = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TRIM(opps[trueai_discount_pct_tier]), "–", "-"), "—", "-"), " ", "")
			            VAR p = SUBSTITUTE(clean, "%", "")
			            VAR dashPos = SEARCH("-", p, 1, BLANK())
			            VAR upperText =
			                SWITCH(
			                    TRUE(),
			                    RIGHT(p, 1) = "+", "999",                      -- treat “%+” as open-ended top bucket
			                    NOT ISBLANK(dashPos), MID(p, dashPos + 1, LEN(p) - dashPos),
			                    TRUE(), p
			                )
			            RETURN VALUE(upperText)
			    )
			
			-- Step 4: Select tiers whose numeric upper bound is higher than the optimal tier
			VAR OverTiers =
			    SELECTCOLUMNS(
			        FILTER(Tiers, [Upper] > BestTierUpper),
			        "Tier", opps[trueai_discount_pct_tier]
			    )
			
			-- Step 5: Count deals in those “over-discounted” tiers
			VAR OverDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS(OverTiers, opps[trueai_discount_pct_tier])
			    )
			
			-- Step 6: Count all deals (for denominator)
			VAR TotalDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        ALL(opps[trueai_discount_pct_tier])
			    )
			
			-- Step 7: Return % of deals over optimal tier
			RETURN
			    COALESCE(DIVIDE(OverDeals, TotalDeals), 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 63b0aff0-9501-46ad-a241-5c4d4be19b7d

	measure 'meas.opps_no_discount_count' =
			
			CALCULATE(
			    [meas.ssr_history_step_count],                 -- or COUNT of opps if you prefer
			    TREATAS({ "0%" }, opps[trueai_discount_pct_tier])
			)
		lineageTag: 7f17629f-a273-407d-9136-24660f365ac5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_over_discount_deal_count' =
			
			VAR BestTier = [meas.opps_optimal_disc_level]
			VAR BestTierClean =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TRIM(BestTier), "–", "-"), "—", "-"), " ", "")
			VAR BestTierUpper =
			    VAR parts = SUBSTITUTE(BestTierClean, "%", "")
			    VAR dashPos = SEARCH("-", parts, 1, BLANK())
			    VAR upperText =
			        SWITCH(
			            TRUE(),
			            NOT ISBLANK(dashPos), MID(parts, dashPos + 1, LEN(parts) - dashPos),  -- "30-40%" → "40"
			            RIGHT(parts, 1) = "+", LEFT(parts, LEN(parts) - 1),                   -- "40%+"   → "40"
			            TRUE(), parts                                                        -- "0%"     → "0"
			        )
			    RETURN VALUE(upperText)
			
			VAR Tiers =
			    ADDCOLUMNS(
			        VALUES(opps[trueai_discount_pct_tier]),
			        "Upper",
			            VAR clean = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TRIM(opps[trueai_discount_pct_tier]), "–", "-"), "—", "-"), " ", "")
			            VAR p = SUBSTITUTE(clean, "%", "")
			            VAR dashPos = SEARCH("-", p, 1, BLANK())
			            VAR upperText =
			                SWITCH(
			                    TRUE(),
			                    RIGHT(p, 1) = "+", "999",                      -- treat “%+” as open-ended
			                    NOT ISBLANK(dashPos), MID(p, dashPos + 1, LEN(p) - dashPos),
			                    TRUE(), p
			                )
			            RETURN VALUE(upperText)
			    )
			
			VAR OverTiers =
			    SELECTCOLUMNS(
			        FILTER(Tiers, [Upper] > BestTierUpper),
			        "Tier", opps[trueai_discount_pct_tier]
			    )
			
			RETURN
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS(OverTiers, opps[trueai_discount_pct_tier])
			    )
		lineageTag: 25e3810a-7540-4eaf-ae38-99d14a3688c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_optimal_discount_deal_count' =
			
			VAR BestTier = [meas.opps_optimal_disc_level]
			RETURN
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS({ BestTier }, opps[trueai_discount_pct_tier])
			    )
		formatString: 0
		lineageTag: 3df4757a-4c6f-4c6e-b5a8-fb9c558fe44f

	measure 'meas.opps_no_discount_pct' =
			
			VAR NoDiscDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS({ "0%" }, opps[trueai_discount_pct_tier])
			    )
			VAR TotalDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        ALL(opps[trueai_discount_pct_tier])
			    )
			RETURN
			    DIVIDE(NoDiscDeals, TotalDeals)
		lineageTag: 112e76c9-31a5-4380-ab5e-d65f6a54ef96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_under_discount_deal_count' =
			
			VAR BestTier = [meas.opps_optimal_disc_level]
			
			-- Convert the tier text (e.g. "20-30%") to its upper numeric boundary
			VAR BestTierUpper =
			    VALUE(
			        SUBSTITUTE(
			            SUBSTITUTE(
			                RIGHT(BestTier, LEN(BestTier) - SEARCH("-", BestTier, 1, 0)),
			                "%",
			                ""
			            ),
			            "+",
			            ""
			        )
			    )
			
			RETURN
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        FILTER(
			            ALL(opps[trueai_discount_pct_tier]),
			            VAR Tier = opps[trueai_discount_pct_tier]
			            VAR TierClean =
			                SUBSTITUTE(SUBSTITUTE(Tier, "%", ""), "+", "")
			            VAR DashPos = SEARCH("-", TierClean, 1, BLANK())
			            VAR UpperText =
			                SWITCH(
			                    TRUE(),
			                    ISBLANK(DashPos), TierClean,
			                    RIGHT(TierClean, 1) = "+", "999",
			                    TRUE(), MID(TierClean, DashPos + 1, LEN(TierClean))
			                )
			            VAR TierUpper = VALUE(UpperText)
			            RETURN
			                TierUpper < BestTierUpper &&     // under optimal
			                TierUpper > 0                    // exclude 0% and negatives
			        )
			    )
		lineageTag: fc573d3e-78f1-4f98-8026-133216143789

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_under_discount_deal_pct' =
			
			VAR UnderCount = [meas.opps_under_discount_deal_count]
			VAR TotalCount =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        ALL(opps[trueai_discount_pct_tier])
			    )
			RETURN
			    DIVIDE(UnderCount, TotalCount)
		lineageTag: f65c7a41-f806-4a0e-ac7c-1780f66da52f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.optimal_discount_tier_background' =
			
			VAR OptimalTier =
			    CALCULATE(
			        [meas.opps_optimal_disc_level],
			        REMOVEFILTERS('opps')
			    )
			VAR ThisTier = SELECTEDVALUE('opps'[trueai_discount_pct_tier])
			
			RETURN
			    SWITCH(
			        TRUE(),
			        ThisTier = OptimalTier, "#78903B",   // Optimal tier (green)
			        ThisTier < OptimalTier, "#595B6F",   // Under optimal (dark blue-gray)
			        ThisTier > OptimalTier, "#912452",   // Over optimal (purple-gray)
			        "#1E1E1E"                            // Default / fallback
			    )
		lineageTag: e358cd7c-fade-48a9-8d27-8493a0f1bce1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_optimal_discount_pct' =
			
			-- Get the optimal discount tier text (e.g. "30-40%")
			VAR TierText = [meas.opps_optimal_disc_level]
			
			-- Find the position of the dash "-" (used to split lower/upper bounds)
			VAR DashPos = SEARCH("-", TierText, 1, BLANK())
			
			-- Extract the upper bound of the range (e.g. "40" from "30-40%")
			VAR UpperPart =
			    IF(
			        ISBLANK(DashPos),
			        SUBSTITUTE(TierText, "%", ""),         -- if no dash, just remove "%"
			        MID(TierText, DashPos + 1, LEN(TierText))  -- else get text after "-"
			    )
			
			-- Convert upper bound text to a number and divide by 100 to get percent (e.g. "40" → 0.4)
			VAR UpperPct = VALUE(SUBSTITUTE(SUBSTITUTE(UpperPart, "%", ""), "+", "")) / 100
			
			-- Extract the lower bound of the range (e.g. "30" from "30-40%")
			VAR LowerPart =
			    IF(
			        ISBLANK(DashPos),
			        SUBSTITUTE(TierText, "%", ""),         -- if no dash, just use the single number
			        LEFT(TierText, DashPos - 1)            -- else get text before "-"
			    )
			
			-- Convert lower bound text to a number and divide by 100 (e.g. "30" → 0.3)
			VAR LowerPct = VALUE(SUBSTITUTE(SUBSTITUTE(LowerPart, "%", ""), "+", "")) / 100
			
			-- Return the midpoint of the range (e.g. (0.3 + 0.4) / 2 = 0.35)
			RETURN
			    DIVIDE(UpperPct + LowerPct, 2)
		lineageTag: 4bebb021-1832-44b1-bd86-13afcb8a7888

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_over_discount_amt' = ```
			
			// 1️⃣ Get the current optimal discount tier text (e.g., "30-40%" or "50%+")
			VAR BestTier = [meas.opps_optimal_disc_level]
			
			// --- Robust Parsing Logic for BestTierUpper ---
			
			// Handle cases where BestTier might be BLANK() (e.g., no data met the optimal criteria)
			VAR IsValidTier = NOT ISBLANK(BestTier)
			
			// Simplified parsing: 
			// Finds the numeric value *after* the dash (for ranges) OR the entire value (for X% or X%+).
			// We'll rely on the logic from the previous measure's parsing for robustness.
			VAR CleanText = 
			    IF(
			        IsValidTier,
			        SUBSTITUTE(SUBSTITUTE(BestTier, "%", ""), "+", ""),
			        BLANK()
			    )
			
			VAR DashPos = 
			    IF(
			        IsValidTier,
			        SEARCH("-", CleanText, 1, 0), // If no dash, returns 0 (handled by error/default below)
			        BLANK()
			    )
			
			// Determine the value to use as the upper bound:
			VAR BestTierUpperPct =
			    IF(
			        NOT IsValidTier,
			        BLANK(), // Skip calculation if BestTier is blank.
			        IF(
			            DashPos > 0,
			            // Case 1: Range tier (e.g., "30-40" -> take "40")
			            VALUE(RIGHT(CleanText, LEN(CleanText) - DashPos)),
			            // Case 2: Single tier (e.g., "50" or "50+")
			            IF(
			                RIGHT(BestTier, 1) = "+",
			                // For X%+, BestTierUpper should be X% (the lower bound of the 'over' range).
			                VALUE(CleanText), 
			                // For a single tier like "50%", treat BestTierUpper as 50.
			                VALUE(CleanText)
			            )
			        )
			    )
			
			// 2️⃣ Convert the parsed upper numeric boundary to a decimal percentage (e.g., 40 → 0.40)
			VAR BestTierUpper = DIVIDE(BestTierUpperPct, 100, BLANK())
			
			
			RETURN
			// Check if a valid optimal tier was found before summing (prevents errors)
			IF(
			    ISBLANK(BestTierUpper),
			    0, // Return 0 if no optimal tier was determined.
			
			    // 3️⃣ Iterate all deals in opps, summing leakage for those above the optimal tier
			    SUMX(
			        FILTER(
			            'opps',
			            // Only deals whose discount percentage is *strictly greater* than the upper bound of the optimal tier.
			            'opps'[trueai_discount_pct] > BestTierUpper && 
			            'opps'[trueai_discount_pct] > 0 && 
			            'opps'[trueai_booking_amt] > 0
			        ),
			        
			        VAR ActualDisc = 'opps'[trueai_discount_pct]
			        VAR Amount = 'opps'[trueai_booking_amt]
			
			        // 4️⃣ Compute the Gross (list) Price before discount
			        // Avoids division by zero/near-zero if discount is 1 (100%) or higher
			        VAR Gross = DIVIDE(Amount, 1 - ActualDisc, BLANK()) 
			
			        // 5️⃣ The "extra" discount given beyond the upper limit of the optimal tier
			        VAR ExtraDiscountPct = ActualDisc - BestTierUpper
			
			        // 6️⃣ Calculate leakage ($) = list price × excess discount %
			        VAR Wasted = Gross * ExtraDiscountPct
			
			        // Return the wasted amount (ensure it's not negative, though logic should prevent that)
			        RETURN IF(Wasted > 0, Wasted, 0)
			    )
			)
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 507893f4-f755-4633-8227-88d3a5e498e8

	measure 'meas.opps_under_discount_amt' =
			
			VAR BestTier = [meas.opps_optimal_disc_level]
			
			-- 🧩 Ensure the measure has a valid string before parsing
			VAR SafeTier =
			    IF(
			        NOT ISBLANK(BestTier),
			        BestTier,
			        "0-0%"     -- default fallback to prevent string errors
			    )
			
			-- Extract lower boundary safely
			VAR DashPos = SEARCH("-", SafeTier, 1, BLANK())
			
			VAR BestTierLowerText =
			    IF(
			        ISBLANK(DashPos),
			        SUBSTITUTE(SUBSTITUTE(SafeTier, "%", ""), "+", ""),
			        LEFT(SafeTier, DashPos - 1)
			    )
			
			VAR BestTierLower = VALUE(BestTierLowerText) / 100
			
			RETURN
			SUMX(
			    FILTER(
			        'opps',
			        'opps'[trueai_discount_pct] < BestTierLower &&
			        'opps'[trueai_discount_pct] > 0 &&
			        'opps'[trueai_booking_amt] > 0
			    ),
			    VAR ActualDisc = 'opps'[trueai_discount_pct]
			    VAR Amount = 'opps'[trueai_booking_amt]
			    VAR Gross = DIVIDE(Amount, 1 - ActualDisc)
			    VAR Missed = Gross * (BestTierLower - ActualDisc)
			    RETURN IF(Missed > 0, Missed, 0)
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3b0c2120-0320-4b5f-b0ee-169487a43ba8

	measure 'meas.opps_discount_avg_pct' =
			
			AVERAGEX(
			    VALUES('opps'[_sys_doc_id]),
			    VAR BookedAmt =
			        CALCULATE(SUM('opps'[trueai_booking_amt]))
			    VAR ListAmt =
			        CALCULATE(SUM('opp_line_items'[trueai_list_price]))
			    RETURN
			        IF(
			            ListAmt > 0,
			            ABS(DIVIDE(ListAmt - BookedAmt, ListAmt)),   // ← always positive
			            BLANK()
			        )
			)
		lineageTag: 0a4f6d01-86d8-4647-a75d-6f5468467ccb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_discount_avg_pct' = ```
			
			VAR list_price = CALCULATE(SUM (opps[col.trueai_list_price_amt])) 
			VAR booking = CALCULATE(SUM (opps[trueai_booking_amt])) 
			VAR res = DIVIDE(list_price - booking, list_price, BLANK()) 
			RETURN res
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6e72aa0a-1689-423c-a601-75d453bd1b16

	measure 'meas.opps_avg_discount_pct' = ```
			
			AVERAGE('opps'[trueai_discount_pct]) 
			```
		lineageTag: d7195d3c-688d-44b8-94cb-20117f9b2a55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas._diagnostic_delta_test' =
			
			VAR SuccessRate = CALCULATE([meas.ssr_history_success_rate], KEEPFILTERS(opps))
			VAR ExpectedRate = CALCULATE([meas.ssr_history_success_prob_avg], KEEPFILTERS(opps))
			RETURN
			SuccessRate - ExpectedRate
		lineageTag: cc8997f7-91d5-4b35-a9fb-ba06e2532354

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_doc_id
		dataType: string
		lineageTag: 88fcbd55-d718-43f8-9717-ccc01592c495
		summarizeBy: count
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = User

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: a6cf0900-2913-4ba5-8576-b6c2f8985e72
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 5fda0ce1-daaf-4bd0-9f51-2660c3e09280
			defaultHierarchy: LocalDateTable_3c94028f-8877-46e3-979b-5cd8d33be02e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 49367a97-76a2-44aa-88af-dc267da57b6f
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 55527176-a1e5-4f40-b689-4c4e400bbb6a
			defaultHierarchy: LocalDateTable_13f4f704-f348-4cd9-8666-42fbbd986b71.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_ssr_id
		dataType: string
		lineageTag: f55be3c2-25bd-49a6-954e-d1f0612cf4c6
		summarizeBy: none
		sourceColumn: _sys_ssr_id

		annotation SummarizationSetBy = Automatic

	column crm_account_custom_value_1
		dataType: string
		lineageTag: 539d75b9-5ab4-4caa-b2f8-bf8d77f44b89
		summarizeBy: none
		sourceColumn: crm_account_custom_value_1

		annotation SummarizationSetBy = Automatic

	column crm_account_custom_value_2
		dataType: string
		lineageTag: 06fad6ce-b10b-4c5e-84de-67a29f9e9823
		summarizeBy: none
		sourceColumn: crm_account_custom_value_2

		annotation SummarizationSetBy = Automatic

	column crm_account_custom_value_3
		dataType: string
		lineageTag: 06c8997d-4a29-4ce3-8b8b-66395e2e2dfb
		summarizeBy: none
		sourceColumn: crm_account_custom_value_3

		annotation SummarizationSetBy = Automatic

	column crm_account_id
		dataType: string
		lineageTag: 3b3bbf19-5963-4e2c-99cc-2dc675dee1fb
		summarizeBy: none
		sourceColumn: crm_account_id

		annotation SummarizationSetBy = Automatic

	column crm_booking_amt
		dataType: double
		lineageTag: d4c3d431-20a1-4523-a30f-6ee2253ba7f0
		summarizeBy: sum
		sourceColumn: crm_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_close_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 1144a88b-9c5c-4e96-bd8d-ec0c252506be
		summarizeBy: none
		sourceColumn: crm_close_date

		variation Variation
			isDefault
			relationship: 01c51b59-7ea6-4004-aed8-958a8dc1e5af
			defaultHierarchy: LocalDateTable_fcaea0e2-d7e0-4a55-8ced-8a82a2761917.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column crm_complt
		dataType: double
		lineageTag: 301775ce-0f4e-4462-8146-aab775558b0a
		summarizeBy: sum
		sourceColumn: crm_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_contact
		dataType: double
		lineageTag: eade5a58-25b1-468d-85b1-85a314c26af2
		summarizeBy: sum
		sourceColumn: crm_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_marketing
		dataType: double
		formatString: 0
		lineageTag: 328ed236-1d4d-4f62-93f9-67343b9bab44
		summarizeBy: sum
		sourceColumn: crm_complt_marketing

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: 613e63ab-3957-4d55-97e3-dd80ae42582e
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_currency
		dataType: string
		lineageTag: 354b9eed-4b20-4502-914c-6be919b3e8a7
		summarizeBy: none
		sourceColumn: crm_currency

		annotation SummarizationSetBy = Automatic

	column crm_custom_value_1
		dataType: string
		lineageTag: b325e3f8-159a-4139-80c2-f4ea62659ec9
		summarizeBy: none
		sourceColumn: crm_custom_value_1

		annotation SummarizationSetBy = Automatic

	column crm_custom_value_2
		dataType: string
		lineageTag: fb20b56e-f861-4804-8b00-9d04b3f5b9ac
		summarizeBy: none
		sourceColumn: crm_custom_value_2

		annotation SummarizationSetBy = Automatic

	column crm_custom_value_3
		dataType: string
		lineageTag: 5f5e1f09-00dc-4c26-a98c-c4d46b1a625a
		summarizeBy: none
		sourceColumn: crm_custom_value_3

		annotation SummarizationSetBy = Automatic

	column crm_deep_link
		dataType: string
		lineageTag: 05cfe5dc-9176-41d2-bc8f-d8e3ed614fae
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	column crm_last_act_time
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5c7e8412-72f6-450c-9ba3-ed6b7c8711ef
		summarizeBy: none
		sourceColumn: crm_last_act_time

		variation Variation
			isDefault
			relationship: b4365009-db12-4b4a-ab7e-69124449ebf7
			defaultHierarchy: LocalDateTable_2d31ddae-87fe-4ec5-8896-d87a04765d4c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_leadsource
		dataType: string
		lineageTag: b6507793-1bf2-4c7d-a00d-b28b7913bff4
		summarizeBy: none
		sourceColumn: crm_leadsource

		annotation SummarizationSetBy = Automatic

	column crm_name
		dataType: string
		lineageTag: 79e788de-2051-412d-8200-cf3df4ee4551
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	column crm_owner_id
		dataType: string
		lineageTag: bd6b991f-9561-4de2-be85-0bee8e163bd1
		summarizeBy: none
		sourceColumn: crm_owner_id

		annotation SummarizationSetBy = Automatic

	column crm_stage_name
		dataType: string
		lineageTag: e4656938-bbe9-46ad-aadb-956c45e34181
		summarizeBy: none
		sourceColumn: crm_stage_name

		annotation SummarizationSetBy = Automatic

	column crm_stage_num
		dataType: int64
		formatString: 0
		lineageTag: 65b93c39-2f42-40fe-a741-b04610e837b3
		summarizeBy: sum
		sourceColumn: crm_stage_num

		annotation SummarizationSetBy = Automatic

	column crm_type
		dataType: string
		lineageTag: 430a5fb9-2142-4084-a963-b6339dcee13b
		summarizeBy: none
		sourceColumn: crm_type

		annotation SummarizationSetBy = Automatic

	column trueai_addr_city
		dataType: string
		lineageTag: e40d7176-d074-4d0c-ae30-b94c5758edb2
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	column trueai_addr_country
		dataType: string
		lineageTag: ca9a4f05-9adf-4b2a-aa5f-30564d36e24e
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	column trueai_addr_lat
		dataType: double
		lineageTag: 982db127-41e6-4eb1-945f-6df7d988b7f1
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_long
		dataType: double
		lineageTag: 088de29a-5fe4-4f25-9e10-53f6a5d20733
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_postal_code
		dataType: string
		lineageTag: 7299d1a8-1541-455d-aceb-02fb839dabc5
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column trueai_addr_rule
		dataType: int64
		formatString: 0
		lineageTag: 51bddaa5-a4cd-40cc-bed2-0d58550fad47
		summarizeBy: sum
		sourceColumn: trueai_addr_rule

		annotation SummarizationSetBy = Automatic

	column trueai_addr_state
		dataType: string
		lineageTag: 29ad86e7-f924-4bce-89de-c9564e3cc600
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	column trueai_addr_street
		dataType: string
		lineageTag: 25418c07-50cc-4637-835c-135aee79b467
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0dd848ff-b00b-4113-b2b2-3ff214292dd3
		summarizeBy: sum
		sourceColumn: trueai_booking_amt

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt_rule
		dataType: int64
		formatString: 0
		lineageTag: 554ca8fc-a26c-4a6d-8dd9-43588a45ebdb
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_rule

		annotation SummarizationSetBy = Automatic

	column trueai_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 59cdc35d-bc26-4406-895b-410b02f3cbdb
		summarizeBy: none
		sourceColumn: trueai_close_date

		variation Variation
			isDefault
			relationship: ed0a72ed-0664-4aee-950c-bd464feacd42
			defaultHierarchy: LocalDateTable_f946d803-7fe1-4e12-85ba-962286615d83.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_company_size
		dataType: string
		lineageTag: 268a37ef-e827-4ce9-b4a7-c43329dc0152
		summarizeBy: none
		sourceColumn: trueai_company_size

		annotation SummarizationSetBy = Automatic

	column trueai_company_size_rule
		dataType: int64
		formatString: 0
		lineageTag: f2d94749-9b87-4c34-9bd7-567e1523c0b6
		summarizeBy: sum
		sourceColumn: trueai_company_size_rule

		annotation SummarizationSetBy = Automatic

	column trueai_complt
		dataType: double
		lineageTag: 05b2a018-d2f5-46bd-984e-8c1d7d0f506b
		summarizeBy: sum
		sourceColumn: trueai_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_complt_contact
		dataType: double
		lineageTag: 3f30935c-ee61-4310-b564-1af485ae9b22
		summarizeBy: sum
		sourceColumn: trueai_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_complt_marketing
		dataType: double
		formatString: 0
		lineageTag: 1b759883-c0f7-4ee4-8437-c15e5711ba73
		summarizeBy: sum
		sourceColumn: trueai_complt_marketing

		annotation SummarizationSetBy = Automatic

	column trueai_creator_id
		dataType: string
		lineageTag: 54cf8b74-c048-47ef-af1b-aa98afdfdb39
		summarizeBy: none
		sourceColumn: trueai_creator_id

		annotation SummarizationSetBy = Automatic

	column trueai_discount
		dataType: double
		lineageTag: 90abccb0-2db9-460d-8757-dddf6403dbc8
		summarizeBy: sum
		sourceColumn: trueai_discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_dur
		dataType: int64
		formatString: 0
		lineageTag: 2f02e986-448a-4e27-aae1-7ac31a266f66
		summarizeBy: sum
		sourceColumn: trueai_dur

		annotation SummarizationSetBy = Automatic

	column trueai_industry
		dataType: string
		lineageTag: 35410a22-5548-4df5-8dc1-fba4ff93f30e
		summarizeBy: none
		sourceColumn: trueai_industry

		annotation SummarizationSetBy = Automatic

	column trueai_industry_conf
		dataType: double
		lineageTag: 219a06c1-7dfe-4f51-8bf4-424a3991d64b
		summarizeBy: sum
		sourceColumn: trueai_industry_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_industry_rule
		dataType: int64
		formatString: 0
		lineageTag: 45918e18-c642-4294-8359-37135937cf61
		summarizeBy: sum
		sourceColumn: trueai_industry_rule

		annotation SummarizationSetBy = Automatic

	column trueai_is_new_logo
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 473bcf62-22df-4375-930d-75c05f10697a
		summarizeBy: none
		sourceColumn: trueai_is_new_logo

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource
		dataType: string
		lineageTag: abda2696-27f8-4d81-b78f-caeab4af7e96
		summarizeBy: none
		sourceColumn: trueai_leadsource

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource_conf
		dataType: double
		lineageTag: 3215f56d-0c96-4264-8a78-1abe5702f7f3
		summarizeBy: sum
		sourceColumn: trueai_leadsource_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_leadsource_rule
		dataType: int64
		formatString: 0
		lineageTag: a1cc073d-8aed-4f29-8ac9-e30155bc3758
		summarizeBy: sum
		sourceColumn: trueai_leadsource_rule

		annotation SummarizationSetBy = Automatic

	column trueai_opp_stage_late_date
		dataType: dateTime
		formatString: General Date
		lineageTag: efbb5160-f1ba-435e-9d0a-20d8be4ce82d
		summarizeBy: none
		sourceColumn: trueai_opp_stage_late_date

		variation Variation
			isDefault
			relationship: 0d877c30-71ed-4cdc-8dc3-3dc1ea884d4d
			defaultHierarchy: LocalDateTable_7d058fa1-9bc3-4c62-9d06-e11f3fa08277.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_opp_stage_mid_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 39e03763-3094-4a0b-8d78-7907c7ebd0f0
		summarizeBy: none
		sourceColumn: trueai_opp_stage_mid_date

		variation Variation
			isDefault
			relationship: 33802dbf-8c7e-4c4c-8854-7ad895933e60
			defaultHierarchy: LocalDateTable_9740a049-2bd3-41e3-99dc-a85354f81994.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_owner_id
		dataType: string
		lineageTag: d7eae22d-928e-4b5b-95d5-afa5e71416b2
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	column trueai_pred_booking_amt
		dataType: double
		lineageTag: 865f3b1d-aeae-4e0e-bd0e-48b19c103c9e
		summarizeBy: sum
		sourceColumn: trueai_pred_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_qual_bucket
		dataType: string
		lineageTag: f9ca256f-982f-4e74-8ba4-bb9073321080
		summarizeBy: none
		sourceColumn: trueai_qual_bucket
		sortByColumn: trueai_qual_bucket_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column trueai_qual_bucket_num
		dataType: int64
		formatString: 0
		lineageTag: 45b3966e-03c2-4582-9323-719ead28155e
		summarizeBy: sum
		sourceColumn: trueai_qual_bucket_num

		annotation SummarizationSetBy = Automatic

	column trueai_sale_type
		dataType: string
		lineageTag: 07005dac-4d02-4068-91fd-dc61de938357
		summarizeBy: none
		sourceColumn: trueai_sale_type
		sortByColumn: trueai_sale_type_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column trueai_sale_type_conf
		dataType: double
		lineageTag: 215ed405-cde1-4f5c-a9a3-6cb3b58cde6e
		summarizeBy: sum
		sourceColumn: trueai_sale_type_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_vi_opp_value
		dataType: double
		lineageTag: 4e0ffca5-7d04-4f6d-8df4-1f5f7c120f07
		summarizeBy: sum
		sourceColumn: trueai_vi_opp_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_vi_post_sales_value
		dataType: double
		lineageTag: cc1327e8-0554-4a74-9372-1f9cb2938742
		summarizeBy: sum
		sourceColumn: trueai_vi_post_sales_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_vi_prospecting_value
		dataType: double
		lineageTag: 343d78c9-3b64-4f5a-9e6f-c25524c7e2c7
		summarizeBy: sum
		sourceColumn: trueai_vi_prospecting_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_vi_repeat_value
		dataType: double
		lineageTag: 42a9b5c3-43e2-4c1f-9980-03a674d24766
		summarizeBy: sum
		sourceColumn: trueai_vi_repeat_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_custom
		dataType: double
		lineageTag: 5999492c-d926-4832-98ab-554786c282fd
		summarizeBy: sum
		sourceColumn: crm_complt_custom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_as_of
		dataType: dateTime
		formatString: Long Date
		lineageTag: c7f5019a-1c24-4def-954f-0feda653998f
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 9f7f849b-0921-4bfe-91d5-4702eb109e0b
			defaultHierarchy: LocalDateTable_622b6751-c6ca-49ca-9ab8-8f2b4b9cb734.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8d15dfa8-d8b0-4f03-8ceb-085049a0275d
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 928dd265-7cd0-4ba5-abc6-37e4f8c1660f
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 6ed75488-b122-43ff-81c9-e5cb9e5ae545
			defaultHierarchy: LocalDateTable_0d867766-6cb9-46d4-92e2-f5e481d9ddc5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 62264037-ceeb-4dfe-b533-d6f672fad326
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: b6a82ba0-6c64-485e-9dc6-f4d58976beb2
			defaultHierarchy: LocalDateTable_c2b74306-a09c-41ea-961f-5ddacaea4d8b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column crm_is_closed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5eea1041-471a-407c-a0ab-e9c415cfd495
		summarizeBy: none
		sourceColumn: crm_is_closed

		annotation SummarizationSetBy = Automatic

	column crm_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 53a19397-2f50-494e-8d99-35fccf120d2b
		summarizeBy: none
		sourceColumn: crm_is_won

		annotation SummarizationSetBy = Automatic

	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 07331f49-c5ab-4cc1-a634-b12cbf861274
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: 678e9d30-5212-4cf8-b437-1dbe7f52f74b
			defaultHierarchy: LocalDateTable_670f2152-beb7-4564-ab06-7945e86e36cb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_created_from_entity
		dataType: string
		lineageTag: 742606d0-e93f-4ebc-8d08-c078da19668d
		summarizeBy: none
		sourceColumn: trueai_created_from_entity

		annotation SummarizationSetBy = Automatic

	column trueai_created_from_id
		dataType: string
		lineageTag: aa27386e-90e5-4f08-9ca3-51edf081d66a
		summarizeBy: none
		sourceColumn: trueai_created_from_id

		annotation SummarizationSetBy = Automatic

	column trueai_created_on
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4ac75f07-9bff-4eb9-955f-62f41b038c16
		summarizeBy: none
		sourceColumn: trueai_created_on

		variation Variation
			isDefault
			relationship: 774b2518-7528-4998-9d95-57015c87e28a
			defaultHierarchy: LocalDateTable_0752fb46-2abf-4378-9541-c789e0fdc007.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 54610216-0dc2-4191-b4d9-07c2600e15ca
		summarizeBy: none
		sourceColumn: trueai_is_won

		annotation SummarizationSetBy = Automatic

	column trueai_stage
		dataType: string
		lineageTag: 6d231412-b655-416f-85f6-fcd506b75399
		summarizeBy: none
		sourceColumn: trueai_stage

		annotation SummarizationSetBy = Automatic

	column trueai_prob_of_next_opp
		dataType: double
		lineageTag: e69071b7-9731-45a6-930f-86e6747e0409
		summarizeBy: sum
		sourceColumn: trueai_prob_of_next_opp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_prob_of_next_opp_explained
		dataType: string
		lineageTag: cd024a6a-cc98-4611-8f94-3556810fba3c
		summarizeBy: none
		sourceColumn: trueai_prob_of_next_opp_explained

		annotation SummarizationSetBy = Automatic

	column trueai_prob_of_win
		dataType: double
		lineageTag: e96f5ead-faa8-42cb-a0c4-25e6e468cd04
		summarizeBy: sum
		sourceColumn: trueai_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_prob_of_win_explained
		dataType: string
		lineageTag: 715a7840-1b04-49e8-b690-f96571024f67
		summarizeBy: none
		sourceColumn: trueai_prob_of_win_explained

		annotation SummarizationSetBy = Automatic

	column trueai_discount_amt
		dataType: double
		lineageTag: dd9afbc5-9311-4dbb-90fd-76e9c3596e80
		summarizeBy: sum
		sourceColumn: trueai_discount_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_discount_pct
		dataType: double
		lineageTag: d298504b-9662-4b09-9aab-80a719e715be
		summarizeBy: sum
		sourceColumn: trueai_discount_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_booking_amt_currency_rule
		dataType: int64
		formatString: 0
		lineageTag: 7b6cd046-3091-4b34-b6ea-a53f77229ffc
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_currency_rule

		annotation SummarizationSetBy = Automatic

	column trueai_is_erp
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7d9e4a19-7c94-4224-ad6f-c5331b95b036
		summarizeBy: none
		sourceColumn: trueai_is_erp

		annotation SummarizationSetBy = Automatic

	column trueai_account_id
		dataType: string
		lineageTag: 38aace67-e071-4e69-8e17-bfe4b3611c6b
		summarizeBy: none
		sourceColumn: trueai_account_id

		annotation SummarizationSetBy = Automatic

	column trueai_account_id_rule
		dataType: int64
		formatString: 0
		lineageTag: ada4f524-9e2e-49ea-8afa-8bb8d8bf6e1e
		summarizeBy: sum
		sourceColumn: trueai_account_id_rule

		annotation SummarizationSetBy = Automatic

	column trueai_account_id_conf
		dataType: double
		lineageTag: 47a16c39-3029-4312-8b23-238b97b72a29
		summarizeBy: sum
		sourceColumn: trueai_account_id_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_test
		dataType: string
		lineageTag: 8235a218-47c3-488d-94b6-f0fc6734df6a
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	column trueai_test_conf
		dataType: double
		lineageTag: c26bab90-9678-4bff-a19d-3c932528c7de
		summarizeBy: sum
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_test_rule
		dataType: string
		lineageTag: bb9e0b1e-408f-4af7-8170-f562456c840b
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	column trueai_test_debug
		dataType: string
		lineageTag: b2c5a489-baa2-4e76-9490-72ff85b96c81
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	column trueai_close_date_rule
		dataType: int64
		formatString: 0
		lineageTag: 4a805e69-9ff1-4921-9f82-d28e45171d26
		summarizeBy: sum
		sourceColumn: trueai_close_date_rule

		annotation SummarizationSetBy = Automatic

	column trueai_start_date_rule
		dataType: int64
		formatString: 0
		lineageTag: 97453820-32b1-4563-9da8-f3df29fc9a57
		summarizeBy: sum
		sourceColumn: trueai_start_date_rule

		annotation SummarizationSetBy = Automatic

	column trueai_created_on_rule
		dataType: int64
		formatString: 0
		lineageTag: c0fbf987-1837-4e35-b070-79819bf797be
		summarizeBy: sum
		sourceColumn: trueai_created_on_rule

		annotation SummarizationSetBy = Automatic

	column trueai_creator_id_rule
		dataType: int64
		formatString: 0
		lineageTag: dcbe66ad-1b7d-48af-af14-ea824512d9ba
		summarizeBy: sum
		sourceColumn: trueai_creator_id_rule

		annotation SummarizationSetBy = Automatic

	column trueai_owner_id_rule
		dataType: int64
		formatString: 0
		lineageTag: 7e8df0f3-1876-44dd-83cf-d5f5d63aa703
		summarizeBy: sum
		sourceColumn: trueai_owner_id_rule

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: e48fcd0a-3356-4007-a9e6-6d394a682b00
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: 5ebbaece-ef39-4c52-b8ff-6172a75cae84
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: c6437621-96ff-47ba-bcf9-194ddadcc939
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: d5b944c2-4b57-4489-9bd4-46eedae481f3
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: c0b6e9c7-8274-4915-8d1c-de54e2859974
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: double
		lineageTag: 1703943b-4f7a-4ea8-9e41-044d05ba67e3
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num2
		dataType: double
		lineageTag: 158a4065-a0b1-43e1-987b-408d2b323a9c
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num3
		dataType: double
		lineageTag: a955c0ad-aad2-4b12-9e60-bdbbcf47ff30
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num4
		dataType: double
		lineageTag: 253ab445-e75c-43eb-8931-0406d3bf798a
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num5
		dataType: double
		lineageTag: f8ea7d53-c480-4f9a-aa20-8c84078f9998
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num6
		dataType: double
		lineageTag: 75d92bbc-8a2a-4892-b6f6-92c3a246fff8
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num7
		dataType: double
		lineageTag: ed3a4644-5693-4232-820a-d8a7914af484
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 71b1d167-6b8d-408b-a435-68e504812741
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 190fd143-80cf-4c29-a07e-c8662f559509
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	column trueai_sale_type_num
		dataType: int64
		formatString: 0
		lineageTag: d5ad6812-4d01-47da-8e56-fcbda475547e
		summarizeBy: sum
		sourceColumn: trueai_sale_type_num

		annotation SummarizationSetBy = Automatic

	column 'col.opp_age' =
			
			var _current_date = TODAY()
			var _created_date = opps[crm_created_on]
			var res = DATEDIFF(_created_date, _current_date, DAY)
			RETURN
			res
		formatString: #" days"
		lineageTag: 7ea63bba-513e-4b40-8713-6e4bff3da1fe
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'col.trueai_opp_stages_recorded' = ```
			
			var opp_id = opps[_sys_doc_id] // get the opp i
			var res = CALCULATE(DISTINCTCOUNT(open_pipeline[trueai_stage_name]), open_pipeline[crm_opp_id] = opp_id) // distinct count # of opp_pieline values 
			RETURN res 
			```
		formatString: 0
		lineageTag: 226857c2-ca7c-42d3-aea7-98e34910b4fb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'col.trueai_days' = ```
			
			 var days = [_sys_filt_end_date] - [_sys_filt_start_date] // get days 
			 var res = if ( opps[crm_is_closed] = false , BLANK(), days ) // closed only
			 return days 
			```
		dataType: int64
		formatString: #" days"
		lineageTag: cad72a71-450b-4da8-a9d5-37b2e4ab1a83
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column crm_loss_reason
		dataType: string
		lineageTag: 1d8edd5f-2f0e-403b-8819-4223be800caa
		summarizeBy: none
		sourceColumn: crm_loss_reason

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_id
		dataType: string
		lineageTag: b68cd95a-ec03-4a4d-a7c2-84a9db8377e5
		summarizeBy: none
		sourceColumn: crm_pipeline_id

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_name
		dataType: string
		lineageTag: 098a82b7-496c-47ac-b6d3-f8daea0efa57
		summarizeBy: none
		sourceColumn: crm_pipeline_name

		annotation SummarizationSetBy = Automatic

	column trueai_loss_reason
		dataType: string
		lineageTag: 2227ec9d-5ce9-418c-b27a-316c37be4cbb
		summarizeBy: none
		sourceColumn: trueai_loss_reason

		annotation SummarizationSetBy = Automatic

	column crm_stage_id
		dataType: string
		lineageTag: b2fe47bb-23b0-42c2-964a-1654c44a999d
		summarizeBy: none
		sourceColumn: crm_stage_id

		annotation SummarizationSetBy = Automatic

	column trueai_stage_id
		dataType: string
		lineageTag: 4ca57c41-1c46-41de-89ed-fc4817a0d140
		summarizeBy: none
		sourceColumn: trueai_stage_id

		annotation SummarizationSetBy = Automatic

	column trueai_stage_name
		dataType: string
		lineageTag: 0dabd22b-ac43-4dd5-af35-1eeb3d0925ae
		summarizeBy: none
		sourceColumn: trueai_stage_name

		annotation SummarizationSetBy = Automatic

	column trueai_pipeline_name
		dataType: string
		lineageTag: 9627b322-883d-45f4-8178-4b9ab26ce3d4
		summarizeBy: none
		sourceColumn: trueai_pipeline_name

		annotation SummarizationSetBy = Automatic

	column trueai_age
		dataType: string
		lineageTag: cc25fbc2-deb6-42f0-9b30-3f4c6f7aa266
		summarizeBy: none
		sourceColumn: trueai_age

		annotation SummarizationSetBy = Automatic

	column trueai_discount_pct_tier
		dataType: string
		lineageTag: d5d56924-c4f6-4819-ab08-6cca48c59b9f
		summarizeBy: none
		sourceColumn: trueai_discount_pct_tier

		annotation SummarizationSetBy = Automatic

	column trueai_nnb_amt
		dataType: string
		lineageTag: e9f6bc83-15bd-48c0-91ec-d57c3a73a98b
		summarizeBy: none
		sourceColumn: trueai_nnb_amt

		annotation SummarizationSetBy = Automatic

	column trueai_downgrade_amt
		dataType: string
		lineageTag: bd379382-b3be-4dd3-8ef7-189895232667
		summarizeBy: none
		sourceColumn: trueai_downgrade_amt

		annotation SummarizationSetBy = Automatic

	column trueai_cross_sale_amt
		dataType: string
		lineageTag: a2b152b4-9691-4e96-8d53-7cac21ea41fe
		summarizeBy: none
		sourceColumn: trueai_cross_sale_amt

		annotation SummarizationSetBy = Automatic

	column trueai_renewal_amt
		dataType: string
		lineageTag: 5130b759-05ac-429f-b8d6-b640da10ec5c
		summarizeBy: none
		sourceColumn: trueai_renewal_amt

		annotation SummarizationSetBy = Automatic

	column trueai_expansion_amt
		dataType: string
		lineageTag: 2aa9029e-00e5-4143-b125-ff4976f53cd7
		summarizeBy: none
		sourceColumn: trueai_expansion_amt

		annotation SummarizationSetBy = Automatic

	column trueai_one_time_amt
		dataType: string
		lineageTag: 89b7956b-1362-4c1b-b5b3-94b83d51344b
		summarizeBy: none
		sourceColumn: trueai_one_time_amt

		annotation SummarizationSetBy = Automatic

	column trueai_nd_amt
		dataType: string
		lineageTag: 0ebcb086-8b02-4f52-8347-ba15c0ad5583
		summarizeBy: none
		sourceColumn: trueai_nd_amt

		annotation SummarizationSetBy = Automatic

	column trueai_arr_amt
		dataType: string
		lineageTag: 1093cd30-1cdd-48a7-8902-022cc75af8cb
		summarizeBy: none
		sourceColumn: trueai_arr_amt

		annotation SummarizationSetBy = Automatic

	column 'col.trueai_list_price_amt' = ```
			
			[trueai_booking_amt]-[trueai_discount_amt]
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d7a4f08b-42aa-4f41-8ae6-082461941af8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition opps-844b2383-8abc-4f81-b4fd-92ba5ff8a92a = m
		mode: import
		source = ```
				let
				
				    
				    dbTable = getDBTable("opps"), // get the right table
				
				
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"trueai_creator_id_rule", Int64.Type},
				{"trueai_discount", type number},
				{"trueai_discount_amt", type number},
				{"trueai_discount_pct", type number},
				{"trueai_dur", Int64.Type},
				{"trueai_industry", type text},
				{"trueai_industry_conf", type number},
				{"trueai_industry_rule", Int64.Type},
				{"trueai_is_erp", type logical},
				{"trueai_is_new_logo", type logical},
				{"trueai_is_won", type logical},
				{"trueai_leadsource", type text},
				{"trueai_leadsource_conf", type number},
				{"trueai_leadsource_rule", Int64.Type},
				{"trueai_loss_reason", type text},
				{"trueai_opp_stage_late_date", type datetime},
				{"trueai_opp_stage_mid_date", type datetime},
				{"trueai_owner_id", type text},
				{"trueai_owner_id_rule", Int64.Type},
				{"trueai_pipeline_name", type text},
				{"trueai_pred_booking_amt", type number},
				{"trueai_prob_of_next_opp", type number},
				{"trueai_prob_of_next_opp_explained", type text},
				{"trueai_prob_of_win", type number},
				{"trueai_prob_of_win_explained", type text},
				{"trueai_qual_bucket", type text},
				{"trueai_qual_bucket_num", Int64.Type},
				{"trueai_sale_type", type text},
				{"trueai_sale_type_conf", type number},
				{"trueai_stage", type text},
				{"trueai_stage_id", type text},
				{"trueai_stage_name", type text},
				{"trueai_start_date_rule", Int64.Type},
				{"trueai_test", type text},
				{"trueai_test_conf", type number},
				{"trueai_test_debug", type text},
				{"trueai_test_rule", type text},
				{"trueai_vi_opp_value", type number},
				{"trueai_vi_post_sales_value", type number},
				{"trueai_vi_prospecting_value", type number},
				{"trueai_vi_repeat_value", type number},
				{"_sys_as_of", type datetime},
				{"_sys_doc_id", type text},
				{"_sys_filt_end_date", type date},
				{"_sys_filt_start_date", type date},
				{"_sys_is_active", type logical},
				{"_sys_last_modified_on", type datetime},
				{"_sys_ssr_id", type text},
				{"crm_account_custom_value_1", type text},
				{"crm_account_custom_value_2", type text},
				{"crm_account_custom_value_3", type text},
				{"crm_account_id", type text},
				{"crm_booking_amt", type number},
				{"crm_close_date", type datetime},
				{"crm_complt", type number},
				{"crm_complt_contact", type number},
				{"crm_complt_custom", type number},
				{"crm_complt_marketing", type number},
				{"crm_created_on", type datetime},
				{"crm_creator_id", type text},
				{"crm_currency", type text},
				{"crm_custom_value_1", type text},
				{"crm_custom_value_2", type text},
				{"crm_custom_value_3", type text},
				{"crm_deep_link", type text},
				{"crm_is_closed", type logical},
				{"crm_is_won", type logical},
				{"crm_last_act_time", type datetime},
				{"crm_leadsource", type text},
				{"crm_loss_reason", type text},
				{"crm_modified_on", type datetime},
				{"crm_name", type text},
				{"crm_owner_id", type text},
				{"crm_pipeline_id", type text},
				{"crm_pipeline_name", type text},
				{"crm_stage_id", type text},
				{"crm_stage_name", type text},
				{"crm_stage_num", Int64.Type},
				{"crm_type", type text},
				{"cust_bool1", type logical},
				{"cust_bool2", type logical},
				{"cust_num1", type number},
				{"cust_num2", type number},
				{"cust_num3", type number},
				{"cust_num4", type number},
				{"cust_num5", type number},
				{"cust_num6", type number},
				{"cust_num7", type number},
				{"cust_text1", type text},
				{"cust_text2", type text},
				{"cust_text3", type text},
				{"cust_text4", type text},
				{"cust_text5", type text},
				{"trueai_account_id", type text},
				{"trueai_account_id_conf", type number},
				{"trueai_account_id_rule", Int64.Type},
				{"trueai_addr_city", type text},
				{"trueai_addr_country", type text},
				{"trueai_addr_lat", type number},
				{"trueai_addr_long", type number},
				{"trueai_addr_postal_code", type text},
				{"trueai_addr_rule", Int64.Type},
				{"trueai_addr_state", type text},
				{"trueai_addr_street", type text},
				{"trueai_booking_amt", type number},
				{"trueai_booking_amt_currency_rule", Int64.Type},
				{"trueai_booking_amt_rule", Int64.Type},
				{"trueai_close_date", type datetime},
				{"trueai_close_date_rule", Int64.Type},
				{"trueai_company_size", type text},
				{"trueai_company_size_rule", Int64.Type},
				{"trueai_complt", type number},
				{"trueai_complt_contact", type number},
				{"trueai_complt_marketing", type number},
				{"trueai_created_from_entity", type text},
				{"trueai_created_from_id", type text},
				{"trueai_created_on", type datetime},
				{"trueai_created_on_rule", Int64.Type},
				{"trueai_creator_id", type text}
				    }),
				    #"Removed Duplicates" = Table.Distinct(dbTableTyped, {"_sys_doc_id"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Duplicates", "trueai_sale_type_num", each if [trueai_sale_type] = "New Logo Sale" then 1 else if [trueai_sale_type] = "Existing Customer Sale" then 2 else if [trueai_sale_type] = "Renewal" then 3 else 4),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"trueai_sale_type_num", Int64.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

