table opps_histories
	lineageTag: e4600b56-78cb-4d7f-bd90-ef966dd38f75

	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: bab0d58c-22b8-45b7-ad3b-c99902a6b00e
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 09b3e963-3c4d-4446-acf0-cb78d7d7ba2a
			defaultHierarchy: LocalDateTable_c4f78851-cf39-4189-a587-0c14d289fc32.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 963c99cc-b314-4ed7-b985-a03cb02daae3
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 2df20986-b183-4d7e-b1fb-5f53df2d7eca
			defaultHierarchy: LocalDateTable_61fa3f69-e9c3-43a5-a7df-e7e0318117a3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1263989b-c87e-4383-9ab7-7f51e5b8c787
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 845c7361-60dc-438e-9889-30ec5c701d0b
			defaultHierarchy: LocalDateTable_175e9825-f28a-463e-a529-c2a4a07e90d3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_doc_id
		dataType: string
		lineageTag: 8431c22d-ac69-4ca1-9aa2-43a69d53bd72
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column crm_booking_amt
		dataType: double
		lineageTag: 85178d62-a976-4da9-83a1-3438511f3f3f
		summarizeBy: sum
		sourceColumn: crm_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7613064b-7c63-4c95-9971-36563a110ef0
		summarizeBy: none
		sourceColumn: crm_close_date

		variation Variation
			isDefault
			relationship: 0be475d9-4dc5-462e-a55c-f9e6f569633e
			defaultHierarchy: LocalDateTable_2a813b67-50eb-489d-b8ae-f062dc511f73.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 4bcce550-9be0-4871-aa67-0344c5e8475d
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 7394f95b-cbb0-4d5a-91a5-024a21601ec4
			defaultHierarchy: LocalDateTable_b1f98d7d-0d63-4c0b-8bbf-833ca720b7dc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: 22947e30-503d-4e25-a9e0-7faeff7b72f1
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_opp_id
		dataType: string
		lineageTag: 133ef257-df5f-471c-bd28-afba5de10b4b
		summarizeBy: none
		sourceColumn: crm_opp_id

		annotation SummarizationSetBy = Automatic

	column crm_stage_name
		dataType: string
		lineageTag: b671498c-ba59-401d-8b9c-e9ff5de75ed4
		summarizeBy: none
		sourceColumn: crm_stage_name

		annotation SummarizationSetBy = Automatic

	column crm_stage_id
		dataType: string
		lineageTag: 0e802123-8c6e-4f47-9776-8c28a0c324f8
		summarizeBy: none
		sourceColumn: crm_stage_id

		annotation SummarizationSetBy = Automatic

	column crm_stage_num
		dataType: string
		lineageTag: a9d31956-00d1-48f8-bd94-ccc95dab9ac5
		summarizeBy: none
		sourceColumn: crm_stage_num

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_id
		dataType: string
		lineageTag: 1372d9d2-0830-495c-b207-ec5ec903a211
		summarizeBy: none
		sourceColumn: crm_pipeline_id

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_name
		dataType: string
		lineageTag: 69ecdf46-edd3-472c-8cbe-a1187b5a00ed
		summarizeBy: none
		sourceColumn: crm_pipeline_name

		annotation SummarizationSetBy = Automatic

	column trueai_stage_id
		dataType: string
		lineageTag: 6cf74c58-9251-415f-bf24-70eb38f55581
		summarizeBy: none
		sourceColumn: trueai_stage_id

		annotation SummarizationSetBy = Automatic

	column trueai_stage_name
		dataType: string
		lineageTag: bcc4927a-a963-4550-b8a2-27d5b51eb510
		summarizeBy: none
		sourceColumn: trueai_stage_name

		annotation SummarizationSetBy = Automatic

	column trueai_pipeline_name
		dataType: string
		lineageTag: d740f8ff-3d00-462c-93f1-7fa2b9ba0325
		summarizeBy: none
		sourceColumn: trueai_pipeline_name

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt
		dataType: double
		lineageTag: 894124c2-ac3a-483c-b8e2-57c869d343e7
		summarizeBy: sum
		sourceColumn: trueai_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_booking_amt_currency_rule
		dataType: int64
		formatString: 0
		lineageTag: b1618f63-3ecd-4d56-9e2c-043c6d02d305
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_currency_rule

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt_rule
		dataType: int64
		formatString: 0
		lineageTag: fecc5b4b-e632-4978-82c4-ae5188de6606
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_rule

		annotation SummarizationSetBy = Automatic

	column trueai_can_be_excluded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9b823512-6573-471d-b74d-3cbba37d5953
		summarizeBy: none
		sourceColumn: trueai_can_be_excluded

		annotation SummarizationSetBy = Automatic

	column trueai_current_prob_of_win
		dataType: double
		lineageTag: 35443206-32f6-4bee-80e1-4d177922c454
		summarizeBy: sum
		sourceColumn: trueai_current_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_is_closed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 74bbe869-7a99-404e-81b3-9647f33c22b3
		summarizeBy: none
		sourceColumn: trueai_is_closed

		annotation SummarizationSetBy = Automatic

	column trueai_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 130c2468-4df7-4700-b511-8dca1a5c9831
		summarizeBy: none
		sourceColumn: trueai_is_won

		annotation SummarizationSetBy = Automatic

	column trueai_stage
		dataType: string
		lineageTag: 37247489-4963-403b-a265-84b95de62121
		summarizeBy: none
		sourceColumn: trueai_stage

		annotation SummarizationSetBy = Automatic

	column trueai_step_sequence
		dataType: int64
		formatString: 0
		lineageTag: a0f7dbce-e055-4bfd-8f3e-36cdd4e16578
		summarizeBy: sum
		sourceColumn: trueai_step_sequence

		annotation SummarizationSetBy = Automatic

	column trueai_owner_prep_factor
		dataType: double
		lineageTag: 4cfeea09-6615-4728-91f3-d5846e3705b6
		summarizeBy: sum
		sourceColumn: trueai_owner_prep_factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_owner_act_capt_lvl
		dataType: double
		lineageTag: 122fe2eb-37a1-42ef-b8d1-93bebf138ff9
		summarizeBy: sum
		sourceColumn: trueai_owner_act_capt_lvl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_owner_act_capt_lvl_conf
		dataType: double
		lineageTag: fe83bcc2-d8d7-420b-bd4d-b0e48ed4cf95
		summarizeBy: sum
		sourceColumn: trueai_owner_act_capt_lvl_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_count
		dataType: int64
		formatString: 0
		lineageTag: a4e7085a-dbed-452a-b0b2-d02995423c7d
		summarizeBy: sum
		sourceColumn: trueai_act_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_auto_email_count
		dataType: int64
		formatString: 0
		lineageTag: 70efb13e-97c8-4f12-92a6-194ad5e7f27c
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_auto_email_dur
		dataType: double
		lineageTag: 87c49e83-313f-4913-be23-cea3a06c40b7
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_auto_email_eng_count
		dataType: int64
		formatString: 0
		lineageTag: c2f7eb94-eed0-44f8-8c77-d76838f5eaff
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_call_count
		dataType: int64
		formatString: 0
		lineageTag: 3c135c02-476d-4486-b47f-55753ab11377
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_call_dur
		dataType: double
		lineageTag: 74dbbf5e-7740-4222-a072-9fe27f085487
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_call_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 0d000e09-0389-4796-b62e-ce8653e9d500
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_dur
		dataType: double
		lineageTag: 0808b0a8-f4e1-47fa-9b2e-577d34b0830d
		summarizeBy: sum
		sourceColumn: trueai_act_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_email_count
		dataType: int64
		formatString: 0
		lineageTag: cd864493-483d-4ae8-a966-4bc3e2de0d57
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_email_dur
		dataType: double
		lineageTag: 22133ef2-507f-45a4-bba0-185b0784af87
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_email_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 8343af8a-3ace-4546-ac82-1cb8b382ea29
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_eng_count
		dataType: int64
		formatString: 0
		lineageTag: abdfb172-12ca-4e4b-a1b6-f7d1a4f6e70a
		summarizeBy: sum
		sourceColumn: trueai_act_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_eng_dur
		dataType: double
		lineageTag: fccbfac5-845a-429e-9f6e-bfa2ef280318
		summarizeBy: sum
		sourceColumn: trueai_act_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_meeting_count
		dataType: int64
		formatString: 0
		lineageTag: 53896e45-d3c1-4f46-9993-63ce0e9e8cc8
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_meeting_dur
		dataType: double
		lineageTag: c41a2d59-50cf-480d-8446-6a61ddfb4841
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_meeting_eng_count
		dataType: int64
		formatString: 0
		lineageTag: c2889060-fdeb-4d77-8a6f-4d14b0de08dc
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_nd_count
		dataType: int64
		formatString: 0
		lineageTag: edc93f20-9c7f-4a6a-bc19-6089f0186fb6
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_nd_dur
		dataType: double
		lineageTag: 26ff1c1f-6a85-4789-b71d-84e60e5ff45d
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_nd_eng_count
		dataType: int64
		formatString: 0
		lineageTag: da3fce38-c33e-46e0-a9d4-7a27463ce9fe
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_no_interaction_count
		dataType: int64
		formatString: 0
		lineageTag: e393c4e0-ae93-4588-925b-9b3a01bc0088
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_no_interaction_dur
		dataType: double
		lineageTag: 5cea9b6b-9ce0-4a3a-960b-324cf173ef62
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_no_interaction_eng_count
		dataType: int64
		formatString: 0
		lineageTag: ad4e174c-c945-4f8f-bd01-19320e4b6131
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_social_count
		dataType: int64
		formatString: 0
		lineageTag: 9448d744-8c56-47bf-add1-417c5130c846
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_social_dur
		dataType: double
		lineageTag: 92b38fa1-edb0-44fc-acbd-a7874a6afc37
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_social_eng_count
		dataType: int64
		formatString: 0
		lineageTag: c447f8d3-e227-4e1a-9e93-4a127f39e2e3
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_adj_dur
		dataType: double
		lineageTag: c5e72387-3251-4dfb-bb58-8b52fc57d733
		summarizeBy: sum
		sourceColumn: trueai_act_adj_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_adj_eng_dur
		dataType: double
		lineageTag: 6e8e9b5d-8995-4d8d-88ee-427d96ac10df
		summarizeBy: sum
		sourceColumn: trueai_act_adj_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_adj_dur_rule
		dataType: int64
		formatString: 0
		lineageTag: ba9d752a-eedc-498e-8b02-6bf1bb6fe547
		summarizeBy: sum
		sourceColumn: trueai_act_adj_dur_rule

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: bf98b2f6-84cc-48ce-bed1-001dc78461f3
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: 92121d4a-b78b-43e1-972c-2b4c6e151811
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: 6986760b-8969-4d1a-9f70-a5475e96b9c7
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: 2a60f69c-71d3-4d03-8045-1795b2c1d63c
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: 11f57329-3d69-4346-b21f-ad83b3b03783
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: double
		lineageTag: 58dd297b-9521-4ce2-9233-75576fabf522
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num2
		dataType: double
		lineageTag: a4dc5198-4fce-4cf0-bfdb-4f302ca648ea
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num3
		dataType: double
		lineageTag: 9e7a088d-635e-40b6-b5b5-c5b2add6dd8f
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num4
		dataType: double
		lineageTag: 744d5160-40d7-45b2-9212-b222872b60e8
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num5
		dataType: double
		lineageTag: 4152f344-9387-4dd5-af5c-4094a36a7cc8
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num6
		dataType: double
		lineageTag: 0bacb883-1192-4b8e-be37-6431dc53d76b
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num7
		dataType: double
		lineageTag: b362d327-9102-4f3f-9e68-bfcceba7527b
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cf03edd0-7703-4ee5-be6a-1d9c2bb65bbb
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 75b565b2-64fc-4e89-b64f-d5cb9da9293d
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	partition opps_histories = m
		mode: import
		source =
				let
				
				
				
				    dbTable = getDBTable("opps_histories"), // get the right table
				
				     dbTableTyped = Table.TransformColumnTypes(dbTable,{
				       {"_sys_as_of", type datetime},
				{"_sys_doc_id", type text},
				{"_sys_filt_end_date", type date},
				{"_sys_filt_start_date", type date},
				{"crm_booking_amt", type number},
				{"crm_close_date", type datetime},
				{"crm_created_on", type datetime},
				{"crm_creator_id", type text},
				{"crm_opp_id", type text},
				{"crm_pipeline_id", type text},
				{"crm_pipeline_name", type text},
				{"crm_stage_id", type text},
				{"crm_stage_name", type text},
				{"crm_stage_num", type text},
				{"cust_bool1", type logical},
				{"cust_bool2", type logical},
				{"cust_num1", type number},
				{"cust_num2", type number},
				{"cust_num3", type number},
				{"cust_num4", type number},
				{"cust_num5", type number},
				{"cust_num6", type number},
				{"cust_num7", type number},
				{"cust_text1", type text},
				{"cust_text2", type text},
				{"cust_text3", type text},
				{"cust_text4", type text},
				{"cust_text5", type text},
				{"trueai_act_adj_dur", type number},
				{"trueai_act_adj_dur_rule", Int64.Type},
				{"trueai_act_adj_eng_dur", type number},
				{"trueai_act_count", Int64.Type},
				{"trueai_act_dur", type number},
				{"trueai_act_eng_count", Int64.Type},
				{"trueai_act_eng_dur", type number},
				{"trueai_act_type_auto_email_count", Int64.Type},
				{"trueai_act_type_auto_email_dur", type number},
				{"trueai_act_type_auto_email_eng_count", Int64.Type},
				{"trueai_act_type_call_count", Int64.Type},
				{"trueai_act_type_call_dur", type number},
				{"trueai_act_type_call_eng_count", Int64.Type},
				{"trueai_act_type_email_count", Int64.Type},
				{"trueai_act_type_email_dur", type number},
				{"trueai_act_type_email_eng_count", Int64.Type},
				{"trueai_act_type_meeting_count", Int64.Type},
				{"trueai_act_type_meeting_dur", type number},
				{"trueai_act_type_meeting_eng_count", Int64.Type},
				{"trueai_act_type_nd_count", Int64.Type},
				{"trueai_act_type_nd_dur", type number},
				{"trueai_act_type_nd_eng_count", Int64.Type},
				{"trueai_act_type_no_interaction_count", Int64.Type},
				{"trueai_act_type_no_interaction_dur", type number},
				{"trueai_act_type_no_interaction_eng_count", Int64.Type},
				{"trueai_act_type_social_count", Int64.Type},
				{"trueai_act_type_social_dur", type number},
				{"trueai_act_type_social_eng_count", Int64.Type},
				{"trueai_booking_amt", type number},
				{"trueai_booking_amt_currency_rule", Int64.Type},
				{"trueai_booking_amt_rule", Int64.Type},
				{"trueai_can_be_excluded", type logical},
				{"trueai_current_prob_of_win", type number},
				{"trueai_is_closed", type logical},
				{"trueai_is_won", type logical},
				{"trueai_owner_act_capt_lvl", type number},
				{"trueai_owner_act_capt_lvl_conf", type number},
				{"trueai_owner_prep_factor", type number},
				{"trueai_pipeline_name", type text},
				{"trueai_stage", type text},
				{"trueai_stage_id", type text},
				{"trueai_stage_name", type text},
				{"trueai_step_sequence", Int64.Type}
				})
				in
				    dbTableTyped

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

