/// CRM entity for opportunity records enriched with TrueAI predictive insights.
table opps
	lineageTag: 94b5d4f0-c14b-4b61-8e6f-fc611c85e6de

	/// Measure meas.opps_count.
	measure 'meas.opps_count' = CALCULATE(Count(opps[_sys_doc_id]))  // count of opportunity
		formatString: #,0
		displayFolder: _success_metrics
		lineageTag: 2cc843ff-f70c-4756-bc7f-55b6fe32f6b0

	/// Measure meas.opps_won_amt.
		annotation AgentPurpose = "Tracks opportunities count."
		annotation AgentLogic = "Counts rows using opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_won_amt' = CALCULATE(SUM(opps[trueai_booking_amt]),opps[trueai_is_won] = True ) // get the won opps  booking amount
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: dba34eb5-a79e-4e3d-83c2-2494b57fe4d4

		annotation PBI_FormatHint = {"currencyCulture":""}

	/// Measure meas.opps_won_count.
		annotation AgentPurpose = "Tracks opportunities won amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opps_won_count' = CALCULATE(Count(opps[_sys_doc_id]),opps[trueai_is_won] = True )// count of won opps
		formatString: #,0
		displayFolder: _success_metrics
		lineageTag: d06a26ea-8130-4af3-99b3-4a9e2d505033

	/// Measure meas.opps_lost_count.
		annotation AgentPurpose = "Tracks opportunities won count."
		annotation AgentLogic = "Counts rows using opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_lost_count' = CALCULATE(Count(opps[_sys_doc_id]),opps[trueai_is_won] = False ) // get the lost opps count
		formatString: #,0
		displayFolder: _success_metrics
		lineageTag: 8a99d981-2d57-4959-a3a1-1438b9c03dc9

	/// Measure meas.opps_won_new_logo_existing_cust_count.
		annotation AgentPurpose = "Tracks opportunities lost count."
		annotation AgentLogic = "Counts rows using opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_won_new_logo_existing_cust_count' = ```
			
			CALCULATE(
			    Count(opps[_sys_doc_id]),           // count of won opps for step new logo and existing customer 
			    opps[trueai_is_won] = True,
			    ssr_history[step_name] in {"New Logo Selling", "Existing Customer Selling"}
			)
			```
		formatString: #,0
		displayFolder: _success_metrics
		lineageTag: d581aaf4-aff3-4ab8-ac67-5e6ec53b0421

	/// Measure meas.opps_new_logo_existing_customer_selling_won_amt.
		annotation AgentPurpose = "Tracks opportunities won new logo existing customer count."
		annotation AgentLogic = "Counts rows using opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id], opps[trueai_is_won], ssr_history[step_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_new_logo_existing_customer_selling_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			    ssr_history[step_name] in {"New Logo Selling", "Existing Customer Selling"}
			    ) 
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: 7514faf0-42d0-4b93-ae3c-94eceb969fcd

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opps_existing_customer_selling_won_amt.
		annotation AgentPurpose = "Tracks opportunities new logo existing customer selling won amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won], ssr_history[step_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opps_existing_customer_selling_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			     ssr_history[step_name] in {"Existing Customer Selling"}
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 111331cb-f7bd-4425-b319-a1c0b7cdd742

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opps_new_logo_selling_won_amt.
		annotation AgentPurpose = "Tracks opportunities existing customer selling won amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won], ssr_history[step_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_new_logo_selling_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			    ssr_history[step_name] = "New Logo Selling"
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 9eab312a-8420-4bdd-ab53-bf08169e77e5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opps_post_sales_support_won_amt.
		annotation AgentPurpose = "Tracks opportunities new logo selling won amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won], ssr_history[step_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_post_sales_support_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			     ssr_history[step_name] in {"Post-Sales Support"}
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 6fec311e-00d4-437b-b8e5-82a3661b84be

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opps_prospecting_won_amt.
		annotation AgentPurpose = "Tracks opportunities post sales support won amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won], ssr_history[step_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_prospecting_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			     ssr_history[step_name] in {"Prospecting"}
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: c0905b74-1adb-4d7d-8437-3d27281bc94b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opps_all_step_won_amt.
		annotation AgentPurpose = "Tracks opportunities prospecting won amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won], ssr_history[step_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_all_step_won_amt' = ```
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),              // get the won opps  booking amount for new logo and existing customer selling step
			    opps[trueai_is_won] = True,
			     ssr_history[step_name] in {"New Logo Selling", "Prospecting", "Existing Customer Selling", "Post-Sales Support"}
			    ) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: e4c8572b-5411-4add-9f95-1ad840289871

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opps_trueai_booking_amt.
		annotation AgentPurpose = "Tracks opportunities all step won amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won], ssr_history[step_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_trueai_booking_amt' = ```
			
			
			CALCULATE(
			    SUM(opps[trueai_booking_amt]),
			    FILTER(
			        opps,
			        COUNTROWS(RELATEDTABLE(opp_line_items)) > 0     // get the opps booking amt  
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: 20fc4bb7-bc67-44ca-be7d-258a4215b929

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opp_line_items_trueai_booking_amt.
		annotation AgentPurpose = "Tracks opportunities trueai booking amount."
		annotation AgentLogic = "Counts rows using opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opp_line_items_trueai_booking_amt' =
			
			CALCULATE(
			    SUM(opp_line_items[trueai_total_price]),
			    RELATEDTABLE(opps)
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 7fc77c41-4348-493f-aefa-925c01369030

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opp_book_amt_opp_line_book_amt_diff.
		annotation AgentPurpose = "Tracks opportunity line items trueai booking amount."
		annotation AgentLogic = "Sums opp_line_items[trueai_total_price] under filters."
		annotation AgentDependencies = "Columns: opp_line_items[trueai_total_price]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_book_amt_opp_line_book_amt_diff' =
			
			var opps_amt = [meas.opps_trueai_booking_amt]   // get the opps booking amt
			var oli_amt = [meas.opp_line_items_trueai_booking_amt]          // get the oli booking amt
			var res  = opps_amt - oli_amt
			
			RETURN
			res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 9b5b3012-7465-4d5d-8268-e028e13a1c72

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opps_crm_booking_amt.
		annotation AgentPurpose = "Tracks opportunity book amount opportunity line book amount diff."
		annotation AgentLogic = "Derived from model references under current filters."
		annotation AgentDependencies = "Measures: [meas.opp_line_items_trueai_booking_amt], [meas.opps_trueai_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_crm_booking_amt' =
			
			CALCULATE(
			    SUM(
			        opps[crm_booking_amt]
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: 3c033b02-a215-4b6c-a54f-4391f82c7cb0

	/// Measure meas.open_opps_is_open.
		annotation AgentPurpose = "Tracks opportunities CRM booking amount."
		annotation AgentLogic = "Sums opps[crm_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[crm_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.open_opps_is_open' = ```
			
			var  asof_date = date(2024,1,1) // the "current" date
				
			// filter down only open opps and associated history steps for that period (include anything started on or before the as if date and not finished on as of date
			var res = CALCULATE(
			    DISTINCTCOUNT(opps[_sys_doc_id]), 
			    opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date 
			)
			return res 
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 386df656-540e-4d43-90bf-29fe8a75c043

	/// Measure meas.open_opps_order.
		annotation AgentPurpose = "Tracks open opportunities is open."
		annotation AgentLogic = "Counts distinct values in opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id], opps[_sys_filt_end_date], opps[_sys_filt_start_date]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.open_opps_order' = ```
			
			
			
				// get th date we care about 
				var  asof_date = date(2024,1,1) // the "current" date
				
				// filter down only open opps and associated history steps for that period (include anything started on or before the as if date and not finished on as of date
				var tbl_curr_open_opps= CALCULATETABLE((opps),  opps[_sys_doc_id] <> "123"   && opps[trueai_stage] <> "123"   && opps[crm_stage_name] <> "123"  && opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date )
			
			
			    // wnsure that end date is unique otherwise weird results
				var tbl_curr_open_opps_unique_end_date = ADDCOLUMNS(tbl_curr_open_opps,
						"oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(00, "00")
				)
					
				// determine the number of prior steps present for the same opps
				var tbl_curr_open_opps_prior_oh_entries = 
				ADDCOLUMNS(
			    tbl_curr_open_opps_unique_end_date,
			    "opp_id_count", 
			    VAR CurrentOppID = (opps[_sys_doc_id])
				var tblTemp = tbl_curr_open_opps_unique_end_date
			    RETURN COUNTX(filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID &&  opps[_sys_filt_end_date] <= asof_date  ),[_sys_doc_id] ))
			
			    var oh_cnt = MAXx(tbl_curr_open_opps_prior_oh_entries, [opp_id_count])
			
			    return oh_cnt
			
			
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: f94ab53f-b321-4774-ade9-7010b94d9687

	/// Measure meas.open_opps_rec.
		annotation AgentPurpose = "Tracks open opportunities order."
		annotation AgentLogic = "Counts rows using opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id], opps[trueai_stage], opps[crm_stage_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.open_opps_rec' = ```
			
				var  asof_date = date(2024,1,1) // the "current" date
				
				// filter down only open opps and associated history steps for that period (include anything started on or before the as if date and not finished on as of date
				var tbl_curr_open_opps= CALCULATETABLE(opps, opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date )
			
			
			
			var res  = countx(tbl_curr_open_opps, IF( LEFT([_sys_doc_id], 1) = "A", [_sys_doc_id], blank()) )
			return res 
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 8896c5d8-5860-4419-9167-539af4c288e4

	/// Measure meas.open_opps_step_by_step.
		annotation AgentPurpose = "Tracks open opportunities rec."
		annotation AgentLogic = "Counts rows using opps[_sys_filt_end_date] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_filt_end_date], opps[_sys_filt_start_date]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.open_opps_step_by_step' = ```
			
			
			var  asof_date = date(2024,1,1) // the "current" date
			var ff =  CALCULATETABLE(opps)
			var tbl_curr_open_opps= FIlter((ff),  opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date )
			
			
			    // wnsure that end date is unique otherwise weird results
				var tbl_curr_open_opps_unique_end_date = ADDCOLUMNS(tbl_curr_open_opps,
						"oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(00, "00")
			            // "oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(opps[_trueai_step_sequence], "00")
				)
					
				// determine the number of prior steps present for the same opps
				var tbl_curr_open_opps_prior_oh_entries = 
				ADDCOLUMNS(
			    tbl_curr_open_opps_unique_end_date,
			    "oh_doc_id", 
			    VAR CurrentOppID = (opps[_sys_doc_id])
				var tblTemp = tbl_curr_open_opps_unique_end_date
			    var doc_id =  MAXX(TOPN(1,filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID &&  opps[_sys_filt_end_date] <= asof_date  ), opps[_sys_filt_end_date],FALSE), opps[_sys_doc_id])
			    var doc_id2 =  MAXX(TOPN(1,filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID  ), opps[_sys_filt_end_date],True), opps[_sys_doc_id])
			    var res_doc_id =If (doc_id = BLANK(), doc_id2, doc_id)
			    RETURN res_doc_id)
			
			
			
			    var filter_tbl = FILTER(tbl_curr_open_opps_prior_oh_entries, [oh_doc_id] =[_sys_doc_id])
			
			    var res =    CALCULATE(count(opps[_sys_doc_id]), filter_tbl )
			    return res
			
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 5c8c0dc1-4e98-4864-84aa-d8e220345f38

	/// Measure meas.open_opps_step_by_step_amt.
		annotation AgentPurpose = "Tracks open opportunities step by step."
		annotation AgentLogic = "Counts rows using opps[_sys_filt_end_date] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_filt_end_date], opps[_sys_filt_start_date], opps[_trueai_step_sequence]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.open_opps_step_by_step_amt' =
			
			
			var tbl = filter((opps), LEFT(opps[_sys_doc_id],1) = "B")
			
			var res = CALCULATE(sum(opps[trueai_booking_amt]),tbl)
			
			return res
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _open_opps_pipeline
		lineageTag: 97534504-33cc-4e7a-bf25-44005419fd32

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.open_opps_step_by_step_slicer.
		annotation AgentPurpose = "Tracks open opportunities step by step amount."
		annotation AgentLogic = "Sums opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id], opps[trueai_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.open_opps_step_by_step_slicer' = ```
			
			
			
			var  asof_date = date(2024,1,1) // the "current" date
			var tbl_curr_open_opps =  CALCULATETABLE(opps , opps[_sys_doc_id] <> "abc" && opps[_sys_doc_id] <> "abc" && opps[_sys_filt_end_date] >= asof_date &&  opps[_sys_filt_start_date] < asof_date )
			
			
			    // wnsure that end date is unique otherwise weird results
				var tbl_curr_open_opps_unique_end_date = ADDCOLUMNS(tbl_curr_open_opps,
						"oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(00, "00")
			            // "oh_end_date", FORMAT(opps[_sys_filt_end_date], "YYYYMMDD") & "-" &  FORMAT(open_opps[oh_trueai_step_sequence], "00")
				)
					
				// determine the number of prior steps present for the same opps
				var tbl_curr_open_opps_prior_oh_entries = 
				ADDCOLUMNS(
			    tbl_curr_open_opps_unique_end_date,
			    "oh_doc_id", 
			    VAR CurrentOppID = (opps[_sys_doc_id])
				var tblTemp = tbl_curr_open_opps_unique_end_date
			    var doc_id =  MAXX(TOPN(1,filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID &&  opps[_sys_filt_end_date] <= asof_date  ), opps[_sys_filt_end_date],FALSE), opps[_sys_doc_id])
			    var doc_id2 =  MAXX(TOPN(1,filter(tblTemp,  opps[_sys_doc_id] = CurrentOppID  ), opps[_sys_filt_end_date],True), opps[_sys_doc_id])
			    var res_doc_id =If (doc_id = BLANK(), doc_id2, doc_id)
			    RETURN res_doc_id)
			
			
			
			    var filter_tbl = FILTER(tbl_curr_open_opps_prior_oh_entries, [oh_doc_id] =[_sys_doc_id])
			
			    var res =    MAXX(filter_tbl,  [oh_doc_id])
			    return res
			
			```
		displayFolder: _open_opps_pipeline
		lineageTag: d6a78e90-d5b6-4c05-8a4a-81b5971753f0

	/// Measure meas.ssr_history_opps_is_open.
		annotation AgentPurpose = "Tracks open opportunities step by step slicer."
		annotation AgentLogic = "Returns an extreme value from opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id], opps[_sys_filt_end_date], opps[_sys_filt_start_date]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.ssr_history_opps_is_open' = ```
			
			var  asof_date = [meas.sel_date] // the "current" date
				
			// filter down only open opps and associated history steps for that period (include anything started on or before the as if date and not finished on as of date
			var res = CALCULATE(
			    count(opps[_sys_doc_id]), 
			    opps[_sys_filt_end_date] > asof_date &&  opps[_sys_filt_start_date] < asof_date 
			)
			return res 
			```
		formatString: 0
		displayFolder: _opps
		lineageTag: 10a98a67-885b-4ca7-aa63-5dd5d2e57d1b

	/// Measure meas.total_opp_count.
		annotation AgentPurpose = "Tracks SSR history opportunities is open."
		annotation AgentLogic = "Counts rows using opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Measures: [meas.sel_date]; Columns: opps[_sys_doc_id], opps[_sys_filt_end_date], opps[_sys_filt_start_date]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.total_opp_count' = count(opps[_sys_doc_id])
		formatString: 0
		displayFolder: _opps
		lineageTag: d17e8206-08e5-44bc-bc7a-e2ebbf39d72c

	/// Measure meas.opps_name.
		annotation AgentPurpose = "Tracks total opportunity count."
		annotation AgentLogic = "Counts rows using opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_name' =
			CALCULATE(
			    MAX(opps[crm_name])
			)
		lineageTag: ca7bd717-4604-47eb-963c-306b7343bb15

	/// Measure meas.opps_booking_lost_amt.
		annotation AgentPurpose = "Tracks opportunities name."
		annotation AgentLogic = "Returns an extreme value from opps[crm_name] under filters."
		annotation AgentDependencies = "Columns: opps[crm_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_booking_lost_amt' = CALCULATE(SUM(opps[trueai_booking_amt]),opps[trueai_is_won] = False ) // get the lost opps  booking amount
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: 1ffbc42c-1acf-476e-8a06-e9f51390f25f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.opps_avg_deal_size_amt.
		annotation AgentPurpose = "Tracks opportunities booking lost amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opps_avg_deal_size_amt' = CALCULATE(Average(opps[trueai_booking_amt]), opps[trueai_booking_amt] > 0 )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _success_metrics
		lineageTag: 415c9aee-bf6f-4607-9601-ebe0db8d3162

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.count_of_crm_deep_link.
		annotation AgentPurpose = "Tracks opportunities average deal size amount."
		annotation AgentLogic = "Averages opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.count_of_crm_deep_link' =
			
			DISTINCTCOUNT(opps[crm_deep_link])
		formatString: 0
		lineageTag: 212bd76d-4e51-41b4-ba2f-ea7b7160fc31

	/// Measure meas.opps_cust_num1.
		annotation AgentPurpose = "Tracks count of CRM deep link."
		annotation AgentLogic = "Counts distinct values in opps[crm_deep_link] under filters."
		annotation AgentDependencies = "Columns: opps[crm_deep_link]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_cust_num1' =
			
			SUM(opps[cust_num1])
		displayFolder: _opps_verification
		lineageTag: 52f7557f-90ac-41af-8fa1-3f5be2fac8a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_cust_num2.
		annotation AgentPurpose = "Tracks opportunities customer num1."
		annotation AgentLogic = "Sums opps[cust_num1] under filters."
		annotation AgentDependencies = "Columns: opps[cust_num1]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_cust_num2' =
			
			SUM(opps[cust_num2])
		displayFolder: _opps_verification
		lineageTag: 0e1671dd-07af-4b69-864a-e3d37e2f37bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_cust_num3.
		annotation AgentPurpose = "Tracks opportunities customer num2."
		annotation AgentLogic = "Sums opps[cust_num2] under filters."
		annotation AgentDependencies = "Columns: opps[cust_num2]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_cust_num3' =
			
			SUM(opps[cust_num3])
		displayFolder: _opps_verification
		lineageTag: 4c3ed9b3-6d46-4b41-8e94-7092d0cc5c0b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_cust_num4.
		annotation AgentPurpose = "Tracks opportunities customer num3."
		annotation AgentLogic = "Sums opps[cust_num3] under filters."
		annotation AgentDependencies = "Columns: opps[cust_num3]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_cust_num4' =
			
			SUM(opps[cust_num4])
		displayFolder: _opps_verification
		lineageTag: f5381680-13e5-4c8d-b8e5-8bc82968b744

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_cust_num5.
		annotation AgentPurpose = "Tracks opportunities customer num4."
		annotation AgentLogic = "Sums opps[cust_num4] under filters."
		annotation AgentDependencies = "Columns: opps[cust_num4]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_cust_num5' =
			
			SUM(opps[cust_num5])
		displayFolder: _opps_verification
		lineageTag: c92f1116-77c7-483c-8af8-925d042d1abf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_cust_num6.
		annotation AgentPurpose = "Tracks opportunities customer num5."
		annotation AgentLogic = "Sums opps[cust_num5] under filters."
		annotation AgentDependencies = "Columns: opps[cust_num5]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_cust_num6' =
			
			SUM(opps[cust_num6])
		displayFolder: _opps_verification
		lineageTag: 5ee9da03-25c8-4b34-837e-90be69bf79ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_cust_num7.
		annotation AgentPurpose = "Tracks opportunities customer num6."
		annotation AgentLogic = "Sums opps[cust_num6] under filters."
		annotation AgentDependencies = "Columns: opps[cust_num6]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_cust_num7' =
			
			SUM(opps[cust_num7])
		displayFolder: _opps_verification
		lineageTag: 7f545910-d104-48da-ab5c-7e6bdf38eb9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.won_amt.
		annotation AgentPurpose = "Tracks opportunities customer num7."
		annotation AgentLogic = "Sums opps[cust_num7] under filters."
		annotation AgentDependencies = "Columns: opps[cust_num7]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.won_amt' = CALCULATE(sum(opps[trueai_booking_amt]), opps[trueai_is_won] = true)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 79ef7551-1b06-4a8a-8b63-141ca9196a8c

	/// Measure meas.won_count.
		annotation AgentPurpose = "Tracks won amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.won_count' = CALCULATE(count(opps[trueai_booking_amt]), opps[trueai_is_won] = true)
		formatString: #,0
		displayFolder: _opps
		lineageTag: ec154535-f996-4fb0-a39a-ee15e2abb37c

	/// Measure meas.opps_booking_amt_total.
		annotation AgentPurpose = "Tracks won count."
		annotation AgentLogic = "Counts rows using opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_booking_amt_total' = ```
			
			CALCULATE(
			    [meas.opps_booking_amt],
			    ALLSELECTED() 
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 3e4fd190-bb25-4c89-a94b-61cc9b045123

	/// Measure meas.lost_count.
		annotation AgentPurpose = "Tracks opportunities booking amount total."
		annotation AgentLogic = "Derived from model references under current filters."
		annotation AgentDependencies = "Measures: [meas.opps_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.lost_count' = CALCULATE(count(opps[trueai_booking_amt]), opps[trueai_is_won] = false)
		formatString: #,0
		displayFolder: _opps
		lineageTag: 00e5941e-43c3-4a97-92c3-a7760510aba7

	/// Measure meas.opps_booking_amt_avg.
		annotation AgentPurpose = "Tracks lost count."
		annotation AgentLogic = "Counts rows using opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_booking_amt_avg' = CALCULATE(AVERAGE((opps[trueai_booking_amt])))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 4a249f2a-182f-4d9d-a156-f5a27543751b

	/// Measure meas.opps_sales_cycle_avg_days.
		annotation AgentPurpose = "Tracks opportunities booking amount average."
		annotation AgentLogic = "Averages opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opps_sales_cycle_avg_days' = ```
			
			var res = CALCULATE(AVERAGE(opps[col.trueai_days]))
			return res 
			```
		formatString: #,##0" Days"
		displayFolder: _opps
		lineageTag: 575eeaba-caa4-408c-9594-805b91564343

		annotation PBI_FormatHint = {"isCustom":true}

	/// Measure meas.lost_amt.
		annotation AgentPurpose = "Tracks opportunities sales cycle average days."
		annotation AgentLogic = "Averages opps[col.trueai_days] under filters."
		annotation AgentDependencies = "Columns: opps[col.trueai_days]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.lost_amt' = CALCULATE(sum(opps[trueai_booking_amt]), opps[trueai_is_won] = false)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: bf734b04-1e82-434c-8912-c972ddb30ac3

	/// Measure meas.opps_lost_amt_in_stage_pct.
		annotation AgentPurpose = "Tracks lost amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opps_lost_amt_in_stage_pct' = DIVIDE([meas.opps_booking_lost_amt],[meas.opps_booking_amt])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _success_metrics
		lineageTag: 8ade373a-56e3-49bd-8f59-3c84379ba6f8

	/// Measure meas.opps_booking_amt.
		annotation AgentPurpose = "Tracks opportunities lost amount in stage percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opps_booking_amt], [meas.opps_booking_lost_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_booking_amt' = CALCULATE( sum(opps[trueai_booking_amt]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 4529b0ce-1347-4c49-81c8-a51245ee0275

	/// Measure meas.opps_booking_lost_amt_pct.
		annotation AgentPurpose = "Tracks opportunities booking amount."
		annotation AgentLogic = "Sums opps[trueai_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opps_booking_lost_amt_pct' = DIVIDE([meas.opps_booking_lost_amt], [meas.opps_booking_amt_total])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _success_metrics
		lineageTag: 585994fc-6fc1-4e21-bae3-2ee24c6e8902

	/// Measure meas.opps_max_stages.
		annotation AgentPurpose = "Tracks opportunities booking lost amount percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opps_booking_amt_total], [meas.opps_booking_lost_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_max_stages' =
			
			SUMX(
			    VALUES(opps[_sys_doc_id]),
			    CALCULATE(
			        DISTINCTCOUNT(open_pipeline[trueai_stage_name]),
			        opps[trueai_is_won] = TRUE()
			    )
			)
		formatString: 0
		displayFolder: _success_metrics
		lineageTag: 40d5b9b3-a8b1-495b-95bb-dd379d53e138

	/// Measure meas.opps_win_rate_value.
		annotation AgentPurpose = "Tracks opportunities max stages."
		annotation AgentLogic = "Counts distinct values in opps[_sys_doc_id] under filters."
		annotation AgentDependencies = "Columns: opps[_sys_doc_id], open_pipeline[trueai_stage_name], opps[trueai_is_won]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_win_rate_value' = DIVIDE([meas.won_amt],[meas.opps_booking_amt_total])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _success_metrics
		lineageTag: a94c7b43-59b3-4861-97be-92d7b828c957

	/// Measure meas.opps_booking_amt_stage.
		annotation AgentPurpose = "Tracks opportunities win rate value."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opps_booking_amt_total], [meas.won_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_booking_amt_stage' = ```
			[meas.opps_booking_amt_total] - [meas.opps_booking_amt] 
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _opps
		lineageTag: 04beffda-c477-4ae0-8bee-c4cf2fa5db12

	/// Measure meas.opps_booking_amt_reached_next_stage.
		annotation AgentPurpose = "Tracks opportunities booking amount stage."
		annotation AgentLogic = "Derived from model references under current filters."
		annotation AgentDependencies = "Measures: [meas.opps_booking_amt], [meas.opps_booking_amt_total]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opps_booking_amt_reached_next_stage' = ```
			
			VAR curIdx =
			    MAX ( open_pipeline[trueai_sort_id] )
			VAR nextIdx =
			    CALCULATE (
			        MINX (
			            FILTER ( ALL ( open_pipeline[trueai_sort_id] ),
			                open_pipeline[trueai_sort_id] > curIdx
			            ),
			            open_pipeline[trueai_sort_id]
			        )
			    )
			RETURN
			IF (
			    ISBLANK ( nextIdx ),
			    BLANK(),
			    CALCULATE (
			        [meas.opps_booking_amt],
			        REMOVEFILTERS (
			            open_pipeline[trueai_sort_id],
			            open_pipeline[trueai_stage],
			            open_pipeline[trueai_stage_name],
			            open_pipeline[trueai_stage_num]
			        ),
			        open_pipeline[trueai_stage_name] <> "Closed Lost",
			         open_pipeline[trueai_stage_name] <> "Closed Won",
			        TREATAS ( { nextIdx }, open_pipeline[trueai_sort_id] )
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _success_metrics
		lineageTag: aa23b27a-3667-4817-9d76-eca8052fa0b2

	/// Measure meas.opps_total_crm_booking_amt.
		annotation AgentPurpose = "Tracks opportunities booking amount reached next stage."
		annotation AgentLogic = "Returns an extreme value from open_pipeline[trueai_sort_id] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_booking_amt]; Columns: open_pipeline[trueai_sort_id], open_pipeline[trueai_stage], open_pipeline[trueai_stage_name]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	measure 'meas.opps_total_crm_booking_amt' = SUM(opps[crm_booking_amt])
		lineageTag: 9f546c8e-a727-4045-b9a7-e88973fb9cd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_optimal_disc_level.
		annotation AgentPurpose = "Tracks opportunities total CRM booking amount."
		annotation AgentLogic = "Sums opps[crm_booking_amt] under filters."
		annotation AgentDependencies = "Columns: opps[crm_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_optimal_disc_level' =
			
			VAR TierStats =
			    ADDCOLUMNS (
			        DimDiscountTier,
			        "OppCount",
			            CALCULATE (
			                COUNTROWS ( opps ),
			                TREATAS ( { DimDiscountTier[trueai_discount_pct_tier] }, opps[trueai_discount_pct_tier] )
			            ),
			        "DeltaVal",
			            CALCULATE (
			                [meas.opps_delta_expected_pct],
			                TREATAS ( { DimDiscountTier[trueai_discount_pct_tier] }, opps[trueai_discount_pct_tier] )
			            )
			    )
			
			VAR TierFiltered =
			    FILTER ( TierStats, [OppCount] >= 3 )
			
			VAR TierRanked =
			    ADDCOLUMNS (
			        TierFiltered,
			        "TierRank",
			            RANKX ( TierFiltered, DimDiscountTier[SortKey], , ASC, DENSE )
			    )
			
			VAR Baseline =
			    AVERAGEX ( FILTER ( TierRanked, [TierRank] <= 2 ), [DeltaVal] )
			
			VAR Threshold = Baseline + 0.05
			
			VAR OptimalSortKey =
			    MINX (
			        FILTER (
			            TierRanked,
			            [TierRank] > 2 &&
			            [DeltaVal] >= Threshold
			        ),
			        DimDiscountTier[SortKey]
			    )
			
			RETURN COALESCE ( OptimalSortKey, -1 )
		lineageTag: 66645cae-a7a3-415a-869b-7803897fe2f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_optimal_discount_deal_count_pct.
		annotation AgentPurpose = "Tracks opportunities optimal disc level."
		annotation AgentLogic = "Counts rows using DimDiscountTier[trueai_discount_pct_tier] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_delta_expected_pct]; Columns: DimDiscountTier[trueai_discount_pct_tier], opps[trueai_discount_pct_tier], DimDiscountTier[SortKey]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_optimal_discount_deal_count_pct' =
			
			-- Step 1: Get the result from your existing "Optimal Discount Level" measure
			VAR BestTier = [meas.opps_optimal_disc_level]   -- e.g. returns "30–40%"
			
			-- Step 2: Count deals in that tier
			VAR OptimalTierDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS({ BestTier }, opps[trueai_discount_pct_tier])  -- apply tier filter at opp_line_items level
			    )
			
			-- Step 3: Count total deals across all tiers
			VAR TotalDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        ALL(opps[trueai_discount_pct_tier])
			    )
			
			-- Step 4: Return % of deals in the optimal tier
			RETURN
			    DIVIDE(OptimalTierDeals, TotalDeals)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4088315a-082d-4abf-93a2-2fafde065533

	/// Measure meas.opps_over_discounted_deal_pct.
		annotation AgentPurpose = "Tracks opportunities optimal discount deal count percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level], [meas.ssr_history_step_count]; Columns: opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_over_discounted_deal_pct' =
			
			-- Step 1: Get the optimal discount tier (e.g. "30-40%" or "40%+")
			VAR BestTier = [meas.opps_optimal_disc_level]
			
			-- Step 2: Clean and parse the upper bound of that tier
			VAR BestTierClean =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TRIM(BestTier), "–", "-"), "—", "-"), " ", "")
			VAR BestTierUpper =
			    VAR parts = SUBSTITUTE(BestTierClean, "%", "")
			    VAR dashPos = SEARCH("-", parts, 1, BLANK())
			    VAR upperText =
			        SWITCH(
			            TRUE(),
			            NOT ISBLANK(dashPos), MID(parts, dashPos + 1, LEN(parts) - dashPos),  -- "30-40%" → "40"
			            RIGHT(parts, 1) = "+", LEFT(parts, LEN(parts) - 1),                   -- "40%+"   → "40"
			            TRUE(), parts                                                        -- "0%"     → "0"
			        )
			    RETURN VALUE(upperText)
			
			-- Step 3: Build a lookup of all tiers with numeric upper bounds
			VAR Tiers =
			    ADDCOLUMNS(
			        VALUES(opps[trueai_discount_pct_tier]),
			        "Upper",
			            VAR clean = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TRIM(opps[trueai_discount_pct_tier]), "–", "-"), "—", "-"), " ", "")
			            VAR p = SUBSTITUTE(clean, "%", "")
			            VAR dashPos = SEARCH("-", p, 1, BLANK())
			            VAR upperText =
			                SWITCH(
			                    TRUE(),
			                    RIGHT(p, 1) = "+", "999",                      -- treat “%+” as open-ended top bucket
			                    NOT ISBLANK(dashPos), MID(p, dashPos + 1, LEN(p) - dashPos),
			                    TRUE(), p
			                )
			            RETURN VALUE(upperText)
			    )
			
			-- Step 4: Select tiers whose numeric upper bound is higher than the optimal tier
			VAR OverTiers =
			    SELECTCOLUMNS(
			        FILTER(Tiers, [Upper] > BestTierUpper),
			        "Tier", opps[trueai_discount_pct_tier]
			    )
			
			-- Step 5: Count deals in those “over-discounted” tiers
			VAR OverDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS(OverTiers, opps[trueai_discount_pct_tier])
			    )
			
			-- Step 6: Count all deals (for denominator)
			VAR TotalDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        ALL(opps[trueai_discount_pct_tier])
			    )
			
			-- Step 7: Return % of deals over optimal tier
			RETURN
			    COALESCE(DIVIDE(OverDeals, TotalDeals), 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 63b0aff0-9501-46ad-a241-5c4d4be19b7d

	/// Measure meas.opps_no_discount_count.
		annotation AgentPurpose = "Tracks opportunities over discounted deal percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level], [meas.ssr_history_step_count]; Columns: opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_no_discount_count' =
			
			CALCULATE(
			    [meas.ssr_history_step_count],                 -- or COUNT of opps if you prefer
			    TREATAS({ "0%" }, opps[trueai_discount_pct_tier])
			)
		lineageTag: 7f17629f-a273-407d-9136-24660f365ac5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_over_discount_deal_count.
		annotation AgentPurpose = "Tracks opportunities no discount count."
		annotation AgentLogic = "Counts rows using opps[trueai_discount_pct_tier] under filters."
		annotation AgentDependencies = "Measures: [meas.ssr_history_step_count]; Columns: opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_over_discount_deal_count' =
			
			VAR BestSortKey = [meas.opps_optimal_disc_level]
			
			VAR OverTiers =
			    FILTER (
			        DimDiscountTier,
			        DimDiscountTier[SortKey] > BestSortKey
			    )
			
			RETURN
			    CALCULATE (
			        [meas.ssr_history_step_count],
			        TREATAS (
			            SELECTCOLUMNS (
			                OverTiers,
			                "TierLabel", DimDiscountTier[trueai_discount_pct_tier]
			            ),
			            opps[trueai_discount_pct_tier]
			        )
			    )
		lineageTag: 25e3810a-7540-4eaf-ae38-99d14a3688c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_optimal_discount_deal_count.
		annotation AgentPurpose = "Tracks opportunities over discount deal count."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level], [meas.ssr_history_step_count]; Columns: DimDiscountTier[SortKey], DimDiscountTier[trueai_discount_pct_tier], opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_optimal_discount_deal_count' =
			
			VAR BestTier = [meas.opps_optimal_disc_level]
			RETURN
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS({ BestTier }, opps[trueai_discount_pct_tier])
			    )
		formatString: 0
		lineageTag: 3df4757a-4c6f-4c6e-b5a8-fb9c558fe44f

	/// Measure meas.opps_no_discount_pct.
		annotation AgentPurpose = "Tracks opportunities optimal discount deal count."
		annotation AgentLogic = "Counts rows using opps[trueai_discount_pct_tier] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level], [meas.ssr_history_step_count]; Columns: opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_no_discount_pct' =
			
			VAR NoDiscDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        TREATAS({ "0%" }, opps[trueai_discount_pct_tier])
			    )
			VAR TotalDeals =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        ALL(opps[trueai_discount_pct_tier])
			    )
			RETURN
			    DIVIDE(NoDiscDeals, TotalDeals)
		lineageTag: 112e76c9-31a5-4380-ab5e-d65f6a54ef96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_under_discount_deal_count.
		annotation AgentPurpose = "Tracks opportunities no discount percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.ssr_history_step_count]; Columns: opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_under_discount_deal_count' =
			
			VAR BestSortKey = [meas.opps_optimal_disc_level]
			
			VAR UnderTiers =
			    FILTER (
			        DimDiscountTier,
			        DimDiscountTier[SortKey] < BestSortKey
			    )
			
			RETURN
			    CALCULATE (
			        [meas.ssr_history_step_count],
			        TREATAS (
			            SELECTCOLUMNS (
			                UnderTiers,
			                "TierLabel", DimDiscountTier[trueai_discount_pct_tier]
			            ),
			            opps[trueai_discount_pct_tier]
			        )
			    )
		lineageTag: fc573d3e-78f1-4f98-8026-133216143789

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_under_discount_deal_pct.
		annotation AgentPurpose = "Tracks opportunities under discount deal count."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level], [meas.ssr_history_step_count]; Columns: DimDiscountTier[SortKey], DimDiscountTier[trueai_discount_pct_tier], opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_under_discount_deal_pct' =
			
			VAR UnderCount = [meas.opps_under_discount_deal_count]
			VAR TotalCount =
			    CALCULATE(
			        [meas.ssr_history_step_count],
			        ALL(opps[trueai_discount_pct_tier])
			    )
			RETURN
			    DIVIDE(UnderCount, TotalCount)
		lineageTag: f65c7a41-f806-4a0e-ac7c-1780f66da52f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.optimal_discount_tier_background.
		annotation AgentPurpose = "Tracks opportunities under discount deal percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opps_under_discount_deal_count], [meas.ssr_history_step_count]; Columns: opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.optimal_discount_tier_background' =
			
			VAR OptimalSortKey =
			    CALCULATE(
			        [meas.opps_optimal_disc_level],
			        REMOVEFILTERS(opps)
			    )
			
			VAR ThisSortKey =
			    CALCULATE(
			        MAX(DimDiscountTier[SortKey]),
			        TREATAS( { SELECTEDVALUE(opps[trueai_discount_pct_tier]) }, DimDiscountTier[trueai_discount_pct_tier] )
			    )
			
			RETURN
			    SWITCH(
			        TRUE(),
			        ThisSortKey = OptimalSortKey, "#78903B",   -- Optimal (green)
			        ThisSortKey < OptimalSortKey, "#595B6F",   -- Under optimal (blue-gray)
			        ThisSortKey > OptimalSortKey, "#912452",   -- Over optimal (purple-rose)
			        "#1E1E1E"                                  -- Default
			    )
		lineageTag: e358cd7c-fade-48a9-8d27-8493a0f1bce1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_optimal_discount_pct.
		annotation AgentPurpose = "Tracks optimal discount tier background."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level]; Columns: DimDiscountTier[SortKey], opps[trueai_discount_pct_tier], DimDiscountTier[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_optimal_discount_pct' =
			
			-- Get the optimal discount tier text (e.g. "30-40%")
			VAR TierText = [meas.opps_optimal_disc_level]
			
			-- Find the position of the dash "-" (used to split lower/upper bounds)
			VAR DashPos = SEARCH("-", TierText, 1, BLANK())
			
			-- Extract the upper bound of the range (e.g. "40" from "30-40%")
			VAR UpperPart =
			    IF(
			        ISBLANK(DashPos),
			        SUBSTITUTE(TierText, "%", ""),         -- if no dash, just remove "%"
			        MID(TierText, DashPos + 1, LEN(TierText))  -- else get text after "-"
			    )
			
			-- Convert upper bound text to a number and divide by 100 to get percent (e.g. "40" → 0.4)
			VAR UpperPct = VALUE(SUBSTITUTE(SUBSTITUTE(UpperPart, "%", ""), "+", "")) / 100
			
			-- Extract the lower bound of the range (e.g. "30" from "30-40%")
			VAR LowerPart =
			    IF(
			        ISBLANK(DashPos),
			        SUBSTITUTE(TierText, "%", ""),         -- if no dash, just use the single number
			        LEFT(TierText, DashPos - 1)            -- else get text before "-"
			    )
			
			-- Convert lower bound text to a number and divide by 100 (e.g. "30" → 0.3)
			VAR LowerPct = VALUE(SUBSTITUTE(SUBSTITUTE(LowerPart, "%", ""), "+", "")) / 100
			
			-- Return the midpoint of the range (e.g. (0.3 + 0.4) / 2 = 0.35)
			RETURN
			    DIVIDE(UpperPct + LowerPct, 2)
		lineageTag: 4bebb021-1832-44b1-bd86-13afcb8a7888

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_over_discount_amount.
		annotation AgentPurpose = "Tracks opportunities optimal discount percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_over_discount_amount' =
			
			VAR BestSortKey = [meas.opps_optimal_disc_level]
			
			VAR OverTiers =
			    FILTER (
			        DimDiscountTier,
			        DimDiscountTier[SortKey] > BestSortKey
			    )
			
			RETURN
			    CALCULATE (
			        SUM ( opps[trueai_discount_amt] ),
			        TREATAS (
			            SELECTCOLUMNS (
			                OverTiers,
			                "TierLabel", DimDiscountTier[trueai_discount_pct_tier]
			            ),
			            opps[trueai_discount_pct_tier]
			        )
			    )
		lineageTag: 507893f4-f755-4633-8227-88d3a5e498e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_under_discount_amount.
		annotation AgentPurpose = "Tracks opportunities over discount amount."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level]; Columns: DimDiscountTier[SortKey], opps[trueai_discount_amt], DimDiscountTier[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_under_discount_amount' =
			
			VAR BestSortKey = [meas.opps_optimal_disc_level]
			
			VAR UnderTiers =
			    FILTER (
			        DimDiscountTier,
			        DimDiscountTier[SortKey] < BestSortKey
			    )
			
			RETURN
			    CALCULATE (
			        SUM ( opps[trueai_discount_amt] ),
			        TREATAS (
			            SELECTCOLUMNS (
			                UnderTiers,
			                "TierLabel", DimDiscountTier[trueai_discount_pct_tier]
			            ),
			            opps[trueai_discount_pct_tier]
			        )
			    )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3b0c2120-0320-4b5f-b0ee-169487a43ba8

	/// Measure meas.opps_discount_avg_pct.
		annotation AgentPurpose = "Tracks opportunities under discount amount."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level]; Columns: DimDiscountTier[SortKey], opps[trueai_discount_amt], DimDiscountTier[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_discount_avg_pct' =
			
			AVERAGEX(
			    VALUES('opps'[_sys_doc_id]),
			    VAR BookedAmt =
			        CALCULATE(SUM('opps'[trueai_booking_amt]))
			    VAR ListAmt =
			        CALCULATE(SUM('opp_line_items'[trueai_list_price]))
			    RETURN
			        IF(
			            ListAmt > 0,
			            ABS(DIVIDE(ListAmt - BookedAmt, ListAmt)),   // ← always positive
			            BLANK()
			        )
			)
		lineageTag: 0a4f6d01-86d8-4647-a75d-6f5468467ccb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.trueai_discount_avg_pct.
		annotation AgentPurpose = "Tracks opportunities discount average percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Columns: 'opps'[_sys_doc_id], 'opps'[trueai_booking_amt], 'opp_line_items'[trueai_list_price]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.trueai_discount_avg_pct' = ```
			
			VAR list_price = CALCULATE(SUM (opps[col.trueai_list_price_amt])) 
			VAR booking = CALCULATE(SUM (opps[trueai_booking_amt])) 
			VAR res = DIVIDE(list_price - booking, list_price, BLANK()) 
			RETURN res
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6e72aa0a-1689-423c-a601-75d453bd1b16

	/// Measure meas.opps_avg_discount_pct.
		annotation AgentPurpose = "Tracks trueai discount average percentage."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Columns: opps[col.trueai_list_price_amt], opps[trueai_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_avg_discount_pct' = ```
			
			AVERAGE('opps'[trueai_discount_pct]) 
			```
		lineageTag: d7195d3c-688d-44b8-94cb-20117f9b2a55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas._diagnostic_delta_test.
		annotation AgentPurpose = "Tracks opportunities average discount percentage."
		annotation AgentLogic = "Counts rows using 'opps'[trueai_discount_pct] under filters."
		annotation AgentDependencies = "Columns: 'opps'[trueai_discount_pct]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas._diagnostic_delta_test' =
			
			VAR SuccessRate = CALCULATE([meas.ssr_history_success_rate], KEEPFILTERS(opps))
			VAR ExpectedRate = CALCULATE([meas.ssr_history_success_prob_avg], KEEPFILTERS(opps))
			RETURN
			SuccessRate - ExpectedRate
		lineageTag: cc8997f7-91d5-4b35-a9fb-ba06e2532354

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_over_discounted_total.
		annotation AgentPurpose = "Tracks diagnostic delta test."
		annotation AgentLogic = "Derived from model references under current filters."
		annotation AgentDependencies = "Measures: [meas.ssr_history_success_prob_avg], [meas.ssr_history_success_rate]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_over_discounted_total' =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            VALUES(opps[trueai_discount_pct_tier]),
			            NOT ISBLANK(opps[trueai_discount_pct_tier])
			        ),
			        [meas.opps_over_discount_amount]
			    ),
			    REMOVEFILTERS(opps[trueai_discount_pct_tier])
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 49d051de-1b3e-4ab6-82a4-f958870a76bf

	/// Measure meas.trueai_disc_avg_pct.
		annotation AgentPurpose = "Tracks opportunities over discounted total."
		annotation AgentLogic = "Counts rows using opps[trueai_discount_pct_tier] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_over_discount_amount]; Columns: opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.trueai_disc_avg_pct' =
			
			AVERAGE(opps[trueai_discount_pct])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b02b6b3e-be61-49ab-bceb-67e1d3616691

	/// Measure meas.opp_valid_amount.
		annotation AgentPurpose = "Tracks trueai disc average percentage."
		annotation AgentLogic = "Counts rows using opps[trueai_discount_pct] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_discount_pct]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opp_valid_amount' =
			
			IF (
			    MAX('ssr_history'[opp_won_amt]) > 0,
			    1,
			    0
			)
		lineageTag: 55035ed9-e8f2-47e5-a5d8-b2e18fd447e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_optimal_disc_label.
		annotation AgentPurpose = "Tracks opportunity valid amount."
		annotation AgentLogic = "Returns an extreme value from 'ssr_history'[opp_won_amt] under filters."
		annotation AgentDependencies = "Columns: 'ssr_history'[opp_won_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_optimal_disc_label' =
			
			VAR BestSortKey =
			    CALCULATE(
			        [meas.opps_optimal_disc_level],
			        REMOVEFILTERS( DimDiscountTier )
			    )
			RETURN
			    MAXX(
			        FILTER( DimDiscountTier, DimDiscountTier[SortKey] = BestSortKey ),
			        DimDiscountTier[trueai_discount_pct_tier]
			    )
		lineageTag: c2af94f1-ae16-4c71-a3c2-2f29204b57a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_deals_in_optimal_tier.
		annotation AgentPurpose = "Tracks opportunities optimal disc label."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level]; Columns: DimDiscountTier[SortKey], DimDiscountTier[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_deals_in_optimal_tier' =
			
			VAR BestSortKey =
			    CALCULATE ( [meas.opps_optimal_disc_level], REMOVEFILTERS( opps ) )
			
			VAR OptimalTierTable =
			    FILTER (
			        DimDiscountTier,
			        DimDiscountTier[SortKey] = BestSortKey
			    )
			
			RETURN
			IF (
			    ISBLANK ( BestSortKey ),
			    BLANK(),
			    CALCULATE (
			        [meas.ssr_history_step_count],   -- your deal count measure
			        TREATAS (
			            SELECTCOLUMNS (
			                OptimalTierTable,
			                "TierLabel", DimDiscountTier[trueai_discount_pct_tier]
			            ),
			            opps[trueai_discount_pct_tier]
			        )
			    )
			)
		lineageTag: aa937972-ddbf-43af-bdee-0ef2919d2932

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_excess_over_discount_amount.
		annotation AgentPurpose = "Tracks opportunities deals in optimal tier."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level], [meas.ssr_history_step_count]; Columns: DimDiscountTier[SortKey], DimDiscountTier[trueai_discount_pct_tier], opps[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opps_excess_over_discount_amount' =
			
			VAR BestSortKey = [meas.opps_optimal_disc_level]
			
			-- All tiers above optimal
			VAR OverTiers =
			    FILTER( DimDiscountTier, DimDiscountTier[SortKey] > BestSortKey )
			
			VAR OptimalPct = [meas.optimal_discount_pct_midpoint]
			
			RETURN
			SUMX(
			    FILTER(
			        opps,
			        opps[trueai_discount_pct_tier] IN
			            SELECTCOLUMNS(
			                OverTiers,
			                "TierLabel", DimDiscountTier[trueai_discount_pct_tier]
			            )
			    ),
			    VAR ActualDiscount = opps[trueai_discount_amt]
			    VAR BookingAmt     = opps[trueai_booking_amt]          -- Won amount per deal
			    VAR ListPrice      = BookingAmt + ActualDiscount
			    VAR ExpectedDiscountAtOptimal = ListPrice * OptimalPct
			    VAR Excess = ActualDiscount - ExpectedDiscountAtOptimal
			    RETURN MAX(Excess, 0)  -- clamp negative leakage to zero
			)
		lineageTag: 69403608-0911-41c1-8e07-1730d51bcb9a

	/// Measure meas.optimal_discount_pct_midpoint.
		annotation AgentPurpose = "Tracks opportunities excess over discount amount."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level], [meas.optimal_discount_pct_midpoint]; Columns: DimDiscountTier[SortKey], opps[trueai_discount_pct_tier], DimDiscountTier[trueai_discount_pct_tier]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.optimal_discount_pct_midpoint' =
			
			VAR BestSortKey = [meas.opps_optimal_disc_level]
			RETURN
			    AVERAGEX(
			        FILTER( DimDiscountTier, DimDiscountTier[SortKey] = BestSortKey ),
			        ( DimDiscountTier[TierStart] + DimDiscountTier[TierEnd] ) / 2
			    ) / 100
		lineageTag: d427d18f-5e29-4780-b45d-b4474b77d256

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_excess_over_discount_amount_by_tier.
		annotation AgentPurpose = "Tracks optimal discount percentage midpoint."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level]; Columns: DimDiscountTier[SortKey], DimDiscountTier[TierStart], DimDiscountTier[TierEnd]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Percentage"
	measure 'meas.opps_excess_over_discount_amount_by_tier' =
			
			VAR BestSortKey =
			    CALCULATE ( [meas.opps_optimal_disc_level], REMOVEFILTERS( opps ) )
			
			VAR ThisSortKey =
			    CALCULATE (
			        MAX ( DimDiscountTier[SortKey] ),
			        KEEPFILTERS( DimDiscountTier )
			    )
			
			VAR OptimalPct =
			    [meas.optimal_discount_pct_midpoint]
			
			RETURN
			IF (
			    ISBLANK ( ThisSortKey ) || ISBLANK ( BestSortKey ) || ThisSortKey <= BestSortKey,
			    BLANK(),          -- <<< This ensures optimal & under tiers show NOTHING
			    SUMX (
			        opps,          -- opps table is filtered by current tier automatically
			        VAR ActualDiscount = opps[trueai_discount_amt]
			        VAR BookingAmt     = opps[trueai_booking_amt]
			        VAR ListPrice      = BookingAmt + ActualDiscount
			        VAR Expected       = ListPrice * OptimalPct
			        VAR Excess         = ActualDiscount - Expected
			        RETURN MAX ( Excess, 0 )
			    )
			)
		lineageTag: f9d49b07-aa70-4715-8772-9628091580b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_nd_amt.
		annotation AgentPurpose = "Tracks opportunities excess over discount amount by tier."
		annotation AgentLogic = "Counts rows using DimDiscountTier[SortKey] under filters."
		annotation AgentDependencies = "Measures: [meas.opps_optimal_disc_level], [meas.optimal_discount_pct_midpoint]; Columns: DimDiscountTier[SortKey], opps[trueai_discount_amt], opps[trueai_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Whole number"
	measure 'meas.opp_nd_amt' =
			
			SUM ( opps[trueai_nd_amt] )
		lineageTag: 03045633-016e-4492-9659-cc27636d00bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_nnb_amt.
		annotation AgentPurpose = "Tracks opportunity nd amount."
		annotation AgentLogic = "Sums opps[trueai_nd_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_nd_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_nnb_amt' = ```
			
			SUM ( opps[trueai_nnb_amt] )
			
			```
		lineageTag: efe1d8fb-30b1-4ab3-89e7-804be31fb5dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_downgrade_amt.
		annotation AgentPurpose = "Tracks opportunity nnb amount."
		annotation AgentLogic = "Sums opps[trueai_nnb_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_nnb_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_downgrade_amt' =
			
			SUM ( opps[trueai_downgrade_amt] )
		lineageTag: 6f61a270-93c2-4d9b-a3b6-0d9401d9dfb8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_cross_sale_amt.
		annotation AgentPurpose = "Tracks opportunity downgrade amount."
		annotation AgentLogic = "Sums opps[trueai_downgrade_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_downgrade_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_cross_sale_amt' =
			
			SUM ( opps[trueai_cross_sale_amt] )
		lineageTag: a5c87d1c-4dcc-4ec0-8f2b-63b6fb6bfb77

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_renewal_amt.
		annotation AgentPurpose = "Tracks opportunity cross sale amount."
		annotation AgentLogic = "Sums opps[trueai_cross_sale_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_cross_sale_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_renewal_amt' =
			
			SUM ( opps[trueai_renewal_amt] )
		lineageTag: 4ac06b0a-b120-4372-8791-aad52081fe68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_arr_amt.
		annotation AgentPurpose = "Tracks opportunity renewal amount."
		annotation AgentLogic = "Sums opps[trueai_renewal_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_renewal_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_arr_amt' =
			
			SUM ( opps[trueai_arr_amt] )
		lineageTag: d14fb762-ef99-4ec6-9aa4-04f50d08f0cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_one_time_amt.
		annotation AgentPurpose = "Tracks opportunity arr amount."
		annotation AgentLogic = "Sums opps[trueai_arr_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_arr_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_one_time_amt' =
			
			SUM ( opps[trueai_one_time_amt] )
		lineageTag: 73387f7c-1bdc-4587-9605-88d477f6790c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_mrr_amt.
		annotation AgentPurpose = "Tracks opportunity one time amount."
		annotation AgentLogic = "Sums opps[trueai_one_time_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_one_time_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_mrr_amt' =
			
			DIVIDE( [meas.opp_arr_amt], 12 )
		lineageTag: 2f7a6496-8c0e-4236-bc17-b61e4a8c2e85

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opp_expansion_amt.
		annotation AgentPurpose = "Tracks opportunity mrr amount."
		annotation AgentLogic = "Calculated as a ratio of two values with any applied filters."
		annotation AgentDependencies = "Measures: [meas.opp_arr_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opp_expansion_amt' =
			
			SUM ( opps[trueai_expansion_amt] )
		lineageTag: 3eb58e07-0156-413b-b2f8-efcbf9ec8cff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.opps_non_nnb_amt.
		annotation AgentPurpose = "Tracks opportunity expansion amount."
		annotation AgentLogic = "Sums opps[trueai_expansion_amt] under filters."
		annotation AgentDependencies = "Columns: opps[trueai_expansion_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	measure 'meas.opps_non_nnb_amt' =
			
			[meas.opps_booking_amt] - [meas.opp_nnb_amt]
		lineageTag: ede2a06f-8f34-430d-889a-82b9010afa15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Unique record identifier, based on the ID of the document in the remote system (such as Salesforce ID)
		annotation AgentPurpose = "Tracks opportunities non nnb amount."
		annotation AgentLogic = "Derived from model references under current filters."
		annotation AgentDependencies = "Measures: [meas.opp_nnb_amt], [meas.opps_booking_amt]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Decimal"
	column _sys_doc_id
		dataType: string
		lineageTag: 88fcbd55-d718-43f8-9717-ccc01592c495
		summarizeBy: count
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = User

	/// The end date of the record, stripped of time
	column _sys_filt_end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: a6cf0900-2913-4ba5-8576-b6c2f8985e72
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 5fda0ce1-daaf-4bd0-9f51-2660c3e09280
			defaultHierarchy: LocalDateTable_3c94028f-8877-46e3-979b-5cd8d33be02e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The start date of the record, stripped of time
	column _sys_filt_start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 49367a97-76a2-44aa-88af-dc267da57b6f
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 55527176-a1e5-4f40-b689-4c4e400bbb6a
			defaultHierarchy: LocalDateTable_13f4f704-f348-4cd9-8666-42fbbd986b71.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Id of the SSR document the record belongs to
	column _sys_ssr_id
		dataType: string
		lineageTag: f55be3c2-25bd-49a6-954e-d1f0612cf4c6
		summarizeBy: none
		sourceColumn: _sys_ssr_id

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable on the account
	column crm_account_custom_value_1
		dataType: string
		lineageTag: 539d75b9-5ab4-4caa-b2f8-bf8d77f44b89
		summarizeBy: none
		sourceColumn: crm_account_custom_value_1

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable on the account
	column crm_account_custom_value_2
		dataType: string
		lineageTag: 06fad6ce-b10b-4c5e-84de-67a29f9e9823
		summarizeBy: none
		sourceColumn: crm_account_custom_value_2

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable on the account
	column crm_account_custom_value_3
		dataType: string
		lineageTag: 06c8997d-4a29-4ce3-8b8b-66395e2e2dfb
		summarizeBy: none
		sourceColumn: crm_account_custom_value_3

		annotation SummarizationSetBy = Automatic

	/// CRM account id of the opportunity
	column crm_account_id
		dataType: string
		lineageTag: 3b3bbf19-5963-4e2c-99cc-2dc675dee1fb
		summarizeBy: none
		sourceColumn: crm_account_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's booking amount in the CRM
	column crm_booking_amt
		dataType: double
		lineageTag: d4c3d431-20a1-4523-a30f-6ee2253ba7f0
		summarizeBy: sum
		sourceColumn: crm_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's close date in the CRM
	column crm_close_date
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 1144a88b-9c5c-4e96-bd8d-ec0c252506be
		summarizeBy: none
		sourceColumn: crm_close_date

		variation Variation
			isDefault
			relationship: 01c51b59-7ea6-4004-aed8-958a8dc1e5af
			defaultHierarchy: LocalDateTable_fcaea0e2-d7e0-4a55-8ced-8a82a2761917.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Opportunity's completeness score based on the CRM data
	column crm_complt
		dataType: double
		lineageTag: 301775ce-0f4e-4462-8146-aab775558b0a
		summarizeBy: sum
		sourceColumn: crm_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's contact information completeness score based on the CRM data
	column crm_complt_contact
		dataType: double
		lineageTag: eade5a58-25b1-468d-85b1-85a314c26af2
		summarizeBy: sum
		sourceColumn: crm_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's marketing completeness score based on the CRM data
	column crm_complt_marketing
		dataType: double
		formatString: 0
		lineageTag: 328ed236-1d4d-4f62-93f9-67343b9bab44
		summarizeBy: sum
		sourceColumn: crm_complt_marketing

		annotation SummarizationSetBy = Automatic

	/// Opportunity creator's id in the CRM
	column crm_creator_id
		dataType: string
		lineageTag: 613e63ab-3957-4d55-97e3-dd80ae42582e
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's currency in the CRM
	column crm_currency
		dataType: string
		lineageTag: 354b9eed-4b20-4502-914c-6be919b3e8a7
		summarizeBy: none
		sourceColumn: crm_currency

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_1
		dataType: string
		lineageTag: b325e3f8-159a-4139-80c2-f4ea62659ec9
		summarizeBy: none
		sourceColumn: crm_custom_value_1

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_2
		dataType: string
		lineageTag: fb20b56e-f861-4804-8b00-9d04b3f5b9ac
		summarizeBy: none
		sourceColumn: crm_custom_value_2

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_3
		dataType: string
		lineageTag: 5f5e1f09-00dc-4c26-a98c-c4d46b1a625a
		summarizeBy: none
		sourceColumn: crm_custom_value_3

		annotation SummarizationSetBy = Automatic

	/// Link to the opportunity in the remote system (such as Salesforce)
	column crm_deep_link
		dataType: string
		lineageTag: 05cfe5dc-9176-41d2-bc8f-d8e3ed614fae
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	/// Opportunity's last activity time in the CRM
	column crm_last_act_time
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5c7e8412-72f6-450c-9ba3-ed6b7c8711ef
		summarizeBy: none
		sourceColumn: crm_last_act_time

		variation Variation
			isDefault
			relationship: b4365009-db12-4b4a-ab7e-69124449ebf7
			defaultHierarchy: LocalDateTable_2d31ddae-87fe-4ec5-8896-d87a04765d4c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity's lead source in the CRM
	column crm_leadsource
		dataType: string
		lineageTag: b6507793-1bf2-4c7d-a00d-b28b7913bff4
		summarizeBy: none
		sourceColumn: crm_leadsource

		annotation SummarizationSetBy = Automatic

	/// Name of the opportunity
	column crm_name
		dataType: string
		lineageTag: 79e788de-2051-412d-8200-cf3df4ee4551
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	/// Opportunity owner's id in the CRM
	column crm_owner_id
		dataType: string
		lineageTag: bd6b991f-9561-4de2-be85-0bee8e163bd1
		summarizeBy: none
		sourceColumn: crm_owner_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage name in the CRM
	column crm_stage_name
		dataType: string
		lineageTag: e4656938-bbe9-46ad-aadb-956c45e34181
		summarizeBy: none
		sourceColumn: crm_stage_name

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage number in the CRM
	column crm_stage_num
		dataType: int64
		formatString: 0
		lineageTag: 65b93c39-2f42-40fe-a741-b04610e837b3
		summarizeBy: sum
		sourceColumn: crm_stage_num

		annotation SummarizationSetBy = Automatic

	/// Opportunity's type in the CRM
	column crm_type
		dataType: string
		lineageTag: 430a5fb9-2142-4084-a963-b6339dcee13b
		summarizeBy: none
		sourceColumn: crm_type

		annotation SummarizationSetBy = Automatic

	/// Opportunity's city
	column trueai_addr_city
		dataType: string
		lineageTag: e40d7176-d074-4d0c-ae30-b94c5758edb2
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	/// Opportunity's country
	column trueai_addr_country
		dataType: string
		lineageTag: ca9a4f05-9adf-4b2a-aa5f-30564d36e24e
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	/// Opportunity's latitude
	column trueai_addr_lat
		dataType: double
		lineageTag: 982db127-41e6-4eb1-945f-6df7d988b7f1
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's longitude
	column trueai_addr_long
		dataType: double
		lineageTag: 088de29a-5fe4-4f25-9e10-53f6a5d20733
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's postal code
	column trueai_addr_postal_code
		dataType: string
		lineageTag: 7299d1a8-1541-455d-aceb-02fb839dabc5
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	/// Opportunity's address prediction rule
	column trueai_addr_rule
		dataType: int64
		formatString: 0
		lineageTag: 51bddaa5-a4cd-40cc-bed2-0d58550fad47
		summarizeBy: sum
		sourceColumn: trueai_addr_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's state
	column trueai_addr_state
		dataType: string
		lineageTag: 29ad86e7-f924-4bce-89de-c9564e3cc600
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	/// Opportunity's street
	column trueai_addr_street
		dataType: string
		lineageTag: 25418c07-50cc-4637-835c-135aee79b467
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	/// Opportunity's booking amount
	column trueai_booking_amt
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0dd848ff-b00b-4113-b2b2-3ff214292dd3
		summarizeBy: sum
		sourceColumn: trueai_booking_amt

		annotation SummarizationSetBy = Automatic

	/// Opportunity's booking amount rule related to the presence or absence of opp line items and custom mappings
	column trueai_booking_amt_rule
		dataType: int64
		formatString: 0
		lineageTag: 554ca8fc-a26c-4a6d-8dd9-43588a45ebdb
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's close date
	column trueai_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 59cdc35d-bc26-4406-895b-410b02f3cbdb
		summarizeBy: none
		sourceColumn: trueai_close_date

		variation Variation
			isDefault
			relationship: ed0a72ed-0664-4aee-950c-bd464feacd42
			defaultHierarchy: LocalDateTable_f946d803-7fe1-4e12-85ba-962286615d83.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized company size
	column trueai_company_size
		dataType: string
		lineageTag: 268a37ef-e827-4ce9-b4a7-c43329dc0152
		summarizeBy: none
		sourceColumn: trueai_company_size

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized company size prediction rule
	column trueai_company_size_rule
		dataType: int64
		formatString: 0
		lineageTag: f2d94749-9b87-4c34-9bd7-567e1523c0b6
		summarizeBy: sum
		sourceColumn: trueai_company_size_rule

		annotation SummarizationSetBy = Automatic

	/// Completeness score of the opportunity based on the standardized data
	column trueai_complt
		dataType: double
		lineageTag: 05b2a018-d2f5-46bd-984e-8c1d7d0f506b
		summarizeBy: sum
		sourceColumn: trueai_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact information completeness score of the opportunity based on the standardized data
	column trueai_complt_contact
		dataType: double
		lineageTag: 3f30935c-ee61-4310-b564-1af485ae9b22
		summarizeBy: sum
		sourceColumn: trueai_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Marketing completeness score of the opportunity based on the standardized data
	column trueai_complt_marketing
		dataType: double
		formatString: 0
		lineageTag: 1b759883-c0f7-4ee4-8437-c15e5711ba73
		summarizeBy: sum
		sourceColumn: trueai_complt_marketing

		annotation SummarizationSetBy = Automatic

	/// Opportunity creator's id
	column trueai_creator_id
		dataType: string
		lineageTag: 54cf8b74-c048-47ef-af1b-aa98afdfdb39
		summarizeBy: none
		sourceColumn: trueai_creator_id

		annotation SummarizationSetBy = Automatic

	/// Total duration of activities performed on the opportunity
	column trueai_dur
		dataType: int64
		formatString: 0
		lineageTag: 2f02e986-448a-4e27-aae1-7ac31a266f66
		summarizeBy: sum
		sourceColumn: trueai_dur

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized industry
	column trueai_industry
		dataType: string
		lineageTag: 35410a22-5548-4df5-8dc1-fba4ff93f30e
		summarizeBy: none
		sourceColumn: trueai_industry

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized industry prediction confidence
	column trueai_industry_conf
		dataType: double
		lineageTag: 219a06c1-7dfe-4f51-8bf4-424a3991d64b
		summarizeBy: sum
		sourceColumn: trueai_industry_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's standardized industry prediction rule
	column trueai_industry_rule
		dataType: int64
		formatString: 0
		lineageTag: 45918e18-c642-4294-8359-37135937cf61
		summarizeBy: sum
		sourceColumn: trueai_industry_rule

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is a new logo
	column trueai_is_new_logo
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 473bcf62-22df-4375-930d-75c05f10697a
		summarizeBy: none
		sourceColumn: trueai_is_new_logo

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized lead source
	column trueai_leadsource
		dataType: string
		lineageTag: abda2696-27f8-4d81-b78f-caeab4af7e96
		summarizeBy: none
		sourceColumn: trueai_leadsource

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized lead source prediction confidence
	column trueai_leadsource_conf
		dataType: double
		lineageTag: 3215f56d-0c96-4264-8a78-1abe5702f7f3
		summarizeBy: sum
		sourceColumn: trueai_leadsource_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's standardized lead source prediction rule
	column trueai_leadsource_rule
		dataType: int64
		formatString: 0
		lineageTag: a1cc073d-8aed-4f29-8ac9-e30155bc3758
		summarizeBy: sum
		sourceColumn: trueai_leadsource_rule

		annotation SummarizationSetBy = Automatic

	/// Date when the opportunity entered the late stage
	column trueai_opp_stage_late_date
		dataType: dateTime
		formatString: General Date
		lineageTag: efbb5160-f1ba-435e-9d0a-20d8be4ce82d
		summarizeBy: none
		sourceColumn: trueai_opp_stage_late_date

		variation Variation
			isDefault
			relationship: 0d877c30-71ed-4cdc-8dc3-3dc1ea884d4d
			defaultHierarchy: LocalDateTable_7d058fa1-9bc3-4c62-9d06-e11f3fa08277.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Date when the opportunity entered the middle stage
	column trueai_opp_stage_mid_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 39e03763-3094-4a0b-8d78-7907c7ebd0f0
		summarizeBy: none
		sourceColumn: trueai_opp_stage_mid_date

		variation Variation
			isDefault
			relationship: 33802dbf-8c7e-4c4c-8854-7ad895933e60
			defaultHierarchy: LocalDateTable_9740a049-2bd3-41e3-99dc-a85354f81994.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity owner's id
	column trueai_owner_id
		dataType: string
		lineageTag: d7eae22d-928e-4b5b-95d5-afa5e71416b2
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	/// Propensity based on the probability of win
	column trueai_propensity
		dataType: string
		lineageTag: f9ca256f-982f-4e74-8ba4-bb9073321080
		summarizeBy: none
		sourceColumn: trueai_propensity
		sortByColumn: trueai_propensity_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Propensity expressed as an integer from 1 to 5 based on the probability of win
	column trueai_propensity_num
		dataType: int64
		formatString: 0
		lineageTag: 45b3966e-03c2-4582-9323-719ead28155e
		summarizeBy: sum
		sourceColumn: trueai_propensity_num

		annotation SummarizationSetBy = Automatic

	/// Opportunity's sale type
	column trueai_sale_type
		dataType: string
		lineageTag: 07005dac-4d02-4068-91fd-dc61de938357
		summarizeBy: none
		sourceColumn: trueai_sale_type
		sortByColumn: trueai_sale_type_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Opportunity's sale type prediction confidence
	column trueai_sale_type_conf
		dataType: double
		lineageTag: 215ed405-cde1-4f5c-a9a3-6cb3b58cde6e
		summarizeBy: sum
		sourceColumn: trueai_sale_type_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's custom completeness score based on the CRM data
	column crm_complt_custom
		dataType: double
		lineageTag: 5999492c-d926-4832-98ab-554786c282fd
		summarizeBy: sum
		sourceColumn: crm_complt_custom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The date of the last data request from the platform
	column _sys_as_of
		dataType: dateTime
		formatString: Long Date
		lineageTag: c7f5019a-1c24-4def-954f-0feda653998f
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 9f7f849b-0921-4bfe-91d5-4702eb109e0b
			defaultHierarchy: LocalDateTable_622b6751-c6ca-49ca-9ab8-8f2b4b9cb734.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is active
	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8d15dfa8-d8b0-4f03-8ceb-085049a0275d
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// The date of the last data modification in the platform
	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 928dd265-7cd0-4ba5-abc6-37e4f8c1660f
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 6ed75488-b122-43ff-81c9-e5cb9e5ae545
			defaultHierarchy: LocalDateTable_0d867766-6cb9-46d4-92e2-f5e481d9ddc5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity creation date in the CRM
	column crm_created_on
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 62264037-ceeb-4dfe-b533-d6f672fad326
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: b6a82ba0-6c64-485e-9dc6-f4d58976beb2
			defaultHierarchy: LocalDateTable_c2b74306-a09c-41ea-961f-5ddacaea4d8b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Boolean flag that indicates whether the opportunity is closed in the CRM
	column crm_is_closed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5eea1041-471a-407c-a0ab-e9c415cfd495
		summarizeBy: none
		sourceColumn: crm_is_closed

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is won in the CRM
	column crm_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 53a19397-2f50-494e-8d99-35fccf120d2b
		summarizeBy: none
		sourceColumn: crm_is_won

		annotation SummarizationSetBy = Automatic

	/// Opportunity modified on date in the CRM
	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 07331f49-c5ab-4cc1-a634-b12cbf861274
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: 678e9d30-5212-4cf8-b437-1dbe7f52f74b
			defaultHierarchy: LocalDateTable_670f2152-beb7-4564-ab06-7945e86e36cb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity's prospecting entity
	column trueai_created_from_entity
		dataType: string
		lineageTag: 742606d0-e93f-4ebc-8d08-c078da19668d
		summarizeBy: none
		sourceColumn: trueai_created_from_entity

		annotation SummarizationSetBy = Automatic

	/// Opportunity's prospecting object's id
	column trueai_created_from_id
		dataType: string
		lineageTag: aa27386e-90e5-4f08-9ca3-51edf081d66a
		summarizeBy: none
		sourceColumn: trueai_created_from_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity creation date
	column trueai_created_on
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4ac75f07-9bff-4eb9-955f-62f41b038c16
		summarizeBy: none
		sourceColumn: trueai_created_on

		variation Variation
			isDefault
			relationship: 774b2518-7528-4998-9d95-57015c87e28a
			defaultHierarchy: LocalDateTable_0752fb46-2abf-4378-9541-c789e0fdc007.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is won
	column trueai_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 54610216-0dc2-4191-b4d9-07c2600e15ca
		summarizeBy: none
		sourceColumn: trueai_is_won

		annotation SummarizationSetBy = Automatic

	/// Opportunity's normalized stage
	column trueai_stage
		dataType: string
		lineageTag: 6d231412-b655-416f-85f6-fcd506b75399
		summarizeBy: none
		sourceColumn: trueai_stage

		annotation SummarizationSetBy = Automatic

	/// Probability of win
	column trueai_prob_of_win
		dataType: double
		lineageTag: e96f5ead-faa8-42cb-a0c4-25e6e468cd04
		summarizeBy: sum
		sourceColumn: trueai_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity discount amount
	column trueai_discount_amt
		dataType: double
		lineageTag: dd9afbc5-9311-4dbb-90fd-76e9c3596e80
		summarizeBy: sum
		sourceColumn: trueai_discount_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity discount percentage
	column trueai_discount_pct
		dataType: double
		lineageTag: d298504b-9662-4b09-9aab-80a719e715be
		summarizeBy: sum
		sourceColumn: trueai_discount_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's booking amount currency conversion rule
	column trueai_booking_amt_currency_rule
		dataType: int64
		formatString: 0
		lineageTag: 7b6cd046-3091-4b34-b6ea-a53f77229ffc
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_currency_rule

		annotation SummarizationSetBy = Automatic

	/// Boolean flag indicating whether the opportunity should be treated as an order instead.
	column trueai_is_erp
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7d9e4a19-7c94-4224-ad6f-c5331b95b036
		summarizeBy: none
		sourceColumn: trueai_is_erp

		annotation SummarizationSetBy = Automatic

	/// Opportunity's account id
	column trueai_account_id
		dataType: string
		lineageTag: 38aace67-e071-4e69-8e17-bfe4b3611c6b
		summarizeBy: none
		sourceColumn: trueai_account_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's account id rule
	column trueai_account_id_rule
		dataType: int64
		formatString: 0
		lineageTag: ada4f524-9e2e-49ea-8afa-8bb8d8bf6e1e
		summarizeBy: sum
		sourceColumn: trueai_account_id_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's account id confidence
	column trueai_account_id_conf
		dataType: double
		lineageTag: 47a16c39-3029-4312-8b23-238b97b72a29
		summarizeBy: sum
		sourceColumn: trueai_account_id_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Test model
	column trueai_test
		dataType: string
		lineageTag: 8235a218-47c3-488d-94b6-f0fc6734df6a
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	/// Test model confidence
	column trueai_test_conf
		dataType: double
		lineageTag: c26bab90-9678-4bff-a19d-3c932528c7de
		summarizeBy: sum
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Test model rule
	column trueai_test_rule
		dataType: string
		lineageTag: bb9e0b1e-408f-4af7-8170-f562456c840b
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	/// Test model debug information
	column trueai_test_debug
		dataType: string
		lineageTag: b2c5a489-baa2-4e76-9490-72ff85b96c81
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	/// Opportunity's close date rule
	column trueai_close_date_rule
		dataType: int64
		formatString: 0
		lineageTag: 4a805e69-9ff1-4921-9f82-d28e45171d26
		summarizeBy: sum
		sourceColumn: trueai_close_date_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's start date rule
	column trueai_start_date_rule
		dataType: int64
		formatString: 0
		lineageTag: 97453820-32b1-4563-9da8-f3df29fc9a57
		summarizeBy: sum
		sourceColumn: trueai_start_date_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity creation date rule
	column trueai_created_on_rule
		dataType: int64
		formatString: 0
		lineageTag: c0fbf987-1837-4e35-b070-79819bf797be
		summarizeBy: sum
		sourceColumn: trueai_created_on_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity creator's id rule
	column trueai_creator_id_rule
		dataType: int64
		formatString: 0
		lineageTag: dcbe66ad-1b7d-48af-af14-ea824512d9ba
		summarizeBy: sum
		sourceColumn: trueai_creator_id_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity owner's id rule
	column trueai_owner_id_rule
		dataType: int64
		formatString: 0
		lineageTag: 7e8df0f3-1876-44dd-83cf-d5f5d63aa703
		summarizeBy: sum
		sourceColumn: trueai_owner_id_rule

		annotation SummarizationSetBy = Automatic

	/// cust_text1
	column cust_text1
		dataType: string
		lineageTag: e48fcd0a-3356-4007-a9e6-6d394a682b00
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	/// cust_text2
	column cust_text2
		dataType: string
		lineageTag: 5ebbaece-ef39-4c52-b8ff-6172a75cae84
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	/// cust_text3
	column cust_text3
		dataType: string
		lineageTag: c6437621-96ff-47ba-bcf9-194ddadcc939
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	/// cust_text4
	column cust_text4
		dataType: string
		lineageTag: d5b944c2-4b57-4489-9bd4-46eedae481f3
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	/// cust_text5
	column cust_text5
		dataType: string
		lineageTag: c0b6e9c7-8274-4915-8d1c-de54e2859974
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	/// cust_num1
	column cust_num1
		dataType: double
		lineageTag: 1703943b-4f7a-4ea8-9e41-044d05ba67e3
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num2
	column cust_num2
		dataType: double
		lineageTag: 158a4065-a0b1-43e1-987b-408d2b323a9c
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num3
	column cust_num3
		dataType: double
		lineageTag: a955c0ad-aad2-4b12-9e60-bdbbcf47ff30
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num4
	column cust_num4
		dataType: double
		lineageTag: 253ab445-e75c-43eb-8931-0406d3bf798a
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num5
	column cust_num5
		dataType: double
		lineageTag: f8ea7d53-c480-4f9a-aa20-8c84078f9998
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num6
	column cust_num6
		dataType: double
		lineageTag: 75d92bbc-8a2a-4892-b6f6-92c3a246fff8
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num7
	column cust_num7
		dataType: double
		lineageTag: ed3a4644-5693-4232-820a-d8a7914af484
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_bool1
	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 71b1d167-6b8d-408b-a435-68e504812741
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	/// cust_bool2
	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 190fd143-80cf-4c29-a07e-c8662f559509
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	/// Column trueai_sale_type_num.
	column trueai_sale_type_num
		dataType: int64
		formatString: 0
		lineageTag: d5ad6812-4d01-47da-8e56-fcbda475547e
		summarizeBy: sum
		sourceColumn: trueai_sale_type_num

		annotation SummarizationSetBy = Automatic

	/// Column 'col.opp_age' =.
	column 'col.opp_age' =
			
			var _current_date = TODAY()
			var _created_date = opps[crm_created_on]
			var res = DATEDIFF(_created_date, _current_date, DAY)
			RETURN
			res
		formatString: #" days"
		lineageTag: 7ea63bba-513e-4b40-8713-6e4bff3da1fe
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column 'col.trueai_opp_stages_recorded' = ```.
	column 'col.trueai_opp_stages_recorded' = ```
			
			var opp_id = opps[_sys_doc_id] // get the opp i
			var res = CALCULATE(DISTINCTCOUNT(open_pipeline[trueai_stage_name]), open_pipeline[crm_opp_id] = opp_id) // distinct count # of opp_pieline values 
			RETURN res 
			```
		formatString: 0
		lineageTag: 226857c2-ca7c-42d3-aea7-98e34910b4fb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_days' = ```.
	column 'col.trueai_days' = ```
			
			 var days = [_sys_filt_end_date] - [_sys_filt_start_date] // get days 
			 var res = if ( opps[crm_is_closed] = false , BLANK(), days ) // closed only
			 return days 
			```
		dataType: int64
		formatString: #" days"
		lineageTag: cad72a71-450b-4da8-a9d5-37b2e4ab1a83
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Opportunity's loss reason in the CRM
	column crm_loss_reason
		dataType: string
		lineageTag: 1d8edd5f-2f0e-403b-8819-4223be800caa
		summarizeBy: none
		sourceColumn: crm_loss_reason

		annotation SummarizationSetBy = Automatic

	/// CRM pipeline id of the opportunity
	column crm_pipeline_id
		dataType: string
		lineageTag: b68cd95a-ec03-4a4d-a7c2-84a9db8377e5
		summarizeBy: none
		sourceColumn: crm_pipeline_id

		annotation SummarizationSetBy = Automatic

	/// CRM pipeline name of the opportunity
	column crm_pipeline_name
		dataType: string
		lineageTag: 098a82b7-496c-47ac-b6d3-f8daea0efa57
		summarizeBy: none
		sourceColumn: crm_pipeline_name

		annotation SummarizationSetBy = Automatic

	/// Opportunity's loss reason
	column trueai_loss_reason
		dataType: string
		lineageTag: 2227ec9d-5ce9-418c-b27a-316c37be4cbb
		summarizeBy: none
		sourceColumn: trueai_loss_reason

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage ID in the CRM
	column crm_stage_id
		dataType: string
		lineageTag: b2fe47bb-23b0-42c2-964a-1654c44a999d
		summarizeBy: none
		sourceColumn: crm_stage_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage ID
	column trueai_stage_id
		dataType: string
		lineageTag: 4ca57c41-1c46-41de-89ed-fc4817a0d140
		summarizeBy: none
		sourceColumn: trueai_stage_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage name
	column trueai_stage_name
		dataType: string
		lineageTag: 0dabd22b-ac43-4dd5-af35-1eeb3d0925ae
		summarizeBy: none
		sourceColumn: trueai_stage_name

		annotation SummarizationSetBy = Automatic

	/// Pipeline name of the opportunity
	column trueai_pipeline_name
		dataType: string
		lineageTag: 9627b322-883d-45f4-8178-4b9ab26ce3d4
		summarizeBy: none
		sourceColumn: trueai_pipeline_name

		annotation SummarizationSetBy = Automatic

	/// Opportunity Age
	column trueai_age
		dataType: int64
		formatString: 0
		lineageTag: cc25fbc2-deb6-42f0-9b30-3f4c6f7aa266
		summarizeBy: sum
		sourceColumn: trueai_age

		annotation SummarizationSetBy = Automatic

	/// Opportunity discount percentage tier
	column trueai_discount_pct_tier
		dataType: string
		lineageTag: d5d56924-c4f6-4819-ab08-6cca48c59b9f
		summarizeBy: none
		sourceColumn: trueai_discount_pct_tier

		annotation SummarizationSetBy = Automatic

	/// Opportunity's NNB amount
	column trueai_nnb_amt
		dataType: double
		lineageTag: e9f6bc83-15bd-48c0-91ec-d57c3a73a98b
		summarizeBy: sum
		sourceColumn: trueai_nnb_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's downgrade amount
	column trueai_downgrade_amt
		dataType: double
		lineageTag: bd379382-b3be-4dd3-8ef7-189895232667
		summarizeBy: sum
		sourceColumn: trueai_downgrade_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's Cross-Sale amount
	column trueai_cross_sale_amt
		dataType: double
		lineageTag: a2b152b4-9691-4e96-8d53-7cac21ea41fe
		summarizeBy: sum
		sourceColumn: trueai_cross_sale_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's renewal amount
	column trueai_renewal_amt
		dataType: double
		lineageTag: 5130b759-05ac-429f-b8d6-b640da10ec5c
		summarizeBy: sum
		sourceColumn: trueai_renewal_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's expansion amount
	column trueai_expansion_amt
		dataType: double
		lineageTag: 2aa9029e-00e5-4143-b125-ff4976f53cd7
		summarizeBy: sum
		sourceColumn: trueai_expansion_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's one time amount
	column trueai_one_time_amt
		dataType: double
		lineageTag: 89b7956b-1362-4c1b-b5b3-94b83d51344b
		summarizeBy: sum
		sourceColumn: trueai_one_time_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's non determinable amount
	column trueai_nd_amt
		dataType: double
		lineageTag: 0ebcb086-8b02-4f52-8347-ba15c0ad5583
		summarizeBy: sum
		sourceColumn: trueai_nd_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's ARR amount
	column trueai_arr_amt
		dataType: double
		lineageTag: 1093cd30-1cdd-48a7-8902-022cc75af8cb
		summarizeBy: sum
		sourceColumn: trueai_arr_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column 'col.trueai_list_price_amt' = ```.
	column 'col.trueai_list_price_amt' = ```
			
			[trueai_booking_amt]-[trueai_discount_amt]
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d7a4f08b-42aa-4f41-8ae6-082461941af8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Opportunity's last crm stage, before it was lost
	column trueai_lost_crm_stage
		dataType: string
		lineageTag: 4658f8e3-0042-4231-b182-53675d8cb4a2
		summarizeBy: none
		sourceColumn: trueai_lost_crm_stage

		annotation SummarizationSetBy = Automatic

	/// Opportunity's Initial Subscription amount
	column trueai_initial_subscription_amt
		dataType: double
		lineageTag: 30ddaf79-4844-4d47-bc28-72376f6f0d3e
		summarizeBy: sum
		sourceColumn: trueai_initial_subscription_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_pred_booking_amt
		dataType: string
		lineageTag: be8c29d5-414a-45f7-9080-c92691b06859
		summarizeBy: none
		sourceColumn: trueai_pred_booking_amt

		annotation SummarizationSetBy = Automatic

	column trueai_pred_close_date
		dataType: string
		lineageTag: ba1e2de3-123b-4bba-9662-49a2bb9f0af9
		summarizeBy: none
		sourceColumn: trueai_pred_close_date

		annotation SummarizationSetBy = Automatic

	column trueai_pred_close_date_if_won
		dataType: string
		lineageTag: 1c29cddb-7aa3-47f6-ba9e-74298cc1897d
		summarizeBy: none
		sourceColumn: trueai_pred_close_date_if_won

		annotation SummarizationSetBy = Automatic

	column trueai_pred_close_date_if_lost
		dataType: string
		lineageTag: 1f16ad66-2a7a-48ad-b1c9-1523b76c79fb
		summarizeBy: none
		sourceColumn: trueai_pred_close_date_if_lost

		annotation SummarizationSetBy = Automatic

	partition opps-844b2383-8abc-4f81-b4fd-92ba5ff8a92a = m
		mode: import
		source = ```
				let
				
				    
				    dbTable = getDBTable("opps"), // get the right table
				
				
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"crm_pipeline_name", type text},
				        {"crm_stage_id", type text},
				        {"crm_stage_name", type text},
				        {"crm_stage_num", Int64.Type},
				        {"crm_type", type text},
				        {"cust_bool1", type logical},
				        {"cust_bool2", type logical},
				        {"cust_num1", type number},
				        {"cust_num2", type number},
				        {"cust_num3", type number},
				        {"cust_num4", type number},
				        {"cust_num5", type number},
				        {"cust_num6", type number},
				        {"cust_num7", type number},
				        {"cust_text1", type text},
				        {"cust_text2", type text},
				        {"cust_text3", type text},
				        {"cust_text4", type text},
				        {"cust_text5", type text},
				        {"trueai_account_id", type text},
				        {"trueai_account_id_conf", type number},
				        {"trueai_account_id_rule", Int64.Type},
				        {"trueai_addr_city", type text},
				        {"trueai_addr_country", type text},
				        {"trueai_addr_lat", type number},
				        {"trueai_addr_long", type number},
				        {"trueai_addr_postal_code", type text},
				        {"trueai_addr_rule", Int64.Type},
				        {"trueai_addr_state", type text},
				        {"trueai_addr_street", type text},
				        {"trueai_age", Int64.Type},
				        {"trueai_arr_amt", type number},
				        {"trueai_booking_amt", type number},
				        {"trueai_booking_amt_currency_rule", Int64.Type},
				        {"trueai_booking_amt_rule", Int64.Type},
				        {"trueai_close_date", type datetime},
				        {"trueai_close_date_rule", Int64.Type},
				        {"trueai_company_size", type text},
				        {"trueai_company_size_rule", Int64.Type},
				        {"trueai_complt", type number},
				        {"trueai_complt_contact", type number},
				        {"trueai_complt_marketing", type number},
				        {"trueai_created_from_entity", type text},
				        {"trueai_created_from_id", type text},
				        {"trueai_created_on", type datetime},
				        {"trueai_created_on_rule", Int64.Type},
				        {"trueai_creator_id", type text},
				        {"trueai_creator_id_rule", Int64.Type},
				        {"trueai_cross_sale_amt", type number},
				        {"trueai_discount_amt", type number},
				        {"trueai_discount_pct", type number},
				        {"trueai_discount_pct_tier", type text},
				        {"trueai_downgrade_amt", type number},
				        {"trueai_dur", Int64.Type},
				        {"trueai_expansion_amt", type number},
				        {"trueai_industry", type text},
				        {"trueai_industry_conf", type number},
				        {"trueai_industry_rule", Int64.Type},
				        {"trueai_initial_subscription_amt", type number},
				        {"trueai_is_erp", type logical},
				        {"trueai_is_new_logo", type logical},
				        {"trueai_is_won", type logical},
				        {"trueai_leadsource", type text},
				        {"trueai_leadsource_conf", type number},
				        {"trueai_leadsource_rule", Int64.Type},
				        {"trueai_loss_reason", type text},
				        {"trueai_lost_crm_stage", type text},
				        {"trueai_nd_amt", type number},
				        {"trueai_nnb_amt", type number},
				        {"trueai_one_time_amt", type number},
				        {"trueai_opp_stage_late_date", type datetime},
				        {"trueai_opp_stage_mid_date", type datetime},
				        {"trueai_owner_id", type text},
				        {"trueai_owner_id_rule", Int64.Type},
				        {"trueai_pipeline_name", type text},
				        {"trueai_prob_of_win", type number},
				        {"trueai_propensity", type text},
				        {"trueai_propensity_num", Int64.Type},
				        {"trueai_renewal_amt", type number},
				        {"trueai_sale_type", type text},
				        {"trueai_sale_type_conf", type number},
				        {"trueai_stage", type text},
				        {"trueai_stage_id", type text},
				        {"trueai_stage_name", type text},
				        {"trueai_start_date_rule", Int64.Type},
				        {"trueai_test", type text},
				        {"trueai_test_conf", type number},
				        {"trueai_test_debug", type text},
				        {"trueai_test_rule", type text},
				        {"_sys_as_of", type datetime},
				        {"_sys_doc_id", type text},
				        {"_sys_filt_end_date", type date},
				        {"_sys_filt_start_date", type date},
				        {"_sys_is_active", type logical},
				        {"_sys_last_modified_on", type datetime},
				        {"_sys_ssr_id", type text},
				        {"crm_account_custom_value_1", type text},
				        {"crm_account_custom_value_2", type text},
				        {"crm_account_custom_value_3", type text},
				        {"crm_account_id", type text},
				        {"crm_booking_amt", type number},
				        {"crm_close_date", type datetime},
				        {"crm_complt", type number},
				        {"crm_complt_contact", type number},
				        {"crm_complt_custom", type number},
				        {"crm_complt_marketing", type number},
				        {"crm_created_on", type datetime},
				        {"crm_creator_id", type text},
				        {"crm_currency", type text},
				        {"crm_custom_value_1", type text},
				        {"crm_custom_value_2", type text},
				        {"crm_custom_value_3", type text},
				        {"crm_deep_link", type text},
				        {"crm_is_closed", type logical},
				        {"crm_is_won", type logical},
				        {"crm_last_act_time", type datetime},
				        {"crm_leadsource", type text},
				        {"crm_loss_reason", type text},
				        {"crm_modified_on", type datetime},
				        {"crm_name", type text},
				        {"crm_owner_id", type text},
				        {"crm_pipeline_id", type text}
				    }),
				    #"Removed Duplicates" = Table.Distinct(dbTableTyped, {"_sys_doc_id"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Duplicates", "trueai_sale_type_num", each if [trueai_sale_type] = "New Logo Sale" then 1 else if [trueai_sale_type] = "Existing Customer Sale" then 2 else if [trueai_sale_type] = "Renewal" then 3 else 4),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"trueai_sale_type_num", Int64.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

