table opps_stages
	lineageTag: 062d8b8c-e3dc-4c84-8a55-689cbb83bec6

	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: c1f5ae98-122d-49dd-afd9-5e0a326c56cf
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: a33d5dc2-b283-46bc-b3d6-37918b33703f
			defaultHierarchy: LocalDateTable_7b615310-6988-4df7-8265-cb6a6249e780.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_doc_id
		dataType: string
		lineageTag: 74b1c9b9-5623-48c2-818b-d5dc3f57cf05
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_is_deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 62567072-bc7e-40cf-b7bd-80bb4e912120
		summarizeBy: none
		sourceColumn: _sys_is_deleted

		annotation SummarizationSetBy = Automatic

	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: f9e8fe39-0204-4635-b640-88403f92fdad
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: afc64c59-9f33-4c7e-9d3a-0fe719130cd0
			defaultHierarchy: LocalDateTable_c1ba4798-8ba4-4972-a733-5f037f9a0980.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 74748376-d500-4ed3-8348-566c98f7059d
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 37540b78-fe7a-4114-a5b4-2b8daef65861
			defaultHierarchy: LocalDateTable_aa445b8d-4f02-4443-ad0b-595becd418a6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: eec1d3f0-793f-4f3b-9319-7db18b138267
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_description
		dataType: string
		lineageTag: 2c9c6cfa-3475-4351-8439-8837281b3451
		summarizeBy: none
		sourceColumn: crm_description

		annotation SummarizationSetBy = Automatic

	column crm_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d9b7d8c8-2e2c-45c2-962d-eeb74d542e79
		summarizeBy: none
		sourceColumn: crm_is_active

		annotation SummarizationSetBy = Automatic

	column crm_is_closed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0cb587ea-8484-4cd8-bec9-08137b47b529
		summarizeBy: none
		sourceColumn: crm_is_closed

		annotation SummarizationSetBy = Automatic

	column crm_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dbc4a19a-f728-4c76-8efa-495b17782f2f
		summarizeBy: none
		sourceColumn: crm_is_won

		annotation SummarizationSetBy = Automatic

	column crm_modified_by
		dataType: string
		lineageTag: d54e6a7a-7d9f-4388-8203-299df4e1f4c8
		summarizeBy: none
		sourceColumn: crm_modified_by

		annotation SummarizationSetBy = Automatic

	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: b4092a66-e2ba-4d23-a002-ae347f11dfad
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: e68fca1e-995c-41c2-a11e-20ad89482bfb
			defaultHierarchy: LocalDateTable_9bdae528-318c-41d5-b5cc-2e19cea1aa4d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_name
		dataType: string
		lineageTag: fe42da05-83ef-4830-818c-f374b53748d0
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	column crm_order
		dataType: double
		formatString: 0
		lineageTag: 378bdc72-d5fb-42fc-9b93-9a80cdca900c
		summarizeBy: sum
		sourceColumn: crm_order

		annotation SummarizationSetBy = Automatic

	column crm_prob_of_win
		dataType: double
		lineageTag: 2e6d303c-c23e-4000-9e3e-6aa229425b7d
		summarizeBy: sum
		sourceColumn: crm_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.open_pipeline_pace_ref_avg_days_in_opp' = ```
			
			var ref_date = [meas.companies_history_reference_date]  // get the ref date
			var period_end = ref_date // use ref date 
			var period_start = period_end - 366 // one year before
			var stage = opps_stages[crm_name] // get the stage without any relationships set 
			
			var filtered_won_opps = filter(
			                 opps ,  
			                 opps[trueai_is_won]= true &&  
			                 opps[_sys_filt_end_date] >= period_start &&  
			                 opps[_sys_filt_end_date] < period_end                  // find filter opps based on ref period
			            )
			var filtered_open_pipeline = CALCULATETABLE(open_pipeline,  open_pipeline[trueai_can_be_excluded] =false && open_pipeline[_sys_filt_end_date] >= period_start && open_pipeline[_sys_filt_end_date] < period_end  &&  open_pipeline[trueai_stage_name] = stage ) // get the items we care about 
			var filtered_final  = FILTER(filtered_open_pipeline ,  open_pipeline[crm_opp_id] IN SELECTCOLUMNS(filtered_won_opps, [_sys_doc_id])) // filter both together 
			
			var days = AVERAGEX(filtered_final, [trueai_days_in_opp]) // get the avg
			return  days// COUNTROWS(filtered_final)
			```
		lineageTag: 688831ab-5d44-41bd-b4b6-3fd1bf9c77fb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.open_pipeline_pace_ref_avg_days_in_stage' = ```
			
			var ref_date = [meas.companies_history_reference_date]  // get the ref date
			var period_end = ref_date // use ref date 
			var period_start = period_end - 366 // one year before
			var stage = opps_stages[crm_name] // get the stage - no relationships set 
			
			
			var filtered_won_opps = filter(
			    opps ,  
			    opps[trueai_is_won]= true &&  
			    opps[_sys_filt_end_date] >= period_start &&  opps[_sys_filt_end_date] < period_end ) // find filter opps based on ref period
			var filtered_open_pipeline = CALCULATETABLE(open_pipeline,  open_pipeline[trueai_can_be_excluded] =false && open_pipeline[_sys_filt_end_date] >= period_start && open_pipeline[_sys_filt_end_date] < period_end  &&  open_pipeline[trueai_stage_name] = stage) // get the items we care about 
			var filtered_final  = FILTER(filtered_open_pipeline ,  open_pipeline[crm_opp_id] IN SELECTCOLUMNS(filtered_won_opps, [_sys_doc_id])) // filter both together 
			
			var days = AVERAGEX(filtered_final, [trueai_days_in_stage]) // get the avg
			return  days// COUNTROWS(filtered_final)
			```
		lineageTag: 67bcc310-0c96-45ad-9526-9df9bb6c1e82
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.open_pipeline_pace_ref_std_dev_days_in_opp' = ```
			
			var ref_date = [meas.companies_history_reference_date]  // get the ref date
			var period_end = ref_date // use ref date 
			var period_start = period_end - 366 // one year before
			var stage = opps_stages[crm_name] // get the stage - no relationships set 
			
			
			
			var filtered_won_opps = filter(opps ,  opps[trueai_is_won]= true &&  opps[_sys_filt_end_date] >= period_start &&  opps[_sys_filt_end_date] < period_end ) // find filter opps based on ref period
			var filtered_open_pipeline = CALCULATETABLE(open_pipeline,  open_pipeline[trueai_can_be_excluded] =false && open_pipeline[_sys_filt_end_date] >= period_start && open_pipeline[_sys_filt_end_date] < period_end  &&  open_pipeline[trueai_stage_name] = stage ) // get the items we care about 
			var filtered_final  = FILTER(filtered_open_pipeline ,  open_pipeline[crm_opp_id] IN SELECTCOLUMNS(filtered_won_opps, [_sys_doc_id])) // filter both together 
			
			var days = STDEVX.P(filtered_final, [trueai_days_in_opp]) // get the sdt dev
			return  days// COUNTROWS(filtered_final)
			```
		lineageTag: 311cfe11-b294-4ea7-a148-a4344e990fd1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'col.open_pipeline_pace_ref_std_dev_days_in_stage' = ```
			
			var ref_date = [meas.companies_history_reference_date]  // get the ref date
			var period_end = ref_date // use ref date 
			var period_start = period_end - 366 // one year before
			var stage = opps_stages[crm_name] // get the stage - no relationships set 
			
			
			
			var filtered_won_opps = filter(opps ,  opps[trueai_is_won]= true &&  opps[_sys_filt_end_date] >= period_start &&  opps[_sys_filt_end_date] < period_end ) // find filter opps based on ref period
			var filtered_open_pipeline = CALCULATETABLE(open_pipeline,  open_pipeline[trueai_can_be_excluded] =false && open_pipeline[_sys_filt_end_date] >= period_start && open_pipeline[_sys_filt_end_date] < period_end  &&  open_pipeline[trueai_stage_name] = stage) // get the items we care about 
			var filtered_final  = FILTER(filtered_open_pipeline ,  open_pipeline[crm_opp_id] IN SELECTCOLUMNS(filtered_won_opps, [_sys_doc_id])) // filter both together 
			
			var days = STDEVX.P(filtered_final, [trueai_days_in_stage]) // get the sdt dev
			return  days// COUNTROWS(filtered_final)
			```
		lineageTag: 6fa194b3-f9a5-4346-970b-c4401c20a1c4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_pipeline_id
		dataType: string
		lineageTag: e5055aec-7c36-4b81-86ed-ec5ccee4c1a8
		summarizeBy: none
		sourceColumn: crm_pipeline_id

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_name
		dataType: string
		lineageTag: 23bd5416-5478-4201-9f4a-3d76e82364e4
		summarizeBy: none
		sourceColumn: crm_pipeline_name

		annotation SummarizationSetBy = Automatic

	partition opps_stages = m
		mode: import
		source = ```
				let
				
				    
				    dbTable = getDBTable("opps_stages"), // get the right table
				
				
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"_sys_as_of", type datetime},
				        {"_sys_doc_id", type text},
				        {"_sys_is_deleted", type logical},
				        {"_sys_last_modified_on", type datetime},
				        {"crm_created_on", type datetime},
				        {"crm_creator_id", type text},
				        {"crm_description", type text},
				        {"crm_is_active", type logical},
				        {"crm_is_closed", type logical},
				        {"crm_is_won", type logical},
				        {"crm_modified_by", type text},
				        {"crm_modified_on", type datetime},
				        {"crm_name", type text},
				        {"crm_order", type number},
				        {"crm_pipeline_id", type text},
				        {"crm_pipeline_name", type text},
				        {"crm_prob_of_win", type number}
				    })
				    
				in
				    dbTableTyped
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

