/// Table orders_opps.
table orders_opps
	description: "TODO: provide business definition for this table."
	lineageTag: 21dc53e5-4fe5-4b36-9252-a0ee5b8fe761

	/// Column Flag.
	column Flag
		description: "Indicates whether flag."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 374c10a6-977c-4202-8222-0b2cd7ea25c4
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	/// Column Label.
	column Label
		description: "Text label for label."
		dataType: string
		lineageTag: 23bdfafe-a2d8-4c17-8d2b-1a81f48f6fd4
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition orders_opps = m
		mode: import
		source =
				let
				    Source = "[#(lf)        {   ""Flag"":1,#(lf)            ""Label"" : ""Orders"",#(lf)          },#(lf)        {   ""Flag"":0,#(lf)            ""Label"" : ""Opps"",#(lf)     }    #(lf)    ]",
				
				    ParsedJson = Json.Document(Source),
				    ToTable = Table.FromList(ParsedJson, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    Expanded = Table.ExpandRecordColumn(ToTable, "Column1", {
				        "Flag", "Label"
				    }),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Expanded,{{"Flag", type logical}, {"Label", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

