/// CRM entity for the reference list for all available products associated with opportunities enriched with TrueAI predictive insights.
table products
	lineageTag: 40b9c0cb-f2d0-4937-88d6-57242cf9d494

	/// Purpose: Product Family Unique Accounts.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.product_family_unique_accounts' =
			
			CALCULATE(
			DISTINCTCOUNT(			opps[_sys_ssr_id]        // distinct count of the accounts			)			)
		formatString: 0
		displayFolder: _product_family_screen
		lineageTag: 67ed0c15-661b-48cc-bce6-2ad1c8b456eb

	/// Purpose: Product Family Unique Deals.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.product_family_unique_deals' =
			
			CALCULATE(
			DISTINCTCOUNT(			opps[_sys_doc_id]   // get the disticnt count of _sys_doc_id as unique deals			)			)
		formatString: 0
		displayFolder: _product_family_screen
		lineageTag: 3669683d-1215-4526-8258-d717340b2d21

	/// Purpose: Product Family Total Price.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.product_family_total_price' = 
			
			CALCULATE(
			SUM(			opp_line_items[trueai_total_price]              // get the total sum 			)			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _product_family_screen
		lineageTag: fa69cd79-aadb-49d4-8bb8-5518cdbb2364

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Purpose: Product Family Avg Qty.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.product_family_avg_qty' = 
			
			CALCULATE(
			AVERAGE(			opp_line_items[trueai_qty]      // get the average qty of the opp line items 			)			)
		formatString: 0.00
		displayFolder: _product_family_screen
		lineageTag: 2827e35a-98ac-4e68-8efb-3d73c5ab166f

	/// Purpose: Product Family Avg List Price.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.product_family_avg_list_price' =
			
			CALCULATE(
			AVERAGE(			opp_line_items[trueai_list_price]           // get the average  opp line item's trueai_list_price			)			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _product_family_screen
		lineageTag: 0d5c6350-bece-4e5f-87ca-f565b988385a

	/// Purpose: Product Family Avg Unit Price.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.product_family_avg_unit_price' =
			
			CALCULATE(
			AVERAGE(			opp_line_items[trueai_unit_price]       //get the average of opp line items "trueai_unit_price"			)			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _product_family_screen
		lineageTag: bd2bbeee-6bb7-48fc-8714-76c18e5150e1

	/// Purpose: Product Family Total List Price.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.product_family_total_list_price' =
			
			CALCULATE(
			SUMX(			opp_line_items,			opp_line_items[trueai_list_price] * opp_line_items[trueai_qty]          // get the total list price (trueai_list_price * trueai_qty)			)			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _product_family_screen
		lineageTag: a5428bcf-0692-491a-946c-1a037fba6693

	/// Purpose: Product Family Avg Sales Cycle.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.product_family_avg_sales_cycle' =
			
			CALCULATE(
			AVERAGE(			ssr_history[step_length_in_days]            // get the average sales cycle days			)			)
		formatString: #,##0" Days"
		displayFolder: _product_family_screen
		lineageTag: ba65f774-c476-469e-9c7f-e1d29bc0b6c7

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Product Family Avg Time Spent Hrs.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.product_family_avg_time_spent_hrs' =
			
			CALCULATE(
			AVERAGE(			ssr_history[stkhlds_all_adj_dur]   // get the average of stkhlds_all_adj_dur			)			)/3600  // converting into hrs
		formatString: #,##0.0" hrs"
		displayFolder: _product_family_screen
		lineageTag: 19ae53ea-a862-4988-a9da-c1a0779cfa31

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Product Family Total Time Spent Hrs.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.product_family_total_time_spent_hrs' = 
			
			CALCULATE(
			SUMX(			ssr_history,			ssr_history[stkhlds_all_adj_dur]        // get the total adjusted duration of the stkhlds			)			)/3600      // convert the duration into hrs 
		formatString: #,##0" hrs"
		displayFolder: _product_family_screen
		lineageTag: ee99d7e9-07ee-406a-bba8-27a51c0e95c5

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Product Family Booking Pct.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Percentage
	measure 'meas.product_family_booking_pct' = 
			
			var total_price = CALCULATE(
			SUM(			opp_line_items[trueai_total_price]              // get the total sum  removing all filters			),			ALL(opp_line_items)			)
			
			var _prodct_price = [meas.product_family_total_price]   // get the product price 
			
			var res = DIVIDE(
			_prodct_price,			total_price,			0			)       // get the ratio
			
			RETURN
			res
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _product_family_screen
		lineageTag: 28d441be-1f36-40c1-91fb-b4d6a82b39bc

	/// Purpose: Product Family Account Penetration Pct.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Percentage
	measure 'meas.product_family_account_penetration_pct' =
			
			var _total_acc = CALCULATE(
			DISTINCTCOUNT(			opps[_sys_ssr_id]        // distinct count of the accounts removing filters			),			ALL(products)			)
			
			var _accts = [meas.product_family_unique_accounts] /// get the _accts count productwise
			
			var res = DIVIDE(
			_accts,			_total_acc,         // get the ratio			0			)
			
			RETURN
			res
		formatString: 0%;-0%;0%
		displayFolder: _product_family_screen
		lineageTag: 29489642-76e8-4b94-b39a-8201d290eba8

	/// Purpose: Product Family Included Won Deals Pct.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Percentage
	measure 'meas.product_family_included_won_deals_pct' = 
			
			
			var _total_deals = CALCULATE(
			DISTINCTCOUNT(			opps[_sys_doc_id]   // get the disticnt count of _sys_doc_id as unique deals removed all filtrs from product table			),			ALL(products)			)
			
			var _deals = [meas.product_family_unique_deals]         // get the unique counts product wise
			
			var res = DIVIDE(
			_deals,			_total_deals,       // get the ratio 			0			)
			
			RETURN
			res
		formatString: 0%;-0%;0%
		displayFolder: _product_family_screen
		lineageTag: 146208f2-5b08-4bbb-bcca-b7800a76fd98

	/// Purpose: Product Family All Won Deals.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.product_family_all_won_deals' =
			
			CALCULATE(
			DISTINCTCOUNT(			opps[_sys_doc_id]   // get the disticnt count of _sys_doc_id as unique deals			),     // get the unique deals count which won			opps[trueai_is_won] = true			)
		formatString: 0
		displayFolder: _product_family_screen
		lineageTag: b0aefd2a-0119-4726-9652-18e4338db9f0

	/// Purpose: Product Family Win Deals Pct.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Percentage
	measure 'meas.product_family_win_deals_pct' =
			
			var total_won = CALCULATE(
			DISTINCTCOUNT(			opps[_sys_doc_id]   // get the disticnt count of _sys_doc_id as unique deals			)     // get the unique deals count which won			
			)
			
			var _deals = [meas.product_family_all_won_deals] // get the deals count productwise
			var res = DIVIDE(
			_deals,			total_won,       // get the ratio			0			)
			
			RETURN
			res
		formatString: 0%;-0%;0%
		displayFolder: _product_family_screen
		lineageTag: fdb3ea90-281d-45fb-ba9b-7487dad25a15

	/// Purpose: Product Family Avg Expected Win Rate Pct.
	/// Logic: Derived from referenced measures and columns.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Percentage
	measure 'meas.product_family_avg_expected_win_rate_pct' =
			
			CALCULATE(
			AVERAGE(			opps[trueai_prob_of_win]        // get the average of opps prob of win			)			)
		formatString: 0%;-0%;0%
		displayFolder: _product_family_screen
		lineageTag: f8724243-e37e-4281-a0a3-268b9b9e1162

	/// Unique record identifier, based on the ID of the document in the remote system (such as Salesforce ID)
	column _sys_doc_id
		dataType: string
		lineageTag: 0bcf5f8d-813c-4af1-8ff2-1711f569dc21
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Product's currency in the CRM
	column crm_currency
		dataType: string
		lineageTag: a79158e9-bb2f-4ac6-aa04-d59d9070d725
		summarizeBy: none
		sourceColumn: crm_currency

		annotation SummarizationSetBy = Automatic

	/// Product's description in the CRM
	column crm_description
		dataType: string
		lineageTag: 87fa0f42-a299-4c7c-9c1e-d4d03d743301
		summarizeBy: none
		sourceColumn: crm_description

		annotation SummarizationSetBy = Automatic

	/// Product's family in the CRM
	column crm_family
		dataType: string
		lineageTag: f07d005b-7aff-468a-b047-ee51d9633e58
		summarizeBy: none
		sourceColumn: crm_family

		annotation SummarizationSetBy = Automatic

	/// Product name in the CRM
	column crm_name
		dataType: string
		lineageTag: c459f7a9-f02b-4d4f-9d61-4a1c6c4f0d02
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	/// Product code in the CRM
	column crm_product_code
		dataType: string
		lineageTag: 12a4fe8b-05e6-452e-95e6-59756c1a0e9f
		summarizeBy: none
		sourceColumn: crm_product_code

		annotation SummarizationSetBy = Automatic

	/// The date of the last data request from the platform
	column _sys_as_of
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d6d2a88-e0fd-4a53-a783-b1c394ed9399
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 98fa61a8-db46-41eb-8f98-980f9dab62a1
			defaultHierarchy: LocalDateTable_daac65e6-0114-497c-923e-742489f6006b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the record was set to inactive in the remote system
	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6049249d-4611-49a2-b7a0-94c4441d9366
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the record was set to deleted in the remote system
	column _sys_is_deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c5a89cb9-af6f-47bf-bf0d-0b6d8bbe3ae9
		summarizeBy: none
		sourceColumn: _sys_is_deleted

		annotation SummarizationSetBy = Automatic

	/// The date of the last data modification in the platform
	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: df5e128e-88e9-4fea-9517-1fc313135472
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: fc3fba1f-1a76-47b2-8a73-6281f431a718
			defaultHierarchy: LocalDateTable_61b30642-5455-4ae8-a11c-07f96dc2fd68.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Product's creation date in the CRM
	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 2a1ba898-6562-4954-b2e3-2acee0a1085d
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 56f6b4a6-ed16-4b1d-bbc9-5166bb1aa81f
			defaultHierarchy: LocalDateTable_3b57d89a-6c8b-4e68-afcf-59da8b8da4bb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Product's modified on date in the CRM
	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: c7cd9c4b-9bcf-420a-ab35-ce95a53ffd61
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: 228a722d-187c-4f1b-8451-9debe9ea5740
			defaultHierarchy: LocalDateTable_3dee6f31-bd2a-4b1a-ae8b-b79102bc6389.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Product name
	column trueai_name
		dataType: string
		lineageTag: 0ff92be8-6302-4a3d-8878-a435d2db6140
		summarizeBy: none
		sourceColumn: trueai_name

		annotation SummarizationSetBy = Automatic

	/// Product's family
	column trueai_family
		dataType: string
		lineageTag: ccbb5fac-6eb2-4657-a77d-3b4c341b0e08
		summarizeBy: none
		sourceColumn: trueai_family

		annotation SummarizationSetBy = Automatic

	/// Column 'col.product_name' =.
	column 'col.product_name' =
			
			CONCATENATEX(
			    FILTER(
			        products,
			        products[trueai_family] = EARLIER(products[trueai_family])      // filter by product family
			    ),
			    products[trueai_name],          // concatenate product name (trueai_name)
			    ", "
			)
		lineageTag: 7cdcdf75-8856-44f0-bd73-95fdc4173392
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition products-3435f4e2-3f24-4b42-b533-d6c616479e85 = m
		mode: import
		source =
				let
				    dbTable = getDBTable("products"), // get the right table
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"_sys_as_of", type datetime},
				        {"_sys_doc_id", type text},
				        {"_sys_is_active", type logical},
				        {"_sys_is_deleted", type logical},
				        {"_sys_last_modified_on", type datetime},
				        {"crm_created_on", type datetime},
				        {"crm_currency", type text},
				        {"crm_description", type text},
				        {"crm_family", type text},
				        {"crm_modified_on", type datetime},
				        {"crm_name", type text},
				        {"crm_product_code", type text},
				        {"trueai_family", type text},
				        {"trueai_name", type text}
				        }),
				    removeBlank = Table.SelectRows(dbTableTyped, each [_sys_doc_id] <> null and [_sys_doc_id] <> "")
				in
				    removeBlank

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

