/// Table rep_overview_table.
table rep_overview_table
	lineageTag: 35e01a1d-7633-4461-b688-1d08303368c3

	/// Measure meas.rep_overview_metric_name.
	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: See DAX expression.
	/// Dynamic Behavior: See DAX expression.
	/// Format/Type: Unspecified
	measure 'meas.rep_overview_metric_name' =
			
			SWITCH(
			    MAX(rep_overview_table[Source]),
			    "Metric 1", SELECTEDVALUE(performance_metric_1[name]),
			    "Metric 2", SELECTEDVALUE(performance_metric_2[name])
			)
		lineageTag: cc8f6dc6-af1e-4c2a-ac40-049130828c11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Source
		dataType: string
		lineageTag: a696aca9-d6c6-49ef-8e13-a73ce7d92761
		summarizeBy: none
		isNameInferred
		sourceColumn: [Source]

		annotation SummarizationSetBy = Automatic

	partition rep_overview_table = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Source", STRING,
				    {
				        {"Metric 1"},
				        {"Metric 2"}
				    }
				)

	annotation PBI_Id = 97463658ecb142d88472630d997aad5c

