/// Derived entity for the deduplicated and consolidated Single Sales Record (SSR). The source of truth for overall account performance and unified sales process tracking.
table ssr
	lineageTag: cb48d9a8-ea61-48bb-845c-67eb596f90f7

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Percentage
	measure 'meas.ssr_trueai_conversion_rate' = [meas.ssr_trueai_converted_count] / CALCULATE(count(ssr[_sys_doc_id]))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: __needs_attention
		lineageTag: a946bddd-5ee9-4adf-a031-0bb4bbb7b204

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.ssr_trueai_converted_count' = Calculate(distinctcount(ssr_history[_sys_ssr_id]),ssr_history[step_name] ="Prospecting" && ssr_history[step_success] =True )
		formatString: 0
		displayFolder: __needs_attention
		lineageTag: f64fb9f1-a6d6-4e35-ade9-42652b127317

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.ssr_trueai_no_leadsource_count' = 
			
			var val = CALCULATE(count(ssr[_sys_doc_id]), or(ISBLANK(ssr[trueai_leadsource]) = TRUE(),ssr[trueai_leadsource]= "ND" ))
			return if(ISBLANK(val), 0, val)
			
		formatString: 0
		displayFolder: __needs_attention
		lineageTag: 9ff987e5-24d2-453a-8420-d58519669d3c

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Percentage
	measure 'meas.ssr_trueai_no_leadsource_rate' = [meas.ssr_trueai_no_leadsource_count] / CALCULATE(count(ssr[_sys_doc_id]))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: __needs_attention
		lineageTag: 688b74be-7bd5-49c2-ac7d-734bc28f3627

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'measure.ssr_touched_accounts' = Calculate(distinctcount(ssr_history[_sys_ssr_id]),ssr_history[step_name] ="Untouched" && ssr_history[step_success] =True )
		formatString: #,0
		displayFolder: __needs_attention
		lineageTag: 9462abf4-4c76-4f8d-8e7f-6b8baac3f495

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.ssr_new_logo_won_count' = Calculate(distinctcount(ssr_history[_sys_ssr_id]),ssr_history[step_name] ="New Logo Selling" && ssr_history[step_success] =True )
		formatString: #,0
		displayFolder: __needs_attention
		lineageTag: cd0cea50-3fac-4990-8fc2-b523aa9dc032

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Boolean
	measure 'meas.ssr_hsitory_accounts_per_prospecting_rep' = 
			
			var accounts = calculate(DISTINCTCOUNT(ssr_history[_sys_ssr_id]))
			var reps = calculate(DISTINCTCOUNT(ssr_history[step_owner_id]), ssr_history[step_name] = "Prospecting")
			var res = divide (accounts, reps,BLANK())
			return res
			
		displayFolder: __needs_attention
		lineageTag: 9c9c697b-63fb-4798-b59e-6ba7fc7bef9f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.ssr_touch_count' = calculate(count(ssr[trueai_first_touch]))
		formatString: 0
		lineageTag: b668fd30-f94c-43db-9460-63b5490155f1

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.ssr_crm_opp_count' =
			CALCULATE(
			    SUM(ssr[crm_opp_count])
			)
		formatString: 0
		lineageTag: fec59036-1e4c-4a53-b0b8-1c0ff6536bf8

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.leadsource_record_count_sort' =
			
			var rnk = RANKX(
			    FILTER(
			        ALL(ssr[crm_leadsource]),
			        CALCULATE(
			            COUNT(ssr[_sys_doc_id]),
			            FILTER(
			                ALL(ssr),
			                ssr[trueai_leadsource] = MAX(ssr[trueai_leadsource])
			            )
			        ) > 0
			    ),
			    CALCULATE(COUNT(ssr[_sys_doc_id])),
			    ,
			    DESC
			)
			
			var res = MAX(ssr[trueai_leadsource]) & rnk
			RETURN
			res
		lineageTag: d08183c0-78aa-4f8d-9ac4-9313e5df3ff7

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.record_counts' =
			
			COUNT(ssr[_sys_doc_id])
		formatString: #,0
		lineageTag: 956cc13c-ee6e-4031-97bd-2dfccee84e0d

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.ssr_crm_contact_count' =
			
			SUM(
			    ssr[crm_contact_count]
			)
		formatString: 0
		lineageTag: 786b0571-6412-45e9-881f-0e927e48c9e6

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.ssr_crm_lead_count' =
			
			SUM(
			    ssr[crm_lead_count]     // sum of crm_lead_count
			)
		formatString: 0
		lineageTag: 5187e7df-f760-4af9-8277-9b5e39ff2c76

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.ssr_crm_account_count' =
			
			SUM(
			    ssr[crm_account_count]     // sum of crm_account_count
			)
		formatString: 0
		lineageTag: f70335cc-8680-4df2-8f61-b5b70e973046

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.ssr_trueai_potential_acv' =
			
			CALCULATE(
			    SUM(ssr[trueai_potential_acv])          // get the sum of trueai potential acv
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9389b41e-30c0-412b-b08e-23d024be1d28

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Record's standardized lead source
	column trueai_leadsource
		dataType: string
		lineageTag: 241a0d9b-3aca-4cfd-80fc-029b596f662c
		summarizeBy: none
		sourceColumn: trueai_leadsource

		annotation SummarizationSetBy = Automatic

	/// Record's standardized company size
	column trueai_company_size
		dataType: string
		lineageTag: 01cd87f9-d111-4160-8eb6-85ddb3a676f1
		summarizeBy: none
		sourceColumn: trueai_company_size

		annotation SummarizationSetBy = Automatic

	/// Group of the owner of the last step in the sales process
	column trueai_group
		dataType: string
		lineageTag: 01a90e56-5a08-4b9d-93a9-589cbcdda1e6
		summarizeBy: none
		sourceColumn: trueai_group

		annotation SummarizationSetBy = Automatic

	/// Record's standardized industry
	column trueai_industry
		dataType: string
		lineageTag: f402584a-04ee-49ef-84ba-2b5118587537
		summarizeBy: none
		sourceColumn: trueai_industry

		annotation SummarizationSetBy = Automatic

	/// Close date of the first opportunity won
	column trueai_first_purchase
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3de5ecb9-c987-4cef-ab5c-3891ff7308c7
		summarizeBy: none
		sourceColumn: trueai_first_purchase

		variation Variation
			isDefault
			relationship: 45086257-0ea6-4125-891f-a3868eecea94
			defaultHierarchy: LocalDateTable_74b0c4f1-e144-4fe7-87cd-b6273766fa96.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Close date of the last opportunity won
	column trueai_last_purchase
		dataType: dateTime
		formatString: General Date
		lineageTag: 2712115d-c1c6-4ca9-b369-e1fac42e6009
		summarizeBy: none
		sourceColumn: trueai_last_purchase

		variation Variation
			isDefault
			relationship: 660a26f1-24a8-4e55-95e1-7b8de0c3c8ec
			defaultHierarchy: LocalDateTable_6e725079-9265-42a5-b5e7-d7c111fc845a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Account's parent id in the CRM
	column crm_parent_id
		dataType: string
		lineageTag: 1f615933-cf28-4b6f-a189-cefe7f03e80f
		summarizeBy: none
		sourceColumn: crm_parent_id

		annotation SummarizationSetBy = Automatic

	/// Account's name
	column crm_name
		dataType: string
		lineageTag: d0935f31-436d-4a8d-83e3-70c116cd9e0b
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	/// Outcome of the last step in the sales process
	column trueai_last_outcome
		dataType: string
		lineageTag: 59198198-e245-4b25-af00-12777e12fb42
		summarizeBy: none
		sourceColumn: trueai_last_outcome

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the account is the master account in its group of duplicates
	column trueai_account_is_master
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6d5a04a7-8a2e-422b-be9c-fc7749e687c1
		summarizeBy: none
		sourceColumn: trueai_account_is_master

		annotation SummarizationSetBy = Automatic

	/// Column 'col.crm_has_leads' = if(ssr[crm_lead_count] > 0, true, false).
	column 'col.crm_has_leads' = if(ssr[crm_lead_count] > 0, true, false)
		lineageTag: db1531e8-482f-42bf-8cac-d2a6505b3bdb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.crm_has_accounts' = if(ssr[crm_account_count] > 0, true, false).
	column 'col.crm_has_accounts' = if(ssr[crm_account_count] > 0, true, false)
		lineageTag: 2e782cce-e140-459d-8463-31e54cc64e91
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_company_size_aprox_val' = ```.
	column 'col.trueai_company_size_aprox_val' = ```
			
			ssr[trueai_company_size_num]
			/*
			// turun back into a number
			var res = SWITCH (ssr[trueai_company_size_], 
			"1-10 employees", 5, 
			"11-50 employees", 25, 
			"51-200 employees", 125, 
			"201-500 employees", 350, 
			"501-1,000 employees", 750, 
			"1,001-5,000 employees", 2500, 
			"5,001-10,000 employees", 7500, 
			"10,001+ employees", 15000, 
			"ND", BLANK(),Blank()
			 )
			
			/*1,001-5,000 employees
			10,001+ employees
			1-10 employees
			11-50 employees
			201-500 employees
			5,001-10,000 employees
			501-1,000 employees
			51-200 employees
			ND */
			return res 
			*/
			```
		formatString: 0
		lineageTag: accd224e-e8ad-4668-a2d5-f263a7e9c3c2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_location_segments' = ```.
	column 'col.trueai_location_segments' = ```
			
			
			var country =  ssr[trueai_addr_country]
			var total_records = countrows(ssr)
			var country_count = countrows(filter(ssr, ssr[trueai_addr_country] = country))
			var country_thresh = 0.025
			
			var country_str = IF(divide(country_count, total_records) >= country_thresh, country, "Other Countries") // consolidate small counts into other
			var state_thresh = 0.015 
			var state = ssr[trueai_addr_state]
			var state_count = countrows(filter(ssr, ssr[trueai_addr_state] = state))
			var state_str = If(country in {"United States", "Canada"},   IF( divide(state_count, total_records) >= state_thresh, " - " &  state, " - Other States"), "") // add states for releant states
			var res = If(IsBlank(country_str), "ND",country_str & state_str)
			return res
			
			```
		lineageTag: 124fb5e3-fbed-4060-badf-28adaafc4127
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_propensity_prospecting' = ```.
	column 'col.trueai_propensity_prospecting' = ```
			
			// var _ssr_id = ssr[_sys_doc_id] 
			// var res = calculate(MAX(hat_leads[trueai_propensity]), hat_leads[_sys_ssr_id] = _ssr_id)
			// return res
			```
		formatString: 0
		lineageTag: f8db34c3-74f8-4354-b3a0-e64b5cc3c623
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_leadsource_is_inbound' = ```.
	column 'col.trueai_leadsource_is_inbound' = ```
			
			/*
			old calc - now depriciated
			
			var is_inbound =  if 
			
			(
			    
			[trueai_leadsource] = "List Upload"  || 
			[trueai_leadsource] = "Upsell"  ||
			[trueai_leadsource] = "Outbound Call"  ||
			[trueai_leadsource] = "Other Offline Campaigns"  ||
			[trueai_leadsource] = "ND"  ||
			[trueai_leadsource] = "Rep Lead Gen"   , False, true)
			*/
			var res = ssr[trueai_leadsource_is_inbound]
			return res
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: _col_passthrough_to_new_api_s
		lineageTag: c472c884-7093-4bb4-b10e-cd70086ff022
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_time_to_touch_days' = ```.
	column 'col.trueai_time_to_touch_days' = ```
			
			var time_days = IF (isblank([trueai_first_touch]), blank(),   [trueai_first_touch] - [trueai_added_on] )
			var res = time_days 
			return res
			```
		dataType: double
		formatString: 0.0
		lineageTag: d4254abd-5afa-4e84-852e-86192d558390
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_success_prob_new_logo' = calculate(MAX(ssr_history[step_success_prob]), ssr_history[step_name] = "New Logo Selling").
	column 'col.trueai_success_prob_new_logo' = calculate(MAX(ssr_history[step_success_prob]), ssr_history[step_name] = "New Logo Selling")
		lineageTag: a1ee1ad3-f241-474f-9138-624d9301a66e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column 'col.trueai_success_prob_untouched' = calculate(MAX(ssr_history[step_success_prob]), ssr_history[step_name] = "Untouched").
	column 'col.trueai_success_prob_untouched' = calculate(MAX(ssr_history[step_success_prob]), ssr_history[step_name] = "Untouched")
		lineageTag: cd7afbc6-7b16-4d70-be1a-f90f7b2d0778
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column 'col.trueai_vi_lead_gen_value_created' =.
	column 'col.trueai_vi_lead_gen_value_created' =
			
			calculate(SUM(ssr_history[vi_value_created]), ssr_history[step_name] = "Lead Gen")
			//calculate(sum(ssr_history[vi_value_created]), ssr_history[step_name] in {"Lead Gen"})
		formatString: 0
		lineageTag: f339f566-6c7d-4011-97cd-0a02f93ec59c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Account's type in the CRM
	column crm_type
		dataType: string
		lineageTag: 4aac2a55-9581-40e6-9f19-3571a1d66e1d
		summarizeBy: none
		sourceColumn: crm_type

		annotation SummarizationSetBy = Automatic

	/// Record's standardized company size prediction rule
	column trueai_company_size_rule
		dataType: int64
		formatString: 0
		lineageTag: 7a12c4ec-50e0-4c14-b586-d515e72113c4
		summarizeBy: sum
		sourceColumn: trueai_company_size_rule

		annotation SummarizationSetBy = Automatic

	/// Record's standardized industry prediction rule
	column trueai_industry_rule
		dataType: int64
		formatString: 0
		lineageTag: 1ed6b0dc-d852-4c2b-88a8-4fd2dd6df2ed
		summarizeBy: sum
		sourceColumn: trueai_industry_rule

		annotation SummarizationSetBy = Automatic

	/// Record's standardized lead source prediction rule
	column trueai_leadsource_rule
		dataType: int64
		formatString: 0
		lineageTag: 4634d771-f8df-4ab2-b441-4222fc86012b
		summarizeBy: sum
		sourceColumn: trueai_leadsource_rule

		annotation SummarizationSetBy = Automatic

	/// Date when the account churned
	column trueai_churned_on
		dataType: dateTime
		formatString: General Date
		lineageTag: a92aacae-b7a3-4691-aae8-80c69efa8214
		summarizeBy: none
		sourceColumn: trueai_churned_on

		variation Variation
			isDefault
			relationship: 4d319bf5-edb9-4004-9d6d-17fc13e8f89b
			defaultHierarchy: LocalDateTable_cebfbc82-bdaf-4687-b245-affd569762c1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Last time when the record was touched
	column trueai_last_touch
		dataType: dateTime
		formatString: General Date
		lineageTag: 302a0d63-c465-49ed-b6f5-62479974a1b0
		summarizeBy: none
		sourceColumn: trueai_last_touch

		variation Variation
			isDefault
			relationship: b50e481e-a055-4921-99cc-af314d64c4a5
			defaultHierarchy: LocalDateTable_dcd7aacd-0b90-4f50-854b-3dd87a5ffb12.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the record's standardized lead source is inbound
	column trueai_leadsource_is_inbound
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ad7765f4-3e89-413c-b269-4f037a5ed36d
		summarizeBy: none
		sourceColumn: trueai_leadsource_is_inbound

		annotation SummarizationSetBy = Automatic

	/// First time when the record was touched
	column trueai_first_touch
		dataType: dateTime
		formatString: Short Date
		lineageTag: ed3cc7a1-8deb-496d-8d09-9fbacadeed33
		summarizeBy: none
		sourceColumn: trueai_first_touch

		variation Variation
			isDefault
			relationship: 8957dd32-3043-47bb-abab-b00457ee29bc
			defaultHierarchy: LocalDateTable_36229989-33b9-468c-881b-0a9df078ae05.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_propensity_prospecting_sortable' = ```.
	column 'col.trueai_propensity_prospecting_sortable' = ```
			
			
			// var bucket =  [col.trueai_propensity_prospecting]
			// var res = SWITCH(bucket, "Highest" , "1 - " & bucket, "High" , "2 - " & bucket, "Mid" , "3 - " & bucket, "Low" , "4 - " & bucket, "Lowest" , "5 - " & bucket )
			// return res 
			```
		formatString: 0
		lineageTag: 79099d10-e945-404e-9754-cf9af4d6f99b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Unique record identifier, based on the ID of the document in the remote system (such as Salesforce ID)
	column _sys_doc_id
		dataType: string
		lineageTag: b6253e8e-bded-4844-b8bf-df63ca107212
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// The end date of the record, stripped of time
	column _sys_filt_end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 039a1197-bc70-45b6-8482-0e6c2e380821
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 2b4c8e27-14d0-4b65-9569-dd734496145e
			defaultHierarchy: LocalDateTable_79a39ce0-a095-43ec-a376-6bfe70c4b38b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The start date of the record, stripped of time
	column _sys_filt_start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 63f58b80-6542-4662-928e-258d17a47ec2
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 44d16445-8885-4c80-bdc0-dcc96db2c241
			defaultHierarchy: LocalDateTable_55378f2d-97bd-4280-ac87-101a06c31968.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Account owner's id in the CRM
	column crm_owner_id
		dataType: string
		lineageTag: 6edcfc7d-c273-495a-bdf9-30ace2688ece
		summarizeBy: none
		sourceColumn: crm_owner_id

		annotation SummarizationSetBy = Automatic

	/// Account's duplication confidence
	column trueai_account_dupe_conf
		dataType: string
		lineageTag: 28071f32-7ec1-4fe2-828f-9adad71357d9
		summarizeBy: none
		sourceColumn: trueai_account_dupe_conf

		annotation SummarizationSetBy = Automatic

	/// Account's duplication id
	column trueai_account_dupe_id
		dataType: string
		lineageTag: 6c3b1ccf-dc90-4ea6-bc70-c68b087b33d2
		summarizeBy: none
		sourceColumn: trueai_account_dupe_id

		annotation SummarizationSetBy = Automatic

	/// Record's city
	column trueai_addr_city
		dataType: string
		lineageTag: 33b32cf3-a360-46a3-8e44-af62e348dc26
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	/// Record's country
	column trueai_addr_country
		dataType: string
		lineageTag: 1b6122a3-599f-4817-a0a6-253906579d0a
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	/// Record's postal code
	column trueai_addr_postal_code
		dataType: string
		lineageTag: c564ead9-1a6f-44b3-b3c7-01f7b6c89c40
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	/// Record's address prediction rule
	column trueai_addr_rule
		dataType: int64
		formatString: 0
		lineageTag: 786d0bef-9a3a-4781-a79e-56d366860683
		summarizeBy: sum
		sourceColumn: trueai_addr_rule

		annotation SummarizationSetBy = Automatic

	/// Record's state
	column trueai_addr_state
		dataType: string
		lineageTag: 8ebc3e2e-9a3e-4e40-a649-cf839fdedc56
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	/// Record's street
	column trueai_addr_street
		dataType: string
		lineageTag: 2414b219-6176-4e6a-a7af-c596d75922b0
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	/// Creator id of the first step in the sales process
	column trueai_creator_id
		dataType: string
		lineageTag: 484e0944-b61c-4723-9d0c-f29de244493a
		summarizeBy: none
		sourceColumn: trueai_creator_id

		annotation SummarizationSetBy = Automatic

	/// Booking amount of the first opportunity won
	column trueai_first_amt
		dataType: double
		lineageTag: 20f57872-5ea0-47dd-a358-edbb0c2959f7
		summarizeBy: sum
		sourceColumn: trueai_first_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Record's standardized industry prediction confidence
	column trueai_industry_conf
		dataType: double
		lineageTag: cb663c7f-c848-4b1b-8092-d334723ac269
		summarizeBy: sum
		sourceColumn: trueai_industry_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Booking amount of the last opportunity won
	column trueai_latest_amt
		dataType: double
		lineageTag: 544d5b23-ead2-490a-b72e-8e06bee7a986
		summarizeBy: sum
		sourceColumn: trueai_latest_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Record's standardized lead source prediction confidence
	column trueai_leadsource_conf
		dataType: double
		lineageTag: db5b0dcb-4148-4844-acef-47b10eaec06d
		summarizeBy: sum
		sourceColumn: trueai_leadsource_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Owner id of the last step in the sales process
	column trueai_owner_id
		dataType: string
		lineageTag: b70bff1e-4686-4fac-921c-b096a2754867
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	/// Sum of the booking amounts of all the opportunities won
	column trueai_tot_amt
		dataType: double
		lineageTag: d9afd2d5-b6fc-4928-ad82-3c0eea10f24b
		summarizeBy: sum
		sourceColumn: trueai_tot_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Sum of the booking amounts of opportunities created
	column trueai_tot_pipeline_amt
		dataType: double
		lineageTag: 63668268-c0b7-4f28-ae43-08311cdc961d
		summarizeBy: sum
		sourceColumn: trueai_tot_pipeline_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of opportunities won
	column trueai_tot_purchases
		dataType: int64
		formatString: 0
		lineageTag: 10dbebfc-80c0-4910-a8db-82124b1c308f
		summarizeBy: sum
		sourceColumn: trueai_tot_purchases

		annotation SummarizationSetBy = Automatic

	/// Number of steps in the sales process
	column trueai_tot_steps
		dataType: int64
		formatString: 0
		lineageTag: 7c0a2ecb-88db-4fc3-aa4a-cec93d7ad1fd
		summarizeBy: sum
		sourceColumn: trueai_tot_steps

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the account is the master account in its group of duplicates taking into account whether it has revenue
	column trueai_ssr_is_master
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 75743922-2ce3-4d00-8c0b-f8b3ab1a8838
		summarizeBy: none
		sourceColumn: trueai_ssr_is_master

		annotation SummarizationSetBy = Automatic

	/// Record's latitude
	column trueai_addr_lat
		dataType: double
		lineageTag: 86535dd2-5d68-49e4-982c-b42ab34e5e9e
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Record's longitude
	column trueai_addr_long
		dataType: double
		lineageTag: 52f19cf1-71f5-4847-b88c-6149caa54313
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Custom categorical variable on the account
	column crm_account_custom_value_1
		dataType: string
		lineageTag: 9a28b167-09cc-4a93-aca5-8ac38b52ac24
		summarizeBy: none
		sourceColumn: crm_account_custom_value_1

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable on the account
	column crm_account_custom_value_2
		dataType: string
		lineageTag: 73fa6f23-23ee-4aee-9660-c2cbb062469e
		summarizeBy: none
		sourceColumn: crm_account_custom_value_2

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable on the account
	column crm_account_custom_value_3
		dataType: string
		lineageTag: 61e5c56b-d0fe-45f3-8674-7d7914032e49
		summarizeBy: none
		sourceColumn: crm_account_custom_value_3

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_1
		dataType: string
		lineageTag: a717687e-625c-4666-b548-4b9b51e5908f
		summarizeBy: none
		sourceColumn: crm_custom_value_1

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_2
		dataType: string
		lineageTag: a747ab71-d3b0-48ba-8473-ecde863a72b8
		summarizeBy: none
		sourceColumn: crm_custom_value_2

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_3
		dataType: string
		lineageTag: be5bb56e-4ab3-445d-9ac6-dcb8bf442fc6
		summarizeBy: none
		sourceColumn: crm_custom_value_3

		annotation SummarizationSetBy = Automatic

	/// Company size number of the account
	column trueai_company_size_num
		dataType: int64
		formatString: 0
		lineageTag: f7391cbd-a008-4cf0-9496-d47d9b718f96
		summarizeBy: sum
		sourceColumn: trueai_company_size_num

		annotation SummarizationSetBy = Automatic

	/// Current ACV of the account
	column trueai_curr_acv
		dataType: double
		lineageTag: c9e9c372-1fe7-4cd5-b40d-b42602c950af
		summarizeBy: sum
		sourceColumn: trueai_curr_acv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Potential ACV of the account
	column trueai_potential_acv
		dataType: double
		lineageTag: 032b8ab1-afe6-457c-8e13-8a865eec125f
		summarizeBy: sum
		sourceColumn: trueai_potential_acv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Potential ACV factor of the account
	column trueai_potential_acv_factor
		dataType: double
		lineageTag: ae363f6b-e278-4d24-8eef-d901065ab782
		summarizeBy: sum
		sourceColumn: trueai_potential_acv_factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column 'col.trueai_leadsource_inbound_outbound' = ```.
	column 'col.trueai_leadsource_inbound_outbound' = ```
			SWITCH(ssr[trueai_leadsource_is_inbound], true, "Inbound", false, "Outbound", "ND")
			
			
			```
		lineageTag: 42726fd0-b7f7-451c-ab5a-b3953b802093
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Record's standardized type
	column trueai_type
		dataType: string
		lineageTag: 5726945a-3f54-4527-8bac-1da0fac8bd07
		summarizeBy: none
		sourceColumn: trueai_type

		annotation SummarizationSetBy = Automatic

	/// Column trueai_custom_company_size =.
	column trueai_custom_company_size =
			
			SWITCH (
			    TRUE (),
			    ssr[trueai_company_size_num] >= 1 && ssr[trueai_company_size_num] <= 9, "1-9 employees",
			    ssr[trueai_company_size_num] >= 10 && ssr[trueai_company_size_num] <= 19, "10-19 employees",
			    ssr[trueai_company_size_num] >= 20 && ssr[trueai_company_size_num] <= 29, "20-29 employees",
			    ssr[trueai_company_size_num] >= 30 && ssr[trueai_company_size_num] <= 39, "30-39 employees",
			    ssr[trueai_company_size_num] >= 40 && ssr[trueai_company_size_num] <= 49, "40-49 employees",
			    ssr[trueai_company_size_num] >= 50 && ssr[trueai_company_size_num] <= 99, "50-99 employees",
			    ssr[trueai_company_size_num] >= 100 && ssr[trueai_company_size_num] <= 199, "100-199 employees",
			    ssr[trueai_company_size_num] >= 200 && ssr[trueai_company_size_num] <= 499, "200-499 employees",
			    ssr[trueai_company_size_num] >= 500 && ssr[trueai_company_size_num] <= 999, "500-999 employees",
			    ssr[trueai_company_size_num] >= 1000 && ssr[trueai_company_size_num] <= 5000, "1000-5000 employees",
			    ssr[trueai_company_size_num] >= 5000 && ssr[trueai_company_size_num] <= 100000, "5000+ employees",
			    "ND"
			)
		lineageTag: a7fff3e0-9708-47a3-8772-8d4ff7015b22
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// The date of the last data request from the platform
	column _sys_as_of
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4795a693-385e-46f7-902e-a26175ac4384
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 6ed10a16-9acb-45f1-8e4a-1625b7db0f0f
			defaultHierarchy: LocalDateTable_c0d40afb-3a58-41a1-91ca-c62c3d3bae09.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Number of accounts related to the sales process
	column crm_account_count
		dataType: int64
		formatString: 0
		lineageTag: 4bc9057e-74ca-482f-8911-99e0d9117dc0
		summarizeBy: sum
		sourceColumn: crm_account_count

		annotation SummarizationSetBy = Automatic

	/// Number of activities related to the sales process
	column crm_act_count
		dataType: int64
		formatString: 0
		lineageTag: 4b8ec2a6-9d91-4c44-a579-c4592e768cd6
		summarizeBy: sum
		sourceColumn: crm_act_count

		annotation SummarizationSetBy = Automatic

	/// Number of contacts related to the sales process
	column crm_contact_count
		dataType: int64
		formatString: 0
		lineageTag: 66c1c519-e568-4bff-9880-e8858acce7da
		summarizeBy: sum
		sourceColumn: crm_contact_count

		annotation SummarizationSetBy = Automatic

	/// Number of leads related to the sales process
	column crm_lead_count
		dataType: int64
		formatString: 0
		lineageTag: cc770444-50ac-41d6-90b5-50f58e8d85c1
		summarizeBy: sum
		sourceColumn: crm_lead_count

		annotation SummarizationSetBy = Automatic

	/// Number of opportunities related to the sales process
	column crm_opp_count
		dataType: int64
		formatString: 0
		lineageTag: dff74efd-9451-4a82-b954-6e73fabb3655
		summarizeBy: sum
		sourceColumn: crm_opp_count

		annotation SummarizationSetBy = Automatic

	/// Account's URL in the CRM
	column crm_web_url
		dataType: string
		lineageTag: efeb106c-f86f-4b37-838e-8d811f1f5928
		summarizeBy: none
		sourceColumn: crm_web_url

		annotation SummarizationSetBy = Automatic

	/// Start date of the first step in the sales process
	column trueai_added_on
		dataType: dateTime
		formatString: Short Date
		lineageTag: 640badb4-9f86-4e4f-9234-df26979e8545
		summarizeBy: none
		sourceColumn: trueai_added_on

		variation Variation
			isDefault
			relationship: 924712cc-6b77-424a-90a0-22fb090e3a9b
			defaultHierarchy: LocalDateTable_0af2d924-dc37-41fc-971e-5d67202c25be.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Current step id
	column trueai_curr_step
		dataType: int64
		formatString: 0
		lineageTag: f1e73a8d-7c6d-489f-a39c-318847f0bf15
		summarizeBy: sum
		sourceColumn: trueai_curr_step

		annotation SummarizationSetBy = Automatic

	/// Current step name
	column trueai_curr_step_name
		dataType: string
		lineageTag: 584ead3b-03ba-4533-8843-40216a923b84
		summarizeBy: none
		sourceColumn: trueai_curr_step_name

		annotation SummarizationSetBy = Automatic

	/// Number of days since the start of the first step until the end of the last step in the sales process
	column trueai_tot_length_in_days
		dataType: int64
		formatString: 0
		lineageTag: 054c6eb1-a0d1-41c1-897c-037cdfa312b0
		summarizeBy: sum
		sourceColumn: trueai_tot_length_in_days

		annotation SummarizationSetBy = Automatic

	/// Column 'col.bucket_num' = ```.
	column 'col.bucket_num' = ```
			//SWITCH(ssr[col.trueai_propensity_prospecting], "Lowest", 1, "Low", 2, "Mid", 3, "High", 4, "Highest", 5) 
			```
		formatString: 0
		lineageTag: 1f216f41-f72d-4e9f-9708-2c16b91786d9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Column 'col.crm_leadsource' =.
	column 'col.crm_leadsource' =
			
			var trueai_leads = [trueai_leadsource]
			
			var crm_leads = CALCULATE(
			    MAX(
			        ssr[crm_leadsource]
			    ),
			    ssr[trueai_leadsource] = trueai_leads
			)
			
			RETURN
			crm_leads
		lineageTag: a9f52232-b4df-41b0-9789-aeeac1a82d54
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Account's leadsource
	column crm_leadsource
		dataType: string
		lineageTag: 51f50f9a-2c04-4bb6-a949-3e46a3457262
		summarizeBy: none
		sourceColumn: crm_leadsource

		annotation SummarizationSetBy = Automatic

	/// Account's industry
	column crm_industry
		dataType: string
		lineageTag: 26e40ab6-d09a-49c7-b496-9cc952b2b261
		summarizeBy: none
		sourceColumn: crm_industry

		annotation SummarizationSetBy = Automatic

	/// Account's number of employees
	column crm_num_employees
		dataType: int64
		formatString: 0
		lineageTag: dcab3c9f-bb3c-4da1-a277-3a7221eec020
		summarizeBy: sum
		sourceColumn: crm_num_employees

		annotation SummarizationSetBy = Automatic

	/// Record's standardized type rule
	column trueai_type_rule
		dataType: int64
		formatString: 0
		lineageTag: 91feb751-b15a-4d0a-8fa8-8e98a557bd55
		summarizeBy: sum
		sourceColumn: trueai_type_rule

		annotation SummarizationSetBy = Automatic

	/// Column 'col.crm_leadsource_concat' =.
	column 'col.crm_leadsource_concat' =
			
			CONCATENATEX(
			    DISTINCT(
			        SELECTCOLUMNS(
			            FILTER(
			                ssr,
			                ssr[trueai_leadsource] = EARLIER(ssr[trueai_leadsource]) &&
			                NOT(ISBLANK(ssr[crm_leadsource]))
			            ),
			            "LeadSource", TRIM(ssr[crm_leadsource])
			        )
			    ),
			    [LeadSource],
			    ", "
			)
		lineageTag: e9672d65-6cb8-49e9-bd9d-b015b1662b81
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.lead_source' =.
	column 'col.lead_source' =
			
			SWITCH(
			    ssr[trueai_leadsource_is_inbound],
			    True, "Inbound",
			    False, "Outbound",
			    BLANK()
			)
		lineageTag: 3954fe24-2664-48b9-a146-ba8cabd4f80e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Record's parent account name
	column trueai_parent_name
		dataType: string
		lineageTag: 6cf4ee67-8f9f-4ed3-bcdf-06cfb68d0994
		summarizeBy: none
		sourceColumn: trueai_parent_name

		annotation SummarizationSetBy = Automatic

	/// Column 'col.trueai_first_touch' = ```.
	column 'col.trueai_first_touch' = ```
			ssr[trueai_first_touch]
			 
			 --calculate(MIN(ssr_history[_sys_filter_start_date]), ssr_history[step_name] = "Prospecting")
			```
		formatString: General Date
		lineageTag: f60563a8-7a55-47b2-b4d6-767d549e5a3a
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 15879d93-d475-4ddd-9d85-c28b23d2b19c
			defaultHierarchy: LocalDateTable_0150aeab-9ee4-4ff3-9cea-e1f34f6e3e0a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Number of days from the start to the first touch
	column trueai_days_to_first_touch
		dataType: int64
		formatString: 0
		lineageTag: 116ac16d-df4e-4134-8777-dfa9fdc43de9
		summarizeBy: sum
		sourceColumn: trueai_days_to_first_touch

		annotation SummarizationSetBy = Automatic

	/// Average CRM Completeness of Contacts
	column trueai_crm_complt_contacts
		dataType: double
		lineageTag: 84bd5612-3cde-4c77-9c03-3947da306959
		summarizeBy: sum
		sourceColumn: trueai_crm_complt_contacts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average CRM Completeness of Leads
	column trueai_crm_complt_leads
		dataType: double
		lineageTag: ec72811c-3c8c-4251-97d8-1141eadf7384
		summarizeBy: sum
		sourceColumn: trueai_crm_complt_leads

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average CRM Completeness of Opps
	column trueai_crm_complt_opps
		dataType: double
		lineageTag: a74d01b9-67d9-43e4-8146-2ded0b70e2a8
		summarizeBy: sum
		sourceColumn: trueai_crm_complt_opps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average CRM Completeness of Accounts
	column trueai_crm_complt_accounts
		dataType: double
		lineageTag: 16b0bc7e-313e-4396-b650-847914c23a96
		summarizeBy: sum
		sourceColumn: trueai_crm_complt_accounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average TrueAI Completeness of Contacts
	column trueai_complt_contacts
		dataType: double
		lineageTag: fc795c18-69aa-442c-a5e5-674eee2053fc
		summarizeBy: sum
		sourceColumn: trueai_complt_contacts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average TrueAI Completeness of Leads
	column trueai_complt_leads
		dataType: double
		lineageTag: e70da5ad-35d1-473b-984b-07785597bb85
		summarizeBy: sum
		sourceColumn: trueai_complt_leads

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average TrueAI Completeness of Opps
	column trueai_complt_opps
		dataType: double
		lineageTag: 6fed659c-fc09-45bc-a958-5df39ac1d865
		summarizeBy: sum
		sourceColumn: trueai_complt_opps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average TrueAI Completeness of Accounts
	column trueai_complt_accounts
		dataType: double
		lineageTag: 7c1ea753-705e-4e89-9ee1-8bf38075e122
		summarizeBy: sum
		sourceColumn: trueai_complt_accounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Overall Average CRM Completeness Across Entities
	column trueai_crm_complt_all
		dataType: double
		lineageTag: 2c23906d-0c0f-4f71-aff9-47b03fef6984
		summarizeBy: sum
		sourceColumn: trueai_crm_complt_all

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Overall Average TrueAI Completeness Across Entities
	column trueai_complt_all
		dataType: double
		lineageTag: d3246f38-7070-4ac6-9010-824142424a12
		summarizeBy: sum
		sourceColumn: trueai_complt_all

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column 'col.trueai_churn_date_no_blanks' =.
	column 'col.trueai_churn_date_no_blanks' =
			
			
			var res = if(isblank(ssr[trueai_churned_on]) = True && isblank(ssr[trueai_first_purchase]) = false  , date(2100,1,1), ssr[trueai_churned_on])
			return res
		formatString: General Date
		lineageTag: 0d533431-9a71-4a72-b402-8baf023cfed9
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 9eff66a3-2498-477b-a625-4cea2950121f
			defaultHierarchy: LocalDateTable_172225b5-5ae5-4387-b255-26965afe3ae5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition ssr-5b934306-a526-4a93-a2ba-c6a8a109259e = m
		mode: import
		source = ```
				let
				  
				  dbTable = getDBTable("ssr"), // get the right table
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{
				    {"_sys_as_of", type datetime},
				    {"_sys_doc_id", type text},
				    {"_sys_filt_end_date", type date},
				    {"_sys_filt_start_date", type date},
				    {"crm_account_count", Int64.Type},
				    {"crm_account_custom_value_1", type text},
				    {"crm_account_custom_value_2", type text},
				    {"crm_account_custom_value_3", type text},
				    {"crm_act_count", Int64.Type},
				    {"crm_contact_count", Int64.Type},
				    {"crm_custom_value_1", type text},
				    {"crm_custom_value_2", type text},
				    {"crm_custom_value_3", type text},
				    {"crm_industry", type text},
				    {"crm_lead_count", Int64.Type},
				    {"crm_leadsource", type text},
				    {"crm_name", type text},
				    {"crm_num_employees", Int64.Type},
				    {"crm_opp_count", Int64.Type},
				    {"crm_owner_id", type text},
				    {"crm_parent_id", type text},
				    {"crm_type", type text},
				    {"crm_web_url", type text},
				    {"trueai_account_dupe_conf", type text},
				    {"trueai_account_dupe_id", type text},
				    {"trueai_account_is_master", type logical},
				    {"trueai_added_on", type datetime},
				    {"trueai_addr_city", type text},
				    {"trueai_addr_country", type text},
				    {"trueai_addr_lat", type number},
				    {"trueai_addr_long", type number},
				    {"trueai_addr_postal_code", type text},
				    {"trueai_addr_rule", Int64.Type},
				    {"trueai_addr_state", type text},
				    {"trueai_addr_street", type text},
				    {"trueai_churned_on", type datetime},
				    {"trueai_company_size", type text},
				    {"trueai_company_size_num", Int64.Type},
				    {"trueai_company_size_rule", Int64.Type},
				    {"trueai_complt_accounts", type number},
				    {"trueai_complt_all", type number},
				    {"trueai_complt_contacts", type number},
				    {"trueai_complt_leads", type number},
				    {"trueai_complt_opps", type number},
				    {"trueai_creator_id", type text},
				    {"trueai_crm_complt_accounts", type number},
				    {"trueai_crm_complt_all", type number},
				    {"trueai_crm_complt_contacts", type number},
				    {"trueai_crm_complt_leads", type number},
				    {"trueai_crm_complt_opps", type number},
				    {"trueai_curr_acv", type number},
				    {"trueai_curr_step", Int64.Type},
				    {"trueai_curr_step_name", type text},
				    {"trueai_days_to_first_touch", Int64.Type},
				    {"trueai_first_amt", type number},
				    {"trueai_first_purchase", type datetime},
				    {"trueai_first_touch", type datetime},
				    {"trueai_group", type text},
				    {"trueai_industry", type text},
				    {"trueai_industry_conf", type number},
				    {"trueai_industry_rule", Int64.Type},
				    {"trueai_last_outcome", type text},
				    {"trueai_last_purchase", type datetime},
				    {"trueai_last_touch", type datetime},
				    {"trueai_latest_amt", type number},
				    {"trueai_leadsource", type text},
				    {"trueai_leadsource_conf", type number},
				    {"trueai_leadsource_is_inbound", type logical},
				    {"trueai_leadsource_rule", Int64.Type},
				    {"trueai_owner_id", type text},
				    {"trueai_parent_name", type text},
				    {"trueai_potential_acv", type number},
				    {"trueai_potential_acv_factor", type number},
				    {"trueai_ssr_is_master", type logical},
				    {"trueai_tot_amt", type number},
				    {"trueai_tot_length_in_days", Int64.Type},
				    {"trueai_tot_pipeline_amt", type number},
				    {"trueai_tot_purchases", Int64.Type},
				    {"trueai_tot_steps", Int64.Type},
				    {"trueai_type", type text},
				    {"trueai_type_rule", Int64.Type}
				  })
				in
				    dbTableTyped
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

