/// Derived entity for monthly snapshots of user-level performance. One row per user per month. Includes User metadata, Deal Intelligence (DI), Coaching Intelligence (CI), and Automatic Data Enhancement (ADE) metrics. Historical depth: 6 years retroactive.
table users_history
	lineageTag: d904fbb9-5121-4eb7-966a-bb236f245cbb

	/// Measure meas.data_logs_user_mgr_count_eop.
	measure 'meas.data_logs_user_mgr_count_eop' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			
			var active_users_tbl =  filter(applicable_rows_tbl,  [col.user.user_role_function] = "MGR" &&  [trueai_hire_date] <  toDate   && if(isblank([trueai_termination_date]), date(2100,1,1),[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			
			var res = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, [_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			return res // return the res :)
			```
		description: """
Purpose: Tracks data logs user mgr count eop.
Logic: Counts rows using users_history[_sys_filt_start_date] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_filt_start_date]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: b37dd8bf-3abb-4c71-b2b1-02d86db3fea8

	/// Measure meas.data_logs_user_new_hires_reached_performer_within_12_months.
	measure 'meas.data_logs_user_new_hires_reached_performer_within_12_months' = ```
			
			
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var res = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_hire_date] >= fromDate &&     users_history[trueai_hire_date]  <= toDate, 
			           If(isblank(users_history[col.perf_date_first_reached]) = true, date(2100,1,1), users_history[col.perf_date_first_reached]) <  (users_history[trueai_hire_date] + 365) 
			)
			return If(isblank( res), 0, res)
			```
		description: """
Purpose: Tracks data logs user new hires reached performer within 12 months.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_hire...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: +0
		displayFolder: _perf_analysis
		lineageTag: a2dee853-9dbc-44fa-8056-38f45ee80945

	/// Measure meas.data_logs_user_new_terminations.
	measure 'meas.data_logs_user_new_terminations' = ```
			
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var res = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_termination_date] >= fromDate &&     users_history[trueai_termination_date]  <= toDate 
			)
			return 
			IF(
			    res = BLANK(), 
			    0,                  // putting the condition to show 0 instead of blank
			    res * -1
			)
			```
		description: """
Purpose: Tracks data logs user new terminations.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_term...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _ramp_analysis
		lineageTag: bde20ead-06ce-47fd-a172-f24a25d9b9c4

	/// Measure meas.data_logs_user_individual_contrib_count_eop.
	measure 'meas.data_logs_user_individual_contrib_count_eop' = ```
			
			[meas.data_logs_user_count_eop_for_all_sales_roles]  - [meas.data_logs_user_count_eop_for_mgr] 
			
			```
		description: """
Purpose: Tracks data logs user individual contrib count eop.
Logic: Counts rows under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop_for_all_sales_roles], [meas.data_logs_user_count_eop_for_mgr]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 190042ed-5ba8-4940-b3a0-4223f7d6d03b

	/// Measure meas.data_logs_user_rep_mgr_ratio.
	measure 'meas.data_logs_user_rep_mgr_ratio' =
			//divide(users_history[meas.data_logs_user_individual_contrib_count_eop] ,users_history[meas.data_logs_user_count_eop_for_mgr])
			
			VAR _total_role = CALCULATE(
			    [meas.data_logs_user_count_eop], // get the necessary count filtering role dept
			    users_history[trueai_user_role_function] in {"AE","AM", "SDR"}
			)
			VAR _mgr_count = [meas.data_logs_user_count_eop_for_mgr]   // get the manager count
			var res  = DIVIDE(
			    _total_role,
			    _mgr_count
			)
			
			RETURN
			res
		description: """
Purpose: Tracks data logs user rep mgr ratio.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop], [meas.data_logs_user_count_eop_for_mgr], [meas.data_logs_user_individual_contrib...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: #.#:1
		displayFolder: _rep_count_analysis
		lineageTag: 1ccfb892-9120-428d-af84-a6829c8cb2ae

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Measure meas.data_logs_user_count_eop.
	measure 'meas.data_logs_user_count_eop' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <=  toDate   && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			
			var res = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, [_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			return res // return the res :)
			```
		description: """
Purpose: Tracks data logs user count eop.
Logic: Counts rows using users_history[_sys_filt_start_date] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_filt_start_date], users_history[tru...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 0d53230b-70a9-4c33-923e-97f01c07267f

	/// Measure meas.data_logs_user_new_terminations_within_12_months.
	measure 'meas.data_logs_user_new_terminations_within_12_months' = ```
			
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			
			var res = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_termination_date] >= fromDate &&  users_history[trueai_termination_date]  <= toDate  && users_history[trueai_tenure] < 13)
			return res * -1
			```
		description: """
Purpose: Tracks data logs user new terminations within 12 months.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_term...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _ramp_analysis
		lineageTag: 1b315d56-3418-4f57-83da-95dd0f39299c

	/// Measure meas.data_logs_ci_perf_tier_count.
	measure 'meas.data_logs_ci_perf_tier_count' = ```
			
			var month_instances = CALCULATE(COUNT(users_history[col.ci.perf_qtly_performance_tier]))  // how many months in this perf cat
			Var total_months = CALCULATE(count(users_history[col.ci.perf_qtly_performance_tier]), users_history[col.ci.perf_qtly_performance_tier] <> "XX") // how many months in total? (per cate not equal anything
			Var total_users = CALCULATE(distinctcount(users_history[_sys_user_id]), users_history[col.ci.perf_qtly_performance_tier] <> "XX")  // total unique users 
			var users_in_perf_tier_dec = total_users * (month_instances) / total_months
			var res = Round(users_in_perf_tier_dec ,0) 
			return res
			```
		description: """
Purpose: Tracks data logs ci perf tier count.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Columns: users_history[col.ci.perf_qtly_performance_tier], users_history[_sys_user_id]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _perf_analysis
		lineageTag: c8771d48-9a93-446a-b576-b1cae3318ddc

	/// Measure meas.data_logs_user_net_new_users.
	measure 'meas.data_logs_user_net_new_users' = ```
			[meas.data_logs_user_new_hires] + [meas.data_logs_user_new_terminations] 
			```
		description: """
Purpose: Tracks data logs user net new users.
Logic: Returns an extreme value under filters.
Dependencies: Measures: [meas.data_logs_user_new_hires], [meas.data_logs_user_new_terminations]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 1103f6b8-a2c1-47f7-82b8-8f911720ebe9

	/// Measure meas.data_logs_ci_perf_annual_avg_bookings.
	measure 'meas.data_logs_ci_perf_annual_avg_bookings' = ```
			
			var end_date =   [meas.companies_history_reference_date]
			var start_date =  end_date - 365 //dateadd( {end_date},-1, year)
			var res =  CALCULATE(AVERAGE(users_history[ci_perf_qtly_avg_bookings_peers]), cal_end_dates[Date] >start_date &&  end_date <= end_date) // qtly number
			return res * 4 // annual number
			
			```
		description: """
Purpose: Tracks data logs ci perf annual average bookings.
Logic: Averages users_history[ci_perf_qtly_avg_bookings_peers] under filters.
Dependencies: Measures: [meas.companies_history_reference_date]; Columns: users_history[ci_perf_qtly_avg_bookings_peers], cal_end_dates[D...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _perf_analysis
		lineageTag: e8d0ba55-4ac1-4b2d-9735-21fbf43528cc

		annotation PBI_FormatHint = {"currencyCulture":""}

	/// Measure meas.data_logs_user_count_bop.
	measure 'meas.data_logs_user_count_bop' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, FIRSTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the first entry in each filter context period (e.g. a year)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <=  fromDate   && if(isblank([trueai_termination_date]), date(2100,1,1),[trueai_termination_date]) >  fromDate) // make sure we only include reps that are in the active 
			
			var res = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, [_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			return res // return the res :)
			```
		description: """
Purpose: Tracks data logs user count bop.
Logic: Counts rows using users_history[_sys_filt_start_date] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_filt_start_date]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 23c2187f-b803-4f66-a9bb-b218861c778f

	/// Measure meas.data_logs_user_count_change.
	measure 'meas.data_logs_user_count_change' = divide([meas.data_logs_user_new_hires] , [meas.data_logs_user_count_bop], BLANK())
		description: """
Purpose: Tracks data logs user count change.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_bop], [meas.data_logs_user_new_hires]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: +#,##0%;-#,##0%
		displayFolder: _rep_count_analysis
		lineageTag: c2d4b16c-eba9-4e44-a36b-88f0439a492c

		annotation PBI_FormatHint = {"isCustom":true}

	/// Measure meas.data_logs_user_new_hires.
	measure 'meas.data_logs_user_new_hires' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var res = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_hire_date] >= fromDate &&     users_history[trueai_hire_date]  <= toDate)
			
			           
			return if(isblank(res), 0, res)
			```
		description: """
Purpose: Tracks data logs user new hires.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_hire...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 71c8d155-d6fc-42de-b47d-f7c9060e54a1

	/// Measure meas.data_logs_user_new_terminations_within_12_months_avg_tenure.
	measure 'meas.data_logs_user_new_terminations_within_12_months_avg_tenure' = ```
			
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			
			var res = CALCULATE(AVERAGEX(users_history, (users_history[trueai_termination_date]  - users_history[trueai_hire_date]) /30  ), 
			           users_history[trueai_termination_date] >= fromDate &&  users_history[trueai_termination_date]  <= toDate  && users_history[trueai_tenure] < 13)
			
			return res
			```
		description: """
Purpose: Tracks data logs user new terminations within 12 months average tenure.
Logic: Averages users_history[trueai_termination_date] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[trueai_termination_date], users_history[...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: 0.0
		displayFolder: _ramp_analysis
		lineageTag: 75d0f25d-3377-4efe-b39e-2e5fcc6393ab

	/// Measure meas.data_logs_user_new_hires_reached_performer_success_rate.
	measure 'meas.data_logs_user_new_hires_reached_performer_success_rate' = ```
			
			var tot_new_hires  = [meas.data_logs_user_new_hires]
			
			var _reached_reps = [meas.user_history_user_new_hires_reached_perf_in_12_month]
			
			var res = DIVIDE(
			    _reached_reps,
			    tot_new_hires,
			    0
			)
			RETURN
			IF(
			    res=BLANK(),
			    0,                      // putting the condition to 0% instead of blank if there is blank 
			    res
			)
			```
		description: """
Purpose: Tracks data logs user new hires reached performer success rate.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_new_hires], [meas.user_history_user_new_hires_reached_perf_in_12_month]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _perf_analysis
		lineageTag: c9422a55-f07e-46d0-8b7d-e7073208b629

	/// Measure meas.data_logs_user_new_terminations_within_12_months_failure_rate.
	measure 'meas.data_logs_user_new_terminations_within_12_months_failure_rate' = divide( -1 * [meas.data_logs_user_new_terminations_within_12_months],  [meas.data_logs_user_new_hires] , BLANK())
		description: """
Purpose: Tracks data logs user new terminations within 12 months failure rate.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_new_hires], [meas.data_logs_user_new_terminations_within_12_months]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: #,0%;-#,0%;#,0%
		displayFolder: _ramp_analysis
		lineageTag: 29a4c52e-0ac6-4eb5-8258-ac1cac98ccae

	/// Measure meas.data_logs_user_new_hires_reached_performer_within_12_months_avg_tenure.
	measure 'meas.data_logs_user_new_hires_reached_performer_within_12_months_avg_tenure' = ```
			
			VAR fromDate = [meas.context_date_min]
			VAR toDate = [meas.context_date_max]
			
			VAR res =
			    CALCULATE(
			        AVERAGEX(
			            users_history,
			            MAX(0, DATEDIFF(users_history[trueai_hire_date], users_history[col.perf_date_first_reached], DAY))
			        ),
			        users_history[trueai_hire_date] >= fromDate &&
			        users_history[trueai_hire_date] <= toDate &&
			
			        NOT(ISBLANK(users_history[col.perf_date_first_reached])) &&
			        users_history[col.perf_date_first_reached] <= users_history[trueai_hire_date] + 365
			    ) / 30 
			
			RETURN
			IF(res = BLANK(), "-", res)
			```
		description: """
Purpose: Tracks data logs user new hires reached performer within 12 months average tenure.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[trueai_hire_date], users_history[col.per...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: #,##0.0" Mos."
		displayFolder: _perf_analysis
		lineageTag: 13df22da-2a25-4c0d-beca-5c550610123e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Measure meas.data_logs_ci_perf_annual_avg_pipeline_created.
	measure 'meas.data_logs_ci_perf_annual_avg_pipeline_created' = ```
			
			var end_date =   [meas.companies_history_reference_date]
			var start_date =  end_date - 365 //dateadd( {end_date},-1, year)
			var res =  CALCULATE(AVERAGE(users_history[col.ci.perf_qtly_avg_pipeline_peers]), cal_end_dates[Date] >start_date &&  end_date <= end_date) // qtly number
			return res * 4 // annual number
			
			
			
			```
		description: """
Purpose: Tracks data logs ci perf annual average pipeline created.
Logic: Averages users_history[col.ci.perf_qtly_avg_pipeline_peers] under filters.
Dependencies: Measures: [meas.companies_history_reference_date]; Columns: users_history[col.ci.perf_qtly_avg_pipeline_peers], cal_end_dat...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _perf_analysis
		lineageTag: a71bba55-020c-4658-b8f1-53fffc283958

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.users_history_ramping_reps_count_eop.
	measure 'meas.users_history_ramping_reps_count_eop' = ```
			
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, users_history[col.ci.perf_ramping_status] ="Ramping" ,  LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <  toDate   && if(isblank([trueai_termination_date]), date(2100,1,1),[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			
			var res = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, users_history[_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			return res // return the res :)
			```
		description: """
Purpose: Tracks users history ramping reps count eop.
Logic: Counts rows using users_history[col.ci.perf_ramping_status] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[col.ci.perf_ramping_status], users_histo...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _skills_analysis
		lineageTag: 443a145f-8199-4a8d-bba8-a3b1556b6100

	/// Measure meas.user_history_period_count.
	measure 'meas.user_history_period_count' = CALCULATE(DISTINCTCOUNT(users_history[_sys_filt_start_date]))
		description: """
Purpose: Tracks user history period count.
Logic: Counts distinct values in users_history[_sys_filt_start_date] under filters.
Dependencies: Columns: users_history[_sys_filt_start_date]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _helper
		lineageTag: a95dbb11-f9e5-4d93-950a-5d9a776941b0

	/// Measure meas.users_history_vi_value_received_all_prior_time.
	measure 'meas.users_history_vi_value_received_all_prior_time' =
			
			var max_date = CALCULATE(max(cal_end_dates[Date]))
			var val_all_time = CALCULATE(Sum(users_history[vi_value_received_tot]),cal_end_dates[Date] > Date(1900,1,1) && cal_end_dates[Date] <= max_date) // override all prior time until max date
			var res = val_all_time
			return res
		description: """
Purpose: Tracks users history vi value received all prior time.
Logic: Sums cal_end_dates[Date] under filters.
Dependencies: Columns: cal_end_dates[Date], users_history[vi_value_received_tot]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _vi_analysis
		lineageTag: dd1e1348-9c8f-433d-b1d8-5597a5c57e16

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.user_history_user_new_hires_reached_perf_in_12_month.
	measure 'meas.user_history_user_new_hires_reached_perf_in_12_month' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			var perf_reps = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_hire_date] >= fromDate &&    users_history[trueai_hire_date]  <= toDate -- hired this year
			           && users_history[col.perf_date_first_reached]  <  users_history[trueai_hire_date] +365  -- did reach perf within a year 
			           && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) > users_history[trueai_hire_date] +365 -- did not get terminated within a year
			           )
			
			var res = if(ISBLANK(perf_reps), 0, perf_reps)
			return res
			```
		description: """
Purpose: Tracks user history user new hires reached perf in 12 month.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_hire...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _ramp_analysis
		lineageTag: d7c2bfef-6936-47f3-b6c3-3453a31b2971

	/// Measure meas.user_history_user_new_hires_didnt_reach_perf_in_12_month.
	measure 'meas.user_history_user_new_hires_didnt_reach_perf_in_12_month' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			var perf_reps = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_hire_date] >= fromDate &&     users_history[trueai_hire_date]  <= toDate -- hired this year
			           && users_history[col.perf_date_first_reached]   > users_history[trueai_hire_date] +365 -- did not reach perf level in a year
			           && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) > users_history[trueai_hire_date] +365 -- was not terminated
			           )
			
			var res = if(ISBLANK(perf_reps), 0, perf_reps)
			return res
			```
		description: """
Purpose: Tracks user history user new hires didnt reach perf in 12 month.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_hire...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _ramp_analysis
		lineageTag: cbad2d08-9be8-4635-a80e-1fb33bbc5488

	/// Measure meas.user_history_user_new_hires_terminated_in_12_month.
	measure 'meas.user_history_user_new_hires_terminated_in_12_month' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			var termed_within12 = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_hire_date] >= fromDate &&     users_history[trueai_hire_date]  <= toDate -- hired this year
			           && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) < users_history[trueai_hire_date] +365) -- terminated within a year
			
			var res = if(isblank(termed_within12),0,termed_within12 )
			return res * -1
			```
		description: """
Purpose: Tracks user history user new hires terminated in 12 month.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_hire...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _ramp_analysis
		lineageTag: 1aea2f21-f4e1-4f4d-bc08-8849f865a4c8

	/// Measure meas.users_history_ci_perf_avg_attainment.
	measure 'meas.users_history_ci_perf_avg_attainment' =
			
			
			var tbl_reps = SUMMARIZE(CALCULATETABLE(users_history,users_history[ci_perf_qtly_avg_bookings_peers] > 1 ), users_history[_sys_user_id],  "rep_sum",  sum(users_history[col.ci.perf_qtly_bookings_user]), "peer_sum",  sum(users_history[ci_perf_qtly_avg_bookings_peers]))
			var avg_rep_attain = AVERAGEX(tbl_reps, DIVIDE([rep_sum],[peer_sum]))
			var res  = avg_rep_attain
			return res
		description: """
Purpose: Tracks users history ci perf average attainment.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Columns: users_history[ci_perf_qtly_avg_bookings_peers], users_history[_sys_user_id], users_history[col.ci.perf_qtly_bookin...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _ramp_
		lineageTag: ed0257f9-3179-461b-8e0b-bd32762b95f9

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_eop_for_ae.
	measure 'meas.data_logs_user_count_eop_for_ae' = ```
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] = "SALES" &&  users_history[trueai_user_role_function] = "AE" 
			)
			```
		description: """
Purpose: Tracks data logs user count eop for ae.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department], users_history[trueai_user_r...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 0f5821e3-d7cc-4ce4-ae7f-9f760cba5013

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_eop_for_am.
	measure 'meas.data_logs_user_count_eop_for_am' = ```
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] = "SALES" &&  users_history[trueai_user_role_function] = "AM" 
			)
			```
		description: """
Purpose: Tracks data logs user count eop for am.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department], users_history[trueai_user_r...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 851eef1a-e954-4e31-91a7-0aaf4d2959b1

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_eop_for_sdr.
	measure 'meas.data_logs_user_count_eop_for_sdr' = ```
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] = "SALES" &&  users_history[trueai_user_role_function] = "SDR" 
			)
			```
		description: """
Purpose: Tracks data logs user count eop for sdr.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department], users_history[trueai_user_r...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: bc734f70-1e1a-414c-8344-0db6935738ea

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_eop_for_all_sales_roles.
	measure 'meas.data_logs_user_count_eop_for_all_sales_roles' = ```
			
			CALCULATE(
			    [meas.data_logs_user_count_eop],
			    users_history[trueai_user_role_department] = "SALES" 
			)
			```
		description: """
Purpose: Tracks data logs user count eop for all sales roles.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 5e4e7b8f-4fec-4aef-aad0-58359508545c

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_eop_for_mgr.
	measure 'meas.data_logs_user_count_eop_for_mgr' = ```
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] = "SALES" &&  users_history[trueai_user_role_function] = "MGMT" 
			        )
			```
		description: """
Purpose: Tracks data logs user count eop for mgr.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department], users_history[trueai_user_r...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 85f4c5b8-e1fe-4183-b591-4ef4151f7ee6

	/// Measure meas.data_logs_user_count_eop_for_other.
	measure 'meas.data_logs_user_count_eop_for_other' =
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] = "SALES" &&  users_history[trueai_user_role_function] = "OTHER ROLES"
			)
		description: """
Purpose: Tracks data logs user count eop for other.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department], users_history[trueai_user_r...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 264b9cb9-f0ce-4764-8abe-39c27f7e8175

	/// Measure meas.data_logs_user_count_eop_for_dept_mkt.
	measure 'meas.data_logs_user_count_eop_for_dept_mkt' =
			
			CALCULATE(
			    [meas.data_logs_user_count_eop],
			    users_history[trueai_user_role_department] IN { "MKT" }
			)
		description: """
Purpose: Tracks data logs user count eop for dept mkt.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 7e8c4b48-a945-4fc5-a092-43358df3fa62

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_eop_for_dept_sales.
	measure 'meas.data_logs_user_count_eop_for_dept_sales' =
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] IN { "SALES" }
			)
		description: """
Purpose: Tracks data logs user count eop for dept sales.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 31ce84f9-bae7-4b16-abad-55e7cea9405c

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_eop_for_dept_other.
	measure 'meas.data_logs_user_count_eop_for_dept_other' =
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] IN { "OTHER DEPTS" }
			)
		description: """
Purpose: Tracks data logs user count eop for dept other.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: c5ee2d2f-a382-44a5-b694-7c76dd98edd0

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_change_perc.
	measure 'meas.data_logs_user_count_change_perc' =
			
			VAR __BASELINE_VALUE = [meas.data_logs_user_count_bop]
			VAR __VALUE_TO_COMPARE = [meas.data_logs_user_count_eop]
			RETURN
				DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
		description: """
Purpose: Tracks data logs user count change percentage.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_bop], [meas.data_logs_user_count_eop]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _rep_count_analysis
		lineageTag: 2bc1cb9f-ae11-4a3c-ac45-7147c60c679d

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "MathematicalPercentageDifference",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_user_count_eop_for_nd.
	measure 'meas.data_logs_user_count_eop_for_nd' =
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role]
			        IN { "ND" }
			)
		description: """
Purpose: Tracks data logs user count eop for nd.
Logic: Counts rows using users_history[trueai_user_role] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 7bcb8763-96e0-4db1-b039-349dbd1c0eec

	/// Measure meas.reps_w_actlvl_pct.
	measure 'meas.reps_w_actlvl_pct' = ```
			
			var reps_w_acl = [meas.reps_w_actlvl_count]
			var reps_tot = CALCULATE(DISTINCTCOUNT([_sys_user_id]))
			
			var res = DIVIDE(reps_w_acl, reps_tot)
			return res
			
			
			```
		description: """
Purpose: Tracks reps w actlvl percentage.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.reps_w_actlvl_count]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _acl_ta_analysis
		lineageTag: a812b715-d8de-41ae-bfc8-aa462a01927b

		changedProperty = FormatString

	/// Measure meas.reps_w_actlvl_count.
	measure 'meas.reps_w_actlvl_count' =
			
			CALCULATE(DISTINCTCOUNT([_sys_user_id]), (users_history[ci_act_capt_lvl] > 0)
			)
		description: """
Purpose: Tracks reps w actlvl count.
Logic: Counts distinct values in users_history[ci_act_capt_lvl] under filters.
Dependencies: Columns: users_history[ci_act_capt_lvl]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _acl_ta_analysis
		lineageTag: cb1894d2-ba0e-4792-8b22-f9f580f4b5e6

	/// Measure meas.reps_w_time_allocation_pct.
	measure 'meas.reps_w_time_allocation_pct' =
			
			var reps_w_ta = [meas.reps_w_time_allocation_count]
			var reps_tot = [meas.data_logs_user_count_eop]
			
			var res = DIVIDE(reps_w_ta, reps_tot)
			return res
		description: """
Purpose: Tracks reps w time allocation percentage.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop], [meas.reps_w_time_allocation_count]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _acl_ta_analysis
		lineageTag: cf3b1586-2449-41dd-8a8a-325aecdcf614

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "MathematicalPercentageDifference",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.reps_w_time_allocation_count.
	measure 'meas.reps_w_time_allocation_count' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <=  toDate   && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) >=  toDate && users_history[ci_time_alloc_tot] >0 ) // make sure we only include reps that are in the active  and user having time allocation greater than 0
			
			var res = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, [_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			return res // return the res :)
			```
		description: """
Purpose: Tracks reps w time allocation count.
Logic: Counts rows using users_history[_sys_filt_start_date] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_filt_start_date], users_history[tru...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: 390d2dd9-6f68-455a-a819-a36c90a9703c

	/// Measure meas.users_history_row_filler.
	measure 'meas.users_history_row_filler' = ""
		description: """
Purpose: Tracks users history row filler.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 6ddcb848-f676-401c-a8b8-ee85f6065845

	/// Measure meas.sys.user_id_for_am.
	measure 'meas.sys.user_id_for_am' =
			
			CALCULATE(
				DISTINCTCOUNT('users_history'[_sys_user_id]),
				'users_history'[trueai_user_role_function] IN { "AM" }
			)
		description: """
Purpose: Tracks sys user id for am.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Columns: 'users_history'[_sys_user_id], 'users_history'[trueai_user_role_function]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: __needs_attention
		lineageTag: e13717b1-4053-45c3-8c69-b95248010273

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

	/// Measure meas.di.trueai_opps_won_amt_am_avg.
	measure 'meas.di.trueai_opps_won_amt_am_avg' =
			
			DIVIDE(
			    SUM(ssr_history[opp_won_amt])+0,
			    [meas.sys.user_id_for_am]
			)
		description: """
Purpose: Tracks di trueai opportunities won amount am average.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.sys.user_id_for_am]; Columns: ssr_history[opp_won_amt]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _results_analysis
		lineageTag: 672dae6d-f8c4-4494-ad53-bf9b1cb93fb6

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "MathematicalDivision",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.sys.user_id_for_ae.
	measure 'meas.sys.user_id_for_ae' =
			
			CALCULATE(
				DISTINCTCOUNT('users_history'[_sys_user_id]),
				'users_history'[trueai_user_role_function] IN { "AE" }
			)
		description: """
Purpose: Tracks sys user id for ae.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Columns: 'users_history'[_sys_user_id], 'users_history'[trueai_user_role_function]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: __needs_attention
		lineageTag: 443717c6-2617-4712-9ee1-236180210cdb

	/// Measure meas.sys.user_id_for_sdr.
	measure 'meas.sys.user_id_for_sdr' =
			
			CALCULATE(
				DISTINCTCOUNT('users_history'[_sys_user_id]),
				'users_history'[trueai_user_role_function] IN { "SDR" }
			)
		description: """
Purpose: Tracks sys user id for sdr.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Columns: 'users_history'[_sys_user_id], 'users_history'[trueai_user_role_function]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: __needs_attention
		lineageTag: b95fcde4-0bcd-4deb-8ac0-ef02a18103d6

	/// Measure meas.sys.user_id_for_nd.
	measure 'meas.sys.user_id_for_nd' =
			
			CALCULATE(
				DISTINCTCOUNT('users_history'[_sys_user_id]),
				'users_history'[trueai_user_role_function] IN { "ND" }
			)
		description: """
Purpose: Tracks sys user id for nd.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Columns: 'users_history'[_sys_user_id], 'users_history'[trueai_user_role_function]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: __needs_attention
		lineageTag: 60ef9f77-bd16-4f97-a5b9-a3d8fd5f0927

	/// Measure meas.sys.user_id_for_other.
	measure 'meas.sys.user_id_for_other' =
			
			CALCULATE(
				DISTINCTCOUNT('users_history'[_sys_user_id]),
				'users_history'[trueai_user_role_function] IN { "OTHER" }
			)
		description: """
Purpose: Tracks sys user id for other.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Columns: 'users_history'[_sys_user_id], 'users_history'[trueai_user_role_function]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: __needs_attention
		lineageTag: a67bea40-cc9d-4b93-b763-4082390316e3

	/// Measure meas.di.trueai_opps_won_amt_ae_avg.
	measure 'meas.di.trueai_opps_won_amt_ae_avg' =
			
			DIVIDE(
			    SUM(ssr_history[opp_won_amt])+0,
			    [meas.sys.user_id_for_ae]
			)
		description: """
Purpose: Tracks di trueai opportunities won amount ae average.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.sys.user_id_for_ae]; Columns: ssr_history[opp_won_amt]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _results_analysis
		lineageTag: 4e7673c7-6ba5-4aaa-8092-0bb53c634fad

		changedProperty = FormatString

	/// Measure meas.di.trueai_opps_won_amt_sdr_avg.
	measure 'meas.di.trueai_opps_won_amt_sdr_avg' =
			
			DIVIDE(
			    SUM(ssr_history[opp_won_amt])+0,
			    [meas.sys.user_id_for_sdr]
			)
		description: """
Purpose: Tracks di trueai opportunities won amount sdr average.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.sys.user_id_for_sdr]; Columns: ssr_history[opp_won_amt]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _results_analysis
		lineageTag: 98385d82-fa66-49df-896d-e5ab747667eb

		changedProperty = FormatString

	/// Measure meas.di.trueai_opps_won_amt_nd_avg.
	measure 'meas.di.trueai_opps_won_amt_nd_avg' =
			
			DIVIDE(
			    SUM(ssr_history[opp_won_amt])+0,
			    [meas.sys.user_id_for_nd]
			)
		description: """
Purpose: Tracks di trueai opportunities won amount nd average.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.sys.user_id_for_nd]; Columns: ssr_history[opp_won_amt]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _results_analysis
		lineageTag: 225d81ac-2ee8-468b-b631-d57e12f9c289

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.di.trueai_opps_won_amt_mgr_avg.
	measure 'meas.di.trueai_opps_won_amt_mgr_avg' =
			
			DIVIDE(
			    SUM(ssr_history[opp_won_amt])+0,
			    [meas.sys.user_id_for_mgr]
			)
		description: """
Purpose: Tracks di trueai opportunities won amount mgr average.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.sys.user_id_for_mgr]; Columns: ssr_history[opp_won_amt]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _results_analysis
		lineageTag: adeb39fc-4055-4ab4-8198-862c0d190999

		changedProperty = FormatString

	/// Measure meas.sys.user_id_for_mgr.
	measure 'meas.sys.user_id_for_mgr' =
			
			CALCULATE(
				DISTINCTCOUNT('users_history'[_sys_user_id]),
				'users_history'[trueai_user_role_function] IN { "MGMT" }
			)
		description: """
Purpose: Tracks sys user id for mgr.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Columns: 'users_history'[_sys_user_id], 'users_history'[trueai_user_role_function]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: __needs_attention
		lineageTag: 8421e203-c9d1-468b-affe-165f59ada1ae

	/// Measure meas.di.trueai_opps_won_amt_other_avg.
	measure 'meas.di.trueai_opps_won_amt_other_avg' =
			
			DIVIDE(
			    SUM(ssr_history[opp_won_amt])+0,
			    [meas.sys.user_id_for_other]
			)
		description: """
Purpose: Tracks di trueai opportunities won amount other average.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.sys.user_id_for_other]; Columns: ssr_history[opp_won_amt]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _results_analysis
		lineageTag: e4a86f1b-abb3-4193-95f4-fcbed163093b

		changedProperty = FormatString

	/// _rep
	measure 'meas.count_trueai_user_role_account_executive' = ```
			
			var min_date = [meas.context_date_min]
			var user_filt = filter(users, If(IsBlank([trueai_termination_date]), date(2100,01,01), [trueai_termination_date]) > min_date)
			
			var res = CALCULATE(
			    DISTINCTCOUNT(users_history[_sys_user_id])+0,
			    users_history[trueai_user_role] IN { "Account Executive"  },user_filt
			)
			return res 
			```
		description: """
Purpose: Tracks count trueai user role account executive.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_user_role]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: f9380111-412f-4044-b400-0d2ca99a2968

	/// _rep
	measure 'meas.count_trueai_user_role_account_manager' = ```
			
			var min_date = [meas.context_date_min]
			var user_filt = filter(users, If(IsBlank([trueai_termination_date]), date(2100,01,01), [trueai_termination_date]) > min_date)
			
			var res = CALCULATE(
			    DISTINCTCOUNT('users_history'[_sys_user_id])+0,
			    users_history[trueai_user_role] IN { "Account Manager"  },user_filt
			)
			return res 
			```
		description: """
Purpose: Tracks count trueai user role account manager.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_min]; Columns: 'users_history'[_sys_user_id], users_history[trueai_user_role]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _rep_count_analysis
		lineageTag: 5569d550-425e-4fd9-99b5-14bb55a3efff

	/// _rep
	measure 'meas.count_trueai_user_role_sales_manager' = ```
			
			var min_date = [meas.context_date_min] // get the min date of the period
			var user_filt = filter(users, If(IsBlank([trueai_termination_date]), date(2100,01,01), [trueai_termination_date]) > min_date) // filter anyone who was terminated prior to start of period
			
			var res = CALCULATE(
			    DISTINCTCOUNT('users_history'[_sys_user_id])+0,
			    users_history[trueai_user_role] IN { "Sales Manager"  },user_filt
			)
			return res 
			```
		description: """
Purpose: Tracks count trueai user role sales manager.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_min]; Columns: 'users_history'[_sys_user_id], users_history[trueai_user_role]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: b6ac59ea-d721-4ef6-8c5b-230bf0de8e09

	/// _rep
	measure 'meas.count_trueai_user_role_nd' = ```
			
			var min_date = [meas.context_date_min]
			var user_filt = filter(users, If(IsBlank([trueai_termination_date]), date(2100,01,01), [trueai_termination_date]) > min_date)
			
			var res = CALCULATE(
			    DISTINCTCOUNT('users_history'[_sys_user_id])+0,
			    users_history[trueai_user_role] IN { "ND"  },user_filt
			)
			return res 
			```
		description: """
Purpose: Tracks count trueai user role nd.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_min]; Columns: 'users_history'[_sys_user_id], users_history[trueai_user_role]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 42d75b4a-4848-4708-8151-7a0816e02c31

	/// _rep
	measure 'meas.count_trueai_user_role_sales_development_rep' = ```
			var min_date = [meas.context_date_min] // get the min date of the period
			var user_filt = filter(users, If(IsBlank([trueai_termination_date]), date(2100,01,01), [trueai_termination_date]) > min_date) // filter anyone who was terminated prior to start of period
			
			var res = CALCULATE(
			    DISTINCTCOUNT('users_history'[_sys_user_id])+0,
			    users_history[trueai_user_role] IN { "Sales Development Rep"  },user_filt
			)
			return res 
			```
		description: """
Purpose: Tracks count trueai user role sales development rep.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_min]; Columns: 'users_history'[_sys_user_id], users_history[trueai_user_role]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: be269a0b-7718-4e82-ac59-c6b6bda76360

	/// Measure meas.user_history_count_dept_sales.
	measure 'meas.user_history_count_dept_sales' =
			
			CALCULATE(
				DISTINCTCOUNT('users_history'[_sys_user_id]),
				'users_history'[trueai_user_role_department] IN { "SALES" }
			)
		description: """
Purpose: Tracks user history count dept sales.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Columns: 'users_history'[_sys_user_id], 'users_history'[trueai_user_role_department]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 7f8f335e-b7db-4e7c-b4f8-42e49526f783

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

	/// _rep
	measure 'meas.count_trueai_user_role_account_executive_in_group_nd' =
			
			CALCULATE(
			    [meas.count_trueai_user_role_account_executive],
			    users_history[trueai_group] IN { "ND" }
			)
		description: """
Purpose: Tracks count trueai user role account executive in group nd.
Logic: Counts rows using users_history[trueai_group] under filters.
Dependencies: Measures: [meas.count_trueai_user_role_account_executive]; Columns: users_history[trueai_group]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 9ca49175-64b3-4320-a764-4d0ddba97eed

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

	/// _rep
	measure 'meas.count_trueai_user_role_all_salesteam' = ```
			var min_date = [meas.context_date_min]
			var user_filt = filter(users, If(IsBlank([trueai_termination_date]), date(2100,01,01), [trueai_termination_date]) > min_date)
			
			var res = CALCULATE(
			    DISTINCTCOUNT('users_history'[_sys_user_id])+0,
			    users_history[trueai_user_role] IN { "Account Executive", "Account Manager", "Sales Development Rep", "Sales Manager", "ND", "Other", "Sales Executive"  },user_filt
			)
			return res 
			
			```
		description: """
Purpose: Tracks count trueai user role all salesteam.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_min]; Columns: 'users_history'[_sys_user_id], users_history[trueai_user_role]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 5ba6ff62-c218-4a8c-a401-b26f5bbba04f

	/// _rep
	measure 'meas.count_trueai_user_role_other' = ```
			var min_date = [meas.context_date_min] // get the min date of the period
			var user_filt = filter(users, If(IsBlank([trueai_termination_date]), date(2100,01,01), [trueai_termination_date]) > min_date) // filter anyone who was terminated prior to start of period
			
			var res = CALCULATE(
			    DISTINCTCOUNT('users_history'[_sys_user_id])+0,
			    users_history[trueai_user_role_function] IN { "OTHER ROLES"  },user_filt
			)
			return res 
			```
		description: """
Purpose: Tracks count trueai user role other.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_min]; Columns: 'users_history'[_sys_user_id], users_history[trueai_user_role_function]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 2096bd64-ff8b-4b2f-8629-80b6e89051cb

	/// _rep
	measure 'meas.count_trueai_user_role_sales_executive' = ```
			
			var min_date = [meas.context_date_min] // get the min date of the period
			var user_filt = filter(users, If(IsBlank([trueai_termination_date]), date(2100,01,01), [trueai_termination_date]) > min_date) // filter anyone who was terminated prior to start of period
			
			var res = CALCULATE(
			    DISTINCTCOUNT('users_history'[_sys_user_id])+0,
			    users_history[trueai_user_role] IN {"Sales Executive"},user_filt
			)
			return res 
			```
		description: """
Purpose: Tracks count trueai user role sales executive.
Logic: Counts distinct values in 'users_history'[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_min]; Columns: 'users_history'[_sys_user_id], users_history[trueai_user_role]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 32655af9-d185-476f-9a78-27fbb9ffbcb5

	/// Measure meas.data_logs_user_count_eop_for_dept_support.
	measure 'meas.data_logs_user_count_eop_for_dept_support' =
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] IN { "SUPPORT" }
			)
		description: """
Purpose: Tracks data logs user count eop for dept support.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: 1e6d0ed8-aaae-4efe-b4d3-51a8c8c2b16c

	/// Measure meas.data_logs_user_count_eop_for_dept_ops.
	measure 'meas.data_logs_user_count_eop_for_dept_ops' =
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] IN { "OPS" }
			)
		description: """
Purpose: Tracks data logs user count eop for dept ops.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: e9b2eb17-1691-4b12-825c-1f151ac84361

	/// Measure meas.data_logs_user_count_eop_for_dept_nd.
	measure 'meas.data_logs_user_count_eop_for_dept_nd' =
			
			CALCULATE(
			    [meas.data_logs_user_count_eop]+0,
			    users_history[trueai_user_role_department] IN { "ND" }
			)
		description: """
Purpose: Tracks data logs user count eop for dept nd.
Logic: Counts rows using users_history[trueai_user_role_department] under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: users_history[trueai_user_role_department]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: #,0
		displayFolder: _rep_count_analysis
		lineageTag: b7c20247-953b-46d0-b3ca-169b075bde67

	/// Measure meas.data_logs_won_amt_user_eop_avg.
	measure 'meas.data_logs_won_amt_user_eop_avg' =
			
			DIVIDE(
				SUM(ssr_history[opp_won_amt]),
				[meas.data_logs_user_count_eop]
			)
		description: """
Purpose: Tracks data logs won amount user eop average.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: ssr_history[opp_won_amt]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _results_analysis
		lineageTag: c630a93b-07a9-455d-8f3a-3c935cffedba

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "MathematicalDivision",
				  "version": 0
				}

		changedProperty = FormatString

	/// Measure meas.data_logs_pipeline_amt_user_eop_avg.
	measure 'meas.data_logs_pipeline_amt_user_eop_avg' =
			
			DIVIDE(
			        SUM('ssr_history'[opp_pipeline_amt]),
			        [meas.data_logs_user_count_eop]
			)
		description: """
Purpose: Tracks data logs pipeline amount user eop average.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: 'ssr_history'[opp_pipeline_amt]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _results_analysis
		lineageTag: e3899a10-a1ed-4134-b2f9-aa52c0d6645e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.data_logs_won_amt_user_eop_avg_for_new_logo_selling.
	measure 'meas.data_logs_won_amt_user_eop_avg_for_new_logo_selling' = ```
			
			var reps = [meas.data_logs_user_count_eop]
			var won_amt = CALCULATE(SUM(ssr_history[opp_won_amt]), ssr_history[step_name] IN { "New Logo Selling" })
			
			var res = DIVIDE(won_amt, reps)
			return res 
			```
		description: """
Purpose: Tracks data logs won amount user eop average for new logo selling.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: ssr_history[opp_won_amt], ssr_history[step_name]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _results_analysis
		lineageTag: e942f6df-814c-42d0-a743-58d166e9dce8

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.data_logs_won_amt_user_eop_avg_for_existing_acv.
	measure 'meas.data_logs_won_amt_user_eop_avg_for_existing_acv' = ```
			
			var reps = [meas.data_logs_user_count_eop]
			var won_amt = CALCULATE(SUM(ssr_history[opp_won_amt]), ssr_history[step_name] IN { "New Logo Selling", "Existing Customer Selling" } && ssr_history[col.opp_acv_classification] = 
			"Existing Customer Selling ACV")
			
			var res = DIVIDE(won_amt, reps)
			return res 
			```
		description: """
Purpose: Tracks data logs won amount user eop average for existing acv.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: ssr_history[opp_won_amt], ssr_history[step_name], ssr_history[col.opp_a...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _results_analysis
		lineageTag: 5fcf4a6a-efa3-4459-988e-6eb31406c216

		changedProperty = FormatString

	/// Measure meas.data_logs_won_amt_user_eop_avg_for_new_acv.
	measure 'meas.data_logs_won_amt_user_eop_avg_for_new_acv' = ```
			
			var reps = [meas.data_logs_user_count_eop]
			var won_amt = CALCULATE(SUM(ssr_history[opp_won_amt]), ssr_history[step_name] IN { "New Logo Selling", "Existing Customer Selling" } && ssr_history[col.opp_acv_classification] = 
			"New ACV")
			
			var res = DIVIDE(won_amt, reps)
			return res 
			```
		description: """
Purpose: Tracks data logs won amount user eop average for new acv.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: ssr_history[opp_won_amt], ssr_history[step_name], ssr_history[col.opp_a...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _results_analysis
		lineageTag: 0b8c546c-cfa8-4fad-9bdc-f3d297110235

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "FilteredMeasure",
				  "version": 0
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.user_history_user_new_hires_terminated_in_12_month_pos.
	measure 'meas.user_history_user_new_hires_terminated_in_12_month_pos' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			var termed_within12 = CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), 
			           users_history[trueai_hire_date] >= fromDate &&     users_history[trueai_hire_date]  <= toDate -- hired this year
			           && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) < users_history[trueai_hire_date] +365) -- terminated within a year
			
			var res = if(isblank(termed_within12),0,termed_within12 )
			return res
			```
		description: """
Purpose: Tracks user history user new hires terminated in 12 month pos.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_user_id], users_history[trueai_hire...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _ramp_analysis
		lineageTag: 640150f5-397a-4029-bd36-e53852d020d0

	/// Measure meas.data_logs_won_amt_user_eop_avg_for_existing_customer_selling.
	measure 'meas.data_logs_won_amt_user_eop_avg_for_existing_customer_selling' = ```
			
			var reps = [meas.data_logs_user_count_eop]
			var won_amt = CALCULATE(SUM(ssr_history[opp_won_amt]), ssr_history[step_name] IN { "Existing Customer Selling" })
			
			var res = DIVIDE(won_amt, reps)
			return res 
			```
		description: """
Purpose: Tracks data logs won amount user eop average for existing customer selling.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop]; Columns: ssr_history[opp_won_amt], ssr_history[step_name]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _results_analysis
		lineageTag: f32bbee9-a90c-45cb-abb0-8f9a96ef2221

		changedProperty = FormatString

	/// Measure meas.users_history_row_filler2.
	measure 'meas.users_history_row_filler2' = ""
		description: """
Purpose: Tracks users history row filler2.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: edeb15e2-b186-459d-8646-a21595bab838

	/// Measure meas.users_history_row_filler3.
	measure 'meas.users_history_row_filler3' = ""
		description: """
Purpose: Tracks users history row filler3.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: fb5ce7e1-3b57-4caa-b47c-75f38cf431ca

	/// Measure meas.users_history_row_filler4.
	measure 'meas.users_history_row_filler4' = ""
		description: """
Purpose: Tracks users history row filler4.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 8980361f-9d0f-4b4f-a5b9-adfe40234d48

	/// Measure meas.users_history_row_filler5.
	measure 'meas.users_history_row_filler5' = ""
		description: """
Purpose: Tracks users history row filler5.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: c1e1b654-df56-4f96-a7f2-b175c3e859ef

	/// Measure meas.users_history_row_filler6.
	measure 'meas.users_history_row_filler6' = ""
		description: """
Purpose: Tracks users history row filler6.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 2f5a5d5a-b880-4048-a7c5-e5d12008ee28

	/// Measure meas.users_history_row_filler7.
	measure 'meas.users_history_row_filler7' = ""
		description: """
Purpose: Tracks users history row filler7.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 3e1bb5f9-21ff-4763-b675-e056bebbc144

	/// Measure meas.users_history_row_filler8.
	measure 'meas.users_history_row_filler8' = ""
		description: """
Purpose: Tracks users history row filler8.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 7aa1bc6d-19ee-4f88-8447-c4ebd53bf512

	/// Measure meas.users_history_row_filler9.
	measure 'meas.users_history_row_filler9' = ""
		description: """
Purpose: Tracks users history row filler9.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 969c4058-2234-4575-ba9f-0cc3d76a47ce

	/// Measure meas.users_history_row_filler10.
	measure 'meas.users_history_row_filler10' = ""
		description: """
Purpose: Tracks users history row filler10.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: f362c584-a411-4e49-bbf6-31cb18a66a80

	/// Measure meas.users_history_row_filler11.
	measure 'meas.users_history_row_filler11' = ""
		description: """
Purpose: Tracks users history row filler11.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: a6884327-0fed-4df0-8827-faaeeda5986f

	/// Measure meas.users_history_row_filler12.
	measure 'meas.users_history_row_filler12' = ""
		description: """
Purpose: Tracks users history row filler12.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 13189c9e-d0d2-42cd-a41c-e2969b8dab74

	/// Measure meas.users_history_row_filler13.
	measure 'meas.users_history_row_filler13' = ""
		description: """
Purpose: Tracks users history row filler13.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 68cc992c-591e-4f1f-9386-89571ceb05af

	/// Measure meas.users_history_row_filler14.
	measure 'meas.users_history_row_filler14' = ""
		description: """
Purpose: Tracks users history row filler14.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: 272625e7-1621-4db5-a38a-56e0f218088a

	/// Measure meas.users_history_row_filler15.
	measure 'meas.users_history_row_filler15' = ""
		description: """
Purpose: Tracks users history row filler15.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _filler
		lineageTag: bce5d1d3-b76b-4858-862e-46f081a4d53b

	/// Measure meas.data_logs_user_turnover_pct.
	measure 'meas.data_logs_user_turnover_pct' =
			
			var res =DIVIDE(
				[meas.data_logs_user_new_terminations_pos],
				[meas.data_logs_user_count_bop]
			)
			RETURN
			IF(
			    res=BLANK(),
			    0,
			    res
			)
		description: """
Purpose: Tracks data logs user turnover percentage.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_bop], [meas.data_logs_user_new_terminations_pos]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _rep_count_analysis
		lineageTag: c17b7b54-4e31-4d1e-bf1c-4aea962f150d

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "MathematicalDivision",
				  "version": 0
				}

	/// Measure meas.time_allocation_total_not_eng.
	measure 'meas.time_allocation_total_not_eng' =
			
			AVERAGE('users_history'[ci_time_alloc_tot]) - AVERAGE('users_history'[ci_time_alloc_tot_eng])
		description: """
Purpose: Tracks time allocation total not eng.
Logic: Averages 'users_history'[ci_time_alloc_tot] under filters.
Dependencies: Columns: 'users_history'[ci_time_alloc_tot], 'users_history'[ci_time_alloc_tot_eng]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _ta_analysis
		lineageTag: 73db7ecd-c91c-482b-93eb-8deebec2a09f

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "MathematicalSubtraction",
				  "version": 0
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.users_history_ta_potential_vs_actual.
	measure 'meas.users_history_ta_potential_vs_actual' = ```
			
			var uh_filt_tbl = CALCULATETABLE(users_history, users_history[ci_time_alloc_tot] <> blank())
			var ratio = AVERAGEX(uh_filt_tbl, DIVIDE(users_history[ci_time_alloc_tot] * users_history[ci_time_alloc_month_to_week_adjustment], users_history[col.ci_ta_potential_hours]) )
			var res  = ratio
			return res
			
			```
		description: """
Purpose: Tracks users history ta potential vs actual.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Columns: users_history[ci_time_alloc_tot], users_history[ci_time_alloc_month_to_week_adjustment], users_history[col.ci_ta_p...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _ta_analysis
		lineageTag: dd9b7816-b83c-4d60-bfb1-f374cc0531f5

	/// Measure meas.data_logs_user_turnover_pct_regrettable.
	measure 'meas.data_logs_user_turnover_pct_regrettable' =
			
			
			var res = DIVIDE(
				[meas.data_logs_user_new_terminations_regrettable],
				[meas.data_logs_user_count_bop]
				* 1
			)
			
			RETURN
			ABS(res)
		description: """
Purpose: Tracks data logs user turnover percentage regrettable.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_bop], [meas.data_logs_user_new_terminations_regrettable]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _rep_count_analysis
		lineageTag: 36204f55-92aa-45d3-846e-38ef4694b4bb

	/// Measure meas.data_logs_user_new_terminations_regrettable.
	measure 'meas.data_logs_user_new_terminations_regrettable' = ```
			
			var tbl_perf_users = SUMMARIZE(users_history , users_history[_sys_user_id], "months", Count(users_history[_sys_doc_id]), "avg_perf_tier_num", AVERAGE(users_history[ci_perf_qtly_performance_tier_num])+ 0)
			
			var res = CALCULATE([meas.data_logs_user_new_terminations] , Filter(tbl_perf_users, [avg_perf_tier_num] >=2)) +0 
			
			return res
			
			
			```
		description: """
Purpose: Tracks data logs user new terminations regrettable.
Logic: Counts rows using users_history[_sys_user_id] under filters.
Dependencies: Measures: [meas.data_logs_user_new_terminations]; Columns: users_history[_sys_user_id], users_history[_sys_doc_id], users_h...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _rep_count_analysis
		lineageTag: 64a5d1ae-0403-49d9-b03e-a8ef509b3d19

	/// Measure meas.users_history_user_role_function_concat_w_count_eop.
	measure 'meas.users_history_user_role_function_concat_w_count_eop' = ```
			
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <  toDate   && if(isblank([trueai_termination_date]), date(2100,1,1),[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			
			-- concats all the crm values for trueai value
			
			-- summarize the currect context and sort by count desc
			var tbl_summarized = TOPN(10,SUMMARIZE(active_users_tbl, [trueai_user_role_function], [trueai_user_role_alias], "count", Count(users[_sys_doc_id]) ),[count], DESC)
			
			-- use the summarized data and concat
			var str_crm_vals = CONCATENATEX(tbl_summarized, [trueai_user_role_function] & ": " & [trueai_user_role_alias] & " (" & [count]  & ")", ", ") 
			
			var res = str_crm_vals -- output string
			return res
			
			
			```
		description: """
Purpose: Tracks users history user role function concat w count eop.
Logic: Counts rows using users_history[_sys_filt_start_date] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: users_history[_sys_filt_start_date], users[_sys_doc_id]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		lineageTag: d413b1b6-88bb-4362-ba1f-b09ba6abc6ae

	/// Measure meas.exp_rpts_all_avg_perf_tier.
	measure 'meas.exp_rpts_all_avg_perf_tier' = ```
			
			 var calc = CALCULATE(AVERAGE(users_history[ci_perf_qtly_performance_tier_num]))
			var res = if(isblank(calc), blank(),calc)
			return res
			```
		description: """
Purpose: Tracks exp rpts all average perf tier.
Logic: Averages users_history[ci_perf_qtly_performance_tier_num] under filters.
Dependencies: Columns: users_history[ci_perf_qtly_performance_tier_num]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: 0.00
		displayFolder: _export_rpts
		lineageTag: ae176c1b-1966-4b3d-bbf0-fa4cbe7fc464

	/// Measure meas.exp_rpts_last_year_avg_perf_tier.
	measure 'meas.exp_rpts_last_year_avg_perf_tier' = CALCULATE(users_history[meas.exp_rpts_all_avg_perf_tier], time_intelligence[filt_item] = "LAST_YEAR")
		description: """
Purpose: Tracks exp rpts last year average perf tier.
Logic: Derived from model references under current filters.
Dependencies: Measures: [meas.exp_rpts_all_avg_perf_tier]; Columns: users_history[meas.exp_rpts_all_avg_perf_tier], time_intelligence[fil...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: 0.00
		displayFolder: _export_rpts
		lineageTag: 4cab50c1-511d-439f-89d3-669c0173ffcc

	/// Measure meas.exp_rpts_prior_to_last_year_avg_perf_tier.
	measure 'meas.exp_rpts_prior_to_last_year_avg_perf_tier' = CALCULATE(users_history[meas.exp_rpts_all_avg_perf_tier], time_intelligence[filt_item] = "PRIOR_TO_LAST_YEAR")
		description: """
Purpose: Tracks exp rpts prior to last year average perf tier.
Logic: Derived from model references under current filters.
Dependencies: Measures: [meas.exp_rpts_all_avg_perf_tier]; Columns: users_history[meas.exp_rpts_all_avg_perf_tier], time_intelligence[fil...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: 0.00
		displayFolder: _export_rpts
		lineageTag: c7aef491-020f-4a36-abf4-ec5b554a1bfa

	/// Measure meas.exp_rpts_current_year_avg_perf_tier.
	measure 'meas.exp_rpts_current_year_avg_perf_tier' = CALCULATE(users_history[meas.exp_rpts_all_avg_perf_tier], time_intelligence[filt_item] = "CURRENT_YEAR")
		description: """
Purpose: Tracks exp rpts current year average perf tier.
Logic: Derived from model references under current filters.
Dependencies: Measures: [meas.exp_rpts_all_avg_perf_tier]; Columns: users_history[meas.exp_rpts_all_avg_perf_tier], time_intelligence[fil...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: 0.00
		displayFolder: _export_rpts
		lineageTag: db51bd07-3023-4d79-b5df-64359d2834ba

	/// Measure meas.data_logs_user_count_all.
	measure 'meas.data_logs_user_count_all' = [meas.data_logs_user_count_eop_for_dept_mkt]+[meas.data_logs_user_count_eop_for_dept_nd]+[meas.data_logs_user_count_eop_for_dept_ops]+[meas.data_logs_user_count_eop_for_dept_other]+[meas.data_logs_user_count_eop_for_dept_sales]+[meas.data_logs_user_count_eop_for_dept_support]
		description: """
Purpose: Tracks data logs user count all.
Logic: Counts rows under filters.
Dependencies: Measures: [meas.data_logs_user_count_eop_for_dept_mkt], [meas.data_logs_user_count_eop_for_dept_nd], [meas.data_logs_user_c...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _rep_count_analysis
		lineageTag: bd7a4307-ed50-4555-bd87-089699d608ba

	/// Measure meas.calibration_user_role_title.
	measure 'meas.calibration_user_role_title' = "User Roles - " & [meas.prior_year] & " Full Calendar Year"
		description: """
Purpose: Tracks calibration user role title.
Logic: Derived from model references under current filters.
Dependencies: Measures: [meas.prior_year]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		displayFolder: _rep_count_analysis
		lineageTag: b46bd447-2ddc-4adc-a282-c0bd8c15171d

	/// Measure meas.data_logs_ci_perf_annual_avg_bookings_account_executive.
	measure 'meas.data_logs_ci_perf_annual_avg_bookings_account_executive' = ```
			
			var end_date =   [meas.companies_history_reference_date]
			var start_date =  end_date - 365 //dateadd( {end_date},-1, year)
			var res =  CALCULATE(AVERAGE(users_history[ci_perf_qtly_avg_bookings_peers]), cal_end_dates[Date] >start_date &&  end_date <= end_date, users_history[trueai_user_role]="Account Executive") // qtly number
			return res * 4 // annual number
			
			```
		description: """
Purpose: Tracks data logs ci perf annual average bookings account executive.
Logic: Counts rows using users_history[ci_perf_qtly_avg_bookings_peers] under filters.
Dependencies: Measures: [meas.companies_history_reference_date]; Columns: users_history[ci_perf_qtly_avg_bookings_peers], cal_end_dates[D...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _perf_analysis
		lineageTag: 03cf934b-81ba-444c-87f7-f0d6df3312dd

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.data_logs_ci_perf_annual_avg_bookings_account_manager.
	measure 'meas.data_logs_ci_perf_annual_avg_bookings_account_manager' = ```
			
			var end_date =   [meas.companies_history_reference_date]
			var start_date =  end_date - 365 //dateadd( {end_date},-1, year)
			var res =  CALCULATE(AVERAGE(users_history[ci_perf_qtly_avg_bookings_peers]), cal_end_dates[Date] >start_date &&  end_date <= end_date, users_history[trueai_user_role]="Account Manager") // qtly number
			return res * 4 // annual number
			
			```
		description: """
Purpose: Tracks data logs ci perf annual average bookings account manager.
Logic: Counts rows using users_history[ci_perf_qtly_avg_bookings_peers] under filters.
Dependencies: Measures: [meas.companies_history_reference_date]; Columns: users_history[ci_perf_qtly_avg_bookings_peers], cal_end_dates[D...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _perf_analysis
		lineageTag: f48cadb1-b2f6-4fb7-ba35-e7ebc413f6c9

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.data_logs_ci_perf_annual_avg_pipeline_created_sdr.
	measure 'meas.data_logs_ci_perf_annual_avg_pipeline_created_sdr' =
			
			var end_date =   [meas.companies_history_reference_date]
			var start_date =  end_date - 365 //dateadd( {end_date},-1, year)
			var res =  CALCULATE(AVERAGE(users_history[col.ci.perf_qtly_avg_pipeline_peers]), cal_end_dates[Date] >start_date &&  end_date <= end_date, users_history[trueai_user_role]="Sales Development Rep") // qtly number
			return res * 4 // annual number
		description: """
Purpose: Tracks data logs ci perf annual average pipeline created sdr.
Logic: Averages users_history[col.ci.perf_qtly_avg_pipeline_peers] under filters.
Dependencies: Measures: [meas.companies_history_reference_date]; Columns: users_history[col.ci.perf_qtly_avg_pipeline_peers], cal_end_dat...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _perf_analysis
		lineageTag: b40da212-94ff-4335-a3c8-1110586f6e22

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.perf_consider_mrasure.
	measure 'meas.perf_consider_mrasure' = "To be considered a Performer, a rep needs to fall within +/- 35% of AAB / AAPC"
		description: """
Purpose: Tracks perf consider mrasure.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _perf_analysis
		lineageTag: e36df813-494b-4999-a2d5-0c02c594db11

	/// Measure meas.calibration_department_title.
	measure 'meas.calibration_department_title' = "Department - " & [meas.prior_year] & " Full Calendar Year"
		description: """
Purpose: Tracks calibration department title.
Logic: Derived from model references under current filters.
Dependencies: Measures: [meas.prior_year]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		displayFolder: _rep_count_analysis
		lineageTag: 6f133e82-cd13-456d-ba5f-2bb46c770268

	/// Measure meas.calibration_group_title.
	measure 'meas.calibration_group_title' = "Group - " & [meas.prior_year] & " Full Calendar Year"
		description: """
Purpose: Tracks calibration group title.
Logic: Derived from model references under current filters.
Dependencies: Measures: [meas.prior_year]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		displayFolder: _rep_count_analysis
		lineageTag: f1b13f39-437e-469b-977e-2ef145c2c495

	/// Measure meas.data_logs_ci_perf_status.
	measure 'meas.data_logs_ci_perf_status' = ```
			
			
			-- get the dates
			var end_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var start_date = EDATE(end_date, -12) // get the start date from end_date
			
			
			var perf_tier_num = CALCULATE(
			    AVERAGE(
			        users_history[ci_perf_qtly_performance_tier_num]
			    ), 
			    users_history[_sys_filt_end_date] > start_date && users_history[_sys_filt_end_date]<end_date
			)  
			var rounded_num = ROUNDUP(perf_tier_num, 0)
			
			RETURN 
			SWITCH(
			    TRUE(),
			    rounded_num =1,  "Underperformer",
			    rounded_num =2,  "Performer",                       // putting an condition to get the performance 
			    rounded_num = 3, "Overperformer"
			)
			```
		description: """
Purpose: Tracks data logs ci perf status.
Logic: Averages cal_end_dates[Date] under filters.
Dependencies: Columns: cal_end_dates[Date], users_history[ci_perf_qtly_performance_tier_num], users_history[_sys_filt_end_date]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _perf_analysis
		lineageTag: a97b7deb-0320-4928-9344-62e8b0ac287e

	/// Measure meas.data_logs_user_12_Mos_ci_perf_status.
	measure 'meas.data_logs_user_12_Mos_ci_perf_status' = ```
			
			
			-- get the dates
			var end_date = [meas.last_date_of_previous_quarter] // get the mgmt current end date
			var start_date = EDATE(end_date, -12) // get the start date from end_date
			
			
			var perf_tier_num = CALCULATE(
			    AVERAGE(
			        users_history[ci_perf_qtly_performance_tier_num]
			    ), 
			    cal_end_dates[Date] >= start_date && cal_end_dates[Date] <= end_date        // get the avg of qrtly perf tier number
			)  
			var rounded_num = ROUND(perf_tier_num, 0)           // rounding the avg number with o decimal point
			
			var ramp_status = [meas.data_logs_users_ramping_status]
			
			RETURN
			 IF(
			    MAX(users[trueai_user_role_department])<>"SALES",
			    "Not in Sales Team",        // result if the user not in sales team
			    IF(
			        MAX(users[trueai_user_role_department])="SALES" && ramp_status="Ramping",
			        "Ramping",          // if the ci_perf_ramping status is ramping then user status 
			        IF(
			            MAX(users[trueai_user_role_department])="SALES" && ramp_status ="Ramped",
			            SWITCH(
			                TRUE(),
			                rounded_num =1 ,  "Underperformer",
			                rounded_num =2 ,  "Performer",                       // putting an condition to get the performance 
			                rounded_num = 3 , "Overperformer",
			                "N/A"
			            )
			        )
			    )
			 )
			```
		description: """
Purpose: Tracks data logs user 12 mos ci perf status.
Logic: Averages users_history[ci_perf_qtly_performance_tier_num] under filters.
Dependencies: Measures: [meas.data_logs_users_ramping_status], [meas.last_date_of_previous_quarter]; Columns: users_history[ci_perf_qtly_...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		displayFolder: _perf_analysis
		lineageTag: 7866caef-955b-4d57-9415-64d9df49695c

	/// Measure meas.data_logs_user_count_rep_eop.
	measure 'meas.data_logs_user_count_rep_eop' = ```
			
			
			var end_date = CALCULATE(MAX(cal_end_dates[Date])) // getting the latest date from the cal_end_date(perio_last_date)
			var start_date = EDATE(end_date, -12) // get the start date from end_date
			
			var fromDate =[meas.context_date_min] 
			var toDate = [meas.context_date_max] 
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			
			var active_users_tbl =  filter(applicable_rows_tbl, [trueai_hire_date] <=  toDate   && if(isblank(users_history[trueai_termination_date]), date(2100,1,1),users_history[trueai_termination_date]) >=  toDate) // make sure we only include reps that are in the active 
			
			var res = COUNTROWS(DISTINCT(SELECTCOLUMNS(active_users_tbl, [_sys_user_id]))) // get a disctinct count of users from that filter context 
			
			return res // return the res :)
			```
		description: """
Purpose: Tracks data logs user count rep eop.
Logic: Counts rows using cal_end_dates[Date] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: cal_end_dates[Date], users_history[_sys_filt_start_dat...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _rep_count_analysis
		lineageTag: aa4e48f7-647a-4d50-ae41-06df2fbef33f

	/// Measure meas.ramping_reps_details_title.
	measure 'meas.ramping_reps_details_title' = "Ramping Reps -   " & [meas.step_owner_user_role_aliased]
		description: """
Purpose: Tracks ramping reps details title.
Logic: Derived from model references under current filters.
Dependencies: Measures: [meas.step_owner_user_role_aliased]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		displayFolder: _ramp_analysis
		lineageTag: 2ab3c61d-7f9a-43c9-9555-deafb52b42f8

	/// Measure meas.reps_w_time_allocation_prospecting_count.
	measure 'meas.reps_w_time_allocation_prospecting_count' =
			
			CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), (users_history[ci_time_alloc_prospecting])>0)
		description: """
Purpose: Tracks reps w time allocation prospecting count.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Columns: users_history[_sys_user_id], users_history[ci_time_alloc_prospecting]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: b9a4709c-76f5-444a-93e1-043c6fba0ff5

	/// Measure meas.reps_w_time_allocation_prospecting_pct.
	measure 'meas.reps_w_time_allocation_prospecting_pct' =
			
			var reps_w_ta = [meas.reps_w_time_allocation_prospecting_count]
			var reps_tot = CALCULATE(DISTINCTCOUNT([_sys_user_id]))
			
			var res = DIVIDE(reps_w_ta, reps_tot)
			return res
		description: """
Purpose: Tracks reps w time allocation prospecting percentage.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.reps_w_time_allocation_prospecting_count]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _acl_ta_analysis
		lineageTag: 95eb85ee-1b16-496a-b04a-aa3042687603

	/// Measure meas.reps_w_time_allocation_new_logo_count.
	measure 'meas.reps_w_time_allocation_new_logo_count' =
			
			CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]), (users_history[ci_time_alloc_new_logo])>0)
		description: """
Purpose: Tracks reps w time allocation new logo count.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Columns: users_history[_sys_user_id], users_history[ci_time_alloc_new_logo]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: dff9104a-517d-4d51-b63b-64e65bacf531

	/// Measure meas.reps_w_time_allocation_new_logo_pct.
	measure 'meas.reps_w_time_allocation_new_logo_pct' =
			
			var reps_w_ta = [meas.reps_w_time_allocation_new_logo_count]
			var reps_tot = CALCULATE(DISTINCTCOUNT([_sys_user_id]))
			
			var res = DIVIDE(reps_w_ta, reps_tot)
			return res
		description: """
Purpose: Tracks reps w time allocation new logo percentage.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.reps_w_time_allocation_new_logo_count]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _acl_ta_analysis
		lineageTag: 59a3a1e0-40af-42fd-8513-123844687a12

	/// Measure meas.reps_w_time_allocation_prospect_pct.
	measure 'meas.reps_w_time_allocation_prospect_pct' =
			
			var reps_w_ta = [meas.reps_w_time_allocation_count]
			var reps_tot = [meas.ssr_history_reps_prospecting]
			
			var res = DIVIDE(reps_w_ta, reps_tot)
			return res
		description: """
Purpose: Tracks reps w time allocation prospect percentage.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.reps_w_time_allocation_count], [meas.ssr_history_reps_prospecting]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _acl_ta_analysis
		lineageTag: c95cc6f4-094d-425d-8174-a1e11580c6ff

	/// Measure meas.reps_all_time_allocation_count.
	measure 'meas.reps_all_time_allocation_count' =
			
			CALCULATE(DISTINCTCOUNT(users_history[_sys_user_id]))
		description: """
Purpose: Tracks reps all time allocation count.
Logic: Counts distinct values in users_history[_sys_user_id] under filters.
Dependencies: Columns: users_history[_sys_user_id]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: aa4c3717-11a2-45fc-b083-3d1126f1fc90

	/// Measure meas.data_logs_user_rep_mgr_ratio_updated.
	measure 'meas.data_logs_user_rep_mgr_ratio_updated' =
			
			VAR _total_role = CALCULATE(
			    [meas.data_logs_user_count_eop], // get the necessary count filtering role dept
			    users_history[trueai_user_role_function] in {"AE","AM", "SDR", "OTHER ROLES"}
			)
			VAR _mgr_count = [meas.data_logs_user_count_eop_for_mgr]   // get the manager count
			var res  = DIVIDE(
			    _total_role,
			    _mgr_count
			)
			
			RETURN
			res
		description: """
Purpose: Tracks data logs user rep mgr ratio updated.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.data_logs_user_count_eop], [meas.data_logs_user_count_eop_for_mgr]; Columns: users_history[trueai_user_role...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: 0.0
		displayFolder: _rep_count_analysis
		lineageTag: 12898c88-6b57-432c-b8f8-c7a8c8bbb2c4

	/// Measure meas.data_logs_users_tenure.
	measure 'meas.data_logs_users_tenure' = ```
			
			-- get the dates
			var end_date = [meas.last_date_of_previous_quarter]
			var start_date = EDATE(end_date, -12) // get the start date from end_date
			
			
			
			var tenure_status =CALCULATE(
			    MAX(
			        users_history[trueai_tenure]
			    ), 
			    cal_end_dates[Date] >= start_date && cal_end_dates[Date] <= end_date        // get the avg of qrtly perf tier number
			)  
			
			
			RETURN
			tenure_status
			```
		description: """
Purpose: Tracks data logs users tenure.
Logic: Returns an extreme value from users_history[trueai_tenure] under filters.
Dependencies: Measures: [meas.last_date_of_previous_quarter]; Columns: users_history[trueai_tenure], cal_end_dates[Date]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: #,##0" Mos."
		displayFolder: _perf_analysis
		lineageTag: 65db4a01-5803-4f39-b98e-2d3164d16f6d

		annotation PBI_FormatHint = {"isCustom":true}

	/// Measure meas.data_logs_users_ramping_status.
	measure 'meas.data_logs_users_ramping_status' = ```
			
			-- get the dates
			var end_date = [meas.last_date_of_previous_quarter]
			var start_date = EDATE(end_date, -12) // get the start date from end_date
			
			
			
			var _status =CALCULATE(
			    MAX(
			        users_history[ci_perf_ramping_status]
			    ), 
			    cal_end_dates[Date] = end_date        // get the avg of qrtly perf tier number
			)  
			
			
			RETURN
			_status
			```
		description: """
Purpose: Tracks data logs users ramping status.
Logic: Returns an extreme value from users_history[ci_perf_ramping_status] under filters.
Dependencies: Measures: [meas.last_date_of_previous_quarter]; Columns: users_history[ci_perf_ramping_status], cal_end_dates[Date]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _perf_analysis
		lineageTag: a73a5ff6-d27e-40cf-b459-57c7e93a4a0e

	/// Measure meas.users_history_ci_time_alloca_avg_existing_cust_selling.
	measure 'meas.users_history_ci_time_alloca_avg_existing_cust_selling' =
			
			CALCULATE(
			    AVERAGE(
			        users_history[ci_time_alloc_existing_customer_selling]      // get the aVERAGE time for existing customer selling
			    )
			)
		description: """
Purpose: Tracks users history ci time alloca average existing customer selling.
Logic: Averages users_history[ci_time_alloc_existing_customer_selling] under filters.
Dependencies: Columns: users_history[ci_time_alloc_existing_customer_selling]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _perf_analysis
		lineageTag: 62dae6ec-b5a6-4618-8717-82729a078884

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.users_history_time_allocation_confidence.
	measure 'meas.users_history_time_allocation_confidence' =
			
			var avg_value = AVERAGE(users_history[ci_time_alloc_conf])    // get the avg of ci time allocation confidence
			
			RETURN avg_value
		description: """
Purpose: Tracks users history time allocation confidence.
Logic: Averages users_history[ci_time_alloc_conf] under filters.
Dependencies: Columns: users_history[ci_time_alloc_conf]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _acl_ta_analysis
		lineageTag: 2059d007-20a9-4cd1-aa99-3c038ce2dd8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.users_history_time_allocation_confidence_status.
	measure 'meas.users_history_time_allocation_confidence_status' = ```
			
			
			var _conf = ROUND(AVERAGE(users_history[ci_time_alloc_conf]),2)*100    // get the avg of ci time allocation confidence
			
			var _status_ = 
			    IF(
			    _conf >= 0 && _conf <= 49, 1,
			        IF(
			            _conf >=50 && _conf <= 74, 2,
			            IF(
			                _conf >=75 && _conf <= 84, 3,
			                IF(
			                    _conf >=85 && _conf <= 94, 4,
			                    5
			                )
			            )
			        )
			)
			
			
			
			RETURN 
			IF(
			    _conf <>0,
			    _status_
			)
			
			```
		description: """
Purpose: Tracks users history time allocation confidence status.
Logic: Averages users_history[ci_time_alloc_conf] under filters.
Dependencies: Columns: users_history[ci_time_alloc_conf]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: ebe06221-1ce3-4e18-9db4-d9701923fee8

	/// Measure meas.time_allocation_confidence.
	measure 'meas.time_allocation_confidence' = ```
			
			
			var _conf = ROUND(AVERAGE(users_history[ci_time_alloc_conf]),2)*100    // get the avg of ci time allocation confidence
			
			var _status_ = 
			    IF(
			    _conf >= 0 && _conf <= 49, "Limited",
			        IF(
			            _conf >=50 && _conf <= 74, "Fair",
			            IF(
			                _conf >=75 && _conf <= 84, "Good",
			                IF(
			                    _conf >=85 && _conf <= 94, "Great",
			                    "Excellent"
			                )
			            )
			        )
			)
			
			
			
			RETURN 
			IF(
			    _conf <>0,
			    _status_ & " (" & _conf & ")"  // Convert _conf to integer text format
			)
			
			```
		description: """
Purpose: Tracks time allocation confidence.
Logic: Averages users_history[ci_time_alloc_conf] under filters.
Dependencies: Columns: users_history[ci_time_alloc_conf]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		displayFolder: _acl_ta_analysis
		lineageTag: 30522698-ba19-4d59-a3c0-a10e54a3a4ae

	/// Measure meas.peek_inside_text_supports_aab.
	measure 'meas.peek_inside_text_supports_aab' = "AAB"
		description: """
Purpose: Tracks peek inside text supports aab.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _helper
		lineageTag: 43c5b6e1-ce31-496d-8af8-614ac968bdde

	/// Measure meas.peek_inside_text_supports_aapc.
	measure 'meas.peek_inside_text_supports_aapc' = "AAPC"
		description: """
Purpose: Tracks peek inside text supports aapc.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _helper
		lineageTag: 22918bb7-2e2d-4dfd-98b3-17eb6b7a6c9b

	/// Measure meas.peek_inside_text_supports_ramping_time.
	measure 'meas.peek_inside_text_supports_ramping_time' = "Ramping Time"
		description: """
Purpose: Tracks peek inside text supports ramping time.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _helper
		lineageTag: ffd6401d-0cfb-4cf4-bcb1-a7739b744def

	/// Measure meas.peek_inside_text_supports_trueai_reference_date.
	measure 'meas.peek_inside_text_supports_trueai_reference_date' = "TrueAI Reference Date"
		description: """
Purpose: Tracks peek inside text supports trueai reference date.
Logic: Derived from model references under current filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Boolean
		"""
		displayFolder: _helper
		lineageTag: 2bda97e6-525d-43bf-9132-5dac7a60b10b

	/// Measure meas.users_history_r2_bg_color.
	measure 'meas.users_history_r2_bg_color' = ```
			
			var pros_r2 = [meas.quality_bucket__prospecting_r2]
			var new_r2 = [meas.quality_bucket__new_logo_r2]
			var post_r2 = [meas.quality_bucket_post_sales_r2]
			var exist_r2 = [meas.quality_bucket_existing_customer_selling_r2]
			
			var step_name = CALCULATE(MAX(ssr_history[step_name]))
			
			var res = SWITCH(
			    TRUE(),
			    step_name = "Prospecting" || step_name = "Untouched" ,pros_r2,
			    step_name = "New Logo Selling", new_r2,
			    step_name = "Post-Sales Support", post_r2,
			    step_name = "Existing Customer Selling", exist_r2
			)
			
			
			var _conf = ROUND(res,2)*100    // get the rounded r2 score
			
			var _status_ = 
			    IF(
			    _conf >= 0 && _conf <= 49, 1,
			        IF(
			            _conf >=50 && _conf <= 74, 2,
			            IF(
			                _conf >=75 && _conf <= 84, 3,
			                IF(
			                    _conf >=85 && _conf <= 94, 4,
			                    5
			                )
			            )
			        )
			)
			
			
			
			RETURN 
			IF(
			    _conf <>0,
			    _status_
			)
			```
		description: """
Purpose: Tracks users history R2 bg color.
Logic: Returns an extreme value from ssr_history[step_name] under filters.
Dependencies: Measures: [meas.quality_bucket__new_logo_r2], [meas.quality_bucket__prospecting_r2], [meas.quality_bucket_existing_customer...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: b9a6f5fd-0e8e-4a17-99f6-68bb6955b805

	/// Measure meas.users_history_auc_bg_color.
	measure 'meas.users_history_auc_bg_color' = ```
			
			var pros_auc = [meas.quality_bucket_prospecting_auc]
			var new_auc = [meas.quality_bucket_new_logo_auc]
			var post_auc = [meas.quality_bucket_post_sales_auc]
			var exist_auc = [meas.quality_bucket_existing_customer_selling_auc]
			
			var step_name = CALCULATE(MAX(ssr_history[step_name]))
			
			var res = SWITCH(
			    TRUE(),
			    step_name = "Prospecting" || step_name = "Untouched" ,pros_auc,
			    step_name = "New Logo Selling", new_auc,
			    step_name = "Post-Sales Support", post_auc,
			    step_name = "Existing Customer Selling", exist_auc
			)
			
			
			var _conf = ROUND(res,2)*100    // get the rounded r2 score
			
			var _status_ = 
			    IF(
			    _conf >= 0 && _conf <= 49, 1,
			        IF(
			            _conf >=50 && _conf <= 74, 2,
			            IF(
			                _conf >=75 && _conf <= 84, 3,
			                IF(
			                    _conf >=85 && _conf <= 94, 4,
			                    5
			                )
			            )
			        )
			)
			
			
			
			RETURN 
			IF(
			    _conf <>0,
			    _status_
			)
			```
		description: """
Purpose: Tracks users history AUC bg color.
Logic: Returns an extreme value from ssr_history[step_name] under filters.
Dependencies: Measures: [meas.quality_bucket_existing_customer_selling_auc], [meas.quality_bucket_new_logo_auc], [meas.quality_bucket_pos...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: ebc1dec3-4c25-49a1-b757-cc84b583ae72

	/// Measure meas.users_history_avg_act_capt_lvl.
	measure 'meas.users_history_avg_act_capt_lvl' = ```
			
			 var _min_date = [meas.context_date_min]        // get the context min date
			 var _max_date = [meas.context_date_max]        // get the context max date 
			
			var rep_tbl = CALCULATETABLE(
			    users_history,
			    cal_end_dates[Date] >= _min_date && cal_end_dates[Date] <= _max_date
			)
			
			var res = CALCULATE(
			    AVERAGEX(
			        rep_tbl,
			        users_history[ci_act_capt_lvl]
			    )
			)
			
			RETURN
			res
			```
		description: """
Purpose: Tracks users history average act capt lvl.
Logic: Averages cal_end_dates[Date] under filters.
Dependencies: Measures: [meas.context_date_max], [meas.context_date_min]; Columns: cal_end_dates[Date], users_history[ci_act_capt_lvl]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _acl_ta_analysis
		lineageTag: 3b0377cc-1f96-47ec-95c0-2878eb5243bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.users_history_ci_time_alloca_avg_prospecting.
	measure 'meas.users_history_ci_time_alloca_avg_prospecting' =
			
			CALCULATE(
			    AVERAGE(
			        users_history[ci_time_alloc_prospecting]      // get the aVERAGE time for prospecting
			    )
			)
		description: """
Purpose: Tracks users history ci time alloca average prospecting.
Logic: Averages users_history[ci_time_alloc_prospecting] under filters.
Dependencies: Columns: users_history[ci_time_alloc_prospecting]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: 0.0
		displayFolder: _perf_analysis
		lineageTag: 363287f9-8e11-4afb-a36a-636b9f8eb0c9

	/// Measure meas.users_history_ci_time_alloca_avg_new_logo_selling.
	measure 'meas.users_history_ci_time_alloca_avg_new_logo_selling' =
			
			CALCULATE(
			    AVERAGE(
			        users_history[ci_time_alloc_new_logo]      // get the aVERAGE time for NEW LOGO SELLING
			    )
			)
		description: """
Purpose: Tracks users history ci time alloca average new logo selling.
Logic: Averages users_history[ci_time_alloc_new_logo] under filters.
Dependencies: Columns: users_history[ci_time_alloc_new_logo]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _perf_analysis
		lineageTag: 0f273889-0f09-4cf7-a177-586dde98d57d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.users_history_ci_time_alloca_avg_post_sales_support.
	measure 'meas.users_history_ci_time_alloca_avg_post_sales_support' =
			
			CALCULATE(
			    AVERAGE(
			        users_history[ci_time_alloc_post_sales]      // get the aVERAGE time for post sales support
			    )
			)
		description: """
Purpose: Tracks users history ci time alloca average post sales support.
Logic: Averages users_history[ci_time_alloc_post_sales] under filters.
Dependencies: Columns: users_history[ci_time_alloc_post_sales]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _perf_analysis
		lineageTag: a2e9401e-6bbc-412c-86ff-d210bab347b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.users_history_ci_time_alloca_avg_internel.
	measure 'meas.users_history_ci_time_alloca_avg_internel' =
			
			CALCULATE(
			    AVERAGE(
			        users_history[ci_time_alloc_internal]      // get the aVERAGE time for internel
			    )
			)
		description: """
Purpose: Tracks users history ci time alloca average internel.
Logic: Averages users_history[ci_time_alloc_internal] under filters.
Dependencies: Columns: users_history[ci_time_alloc_internal]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		displayFolder: _perf_analysis
		lineageTag: 076d5fc9-0c65-4ddc-8328-ad90a7ae1d0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure meas.reps_without_act_lvl_count.
	measure 'meas.reps_without_act_lvl_count' =
			
			var reps_tot = CALCULATE(DISTINCTCOUNT([_sys_user_id]), users_history[ci_act_capt_lvl]=BLANK())
			RETURN
			reps_tot
		description: """
Purpose: Tracks reps without act lvl count.
Logic: Counts distinct values in users_history[ci_act_capt_lvl] under filters.
Dependencies: Columns: users_history[ci_act_capt_lvl]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: 823b6167-9d31-4002-92a5-8ef055257123

	/// Measure meas.reps_without_act_lvl_pct.
	measure 'meas.reps_without_act_lvl_pct' =
			
			var reps_w_acl = [meas.reps_without_act_lvl_count]
			var reps_tot = CALCULATE(DISTINCTCOUNT([_sys_user_id]))
			var res = DIVIDE(reps_w_acl, reps_tot)
			RETURN
			res
		description: """
Purpose: Tracks reps without act lvl percentage.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.reps_without_act_lvl_count]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _acl_ta_analysis
		lineageTag: b4f7597e-76a9-497e-9c04-10bad1c384ba

	/// Measure meas.reps_has_ci_act_capt_lvl.
	measure 'meas.reps_has_ci_act_capt_lvl' =
			
			
			var res=IF(
			    MAX(users_history[ci_act_capt_lvl])=BLANK(),
			    0,
			    1
			)
			RETURN
			res
		description: """
Purpose: Tracks reps has ci act capt lvl.
Logic: Returns an extreme value from users_history[ci_act_capt_lvl] under filters.
Dependencies: Columns: users_history[ci_act_capt_lvl]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _acl_ta_analysis
		lineageTag: f7c7a23d-abf3-4d19-83f8-b9268e8cd6cb

	/// Measure meas.ci_act_capt_lvl_pi_owner_act.
	measure 'meas.ci_act_capt_lvl_pi_owner_act' =
			
			var _prospect_count = SUM(users_history[ci_act_capt_lvl_pi_prospecting_owner_act])
			var _new_logo_count = SUM(users_history[ci_act_capt_lvl_pi_new_logo_owner_act])
			var _post_sales_count = SUM(users_history[ci_act_capt_lvl_pi_post_sales_owner_act])
			var _exist_count = SUM(users_history[ci_act_capt_lvl_pi_exist_cust_owner_act])
			
			RETURN
			_prospect_count+_new_logo_count+_post_sales_count+_exist_count
		description: """
Purpose: Tracks ci act capt lvl PI owner act.
Logic: Counts rows using users_history[ci_act_capt_lvl_pi_prospecting_owner_act] under filters.
Dependencies: Columns: users_history[ci_act_capt_lvl_pi_prospecting_owner_act], users_history[ci_act_capt_lvl_pi_new_logo_owner_act], use...
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		lineageTag: a9dc1dca-80f1-4459-bf59-70b7dc8b07fe

	/// Measure meas.underperformer_annual_avg.
	measure 'meas.underperformer_annual_avg' =
			
			CALCULATE(
			    [meas.data_logs_ci_perf_annual_avg_bookings],   // get the under performer annual average
			    users_history[col.ci.perf_annual_performance_tier]="Underperformer"
			)
		description: """
Purpose: Tracks underperformer annual average.
Logic: Averages users_history[col.ci.perf_annual_performance_tier] under filters.
Dependencies: Measures: [meas.data_logs_ci_perf_annual_avg_bookings]; Columns: users_history[col.ci.perf_annual_performance_tier]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _rep_overview
		lineageTag: e36c1779-b7a1-4178-aba2-048b42a3657f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.performer_annual_avg.
	measure 'meas.performer_annual_avg' =
			
			CALCULATE(
			    [meas.data_logs_ci_perf_annual_avg_bookings],   // get the performer annual average
			    users_history[col.ci.perf_annual_performance_tier]="Performer"
			)
		description: """
Purpose: Tracks performer annual average.
Logic: Averages users_history[col.ci.perf_annual_performance_tier] under filters.
Dependencies: Measures: [meas.data_logs_ci_perf_annual_avg_bookings]; Columns: users_history[col.ci.perf_annual_performance_tier]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _rep_overview
		lineageTag: b65fd732-3ba1-4caf-8147-8e81f722dbd1

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.overperformer_annual_avg.
	measure 'meas.overperformer_annual_avg' =
			
			CALCULATE(
			    [meas.data_logs_ci_perf_annual_avg_bookings],   // get the over performer annual average
			    users_history[col.ci.perf_annual_performance_tier]="Overperformer"
			)
		description: """
Purpose: Tracks overperformer annual average.
Logic: Averages users_history[col.ci.perf_annual_performance_tier] under filters.
Dependencies: Measures: [meas.data_logs_ci_perf_annual_avg_bookings]; Columns: users_history[col.ci.perf_annual_performance_tier]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Decimal
		"""
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _rep_overview
		lineageTag: 7f890585-40c8-496c-8997-1a9984b5c8f5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Measure meas.min_user_role_alias.
	measure 'meas.min_user_role_alias' =
			
			MINX(
			    VALUES(users_history[trueai_user_role_alias]),
			    users_history[trueai_user_role_alias]
			)
		description: """
Purpose: Tracks min user role alias.
Logic: Returns an extreme value from users_history[trueai_user_role_alias] under filters.
Dependencies: Columns: users_history[trueai_user_role_alias]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Boolean
		"""
		lineageTag: 4ebf3e77-dde2-4068-b567-e41f84e4e937

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column 'col.ci.perf_qtly_bookings_user' = ```.
	column 'col.ci.perf_qtly_bookings_user' = ```
			
			
			var res = users_history[ci_perf_qtly_bookings_user]
			
			return res
			
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0763e5ef-bf43-4d05-a2bb-558d1816494e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":""}

	/// Column 'col.ci.perf_qtly_performance_tier' = ```.
	column 'col.ci.perf_qtly_performance_tier' = ```
			
			
			var res = users_history[ci_perf_qtly_performance_tier]
			
			return res
			
			```
		lineageTag: a81976e8-e3e2-489d-ae0f-82ddfbf5bd6b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.user.user_role_dept' = ```.
	column 'col.user.user_role_dept' = ```
			
			users_history[trueai_user_role_department]
			 --var res = users_history[trueai_user_role_department]
			--return If(res = "OTHER", "OTHER DEPTS", res)
			
			```
		lineageTag: 0faff3ac-c22e-4e95-8c7b-cbc06d0e486f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.user.user_role_function' = ```.
	column 'col.user.user_role_function' = ```
			
			 var res = users_history[trueai_user_role_function]
			return If(res = "OTHER", "OTHER ROLES", res)
			```
		lineageTag: 5ab4a6c0-26cf-44ae-be89-f894dee5273b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.ci.perf_ramping_status' = ```.
	column 'col.ci.perf_ramping_status' = ```
			
			
			var res = users_history[ci_perf_ramping_status]
			
			return res
			
			
			```
		lineageTag: 0d18b050-356e-4643-ac3e-ccad106b65e0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Column 'col.perf_date_first_reached' =.
	column 'col.perf_date_first_reached' =
			
			var perf_date = related(users[trueai_performance_lvl_reached_on])
			var res = if(isblank(perf_date), date(2100,01,01), perf_date)
			return res
		formatString: General Date
		lineageTag: faad2598-dc46-47af-8301-bee975cefdac
		summarizeBy: none

		variation Variation
			isDefault
			relationship: ab1c90c5-27da-4651-8ab2-7dd381292ddf
			defaultHierarchy: LocalDateTable_11197bed-ded4-4a7a-9aad-f88f5ce688a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Column 'col.ci.perf_qtly_pipeline_user' =.
	column 'col.ci.perf_qtly_pipeline_user' =
			
			
			var res = users_history[ci_perf_qtly_pipeline_user]
			
			return res
		formatString: _col_passthrough_to_new_api
		lineageTag: 167ea7b9-c61e-4e76-bdff-f25f44620aa2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column 'col.ci.perf_qtly_avg_pipeline_peers' = ```.
	column 'col.ci.perf_qtly_avg_pipeline_peers' = ```
			
			
			var res = users_history[ci_perf_qtly_avg_pipeline_peers]
			
			return res
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 60f45449-9d11-4290-8b73-b365fee0be92
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":""}

	/// The ID of the document in the remote system (such as Salesforce ID)
	column _sys_user_id
		dataType: string
		lineageTag: e2a62a55-5407-4e09-9f6d-dea84a660ff7
		summarizeBy: none
		sourceColumn: _sys_user_id

		annotation SummarizationSetBy = Automatic

	/// Average quarterly sum of the booking amounts of opportunities won by the user's peers in the period
	column ci_perf_qtly_avg_bookings_peers
		dataType: double
		lineageTag: d43b5694-6d16-4043-929b-38a8b6196a44
		summarizeBy: sum
		sourceColumn: ci_perf_qtly_avg_bookings_peers

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average quarterly sum of the booking amounts of opportunities created by the user's peers in the period
	column ci_perf_qtly_avg_pipeline_peers
		dataType: double
		lineageTag: 991fdb28-f0aa-48be-8a35-bda196ae993e
		summarizeBy: sum
		sourceColumn: ci_perf_qtly_avg_pipeline_peers

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Quarterly sum of the booking amounts of opportunities won by the user in the period
	column ci_perf_qtly_bookings_user
		dataType: double
		lineageTag: f1ce53e8-d098-44b8-b33e-73013b1b09e9
		summarizeBy: sum
		sourceColumn: ci_perf_qtly_bookings_user

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Quarterly sum of the booking amounts of opportunities created by the user in the period
	column ci_perf_qtly_pipeline_user
		dataType: double
		lineageTag: c2ef63cf-580b-4168-9a73-6a3c93728058
		summarizeBy: sum
		sourceColumn: ci_perf_qtly_pipeline_user

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's ramping status indicating whether the user's tenure is lower than 6 months
	column ci_perf_ramping_status
		dataType: string
		lineageTag: 41b034b9-3dc1-46a2-a478-c5c220bf32d9
		summarizeBy: none
		sourceColumn: ci_perf_ramping_status

		annotation SummarizationSetBy = Automatic

	/// The Cien company ID
	column _sys_co_id
		dataType: string
		lineageTag: da4b2557-1856-4ba0-81c3-058822903a05
		summarizeBy: none
		sourceColumn: _sys_co_id

		annotation SummarizationSetBy = Automatic

	/// Unique record identifier, based on the ID of the document in the remote system (such as Salesforce ID) and date
	column _sys_doc_id
		dataType: string
		lineageTag: 32589dc0-ac64-4e4e-b519-ef87934ea2f0
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// The last date of the month that the record applies to (for past months) or the last date of aggregated data (for the present month), stripped of time
	column _sys_filt_end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: c08cd854-4667-49f7-a57b-3df8f2b7be15
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The first date of the month that the records applies to, stripped of time
	column _sys_filt_start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 559873a4-ce65-41e4-91b6-b8550846a2d9
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 7c971af1-037c-4c02-847a-9596588dd35e
			defaultHierarchy: LocalDateTable_cd48709e-408c-49fa-ba94-c04ec6cce76e.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// User's act_capture_level score in the period
	column ci_act_capt_lvl
		dataType: double
		lineageTag: cedecab7-6c3f-48d3-9a76-031c73d3fb54
		summarizeBy: average
		sourceColumn: ci_act_capt_lvl

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's act_capture_level score confidence in the period
	column ci_act_capt_lvl_conf
		dataType: double
		lineageTag: 53283eb6-1379-4e75-9be7-51e8b28af86c
		summarizeBy: average
		sourceColumn: ci_act_capt_lvl_conf

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of owner activities performed on new logo selling steps that completed in the period
	column ci_act_capt_lvl_pi_new_logo_owner_act
		dataType: int64
		formatString: 0
		lineageTag: 33bdac73-809c-4813-8bd4-88af3eb65b08
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_new_logo_owner_act

		annotation SummarizationSetBy = Automatic

	/// Duration of activities performed on new logo selling steps that completed in the period
	column ci_act_capt_lvl_pi_new_logo_owner_dur
		dataType: double
		lineageTag: 5e8787fa-d5a8-4827-9362-51346f34a28d
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_new_logo_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of new logo selling steps that completed in the period
	column ci_act_capt_lvl_pi_new_logo_steps
		dataType: int64
		formatString: 0
		lineageTag: 010cf2aa-e7ef-4e26-aeaa-d8b14c7c7a98
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_new_logo_steps

		annotation SummarizationSetBy = Automatic

	/// Expected duration of activities performed on post-sales support steps that completed in the period
	column ci_act_capt_lvl_pi_post_sales_expect_owner_dur
		dataType: double
		lineageTag: 426bf139-3706-45c2-bd8f-8d8663801111
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_post_sales_expect_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of owner activities performed on post-sales support steps that completed in the period
	column ci_act_capt_lvl_pi_post_sales_owner_act
		dataType: int64
		formatString: 0
		lineageTag: def48617-cbe0-4079-afe8-b773e0d447ea
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_post_sales_owner_act

		annotation SummarizationSetBy = Automatic

	/// Duration of activities performed on post-sales support steps that completed in the period
	column ci_act_capt_lvl_pi_post_sales_owner_dur
		dataType: double
		lineageTag: 25070f5e-4b17-4bac-aca0-254d2d7caebe
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_post_sales_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of post-sales support steps that completed in the period
	column ci_act_capt_lvl_pi_post_sales_steps
		dataType: int64
		formatString: 0
		lineageTag: a4498441-f8b6-4808-989e-e3b873839411
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_post_sales_steps

		annotation SummarizationSetBy = Automatic

	/// Expected duration of activities performed on prospecting steps that completed in the period
	column ci_act_capt_lvl_pi_prospecting_expect_owner_dur
		dataType: double
		lineageTag: de6871f6-200c-4cc5-bb3d-16279fc08302
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_prospecting_expect_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of owner activities performed on prospecting steps that completed in the period
	column ci_act_capt_lvl_pi_prospecting_owner_act
		dataType: int64
		formatString: 0
		lineageTag: 156facd6-0d87-4cc6-9c85-b65d6a47248e
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_prospecting_owner_act

		annotation SummarizationSetBy = Automatic

	/// Duration of activities performed on prospecting steps that completed in the period
	column ci_act_capt_lvl_pi_prospecting_owner_dur
		dataType: double
		lineageTag: 8c70edb1-c66c-46a7-ad96-b65767cc326b
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_prospecting_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of prospecting steps that completed in the period
	column ci_act_capt_lvl_pi_prospecting_steps
		dataType: int64
		formatString: 0
		lineageTag: e2d28d37-bb46-43a7-8eda-ce8316cdfc4a
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_prospecting_steps

		annotation SummarizationSetBy = Automatic

	/// User's timeliness score in the period
	column ci_act_capt_lvl_pi_timeliness
		dataType: double
		lineageTag: 780906d6-2f18-405e-91c2-7184cfb2cfe8
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_timeliness

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// act_capture_level adjustment factor to account for the user's act_capture_level score
	column ci_time_alloc_act_capt_lvl_adjustment
		dataType: double
		lineageTag: 4c5900c1-713a-4bea-9722-8f3ac8fcfe89
		summarizeBy: sum
		sourceColumn: ci_time_alloc_act_capt_lvl_adjustment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's time allocation values confidence in the period
	column ci_time_alloc_conf
		dataType: double
		lineageTag: e1d5eb9b-09a3-41b6-8662-ed5b23c90bd1
		summarizeBy: sum
		sourceColumn: ci_time_alloc_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on internal activities in the period
	column ci_time_alloc_internal
		dataType: double
		lineageTag: 13300d16-fbf5-49f7-910c-5b31a16fdb0f
		summarizeBy: sum
		sourceColumn: ci_time_alloc_internal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged internal activities in the period
	column ci_time_alloc_internal_eng
		dataType: double
		lineageTag: 72b50157-c613-4cc3-b150-7dbb8fab9c12
		summarizeBy: sum
		sourceColumn: ci_time_alloc_internal_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Week adjustment factor to convert monthly to weekly
	column ci_time_alloc_month_to_week_adjustment
		dataType: double
		lineageTag: 7bd82971-b7f0-4ff1-aa47-b310b7e6496f
		summarizeBy: sum
		sourceColumn: ci_time_alloc_month_to_week_adjustment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on new logo selling activities in the period
	column ci_time_alloc_new_logo
		dataType: double
		lineageTag: e0ba2bcc-dca3-4bac-9621-775926260a0f
		summarizeBy: sum
		sourceColumn: ci_time_alloc_new_logo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged new logo selling activities in the period
	column ci_time_alloc_new_logo_eng
		dataType: double
		lineageTag: 0a57136a-61da-4153-97a6-b19ac5793f8c
		summarizeBy: sum
		sourceColumn: ci_time_alloc_new_logo_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on post-sales support activities in the period
	column ci_time_alloc_post_sales
		dataType: double
		lineageTag: 117284d7-5a41-4cc5-a2b8-001980d17c32
		summarizeBy: sum
		sourceColumn: ci_time_alloc_post_sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged post-sales support activities in the period
	column ci_time_alloc_post_sales_eng
		dataType: double
		lineageTag: cdea35cd-162a-4e86-bd14-69933ffb8aeb
		summarizeBy: sum
		sourceColumn: ci_time_alloc_post_sales_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Prep adjustment factor to account for the preparation time needed apart from sales related activities
	column ci_time_alloc_prep_adjustment
		dataType: double
		lineageTag: 49c90b85-68a6-4b44-88d1-2308b444e1e3
		summarizeBy: sum
		sourceColumn: ci_time_alloc_prep_adjustment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on prospecting activities in the period
	column ci_time_alloc_prospecting
		dataType: double
		lineageTag: 9237a3a2-908e-467c-811c-f5e9c9f23b6b
		summarizeBy: sum
		sourceColumn: ci_time_alloc_prospecting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged prospecting activities in the period
	column ci_time_alloc_prospecting_eng
		dataType: double
		lineageTag: f5bf03e8-8958-48a8-b728-6d8650788d04
		summarizeBy: sum
		sourceColumn: ci_time_alloc_prospecting_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on activities in the period
	column ci_time_alloc_tot
		dataType: double
		lineageTag: 43a23bf6-1c7f-4abb-b4a1-d1c6a2aa3252
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Duration of the activities the user performed in the period
	column ci_time_alloc_tot_dur
		dataType: double
		lineageTag: f9f2a426-29ce-42c3-855c-ce9f8ab42b3e
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged activities in the period
	column ci_time_alloc_tot_eng
		dataType: double
		lineageTag: 81e56d15-594b-4172-85ee-173338fc2986
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Duration of the engaged activities the user performed in the period
	column ci_time_alloc_tot_eng_dur
		dataType: double
		lineageTag: bca305da-8bd2-4192-8a25-7e0dc65d3fc0
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on sales related activities in the period
	column ci_time_alloc_tot_selling
		dataType: double
		lineageTag: 45f51f39-22ec-4b5d-8ffb-05b5edd17532
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_selling

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged sales related activities in the period
	column ci_time_alloc_tot_selling_eng
		dataType: double
		lineageTag: cdf91be9-72ba-4ca8-aba5-6b709e2f222d
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_selling_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's last login time in the CRM
	column crm_last_login_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 11fd96c0-6eb9-43ad-a5b4-5729bf91ed18
		summarizeBy: none
		sourceColumn: crm_last_login_time

		variation Variation
			isDefault
			relationship: 02977a3b-e3e5-4ead-b9a7-335f7b367669
			defaultHierarchy: LocalDateTable_2f329bcd-2cf6-45a7-8500-fb579ca53552.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// User's group
	column trueai_group
		dataType: string
		lineageTag: 36d8cda1-723e-4564-b957-bcc4935a74bf
		summarizeBy: none
		sourceColumn: trueai_group

		annotation SummarizationSetBy = Automatic

	/// User's hire date
	column trueai_hire_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 85b6ced2-ce0e-4e54-b540-492f776919c9
		summarizeBy: none
		sourceColumn: trueai_hire_date

		variation Variation
			isDefault
			relationship: f0f6ba6f-f544-428d-a22b-e760825a518e
			defaultHierarchy: LocalDateTable_8a505c72-a43a-4825-bf4c-b53ef795066f.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Number of months since the user's hire date
	column trueai_tenure
		dataType: int64
		lineageTag: 9a92bd5f-1f5e-4c79-9e26-3622af124e95
		summarizeBy: sum
		sourceColumn: trueai_tenure

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's termination date
	column trueai_termination_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0ecbd518-7f37-4517-9551-2661a4652706
		summarizeBy: none
		sourceColumn: trueai_termination_date

		variation Variation
			isDefault
			relationship: 05b444aa-a610-4263-969d-7ab0e8da289b
			defaultHierarchy: LocalDateTable_276c649e-63fb-4366-901d-2918420af627.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// User's standardized and combined role
	column trueai_user_role
		dataType: string
		lineageTag: 9733a575-c52c-474d-854f-96a859fe558c
		summarizeBy: none
		sourceColumn: trueai_user_role

		annotation SummarizationSetBy = Automatic

	/// User's function derived from the standardized and combined role
	column trueai_user_role_function
		dataType: string
		lineageTag: 0fe69c05-1a3a-4e40-a4ab-1f635f7dd27e
		summarizeBy: none
		sourceColumn: trueai_user_role_function

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// User's performance tier expressed as "underperformer", "overperformer" or "performer", based on their quarterly sum of booking amounts of won opportunities compared to their peers
	column ci_perf_qtly_performance_tier
		dataType: string
		lineageTag: 67717ba0-c518-4efa-b95e-1415ae4e33d5
		summarizeBy: none
		sourceColumn: ci_perf_qtly_performance_tier

		annotation SummarizationSetBy = Automatic

	/// Column 'col.ci_perf_qtly_performance_tier_num' = ```.
	column 'col.ci_perf_qtly_performance_tier_num' = ```
			SWITCH([ci_perf_qtly_performance_tier], "Overperformer", 3, "Performer", 2, "Underperformer", 1) 
			
			```
		formatString: 0
		lineageTag: 0eca5a9b-0a37-4c47-96f7-2475b5be8b1b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Column 'col.ci.perf_annual_performance_tier_num' = ```.
	column 'col.ci.perf_annual_performance_tier_num' = ```
			
			// do the filter first
			
			var curr_year = year(users_history[_sys_filt_end_date]) // get the current year
			var curr_user_id = users_history[_sys_user_id] // get the current user
			var filt = filter(all(users_history), users_history[_sys_user_id] = curr_user_id &&  Year(users_history[_sys_filt_end_date]) = curr_year && ISBLANK([ci_perf_qtly_performance_tier]) = FALSE() ) // look for all user histor records in the current year that are not blank
			     
			var tot_year_rows = countrows(filt) // count those records 
			var sum_perf_tier_num =SUMX(filt,  [ci_perf_qtly_performance_tier_num]) // sum up the numeric perf number of those records
			var avg_perf_tier_num = round(DIVIDE(sum_perf_tier_num, tot_year_rows),0) // divide by total number of records to get the avg. and round to the closest integer (1-3)
			var res = IF(ISBLANK([ci_perf_qtly_performance_tier]) = FALSE, avg_perf_tier_num, BLANK()) -- return the number for that year.
			
			return res 
			
			/*
			var last_full_year = (MAX(users_history[_sys.asof]) -800)
			var filt = filter(all(users_history), 
			    users_history[_sys.filter_end_date] > last_full_year
			    && quarter(users_history[_sys.filter_end_date]) = quarter(EARLIER(users_history[_sys.filter_end_date]))  // specific qtr
			    && (users_history[col.user.user_role_function]) = (earlier(users_history[col.user.user_role_function]))   
			    && ((users_history[col.user.user_role_function])) in {"AE", "AM", "SDR"}    
			    && ((users_history[di.trueai_opps_owned_count])) > 1 
			    && users_history[col.ci.perf_ramping_status] = "Ramped" // need to have ramped
			    &&  (users_history[_sys.filter_end_date]) < if(isblank((users_history[user.termination_date])),now(), (users_history[user.termination_date])) - 45// cannot have quit
			   
			) 
			
			
			var sum_qtly_bookings = SUMX(filt,  users_history[di.trueai_opps_won_amt])
			var items = COUNTX(filt,  users_history[_sys.user_id])
			var unique_items = COUNTROWS ( DISTINCT ( SELECTCOLUMNS ( filt, "_sys.user_id", [_sys.user_id]) ) )
			var avg_qtly_bookings = DIVIDE(sum_qtly_bookings,  items, blank()) * 3
			
			var smooth_factor = 10000
			var res = round(avg_qtly_bookings / smooth_factor,0) * smooth_factor
			
			return res
			*/
			```
		formatString: 0
		lineageTag: ac425e62-eb40-4f81-805b-d0ef2d1bb53a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Column 'col.ci.perf_annual_performance_tier' = ```.
	column 'col.ci.perf_annual_performance_tier' = ```
			
			SWITCH(users_history[col.ci.perf_annual_performance_tier_num], 3, "Overperformer", 2, "Performer", 1, "Underperformer")
			
			```
		lineageTag: d5e9005a-2033-4c0e-bd3f-268748330990
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// User's performance tier expressed as an integer from 1 to 3, based on their quarterly sum of booking amounts of won opportunities compared to their peers
	column ci_perf_qtly_performance_tier_num
		dataType: int64
		formatString: 0
		lineageTag: 5d68fed3-4995-4efa-9635-1b5401c0e7fd
		summarizeBy: sum
		sourceColumn: ci_perf_qtly_performance_tier_num

		annotation SummarizationSetBy = Automatic

	/// Column 'col.ci_ta_potential_hours' = ```.
	column 'col.ci_ta_potential_hours' = ```
			
			var hours_per_cal_day = (250 * 8)/365 // number of work days
			var as_of = [_sys_as_of] // current month's last day
			var end_day = If (If([trueai_termination_date] = blank() , date(2100,1,1), [trueai_termination_date]) < as_of, 0,  Day(as_of))
			var days_in_curr_month = end_day
			var res = days_in_curr_month * hours_per_cal_day
			return res
			
			
			```
		formatString: 0
		lineageTag: 6e118953-8789-48f9-9e62-2b96b163b27d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_closing_ability_actual_vs_predicted
		dataType: double
		lineageTag: d3ef3092-a25e-45d9-85a8-9be542824dba
		summarizeBy: sum
		sourceColumn: ci_sb_closing_ability_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_closing_ability_conf
		dataType: double
		lineageTag: b372a6fb-c8c0-4024-880c-c15d4df5fa0b
		summarizeBy: sum
		sourceColumn: ci_sb_closing_ability_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_closing_ability_peer_actual_vs_predicted
		dataType: double
		lineageTag: d229fdb3-1ee0-44dc-b34d-83df64575445
		summarizeBy: sum
		sourceColumn: ci_sb_closing_ability_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_discov_skills_actual_vs_predicted
		dataType: double
		lineageTag: 6546394c-2ae3-4626-9f47-8bf8b76975c9
		summarizeBy: sum
		sourceColumn: ci_sb_discov_skills_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_discov_skills_conf
		dataType: double
		lineageTag: ab2e41ff-9e53-46b3-bb6b-bdb1a60ac16f
		summarizeBy: sum
		sourceColumn: ci_sb_discov_skills_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_discov_skills_peer_actual_vs_predicted
		dataType: double
		formatString: 0
		lineageTag: 0aaad8ee-eef0-4607-af1c-44c0e466ce9e
		summarizeBy: sum
		sourceColumn: ci_sb_discov_skills_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_max
		dataType: double
		lineageTag: f6a89d98-299d-4790-a4ca-69fe3f4fc312
		summarizeBy: sum
		sourceColumn: ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_min
		dataType: double
		lineageTag: 7ec7a725-3a35-4692-9c32-1d14e42063e2
		summarizeBy: sum
		sourceColumn: ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_deal_maxing_conf
		dataType: double
		lineageTag: 2a28d51c-1917-4f8d-a5b1-b69d5b7fab81
		summarizeBy: sum
		sourceColumn: ci_sb_deal_maxing_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Deal maximizing final score as compared to peers.
	column ci_sb_deal_maxing_num
		dataType: double
		lineageTag: 03b48771-de12-4fbf-938a-c71feeead6d2
		summarizeBy: sum
		sourceColumn: ci_sb_deal_maxing_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_engmt_ability_conf
		dataType: double
		lineageTag: 150917d1-51fe-44b0-8041-070e6d0d4bed
		summarizeBy: sum
		sourceColumn: ci_sb_engmt_ability_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Engagement ability final score as compared to peers.
	column ci_sb_engmt_ability_num
		dataType: double
		lineageTag: 9c50b699-18ee-48cb-9f82-f6d3a7df6dff
		summarizeBy: sum
		sourceColumn: ci_sb_engmt_ability_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_work_effort_conf
		dataType: double
		lineageTag: 5f93bf7b-cb1c-44a2-a26e-193d8e55511f
		summarizeBy: sum
		sourceColumn: ci_sb_work_effort_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Work effort final score as compared to peers.
	column ci_sb_work_effort_num
		dataType: double
		lineageTag: f2aeccda-bde2-4b01-bc68-221712c00268
		summarizeBy: sum
		sourceColumn: ci_sb_work_effort_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The date of the last data request from the platform in UTC
	column trueai_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6401d21-4f61-4dd5-a51e-8bcb826d8b41
		summarizeBy: none
		sourceColumn: trueai_end_date

		variation Variation
			isDefault
			relationship: 04126cee-830f-4da6-ab4f-4bd9e45f0291
			defaultHierarchy: LocalDateTable_b1a61984-c291-4452-9b8d-623ed46574db.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The last date of the month that the record applies to (for past months) or the last date of aggregated data (for the present month)
	column _sys_as_of
		dataType: dateTime
		formatString: Long Date
		lineageTag: f45bccb0-1f4e-48bd-a57e-940c08330b14
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 0d14204a-4606-4288-b570-3121835486c0
			defaultHierarchy: LocalDateTable_c08185c8-0b2f-4aa3-af8c-1d311d5c2a3a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the record was set to inactive in the remote system
	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 41958ca8-ca01-4e94-b6e8-949ab3aeac67
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the record was set to deleted in the remote system
	column _sys_is_deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 396c6de1-9f1f-4043-93c4-eb38e29c3db8
		summarizeBy: none
		sourceColumn: _sys_is_deleted

		annotation SummarizationSetBy = Automatic

	/// Expected duration of activities performed on new logo selling steps that completed in the period
	column ci_act_capt_lvl_pi_new_logo_expected_owner_dur
		dataType: double
		lineageTag: 6e1ed90d-afba-47ed-91da-18baf1c4efa5
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_new_logo_expected_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's creation date in the CRM
	column crm_created_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1fb809ed-0a11-415d-b368-51a2eb306268
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: bf3fecbb-efa0-48bf-90ad-7c24ccaf28f0
			defaultHierarchy: LocalDateTable_ea825cf1-037c-4fb3-9123-34d41aa47a06.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Expected duration of activities performed on existing customer selling steps that completed in the period
	column ci_act_capt_lvl_pi_exist_cust_expect_owner_dur
		dataType: double
		lineageTag: e2a20ea6-6e91-417f-ac91-c9f551bf6a48
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_exist_cust_expect_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of owner activities performed on existing customer selling steps that completed in the period
	column ci_act_capt_lvl_pi_exist_cust_owner_act
		dataType: int64
		formatString: 0
		lineageTag: fb01fafb-b9ae-46de-a0a4-575a4e513b7d
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_exist_cust_owner_act

		annotation SummarizationSetBy = Automatic

	/// Duration of activities performed on existing customer selling steps that completed in the period
	column ci_act_capt_lvl_pi_exist_cust_owner_dur
		dataType: double
		lineageTag: f166d551-cff6-4f73-a3f5-b860f06330c7
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_exist_cust_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of existing customer selling steps that completed in the period
	column ci_act_capt_lvl_pi_exist_cust_steps
		dataType: int64
		formatString: 0
		lineageTag: a94bb3c7-4bc6-4824-b686-048442588635
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_exist_cust_steps

		annotation SummarizationSetBy = Automatic

	/// Average number of weekly hours the user spent on existing customer selling activities in the period
	column ci_time_alloc_existing_customer_selling
		dataType: double
		lineageTag: 48e869c0-9a0e-4e68-917f-d963b95acb5b
		summarizeBy: sum
		sourceColumn: ci_time_alloc_existing_customer_selling

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged existing customer selling activities in the period
	column ci_time_alloc_existing_customer_selling_eng
		dataType: double
		lineageTag: 5f99395c-b1a3-417d-af49-9947f5066ab7
		summarizeBy: sum
		sourceColumn: ci_time_alloc_existing_customer_selling_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's standardized and combined role aliased
	column trueai_user_role_alias
		dataType: string
		lineageTag: 24baa1ad-7363-439d-9b42-3640c9e478ef
		summarizeBy: none
		sourceColumn: trueai_user_role_alias

		annotation SummarizationSetBy = Automatic

	/// User's performance tier confidence
	column ci_perf_qtly_performance_tier_conf
		dataType: double
		lineageTag: c26128f8-4661-4233-99a2-4cbe2b78fde9
		summarizeBy: sum
		sourceColumn: ci_perf_qtly_performance_tier_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of peers the user was compared to when determining the performance tier
	column ci_perf_qtly_performance_peer_count
		dataType: int64
		formatString: 0
		lineageTag: e26b5072-67ed-4c8a-b5f3-d17cf3d8b738
		summarizeBy: sum
		sourceColumn: ci_perf_qtly_performance_peer_count

		annotation SummarizationSetBy = Automatic

	/// Potential number of hours a user can put in during a given month
	column ci_time_alloc_potential
		dataType: double
		lineageTag: 97a8326a-5c34-41bd-bfc7-363ac8e3dff5
		summarizeBy: sum
		sourceColumn: ci_time_alloc_potential

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Closing ability final score tier as compared to peers.
	column ci_sb_closing_ability_tier
		dataType: string
		lineageTag: cee04b62-8105-4b27-8b01-e805cf3e3fdd
		summarizeBy: none
		sourceColumn: ci_sb_closing_ability_tier

		annotation SummarizationSetBy = Automatic

	/// Closing ability final score as compared to peers.
	column ci_sb_closing_ability_num
		dataType: double
		lineageTag: 8ae645ff-5945-469a-9798-be6e8bbdf546
		summarizeBy: sum
		sourceColumn: ci_sb_closing_ability_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Deal maximizing final score tier as compared to peers.
	column ci_sb_deal_maxing_tier
		dataType: string
		lineageTag: b467483f-bdc3-4217-8bcb-a4c8e547863b
		summarizeBy: none
		sourceColumn: ci_sb_deal_maxing_tier

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_deal_maxing_actual_vs_predicted
		dataType: double
		lineageTag: 74373ae0-48ca-46f6-ae43-68a4bf90aec7
		summarizeBy: sum
		sourceColumn: ci_sb_deal_maxing_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_max
		dataType: double
		lineageTag: 5462b376-1e86-4285-bb68-ce9957d62dbe
		summarizeBy: sum
		sourceColumn: ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_min
		dataType: double
		lineageTag: 33826acf-38c2-4950-bca8-937ee9d7566b
		summarizeBy: sum
		sourceColumn: ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_deal_maxing_peer_actual_vs_predicted
		dataType: double
		lineageTag: 5d25bd97-a20d-4630-9111-bcdcf42597dd
		summarizeBy: sum
		sourceColumn: ci_sb_deal_maxing_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Discovery skills final score tier as compared to peers.
	column ci_sb_discov_skills_tier
		dataType: string
		lineageTag: 2fe6858b-f030-4a36-846d-0a0ee15d08d5
		summarizeBy: none
		sourceColumn: ci_sb_discov_skills_tier

		annotation SummarizationSetBy = Automatic

	/// Discovery skills final score as compared to peers.
	column ci_sb_discov_skills_num
		dataType: double
		lineageTag: b37f90e8-7268-4131-9eb2-b981435c9c40
		summarizeBy: sum
		sourceColumn: ci_sb_discov_skills_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_max
		dataType: double
		lineageTag: df281477-a8bc-4cd3-b54f-7288047d5bd0
		summarizeBy: sum
		sourceColumn: ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_min
		dataType: double
		lineageTag: a31d2ce7-f839-4de6-bbea-1013dfdeaf3d
		summarizeBy: sum
		sourceColumn: ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Engagement ability final score tier as compared to peers.
	column ci_sb_engmt_ability_tier
		dataType: string
		lineageTag: 13adc711-1164-4f63-b48b-f63dc6098cb1
		summarizeBy: none
		sourceColumn: ci_sb_engmt_ability_tier

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_engmt_ability_actual_vs_predicted
		dataType: double
		lineageTag: d10358fa-989f-467a-90b9-1fc7899926ea
		summarizeBy: sum
		sourceColumn: ci_sb_engmt_ability_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_max
		dataType: double
		lineageTag: bb9a5432-5a98-41ff-a3ed-930f05514a6a
		summarizeBy: sum
		sourceColumn: ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_min
		dataType: double
		lineageTag: 2bbb99ab-5891-4ddb-8364-7a2549ae34f6
		summarizeBy: sum
		sourceColumn: ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_engmt_ability_peer_actual_vs_predicted
		dataType: double
		lineageTag: 548d1855-29a8-49f4-9bfa-ba7598591fc3
		summarizeBy: sum
		sourceColumn: ci_sb_engmt_ability_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Work effort final score tier as compared to peers.
	column ci_sb_work_effort_tier
		dataType: string
		lineageTag: ac6f1e6f-7215-4b94-9d98-4551b8c0bb8c
		summarizeBy: none
		sourceColumn: ci_sb_work_effort_tier

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_work_effort_actual_vs_predicted
		dataType: double
		lineageTag: 73991f4d-aa28-4d57-8b41-24bd3ef12050
		summarizeBy: sum
		sourceColumn: ci_sb_work_effort_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_max
		dataType: double
		lineageTag: bacb95de-ff97-4f29-886f-43dafa9f0ebe
		summarizeBy: sum
		sourceColumn: ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_min
		dataType: double
		lineageTag: 0aefc028-978f-441c-ba3a-687aba96cb1d
		summarizeBy: sum
		sourceColumn: ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_work_effort_peer_actual_vs_predicted
		dataType: double
		lineageTag: d644117c-15c6-4f7b-af75-3c04f9f12af8
		summarizeBy: sum
		sourceColumn: ci_sb_work_effort_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Time management final score tier as compared to peers.
	column ci_sb_time_management_tier
		dataType: string
		lineageTag: 97ad7927-fbcc-43bf-ad93-2b080d4f83ad
		summarizeBy: none
		sourceColumn: ci_sb_time_management_tier

		annotation SummarizationSetBy = Automatic

	/// Time management final score as compared to peers.
	column ci_sb_time_management_num
		dataType: double
		lineageTag: 32d3abed-6f31-4a22-85cb-5d0c492ea5e8
		summarizeBy: sum
		sourceColumn: ci_sb_time_management_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_time_management_conf
		dataType: double
		lineageTag: 5430dfbe-8683-4c0a-86e6-74967889d5bc
		summarizeBy: sum
		sourceColumn: ci_sb_time_management_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_time_management_actual_vs_predicted
		dataType: double
		lineageTag: 88172038-9977-4b8d-ac78-47d7bf8c587d
		summarizeBy: sum
		sourceColumn: ci_sb_time_management_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_time_management_peer_actual_vs_pred_ratio_derived_max
		dataType: double
		lineageTag: 4fa7abae-c2f8-468a-b95a-49785f21bfaf
		summarizeBy: sum
		sourceColumn: ci_sb_time_management_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_time_management_peer_actual_vs_pred_ratio_derived_min
		dataType: double
		lineageTag: d467e8d8-3eeb-4bea-9646-4fd1f878cc70
		summarizeBy: sum
		sourceColumn: ci_sb_time_management_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_time_management_peer_actual_vs_predicted
		dataType: double
		lineageTag: c75eed9b-4045-4c70-9307-dd0a0cbe1d7c
		summarizeBy: sum
		sourceColumn: ci_sb_time_management_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's department derived from the standardized and combined role
	column trueai_user_role_department
		dataType: string
		lineageTag: d7442e13-deda-4aa8-8fd6-ae6efe9166dd
		summarizeBy: none
		sourceColumn: trueai_user_role_department

		annotation SummarizationSetBy = Automatic

	partition users_history-64a55d24-c03e-4c6b-af52-03f70e2fc93d = m
		mode: import
		source =
				let
				  dbTable = getDBTable("users_history"), // get the right table
				
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				 {"_sys_as_of", type datetime},
				    {"_sys_co_id", type text},
				    {"_sys_doc_id", type text},
				    {"_sys_filt_end_date", type date},
				    {"_sys_filt_start_date", type date},
				    {"_sys_is_active", type logical},
				    {"_sys_is_deleted", type logical},
				    {"_sys_user_id", type text},
				    {"ci_act_capt_lvl", type number},
				    {"ci_act_capt_lvl_conf", type number},
				    {"ci_act_capt_lvl_pi_exist_cust_expect_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_exist_cust_owner_act", Int64.Type},
				    {"ci_act_capt_lvl_pi_exist_cust_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_exist_cust_steps", Int64.Type},
				    {"ci_act_capt_lvl_pi_new_logo_expected_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_new_logo_owner_act", Int64.Type},
				    {"ci_act_capt_lvl_pi_new_logo_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_new_logo_steps", Int64.Type},
				    {"ci_act_capt_lvl_pi_post_sales_expect_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_post_sales_owner_act", Int64.Type},
				    {"ci_act_capt_lvl_pi_post_sales_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_post_sales_steps", Int64.Type},
				    {"ci_act_capt_lvl_pi_prospecting_expect_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_prospecting_owner_act", Int64.Type},
				    {"ci_act_capt_lvl_pi_prospecting_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_prospecting_steps", Int64.Type},
				    {"ci_act_capt_lvl_pi_timeliness", type number},
				    {"ci_perf_qtly_avg_bookings_peers", type number},
				    {"ci_perf_qtly_avg_pipeline_peers", type number},
				    {"ci_perf_qtly_bookings_user", type number},
				    {"ci_perf_qtly_performance_peer_count", Int64.Type},
				    {"ci_perf_qtly_performance_tier", type text},
				    {"ci_perf_qtly_performance_tier_conf", type number},
				    {"ci_perf_qtly_performance_tier_num", Int64.Type},
				    {"ci_perf_qtly_pipeline_user", type number},
				    {"ci_perf_ramping_status", type text},
				    {"ci_sb_closing_ability_actual_vs_predicted", type number},
				    {"ci_sb_closing_ability_conf", type number},
				    {"ci_sb_closing_ability_num", type number},
				    {"ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_max", type number},
				    {"ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_min", type number},
				    {"ci_sb_closing_ability_peer_actual_vs_predicted", type number},
				    {"ci_sb_closing_ability_tier", type text},
				    {"ci_sb_deal_maxing_actual_vs_predicted", type number},
				    {"ci_sb_deal_maxing_conf", type number},
				    {"ci_sb_deal_maxing_num", type number},
				    {"ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_max", type number},
				    {"ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_min", type number},
				    {"ci_sb_deal_maxing_peer_actual_vs_predicted", type number},
				    {"ci_sb_deal_maxing_tier", type text},
				    {"ci_sb_discov_skills_actual_vs_predicted", type number},
				    {"ci_sb_discov_skills_conf", type number},
				    {"ci_sb_discov_skills_num", type number},
				    {"ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_max", type number},
				    {"ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_min", type number},
				    {"ci_sb_discov_skills_peer_actual_vs_predicted", type number},
				    {"ci_sb_discov_skills_tier", type text},
				    {"ci_sb_engmt_ability_actual_vs_predicted", type number},
				    {"ci_sb_engmt_ability_conf", type number},
				    {"ci_sb_engmt_ability_num", type number},
				    {"ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_max", type number},
				    {"ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_min", type number},
				    {"ci_sb_engmt_ability_peer_actual_vs_predicted", type number},
				    {"ci_sb_engmt_ability_tier", type text},
				    {"ci_sb_time_management_actual_vs_predicted", type number},
				    {"ci_sb_time_management_conf", type number},
				    {"ci_sb_time_management_num", type number},
				    {"ci_sb_time_management_peer_actual_vs_pred_ratio_derived_max", type number},
				    {"ci_sb_time_management_peer_actual_vs_pred_ratio_derived_min", type number},
				    {"ci_sb_time_management_peer_actual_vs_predicted", type number},
				    {"ci_sb_time_management_tier", type text},
				    {"ci_sb_work_effort_actual_vs_predicted", type number},
				    {"ci_sb_work_effort_conf", type number},
				    {"ci_sb_work_effort_num", type number},
				    {"ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_max", type number},
				    {"ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_min", type number},
				    {"ci_sb_work_effort_peer_actual_vs_predicted", type number},
				    {"ci_sb_work_effort_tier", type text},
				    {"ci_time_alloc_act_capt_lvl_adjustment", type number},
				    {"ci_time_alloc_conf", type number},
				    {"ci_time_alloc_existing_customer_selling", type number},
				    {"ci_time_alloc_existing_customer_selling_eng", type number},
				    {"ci_time_alloc_internal", type number},
				    {"ci_time_alloc_internal_eng", type number},
				    {"ci_time_alloc_month_to_week_adjustment", type number},
				    {"ci_time_alloc_new_logo", type number},
				    {"ci_time_alloc_new_logo_eng", type number},
				    {"ci_time_alloc_post_sales", type number},
				    {"ci_time_alloc_post_sales_eng", type number},
				    {"ci_time_alloc_potential", type number},
				    {"ci_time_alloc_prep_adjustment", type number},
				    {"ci_time_alloc_prospecting", type number},
				    {"ci_time_alloc_prospecting_eng", type number},
				    {"ci_time_alloc_tot", type number},
				    {"ci_time_alloc_tot_dur", type number},
				    {"ci_time_alloc_tot_eng", type number},
				    {"ci_time_alloc_tot_eng_dur", type number},
				    {"ci_time_alloc_tot_selling", type number},
				    {"ci_time_alloc_tot_selling_eng", type number},
				    {"crm_created_on", type datetime},
				    {"crm_last_login_time", type datetime},
				    {"trueai_end_date", type date},
				    {"trueai_group", type text},
				    {"trueai_hire_date", type datetime},
				    {"trueai_tenure", Int64.Type},
				    {"trueai_termination_date", type datetime},
				    {"trueai_user_role", type text},
				    {"trueai_user_role_alias", type text},
				    {"trueai_user_role_department", type text},
				    {"trueai_user_role_function", type text}
				
				
				
				  })
				in
				    dbTableTyped

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

