/// Table users_managers.
table users_managers
	description: "One row per users_manager record. Source fields include System, TrueAI prefixes."
	lineageTag: bb069c2a-cf9c-429e-b3ce-b37fd7d995cb

	/// Column _sys_doc_id.
	column _sys_doc_id
		description: "System: Identifier for doc."
		dataType: string
		lineageTag: 93500f8e-d411-4e86-a89a-5a32ceae1fe8
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Column trueai_mgr_ids.
	column trueai_mgr_ids
		description: "TrueAI: Text label for mgr ids."
		dataType: string
		lineageTag: 956f13fd-f0df-460e-ab4b-d05a22358af9
		summarizeBy: none
		sourceColumn: trueai_mgr_ids

		annotation SummarizationSetBy = Automatic

	partition users_managers-29394942-5460-4495-b703-53703bc70474 = m
		mode: import
		source =
				let
				
				  dbTable = getDBTable("users"), // get the right table
				
				
				  dbTableFiltered = Table.SelectRows(dbTable, each [trueai_mgr_ids] <> null),
				  dbTableRemoved  = Table.SelectColumns(dbTableFiltered ,{"_sys_doc_id", "trueai_mgr_ids"}),
				  dbTableRemovedReplaced  = Table.ReplaceValue(dbTableRemoved ,"'","""",Replacer.ReplaceText,{"trueai_mgr_ids"}),
				  dbTableRemovedReplacedJSON = Table.TransformColumns(dbTableRemovedReplaced,{{"trueai_mgr_ids", Json.Document}}),
				  dbTableRemovedReplacedJSONExpanded = Table.ExpandListColumn(dbTableRemovedReplacedJSON, "trueai_mgr_ids"),
				  dbTableRemovedReplacedJSONExpandedRenamed = Table.RenameColumns(dbTableRemovedReplacedJSONExpanded,{{"trueai_mgr_ids", "trueai_mgr_id"}})
				in
				    dbTableRemovedReplacedJSONExpanded

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

