table users
	lineageTag: a820f8fc-c2ef-41f8-bc42-b46f25fc4f43

	measure 'meas.users_user_roles_concat' = ```
			
			-- concats all the crm values for trueai value
			
			-- summarize the currect context and sort by count desc
			var tbl_summarized = TOPN(10,SUMMARIZE(CALCULATETABLE(users), users[trueai_user_role], "count", Count(users[_sys_doc_id]) ),[count], DESC)
			
			-- use the summarized data and concat
			var str_crm_vals = CONCATENATEX(tbl_summarized,  [trueai_user_role], ", ") 
			
			var res = str_crm_vals -- output string
			return res
			```
		displayFolder: user_role_concats
		lineageTag: 2e4a5f18-741d-4c16-9371-62736ec5de95

	measure 'meas.users_user_roles_concat_w_count' = ```
			
			-- concats all the crm values for trueai value
			
			-- summarize the currect context and sort by count desc
			var tbl_summarized = TOPN(10,SUMMARIZE(CALCULATETABLE(users), users[trueai_user_role_alias], "count", Count(users[_sys_doc_id]) ),[count], DESC)
			
			-- use the summarized data and concat
			var str_crm_vals = CONCATENATEX(tbl_summarized,  users[trueai_user_role_alias] & " (" & [count]  & ")", ", ") 
			
			var res = str_crm_vals -- output string
			return res
			```
		displayFolder: user_role_concats
		lineageTag: 90265a0f-91d1-49cd-876f-f521314ce19b

	measure 'meas.users_user_roles_concat_w_count_eop' = ```
			
			-- concats all the crm values for trueai value for eop
			
			var applicable_rows_tbl = CALCULATETABLE(users_history, LASTNONBLANK(users_history[_sys_filt_start_date],users_history[_sys_filt_start_date]))  // get only the last entry in each filter context period (e.g. a year)
			-- summarize the currect context and sort by count desc
			
			var tbl_summarized = TOPN(10,SUMMARIZE(CALCULATETABLE(users), users[trueai_user_role_alias], "count", Count(users[_sys_doc_id]) ),[count], DESC)
			
			-- use the summarized data and concat
			var str_crm_vals = CONCATENATEX(tbl_summarized,  users[trueai_user_role_alias] & " (" & [count]  & ")", ", ") 
			
			var res = str_crm_vals -- output string
			return res
			```
		displayFolder: user_role_concats
		lineageTag: e77c169f-e8d6-48e8-ab2e-87441d66a83b

	measure 'meas.users_user_roles_function_concat_w_count' = ```
			
			-- concats all the crm values for trueai value
			
			-- summarize the currect context and sort by count desc
			var tbl_summarized = TOPN(10,SUMMARIZE(CALCULATETABLE(users), users[trueai_user_role_function], users[trueai_user_role_alias], "count", Count(users[_sys_doc_id]) ),[count], DESC)
			
			-- use the summarized data and concat
			var str_crm_vals = CONCATENATEX(tbl_summarized, users[trueai_user_role_function] & ": " & users[trueai_user_role_alias] & " (" & [count]  & ")", ", ") 
			
			var res = str_crm_vals -- output string
			return res
			```
		displayFolder: user_role_concats
		lineageTag: cf2e5ac8-6558-41ec-8060-fff13bff2cbd

	measure 'meas.users_rep_stats_bookings' = CALCULATE(SUM(ssr_history[opp_won_amt]), ssr_history[step_name] in {"New Logo Selling" , "Existing Customer Selling"})
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: rep_stats
		lineageTag: 98abfde2-24b2-45d4-bff2-09d94f91f1aa

	measure 'meas.users_rep_stats_bookings 1' =
			var start_date = date(2020,1,1)
			var end_date = date(2021,1,1)
			var res = CALCULATE([meas.users_rep_stats_bookings], ssr_history[_sys_filt_end_date] >= start_date &&  ssr_history[_sys_filt_end_date] < end_date )
			return res
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: rep_stats
		lineageTag: 8359b751-d9bd-4138-80cc-d97135f2e6c8

	measure 'meas.users_table_row_count' =
			
			COUNTROWS(Users)
		formatString: 0
		lineageTag: 59d6070a-cbdb-4359-9c06-41be235e091e

	measure 'meas.users_is_active' =
			
			// var curr_date = CALCULATE(MAX(cal_end_dates[Date]))  // get  the current maximum date
			// var user_end_date = CALCULATE(MAX(users[_sys_filt_end_date]))  // get the user end date
			// var res = IF(MAX(users[_sys_filt_end_date]) < curr_date, "True", "False")
			
			var res = IF(
			    ISBLANK(MAX(users[trueai_termination_date])),
			    1,
			    0
			)
			
			RETURN res
		formatString: 0
		lineageTag: 1431c953-2044-4fbb-97c2-b353ce241402

	measure 'meas.user_overview_title' = "Active Users Overview"
		displayFolder: _active_user_overview
		lineageTag: db75255d-25c7-45bb-8d82-f23f4ca2fedc

	measure 'meas.users_overview_win_rate_mtd' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_mtd &&  cal_end_dates[Date] <= end_date)
			
			-- apply addl. filters by sales steps
			var success_filt_tbl = Filter(dates_tbl,  ssr_history[step_success] = true && ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} ) // filter table for success steps
			
			var total_filt_tbl = Filter(dates_tbl,  ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} )  // filter the table for total steps
			
			var total_steps = CALCULATE( 
			    COUNTX(
			        total_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var success_steps  = CALCULATE(
			    COUNTX(
			        success_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			var res = DIVIDE(success_steps, total_steps, BLANK())
			return res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 310a8955-0807-4928-a59d-3c8abc9da526

	measure 'meas.users_overview_win_rate_qtd' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_qtd &&  cal_end_dates[Date] <= end_date)
			
			-- apply addl. filters by sales ssteps
			var success_filt_tbl = Filter(dates_tbl,  ssr_history[step_success] = true && ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} ) // filter table for success steps
			
			var total_filt_tbl = Filter(dates_tbl,  ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} )  // filter the table for total steps
			
			var total_steps = CALCULATE( 
			    COUNTX(
			        total_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var success_steps  = CALCULATE(
			    COUNTX(
			        success_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var res = DIVIDE(success_steps, total_steps, BLANK())
			RETURN res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: ebc4d37a-ed87-42fa-ae20-94ae49a81b47

	measure 'meas.users_overview_win_rate_ytd' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_ytd &&  cal_end_dates[Date] <= end_date)
			
			-- apply addl. filters by sales steps
			var success_filt_tbl = Filter(dates_tbl,  ssr_history[step_success] = true && ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} ) // filter table for success steps
			
			var total_filt_tbl = Filter(dates_tbl,  ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} )  // filter the table for total steps
			
			var total_steps = CALCULATE( 
			    COUNTX(
			        total_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var success_steps  = CALCULATE(
			    COUNTX(
			        success_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var res = DIVIDE(success_steps, total_steps, BLANK())
			RETURN res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 0fed3d7e-4822-429b-80b1-b6d73792eabe

	measure 'meas.users_overview_win_rate_mtd_sply' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_mtd_sply &&  cal_end_dates[Date] <= end_date_sply)
			
			-- apply addl. filters by sales steps
			var success_filt_tbl = Filter(dates_tbl,  ssr_history[step_success] = true && ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} ) // filter table for success steps
			
			var total_filt_tbl = Filter(dates_tbl,  ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} )  // filter the table for total steps
			
			var total_steps = CALCULATE( 
			    COUNTX(
			        total_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var success_steps  = CALCULATE(
			    COUNTX(
			        success_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var res = DIVIDE(success_steps, total_steps, BLANK())
			return res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: eb3379cf-b461-48f9-9595-960b3626535f

	measure 'meas.users_overview_win_rate_mtd_sply_diff' = ```
			
			var res = DIVIDE([meas.users_overview_win_rate_mtd] - [meas.users_overview_win_rate_mtd_sply], [meas.users_overview_win_rate_mtd])
			        // get the delta
			RETURN 
			IF(
			    res = BLANK(),
			    "-",
			    res
			)
			```
		formatString: +0%;-0%;"-"
		displayFolder: _active_user_overview
		lineageTag: 5a68121d-2018-4772-a757-0b8cd65ef3ed

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.users_overview_win_rate_qtd_sply' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_qtd_sply &&  cal_end_dates[Date] <= end_date_sply)
			
			-- apply addl. filters by sales steps
			var success_filt_tbl = Filter(dates_tbl,  ssr_history[step_success] = true && ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} ) // filter table for success steps
			
			var total_filt_tbl = Filter(dates_tbl,  ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} )  // filter the table for total steps
			
			var total_steps = CALCULATE( 
			    COUNTX(
			        total_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var success_steps  = CALCULATE(
			    COUNTX(
			        success_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var res = DIVIDE(success_steps, total_steps, BLANK())
			RETURN res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 3f8bd10b-3cc4-4760-a4b5-8e732adaee1d

	measure 'meas.users_overview_win_rate_qtd_sply_diff' =
			
			var res = DIVIDE([meas.users_overview_win_rate_qtd] - [meas.users_overview_win_rate_qtd_sply], [meas.users_overview_win_rate_qtd])
			// get the delta
			
			RETURN
			IF(
			    res = BLANK(),
			    "-",
			    res
			)
		formatString: +0%;-0%;"-"
		displayFolder: _active_user_overview
		lineageTag: 59a218f5-8977-4c38-9050-4c17c812131e

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.users_overview_win_rate_ytd_sply' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_ytd_sply &&  cal_end_dates[Date] <= end_date_sply)
			
			-- apply addl. filters by sales steps
			var success_filt_tbl = Filter(dates_tbl,  ssr_history[step_success] = true && ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} ) // filter table for success steps
			
			var total_filt_tbl = Filter(dates_tbl,  ssr_history[step_name] in{"Existing Customer Selling", "New Logo Selling"} )  // filter the table for total steps
			
			var total_steps = CALCULATE( 
			    COUNTX(
			        total_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var success_steps  = CALCULATE(
			    COUNTX(
			        success_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var res = DIVIDE(success_steps, total_steps, BLANK())
			RETURN res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 07e8a5e9-84ce-4495-8914-7d40a27a3b10

	measure 'meas.users_overview_win_rate_ytd_sply_diff' = ```
			
			var res = DIVIDE(([meas.users_overview_win_rate_ytd]-[meas.users_overview_win_rate_ytd_sply]), [meas.users_overview_win_rate_ytd])
			
			// get the delta
			
			RETURN 
			IF(
			    res = BLANK(),
			    "-",
			    res
			)
			```
		formatString: +0%;-0%;"-"
		displayFolder: _active_user_overview
		lineageTag: 1a8f810c-0797-490a-bcbc-d31a32001c74

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.users_overview_avg_pred_conv_rate_mtd' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_mtd &&  cal_end_dates[Date] <= end_date)
			
			-- apply addl. filters for sales steps
			var filt_tbl = Filter(dates_tbl, ssr_history[step_name] in { "New Logo Selling","Post-Sales Support","Prospecting","Existing Customer Selling"} )
			
			var res = CALCULATE(
			    AVERAGEX(
			        filt_tbl,
			        ssr_history[step_success_prob]
			    )
			)
			
			RETURN res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 948eb230-a8c7-4ff6-bcc4-06359fe0ba6d

	measure 'meas.users_overview_avg_pred_conv_rate_mtd_sply' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_mtd_sply &&  cal_end_dates[Date] <= end_date_sply)
			
			-- apply addl. filters for sales steps
			var filt_tbl = Filter(dates_tbl, ssr_history[step_name] in { "New Logo Selling","Post-Sales Support","Prospecting","Existing Customer Selling"} )
			
			var res = CALCULATE(
			    AVERAGEX(
			        filt_tbl,
			        ssr_history[step_success_prob]
			    )
			)+0
			
			RETURN res
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 7d964627-3956-4dbf-a6e3-d9d7bcfc2bf5

	measure 'meas.users_overview_avg_pred_conv_mtd_sply_diff' = ```
			
			var res = DIVIDE([meas.users_overview_avg_pred_conv_rate_mtd] - [meas.users_overview_avg_pred_conv_rate_mtd_sply], [meas.users_overview_avg_pred_conv_rate_mtd])
			RETURN 
			IF(
			    res = BLANK(),
			    "-",
			    res
			)
			```
		formatString: +0%;-0%;"-"
		displayFolder: _active_user_overview
		lineageTag: 8832b4c5-b603-428b-9ca7-9b20cfaaa3b2

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.users_overview_avg_pred_conv_rate_qtd' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_qtd &&  cal_end_dates[Date] <= end_date)
			
			-- apply addl. filters for sales steps
			var filt_tbl = Filter(dates_tbl, ssr_history[step_name] in { "New Logo Selling","Post-Sales Support","Prospecting","Existing Customer Selling"} )
			
			var res = CALCULATE(
			    AVERAGEX(
			        filt_tbl,
			        ssr_history[step_success_prob]
			    )
			)+0
			
			RETURN res
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 7703ba0a-e9d0-4a81-ba9d-781cf350d54e

	measure 'meas.users_overview_avg_pred_conv_rate_qtd_sply' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_qtd_sply &&  cal_end_dates[Date] <= end_date_sply)
			
			-- apply addl. filters for sales steps
			var filt_tbl = Filter(dates_tbl, ssr_history[step_name] in { "New Logo Selling","Post-Sales Support","Prospecting","Existing Customer Selling"})
			
			var res = CALCULATE(
			    AVERAGEX(
			        filt_tbl,
			        ssr_history[step_success_prob]
			    )
			)+0
			
			RETURN res
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 91dd19a6-1fa4-42e5-968a-db02bf828f0e

	measure 'meas.users_overview_avg_pred_conv_qtd_sply_diff' = ```
			
			var res = DIVIDE([meas.users_overview_avg_pred_conv_rate_qtd] - [meas.users_overview_avg_pred_conv_rate_qtd_sply], [meas.users_overview_avg_pred_conv_rate_qtd])
			RETURN 
			IF(
			    res = BLANK(),
			    "-",
			    res
			)
			```
		formatString: +0%;-0%;"-"
		displayFolder: _active_user_overview
		lineageTag: 4fc18d35-811b-4d17-8a2b-75517ba44e70

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.users_overview_avg_pred_conv_rate_ytd' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_ytd &&  cal_end_dates[Date] <= end_date)
			
			-- apply addl. filters for sales steps
			var filt_tbl = Filter(dates_tbl, ssr_history[step_name] in { "New Logo Selling","Post-Sales Support","Prospecting","Existing Customer Selling"})
			
			var res = CALCULATE(
			    AVERAGEX(
			        filt_tbl,
			        ssr_history[step_success_prob]
			    )
			)+0
			
			RETURN res
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: e3eece90-6448-45ce-9ea9-a89ed47c6414

	measure 'meas.users_overview_avg_pred_conv_rate_ytd_sply' = ```
			
			
			-- get the dates
			var curr_date = CALCULATE(MAX(cal_end_dates[Date])) // get the mgmt current end date
			var end_date = curr_date
			var end_date_sply = date(Year(end_date) -1,Month(end_date),day(end_date)) // get the yoy end date
			var start_year = Year(curr_date) 
			var start_qtr_month = (Quarter(curr_date) * 3) - 2  
			var start_month = Month(curr_date)
			var start_date_ytd = date(start_year,1,1)  
			var start_date_ytd_sply = date(start_year-1,1,1)  
			var start_date_qtd = date(start_year,start_qtr_month ,1)  
			var start_date_qtd_sply = date(start_year -1,start_qtr_month,1)  
			var start_date_mtd = date(start_year,start_month,1)  
			var start_date_mtd_sply = date(start_year -1,start_month,1)  
			
			-- get data for overridden date periods but still contextual
			var dates_tbl =  CALCULATETABLE(ssr_history , cal_end_dates[Date] >=  start_date_ytd_sply &&  cal_end_dates[Date] <= end_date_sply)
			
			-- apply addl. filters for sales steps
			var filt_tbl = Filter(dates_tbl, ssr_history[step_name] in { "New Logo Selling","Post-Sales Support","Prospecting","Existing Customer Selling"})
			
			var res = CALCULATE(
			    AVERAGEX(
			        filt_tbl,
			        ssr_history[step_success_prob]
			    )
			)+0
			
			RETURN res
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: 92cb3110-77ea-42c3-b92b-6f1ebb40254a

	measure 'meas.users_overview_avg_pred_conv_ytd_sply_diff' = ```
			
			var res = DIVIDE([meas.users_overview_avg_pred_conv_rate_ytd] - [meas.users_overview_avg_pred_conv_rate_ytd_sply], [meas.users_overview_avg_pred_conv_rate_ytd])       // get the delta
			RETURN 
			IF(
			    res = BLANK(),
			    "-",
			    res
			)
			```
		formatString: +0%;-0%;"-"
		displayFolder: _active_user_overview
		lineageTag: ddbc5fa2-1c77-47d1-b6ff-eba18233148a

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.ssr_history_actual_win_rate' = ```
			
			
			
			-- apply addl. filters by sales steps
			var success_filt_tbl = Filter(ssr_history,  ssr_history[step_success] = true) // filter table for success steps
			
			
			var total_steps = CALCULATE( 
			    COUNTX(
			        ssr_history,
			        ssr_history[_sys_doc_id]
			    )
			)
			
			
			var success_steps  = CALCULATE(
			    COUNTX(
			        success_filt_tbl,
			        ssr_history[_sys_doc_id]
			    )
			)
			var res = DIVIDE(success_steps, total_steps, BLANK())
			return res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _active_user_overview
		lineageTag: b697679b-3c93-4420-86f1-f25eb146002f

	measure 'meas.users_trueai_full_name' =
			
			SELECTEDVALUE(users[trueai_full_name])
		lineageTag: 31d53d83-f813-4c59-a312-df48ed52ef39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_division
		dataType: string
		lineageTag: 33550b93-126b-487d-9e30-5ec88ff36709
		summarizeBy: none
		sourceColumn: crm_division

		annotation SummarizationSetBy = Automatic

	column crm_username
		dataType: string
		lineageTag: bbcdda99-fb1d-4cc2-bafb-c79586cedb19
		summarizeBy: none
		sourceColumn: crm_username

		annotation SummarizationSetBy = Automatic

	column crm_email
		dataType: string
		lineageTag: a6335290-93dc-42cd-a2ce-2de9c5137a5b
		summarizeBy: none
		sourceColumn: crm_email

		annotation SummarizationSetBy = Automatic

	column crm_language_locale
		dataType: string
		lineageTag: 40e21f33-6ae5-46a7-8c18-06e4354f88b1
		summarizeBy: none
		sourceColumn: crm_language_locale

		annotation SummarizationSetBy = Automatic

	column crm_last_login_time
		dataType: dateTime
		formatString: General Date
		lineageTag: b24275a3-13db-4e05-ab17-2e6a117711e6
		summarizeBy: none
		sourceColumn: crm_last_login_time

		variation Variation
			isDefault
			relationship: 8a82df05-2884-4426-baf5-765dc77dc229
			defaultHierarchy: LocalDateTable_11fc6c4a-c432-4ad2-a5ac-2daa6b506406.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_locale
		dataType: string
		lineageTag: 399b4143-6c76-4299-ae26-393cf9c2a963
		summarizeBy: none
		sourceColumn: crm_locale

		annotation SummarizationSetBy = Automatic

	column crm_profile_url
		dataType: string
		lineageTag: ea0574d9-3f71-4e27-a708-f214d2215cc9
		summarizeBy: none
		sourceColumn: crm_profile_url

		annotation SummarizationSetBy = Automatic

	column crm_time_zone
		dataType: string
		lineageTag: 01e66e1b-d600-4838-9c3b-3a63028092c1
		summarizeBy: none
		sourceColumn: crm_time_zone

		annotation SummarizationSetBy = Automatic

	column crm_role
		dataType: string
		lineageTag: 7b0b30a3-2da8-4109-8f97-646b7e68c951
		summarizeBy: none
		sourceColumn: crm_role

		annotation SummarizationSetBy = Automatic

	column crm_title
		dataType: string
		lineageTag: eaf0edd9-7aac-46e2-80c7-dbaa5ffb69eb
		summarizeBy: none
		sourceColumn: crm_title

		annotation SummarizationSetBy = Automatic

	column crm_user_type
		dataType: string
		lineageTag: 44f73047-d35f-44cc-be40-abe2bcc9e958
		summarizeBy: none
		sourceColumn: crm_user_type

		annotation SummarizationSetBy = Automatic

	column trueai_hire_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: e049536e-c0ac-4f78-b6f0-c63e8bbb1225
		summarizeBy: none
		sourceColumn: trueai_hire_date

		variation Variation
			isDefault
			relationship: 9d1627e3-bf9f-4029-8b9a-076a51d6ea6c
			defaultHierarchy: LocalDateTable_fdd4e3a5-c429-413b-90c0-7eca8a366125.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_termination_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: de59aad4-b3c0-436e-b48b-95ba59e20c6e
		summarizeBy: none
		sourceColumn: trueai_termination_date

		variation Variation
			isDefault
			relationship: de2e6583-4e38-4e0b-a75a-32379330c4e4
			defaultHierarchy: LocalDateTable_7bca1e78-af76-46a2-abd5-5551bd7bd92d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_role
		dataType: string
		lineageTag: c529d258-39f0-42a3-b481-829244963fba
		summarizeBy: none
		sourceColumn: trueai_role

		annotation SummarizationSetBy = Automatic

	column trueai_title
		dataType: string
		lineageTag: 376df9b2-b031-4756-8088-e7fdf9d4d8f0
		summarizeBy: none
		sourceColumn: trueai_title

		annotation SummarizationSetBy = Automatic

	column trueai_user_role
		dataType: string
		lineageTag: 7c85b453-efa0-4534-911c-b80405c92a1d
		summarizeBy: none
		sourceColumn: trueai_user_role

		annotation SummarizationSetBy = Automatic

	column trueai_group
		dataType: string
		lineageTag: 6bbe1ba9-9650-4c21-9a9b-0422c0e0ecf5
		summarizeBy: none
		sourceColumn: trueai_group
		sortByColumn: 'col.trueai_group_sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column trueai_direct_reports
		dataType: int64
		formatString: 0
		lineageTag: a596de3f-dc32-4c2d-849e-db481ba399df
		summarizeBy: sum
		sourceColumn: trueai_direct_reports

		annotation SummarizationSetBy = Automatic

	column trueai_billable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d0d89462-e5ef-4a24-8137-9813b59c0ead
		summarizeBy: none
		sourceColumn: trueai_billable

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_function
		dataType: string
		lineageTag: 64cfb219-565d-44dd-ba77-e725875c7072
		summarizeBy: none
		sourceColumn: trueai_user_role_function
		sortByColumn: trueai_user_role_function_sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column _sys_co_id
		dataType: string
		lineageTag: 71c257d2-1ef0-4616-9ba5-797ef77c98db
		summarizeBy: none
		sourceColumn: _sys_co_id

		annotation SummarizationSetBy = Automatic

	column _sys_doc_id
		dataType: string
		lineageTag: e8e2daec-ae5b-4985-8c92-c68f14abdd97
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 10d9fa5b-ba58-499a-a52e-62e3565a0464
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: d5cffb46-3da1-4de2-a44d-9b4480907534
			defaultHierarchy: LocalDateTable_7e8444de-f6bc-40e4-bd41-17bec32bd6c2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9c1ce28b-787f-4442-9a65-51b58a91cc8a
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 5b4574c0-a988-486b-8ef0-d5a06bd0c202
			defaultHierarchy: LocalDateTable_a5062363-5200-4250-ac1e-16fa22859986.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column crm_addr_city
		dataType: string
		lineageTag: 7930dadb-8b5c-4ab8-aac5-6c14641f9258
		summarizeBy: none
		sourceColumn: crm_addr_city

		annotation SummarizationSetBy = Automatic

	column crm_addr_country
		dataType: string
		lineageTag: e2441aa2-5825-43ab-b80d-d69de529b586
		summarizeBy: none
		sourceColumn: crm_addr_country

		annotation SummarizationSetBy = Automatic

	column crm_addr_postal_code
		dataType: string
		lineageTag: ee2fd37d-f267-44b7-b20c-d0a3c270bcfd
		summarizeBy: none
		sourceColumn: crm_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column crm_addr_state
		dataType: string
		lineageTag: 76dbaaa4-5dee-4fd5-84c2-663a5f953eb0
		summarizeBy: none
		sourceColumn: crm_addr_state

		annotation SummarizationSetBy = Automatic

	column crm_addr_street
		dataType: string
		lineageTag: f01edc9c-e8e2-443b-a396-d3573b4660c2
		summarizeBy: none
		sourceColumn: crm_addr_street

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: 35ed8194-09ce-4a02-b407-c4a1b358cf3a
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_first_name
		dataType: string
		lineageTag: e132a761-7019-4330-af3a-88ecde498e55
		summarizeBy: none
		sourceColumn: crm_first_name

		annotation SummarizationSetBy = Automatic

	column crm_last_name
		dataType: string
		lineageTag: 6747da50-f339-4bfc-9f0b-fdd844c87cec
		summarizeBy: none
		sourceColumn: crm_last_name

		annotation SummarizationSetBy = Automatic

	column trueai_performance_lvl_reached_on
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3dc56c4f-fb0a-4baa-8f30-8055944ed328
		summarizeBy: none
		sourceColumn: trueai_performance_lvl_reached_on

		variation Variation
			isDefault
			relationship: e91c4646-321f-485c-8aa3-9b1cad614386
			defaultHierarchy: LocalDateTable_126bb43c-ff78-4621-9ac0-1d9d42f4fd2a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_role_conf
		dataType: double
		lineageTag: 1ab4cfc7-edad-4ee2-b503-f9666c72f7f6
		summarizeBy: sum
		sourceColumn: trueai_role_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_tenure
		dataType: int64
		formatString: #,##0" Mos."
		lineageTag: 654e1b4a-4a20-4fe0-aa77-db2ea5d0d5b6
		summarizeBy: sum
		sourceColumn: trueai_tenure

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column trueai_title_conf
		dataType: double
		lineageTag: 076364ca-9ec0-46c7-8b87-fd4c24d6d5a9
		summarizeBy: sum
		sourceColumn: trueai_title_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_tot_reports
		dataType: int64
		formatString: 0
		lineageTag: efe2ffd8-0432-4270-a42a-130df1e159e1
		summarizeBy: sum
		sourceColumn: trueai_tot_reports

		annotation SummarizationSetBy = Automatic

	column trueai_user_behavior
		dataType: string
		lineageTag: 881fa4e2-25db-45d6-bc6e-b3010b4d19d7
		summarizeBy: none
		sourceColumn: trueai_user_behavior

		annotation SummarizationSetBy = Automatic

	column trueai_user_behavior_conf
		dataType: double
		lineageTag: 6c375721-4e2a-4800-900b-d0982ddde52b
		summarizeBy: sum
		sourceColumn: trueai_user_behavior_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_group_conf
		dataType: double
		lineageTag: 75242738-9532-4ba2-819d-ff2b71efe356
		summarizeBy: sum
		sourceColumn: trueai_group_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_ext_match_rule
		dataType: int64
		formatString: 0
		lineageTag: 999040cd-96d5-4101-8400-df5bc0275885
		summarizeBy: sum
		sourceColumn: trueai_ext_match_rule

		annotation SummarizationSetBy = Automatic

	column trueai_group_rule
		dataType: int64
		formatString: 0
		lineageTag: 7a59b985-736e-446a-855d-7da651a400ad
		summarizeBy: sum
		sourceColumn: trueai_group_rule

		annotation SummarizationSetBy = Automatic

	column trueai_addr_city
		dataType: string
		lineageTag: b9f74bf7-6821-499c-99ea-121d62d53168
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	column trueai_addr_country
		dataType: string
		lineageTag: 21759031-884d-48bb-bd54-63165b07c586
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	column trueai_addr_lat
		dataType: double
		lineageTag: 65519d9e-e4a0-41f8-be24-64ba7e56a285
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_long
		dataType: double
		lineageTag: 686624b3-6392-4ca9-b6c3-4b0c0ea6e0d0
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_postal_code
		dataType: string
		lineageTag: f032fa51-2ef0-4598-a2f6-885ec41caa22
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column trueai_addr_state
		dataType: string
		lineageTag: 5feaa1a3-4497-4e89-bbe7-bd4049f58e58
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	column trueai_addr_street
		dataType: string
		lineageTag: c63ed787-2d57-41ca-8ee9-58337214e68a
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	column trueai_ext_match_id
		dataType: string
		lineageTag: 7251d3c3-3fe6-4ad1-be7a-c3d5d360c672
		summarizeBy: none
		sourceColumn: trueai_ext_match_id

		annotation SummarizationSetBy = Automatic

	column _sys_as_of
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4a052658-52b2-4a8c-a868-35b5197a0467
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 6954fed3-a23b-4e93-a5a8-020d72b33b44
			defaultHierarchy: LocalDateTable_f7bb80d9-198b-4ebc-9d5a-142cca7445ce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 4d3439f3-cc47-4ea1-9598-023981344416
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 7054dee1-c92e-4069-8ae6-35c3146f2d89
			defaultHierarchy: LocalDateTable_effd522b-b03a-49c3-88fe-1240835fef98.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 53484041-0449-4cdb-9b8d-1602e78e8ba6
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: b4e60e36-96ca-4705-8e77-b6171ccd1d46
			defaultHierarchy: LocalDateTable_e59a4e9e-cacf-4dd0-9523-40d40a4a6bf9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_mgr_id
		dataType: string
		lineageTag: c2ac481c-edb1-405e-ad05-52b9aa1f63d0
		summarizeBy: none
		sourceColumn: crm_mgr_id

		annotation SummarizationSetBy = Automatic

	column trueai_is_mgr
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 92bf4983-5528-4698-8fed-197fe9966ade
		summarizeBy: none
		sourceColumn: trueai_is_mgr

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_id
		dataType: string
		lineageTag: d5697ebe-e0cb-403c-bb15-16cacaa5beb3
		summarizeBy: none
		sourceColumn: trueai_mgr_id

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_id_conf
		dataType: double
		lineageTag: 9fdd29b0-ac67-4e23-bce3-062fad89e746
		summarizeBy: sum
		sourceColumn: trueai_mgr_id_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_mgr_id_rule
		dataType: int64
		formatString: 0
		lineageTag: 3db2acf8-9f51-46e8-aaa3-b6b51f206ea2
		summarizeBy: sum
		sourceColumn: trueai_mgr_id_rule

		annotation SummarizationSetBy = Automatic

	column trueai_mgr_ids
		dataType: string
		lineageTag: 98e65bfd-e87e-4049-ba61-1dd9fc3b3650
		summarizeBy: none
		sourceColumn: trueai_mgr_ids

		annotation SummarizationSetBy = Automatic

	column trueai_full_name_title = ```
			IF(
			    ISBLANK(users[crm_first_name]) , 
			    users[crm_username] ,  
			    users[crm_first_name] &  " " &  users[crm_last_name] & ", " & users[crm_title])
			```
		lineageTag: b0ddfd37-9b40-483f-b3ce-7412f24135b8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'col.trueai_group_sort' =
			
			VAR _group = CALCULATE(MAX(users_history[trueai_group]))
			
			VAR res = IF(
			    _group="ND",
			    1,
			    0
			)
			RETURN
			res
		formatString: 0
		lineageTag: 54c56aac-2a6c-444e-8449-a065682002fb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_alias
		dataType: string
		lineageTag: e7262945-9334-4bdb-9ff3-2d8562c4db5b
		summarizeBy: none
		sourceColumn: trueai_user_role_alias

		annotation SummarizationSetBy = Automatic

	column trueai_is_dummy
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9b32f7df-f8e5-44f3-b523-dfe25145e02a
		summarizeBy: none
		sourceColumn: trueai_is_dummy

		annotation SummarizationSetBy = Automatic

	column trueai_test
		dataType: string
		lineageTag: b611eac7-d877-4f66-9423-433db44223fa
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	column trueai_test_conf
		dataType: double
		lineageTag: 7996e98e-d82e-4121-8a5a-65afb1f34be6
		summarizeBy: sum
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_test_rule
		dataType: string
		lineageTag: c8fc1029-13c6-4545-9ba8-c2ebd080c9b1
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	column trueai_test_debug
		dataType: string
		lineageTag: e67c5c07-a880-45ec-8c1e-0402fe9ac781
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: aeba5101-8eb8-4172-a959-1720cd620e67
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: 01f5acb3-9866-4abf-92f3-4ad8e322b309
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: 1be9b9c0-fdaf-4ed1-9cbf-bfddf3cbac90
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: 996365ff-7b99-46cb-b2e8-73cb6be7f772
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: 53fb48ca-ff23-4e5f-8f43-9bbc92e58ff1
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: double
		lineageTag: 39aff411-5a20-4e42-bc66-1e2dffb58f4a
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num2
		dataType: double
		lineageTag: 116a6d32-5a97-48dd-8dc0-ace0f32cd118
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num3
		dataType: double
		lineageTag: edcc5cb2-d532-49cb-bb25-a2c800fff642
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num4
		dataType: double
		lineageTag: afedfc0e-aea1-4f5f-8796-bf8f8c948cf6
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num5
		dataType: double
		lineageTag: 18b2693e-9a69-4b21-9a73-efc7a0df9d46
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num6
		dataType: double
		lineageTag: 587399da-ee82-4b4e-89f4-349238cca390
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num7
		dataType: double
		lineageTag: 7265e1c0-5aab-4812-b88a-6a5ae4fcad4d
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6e8a38c2-1792-4cef-b1ef-313dd272f751
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0c1efc2b-3163-4a01-9ac6-697d6a828c9a
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_sort
		dataType: int64
		formatString: 0
		lineageTag: 49f7c349-5d1c-44fe-8a96-9d8431fb1f71
		summarizeBy: sum
		sourceColumn: trueai_user_role_sort

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_function_sort
		dataType: int64
		formatString: 0
		lineageTag: b510b371-38de-444a-b542-4e63bd9ba57e
		summarizeBy: sum
		sourceColumn: trueai_user_role_function_sort

		annotation SummarizationSetBy = Automatic

	column crm_deep_link
		dataType: string
		lineageTag: e281d443-35d9-4b72-bf57-35ff9ebc1b51
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	column trueai_full_name
		dataType: string
		lineageTag: 61b18b35-2104-49b7-a370-02d270de24c8
		summarizeBy: none
		sourceColumn: trueai_full_name

		annotation SummarizationSetBy = Automatic

	column trueai_ramping_status
		dataType: string
		lineageTag: d56d219f-f4bf-414f-9f17-f239c6262bd7
		summarizeBy: none
		sourceColumn: trueai_ramping_status

		annotation SummarizationSetBy = Automatic

	column 'col.is_ext_match_id' =
			
			IF ( NOT ISBLANK ( 'users'[trueai_ext_match_id] ), "True", "False" )
		lineageTag: 66dfae85-06b2-4816-819f-a7c89744ce92
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column crm_department
		dataType: string
		lineageTag: 650ad7fc-178b-4e84-9692-e9bc1f0a30b4
		summarizeBy: none
		sourceColumn: crm_department

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_department
		dataType: string
		lineageTag: 1443952d-6658-4dcf-9bbd-5cb78877870f
		summarizeBy: none
		sourceColumn: trueai_user_role_department

		annotation SummarizationSetBy = Automatic

	column trueai_user_role_department_sort
		dataType: int64
		formatString: 0
		lineageTag: 841dcffa-8019-42b8-99be-252557a5fd90
		summarizeBy: sum
		sourceColumn: trueai_user_role_department_sort

		annotation SummarizationSetBy = Automatic

	partition users-325b18c0-2983-4ccf-ad12-2466298e6bdc = m
		mode: import
		source =
				let
				
				  dbTable = getDBTable("users"), // get the right table
				
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				      {"_sys_as_of", type datetime},
				{"_sys_co_id", type text},
				{"_sys_doc_id", type text},
				{"_sys_filt_end_date", type date},
				{"_sys_filt_start_date", type date},
				{"_sys_last_modified_on", type datetime},
				{"crm_addr_city", type text},
				{"crm_addr_country", type text},
				{"crm_addr_postal_code", type text},
				{"crm_addr_state", type text},
				{"crm_addr_street", type text},
				{"crm_created_on", type datetime},
				{"crm_creator_id", type text},
				{"crm_deep_link", type text},
				{"crm_department", type text},
				{"crm_division", type text},
				{"crm_email", type text},
				{"crm_first_name", type text},
				{"crm_language_locale", type text},
				{"crm_last_login_time", type datetime},
				{"crm_last_name", type text},
				{"crm_locale", type text},
				{"crm_mgr_id", type text},
				{"crm_profile_url", type text},
				{"crm_role", type text},
				{"crm_time_zone", type text},
				{"crm_title", type text},
				{"crm_user_type", type text},
				{"crm_username", type text},
				{"cust_bool1", type logical},
				{"cust_bool2", type logical},
				{"cust_num1", type number},
				{"cust_num2", type number},
				{"cust_num3", type number},
				{"cust_num4", type number},
				{"cust_num5", type number},
				{"cust_num6", type number},
				{"cust_num7", type number},
				{"cust_text1", type text},
				{"cust_text2", type text},
				{"cust_text3", type text},
				{"cust_text4", type text},
				{"cust_text5", type text},
				{"trueai_addr_city", type text},
				{"trueai_addr_country", type text},
				{"trueai_addr_lat", type number},
				{"trueai_addr_long", type number},
				{"trueai_addr_postal_code", type text},
				{"trueai_addr_state", type text},
				{"trueai_addr_street", type text},
				{"trueai_billable", type logical},
				{"trueai_direct_reports", Int64.Type},
				{"trueai_ext_match_id", type text},
				{"trueai_ext_match_rule", Int64.Type},
				{"trueai_full_name", type text},
				{"trueai_group", type text},
				{"trueai_group_conf", type number},
				{"trueai_group_rule", Int64.Type},
				{"trueai_hire_date", type datetime},
				{"trueai_is_dummy", type logical},
				{"trueai_is_mgr", type logical},
				{"trueai_mgr_id", type text},
				{"trueai_mgr_id_conf", type number},
				{"trueai_mgr_id_rule", Int64.Type},
				{"trueai_mgr_ids", type text},
				{"trueai_performance_lvl_reached_on", type datetime},
				{"trueai_ramping_status", type text},
				{"trueai_role", type text},
				{"trueai_role_conf", type number},
				{"trueai_tenure", Int64.Type},
				{"trueai_termination_date", type datetime},
				{"trueai_test", type text},
				{"trueai_test_conf", type number},
				{"trueai_test_debug", type text},
				{"trueai_test_rule", type text},
				{"trueai_title", type text},
				{"trueai_title_conf", type number},
				{"trueai_tot_reports", Int64.Type},
				{"trueai_user_behavior", type text},
				{"trueai_user_behavior_conf", type number},
				{"trueai_user_role", type text},
				{"trueai_user_role_alias", type text},
				{"trueai_user_role_department", type text},
				{"trueai_user_role_function", type text}
				    }),
				    addedUserRoleAliasedSort = Table.AddColumn(dbTableTyped, "trueai_user_role_sort", each if [trueai_user_role] = "ND" then 99 else 1),
				    UserRoleFunctionSort = Table.AddColumn(addedUserRoleAliasedSort, "trueai_user_role_function_sort", each if [trueai_user_role_function] = "ND" then 99 else 1),
				    UserRoleDeptSort = Table.AddColumn(UserRoleFunctionSort, "trueai_user_role_department_sort", each if [trueai_user_role_dept] = "ND" then 99 else 1),
				    DataTyped = Table.TransformColumnTypes(UserRoleDeptSort,{{"trueai_user_role_sort", Int64.Type}, {"trueai_user_role_function_sort", Int64.Type}, {"trueai_user_role_department_sort", Int64.Type}})
				in
				    DataTyped

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

