/// Table act_time_alloc_summary.
table act_time_alloc_summary
	lineageTag: 784db851-8b49-42ca-99be-90fa56772532

	/// Purpose: Act Time Alloc Reps.
	/// Logic: No VAR blocks.
	/// Dependencies: Columns: act_time_alloc_summary[_sys_user_id].
	/// Context: Uses CALCULATE/CALCULATETABLE to modify filter context with its filter arguments.
	/// Output: Whole number
	measure 'meas.act_time_alloc_reps' = CALCULATE(DISTINCTCOUNT(act_time_alloc_summary[_sys_user_id]))
		formatString: 0
		displayFolder: _tl_analysis
		lineageTag: 7b3aa411-fbb6-4366-893f-6222d570fa8f

	/// Purpose: Act Time Alloc Reps W Act Capt Level.
	/// Logic: VAR blocks define intermediate values (res) used later in the expression.
	/// Dependencies: Columns: act_time_alloc_summary[act_capt_lvl_adjustment] | Measures: [meas.act_time_alloc_reps].
	/// Context: Uses IF for conditional branching.
	/// Output: Whole number
	measure 'meas.act_time_alloc_reps_w_act_capt_level' = 
			
			var res = Calculate([meas.act_time_alloc_reps], act_time_alloc_summary[act_capt_lvl_adjustment] > 0)
			return if(ISBLANK(res) , 0, res)
			
		formatString: 0
		displayFolder: _tl_analysis
		lineageTag: 41b390ab-c2d0-487d-8c76-f569e1464fe6

	/// Purpose: Act Time Alloc Captured Durations H.
	/// Logic: No VAR blocks.
	/// Dependencies: No explicit column or measure references detected..
	/// Context: No explicit conditional branching detected.
	/// Output: Text
	measure 'meas.act_time_alloc_captured_durations_h' =
			
			var res = CALCULATE(Sum(act_time_alloc_summary[act_dur]) / 3600)
			return IF(ISBLANK(res), 0, res)
		formatString: ###,###,###0.0" hrs"
		displayFolder: _tl_analysis
		lineageTag: 87c56af4-3aca-4a61-bab1-c500e9f3ae15

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Act Time Alloc Adj Durations H.
	/// Logic: No VAR blocks.
	/// Dependencies: No explicit column or measure references detected..
	/// Context: No explicit conditional branching detected.
	/// Output: Text
	measure 'meas.act_time_alloc_adj_durations_h' =
			
			// var capt_dur_tbl = CALCULATETABLE( act_time_alloc_summary, act_time_alloc_summary[act_capt_lvl_adjustment] > 0)
			// var capt_lvl_adj  = sumx(capt_dur_tbl, act_time_alloc_summary[act_dur] * act_time_alloc_summary[prep_adjustment] * act_time_alloc_summary[act_capt_lvl_adjustment] )
			
			// var res = capt_lvl_adj /3600
			// return IF(ISBLANK(res), 0, res)
			
			
			var _captured_dur = [meas.act_time_alloc_captured_durations_h]      // get the capture duration hrs
			var _adj_factor = AVERAGE(act_time_alloc_summary[act_capt_lvl_adjustment])      // get the capt_lvl adjsument average
			var _prep_factor = AVERAGE(act_time_alloc_summary[prep_adjustment])         // getbthe avg prep factor
			
			var res = _captured_dur*_adj_factor*_prep_factor    // get the adjusted duratio
			
			return
			res
		formatString: ###,###,###" hrs"
		displayFolder: _tl_analysis
		lineageTag: a9976925-1bc8-4b96-9b93-8ad1465e02a1

	/// Purpose: Act Time Alloc Avg Dur.
	/// Logic: No VAR blocks.
	/// Dependencies: No explicit column or measure references detected..
	/// Context: No explicit conditional branching detected.
	/// Output: Text
	measure 'meas.act_time_alloc_avg_dur' =
			var capt_dur_min = CALCULATE(Sum(act_time_alloc_summary[act_dur]) / 60)
			var capt_tot  = CALCULATE(Sum(act_time_alloc_summary[act_tot_count]))
			var res =  DIVIDE(capt_dur_min,capt_tot)
			return IF(ISBLANK(res), 0, res)
		formatString: ###,###,###" min"
		displayFolder: _tl_analysis
		lineageTag: af4127e5-1a22-4bde-aa1e-9a4d03d1a80a

	/// Purpose: Act Time Rep W Act Capt Level Pct.
	/// Logic: VAR blocks define intermediate values (res) used later in the expression.
	/// Dependencies: Measures: [meas.act_time_alloc_reps_w_act_capt_level], [meas.act_time_alloc_reps].
	/// Context: No explicit conditional branching detected.
	/// Output: Percentage
	measure 'meas.act_time_rep_w_act_capt_level_pct' = 
			
			var res  = DIVIDE([meas.act_time_alloc_reps_w_act_capt_level],[meas.act_time_alloc_reps])
			return res
			
		formatString: 0%;-0%;0%
		displayFolder: _tl_analysis
		lineageTag: 32b18e31-82ff-4240-a15b-d8ff9447d912

		changedProperty = FormatString

	/// Purpose: Act Time Alloc Hours Weekly.
	/// Logic: VAR blocks define intermediate values (time, count_months, week_adj, res, _cap_dure, adj_factor, prep_factor, _total_duration, _min_date, _max_date, week_count, _reps_w_ta) used later in the expression.
	/// Dependencies: Columns: act_time_alloc_summary[_sys_filter_end_date], act_time_alloc_summary[_sys_filter_start_date], act_time_alloc_summary[act_capt_lvl_adjustment], act_time_alloc_summary[month_to_week_adjustment], act_time_alloc_summary[prep_adjustment] | Measures: [meas.act_time_alloc_adj_durations_h], [meas.act_time_alloc_user_months_w_time_alloc], [meas.act_time_alloc_captured_durations_h], [meas.act_time_alloc_reps_w_act_capt_level].
	/// Context: Uses IF for conditional branching.
	/// Output: Text
	measure 'meas.act_time_alloc_hours_weekly' = 
			
			
			-- this is old code where we get the avg. weekly hrs per Rep for AE --> 83 hrs/week --------
			
			// var time = [meas.act_time_alloc_adj_durations_h]
			// var count_months = [meas.act_time_alloc_user_months_w_time_alloc]
			// var week_adj = CALCULATE(AVERAGE( act_time_alloc_summary[month_to_week_adjustment]), act_time_alloc_summary[act_capt_lvl_adjustment] > 0)
			// var res = DIVIDE(time, count_months * week_adj )
			// return res
			
			var _cap_dure = [meas.act_time_alloc_captured_durations_h]              // get the captured durations hrs
			var adj_factor = AVERAGE(act_time_alloc_summary[act_capt_lvl_adjustment])               // get the adjustment factor
			var prep_factor = AVERAGE(act_time_alloc_summary[prep_adjustment])                      // get the prep factor
			var _total_duration = (_cap_dure*adj_factor*prep_factor)                                // calculate the total duration
			
			
			var _min_date = CALCULATE(MIN(act_time_alloc_summary[_sys_filter_start_date]))
			var _max_date = CALCULATE(MAX(act_time_alloc_summary[_sys_filter_end_date]))
			var week_count = DATEDIFF(_min_date,_max_date,WEEK)             // count of week
			
			var _reps_w_ta = [meas.act_time_alloc_reps_w_act_capt_level]        // get the reps with time allocation
			var res = DIVIDE(_total_duration, (week_count * _reps_w_ta) )
			RETURN
			res
			
		formatString: ###,###,###"  hrs/week"
		displayFolder: _tl_analysis
		lineageTag: 9ec1357c-9789-4e43-a71d-00c31ed960dd

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Act Time Alloc User Months W Time Alloc.
	/// Logic: No VAR blocks.
	/// Dependencies: Columns: act_time_alloc_summary[_sys_docid], act_time_alloc_summary[act_capt_lvl_adjustment].
	/// Context: Uses CALCULATE/CALCULATETABLE to modify filter context with its filter arguments.
	/// Output: Whole number
	measure 'meas.act_time_alloc_user_months_w_time_alloc' = 
			
			CALCULATE(count( act_time_alloc_summary[_sys_docid]), act_time_alloc_summary[act_capt_lvl_adjustment] > 0, act_time_alloc_summary[act_capt_lvl_adjustment] > 0)
			
		formatString: 0
		displayFolder: _tl_analysis
		lineageTag: 49d72214-dc8d-4f17-a750-cb340feba375

	/// Purpose: Act Time Alloc Capture Lvl.
	/// Logic: No VAR blocks.
	/// Dependencies: No explicit column or measure references detected..
	/// Context: No explicit conditional branching detected.
	/// Output: Percentage
	measure 'meas.act_time_alloc_capture_lvl' =
			
			divide(1,calculate(AVERAGE(act_time_alloc_summary[act_capt_lvl_adjustment])))
		formatString: 0%;-0%;0%
		displayFolder: _tl_analysis
		lineageTag: 6825710f-355b-49bf-93b6-549ccf1e0f89

		changedProperty = FormatString

	/// Purpose: Act Time Rep Act Capture Value Pct.
	/// Logic: VAR blocks define intermediate values (reps, reps_act_capture, res) used later in the expression.
	/// Dependencies: Columns: act_time_alloc_summary[act_capt_lvl] | Measures: [meas.act_time_alloc_reps].
	/// Context: Uses CALCULATE/CALCULATETABLE to modify filter context with its filter arguments.
	/// Output: Percentage
	measure 'meas.act_time_rep_act_capture_value_pct' = 
			
			var reps = [meas.act_time_alloc_reps]
			var reps_act_capture = CALCULATE([meas.act_time_alloc_reps],  act_time_alloc_summary[act_capt_lvl] > 0)
			var res = DIVIDE ( reps_act_capture, reps)
			return res 
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _tl_analysis
		lineageTag: bdd26b8c-ef42-408e-8984-52b78f930c41

	/// Purpose: Tot Count.
	/// Logic: No VAR blocks.
	/// Dependencies: Columns: users_activities[trueai_count].
	/// Context: Uses CALCULATE/CALCULATETABLE to modify filter context with its filter arguments.
	/// Output: Whole number
	measure 'meas.tot_count' = CALCULATE(SUM(users_activities[trueai_count]))
		formatString: 0
		displayFolder: _tl_analysis
		lineageTag: ad57e66a-3b39-4ea3-b2f6-0b6ed7e07337

	/// Purpose: Act Time Alloc Hours Weekly Test.
	/// Logic: No VAR blocks.
	/// Dependencies: No explicit column or measure references detected..
	/// Context: No explicit conditional branching detected.
	/// Output: Decimal
	measure 'meas.act_time_alloc_hours_weekly_test' =
			
			var _cap_dure = [meas.act_time_alloc_captured_durations_h]              // get the captured durations hrs
			var adj_factor = AVERAGE(act_time_alloc_summary[act_capt_lvl_adjustment])               // get the adjustment factor
			var prep_factor = AVERAGE(act_time_alloc_summary[prep_adjustment])                      // get the prep factor
			var _total_duration = (_cap_dure*adj_factor*prep_factor)                                // calculate the total duration
			
			
			var _min_date = CALCULATE(MIN(act_time_alloc_summary[_sys_filter_start_date]))
			var _max_date = CALCULATE(MAX(act_time_alloc_summary[_sys_filter_end_date]))
			var week_count = DATEDIFF(_min_date,_max_date,WEEK)             // count of week
			
			var _reps_w_ta = [meas.act_time_alloc_reps_w_act_capt_level]        // get the reps with time allocation
			var res = DIVIDE(_total_duration, (week_count * _reps_w_ta) )
			RETURN
			res
		displayFolder: _tl_analysis
		lineageTag: c04f4aa8-43c4-4305-b135-3d99b59e3891

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column sort.
	column sort
		formatString: 0
		lineageTag: 4f986b40-1642-4f04-9d7c-12a316a62281
		summarizeBy: sum
		isNameInferred
		sourceColumn: [sort]

		annotation SummarizationSetBy = Automatic

	/// Column _sys_docid.
	column _sys_docid
		lineageTag: eeee48ff-c016-4835-a6bd-7806c4218641
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_docid]

		annotation SummarizationSetBy = Automatic

	/// Column _sys_user_id.
	column _sys_user_id
		lineageTag: f981d8cd-8a9e-4713-829b-93acc0b3ea7d
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_user_id]

		annotation SummarizationSetBy = Automatic

	/// Column _sys_filter_start_date.
	column _sys_filter_start_date
		formatString: Short Date
		lineageTag: 618cc91e-d7f3-4839-9cf4-07c67ec2957d
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_filter_start_date]

		variation Variation
			isDefault
			relationship: 55982658-6d4d-4b40-a93b-d8b1e4750958
			defaultHierarchy: LocalDateTable_c75e9ce6-4e49-45c8-97b0-76b4296cfd97.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	/// Column _sys_filter_end_date.
	column _sys_filter_end_date
		formatString: Short Date
		lineageTag: 70ab9415-3fb5-4a0b-a031-cc8d2dbdf94c
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_filter_end_date]

		variation Variation
			isDefault
			relationship: 44936954-9bc4-4a6e-bb4c-5b79e9cf8c36
			defaultHierarchy: LocalDateTable_b4b23882-ded4-4b7b-b035-01cc51dbdd98.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	/// Column full_name.
	column full_name
		lineageTag: 12da8bd2-77b2-4ce2-bbb6-b031aba8fe6c
		summarizeBy: none
		isNameInferred
		sourceColumn: [full_name]

		annotation SummarizationSetBy = Automatic

	/// Column user_role_function.
	column user_role_function
		lineageTag: 88da9a9e-081e-4e8b-8006-9a3549d8cd02
		summarizeBy: none
		isNameInferred
		sourceColumn: [user_role_function]

		annotation SummarizationSetBy = Automatic

	/// Column month_to_week_adjustment.
	column month_to_week_adjustment
		lineageTag: 96a05d21-2d40-4eb5-9e15-1d510d78fa95
		summarizeBy: none
		isNameInferred
		sourceColumn: [month_to_week_adjustment]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column act_tot_count.
	column act_tot_count
		formatString: ###,###,###
		lineageTag: 91a8b034-9d30-4c54-b13d-d7db4e0b15bc
		summarizeBy: sum
		isNameInferred
		sourceColumn: [act_tot_count]

		annotation SummarizationSetBy = Automatic

	/// Column act_dur.
	column act_dur
		formatString: 0
		lineageTag: 43430324-cb7f-41f2-bccf-6885bcd8ef7d
		summarizeBy: sum
		isNameInferred
		sourceColumn: [act_dur]

		annotation SummarizationSetBy = Automatic

	/// Column act_capt_lvl_adjustment.
	column act_capt_lvl_adjustment
		dataType: double
		lineageTag: b9c4444e-289e-4a0f-881a-7a2f9f71ffa7
		summarizeBy: sum
		isNameInferred
		sourceColumn: [act_capt_lvl_adjustment]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column prep_adjustment.
	column prep_adjustment
		dataType: double
		lineageTag: 498fa876-d7b3-4395-83e3-ac4e8ed639c6
		summarizeBy: sum
		isNameInferred
		sourceColumn: [prep_adjustment]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_tot.
	column time_alloc_tot
		formatString: ###" hrs/week"
		lineageTag: ba7cc1fc-5ae8-4b7d-84d3-4498f4bd479f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_tot]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column time_alloc_tot_eng.
	column time_alloc_tot_eng
		formatString: ###" hrs/week"
		lineageTag: c16d6a2c-6eea-43fe-bc13-28658c26c246
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_tot_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column time_alloc_prospecting.
	column time_alloc_prospecting
		dataType: double
		lineageTag: 908fe0d0-17a3-43ea-a09e-d5406f2d34c1
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_prospecting]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_prospecting_eng.
	column time_alloc_prospecting_eng
		dataType: double
		lineageTag: 4e85d559-0654-4aa7-8b42-fbae0709f78c
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_prospecting_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_new_logo.
	column time_alloc_new_logo
		dataType: double
		lineageTag: a190e2ec-0365-4a27-bca1-5f849f2c8cdb
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_new_logo]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_new_logo_eng.
	column time_alloc_new_logo_eng
		dataType: double
		lineageTag: 0efc2cd8-9ccf-4b6b-a90b-5589194b6495
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_new_logo_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_post_sales.
	column time_alloc_post_sales
		dataType: double
		lineageTag: c6cb9fe3-d119-48d9-9c16-b732adcee8ac
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_post_sales]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_internal.
	column time_alloc_internal
		dataType: double
		lineageTag: a649f48e-d68f-4b35-8fe1-798a64f5f6a3
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_internal]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_internal_eng.
	column time_alloc_internal_eng
		dataType: double
		lineageTag: 5f22f269-6de0-493e-bb1f-6cfea0eee38d
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_internal_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column dd.
	column dd
		formatString: 0
		lineageTag: 38a884ab-b0a1-42ba-83a9-9cc03513b575
		summarizeBy: sum
		isNameInferred
		sourceColumn: [dd]

		annotation SummarizationSetBy = Automatic

	/// Column act_capt_lvl.
	column act_capt_lvl
		lineageTag: 65f7e5a0-9a20-4f34-9fb8-e19886eed558
		summarizeBy: sum
		isNameInferred
		sourceColumn: [act_capt_lvl]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column act_capt_lvl_conf.
	column act_capt_lvl_conf
		lineageTag: 22c745ce-16bc-481a-a298-b787823ea7d4
		summarizeBy: sum
		isNameInferred
		sourceColumn: [act_capt_lvl_conf]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_tot_no_eng.
	column time_alloc_tot_no_eng
		formatString: ###" hrs/week"
		lineageTag: a9d73c2d-9061-4569-8eca-c1a7be00aafd
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_tot_no_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column time_alloc_prospecting_no_eng.
	column time_alloc_prospecting_no_eng
		formatString: ###" hrs/week"
		lineageTag: 55d470df-b04a-40e9-b428-37dbee16a17b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_prospecting_no_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column time_alloc_new_logo_no_eng.
	column time_alloc_new_logo_no_eng
		formatString: ###" hrs/week"
		lineageTag: 34a25b74-81af-4a11-9bd5-cb3219576e47
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_new_logo_no_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column time_alloc_post_sales_eng.
	column time_alloc_post_sales_eng
		dataType: double
		lineageTag: 903f38c7-0001-42b7-82e3-4f6bbc31b8cf
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_post_sales_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_post_sales_no_eng.
	column time_alloc_post_sales_no_eng
		formatString: ###" hrs/week"
		lineageTag: 55664813-b416-40b3-aa7f-7eff86f7e4d3
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_post_sales_no_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column time_alloc_internal_no_eng.
	column time_alloc_internal_no_eng
		formatString: ###" hrs/week"
		lineageTag: 42200b84-0baa-457e-9cdd-a50014cddd37
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_internal_no_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column 'col.act_tot_dur' =.
	column 'col.act_tot_dur' =
			
			CALCULATE(SUM(users_activities[trueai_dur]))
		lineageTag: 7e3bc9ab-3629-4fe4-b68b-c159d9b4facf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_existing_customer_selling.
	column time_alloc_existing_customer_selling
		dataType: double
		lineageTag: 30ad360e-6bda-4617-bdc3-aaa37e23008d
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_existing_customer_selling]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_existing_customer_selling_eng.
	column time_alloc_existing_customer_selling_eng
		dataType: double
		lineageTag: 58f296f8-07f6-4fca-9724-14fb04402175
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_existing_customer_selling_eng]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_existing_customer_selling_no_eng.
	column time_alloc_existing_customer_selling_no_eng
		lineageTag: b7fddcd5-5d85-494f-a05e-fe5f2735db90
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_existing_customer_selling_no_eng]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition act_time_alloc_summary-153be9d0-81a4-4b11-8377-87a08f40bd95 = calculated
		mode: import
		source = ```
				
				var year = Year(max('cal_end_dates'[date]) ) -1 // get the full year prior
				var filter_date =filter(users_history,if(isblank(users_history[trueai_termination_date]), date(2100,1,1), users_history[trueai_termination_date] ) > users_history[_sys_filt_end_date] && users_history[_sys_filt_end_date] >= date(year,1,1) && users_history[_sys_filt_end_date] < date(year+1,1,1)  )  // get the 1 year filter period
				var tbl_summary = 
				SELECTCOLUMNS(filter_date, "sort", 1, "_sys_docid", users_history[_sys_doc_id],  "_sys_user_id", users_history[_sys_user_id],  "_sys_filter_start_date", users_history[_sys_filt_start_date],    "_sys_filter_end_date", users_history[_sys_filt_end_date],   "full_name", related(users[col.full_name]),"user_role_function", related(users[trueai_user_role_function]),
				"act_tot_count", users_history[col.act_monthly_count] , 
				"act_dur", users_history[col.act_monthly_duration],
				"act_capt_lvl", users_history[ci_act_capt_lvl],
				"act_capt_lvl_conf", users_history[ci_act_capt_lvl_conf],
				"act_capt_lvl_adjustment", users_history[ci_time_alloc_act_capt_lvl_adjustment],
				"prep_adjustment", users_history[ci_time_alloc_prep_adjustment],
				"month_to_week_adjustment", users_history[ci_time_alloc_month_to_week_adjustment],
				"time_alloc_tot",  users_history[ci_time_alloc_tot],
				"time_alloc_tot_eng",  users_history[ci_time_alloc_tot_eng],
				"time_alloc_tot_no_eng",  users_history[ci_time_alloc_tot] - users_history[ci_time_alloc_tot_eng],
				"time_alloc_prospecting", users_history[ci_time_alloc_prospecting],   
				"time_alloc_prospecting_eng", users_history[ci_time_alloc_prospecting_eng], 
				"time_alloc_prospecting_no_eng", users_history[ci_time_alloc_prospecting] - users_history[ci_time_alloc_prospecting_eng],
				"time_alloc_new_logo", users_history[ci_time_alloc_new_logo],   
				"time_alloc_new_logo_eng", users_history[ci_time_alloc_new_logo_eng],
				"time_alloc_new_logo_no_eng", users_history[ci_time_alloc_new_logo] - users_history[ci_time_alloc_new_logo_eng],
				"time_alloc_post_sales", users_history[ci_time_alloc_post_sales],   
				"time_alloc_post_sales_eng", users_history[ci_time_alloc_post_sales_eng],
				"time_alloc_post_sales_no_eng", users_history[ci_time_alloc_post_sales] - users_history[ci_time_alloc_post_sales_eng],
				"time_alloc_existing_customer_selling", users_history[ci_time_alloc_existing_customer_selling],  
				"time_alloc_existing_customer_selling_eng", users_history[ci_time_alloc_existing_customer_selling_eng],
				"time_alloc_existing_customer_selling_no_eng", users_history[ci_time_alloc_existing_customer_selling] - users_history[ci_time_alloc_existing_customer_selling_eng],
				"time_alloc_internal", users_history[ci_time_alloc_internal],  
				"time_alloc_internal_eng", users_history[ci_time_alloc_internal_eng],
				"time_alloc_internal_no_eng", users_history[ci_time_alloc_internal] - users_history[ci_time_alloc_internal_eng],
				"dd", 1
				 )
				return tbl_summary
				
				```

	annotation PBI_Id = f9e1e52527d045d28afc8be85348a79d

