/// Table act_capture_level_summary.
table act_capture_level_summary
	lineageTag: b2717458-96a3-4785-97f7-099181ed5d0d

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.act_capt_act_per_step_avg' = 
			
			var act_count = calculate(Sum(act_capture_level_summary[crm_activity_count]))
			var step_count = calculate(Sum(act_capture_level_summary[steps]))
			var res  = divide(act_count, step_count)
			return res 
			
		formatString: 0
		displayFolder: _acl_scores
		lineageTag: 16207cf0-5e26-48aa-a104-df98fb1f2476

		changedProperty = FormatString

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.act_capt_dur_per_step_avg' = 
			
			var act_count = calculate(Sum(act_capture_level_summary[total_duration]))
			var step_count = calculate(Sum(act_capture_level_summary[steps]))
			
			var res  =  divide(act_count, step_count) / 3600 // convert to hours
			return res 
			
		formatString: 0.0"  hrs"
		displayFolder: _acl_scores
		lineageTag: a40542a2-5ae3-4406-9b52-6a626a8786db

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.act_capt_expected_dur_per_step_avg' = 
			
			var act_count = calculate(Sum(act_capture_level_summary[expected_duration]))
			var step_count = calculate(Sum(act_capture_level_summary[steps]))
			
			var res  =  divide(act_count, step_count) / 3600 // convert to hours
			return res 
			
		formatString: 0.0"  hrs"
		displayFolder: _acl_scores
		lineageTag: d9ee9d7b-1381-44fa-979e-a67f73ac0777

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.act_capt_duration' = 
			
			var act_dur = calculate(Sum(act_capture_level_summary[capped_duration]))
			
			
			var res  =  act_dur / 3600 // convert to hours
			return res 
			
		formatString: 0"  hrs"
		displayFolder: _acl_scores
		lineageTag: 09eba839-9cf4-451b-92e6-039b5c2bda85

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.act_capt_expected_duration' = 
			
			var act_dur = calculate(Sum(act_capture_level_summary[expected_duration]))
			
			
			var res  =  act_dur / 3600 // convert to hours
			return res 
			
		formatString: 0"  hrs"
		displayFolder: _acl_scores
		lineageTag: 24a29e7e-20f0-4791-809e-b832d47a0339

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.act_capture' =
			
			divide(SUM(act_capture_level_summary[capped_duration]),SUM(act_capture_level_summary[expected_duration]))
		formatString: #,0.00
		displayFolder: _acl_scores
		lineageTag: 8e90b6fc-50af-4cda-aa88-8e9ce3d90e83

		changedProperty = FormatString

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.act_capt_duration_weekly_rep_avg' = 
			
			// way to calculate the avg weekly rep time spent on the current "selection"
			var dur = CALCULATE(sum(act_capture_level_summary[capped_duration])) / 3600 // get duration in hours
			var months = CALCULATE(distinctcount(act_capture_level_summary[_sys_filter_start_date])) // up to 4 entries per month per rep so pull distinct per month
			var weeks = CALCULATE(average(act_capture_level_summary[month_to_week_adjustment]), ISBLANK(act_capture_level_summary[capped_duration]) = false) * months // multiply the avg. weeks in a 
			var reps =  [meas.act_capt_applicable_reps]
			var val = dur / weeks/ reps // get the duration per week per rep
			var res =   round(val * 2 , 0) / 2 // round to closest 0.5 and format w/ format string "#.0hrs/week"
			return res
		formatString: #.0" hrs"
		displayFolder: _acl_scores
		lineageTag: e44d402a-28ad-472f-9ffb-4c9c23412f3e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Boolean
	measure 'meas.act_capt_expected_duration_weekly_rep_avg' = 
			
			// way to calculate the avg weekly rep time spent on the current "selection"
			var dur = CALCULATE(sum(act_capture_level_summary[expected_duration])) / 3600 // get duration in hours
			var months = CALCULATE(distinctcount(act_capture_level_summary[_sys_filter_start_date])) // up to 4 entries per month per rep so pull distinct per month
			var weeks = CALCULATE(average(act_capture_level_summary[month_to_week_adjustment]), ISBLANK(act_capture_level_summary[expected_duration]) = false) * months // multiply the avg. weeks in  
			var reps =  [meas.act_capt_applicable_reps]
			var val = dur / weeks/ reps // get the duration per week per rep
			var res =   round(val * 2 , 0) / 2 // round to closest 0.5 and format w/ format string "#.0hrs/week"
			return val
		displayFolder: _acl_scores
		lineageTag: 0b5ebe13-d803-4116-b8de-dd52ee14d8df

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.crm_act_capt_score' =
			
			var crm_capture_level = [meas.act_capture]
			var res  = round(crm_capture_level * 100,0)
			return res
		formatString: 0
		displayFolder: _acl_scores
		lineageTag: 4afafcb3-593b-4adb-8956-99da37a8f1f6

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.crm_act_capt_score_industry_avg' =
			//0.48 * 100
			var _score = CALCULATE(
			    MAX(metadata_reference_values[value]),
			    metadata_reference_values[_sys_doc_id]="acl5"
			)
			
			RETURN
			_score
		formatString: 0
		displayFolder: _acl_scores
		lineageTag: 25caccab-5c62-4871-8096-7c890988147a

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.trueai_act_capt_score' = 
			
			VAR _before = [meas.crm_act_capt_score]
			VAR temp_tbl =
			    CALCULATETABLE(
			        ssr_history,
			        ssr_history[step_name] IN {
			            "Prospecting",
			            "New Logo Selling",
			            "Post-Sales Support",
			            "Existing Customer Selling"
			        }
			    )
			VAR score_res =
			    AVERAGEX(
			        temp_tbl,
			        SWITCH(
			            ssr_history[stkhlds_all_adj_dur_rule],
			            133002, 0.4,
			            133001, 0.7,
			            133003, 0.97,
			            133004, 0.86
			        )
			    )
			VAR _after = ROUND(score_res * 100, 0)
			VAR res = IF(_after < _before, _before, _after)
			RETURN res
			
		formatString: 0
		displayFolder: _acl_scores
		lineageTag: fbbac8e0-05bb-41a5-8e39-2343fc1b4f37

		changedProperty = FormatString

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Percentage
	measure 'meas.trueai_act_capt_score_improvement' =
			
			var trueai_score = ROUND([meas.trueai_act_capt_score],2)
			var crm_score = ROUND([meas.crm_act_capt_score],2)
			var imp = divide(trueai_score - crm_score,  crm_score, 0)
			var res = imp
			return res
		formatString: +#%;-#%;0%
		displayFolder: _acl_scores
		lineageTag: 235e9aad-68ad-45cf-b962-a4412234d120

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.act_capture_adjustment_factor' = divide(1, [meas.act_capture])
		formatString: 0.0
		displayFolder: _acl_scores
		lineageTag: 4bf4da47-0c5e-455f-b690-534812ebe055

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Text
	measure 'meas.act_capt_applicable_reps' = 
			
			/*
			//month by number of month periods
			var periods_tbl = SUMMARIZE(calculatetable(act_capture_level_summary), act_capture_level_summary[_sys_user_id],act_capture_level_summary[_sys_filter_start_date]) // get the total number of periods in the 
			
			// selection group by rep and month
			var reps_tbl = SUMMARIZE(calculatetable(act_capture_level_summary), act_capture_level_summary[_sys_user_id]) // get just the unique names
			var reps =  divide(COUNTROWS(periods_tbl) , COUNTROWS( reps_tbl)) // get the avg number of "active" reps per period */
			var reps = CALCULATE(DISTINCTCOUNT(act_capture_level_summary[_sys_user_id]))
			var res = reps
			return res
			
		formatString: _acl_scores
		lineageTag: 33577b57-cda0-4543-974a-8756bee44e7b

		changedProperty = FormatString

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Decimal
	measure 'meas.act_capt_activity_count' = 
			
			var act_count = CALCULATE(SUM(users_history[ci_time_alloc_tot_dur]), 'cal_end_dates'[date] > date(1900,1,1) && 'cal_end_dates'[date] > date(210,1,1) )-- override the standard date filter 
			var res = act_count
			return res
			
			// act_tot_count --> ci_time_alloc_tot_dur
		formatString: _acl_scores
		displayFolder: 0
		lineageTag: ee680742-49b5-4460-aa06-85524f4fbb59

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Boolean
	measure 'meas.act_capt_lvl_summary_time_alloc_eng' =
			
			CALCULATE(
			    AVERAGE(
			        act_capture_level_summary[time_alloc_eng]       // get the average eng time allocation
			    )
			)
		formatString: #" hrs/week"
		displayFolder: _time_allocation
		lineageTag: 644d9112-46ce-4307-9e3a-b10b5306237a

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Boolean
	measure 'meas.act_capt_lvl_summary_time_alloc_non_eng' =
			
			CALCULATE(
			    AVERAGE(
			        act_capture_level_summary[time_alloc_no_eng]        // get the non eng time alloc
			    )
			)
		formatString: #" hrs/week"
		displayFolder: _time_allocation
		lineageTag: 422619fa-5693-4106-98e7-acc2ef92b223

		annotation PBI_FormatHint = {"isCustom":true}

	/// Purpose: Returns the business metric for this measure.
	/// Logic: Computes the metric from its underlying model references.
	/// Dependencies: See model references.
	/// Context: Evaluated in current filter context unless overridden in DAX.
	/// Output: Whole number
	measure 'meas.no_activities_count' =
			
			var _prospect = SUM(users_history[ci_act_capt_lvl_pi_prospecting_owner_act])            // get prospecting act
			var _new_logo = SUM(users_history[ci_act_capt_lvl_pi_new_logo_owner_act])            // get new logo act
			var _post_sales = SUM(users_history[ci_act_capt_lvl_pi_post_sales_owner_act])            // get post sales support act
			var _existing = SUM(users_history[ci_act_capt_lvl_pi_exist_cust_owner_act])            // get existing customer selling act
			var res = _prospect+_new_logo+_post_sales+_existing
			
			RETURN
			res
		formatString: 0
		lineageTag: b8ec6df0-1df6-41d1-b949-fcb80cb1af48

	/// Column _sys_docid.
	column _sys_docid
		lineageTag: d4dc375b-3742-4a72-8021-282ef1deeb00
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_docid]

		annotation SummarizationSetBy = Automatic

	/// Column _sys_user_id.
	column _sys_user_id
		lineageTag: 54c10149-472b-49e0-bc98-6eff465482a1
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_user_id]

		annotation SummarizationSetBy = Automatic

	/// Column _sys_filter_start_date.
	column _sys_filter_start_date
		formatString: Short Date
		lineageTag: f4fe8b25-e5d5-47dd-9cd9-7ea34bb5a612
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_filter_start_date]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	/// Column full_name.
	column full_name
		lineageTag: 557fe57f-8f4b-4b3d-a10a-2200331b5872
		summarizeBy: none
		isNameInferred
		sourceColumn: [full_name]

		annotation SummarizationSetBy = Automatic

	/// Column user_role_function.
	column user_role_function
		lineageTag: 8d5e3e68-b425-469a-be69-9032ba86a953
		summarizeBy: none
		isNameInferred
		sourceColumn: [user_role_function]

		annotation SummarizationSetBy = Automatic

	/// Column step_id.
	column step_id
		formatString: 0
		lineageTag: e4586870-7037-40aa-ad9c-55d2b4a8b48c
		summarizeBy: sum
		isNameInferred
		sourceColumn: [step_id]

		annotation SummarizationSetBy = Automatic

	/// Column step_name.
	column step_name
		lineageTag: 5205da11-e411-41ad-8982-86db784dcfca
		summarizeBy: none
		isNameInferred
		sourceColumn: [step_name]
		sortByColumn: step_id

		annotation SummarizationSetBy = Automatic

	/// Column crm_activity_count.
	column crm_activity_count
		formatString: 0
		lineageTag: 779a605d-f7de-4267-9b51-953b7963ac23
		summarizeBy: sum
		isNameInferred
		sourceColumn: [crm_activity_count]

		annotation SummarizationSetBy = Automatic

	/// Column steps.
	column steps
		formatString: 0
		lineageTag: 1b44c856-3bf4-4003-a0c8-573812a7111d
		summarizeBy: sum
		isNameInferred
		sourceColumn: [steps]

		annotation SummarizationSetBy = Automatic

	/// Column total_duration.
	column total_duration
		formatString: #,0
		lineageTag: 13f8154c-e727-45e5-b6a4-308dd878c4de
		summarizeBy: sum
		isNameInferred
		sourceColumn: [total_duration]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Column expected_duration.
	column expected_duration
		formatString: #,0
		lineageTag: f240be9c-14e0-4538-81d6-c41f5da6f591
		summarizeBy: sum
		sourceColumn: [expect_duration]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Column capped_duration.
	column capped_duration
		formatString: #,0
		lineageTag: 709aafaa-8f1c-4039-8526-dbda8caf13b8
		summarizeBy: sum
		isNameInferred
		sourceColumn: [capped_duration]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Column raw_ratio.
	column raw_ratio
		lineageTag: 5d06fe7f-1533-4847-b8f9-68b8f34e5b82
		summarizeBy: sum
		isNameInferred
		sourceColumn: [raw_ratio]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column capped_ratio.
	column capped_ratio
		lineageTag: 096e607b-77c8-4671-9837-43d307a11ba1
		summarizeBy: sum
		isNameInferred
		sourceColumn: [capped_ratio]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column month_to_week_adjustment.
	column month_to_week_adjustment
		lineageTag: 299c10e1-f3c2-46af-954b-4d402512e379
		summarizeBy: sum
		isNameInferred
		sourceColumn: [month_to_week_adjustment]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column act_capture_level.
	column act_capture_level
		lineageTag: 9ce2f361-9ef8-4ca8-bc91-aaa2b6ea15e5
		summarizeBy: sum
		isNameInferred
		sourceColumn: [act_capture_level]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column _sys_filter_end_date.
	column _sys_filter_end_date
		formatString: Short Date
		lineageTag: 7e414115-5480-4760-a588-77f304814187
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_filter_end_date]

		variation Variation
			isDefault
			relationship: 4ff2a63f-d851-4a9b-88d8-b7572d7cc292
			defaultHierarchy: LocalDateTable_6abe9e27-1c5a-4473-94ac-6a8060308a51.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	/// Column sort.
	column sort
		formatString: 0
		lineageTag: f74fc398-bff8-47c6-9b04-6bac24951441
		summarizeBy: sum
		isNameInferred
		sourceColumn: [sort]

		annotation SummarizationSetBy = Automatic

	/// Column time_alloc.
	column time_alloc
		lineageTag: 62349f31-2de6-4533-a5fe-a8b055fed5de
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_eng.
	column time_alloc_eng
		dataType: double
		lineageTag: a96d2a1e-cf60-492e-b381-989af87fe4f1
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column time_alloc_no_eng.
	column time_alloc_no_eng
		formatString: #" hrs/week"
		lineageTag: 2f4c9d9d-c1a8-422d-b5a2-9662b9df32cd
		summarizeBy: sum
		isNameInferred
		sourceColumn: [time_alloc_no_eng]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column act_capture_level_conf.
	column act_capture_level_conf
		formatString: #,0.00
		lineageTag: 3b64489a-f816-4d45-978c-462ec32d7b09
		summarizeBy: sum
		isNameInferred
		sourceColumn: [act_capture_level_conf]

		annotation SummarizationSetBy = Automatic

	partition act_capture_level_summary-c8f9c099-3686-4e53-9739-1daed7e59936 = calculated
		mode: import
		source = ```
				
				var year = Year(max('cal_end_dates'[date]) ) -1 // get the full year prior
				var filter_date =filter(users_history, users_history[_sys_filt_end_date] >= date(year,1,1) && users_history[_sys_filt_end_date] < date(year+1,1,1)  )  // get teh 1 year filter period
				var filt_prospecting = filter(filter_date,   users_history[ci_act_capt_lvl_pi_prospecting_expect_owner_dur] > 500 ) // get items that prospecting
				var filt_new_logo = filter(filter_date,   users_history[ci_act_capt_lvl_pi_new_logo_expected_owner_dur] > 500 ) // get items that new_logo
				var filt_post_sales = filter(filter_date,   users_history[ci_act_capt_lvl_pi_post_sales_expect_owner_dur] > 500 ) // get items that filt_post_selling
				var filt_existing_cust = filter(filter_date,   users_history[ci_act_capt_lvl_pi_exist_cust_expect_owner_dur] > 500 ) // get items that filt_existing customer selling
				var filt = filter_date
				var tbl_summary = UNION(
				
				 SELECTCOLUMNS(filt_prospecting, "sort", 1, "_sys_docid", users_history[_sys_doc_id],  "_sys_user_id", users_history[_sys_user_id],  "_sys_filter_start_date", users_history[_sys_filt_start_date],    "_sys_filter_end_date", users_history[_sys_filt_end_date],   "full_name", related(users[col.full_name]),"user_role_function", related(users[trueai_user_role_function]),
				 "step_id", 3, "step_name", "Prospecting", "crm_activity_count",  users_history[ci_act_capt_lvl_pi_prospecting_owner_act] , "steps", users_history[ci_act_capt_lvl_pi_prospecting_steps],
				 "time_alloc", users_history[ci_time_alloc_prospecting],   
				"time_alloc_eng", users_history[ci_time_alloc_prospecting_eng], 
				"time_alloc_no_eng", users_history[ci_time_alloc_prospecting] - users_history[ci_time_alloc_prospecting_eng],
				 "total_duration" , users_history[ci_act_capt_lvl_pi_prospecting_owner_dur],"expect_duration" , users_history[ci_act_capt_lvl_pi_prospecting_expect_owner_dur], 
				 "capped_duration" , If(users_history[ci_act_capt_lvl_pi_prospecting_owner_dur] >  users_history[ci_act_capt_lvl_pi_prospecting_expect_owner_dur] ,  users_history[ci_act_capt_lvl_pi_prospecting_expect_owner_dur] * 0.95,users_history[ci_act_capt_lvl_pi_prospecting_owner_dur]) ,
				  "month_to_week_adjustment", users_history[ci_time_alloc_month_to_week_adjustment],
				  "act_capture_level", users_history[ci_act_capt_lvl],
				    "act_capture_level_conf", users_history[ci_act_capt_lvl_conf],
				 "raw_ratio", divide(users_history[ci_act_capt_lvl_pi_prospecting_owner_dur], users_history[ci_act_capt_lvl_pi_prospecting_expect_owner_dur]),
				  "capped_ratio",  if(divide(users_history[ci_act_capt_lvl_pi_prospecting_owner_dur], users_history[ci_act_capt_lvl_pi_prospecting_expect_owner_dur]) > .95, .95,divide(users_history[ci_act_capt_lvl_pi_prospecting_owner_dur], users_history[ci_act_capt_lvl_pi_prospecting_expect_owner_dur]))  // cap @ 95%
				 
				 ), // prospecting
				
				 SELECTCOLUMNS(filt_new_logo, "sort", 2,  "_sys_docid", users_history[_sys_doc_id],  "_sys_user_id", users_history[_sys_user_id],  "_sys_filter_start_date", users_history[_sys_filt_start_date],  "_sys_filter_end_date", users_history[_sys_filt_end_date], "full_name", related(users[col.full_name]),"user_role_function", related(users[trueai_user_role_function]) ,
				 "step_id", 4,"step_name", "New Logo Selling", "crm_activity_count", users_history[ci_act_capt_lvl_pi_new_logo_owner_act] , "steps", users_history[ci_act_capt_lvl_pi_new_logo_steps],
				 "time_alloc", users_history[ci_time_alloc_new_logo],   
				"time_alloc_eng", users_history[ci_time_alloc_new_logo_eng], 
				"time_alloc_no_eng", users_history[ci_time_alloc_new_logo] - users_history[ci_time_alloc_new_logo_eng],
				 "total_duration" , users_history[ci_act_capt_lvl_pi_new_logo_owner_dur],"expect_duration" , users_history[ci_act_capt_lvl_pi_new_logo_expected_owner_dur],
				 "capped_duration" , If(users_history[ci_act_capt_lvl_pi_new_logo_owner_dur] >  users_history[ci_act_capt_lvl_pi_new_logo_expected_owner_dur] ,  users_history[ci_act_capt_lvl_pi_new_logo_expected_owner_dur]  * 0.95,users_history[ci_act_capt_lvl_pi_new_logo_owner_dur]) ,
				 "month_to_week_adjustment", users_history[ci_time_alloc_month_to_week_adjustment],
				 "act_capture_level", users_history[ci_act_capt_lvl],
				 "act_capture_level_conf", users_history[ci_act_capt_lvl_conf],
				 "raw_ratio", divide(users_history[ci_act_capt_lvl_pi_new_logo_owner_dur], users_history[ci_act_capt_lvl_pi_new_logo_expected_owner_dur]),
				 "capped_ratio", if(divide(users_history[ci_act_capt_lvl_pi_new_logo_owner_dur], users_history[ci_act_capt_lvl_pi_new_logo_expected_owner_dur])> .95, .95,divide(users_history[ci_act_capt_lvl_pi_new_logo_owner_dur], users_history[ci_act_capt_lvl_pi_new_logo_expected_owner_dur]))  // cap @ 95%
				 ), // new logo selling
				
				  SELECTCOLUMNS(filt_post_sales, "sort", 3,  "_sys_docid", users_history[_sys_doc_id],  "_sys_user_id", users_history[_sys_user_id],  "_sys_filter_start_date", users_history[_sys_filt_start_date],  "_sys_filter_end_date", users_history[_sys_filt_end_date], "full_name", related(users[col.full_name]),"user_role_function", related(users[trueai_user_role_function]) ,
				  "step_id", 5,"step_name", "Post-Sales Support", "crm_activity_count", users_history[ci_act_capt_lvl_pi_post_sales_owner_act], "steps", users_history[ci_act_capt_lvl_pi_post_sales_steps],
				 "time_alloc", users_history[ci_time_alloc_post_sales],   
				"time_alloc_eng", users_history[ci_time_alloc_post_sales_eng], 
				"time_alloc_no_eng", users_history[ci_time_alloc_post_sales] - users_history[ci_time_alloc_post_sales_eng],
				 "total_duration" , users_history[ci_act_capt_lvl_pi_post_sales_owner_dur],"expect_duration" , users_history[ci_act_capt_lvl_pi_post_sales_expect_owner_dur],
				 "capped_duration" , If(users_history[ci_act_capt_lvl_pi_post_sales_owner_dur] >  users_history[ci_act_capt_lvl_pi_post_sales_expect_owner_dur] ,  users_history[ci_act_capt_lvl_pi_post_sales_expect_owner_dur]  * 0.95,users_history[ci_act_capt_lvl_pi_post_sales_owner_dur]) ,
				 "month_to_week_adjustment", users_history[ci_time_alloc_month_to_week_adjustment],
				 "act_capture_level", users_history[ci_act_capt_lvl],
				     "act_capture_level_conf", users_history[ci_act_capt_lvl_conf],
				 "raw_ratio", divide(users_history[ci_act_capt_lvl_pi_post_sales_owner_dur], users_history[ci_act_capt_lvl_pi_post_sales_expect_owner_dur]),
				 "capped_ratio", if(divide(users_history[ci_act_capt_lvl_pi_post_sales_owner_dur], users_history[ci_act_capt_lvl_pi_post_sales_expect_owner_dur])> .95, .95,divide(users_history[ci_act_capt_lvl_pi_post_sales_owner_dur], users_history[ci_act_capt_lvl_pi_post_sales_expect_owner_dur]))  // cap @ 95%
				 ), // post_sales
				
				 SELECTCOLUMNS(filt_existing_cust, "sort", 4,  "_sys_docid", users_history[_sys_doc_id],  "_sys_user_id", users_history[_sys_user_id],  "_sys_filter_start_date", users_history[_sys_filt_start_date],  "_sys_filter_end_date", users_history[_sys_filt_end_date], "full_name", related(users[col.full_name]),"user_role_function", related(users[trueai_user_role_function]) ,
				 "step_id", 6,"step_name", "Existing Customer Selling", "crm_activity_count", users_history[ci_act_capt_lvl_pi_exist_cust_owner_act] , "steps", users_history[ci_act_capt_lvl_pi_exist_cust_steps],
				 "time_alloc", users_history[ci_time_alloc_existing_customer_selling],   
				"time_alloc_eng", users_history[ci_time_alloc_existing_customer_selling_eng], 
				"time_alloc_no_eng", users_history[ci_time_alloc_existing_customer_selling] - users_history[ci_time_alloc_existing_customer_selling_eng],
				 "total_duration" , users_history[ci_act_capt_lvl_pi_exist_cust_owner_dur],"expect_duration" , users_history[ci_act_capt_lvl_pi_exist_cust_expect_owner_dur],
				 "capped_duration" , If(users_history[ci_act_capt_lvl_pi_exist_cust_owner_dur] >  users_history[ci_act_capt_lvl_pi_exist_cust_expect_owner_dur] ,  users_history[ci_act_capt_lvl_pi_exist_cust_expect_owner_dur]  * 0.95,users_history[ci_act_capt_lvl_pi_exist_cust_owner_dur]) ,
				  "month_to_week_adjustment", users_history[ci_time_alloc_month_to_week_adjustment],
				  "act_capture_level", users_history[ci_act_capt_lvl],
				      "act_capture_level_conf", users_history[ci_act_capt_lvl_conf],
				 "raw_ratio", divide(users_history[ci_act_capt_lvl_pi_exist_cust_owner_dur], users_history[ci_act_capt_lvl_pi_exist_cust_expect_owner_dur]),
				 "capped_ratio", if(divide(users_history[ci_act_capt_lvl_pi_exist_cust_owner_dur], users_history[ci_act_capt_lvl_pi_exist_cust_expect_owner_dur])> .95, .95,divide(users_history[ci_act_capt_lvl_pi_exist_cust_owner_dur], users_history[ci_act_capt_lvl_pi_exist_cust_expect_owner_dur]))  // cap @ 95% // Existing Customer Selling
				
				)
				)
				
				return tbl_summary
				
				```

	annotation PBI_Id = 6f7bcfb074fe4d7aaea51c3dd4d3a3d1

