/// Table ai_conf_skills_summary.
table ai_conf_skills_summary
	lineageTag: 8366b68f-eb81-4009-b4c5-46dae1a9cb66

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: 0
	measure 'meas.skills_reps' =
			
			var cnt = CALCULATE(DISTINCTCOUNT(ai_conf_skills_summary[user_id]),ai_conf_skills_summary[is_applicable]= true)
			var res = cnt
			return res
		formatString: 0
		displayFolder: _skills_analysis
		lineageTag: 154ab5fb-48e4-4d5e-ad78-dccd191b6d26

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: 0
	measure 'meas.skills_reps_with_scores' =
			
			var cnt = CALCULATE(DISTINCTCOUNT(ai_conf_skills_summary[user_id]),ai_conf_skills_summary[is_applicable]= true && Isblank(ai_conf_skills_summary[skill_value]) = false)
			var res = cnt
			return res
		formatString: 0
		displayFolder: _skills_analysis
		lineageTag: 64cb0b1e-ff49-4890-b689-a20a5541df2b

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: Measures: [meas.skills_reps_with_scores], [meas.skills_reps].
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: #,##0 %
	measure 'meas.skills_reps_with_scores_ratio' = divide([meas.skills_reps_with_scores], [meas.skills_reps])
		formatString: #,##0 %
		displayFolder: _skills_analysis
		lineageTag: 49238757-511c-4344-9f64-e365c4652f62

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: Not specified.
	measure 'meas.skills_reps_with_scores_ae' =
			
			var cnt = CALCULATE(DISTINCTCOUNT(ai_conf_skills_summary[user_id]),ai_conf_skills_summary[is_applicable]= true && ai_conf_skills_summary[user_role_function] = "AE" && Isblank(ai_conf_skills_summary[skill_value]) = false)
			var res = cnt
			return res
		displayFolder: _skills_analysis
		lineageTag: d00b3c0c-40a0-42f2-a50e-7f58f185ed2d

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: Not specified.
	measure 'meas.skills_reps_with_scores_am' =
			
			var cnt = CALCULATE(DISTINCTCOUNT(ai_conf_skills_summary[user_id]),ai_conf_skills_summary[is_applicable]= true && ai_conf_skills_summary[user_role_function] = "AM" && Isblank(ai_conf_skills_summary[skill_value]) = false)
			var res = cnt
			return res
		displayFolder: _skills_analysis
		lineageTag: 8f3e9f70-218f-4843-b48e-dd8c18cde905

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: Not specified.
	measure 'meas.skills_reps_with_scores_sdr' =
			
			var cnt = CALCULATE(DISTINCTCOUNT(ai_conf_skills_summary[user_id]),ai_conf_skills_summary[is_applicable]= true && ai_conf_skills_summary[user_role_function] = "SDR" && Isblank(ai_conf_skills_summary[skill_value]) = false)
			var res = cnt
			return res
		displayFolder: _skills_analysis
		lineageTag: 6d5fe4b3-0f8a-487f-bcc7-a753e42f0a0a

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: Measures: [meas.skills_reps_with_scores_ae], [meas.skills_reps_ae].
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: #,##0 %
	measure 'meas.skills_reps_with_scores_ae_ratio' = divide([meas.skills_reps_with_scores_ae], [meas.skills_reps_ae])
		formatString: #,##0 %
		displayFolder: _skills_analysis
		lineageTag: 668d362a-d7e3-430d-8867-ad31b3b681b4

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: Measures: [meas.skills_reps_with_scores_am], [meas.skills_reps_am].
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: #,##0 %
	measure 'meas.skills_reps_with_scores_am_ratio' = divide([meas.skills_reps_with_scores_am], [meas.skills_reps_am])
		formatString: #,##0 %
		displayFolder: _skills_analysis
		lineageTag: 5c94f6ed-4983-4678-863e-b985f9b4cb02

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: Measures: [meas.skills_reps_with_scores_sdr], [meas.skills_reps_sdr].
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: #,##0 %
	measure 'meas.skills_reps_with_scores_sdr_ratio' = divide([meas.skills_reps_with_scores_sdr], [meas.skills_reps_sdr])
		formatString: #,##0 %
		displayFolder: _skills_analysis
		lineageTag: 17ed8911-46ec-4ec9-adb1-4d608125f793

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: #,##0 %
	measure 'meas.skills_reps_avg_confidence' =
			
			var cnt = CALCULATE(AVERAGE(ai_conf_skills_summary[skill_confidence]),ai_conf_skills_summary[is_applicable]= true && ai_conf_skills_summary[skill_confidence] <> 0)
			var res = cnt
			return res
		formatString: #,##0 %
		displayFolder: _skills_analysis
		lineageTag: e9183b16-608c-47e8-bc69-c50dc426301c

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: 0
	measure 'meas.skills_score' =
			
			var res = ai_conf_skills_summary[meas.skills_reps_avg_confidence] * 100
			return res
		formatString: 0
		displayFolder: _skills_analysis
		lineageTag: af4590d2-d509-4f80-b59e-27c5e9b5d673

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: VAR blocks define intermediate values (score, res) used later in the expression. Dependencies: Columns: ai_conf_skills_summary[meas.skills_score].
	/// Dynamic Behavior: Uses IF for conditional branching.
	/// Format/Type: Not specified.
	measure 'meas.skills_score_text' = ```
			
			var score = ai_conf_skills_summary[meas.skills_score]
			var res = If (score >= 95, "Excellent", if(score >= 85,  "Great",If(score >= 75, "Good",If(score >= 50, "Fair", "Limited" ))))
			return  res 
			```
		displayFolder: _skills_analysis
		lineageTag: 63c7c775-e60f-4f04-b029-ec93d854a252

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: 0
	measure 'meas.skills_reps_ae' =
			
			var cnt = CALCULATE(DISTINCTCOUNT(ai_conf_skills_summary[user_id]),ai_conf_skills_summary[is_applicable]= true && ai_conf_skills_summary[user_role_function] = "AE")
			var res = cnt
			return res
		formatString: 0
		displayFolder: _skills_analysis
		lineageTag: 24e61aa4-cd45-425c-acc4-243126e7211c

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: 0
	measure 'meas.skills_reps_am' =
			
			var cnt = CALCULATE(DISTINCTCOUNT(ai_conf_skills_summary[user_id]),ai_conf_skills_summary[is_applicable]= true && ai_conf_skills_summary[user_role_function] = "AM")
			var res = cnt
			return res
		formatString: 0
		displayFolder: _skills_analysis
		lineageTag: ebcc592a-d4c5-4532-992a-244a19cec666

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: 0
	measure 'meas.skills_reps_sdr' =
			
			var cnt = CALCULATE(DISTINCTCOUNT(ai_conf_skills_summary[user_id]),ai_conf_skills_summary[is_applicable]= true && ai_conf_skills_summary[user_role_function] = "SDR")
			var res = cnt
			return res
		formatString: 0
		displayFolder: _skills_analysis
		lineageTag: 6d5819e0-7f6f-4b87-8462-1bd32318c431

	/// Column sort.
	column sort
		formatString: 0
		lineageTag: 53f21e8a-aef1-4821-9ddb-08fe9de8a4b9
		summarizeBy: sum
		isNameInferred
		sourceColumn: [sort]

		annotation SummarizationSetBy = Automatic

	/// Column user_id.
	column user_id
		lineageTag: 8d4dea27-b90b-47cb-824b-4481343239ea
		summarizeBy: none
		isNameInferred
		sourceColumn: [user_id]

		annotation SummarizationSetBy = Automatic

	/// Column filter_start_date.
	column filter_start_date
		formatString: Short Date
		lineageTag: ec675f04-9fba-41d3-8771-cb8d12c7e71f
		summarizeBy: none
		isNameInferred
		sourceColumn: [filter_start_date]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	/// Column skill.
	column skill
		lineageTag: 0f999199-4312-4ef6-89a3-65ffbb9e9f31
		summarizeBy: none
		isNameInferred
		sourceColumn: [skill]

		annotation SummarizationSetBy = Automatic

	/// Column user_role_function.
	column user_role_function
		lineageTag: 55ebf4eb-8f7a-410c-8de4-8d005d351d5f
		summarizeBy: none
		isNameInferred
		sourceColumn: [user_role_function]

		annotation SummarizationSetBy = Automatic

	/// Column user_full_name.
	column user_full_name
		lineageTag: 0d8af7fe-7a7f-46e4-b239-401f148f7436
		summarizeBy: none
		isNameInferred
		sourceColumn: [user_full_name]

		annotation SummarizationSetBy = Automatic

	/// Column skill_value.
	column skill_value
		lineageTag: 8e4d6911-e2ab-4cae-a13a-3d46b5729b40
		summarizeBy: none
		isNameInferred
		sourceColumn: [skill_value]

		annotation SummarizationSetBy = Automatic

	/// Column skill_confidence.
	column skill_confidence
		lineageTag: 99ffa2e2-cddd-49c4-ae97-2b34b9f58d18
		summarizeBy: none
		isNameInferred
		sourceColumn: [skill_confidence]

		annotation SummarizationSetBy = Automatic

	/// Column is_applicable.
	column is_applicable
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 085f18b5-b831-4f81-893e-9a570763e985
		summarizeBy: none
		isNameInferred
		sourceColumn: [is_applicable]

		annotation SummarizationSetBy = Automatic

	partition ai_conf_skills_summary-51f64804-2c88-4d21-a649-b1823d35e592 = calculated
		mode: import
		source = ```
				
				UNION(
				    SELECTCOLUMNS(
				        FILTER(users_history, users_history[trueai_user_role_function] IN {"AE","AM","SDR"}),
				        "sort", 1,
				        "user_id", users_history[_sys_user_id],
				        "filter_start_date", users_history[_sys_filt_start_date],
				        "skill", "Work Effort",
				        "user_role_function", users_history[trueai_user_role_function],
				        "user_full_name", RELATED(users[col.full_name]),
				        "skill_value", users_history[ci_sb_work_effort_num],
				        "skill_confidence", users_history[ci_sb_work_effort_conf],
				        "is_applicable", TRUE()
				    ),
				
				    SELECTCOLUMNS(
				        FILTER(users_history, users_history[trueai_user_role_function] IN {"AE","AM","SDR"}),
				        "sort", 2,
				        "user_id", users_history[_sys_user_id],
				        "filter_start_date", users_history[_sys_filt_start_date],
				        "skill", "Engagement Ability",
				        "user_role_function", users_history[trueai_user_role_function],
				        "user_full_name", RELATED(users[col.full_name]),
				        "skill_value", users_history[ci_sb_engmt_ability_num],
				        "skill_confidence", users_history[ci_sb_engmt_ability_conf],
				        "is_applicable", TRUE()
				    ),
				
				    SELECTCOLUMNS(
				        FILTER(users_history, users_history[trueai_user_role_function] IN {"AE","AM","SDR"}),
				        "sort", 3,
				        "user_id", users_history[_sys_user_id],
				        "filter_start_date", users_history[_sys_filt_start_date],
				        "skill", "Discovery Skills",
				        "user_role_function", users_history[trueai_user_role_function],
				        "user_full_name", RELATED(users[col.full_name]),
				        "skill_value", users_history[ci_sb_discov_skills_num],
				        "skill_confidence", users_history[ci_sb_discov_skills_conf],
				        "is_applicable", TRUE()
				    ),
				
				    SELECTCOLUMNS(
				        FILTER(users_history, users_history[trueai_user_role_function] IN {"AE","AM","SDR"}),
				        "sort", 4,
				        "user_id", users_history[_sys_user_id],
				        "filter_start_date", users_history[_sys_filt_start_date],
				        "skill", "Closing Ability",
				        "user_role_function", users_history[trueai_user_role_function],
				        "user_full_name", RELATED(users[col.full_name]),
				        "skill_value", users_history[ci_sb_closing_ability_num],
				        "skill_confidence", IF(users_history[trueai_user_role_function] = "SDR", BLANK(), users_history[ci_sb_closing_ability_conf]),
				        "is_applicable", TRUE()
				    ),
				
				    SELECTCOLUMNS(
				        FILTER(users_history, users_history[trueai_user_role_function] IN {"AE","AM","SDR"}),
				        "sort", 5,
				        "user_id", users_history[_sys_user_id],
				        "filter_start_date", users_history[_sys_filt_start_date],
				        "skill", "Deal Maximizing",
				        "user_role_function", users_history[trueai_user_role_function],
				        "user_full_name", RELATED(users[col.full_name]),
				        "skill_value", users_history[ci_sb_deal_maxing_num],
				        "skill_confidence", IF(users_history[trueai_user_role_function] = "SDR", BLANK(), users_history[ci_sb_deal_maxing_conf]),
				        "is_applicable", TRUE()
				    )
				)
				
				
				
				
				```

	annotation PBI_Id = 1de40001a073401e9bafcc118fb9d4ff

