table ai_conf_pred_qual_summary
	lineageTag: 0d21c45d-579a-4b2f-8d78-9164865c4643

	measure 'meas.ai_conf_overall_score' = ```
			
			var scr =  (ai_conf_pred_qual_summary[meas.pred_qual_trueai_score] + 'ai_conf_nlp_summary'[meas.nlp_score])/2
			 
			 //+ ai_conf_skills_summary[meas.skills_score]) / 3 // simple avg
			var res = scr
			return res 
			
			```
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: cb94e22d-e69e-420a-9626-b712c33e1a9f

	measure 'meas.ai_conf_overall_score_instry_avg' =
			//87
			var _score = CALCULATE(
			    MAX(metadata_reference_values[value]),
			    metadata_reference_values[_sys_doc_id]="aipred6"
			)
			
			RETURN
			_score
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 7616300d-cae6-467a-8352-84608e038164

	measure 'meas.ai_conf_overall_score_text' = ```
			
			var score = ai_conf_pred_qual_summary[meas.ai_conf_overall_score]
			var res = If (score >= 95, "Excellent", if(score >= 85,  "Great",If(score >= 75, "Good",If(score >= 50, "Fair", "Limited" ))))
			return  res 
			```
		displayFolder: _ai_scores
		lineageTag: 39b4e86c-460e-4a33-9eb4-a5bf45f38f7b

	measure 'meas.ai_conf_score_text' = ```
			
			var score = ai_conf_pred_qual_summary[meas.ai_conf_overall_score]
			var res = If (score >= 95, "Excellent", if(score >= 85,  "Great",If(score >= 75, "Good",If(score >= 50, "Fair", "Limited" ))))
			return  res 
			```
		displayFolder: _ai_scores
		lineageTag: 915fade2-d8df-4076-b918-0739d09e5eaa

	measure 'meas.pred_qual_score_text' = ```
			
			var score = ai_conf_pred_qual_summary[meas.pred_qual_trueai_score]
			var res = If (score >= 95, "Excellent", if(score >= 85,  "Great",If(score >= 75, "Good",If(score >= 50, "Fair", "Limited" ))))
			return  res 
			```
		displayFolder: _ai_scores
		lineageTag: 72f176ba-aefb-4f5e-a69c-aa67a8b54ba1

	measure 'meas.pred_qual_trueai_score' =
			
			AVERAGE(ai_conf_pred_qual_summary[pred_qual_score]) * 100
		formatString: 0
		displayFolder: _ai_scores
		lineageTag: 7483542d-1a68-4c60-a713-ed796df5673b

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	column _sys_docid
		lineageTag: 6e3f0a05-b2ad-49d8-9339-eb397adde317
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_docid]

		annotation SummarizationSetBy = Automatic

	column _sys_coid
		lineageTag: cc4dcd31-18e6-43ae-8ef1-e5ae6c4765f0
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_coid]

		annotation SummarizationSetBy = Automatic

	column _sys_filter_start_date
		formatString: Short Date
		lineageTag: fbc208fe-89c0-446d-a869-92196471f9cd
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_filter_start_date]

		variation Variation
			isDefault
			relationship: 05fcd0e4-9077-4c16-b813-4ea87577c8ef
			defaultHierarchy: LocalDateTable_edf4a222-9ae1-4915-9173-7f1bedd1a2a9.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column _sys_process_date
		formatString: Short Date
		lineageTag: 0c904573-53c1-4215-bd16-29891e189e01
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_process_date]

		variation Variation
			isDefault
			relationship: 1f7ed59a-1eb4-4bea-b97b-285676531a85
			defaultHierarchy: LocalDateTable_3035c574-0a99-49e2-a887-8c086e67dd9f.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column step_id
		formatString: 0
		lineageTag: d32bc27f-29f0-4644-bd48-db50f838e141
		summarizeBy: sum
		isNameInferred
		sourceColumn: [step_id]

		annotation SummarizationSetBy = Automatic

	column step_name
		lineageTag: 3eaf6b11-d23e-4bb0-ad11-474f063b0bee
		summarizeBy: none
		isNameInferred
		sourceColumn: [step_name]
		sortByColumn: step_id

		annotation SummarizationSetBy = Automatic

	column r2
		lineageTag: 7ef46739-a0d6-4542-9346-e0c39ff4128f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [r2]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column auc
		lineageTag: 515df6c4-2b41-4804-af2a-0b47c51951ea
		summarizeBy: sum
		isNameInferred
		sourceColumn: [auc]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pred_qual_score
		lineageTag: d526a8e2-424b-445b-9710-0907ceafef87
		summarizeBy: sum
		isNameInferred
		sourceColumn: [pred_qual_score]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column validation_score
		formatString: #,0.00
		lineageTag: 352a764c-b7cf-4f92-8a4e-78b4d9d04f5b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [validation_score]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column training_score
		lineageTag: 88c82b83-9dee-4400-bf11-6eb9cbbd00cd
		summarizeBy: sum
		isNameInferred
		sourceColumn: [training_score]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ai_conf_pred_qual_summary-2f009e47-b469-4a53-b115-aff2a4a23cad = calculated
		mode: import
		source = ```
				
				UNION(
				
				 SELECTCOLUMNS(TopN(1,companies_history, companies_history[_sys_processed_as_of],DESC ), "_sys_docid", companies_history[_sys_doc_id],  "_sys_coid", companies_history[_sys_co_id],  "_sys_filter_start_date", companies_history[_sys_filt_start_date]  , "_sys_process_date", companies_history[_sys_processed_as_of] ,"step_id", 3, "step_name", "Prospecting", 
				 "validation_score", companies_history[di_success_prob_validation_score],
				 "training_score", companies_history[di_success_prob_training_score],
				   
				  "r2",companies_history[di_pred_prospecting_r2], "auc", companies_history[di_pred_prospecting_auc], "pred_qual_score", (if(companies_history[di_pred_prospecting_r2] < 0,0 , companies_history[di_pred_prospecting_r2]) +  companies_history[di_pred_prospecting_auc]) / 2 ), // prospecting
				
				 SELECTCOLUMNS(TopN(1,companies_history, companies_history[_sys_processed_as_of],DESC ), "_sys_docid", companies_history[_sys_doc_id],  "_sys_coid", companies_history[_sys_co_id],  "_sys_filter_start_date", companies_history[_sys_filt_start_date]  , "_sys_process_date", companies_history[_sys_processed_as_of] ,"step_id", 4, "step_name", "New Logo Selling", "validation_score", companies_history[di_success_prob_validation_score],
				"training_score", companies_history[di_success_prob_training_score],
				   "r2",companies_history[di_pred_new_logo_r2], "auc", companies_history[di_pred_new_logo_auc], "pred_qual_score", (if(companies_history[di_pred_new_logo_r2] < 0,0 , companies_history[di_pred_new_logo_r2]) +  companies_history[di_pred_new_logo_auc]) / 2  ), // new logo 
				
				 SELECTCOLUMNS(TopN(1,companies_history, companies_history[_sys_processed_as_of],DESC ), 
				    "_sys_docid", companies_history[_sys_doc_id],  
				    "_sys_coid", companies_history[_sys_co_id],  
				    "_sys_filter_start_date", companies_history[_sys_filt_start_date]  , 
				    "_sys_process_date", companies_history[_sys_processed_as_of] ,
				    "step_id", 5, 
				    "step_name", "Post-Sales Support",  
				    "validation_score", companies_history[di_success_prob_validation_score], 
				    "training_score", companies_history[di_success_prob_training_score],
				    "r2",companies_history[di_pred_post_sales_r2], 
				    "auc", companies_history[di_pred_post_sales_auc], 
				    "pred_qual_score", (if(companies_history[di_pred_post_sales_r2] < 0,0 , companies_history[di_pred_post_sales_r2]) +  companies_history[di_pred_post_sales_auc]) / 2 ), // post_sales
				
				 SELECTCOLUMNS(TopN(1,companies_history, companies_history[_sys_processed_as_of],DESC ), "_sys_docid", companies_history[_sys_doc_id],  "_sys_coid", companies_history[_sys_co_id],  "_sys_filter_start_date", companies_history[_sys_filt_start_date]  , "_sys_process_date", companies_history[_sys_processed_as_of] ,"step_id", 6, "step_name", "Existing Customer Selling",
				  "validation_score", companies_history[di_success_prob_validation_score], 
				  "training_score", companies_history[di_success_prob_training_score],
				  "r2",companies_history[di_pred_existing_customer_selling_r2], "auc", companies_history[di_pred_existing_customer_selling_auc], "pred_qual_score", (if(companies_history[di_pred_existing_customer_selling_r2] < 0,0 , companies_history[di_pred_existing_customer_selling_r2]) +  companies_history[di_pred_existing_customer_selling_auc]) / 2 ) // existing customer selling 
				)
				```

	annotation PBI_Id = 31086e1efb594e3d8ffb91217c3ad15d

