/// Table cal_end_dates.
table cal_end_dates
	lineageTag: 0c87fa54-b3b7-47c2-9154-a95fcfb4b586

	/// Measure meas.filter_string.
	measure 'meas.filter_string' = ```
			
			
			//var filter_start_table = topn(1, filter(cal_end_dates,[Date])) // "01/01/2010"
			//var filter_start_val = ISFILTERED(cal_end_dates[Date]) //  min(filter_start_table[Date])
			var max_filters =3
			var date_str =  "Date: " & Min('cal_end_dates'[Date])  & " - " &  Max('cal_end_dates'[Date])
			
			var user_role_str = IF ( 
			    ISFILTERED ( users[trueai_user_role]), 
			    VAR ___f = FILTERS ( users[trueai_user_role] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( max_filters, ___f, users[trueai_user_role] )
			    VAR ___d = CONCATENATEX ( ___t, users[trueai_user_role], ", " )
			    VAR ___x = "Role: " & ___d & IF(___r > max_filters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x , "Role: All"
			)
			
			var group_str = IF ( 
			    ISFILTERED ( users[trueai_group]), 
			    VAR ___f = FILTERS ( users[trueai_group] ) 
			    VAR ___r = COUNTROWS ( ___f ) 
			    VAR ___t = TOPN ( max_filters, ___f, users[trueai_group] )
			    VAR ___d = CONCATENATEX ( ___t, users[trueai_group], ", " )
			    VAR ___x = "Group: " & ___d & IF(___r > max_filters, ", ... [" & ___r & " items selected]") & " " 
			    RETURN ___x , "Group: All"
			)
			
			
			
			
			var res =  date_str & "  |  " & user_role_str & " | "  &  group_str
			return res
			```
		displayFolder: _filt_helpers
		lineageTag: 203cf28c-7376-4634-a106-b86acd188d74

	/// Measure meas.data_asof.
	measure 'meas.data_asof' = //"Data last processed on: " & calculate(max(leads[_sys_as_of]))
		formatString: 0
		displayFolder: _filt_helpers
		lineageTag: 45ef1e74-2032-4fab-8fcc-e9b422fa3e4c

	/// Measure meas.last_year_full.
	measure 'meas.last_year_full' =
			
			var _current_year = YEAR(MAX('cal_end_dates'[date]))
			var _last_year = YEAR(MAX('cal_end_dates'[date]))-1
			
			var res = _current_year - _last_year
			var res1 = IF(
			    res=1,
			    _last_year,
			    _current_year
			)
			
			RETURN
			res1
		formatString: 0
		displayFolder: _filt_helpers
		lineageTag: a32c0d45-f0d4-4361-bb6b-0b48af7d7861

	/// Measure meas.context_min.
	measure 'meas.context_min' =
			
			CALCULATE(MIN('cal_end_dates'[date]))
		formatString: General Date
		displayFolder: _filt_helpers
		lineageTag: 1148b606-5a63-49e5-b97e-960f5897841b

	/// Measure meas.context_max.
	measure 'meas.context_max' =
			
			CALCULATE(MAX('cal_end_dates'[date]))
		formatString: General Date
		displayFolder: _filt_helpers
		lineageTag: 57062494-3508-4371-b498-92dfb39f703e

	/// Column date.
	column date
		formatString: Short Date
		lineageTag: 86095ff3-619d-4c1f-ab71-5e768c8b7a14
		summarizeBy: none
		sourceColumn: [Date]

		variation Variation
			isDefault
			relationship: 9636e69b-c448-4a19-af73-36f8c4b26a38
			defaultHierarchy: LocalDateTable_bab82619-28e3-41d4-97e7-0c4cc876d812.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	/// Column date_as_integer.
	column date_as_integer
		lineageTag: dc31e7db-2c2a-4c88-8eaf-3f9f25989f77
		summarizeBy: none
		isNameInferred
		sourceColumn: [date_as_integer]

		annotation SummarizationSetBy = Automatic

	/// Column year.
	column year
		dataType: int64
		formatString: 0
		lineageTag: e4f6ada4-90ae-4609-b42c-d5f4ff0660ee
		summarizeBy: sum
		isNameInferred
		sourceColumn: [year]

		annotation SummarizationSetBy = Automatic

	/// Column month_number.
	column month_number
		lineageTag: 973279c9-f2cb-47e3-b904-eb2c55e05a94
		summarizeBy: none
		isNameInferred
		sourceColumn: [month_number]

		annotation SummarizationSetBy = Automatic

	/// Column year_month_number.
	column year_month_number
		lineageTag: 36158ebe-806d-4b59-adf7-70acc7db9a47
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_month_number]

		annotation SummarizationSetBy = Automatic

	/// Column year_month_short.
	column year_month_short
		lineageTag: d564f460-3385-4216-a2e1-c9bb73347be9
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_month_short]

		annotation SummarizationSetBy = Automatic

	/// Column month_name_short.
	column month_name_short
		lineageTag: 026af4ac-4da3-4995-b9f5-fae59f8ec971
		summarizeBy: none
		isNameInferred
		sourceColumn: [month_name_short]

		annotation SummarizationSetBy = Automatic

	/// Column month_name_long.
	column month_name_long
		lineageTag: f22c6569-cb80-4917-b2de-e2aab35879c8
		summarizeBy: none
		isNameInferred
		sourceColumn: [month_name_long]

		annotation SummarizationSetBy = Automatic

	/// Column day_of_week_number.
	column day_of_week_number
		formatString: 0
		lineageTag: 86142ac0-d7ba-433d-a4c0-4b3ea11830ae
		summarizeBy: sum
		isNameInferred
		sourceColumn: [day_of_week_number]

		annotation SummarizationSetBy = Automatic

	/// Column day_of_week.
	column day_of_week
		lineageTag: 687c0d7c-30a6-49fe-9057-642d2d0ba7bf
		summarizeBy: none
		isNameInferred
		sourceColumn: [day_of_week]

		annotation SummarizationSetBy = Automatic

	/// Column day_of_week_short.
	column day_of_week_short
		lineageTag: 83ef68a1-52ef-4b07-812b-b7efdc56c457
		summarizeBy: none
		isNameInferred
		sourceColumn: [day_of_week_short]

		annotation SummarizationSetBy = Automatic

	/// Column quarter.
	column quarter
		lineageTag: 6cb1305b-2d31-404c-87ed-5795b4692299
		summarizeBy: none
		isNameInferred
		sourceColumn: [quarter]

		annotation SummarizationSetBy = Automatic

	/// Column year_quarter.
	column year_quarter
		lineageTag: 0a907e53-7d54-4cd2-99a0-25cb602e0f15
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_quarter]

		annotation SummarizationSetBy = Automatic

	/// Column year_week_number.
	column year_week_number
		lineageTag: faf180e6-804a-4525-b401-37fe3e1e6577
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_week_number]

		annotation SummarizationSetBy = Automatic

	/// Column year_day_number.
	column year_day_number
		lineageTag: 15d54118-9d10-4199-9d57-c5c997f25c8d
		summarizeBy: none
		isNameInferred
		sourceColumn: [year_day_number]

		annotation SummarizationSetBy = Automatic

	column year_quarter_num
		formatString: 0
		lineageTag: 61ba36bc-447a-40de-935e-588b6a12cdfb
		summarizeBy: sum
		isNameInferred
		sourceColumn: [year_quarter_num]

		annotation SummarizationSetBy = Automatic

	column first_of_week_date
		formatString: General Date
		lineageTag: 2b4075c3-f6b1-4e05-a5e0-c395b8f30612
		summarizeBy: none
		isNameInferred
		sourceColumn: [first_of_week_date]

		annotation SummarizationSetBy = Automatic

	column first_of_month_date
		formatString: General Date
		lineageTag: 9ea75d3b-4960-45c8-a43d-5e81af95c82a
		summarizeBy: none
		isNameInferred
		sourceColumn: [first_of_month_date]

		annotation SummarizationSetBy = Automatic

	column first_of_qtr_date
		formatString: General Date
		lineageTag: d4aae04e-6d93-4175-9750-3378a4044716
		summarizeBy: none
		isNameInferred
		sourceColumn: [first_of_qtr_date]

		annotation SummarizationSetBy = Automatic

	column is_last_4q
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b93539d8-ef40-4d87-8f1e-05c0b06a1c65
		summarizeBy: none
		isNameInferred
		sourceColumn: [is_last_4q]

		annotation SummarizationSetBy = Automatic

	column first_of_year_date
		formatString: General Date
		lineageTag: dc7c1e3d-66f2-493b-984e-383d2c7868f4
		summarizeBy: none
		isNameInferred
		sourceColumn: [first_of_year_date]

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Date'
		formatString: General Date
		lineageTag: e35c5b50-0c2f-4d47-964d-fcde8469a530
		summarizeBy: none
		isNameInferred
		sourceColumn: [Fiscal Date]

		annotation SummarizationSetBy = Automatic

	partition cal_end_dates-c3d83cde-1612-440f-b017-358fa64b862d = calculated
		mode: import
		source =
				
				VAR MinDateRaw =
				    CALCULATE (
				        MIN ( ssr[_sys_filt_start_date] ),
				        REMOVEFILTERS ( ssr )
				    )
				
				VAR MaxDateRaw =
				    CALCULATE (
				        MAX ( ssr[_sys_as_of] ),
				        REMOVEFILTERS ( ssr )
				    )
				
				VAR min_date =
				    MAX (
				        DATE ( 2000, 1, 1 ),
				        COALESCE ( MinDateRaw, DATE ( 2000, 1, 1 ) )
				    )
				
				VAR max_date =
				    COALESCE ( MaxDateRaw, DATE ( 2000, 1, 1 ) )
				
				VAR f_month = [meas.getFiscalYearOffset]
				
				VAR CurrentQuarterStart =
				    DATE ( YEAR ( max_date ), MONTH ( max_date ) - MOD ( MONTH ( max_date ) - 1, 3 ), 1 )
				
				VAR FourQuartersAgo =
				    EDATE ( CurrentQuarterStart, -9 )
				
				VAR cal_tbl =
				    ADDCOLUMNS (
				        CALENDAR ( min_date, max_date ),
				        "date_as_integer", FORMAT ( [Date], "YYYYMMDD" ),
				        "year", YEAR ( [Date] ),
				        "month_number", FORMAT ( [Date], "MM" ),
				        "year_month_number", FORMAT ( [Date], "YYYY/MM" ),
				        "year_week_number", FORMAT ( [Date], "YYYY/0w" ),
				        "year_day_number", FORMAT ( [Date], "YYYY/ddd" ),
				        "year_month_short", FORMAT ( [Date], "YYYY/mmm" ),
				        "month_name_short", FORMAT ( [Date], "mmm" ),
				        "month_name_long", FORMAT ( [Date], "mmmm" ),
				        "day_of_week_number", WEEKDAY ( [Date] ),
				        "day_of_week", FORMAT ( [Date], "dddd" ),
				        "day_of_week_short", FORMAT ( [Date], "ddd" ),
				        "quarter", "Q" & FORMAT ( [Date], "Q" ),
				        "year_quarter", FORMAT ( [Date], "YYYY" ) & "/Q" & FORMAT ( [Date], "Q" ),
				        "year_quarter_num", YEAR ( [Date] ) * 4 + QUARTER ( [Date] ),
				        "first_of_week_date", [Date] - WEEKDAY ( [Date] ) + 1,
				        "first_of_month_date", DATE ( YEAR ( [Date] ), MONTH ( [Date] ), 1 ),
				        "first_of_qtr_date",
				            DATE (
				                YEAR ( [Date] ),
				                SWITCH (
				                    MONTH ( [Date] ),
				                    1, 1,
				                    2, 1,
				                    3, 1,
				                    4, 4,
				                    5, 4,
				                    6, 4,
				                    7, 7,
				                    8, 7,
				                    9, 7,
				                    10, 10,
				                    11, 10,
				                    12, 10
				                ),
				                1
				            ),
				        "is_last_4q",
				            IF (
				                [Date] >= FourQuartersAgo
				                    && [Date] < EDATE ( CurrentQuarterStart, 3 ),
				                TRUE (),
				                FALSE ()
				            ),
				        "first_of_year_date", DATE ( YEAR ( [Date] ), 1, 1 ),
				        "Fiscal Date",
				            DATE (
				                IF (
				                    f_month = 0,
				                    YEAR ( [Date] ),
				                    IF ( MONTH ( [Date] ) >= f_month, YEAR ( [Date] ), YEAR ( [Date] ) - 1 )
				                ),
				                IF (
				                    f_month = 0,
				                    MONTH ( [Date] ),
				                    IF (
				                        MONTH ( [Date] ) >= f_month,
				                        MONTH ( [Date] ) - f_month + 1,
				                        MONTH ( [Date] ) + 12 - f_month + 1
				                    )
				                ),
				                DAY ( [Date] )
				            )
				    )
				
				VAR cal_tbl2 =
				    ADDCOLUMNS (
				        CALENDAR ( DATE ( 2100, 1, 1 ), DATE ( 2100, 1, 1 ) ),
				        "date_as_integer", FORMAT ( [Date], "YYYYMMDD" ),
				        "year", YEAR ( [Date] ),
				        "month_number", FORMAT ( [Date], "MM" ),
				        "year_month_number", FORMAT ( [Date], "YYYY/MM" ),
				        "year_day_number", FORMAT ( [Date], "YYYY/00d" ),
				        "year_week_number", FORMAT ( [Date], "YYYY/ww" ),
				        "year_month_short", FORMAT ( [Date], "YYYY/mmm" ),
				        "month_name_short", FORMAT ( [Date], "mmm" ),
				        "month_name_long", FORMAT ( [Date], "mmmm" ),
				        "day_of_week_number", WEEKDAY ( [Date] ),
				        "day_of_week", FORMAT ( [Date], "dddd" ),
				        "day_of_week_short", FORMAT ( [Date], "ddd" ),
				        "quarter", "Q" & FORMAT ( [Date], "Q" ),
				        "year_quarter", FORMAT ( [Date], "YYYY" ) & "/Q" & FORMAT ( [Date], "Q" ),
				        "year_quarter_num", YEAR ( [Date] ) * 4 + QUARTER ( [Date] ),
				        "first_of_week_date", [Date] - WEEKDAY ( [Date] ) + 1,
				        "first_of_month_date", DATE ( YEAR ( [Date] ), MONTH ( [Date] ), 1 ),
				        "first_of_qtr_date",
				            DATE (
				                YEAR ( [Date] ),
				                SWITCH (
				                    MONTH ( [Date] ),
				                    1, 1,
				                    2, 1,
				                    3, 1,
				                    4, 4,
				                    5, 4,
				                    6, 4,
				                    7, 7,
				                    8, 7,
				                    9, 7,
				                    10, 10,
				                    11, 10,
				                    12, 10
				                ),
				                1
				            ),
				        "is_last_4q",
				            IF (
				                [Date] >= FourQuartersAgo
				                    && [Date] < EDATE ( CurrentQuarterStart, 3 ),
				                TRUE (),
				                FALSE ()
				            ),
				        "first_of_year_date", DATE ( YEAR ( [Date] ), 1, 1 ),
				        "Fiscal Date",
				            DATE (
				                IF (
				                    f_month = 0,
				                    YEAR ( [Date] ),
				                    IF ( MONTH ( [Date] ) >= f_month, YEAR ( [Date] ), YEAR ( [Date] ) - 1 )
				                ),
				                IF (
				                    f_month = 0,
				                    MONTH ( [Date] ),
				                    IF (
				                        MONTH ( [Date] ) >= f_month,
				                        MONTH ( [Date] ) - f_month + 1,
				                        MONTH ( [Date] ) + 12 - f_month + 1
				                    )
				                ),
				                DAY ( [Date] )
				            )
				    )
				
				RETURN
				    UNION ( cal_tbl, cal_tbl2 )

	annotation PBI_Id = 47fdd5fe548045698e2980cebacd82ae

