/// Table completeness_summary.
table completeness_summary
	lineageTag: 3fb477da-2334-4131-be85-e28100904333

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: Measures: [crm_completeness].
	/// Dynamic Behavior: Uses CALCULATE/CALCULATETABLE to modify filter context with its filter arguments.
	/// Format/Type: 0
	measure 'meas.crm_completeness_score_display' = CALCULATE(AVERAGE([crm_completeness])  * 100)
		description: """
Purpose: Tracks CRM completeness score display.
Logic: Averages values under filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _completeness_score
		lineageTag: 25d350dc-3b66-4cb2-83ae-59852cd3198b

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: 0
	measure 'meas.trueai_completeness_score' =
			
			var _before_score = [meas.crm_completeness_score_display]               // get the crm score(before)
			var _after_score = CALCULATE(AVERAGE([trueai_completeness])  * 100)             // get the after score
			
			VAR res = IF(
			    _after_score < _before_score,
			    _before_score,              // create the condition to display the after score less than before score
			    _after_score
			)
			
			RETURN
			res
		description: """
Purpose: Tracks trueai completeness score.
Logic: Averages values under filters.
Dependencies: Measures: [meas.crm_completeness_score_display]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _completeness_score
		lineageTag: 220faaec-56c9-48ef-870f-4244580439c6

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: 0
	measure 'meas.crm_completeness_score_industry_avg' =
			
			var _score = CALCULATE(
			    MAX(metadata_reference_values[value]),
			    metadata_reference_values[_sys_doc_id]="comp2"
			)
			
			RETURN
			_score
		description: """
Purpose: Tracks CRM completeness score industry average.
Logic: Returns an extreme value from metadata_reference_values[value] under filters.
Dependencies: Columns: metadata_reference_values[value], metadata_reference_values[_sys_doc_id]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Whole number
		"""
		formatString: 0
		displayFolder: _completeness_score
		lineageTag: 295be6f7-5568-467e-ada1-cb24b46e2ed9

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: VAR blocks define intermediate values (crmval, aival, impro, res) used later in the expression. Dependencies: Measures: [crm_completeness], [trueai_completeness].
	/// Dynamic Behavior: Uses IF for conditional branching.
	/// Format/Type: Not specified.
	measure 'meas.trueai_completeness_improvement' = ```
			
			var crmval = CALCULATE(AVERAGE([crm_completeness]))
			var aival = CALCULATE(AVERAGE([trueai_completeness]))
			var impro = Divide(aival - crmval, crmval) 
			var res = If(impro > 0, "+" & FORMAT( impro, "###%"),  "No change")
			return res 
			
			```
		description: """
Purpose: Tracks trueai completeness improvement.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		displayFolder: _completeness_score
		lineageTag: 8cf3d72c-fedc-4ef5-970d-57580fe4ba53

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: VAR blocks define intermediate values (crmval, aival, impro, res) used later in the expression. Dependencies: Measures: [crm_completeness_geo], [trueai_completeness_geo].
	/// Dynamic Behavior: Uses IF for conditional branching.
	/// Format/Type: 0%;-0%;0%
	measure 'meas.trueai_completeness_geo_improvement' = ```
			
			var crmval = CALCULATE(AVERAGE([crm_completeness_geo]))
			var aival = CALCULATE(AVERAGE([trueai_completeness_geo]))
			var impro = Divide(aival - crmval, crmval) 
			var res = If(impro > 0, "+" & FORMAT( impro, "###%"),  "No change")
			return res 
			
			```
		description: """
Purpose: Tracks trueai completeness geo improvement.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _completeness_score
		lineageTag: 8f49df2a-bdc7-43e0-aa92-36030435c286

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: VAR blocks define intermediate values (crmval, aival, impro, res) used later in the expression. Dependencies: Measures: [crm_completeness_marketing], [trueai_completeness_marketing].
	/// Dynamic Behavior: Uses IF for conditional branching.
	/// Format/Type: 0%;-0%;0%
	measure 'meas.trueai_completeness_marketing_improvement' = ```
			
			var crmval = CALCULATE(AVERAGE([crm_completeness_marketing]))
			var aival = CALCULATE(AVERAGE([trueai_completeness_marketing]))
			var impro = Divide(aival - crmval, crmval) 
			var res = If(impro > 0, "+" & FORMAT( impro, "###%"),  "No change")
			return res 
			
			```
		description: """
Purpose: Tracks trueai completeness marketing improvement.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _completeness_score
		lineageTag: 82d8b5b9-38ea-4989-9adf-d76ea2f2af22

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: VAR blocks define intermediate values (crmval, aival, impro, res) used later in the expression. Dependencies: Measures: [crm_completeness_contact], [trueai_completeness_contact].
	/// Dynamic Behavior: Uses IF for conditional branching.
	/// Format/Type: Not specified.
	measure 'meas.trueai_completeness_contact_improvement' = ```
			
			var crmval = CALCULATE(AVERAGE([crm_completeness_contact]))
			var aival = CALCULATE(AVERAGE([trueai_completeness_contact]))
			var impro = Divide(aival - crmval, crmval) 
			var res = If(impro > 0, "+" & FORMAT( impro, "###%"),  "No change")
			return res 
			
			```
		description: """
Purpose: Tracks trueai completeness contact improvement.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Text
		"""
		displayFolder: _completeness_score
		lineageTag: 7cf2b251-0b10-4d7d-ada9-772238f7d953

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: VAR blocks define intermediate values (crmval, aival, impro, res) used later in the expression. Dependencies: Measures: [crm_completeness_contact_method], [trueai_completeness_contact_method].
	/// Dynamic Behavior: Uses IF for conditional branching.
	/// Format/Type: 0%;-0%;0%
	measure 'meas.trueai_completeness_contact_method_improvement' = ```
			
			var crmval = CALCULATE(AVERAGE([crm_completeness_contact_method]))
			var aival = CALCULATE(AVERAGE([trueai_completeness_contact_method]))
			var impro = Divide(aival - crmval, crmval) 
			var res = If(impro > 0, "+" & FORMAT( impro, "###%"),  "No change")
			return res 
			
			```
		description: """
Purpose: Tracks trueai completeness contact method improvement.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: See model references
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: 0%;-0%;0%
		displayFolder: _completeness_score
		lineageTag: 770b89c9-ad28-48c3-8957-004b46ed2d56

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..
	/// Dynamic Behavior: No explicit conditional branching detected.
	/// Format/Type: +#%;-#%;0%
	measure 'meas.trueai_completeness_score_improvement' =
			
			var trueai_score = ROUND([meas.trueai_completeness_score],2)
			var crm_score = ROUND([meas.crm_completeness_score_display],2)
			var imp = divide(trueai_score - crm_score,  crm_score, 0)
			var res = imp
			return res
		description: """
Purpose: Tracks trueai completeness score improvement.
Logic: Calculated as a ratio of two values with any applied filters.
Dependencies: Measures: [meas.crm_completeness_score_display], [meas.trueai_completeness_score]
Context: Evaluated in the current filter context unless explicitly overridden in DAX.
Output: Percentage
		"""
		formatString: +#%;-#%;0%
		displayFolder: _completeness_score
		lineageTag: f444042a-587c-402b-a3c6-222e0aed0d89

		annotation PBI_FormatHint = {"isCustom":true}

	/// Column entity.
	column entity
		lineageTag: 82e8678d-ea59-42b4-a35d-e6043095aadb
		summarizeBy: none
		isNameInferred
		sourceColumn: [entity]

		annotation SummarizationSetBy = Automatic

	/// Column _sys_docid.
	column _sys_docid
		lineageTag: 6a99baa4-5d68-47c8-9ada-55350670d51b
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_docid]

		annotation SummarizationSetBy = Automatic

	/// Column _sys_filter_start_date.
	column _sys_filter_start_date
		formatString: General Date
		lineageTag: 317b3218-8ae0-4491-955d-f6fa7d93aac0
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_filter_start_date]

		annotation SummarizationSetBy = Automatic

	/// Column crm_completeness.
	column crm_completeness
		lineageTag: 0ac69f0e-ef6b-4664-b221-d87792de51be
		summarizeBy: sum
		isNameInferred
		sourceColumn: [crm_completeness]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column crm_completeness_geo.
	column crm_completeness_geo
		lineageTag: 0f227e34-8b51-4dbe-8b9a-25544bf2c0ea
		summarizeBy: sum
		isNameInferred
		sourceColumn: [crm_completeness_geo]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column crm_completeness_marketing.
	column crm_completeness_marketing
		lineageTag: 7134e4ce-5322-4256-8b89-841f1abec6ba
		summarizeBy: sum
		isNameInferred
		sourceColumn: [crm_completeness_marketing]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column crm_completeness_contact.
	column crm_completeness_contact
		lineageTag: 82ea1c2f-37be-4bc6-9ae1-0b9cc2585543
		summarizeBy: sum
		isNameInferred
		sourceColumn: [crm_completeness_contact]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column crm_completeness_contact_method.
	column crm_completeness_contact_method
		lineageTag: 7ce74689-0411-4b3d-8612-b84e840ee524
		summarizeBy: sum
		isNameInferred
		sourceColumn: [crm_completeness_contact_method]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column trueai_completeness.
	column trueai_completeness
		lineageTag: 8484a2f0-3347-4374-8aaf-3f5558b6c691
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_completeness]

		annotation SummarizationSetBy = Automatic

	/// Column trueai_completeness_geo.
	column trueai_completeness_geo
		lineageTag: cc152aae-b5e0-4210-854b-aef0ecebb743
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_completeness_geo]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column trueai_completeness_marketing.
	column trueai_completeness_marketing
		lineageTag: ac7fc4bf-8cb9-44a8-84d6-4df1c343c08e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_completeness_marketing]

		annotation SummarizationSetBy = Automatic

	/// Column trueai_completeness_contact.
	column trueai_completeness_contact
		lineageTag: 0996c4b7-3886-49ec-afef-235555adf290
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_completeness_contact]

		annotation SummarizationSetBy = Automatic

	/// Column trueai_completeness_contact_method.
	column trueai_completeness_contact_method
		lineageTag: 6d583088-59e0-46df-b464-96cd1e50d573
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_completeness_contact_method]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column _sys_user_id.
	column _sys_user_id
		lineageTag: 8d196aa1-3b2f-421a-8d66-f6aaa93688f3
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_user_id]

		annotation SummarizationSetBy = Automatic

	/// Column sort.
	column sort
		formatString: 0
		lineageTag: 0f827162-3e98-40fb-a0b4-64a780bf3e28
		summarizeBy: sum
		isNameInferred
		sourceColumn: [sort]

		annotation SummarizationSetBy = Automatic

	partition completeness_summary-32d13607-6cda-486f-a830-988dcac24cf6 = calculated
		mode: import
		source = ```
				UNION(
				
				 SELECTCOLUMNS(leads, "entity", "Leads",  "_sys_docid", leads[_sys_docid], "_sys_user_id", leads[trueai_owner_id],  "_sys_filter_start_date", leads[_sys_filt_start_date],  "sort", 1,
				"crm_completeness", leads[crm_complt], 
				"crm_completeness_geo", leads[crm_complt_geo], "crm_completeness_marketing", leads[crm_complt_marketing],"crm_completeness_contact", leads[crm_complt_contact],  "crm_completeness_contact_method", leads[crm_complt_contact_method], 
				"trueai_completeness", leads[trueai_complt],  
				"trueai_completeness_geo", leads[trueai_complt_geo], "trueai_completeness_marketing", leads[trueai_complt_marketing], "trueai_completeness_contact", leads[trueai_complt_contact], "trueai_completeness_contact_method", leads[crm_complt_contact_method]) // leads
				,
				SELECTCOLUMNS(accounts, "entity", "Accounts",  "_sys_docid", accounts[_sys_docid], "_sys_user_id", accounts[trueai_owner_id],  "_sys_filter_start_date", accounts[_sys_filt_start_date],   "sort", 2,
				"crm_completeness", accounts[crm_complt], 
				"crm_completeness_geo", accounts[crm_complt_geo], "crm_completeness_marketing", accounts[crm_complt_marketing],"crm_completeness_contact", accounts[crm_complt_contact],  "crm_completeness_contact_method", accounts[crm_complt_contact_method], 
				"trueai_completeness", accounts[trueai_complt],  
				"trueai_completeness_geo", accounts[trueai_complt_geo], "trueai_completeness_marketing", accounts[trueai_complt_marketing], "trueai_completeness_contact", accounts[trueai_complt_contact], "trueai_completeness_contact_method", accounts[crm_complt_contact_method]) // accounts
				,
				SELECTCOLUMNS(opps, "entity", "Opps",  "_sys_docid", opps[_sys_docid], "_sys_user_id", opps[trueai_owner_id],  "_sys_filter_start_date", opps[_sys_filt_start_date],   "sort", 3,
				"crm_completeness", opps[crm_complt], 
				"crm_completeness_geo", blank(), "crm_completeness_marketing", opps[crm_complt_marketing],"crm_completeness_contact", opps[crm_complt_contact],  "crm_completeness_contact_method", blank(), 
				"trueai_completeness", opps[trueai_complt],  
				"trueai_completeness_geo", blank(), "trueai_completeness_marketing", opps[trueai_complt_marketing], "trueai_completeness_contact", opps[trueai_complt_contact], "trueai_completeness_contact_method", blank()) // opps
				,
				SELECTCOLUMNS(contacts, "entity", "Contacts",  "_sys_docid", contacts[_sys_doc_id],  "_sys_user_id", contacts[trueai_owner_id], "_sys_filter_start_date",DATEVALUE("" & contacts[crm_created_on]),   "sort", 4,
				"crm_completeness", contacts[crm_complt], 
				"crm_completeness_geo", contacts[crm_complt_geo], "crm_completeness_marketing", contacts[crm_complt_marketing],"crm_completeness_contact", contacts[crm_complt_contact],  "crm_completeness_contact_method", contacts[crm_complt_contact_method], 
				"trueai_completeness", contacts[trueai_complt],  
				"trueai_completeness_geo", contacts[trueai_complt_geo], "trueai_completeness_marketing", contacts[trueai_complt_marketing], "trueai_completeness_contact", contacts[trueai_complt_contact], "trueai_completeness_contact_method", contacts[crm_complt_contact_method]) // contacts
				
				)
				```

	annotation PBI_Id = 1019b44ce9a14ebdbe81557856032529

