table consistency_summary
	lineageTag: 5f7d346c-d097-4fee-b748-c946478a0dc7

	measure 'meas.crm_consistency_count_address_city' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([crm_addr_city]), consistency_summary[crm_addr_city] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: b2f66e5b-e2bd-4a12-acc7-57ebef2b3a3f

	measure 'meas.crm_consistency_count_address_country' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([crm_addr_country]), consistency_summary[crm_addr_country] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: fddf49aa-3f1e-4060-a815-6c1c214cf480

	measure 'meas.crm_consistency_count_address_state' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([crm_addr_state]), consistency_summary[crm_addr_state] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: #,0
		displayFolder: _consistancy_score
		lineageTag: 0e43b5bf-d05a-441a-b050-f8506e5685ee

	measure 'meas.crm_consistency_count_industry' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([crm_industry]), consistency_summary[crm_industry] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: 02a0e393-6924-461a-9d23-a2fdfea3092e

	measure 'meas.crm_consistency_count_leadsource' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([crm_leadsource]), consistency_summary[crm_leadsource] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: e8be4735-db38-4312-b8ec-7f8cb2a36e7a

	measure 'meas.crm_consistency_count_title' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([crm_title]), consistency_summary[crm_title] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: 76dd37d6-6a50-4281-a779-d751e29e2864

	measure 'meas.crm_consistency_score' = ```
			
			var coeff = 0.6 // make the ratio less drastic so it takes longer to get to 0
			var max_date = CALCULATE(MAX(cal_end_dates[Date])  )
			var min_date =  DATE(2000,1,1) //FILTERS(cal_start_dates[Date])
			
			// leadsource
			var ls_count = CALCULATE(DISTINCTCOUNT([crm_leadsource]))
			
			var ls_optimal_count = 30
			var ls_score =  if(ls_count <2 , blank(), If(ls_count < ls_optimal_count, 1,  (ls_optimal_count/ls_count) ^ coeff)) // no data = blank, unique count < ideal count = 1, otherwise do the ratio and sqaure it 
			
			// industry
			var ind_count = CALCULATE(DISTINCTCOUNT([crm_industry]))
			var ind_optimal_count = 50
			var ind_score =  if(ind_count <2 , blank(), If(ind_count < ind_optimal_count, 1,  (ind_optimal_count/ind_count) ^ coeff)) // no data = blank, unique count < ideal count = 1, otherwise do the ratio and 
			
			var countScore =  IF(ISBLANK( ls_score), 0, 1) +  IF(ISBLANK( ind_score), 0, 1) 
			
			
			var res = divide(If(isBLANK(ls_score), 0,ls_score) + If(isBLANK(ind_score), 0,ind_score)  , countScore, blank()) 
			
			return res
			```
		formatString: 0.00
		displayFolder: _consistancy_score
		lineageTag: d9e1bcfa-3f3c-4392-9c91-9dfbff1dd779

		changedProperty = FormatString

	measure 'meas.crm_consistency_score_industry_avg' =
			//68
			var _score = CALCULATE(
			    MAX(metadata_reference_values[value]),
			    metadata_reference_values[_sys_doc_id]="consist3"
			)
			
			RETURN
			_score
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: ad84e61a-dca2-4efb-a8a8-f6aed2e396e8

	measure 'meas.trueai_consistency_count_address_city' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([trueai_addr_city]), consistency_summary[trueai_addr_city] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: 6afb1038-d72c-4856-9f93-a38e5c3be21f

	measure 'meas.trueai_consistency_count_address_country' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([trueai_addr_country]), consistency_summary[trueai_addr_country] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: d053adf7-cdb7-43d1-9b0b-3f3c38024496

	measure 'meas.trueai_consistency_count_address_state' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([trueai_addr_state]), consistency_summary[trueai_addr_state] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: #,0
		displayFolder: _consistancy_score
		lineageTag: b252c2ab-cbcd-4e94-a08e-02aa8ccb97fe

	measure 'meas.trueai_consistency_count_industry' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([trueai_industry]), consistency_summary[trueai_industry] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: 5200942a-36fe-4f17-bd48-09441851a736

	measure 'meas.trueai_consistency_count_leadsource' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([trueai_leadsource]), consistency_summary[trueai_leadsource] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: 59cc3869-fd60-4307-bd80-a994d9821119

	measure 'meas.trueai_consistency_count_title_concat' =
			
			var cnt = CALCULATE(DISTINCTCOUNT([trueai_title_concat]), consistency_summary[trueai_title_concat] <> BLANK())  //count all non blanks
			var res = cnt
			return res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: eed2043e-325f-4c87-9a8a-4c179bc4bd2a

	measure 'meas.trueai_consistency_improvement_country' = ```
			
			var crm_count = CALCULATE(DISTINCTCOUNT([crm_addr_country]), consistency_summary[crm_addr_country] <> BLANK())
			var ai_count =  CALCULATE(DISTINCTCOUNT([trueai_addr_country]), consistency_summary[trueai_addr_country] <> BLANK())
			var ratio =  round(divide(crm_count , ai_count,BLANK()),0)
			var res  = If(isblank(ratio), "Country not consolidated", "Country - " & ratio & "X Consolidation" )
			return res 
			
			
			```
		displayFolder: _consistancy_score
		lineageTag: 214c6ede-747e-465d-ba51-105e91f6a1a3

	measure 'meas.trueai_consistency_improvement_industry' = ```
			
			var crm_count = CALCULATE(DISTINCTCOUNT([crm_industry]), consistency_summary[crm_industry] <> BLANK())
			var ai_count =  CALCULATE(DISTINCTCOUNT([trueai_industry]), consistency_summary[trueai_industry] <> BLANK())
			var ratio =  round(divide(crm_count , ai_count,BLANK()),0)
			var res  = If(isblank(ratio), "Industry not consolidated", "Industry - " & ratio & "X Consolidation" )
			return res 
			
			
			```
		displayFolder: _consistancy_score
		lineageTag: 87fcd8b0-0afc-4825-a40d-bfec76c1ce38

	measure 'meas.trueai_consistency_improvement_leadsource' = ```
			
			var crm_count = CALCULATE(DISTINCTCOUNT([crm_leadsource]), consistency_summary[crm_leadsource] <> BLANK())
			var ai_count =  CALCULATE(DISTINCTCOUNT([trueai_leadsource]), consistency_summary[trueai_leadsource] <> BLANK())
			var ratio =  round(divide(crm_count , ai_count,BLANK()),0)
			var res  = If(isblank(ratio), "Leadsource not consolidated", "Leadsource - " & ratio & "X Consolidation" )
			return res 
			
			
			```
		displayFolder: _consistancy_score
		lineageTag: 60a16077-4e1f-4bc5-a21b-04224e2df6cc

	measure 'meas.trueai_consistency_improvement_title' = ```
			
			var crm_count = CALCULATE(DISTINCTCOUNT([crm_title]), consistency_summary[crm_title] <> BLANK())
			var ai_count =  CALCULATE(DISTINCTCOUNT([trueai_title_concat]), consistency_summary[trueai_title_concat] <> BLANK())
			var ratio =  round(divide(crm_count , ai_count,BLANK()),0)
			var res  = If(isblank(ratio), "Title not consolidated", "Title - " & ratio & "X Consolidation" )
			return res 
			
			
			```
		displayFolder: _consistancy_score
		lineageTag: 27638655-fbbe-438d-a504-b456e9d2041d

	measure 'meas.trueai_consistency_score' = ```
			
			var industry_conf_raw = CALCULATE(
			    average(consistency_summary[trueai_industry_conf]), 
			    consistency_summary[crm_industry] <> "" 
			    && isblank(consistency_summary[crm_industry]) =false 
			) + 0
			
			VAR industry_conf = POWER(industry_conf_raw, 0.4)
			
			
			var industry_count = CALCULATE(
			    count(consistency_summary[trueai_industry_conf]), 
			    consistency_summary[crm_industry] <> "" 
			    && isblank(consistency_summary[crm_industry]) =false 
			) + 0
			var leadsource_conf_raw = CALCULATE(
			    average(consistency_summary[trueai_leadsource_conf]), 
			    consistency_summary[crm_leadsource] <> "" 
			    && isblank(consistency_summary[crm_leadsource]) = false
			) + 0
			
			VAR leadsource_conf = POWER(leadsource_conf_raw, 0.4)
			
			var leadsource_count = CALCULATE(
			    count(consistency_summary[trueai_leadsource_conf]), 
			    consistency_summary[crm_leadsource] <> "" 
			    && isblank(consistency_summary[crm_leadsource]) = false
			) +0 
			
			var res  =  Divide((industry_conf * industry_count) + (leadsource_conf * leadsource_count) , industry_count + leadsource_count)
			return res
			
			```
		displayFolder: _consistancy_score
		lineageTag: 9752bf98-83c9-487b-a234-92b6fe82db9a

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.trueai_consistency_score_improvement' =
			
			var trueai_score = ROUND([meas.trueai_consistency_score_display],2)     // get the trueai consistency score
			var crm_score = ROUND([meas.crm_consistency_score_display],2)           // crm consistency score
			var res = divide(trueai_score -crm_score,  crm_score, 0)
			RETURN
			res
		formatString: +#%;-#%;0%
		displayFolder: _consistancy_score
		lineageTag: 7562cc7c-d6d5-4e43-8bd4-def9fb3817e6

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.crm_consistency_score_display' = [meas.crm_consistency_score] * 100
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: fc3025a8-9bfe-4359-a717-d8a1e1cdb3fa

		changedProperty = FormatString

	measure 'meas.trueai_consistency_score_display' =
			
			var _before_score = [meas.crm_consistency_score_display]                // get the before score
			var _after_score = [meas.trueai_consistency_score] * 100                // get the after score
			
			var res = IF(
			    _after_score < _before_score,
			    _before_score,
			    _after_score
			)
			
			RETURN
			res
		formatString: 0
		displayFolder: _consistancy_score
		lineageTag: 8a469cd2-ac3f-4681-a7a4-74cf02b78697

		changedProperty = FormatString

	column entity
		lineageTag: 35f50a1f-a07f-4b72-9239-e22aed7861fd
		summarizeBy: none
		isNameInferred
		sourceColumn: [entity]

		annotation SummarizationSetBy = Automatic

	column _sys_docid
		lineageTag: 9cad70a7-4dc3-4491-b97e-2f13a94683fb
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_docid]

		annotation SummarizationSetBy = Automatic

	column _sys_filter_start_date
		formatString: General Date
		lineageTag: ad449777-5480-49b1-9ebe-f8127ecbd27b
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_filter_start_date]

		annotation SummarizationSetBy = Automatic

	column crm_leadsource
		lineageTag: 7c04e25b-2778-4637-a9ef-cb9ba32b1a5b
		summarizeBy: none
		isNameInferred
		sourceColumn: [crm_leadsource]

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource
		lineageTag: 582eb5e3-b8c5-4145-9f87-b4553f1775a0
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_leadsource]

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource_rule
		lineageTag: ee1f88ed-c1d3-4a75-ab1f-1949f273dcac
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_leadsource_rule]

		annotation SummarizationSetBy = Automatic

	column crm_industry
		lineageTag: 2d6c1c7f-1bb6-4e03-ab0b-a924cbb7f7c6
		summarizeBy: none
		isNameInferred
		sourceColumn: [crm_industry]

		annotation SummarizationSetBy = Automatic

	column trueai_industry
		lineageTag: 470894fa-22c0-4bc8-ac3f-be939e6bb533
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_industry]

		annotation SummarizationSetBy = Automatic

	column trueai_industry_rule
		lineageTag: a7d333fb-bf87-4d29-8851-afdd40b1de07
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_industry_rule]

		annotation SummarizationSetBy = Automatic

	column crm_addr_city
		lineageTag: f3af1b63-e318-44c2-82d8-67895c360f34
		summarizeBy: none
		isNameInferred
		sourceColumn: [crm_addr_city]

		annotation SummarizationSetBy = Automatic

	column trueai_addr_city
		lineageTag: 72e58c45-fbd3-440c-a004-95df8e14448c
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_addr_city]

		annotation SummarizationSetBy = Automatic

	column crm_addr_state
		lineageTag: 0cd64b4e-c36f-44ab-858a-cbdff27b89b9
		summarizeBy: none
		isNameInferred
		sourceColumn: [crm_addr_state]

		annotation SummarizationSetBy = Automatic

	column trueai_addr_state
		lineageTag: bb84d90f-f9ad-40dd-98af-95d38f476a56
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_addr_state]

		annotation SummarizationSetBy = Automatic

	column crm_addr_country
		lineageTag: 4dc6bd88-3436-4819-9e09-6d1050924fd0
		summarizeBy: none
		isNameInferred
		sourceColumn: [crm_addr_country]

		annotation SummarizationSetBy = Automatic

	column trueai_addr_country
		lineageTag: da8f24fb-4b24-4b09-8432-2f91a4425953
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_addr_country]

		annotation SummarizationSetBy = Automatic

	column crm_title
		lineageTag: 29e62eb9-822d-489c-a46b-ed76a9b92613
		summarizeBy: none
		isNameInferred
		sourceColumn: [crm_title]

		annotation SummarizationSetBy = Automatic

	column trueai_title_dept
		lineageTag: d5599f18-40d4-4613-9ee5-f63bbe9dbe9e
		summarizeBy: none
		sourceColumn: [trueai_title_function]

		annotation SummarizationSetBy = Automatic

	column trueai_title_concat
		lineageTag: 7e9aa28a-32d5-487a-857b-99769c768c5b
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_title_concat]

		annotation SummarizationSetBy = Automatic

	column trueai_completeness_contact_method
		lineageTag: 453e1e75-c31a-4a69-9fbf-f26ff6b94ba0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_completeness_contact_method]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_user_id
		lineageTag: a5e64021-e8a3-4f0f-9279-1c4b9a5b8938
		summarizeBy: none
		isNameInferred
		sourceColumn: [_sys_user_id]

		annotation SummarizationSetBy = Automatic

	column trueai_title_seniority
		lineageTag: bca38651-e6ef-4830-8554-127bd9d28008
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_title_seniority]

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource_conf
		lineageTag: f2f2ec31-6478-4920-b1a6-b8dc8a7cb8ef
		summarizeBy: none
		isNameInferred
		sourceColumn: [trueai_leadsource_conf]

		annotation SummarizationSetBy = Automatic

	column trueai_industry_conf
		lineageTag: 11ef57e9-7229-41b0-9de6-158a4c6c8270
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_industry_conf]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_title_seniority_conf
		lineageTag: 499e75e4-456f-4a87-b2d8-6c14660cb644
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_title_seniority_conf]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_title_dept_conf
		lineageTag: a487635c-d3ea-4f79-99d5-18a3325c1b02
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_title_dept_conf]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_title_concat_conf
		lineageTag: 5e9f131d-1c23-4d03-be58-b994d5272b2f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [trueai_title_concat_conf]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sort
		formatString: 0
		lineageTag: 71aa44ef-722f-4dfd-b742-1dc45a3fb54b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [sort]

		annotation SummarizationSetBy = Automatic

	partition consistency_summary-df8d9cae-88d6-4c1d-8c64-c2ad75ed48e5 = calculated
		mode: import
		source = ```
				UNION(
				
				 SELECTCOLUMNS(leads, "entity", "Leads", "sort", 1,  "_sys_docid", leads[_sys_docid],   "_sys_user_id", leads[trueai_owner_id],  "_sys_filter_start_date", leads[_sys_filt_start_date],  
				
				 
				 "crm_leadsource", leads[crm_leadsource],
				 "trueai_leadsource", leads[trueai_leadsource],
				 "trueai_leadsource_conf", leads[trueai_leadsource_conf],
				 "trueai_leadsource_rule", leads[trueai_leadsource_rule],
				 "crm_industry", leads[crm_industry],
				 "trueai_industry", leads[trueai_industry],
				 "trueai_industry_conf", leads[trueai_industry_conf],
				"trueai_industry_rule", leads[trueai_industry_rule],
				 "crm_addr_city", leads[crm_addr_city],
				 "trueai_addr_city", leads[trueai_addr_city],
				 "crm_addr_state", leads[crm_addr_state],
				 "trueai_addr_state", leads[trueai_addr_state],
				 "crm_addr_country", leads[crm_addr_country],
				 "trueai_addr_country", leads[trueai_addr_country],
				 "crm_title", leads[crm_contact_title],
				 "trueai_title_seniority", leads[trueai_title_seniority],
				 "trueai_title_seniority_conf", leads[trueai_title_seniority_conf],
				 "trueai_title_function", leads[trueai_title_department],
				 "trueai_title_dept_conf", leads[trueai_title_department_conf],
				 "trueai_title_concat", leads[trueai_title_department] & " - " & leads[trueai_title_seniority],
				 "trueai_title_concat_conf", (leads[trueai_title_department_conf] + leads[trueai_title_seniority_conf]) /2 ,
				"trueai_completeness_contact_method", leads[crm_complt_contact_method]) // leads
				,
				SELECTCOLUMNS(accounts, "entity", "Accounts",  "sort", 2,  "_sys_docid", accounts[_sys_docid],  "_sys_user_id", accounts[trueai_owner_id],  "_sys_filter_start_date", accounts[_sys_filt_start_date],  
				 "crm_leadsource", accounts[crm_leadsource],
				 "trueai_leadsource", accounts[trueai_leadsource],
				 "trueai_leadsource_conf", accounts[trueai_leadsource_conf],
				 "trueai_leadsource_rule", accounts[trueai_leadsource_rule],
				 "crm_industry", accounts[crm_industry],
				 "trueai_industry", accounts[trueai_industry],
				 "trueai_industry_conf", accounts[trueai_industry_conf],
				 "trueai_industry_rule", accounts[trueai_industry_rule],
				 "crm_addr_city", accounts[crm_addr_city],
				 "trueai_addr_city", accounts[trueai_addr_city],
				 "crm_addr_state", accounts[crm_addr_state],
				 "trueai_addr_state", accounts[trueai_addr_state],
				 "crm_addr_country", accounts[crm_addr_country],
				 "trueai_addr_country", accounts[trueai_addr_country],
				  "crm_title", BLANK(),
				 "trueai_title_seniority", blank(),
				 "trueai_title_seniority_conf", BLANK(),
				 "trueai_title_function", BLANK(),
				 "trueai_title_dept_conf", BLANK(),
				 "trueai_title_concat", BLANK(),
				 "trueai_title_concat_conf", BLANK() ,
				"trueai_completeness_contact_method",  BLANK()) // accounts
				,
				SELECTCOLUMNS(opps, "entity", "Opps",  "sort", 3,  "_sys_docid", opps[_sys_docid],   "_sys_user_id", opps[trueai_owner_id], "_sys_filter_start_date", opps[_sys_filt_start_date],  
				 "crm_leadsource", opps[crm_leadsource],
				 "trueai_leadsource", opps[trueai_leadsource],
				 "trueai_leadsource_conf", opps[trueai_leadsource_conf],
				 "trueai_leadsource_rule", opps[trueai_leadsource_rule],
				 "crm_industry", blank(),
				 "trueai_industry", blank(),
				 "trueai_industry_conf", blank(),
				 "trueai_industry_rule", blank(),
				 "crm_addr_city", blank(),
				 "trueai_addr_city", blank(),
				 "crm_addr_state", blank(),
				 "trueai_addr_state", blank(),
				 "crm_addr_country", blank(),
				 "trueai_addr_country", blank(),
				 "crm_title", blank(),
				  "trueai_title_seniority", blank(),
				 "trueai_title_seniority_conf", blank(),
				 "trueai_title_function", blank(), 
				 "trueai_title_dept_conf", blank(),
				 "trueai_title_concat", blank(),
				 "trueai_title_concat_conf", blank(),
				 "trueai_completeness_contact_method", blank()) // opps
				,
				SELECTCOLUMNS(contacts, "entity", "Contacts",  "sort", 4,  "_sys_docid", contacts[_sys_doc_id],   "_sys_user_id", contacts[trueai_owner_id], "_sys_filter_start_date",DATEVALUE("" & contacts[crm_created_on]),  
				  "crm_leadsource", contacts[crm_leadsource],
				 "trueai_leadsource", contacts[trueai_leadsource],
				 "trueai_leadsource_conf", contacts[trueai_leadsource_conf],
				 "trueai_leadsource_rule", contacts[trueai_leadsource_rule],
				 "crm_industry", BLANK(),
				 "trueai_industry", BLANK(),
				 "trueai_industry_conf", BLANK(),
				 "trueai_industry_rule", BLANK(),
				 "crm_addr_city", BLANK(),
				 "trueai_addr_city", contacts[trueai_addr_city],
				 "crm_addr_state", BLANK(),
				 "trueai_addr_state", contacts[trueai_addr_state],
				 "crm_addr_country", BLANK(),
				 "trueai_addr_country", contacts[trueai_addr_country],
				 "crm_title", contacts[crm_title],
				 "trueai_title_seniority", contacts[trueai_title_seniority],
				 "trueai_title_seniority_conf", contacts[trueai_title_seniority_conf],
				 "trueai_title_function", contacts[trueai_title_department],
				 "trueai_title_dept_conf", contacts[trueai_title_department_conf],
				 "trueai_title_concat", contacts[trueai_title_department] & " - " & contacts[trueai_title_seniority],
				 "trueai_title_concat_conf", (contacts[trueai_title_department_conf] + contacts[trueai_title_seniority_conf]) /2 ,
				"trueai_completeness_contact_method", contacts[crm_complt_contact_method]) // contacts
				)
				
				```

	annotation PBI_Id = 7b5043ca5f114295843467acd4ea5476

