/// CRM entity for contact records enriched with TrueAI predictive insights.
table contacts
	lineageTag: e95d03ab-d655-415d-b942-9545f293c54c

	measure 'meas.contact_trueai_completeness_improvement' = ```
			
			var crmval = CALCULATE(AVERAGE([crm_complt]))
			var aival = CALCULATE(AVERAGE([trueai_complt]))
			var impro = Divide(aival - crmval, crmval) 
			var res = If(impro > 0, "+" & FORMAT( impro, "###%"),  "No change")
			return res 
			
			```
		formatString: 0 %
		displayFolder: _needs_atte
		lineageTag: b5bae688-efc8-42ef-bd98-83c8994f8390

	/// Id of the SSR document the record belongs to
	column _sys_ssr_id
		dataType: string
		lineageTag: ce00c989-b987-4057-9275-2b06ded62fec
		summarizeBy: none
		sourceColumn: _sys_ssr_id

		annotation SummarizationSetBy = Automatic

	/// Link to the contact in the remote system (such as Salesforce)
	column crm_deep_link
		dataType: string
		lineageTag: ecc627c3-8216-45c0-931a-3b90054bc6a7
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	/// Contact's first name
	column crm_first_name
		dataType: string
		lineageTag: 331f0bd3-79bf-4c77-88a9-14cd089d67ea
		summarizeBy: none
		sourceColumn: crm_first_name

		annotation SummarizationSetBy = Automatic

	/// Contact's last name
	column crm_last_name
		dataType: string
		lineageTag: 71934ea8-1719-47de-acc5-f22bfd20f488
		summarizeBy: none
		sourceColumn: crm_last_name

		annotation SummarizationSetBy = Automatic

	/// Contact's phone number
	column crm_phone
		dataType: string
		lineageTag: a14b43e4-ae67-4ddb-abd3-23218d4aa329
		summarizeBy: none
		sourceColumn: crm_phone

		annotation SummarizationSetBy = Automatic

	/// Contact's email
	column crm_email
		dataType: string
		lineageTag: 8805688c-9279-4004-a151-c795d388a821
		summarizeBy: none
		sourceColumn: crm_email

		annotation SummarizationSetBy = Automatic

	/// Contact's title in the CRM
	column crm_title
		dataType: string
		lineageTag: 8a159f8e-b947-410b-bbac-9c3f6e95a548
		summarizeBy: none
		sourceColumn: crm_title

		annotation SummarizationSetBy = Automatic

	/// Contact's salutation in the CRM
	column crm_salutation
		dataType: string
		lineageTag: 5bd4478f-1699-4ffa-8e2e-da0e6f6af6b6
		summarizeBy: none
		sourceColumn: crm_salutation

		annotation SummarizationSetBy = Automatic

	/// Contact's lead source in the CRM
	column crm_leadsource
		dataType: string
		lineageTag: 0d1acf56-24a6-4cc8-808e-4119ddf4d3e4
		summarizeBy: none
		sourceColumn: crm_leadsource

		annotation SummarizationSetBy = Automatic

	/// Contact's standardized lead source
	column trueai_leadsource
		dataType: string
		lineageTag: bba276f8-ee32-441e-bbf3-c617db0efac4
		summarizeBy: none
		sourceColumn: trueai_leadsource

		annotation SummarizationSetBy = Automatic

	/// Contact's standardized lead source prediction rule
	column trueai_leadsource_rule
		dataType: int64
		formatString: 0
		lineageTag: ad8db5db-5a21-43be-8fdb-c0293e39846b
		summarizeBy: sum
		sourceColumn: trueai_leadsource_rule

		annotation SummarizationSetBy = Automatic

	/// Unique record identifier, based on the ID of the document in the remote system (such as Salesforce ID)
	column _sys_doc_id
		dataType: string
		lineageTag: b98893c9-8572-40e0-ae85-a2b8fef87943
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// The end date of the record, stripped of time
	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 816c4a85-6786-4c2e-8223-669954dd09ff
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: acfe1570-ac49-4ab1-b7ed-8cb3bd07b4a2
			defaultHierarchy: LocalDateTable_b796b35a-1fcc-44c3-a1fe-8b7945a74123.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The start date of the record, stripped of time
	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 445aef34-4960-4923-bac9-cd37c986334f
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// CRM account id of the contact
	column crm_account_id
		dataType: string
		lineageTag: d4112359-7b7e-4762-ab60-17fb7bb71def
		summarizeBy: none
		sourceColumn: crm_account_id

		annotation SummarizationSetBy = Automatic

	/// Contact's city in the CRM
	column crm_addr_city
		dataType: string
		lineageTag: baec63ca-c2ec-460e-bd37-cf3ab417620b
		summarizeBy: none
		sourceColumn: crm_addr_city

		annotation SummarizationSetBy = Automatic

	/// Contact's country in the CRM
	column crm_addr_country
		dataType: string
		lineageTag: 91c07c5b-9b59-47dc-a209-2d8625de40f7
		summarizeBy: none
		sourceColumn: crm_addr_country

		annotation SummarizationSetBy = Automatic

	/// Contact's postal code in the CRM
	column crm_addr_postal_code
		dataType: string
		lineageTag: c191c6ea-9672-42a9-ab60-72d8e2723ee0
		summarizeBy: none
		sourceColumn: crm_addr_postal_code

		annotation SummarizationSetBy = Automatic

	/// Contact's state in the CRM
	column crm_addr_state
		dataType: string
		lineageTag: 95f9f35e-52f5-46a0-85b3-b412eb9d93bb
		summarizeBy: none
		sourceColumn: crm_addr_state

		annotation SummarizationSetBy = Automatic

	/// Contact's street in the CRM
	column crm_addr_street
		dataType: string
		lineageTag: 211e9794-9a76-4dd3-b077-e09c08fbff4c
		summarizeBy: none
		sourceColumn: crm_addr_street

		annotation SummarizationSetBy = Automatic

	/// Contact's completeness score based on the CRM data
	column crm_complt
		dataType: double
		lineageTag: a350d20f-26e9-448b-84cf-4a659dba24c1
		summarizeBy: sum
		sourceColumn: crm_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact's contact information completeness score based on the CRM data
	column crm_complt_contact
		dataType: double
		lineageTag: 974eb3ba-2242-4da7-bc1d-53a68913520b
		summarizeBy: sum
		sourceColumn: crm_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact's contact method completeness score based on the CRM data
	column crm_complt_contact_method
		dataType: double
		lineageTag: 5ef751b0-d288-45a0-92b6-fc163659f91e
		summarizeBy: sum
		sourceColumn: crm_complt_contact_method

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact's location completeness score based on the CRM data
	column crm_complt_geo
		dataType: double
		lineageTag: 4a9eacaf-c681-45ab-83f5-4cc24dd1b54d
		summarizeBy: sum
		sourceColumn: crm_complt_geo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact's marketing completeness score based on the CRM data
	column crm_complt_marketing
		dataType: double
		lineageTag: 4302ba42-f7ec-4ebb-bd52-89217c495d8a
		summarizeBy: sum
		sourceColumn: crm_complt_marketing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact creator's id in the CRM
	column crm_creator_id
		dataType: string
		lineageTag: 05aa60af-817a-4984-acd8-4dfa513ce371
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	/// Contact's last activity time in the CRM
	column crm_last_act_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 25d495b2-faf9-4b1e-94ba-171811168aa2
		summarizeBy: none
		sourceColumn: crm_last_act_time

		variation Variation
			isDefault
			relationship: 0f4ad1ce-10a7-400a-894c-e6876525ca57
			defaultHierarchy: LocalDateTable_4a533cf9-0999-4765-b7bb-cf37ad970107.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Contact owner's id in the CRM
	column crm_owner_id
		dataType: string
		lineageTag: a726c901-0d28-4fbf-b930-0683c0b089e4
		summarizeBy: none
		sourceColumn: crm_owner_id

		annotation SummarizationSetBy = Automatic

	/// Contact's city
	column trueai_addr_city
		dataType: string
		lineageTag: a996bf99-b305-4456-a459-32192dd8626a
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	/// Contact's country
	column trueai_addr_country
		dataType: string
		lineageTag: 16253b95-cdd9-4c41-9e77-ca383bc681fc
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	/// Contact's postal code
	column trueai_addr_postal_code
		dataType: string
		lineageTag: 895c1991-201a-4b96-b263-078ce52ce9da
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	/// Contact's address prediction rule
	column trueai_addr_rule
		dataType: int64
		formatString: 0
		lineageTag: ecab651f-1073-4858-a7f3-f56116cd5976
		summarizeBy: sum
		sourceColumn: trueai_addr_rule

		annotation SummarizationSetBy = Automatic

	/// Contact's state
	column trueai_addr_state
		dataType: string
		lineageTag: 31c370f4-e853-43ff-af7d-52fbfe3aaeac
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	/// Contact's street
	column trueai_addr_street
		dataType: string
		lineageTag: 03e52dc4-d6fc-41aa-9fb2-d0d1d3c77cb9
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	/// Completeness score of the contact based on the standardized data
	column trueai_complt
		dataType: double
		lineageTag: 1b21281e-3a05-4145-8e26-202f6548042a
		summarizeBy: sum
		sourceColumn: trueai_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact information completeness score of the contact based on the standardized data
	column trueai_complt_contact
		dataType: double
		lineageTag: db37d6a5-7540-45e9-997f-2d8b51321d0b
		summarizeBy: sum
		sourceColumn: trueai_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact method completeness score of the contact based on the standardized data
	column trueai_complt_contact_method
		dataType: double
		lineageTag: 1ab35eaf-6213-4fa7-89e7-1ec42e998f62
		summarizeBy: sum
		sourceColumn: trueai_complt_contact_method

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Location completeness score of the contact based on the standardized data
	column trueai_complt_geo
		dataType: double
		lineageTag: ed517df7-df1d-4058-b5f0-e8f269e0cb9f
		summarizeBy: sum
		sourceColumn: trueai_complt_geo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Marketing completeness score of the contact based on the standardized data
	column trueai_complt_marketing
		dataType: double
		lineageTag: 78f7e7ee-acc7-4095-bd9c-dbc9fcf77b8e
		summarizeBy: sum
		sourceColumn: trueai_complt_marketing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact creator's id
	column trueai_creator_id
		dataType: string
		lineageTag: 6d864b18-5883-4b35-a982-b77bb7045957
		summarizeBy: none
		sourceColumn: trueai_creator_id

		annotation SummarizationSetBy = Automatic

	/// Contact's standardized lead source prediction confidence
	column trueai_leadsource_conf
		dataType: double
		lineageTag: a0907482-bfae-43ca-a5c4-dddadfbbc8b0
		summarizeBy: sum
		sourceColumn: trueai_leadsource_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact owner's id
	column trueai_owner_id
		dataType: string
		lineageTag: 78479c90-af82-4ff9-97ed-6d5754adbe5e
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	/// Contact's standardized seniority
	column trueai_title_seniority
		dataType: string
		lineageTag: ada25ab0-9820-4e7b-8cf6-b8412d772fe7
		summarizeBy: none
		sourceColumn: trueai_title_seniority

		annotation SummarizationSetBy = Automatic

	/// Contact's standardized seniority prediction confidence
	column trueai_title_seniority_conf
		dataType: double
		lineageTag: 219c071b-ed64-451c-b5e8-7fbbf202303a
		summarizeBy: sum
		sourceColumn: trueai_title_seniority_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column 'col.expected_usefulness' = ```.
	column 'col.expected_usefulness' = ```
			
			// var asof = contacts[_sys_as_of]
			// var days_since_edit =  asof - contacts[crm_created_on]
			// var age_coeff = 3
			// var max_age_days = 8000
			// var age_score = ((max_age_days - days_since_edit) / max_age_days) ^ age_coeff
			// var days_since_last_engagement = If(ISBLANK(contacts[trueai_last_engmt]), 100000, asof - contacts[trueai_last_engmt])
			// var days_since_last_act = If(ISBLANK(contacts[trueai_last_engmt]), 100000, asof - contacts[trueai_last_engmt])
			// var act_adjustment = IF(days_since_last_engagement < 360, 1.5, IF( days_since_last_engagement < 720 ,1.2, 1))
			// var final_score = age_score * act_adjustment
			
			// var res = IF(final_score > 1, 1, if(final_score < 0, 0, final_score))
			// return res 
			```
		dataType: double
		lineageTag: d0835c4f-adf5-4626-ba7f-176248b4b0b0
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact's latitude
	column trueai_addr_lat
		dataType: double
		lineageTag: c08c2c48-038f-4d33-be0b-29510fba893c
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact's longitude
	column trueai_addr_long
		dataType: double
		lineageTag: a5854470-9e0f-4a05-833f-8c5c15694142
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The date of the last data request from the platform
	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: 0a360da9-a9ea-421c-82c8-4fe45c00b1b6
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 398b615b-bf9a-44c6-9f23-33d3ee6fdc7e
			defaultHierarchy: LocalDateTable_c43921df-cedf-4c21-b0b7-7898b5f3a594.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// The date of the last data modification in the platform
	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: c5892cf6-2754-413d-9617-34c7c64c4168
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 6a7ea999-3ba2-4b28-920c-1d4232c0d0e6
			defaultHierarchy: LocalDateTable_c024516e-04e3-447a-90b9-290c9b848de2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Contact creation date in the CRM
	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: a4b91601-e02f-43ad-9860-8236ac6dd77f
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 80a9732b-3d27-49f9-b24d-b6a91aa0b431
			defaultHierarchy: LocalDateTable_9e41b2cf-00e4-404f-8f04-d124d761ea8e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Contact modified on date in the CRM
	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: e193f3a6-2a72-4f01-996e-2b9017c0d80c
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: 9b8aba4f-ab95-4ef0-b2eb-637abd56cc2f
			defaultHierarchy: LocalDateTable_8589979e-67fa-4f9f-a239-a9c61d6fd2c9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Contact creation date
	column trueai_created_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: e35f9a7a-f7c8-44bd-9d48-3d1e8013ee4f
		summarizeBy: none
		sourceColumn: trueai_created_on

		variation Variation
			isDefault
			relationship: f3494388-1d12-4606-9615-729d38838e22
			defaultHierarchy: LocalDateTable_c4f7d582-bea9-48e1-a86e-d0484b5519a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Test model
	column trueai_test
		dataType: string
		lineageTag: 50b2341c-31e9-4938-b6a7-c1695cd3c38a
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	/// Test model confidence
	column trueai_test_conf
		dataType: double
		lineageTag: 7a9dc1c4-9289-4abb-ae89-2d5e322dfdc3
		summarizeBy: sum
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Test model rule
	column trueai_test_rule
		dataType: string
		lineageTag: 54e48af1-eb30-4bbe-a2b2-4771f9e07657
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	/// Test model debug information
	column trueai_test_debug
		dataType: string
		lineageTag: e6c1e9d8-668c-4177-aed7-a00711b7b550
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	/// cust_text1
	column cust_text1
		dataType: string
		lineageTag: bc16dec5-5cc2-419f-bd32-42165236f556
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	/// cust_text2
	column cust_text2
		dataType: string
		lineageTag: 9928d585-abcb-44e9-ab34-4e5ee7c1c7b2
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	/// cust_text3
	column cust_text3
		dataType: string
		lineageTag: 2c120d05-533a-4cf1-9f88-872bd301621a
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	/// cust_text4
	column cust_text4
		dataType: string
		lineageTag: 739d4f4e-96bf-43e3-aae5-b2fce0cbb10f
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	/// cust_text5
	column cust_text5
		dataType: string
		lineageTag: eb2582f0-cfcc-40b0-93e2-82a25cb19246
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	/// cust_num1
	column cust_num1
		dataType: double
		lineageTag: ed1a0f0e-a392-4bbd-b64d-8479e198aa99
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num2
	column cust_num2
		dataType: double
		lineageTag: 27747d37-0d4a-4f08-8a8c-78ccea89a269
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num3
	column cust_num3
		dataType: double
		lineageTag: 9d0b34e2-49bc-4cfa-a9c7-d4f20f996e5e
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num4
	column cust_num4
		dataType: double
		lineageTag: 87901ffd-756d-47bd-a58d-664ed4e33d08
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num5
	column cust_num5
		dataType: double
		lineageTag: a94dd129-f63e-47d2-9686-15055085a15d
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num6
	column cust_num6
		dataType: double
		lineageTag: 456972e2-69ef-423c-bd45-59d2c6270c2a
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num7
	column cust_num7
		dataType: double
		lineageTag: c2197821-9a6f-4cbd-b95f-eda5e0ea4419
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_bool1
	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6f9be1db-58cb-4926-b34e-9182c903a807
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	/// cust_bool2
	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 351df501-7a93-46a3-9bfe-aef550fcb915
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	/// Contact's standardized department
	column trueai_title_department
		dataType: string
		lineageTag: a5ed7e63-6839-4d6b-a60e-e60a7094e348
		summarizeBy: none
		sourceColumn: trueai_title_department

		annotation SummarizationSetBy = Automatic

	/// Contact's standardized department prediction confidence
	column trueai_title_department_conf
		dataType: double
		lineageTag: b8578ec5-562b-47e6-871c-5c291c4403f1
		summarizeBy: sum
		sourceColumn: trueai_title_department_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition contacts-21a2a49f-4ba9-40c8-a889-ed2c60393586 = m
		mode: import
		source =
				let
				
				  dbTable = getDBTable("contacts"), // get the right table
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				      {"_sys_as_of", type datetime},
				      {"_sys_doc_id", type text},
				      {"_sys_filt_end_date", type date},
				      {"_sys_filt_start_date", type date},
				      {"_sys_last_modified_on", type datetime},
				      {"_sys_ssr_id", type text},
				      {"crm_account_id", type text},
				      {"crm_addr_city", type text},
				      {"crm_addr_country", type text},
				      {"crm_addr_postal_code", type text},
				      {"crm_addr_state", type text},
				      {"crm_addr_street", type text},
				      {"crm_complt", type number},
				      {"crm_complt_contact", type number},
				      {"crm_complt_contact_method", type number},
				      {"crm_complt_geo", type number},
				      {"crm_complt_marketing", type number},
				      {"crm_created_on", type datetime},
				      {"crm_creator_id", type text},
				      {"crm_deep_link", type text},
				      {"crm_email", type text},
				      {"crm_first_name", type text},
				      {"crm_last_act_time", type datetime},
				      {"crm_last_name", type text},
				      {"crm_leadsource", type text},
				      {"crm_modified_on", type datetime},
				      {"crm_owner_id", type text},
				      {"crm_phone", type text},
				      {"crm_salutation", type text},
				      {"crm_title", type text},
				      {"cust_bool1", type logical},
				      {"cust_bool2", type logical},
				      {"cust_num1", type number},
				      {"cust_num2", type number},
				      {"cust_num3", type number},
				      {"cust_num4", type number},
				      {"cust_num5", type number},
				      {"cust_num6", type number},
				      {"cust_num7", type number},
				      {"cust_text1", type text},
				      {"cust_text2", type text},
				      {"cust_text3", type text},
				      {"cust_text4", type text},
				      {"cust_text5", type text},
				      {"trueai_addr_city", type text},
				      {"trueai_addr_country", type text},
				      {"trueai_addr_lat", type number},
				      {"trueai_addr_long", type number},
				      {"trueai_addr_postal_code", type text},
				      {"trueai_addr_rule", Int64.Type},
				      {"trueai_addr_state", type text},
				      {"trueai_addr_street", type text},
				      {"trueai_complt", type number},
				      {"trueai_complt_contact", type number},
				      {"trueai_complt_contact_method", type number},
				      {"trueai_complt_geo", type number},
				      {"trueai_complt_marketing", type number},
				      {"trueai_created_on", type date},
				      {"trueai_creator_id", type text},
				      {"trueai_leadsource", type text},
				      {"trueai_leadsource_conf", type number},
				      {"trueai_leadsource_rule", Int64.Type},
				      {"trueai_owner_id", type text},
				      {"trueai_test", type text},
				      {"trueai_test_conf", type number},
				      {"trueai_test_debug", type text},
				      {"trueai_test_rule", type text},
				      {"trueai_title_department", type text},
				      {"trueai_title_department_conf", type number},
				      {"trueai_title_seniority", type text},
				      {"trueai_title_seniority_conf", type number}
				
				
				
				   })
				in
				dbTableTyped

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

