/// Table 'Last Refresh Date'.
table 'Last Refresh Date'
	lineageTag: 6cef7a97-bc04-4557-ba57-c8550f75fec3

	/// Purpose: Compute the measure result from the DAX expression and current filter context.
	/// Calculation Logic: No VAR blocks. Dependencies: Measures: [Last Refresh Date].
	/// Dynamic Behavior: Uses CALCULATE/CALCULATETABLE to modify filter context with its filter arguments.
	/// Format/Type: General Date
	measure 'meas.last_refresh_date' = CALCULATE(MAX('Last Refresh Date'[Last Refresh Date]))
		formatString: General Date
		lineageTag: 53cdffaa-301b-4375-89c9-a560adaa4828

	/// Column 'Last Refresh Date'.
		annotation AgentPurpose = "Tracks last refresh date."
		annotation AgentLogic = "Returns an extreme value from 'Last Refresh Date'[Last Refresh Date] under filters."
		annotation AgentDependencies = "Columns: 'Last Refresh Date'[Last Refresh Date]"
		annotation AgentContext = "Evaluated in current filter context unless overridden in DAX."
		annotation AgentOutput = "Text"
	column 'Last Refresh Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 295cab28-1cd6-414b-8131-f4faa3aa66b9
		summarizeBy: none
		sourceColumn: Last Refresh Date

		variation Variation
			isDefault
			relationship: 1ec07016-aabf-4793-8874-b50f9a7414e3
			defaultHierarchy: LocalDateTable_97ae4aef-e70f-45ab-b7ec-7b59aaf30742.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Last Refresh Date' = m
		mode: import
		source =
				let
				    Source = DateTimeZone.UtcNow(),
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Last Refresh Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

