table metadata_reference_values
	lineageTag: 5ec3a8ec-d1e5-486c-8913-90236cd4aca1

	column _sys_doc_id
		dataType: string
		lineageTag: d5a493e8-638f-4903-af6c-fffd61bcadea
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_is_active
		dataType: string
		lineageTag: fe89c3a0-1608-440f-8cfd-423f3d935152
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	column _sys_added_on
		dataType: dateTime
		formatString: General Date
		lineageTag: fb259560-1f94-4e33-b32e-c66d26485189
		summarizeBy: none
		sourceColumn: _sys_added_on

		variation Variation
			isDefault
			relationship: 74aa8f86-061e-4068-8862-58521896a199
			defaultHierarchy: LocalDateTable_6d587d3a-0337-4fca-89aa-b4b8a41378ad.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_added_by
		dataType: string
		lineageTag: 6ff0f93a-f02d-4cbf-8e2f-60aa283395c7
		summarizeBy: none
		sourceColumn: _sys_added_by

		annotation SummarizationSetBy = Automatic

	column _sys_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 29926c0d-ffa9-420d-814e-7749d1bde118
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: 6262ccb7-9642-4b3f-b35a-d197b2e6e26b
			defaultHierarchy: LocalDateTable_48379972-0a79-4ef0-8873-b26d55fb5b4a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column value_category
		dataType: string
		lineageTag: 3ef70eb1-91e2-4ef1-8f14-6d896fa02e6c
		summarizeBy: none
		sourceColumn: value_category

		annotation SummarizationSetBy = Automatic

	column related_to_record
		dataType: string
		lineageTag: 3fc11fd8-ac18-4871-82dc-802a9e262e25
		summarizeBy: none
		sourceColumn: related_to_record

		annotation SummarizationSetBy = Automatic

	column value_name
		dataType: string
		lineageTag: b912af68-9b82-48e8-bc22-c18604d00d21
		summarizeBy: none
		sourceColumn: value_name

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		lineageTag: f7c0b122-6421-48b8-b161-1b575fac00a7
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column supporting_value_1_name
		dataType: string
		lineageTag: d260c8e6-f6f4-4734-9d1d-c3a1f311c701
		summarizeBy: none
		sourceColumn: supporting_value_1_name

		annotation SummarizationSetBy = Automatic

	column supporting_value_1
		dataType: double
		lineageTag: 76f47fe0-916f-4d04-a90c-9b7105f94297
		summarizeBy: sum
		sourceColumn: supporting_value_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column supporting_value_2_name
		dataType: string
		lineageTag: 55c451af-a550-444f-a0c1-fedbf2f58931
		summarizeBy: none
		sourceColumn: supporting_value_2_name

		annotation SummarizationSetBy = Automatic

	column supporting_value_2
		dataType: double
		lineageTag: e192489f-9761-4435-ad39-a5888eb4cdbb
		summarizeBy: sum
		sourceColumn: supporting_value_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column supporting_value_3_name
		dataType: string
		lineageTag: 6ef16aca-ed0f-45bd-bd3d-051bb07b7522
		summarizeBy: none
		sourceColumn: supporting_value_3_name

		annotation SummarizationSetBy = Automatic

	column supporting_value_3
		dataType: double
		lineageTag: 34773097-e409-494a-8bc7-0ebd82f8dc25
		summarizeBy: sum
		sourceColumn: supporting_value_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column applies_to_industry
		dataType: string
		lineageTag: f37619b9-9764-4355-b54d-71716e698a07
		summarizeBy: none
		sourceColumn: applies_to_industry

		annotation SummarizationSetBy = Automatic

	column applies_to_co_size
		dataType: string
		lineageTag: d9cd4b8a-7e06-4e60-a44f-c2adcf6a0531
		summarizeBy: none
		sourceColumn: applies_to_co_size

		annotation SummarizationSetBy = Automatic

	column applies_to_geo
		dataType: string
		lineageTag: 0ae3abfd-108d-4f23-8eaa-dabfad315e7b
		summarizeBy: none
		sourceColumn: applies_to_geo

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: f233fd82-e43f-40c6-97df-9c3f49ad3aca
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	partition metadata_reference_values = m
		mode: import
		source = ```
				let
				  
				  dbTable = getDBTable("metadata_reference_values"),          // get the right table
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				      {"_sys_added_by", type text},
				      {"_sys_added_on", type datetime},
				      {"_sys_doc_id", type text},
				      {"_sys_is_active", type text},
				      {"_sys_modified_on", type datetime},
				      {"applies_to_co_size", type text},
				      {"applies_to_geo", type text},
				      {"applies_to_industry", type text},
				      {"comments", type text},
				      {"related_to_record", type text},
				      {"supporting_value_1", type number},
				      {"supporting_value_1_name", type text},
				      {"supporting_value_2", type number},
				      {"supporting_value_2_name", type text},
				      {"supporting_value_3", type number},
				      {"supporting_value_3_name", type text},
				      {"value", type number},
				      {"value_category", type text},
				      {"value_name", type text}
				    })     
				
				in
				    dbTableTyped
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

