/// Reference list for iconography and graphic assets used in the platform interface.
table metadata_graphics
	description: "One row per metadata_graphic record. Source fields include System prefixes. Related to LocalDateTable_fb0fca32-b454-41cd-84fa-153aca6b86b8 (_sys_modified_on -> Date)."
	lineageTag: 082acf99-4fd2-4404-830d-dcb1f51e99f5

	/// Graphic image
	column _sys_base64
		description: "System: Text label for base64."
		dataType: string
		lineageTag: f41f5d29-49ae-4ab5-a734-78009136dfb6
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: _sys_base64

		annotation SummarizationSetBy = Automatic

	/// Graphic dimensions
	column _sys_dimensions
		description: "System: Text label for dimensions."
		dataType: string
		lineageTag: 539ff6df-d240-4b3d-ad81-a215e436a857
		summarizeBy: none
		sourceColumn: _sys_dimensions

		annotation SummarizationSetBy = Automatic

	/// Unique graphic identifier
	column _sys_doc_id
		description: "System: Identifier for doc."
		dataType: string
		lineageTag: a0004065-cabb-4a5c-bc6a-f0864c564bb4
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Graphic name
	column _sys_name
		description: "System: Text label for name."
		dataType: string
		lineageTag: fe3e7ddb-3940-4735-8929-15d84b0a1ab3
		summarizeBy: none
		sourceColumn: _sys_name

		annotation SummarizationSetBy = Automatic

	/// Graphic URL
	column _sys_url
		description: "System: Text label for url."
		dataType: string
		lineageTag: 5dbfb125-46b7-409d-af0f-94bcfd63a6be
		summarizeBy: none
		sourceColumn: _sys_url

		annotation SummarizationSetBy = Automatic

	/// Notes related to the graphic
	column notes
		description: "Text label for notes."
		dataType: string
		lineageTag: 7a87b03d-7afa-47de-bed8-4cbb36947ae8
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	/// Is Active
	column _sys_is_active
		description: "System: Indicates whether is active."
		dataType: string
		lineageTag: 29282e56-8a1b-4be9-8878-1bcdf741dde3
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// Modified On Date
	column _sys_modified_on
		description: "System: Date/time when modified on."
		dataType: dateTime
		formatString: General Date
		lineageTag: ff207ee0-7f2a-4e0c-87fc-d350c288bb7a
		summarizeBy: none
		sourceColumn: _sys_modified_on

		variation Variation
			isDefault
			relationship: 40165edf-5d3b-4b18-a803-2c5773392683
			defaultHierarchy: LocalDateTable_fb0fca32-b454-41cd-84fa-153aca6b86b8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition metadata_graphics = m
		mode: import
		source =
				let
				  dbTable = getDBTable("metadata_graphics"), // get the right table
				
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				    {"_sys_base64", type text},
				    {"_sys_dimensions", type text},
				    {"_sys_doc_id", type text},
				    {"_sys_is_active", type text},
				    {"_sys_modified_on", type datetime},
				    {"_sys_name", type text},
				    {"_sys_url", type text},
				    {"notes", type text}
				
				
				
				  })
				in
				    dbTableTyped

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

