/// Derived entity synthesizing Opportunities and Opportunity History. Engineered to resolve CRM history gaps to ensure a continuous, reconstructible history record for every opportunity.
table open_pipeline
	lineageTag: 63e68162-90ed-40cd-8e52-99f2a6d679a2

	/// The date of the last data request from the platform
	column _sys_as_of
		dataType: dateTime
		formatString: Short Date
		lineageTag: 84c24770-04d5-464e-a640-80d113916b47
		summarizeBy: none
		sourceColumn: _sys_as_of

		annotation SummarizationSetBy = Automatic

	/// The end date of the record, stripped of time
	column _sys_filt_end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4a2b3a16-6caf-448b-97d0-b89705d4a70e
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The start date of the record, stripped of time
	column _sys_filt_start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5c3452b5-751c-4957-87f6-fc6a034c2d04
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Opportunity's booking amount in the CRM
	column crm_booking_amt
		dataType: double
		lineageTag: a7ab38e7-7bd8-45db-bb44-69c4b7610fb1
		summarizeBy: sum
		sourceColumn: crm_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's close date in the CRM
	column crm_close_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: b021503a-2e22-41cc-9f37-d47159daaeca
		summarizeBy: none
		sourceColumn: crm_close_date

		annotation SummarizationSetBy = Automatic

	/// Opportunity's creation date in the CRM
	column crm_created_on
		dataType: dateTime
		formatString: Short Date
		lineageTag: c0c04d63-3c6e-4287-84ed-197863ad7cbf
		summarizeBy: none
		sourceColumn: crm_created_on

		annotation SummarizationSetBy = Automatic

	/// Opportunity's creator's id in the CRM
	column crm_creator_id
		dataType: string
		lineageTag: 494afd3f-f2e0-4ceb-a0b9-f3443d5b5e50
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's id in the CRM
	column crm_opp_id
		dataType: string
		lineageTag: 93982bca-9859-4daf-a8ed-156b4116a9c8
		summarizeBy: none
		sourceColumn: crm_opp_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage name in the CRM
	column crm_stage_name
		dataType: string
		lineageTag: 39e0679f-55fa-4214-ba46-2e60c6db3f6d
		summarizeBy: none
		sourceColumn: crm_stage_name
		sortByColumn: trueai_stage_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage number in the CRM
	column crm_stage_num
		dataType: string
		lineageTag: 7108c05b-c9ec-49e4-928b-8306a3b40ffb
		summarizeBy: none
		sourceColumn: crm_stage_num

		annotation SummarizationSetBy = Automatic

	/// Opportunity's booking amount
	column trueai_booking_amt
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e3654569-5198-42f6-976e-9e3f9bf085ff
		summarizeBy: sum
		sourceColumn: trueai_booking_amt

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is won
	column trueai_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 727dc425-47c4-4aa5-a460-8e57d31b12a2
		summarizeBy: none
		sourceColumn: trueai_is_won

		annotation SummarizationSetBy = Automatic

	/// Opportunity's normalized stage
	column trueai_stage
		dataType: string
		lineageTag: c17ed2a6-cfca-487a-ac22-9503016d5f4a
		summarizeBy: none
		sourceColumn: trueai_stage
		sortByColumn: trueai_stage_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// cust_text1
	column cust_text1
		dataType: string
		lineageTag: 8f57c040-d45f-4d28-a473-b7ae83e69aac
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	/// cust_text2
	column cust_text2
		dataType: string
		lineageTag: d3257e95-78c9-4e2e-bfff-5d015ae5c915
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	/// cust_text3
	column cust_text3
		dataType: string
		lineageTag: fc4b49db-8ddc-445d-8138-675c178fa5d4
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	/// cust_text4
	column cust_text4
		dataType: string
		lineageTag: e9b1480c-d57a-40aa-85b0-45760008f056
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	/// cust_text5
	column cust_text5
		dataType: string
		lineageTag: 916899fd-466f-4c8f-80d7-fcb22780f7e3
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	/// cust_num1
	column cust_num1
		dataType: double
		lineageTag: 1cf5190a-c739-410d-8672-e8ff0973aead
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num2
	column cust_num2
		dataType: double
		lineageTag: 7f1e3962-4286-4dff-95ab-40aacb3a7d26
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num3
	column cust_num3
		dataType: double
		lineageTag: 896ccf0e-7518-4c84-8a41-50098cabd965
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num4
	column cust_num4
		dataType: double
		lineageTag: 4c00df42-2f71-490c-937b-ed53235548fe
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num5
	column cust_num5
		dataType: double
		lineageTag: d863f2c3-d442-4ef5-a7f2-0e8d0979ce99
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num6
	column cust_num6
		dataType: double
		lineageTag: e6d6a9ca-43ba-4b90-8daa-2237c3d103bd
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num7
	column cust_num7
		dataType: double
		lineageTag: 28d39190-860c-438b-ab66-9181b90c5eff
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_bool1
	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 63f7944c-5262-4e42-94ad-3c73020d389a
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	/// cust_bool2
	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c9709a3e-9d8e-4613-b037-16e184dc65ef
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	/// Ordinal number based on the position of the step in the sequence
	column trueai_step_sequence
		dataType: int64
		formatString: 0
		lineageTag: 31663b45-26e1-4adf-8e87-f498a1e56124
		summarizeBy: sum
		sourceColumn: trueai_step_sequence

		annotation SummarizationSetBy = Automatic

	/// Unique record identifier, based on the ID of the opp in the remote system (such as Salesforce ID) and date
	column _sys_doc_id
		dataType: string
		lineageTag: 7914c411-03dd-4a71-8ac6-9e3b59348131
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Activities Count
	column trueai_act_count
		dataType: int64
		formatString: 0
		lineageTag: 30dfadc6-f2b0-4727-99b4-9bc0e8f66632
		summarizeBy: sum
		sourceColumn: trueai_act_count

		annotation SummarizationSetBy = Automatic

	/// Activities Duration
	column trueai_act_dur
		dataType: double
		lineageTag: f6face08-bd35-4899-b1b0-400d1e7326d2
		summarizeBy: sum
		sourceColumn: trueai_act_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Engaged Count
	column trueai_act_eng_count
		dataType: int64
		formatString: 0
		lineageTag: dece7dd9-e5a3-44d9-a6a1-6aa742ba4e27
		summarizeBy: sum
		sourceColumn: trueai_act_eng_count

		annotation SummarizationSetBy = Automatic

	/// Activities Engaged Duration
	column trueai_act_eng_dur
		dataType: double
		lineageTag: b27ae1b9-dcf3-4ae3-aa2a-d1114a7bff1e
		summarizeBy: sum
		sourceColumn: trueai_act_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Column trueai_stage_num.
	column trueai_stage_num
		dataType: int64
		formatString: 0
		lineageTag: dea5d0ac-bfdf-4814-9bf3-3a56c97060c7
		summarizeBy: sum
		sourceColumn: trueai_stage_num

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the record is redundant
	column trueai_can_be_excluded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7a312381-3cb6-4767-b9c1-296dfc5e5a03
		summarizeBy: none
		sourceColumn: trueai_can_be_excluded

		annotation SummarizationSetBy = Automatic

	/// Current probability of win of the opportunity
	column trueai_current_prob_of_win
		dataType: double
		lineageTag: a83f703e-0b45-4cb0-85b9-e96c24ea7d01
		summarizeBy: sum
		sourceColumn: trueai_current_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Boolean flag that indicates whether the opportunity is closed
	column trueai_is_closed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b39fc385-703a-45ec-8162-08af49dcdcd2
		summarizeBy: none
		sourceColumn: trueai_is_closed

		annotation SummarizationSetBy = Automatic

	/// Stage Owner Prep Factor
	column trueai_owner_prep_factor
		dataType: double
		lineageTag: 11b787c2-dc72-4a6a-a47f-de4ddfc71b1d
		summarizeBy: sum
		sourceColumn: trueai_owner_prep_factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Stage Owner Activity Capture Level
	column trueai_owner_act_capt_lvl
		dataType: double
		lineageTag: 8e2b4033-afbe-4d3c-9c9f-c626065a0af2
		summarizeBy: sum
		sourceColumn: trueai_owner_act_capt_lvl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Stage Owner Activity Capture Level Confidence
	column trueai_owner_act_capt_lvl_conf
		dataType: double
		lineageTag: 9dc4ff5e-3bfb-4ea4-8298-55260ff334be
		summarizeBy: sum
		sourceColumn: trueai_owner_act_capt_lvl_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Automated Email Count
	column trueai_act_type_auto_email_count
		dataType: int64
		formatString: 0
		lineageTag: fec509b9-2090-4688-83f2-a75ceb55c3ce
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_count

		annotation SummarizationSetBy = Automatic

	/// Activities Automated Email Duration
	column trueai_act_type_auto_email_dur
		dataType: double
		lineageTag: b6aa685e-4fb6-4acb-8b15-bcd081783d05
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Automated Email Engaged Count
	column trueai_act_type_auto_email_eng_count
		dataType: int64
		formatString: 0
		lineageTag: ac556dd3-6a8e-4ca4-8775-4353fd4133c9
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_eng_count

		annotation SummarizationSetBy = Automatic

	/// Activities Call Count
	column trueai_act_type_call_count
		dataType: int64
		formatString: 0
		lineageTag: e6b7ea6c-15ce-4d61-b861-4f54c8be953a
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_count

		annotation SummarizationSetBy = Automatic

	/// Activities Call Duration
	column trueai_act_type_call_dur
		dataType: double
		lineageTag: 65e500d7-c167-407b-94ad-4522436920a4
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Call Engaged Count
	column trueai_act_type_call_eng_count
		dataType: int64
		formatString: 0
		lineageTag: e3a3f6aa-70fe-45ca-be3e-c710f6e6f052
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_eng_count

		annotation SummarizationSetBy = Automatic

	/// Activities Email Count
	column trueai_act_type_email_count
		dataType: int64
		formatString: 0
		lineageTag: bc1feca5-6286-47a4-a7c0-6fe0d53afa67
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_count

		annotation SummarizationSetBy = Automatic

	/// Activities Email Duration
	column trueai_act_type_email_dur
		dataType: double
		lineageTag: 6508514d-f2d8-4515-a3b9-c7ebe949a71b
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Email Engaged Count
	column trueai_act_type_email_eng_count
		dataType: int64
		formatString: 0
		lineageTag: f9a64fba-f629-418f-97c9-c05811b5eaaf
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_eng_count

		annotation SummarizationSetBy = Automatic

	/// Activities Meeting Count
	column trueai_act_type_meeting_count
		dataType: int64
		formatString: 0
		lineageTag: 2ffac20e-1983-447e-8a2b-136cfd11f930
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_count

		annotation SummarizationSetBy = Automatic

	/// Activities Meeting Durationuratin
	column trueai_act_type_meeting_dur
		dataType: double
		lineageTag: 63fb6b62-6271-4f6c-ab69-470e671eeedc
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Meeting Engaged Count
	column trueai_act_type_meeting_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 604dfd3f-b77e-461d-bf33-21f40bb109c0
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_eng_count

		annotation SummarizationSetBy = Automatic

	/// Activities Non Determinable Count
	column trueai_act_type_nd_count
		dataType: int64
		formatString: 0
		lineageTag: 0033078f-30f7-465b-be9e-ac4e047dfdc5
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_count

		annotation SummarizationSetBy = Automatic

	/// Activities Non Determinable Duration
	column trueai_act_type_nd_dur
		dataType: double
		lineageTag: 907ceb27-9e2e-4e04-8416-e80397279002
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Non Determinable Engaged Count
	column trueai_act_type_nd_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 1d32d31a-d978-4845-8d51-49caebdf5fd9
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_eng_count

		annotation SummarizationSetBy = Automatic

	/// Activities No Interaction Count
	column trueai_act_type_no_interaction_count
		dataType: int64
		formatString: 0
		lineageTag: c679b5ba-f268-457b-bc13-72d7fdb2529b
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_count

		annotation SummarizationSetBy = Automatic

	/// Activities No Interaction Duration
	column trueai_act_type_no_interaction_dur
		dataType: double
		lineageTag: 53d03c90-02e1-496e-8045-1001a254b42c
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities No Interaction Engaged Count
	column trueai_act_type_no_interaction_eng_count
		dataType: int64
		formatString: 0
		lineageTag: d500819e-63b7-4bd2-a303-77cfa9b6c373
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_eng_count

		annotation SummarizationSetBy = Automatic

	/// Activities Social Count
	column trueai_act_type_social_count
		dataType: int64
		formatString: 0
		lineageTag: b01b755f-3d94-4dde-8942-e57a26fb3505
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_count

		annotation SummarizationSetBy = Automatic

	/// Activities Social Duration
	column trueai_act_type_social_dur
		dataType: double
		lineageTag: 1957ea43-4d9b-4029-b171-1542dd3d214f
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Social Engaged Count
	column trueai_act_type_social_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 90e3b2fe-504c-438c-ae72-f325f5287093
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_eng_count

		annotation SummarizationSetBy = Automatic

	/// Activities Adj Duration
	column trueai_act_adj_dur
		dataType: double
		lineageTag: 62f8f7cc-4073-443b-8ed9-1392a213a397
		summarizeBy: sum
		sourceColumn: trueai_act_adj_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Adj Engaged Duration
	column trueai_act_adj_eng_dur
		dataType: double
		lineageTag: b966ae9b-84a6-4a7a-b3ba-5d8dad58e75f
		summarizeBy: sum
		sourceColumn: trueai_act_adj_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Activities Adj Duration Rule
	column trueai_act_adj_dur_rule
		dataType: int64
		formatString: 0
		lineageTag: 35e72331-7a15-4838-b34f-8ff501c53094
		summarizeBy: sum
		sourceColumn: trueai_act_adj_dur_rule

		annotation SummarizationSetBy = Automatic

	/// Column trueai_last_eng_act =.
	column trueai_last_eng_act =
			
			var _id = [crm_opp_id]
			var res  = CALCULATE(
			    MAX(ssr_history[stkhlds_all_last_eng]),
			    ssr_history[entity_opp_id]=_id
			)
			
			RETURN
			res
		formatString: Short Date
		lineageTag: ec9e5e54-a2ee-4917-aaab-505ce2223b3b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage ID in the CRM
	column crm_stage_id
		dataType: string
		lineageTag: 794cd384-506b-463d-a43d-b6b242e374f5
		summarizeBy: none
		sourceColumn: crm_stage_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage ID
	column trueai_stage_id
		dataType: string
		lineageTag: a22456f8-dc7e-448e-ac75-166c5ceddac5
		summarizeBy: none
		sourceColumn: trueai_stage_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage name
	column trueai_stage_name
		dataType: string
		lineageTag: 1819dcf2-878d-4ecf-ad48-516fc28898e0
		summarizeBy: none
		sourceColumn: trueai_stage_name

		annotation SummarizationSetBy = Automatic

	/// Pipeline name of the opportunity
	column trueai_pipeline_name
		dataType: string
		lineageTag: ebdbabfd-ae67-4d27-ac0e-324d87542d91
		summarizeBy: none
		sourceColumn: trueai_pipeline_name

		annotation SummarizationSetBy = Automatic

	/// Sortable ID
	column trueai_sort_id
		dataType: string
		lineageTag: b5868077-1537-4949-8e9b-08f991c61b96
		summarizeBy: none
		sourceColumn: trueai_sort_id

		annotation SummarizationSetBy = Automatic

	/// Success Probability of Opp
	column trueai_success_prob
		dataType: double
		lineageTag: 44d41e39-4a3a-4227-acb5-4ba13109fe17
		summarizeBy: sum
		sourceColumn: trueai_success_prob

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Owner ID of Opp
	column trueai_owner_id
		dataType: string
		lineageTag: 38926ce8-7bd7-42a4-847b-cadfa7f02a6f
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	/// Days In Stage
	column trueai_days_in_stage
		dataType: int64
		formatString: 0
		lineageTag: 8bc470f9-c3d4-490a-bb62-2f0291f12485
		summarizeBy: sum
		sourceColumn: trueai_days_in_stage

		annotation SummarizationSetBy = Automatic

	/// Days Since Opportunity Open
	column trueai_days_in_opp
		dataType: int64
		formatString: 0
		lineageTag: 69aba56d-0596-4208-9332-017c0b5661b8
		summarizeBy: sum
		sourceColumn: trueai_days_in_opp

		annotation SummarizationSetBy = Automatic

	/// Days In Stage
	column trueai_pace_score_days_in_stage
		dataType: double
		lineageTag: 7329a950-5c17-4ea0-9167-e971631c43d8
		summarizeBy: sum
		sourceColumn: trueai_pace_score_days_in_stage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Pace Score Days Since Opportunity Open
	column trueai_pace_score_days_in_opp
		dataType: double
		lineageTag: b252ccb5-627f-4ff6-a989-dcdcb2da6d09
		summarizeBy: sum
		sourceColumn: trueai_pace_score_days_in_opp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Pace Score
	column trueai_pace_score
		dataType: double
		lineageTag: 52f2efd6-71a0-4d3b-bf9e-78a00b8fb46c
		summarizeBy: sum
		sourceColumn: trueai_pace_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Pace Tier 0-5
	column trueai_pace_tier
		dataType: int64
		formatString: 0
		lineageTag: 10f9fe0e-a498-4239-bafd-d5c0c464a947
		summarizeBy: sum
		sourceColumn: trueai_pace_tier

		annotation SummarizationSetBy = Automatic

	/// Activities Last Engaged
	column trueai_act_last_eng
		dataType: dateTime
		formatString: General Date
		lineageTag: 811e5918-000e-4bb6-8441-f90c896d9696
		summarizeBy: none
		sourceColumn: trueai_act_last_eng

		annotation SummarizationSetBy = Automatic

	/// Initial Close Date of Opp
	column trueai_init_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: cadd40c0-a914-40c0-ba2e-8962ac22da6c
		summarizeBy: none
		sourceColumn: trueai_init_close_date

		annotation SummarizationSetBy = Automatic

	/// Average Step Sequence Number Across All Opportunities
	column trueai_avg_step_sequence
		dataType: double
		lineageTag: 3337e4f5-5b5f-46f0-8e61-431dd3cb9932
		summarizeBy: sum
		sourceColumn: trueai_avg_step_sequence

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Predicted Booking Amount
	column trueai_pred_booking_amt
		dataType: double
		lineageTag: 90f0aa66-a06f-4b9f-be32-3214df6c30ca
		summarizeBy: sum
		sourceColumn: trueai_pred_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Predicted Close Date
	column trueai_pred_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1ab1f353-fe6a-4171-b1e9-0b4eefa801fe
		summarizeBy: none
		sourceColumn: trueai_pred_close_date

		annotation SummarizationSetBy = Automatic

	/// Calibrated Success Probability
	column trueai_attention_value_success_prob
		dataType: double
		lineageTag: 535d8d6c-b8ba-459f-8f5d-38ccc6546908
		summarizeBy: sum
		sourceColumn: trueai_attention_value_success_prob

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Expected Success Probability
	column trueai_attention_value_expected_success_prob
		dataType: double
		lineageTag: ce98edad-d7c6-419c-9a3f-b6cef978691c
		summarizeBy: sum
		sourceColumn: trueai_attention_value_expected_success_prob

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Attention Value Score
	column trueai_attention_value_score
		dataType: double
		lineageTag: 043b4fb9-fc99-4d9c-8b4e-cdce1c5ed155
		summarizeBy: sum
		sourceColumn: trueai_attention_value_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Attention Value Text
	column trueai_attention_value_text
		dataType: string
		lineageTag: ec0e3163-e5bd-4104-94f6-1f513d6485f7
		summarizeBy: none
		sourceColumn: trueai_attention_value_text

		annotation SummarizationSetBy = Automatic

	/// Difference In Days Between The Opportunity Expected Close Date and The Actual Close Date
	column trueai_days_pushed_pulled
		dataType: int64
		formatString: 0
		lineageTag: 3a282143-9d18-4108-9e30-5af76f854596
		summarizeBy: sum
		sourceColumn: trueai_days_pushed_pulled

		annotation SummarizationSetBy = Automatic

	/// Column opp_is_won = RELATED(opps[trueai_is_won]).
	column opp_is_won = RELATED(opps[trueai_is_won])
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 47a775ab-0ea4-4d6e-b391-eb712fdbe590
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column trueai_pred_close_date_if_won
		dataType: string
		lineageTag: 37ee1e38-260b-4665-bc49-e33a5cf12051
		summarizeBy: none
		sourceColumn: trueai_pred_close_date_if_won

		annotation SummarizationSetBy = Automatic

	column trueai_pred_close_date_if_lost
		dataType: string
		lineageTag: b54d679a-8a12-43eb-b005-4a624ac20b50
		summarizeBy: none
		sourceColumn: trueai_pred_close_date_if_lost

		annotation SummarizationSetBy = Automatic

	column cust_date1
		dataType: string
		lineageTag: c59813c9-fe01-42fd-bf03-c9dc3211f49a
		summarizeBy: none
		sourceColumn: cust_date1

		annotation SummarizationSetBy = Automatic

	column cust_date2
		dataType: string
		lineageTag: afbdbc7f-f53a-47e0-bc3c-b944c7fed96f
		summarizeBy: none
		sourceColumn: cust_date2

		annotation SummarizationSetBy = Automatic

	column cust_date3
		dataType: string
		lineageTag: 2c593a8d-d985-4223-9c72-50778f1e4c67
		summarizeBy: none
		sourceColumn: cust_date3

		annotation SummarizationSetBy = Automatic

	column _sys_sync_id
		dataType: string
		lineageTag: 81211916-cb1f-40b5-a306-89c5bb2eaecb
		summarizeBy: none
		sourceColumn: _sys_sync_id

		annotation SummarizationSetBy = Automatic

	partition open_pipeline = m
		mode: import
		source =
				let
				
				
				    dbTable = getDBTable("open_pipeline"), // get the right table
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"_sys_as_of", type datetime},
				        {"_sys_doc_id", type text},
				        {"_sys_filt_end_date", type date},
				        {"_sys_filt_start_date", type date},
				        {"crm_booking_amt", type number},
				        {"crm_close_date", type datetime},
				        {"crm_created_on", type datetime},
				        {"crm_creator_id", type text},
				        {"crm_opp_id", type text},
				        {"crm_stage_id", type text},
				        {"crm_stage_name", type text},
				        {"crm_stage_num", type text},
				        {"cust_bool1", type logical},
				        {"cust_bool2", type logical},
				        {"cust_num1", type number},
				        {"cust_num2", type number},
				        {"cust_num3", type number},
				        {"cust_num4", type number},
				        {"cust_num5", type number},
				        {"cust_num6", type number},
				        {"cust_num7", type number},
				        {"cust_text1", type text},
				        {"cust_text2", type text},
				        {"cust_text3", type text},
				        {"cust_text4", type text},
				        {"cust_text5", type text},
				        {"trueai_act_adj_dur", type number},
				        {"trueai_act_adj_dur_rule", Int64.Type},
				        {"trueai_act_adj_eng_dur", type number},
				        {"trueai_act_count", Int64.Type},
				        {"trueai_act_dur", type number},
				        {"trueai_act_eng_count", Int64.Type},
				        {"trueai_act_eng_dur", type number},
				        {"trueai_act_last_eng", type datetime},
				        {"trueai_act_type_auto_email_count", Int64.Type},
				        {"trueai_act_type_auto_email_dur", type number},
				        {"trueai_act_type_auto_email_eng_count", Int64.Type},
				        {"trueai_act_type_call_count", Int64.Type},
				        {"trueai_act_type_call_dur", type number},
				        {"trueai_act_type_call_eng_count", Int64.Type},
				        {"trueai_act_type_email_count", Int64.Type},
				        {"trueai_act_type_email_dur", type number},
				        {"trueai_act_type_email_eng_count", Int64.Type},
				        {"trueai_act_type_meeting_count", Int64.Type},
				        {"trueai_act_type_meeting_dur", type number},
				        {"trueai_act_type_meeting_eng_count", Int64.Type},
				        {"trueai_act_type_nd_count", Int64.Type},
				        {"trueai_act_type_nd_dur", type number},
				        {"trueai_act_type_nd_eng_count", Int64.Type},
				        {"trueai_act_type_no_interaction_count", Int64.Type},
				        {"trueai_act_type_no_interaction_dur", type number},
				        {"trueai_act_type_no_interaction_eng_count", Int64.Type},
				        {"trueai_act_type_social_count", Int64.Type},
				        {"trueai_act_type_social_dur", type number},
				        {"trueai_act_type_social_eng_count", Int64.Type},
				        {"trueai_attention_value_expected_success_prob", type number},
				        {"trueai_attention_value_score", type number},
				        {"trueai_attention_value_success_prob", type number},
				        {"trueai_attention_value_text", type text},
				        {"trueai_avg_step_sequence", type number},
				        {"trueai_booking_amt", type number},
				        {"trueai_can_be_excluded", type logical},
				        {"trueai_current_prob_of_win", type number},
				        {"trueai_days_in_opp", Int64.Type},
				        {"trueai_days_in_stage", Int64.Type},
				        {"trueai_days_pushed_pulled", Int64.Type},
				        {"trueai_init_close_date", type datetime},
				        {"trueai_is_closed", type logical},
				        {"trueai_is_won", type logical},
				        {"trueai_owner_act_capt_lvl", type number},
				        {"trueai_owner_act_capt_lvl_conf", type number},
				        {"trueai_owner_id", type text},
				        {"trueai_owner_prep_factor", type number},
				        {"trueai_pace_score", type number},
				        {"trueai_pace_score_days_in_opp", type number},
				        {"trueai_pace_score_days_in_stage", type number},
				        {"trueai_pace_tier", Int64.Type},
				        {"trueai_pipeline_name", type text},
				        {"trueai_pred_booking_amt", type number},
				        {"trueai_pred_close_date", type datetime},
				        {"trueai_sort_id", type text},
				        {"trueai_stage", type text},
				        {"trueai_stage_id", type text},
				        {"trueai_stage_name", type text},
				        {"trueai_step_sequence", Int64.Type},
				        {"trueai_success_prob", type number}
				    }),
				     addedStageNum = Table.AddColumn(dbTableTyped, "trueai_stage_num", each if [trueai_stage] = "Early" then 1 else if [trueai_stage] = "Mid" then 2 else if [trueai_stage] = "Late" then 3 else if [trueai_stage] = "Closed Won" then 4 else if [trueai_stage] = "Closed Lost" then 5 else 7),
				    ChangedType = Table.TransformColumnTypes(addedStageNum,{{"trueai_stage_num", Int64.Type}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(ChangedType,{{"_sys_doc_id", "_sys_doc_id"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

