/// CRM entity for individual product or service entries linked to an Opportunity enriched with TrueAI predictive insights.
table opp_line_items
	lineageTag: edae7c88-f01d-4324-822e-0bbf7f5f5b44

	/// The date of the last data request from the platform
	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: ccf5ba30-e90d-4b8b-b586-ca35d8562821
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 08a38501-8392-4a44-af22-fffa39811cd2
			defaultHierarchy: LocalDateTable_f7d74739-47d0-4a14-a0a4-dd2038a699f2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Unique record identifier, based on the ID of the document in the remote system (such as Salesforce ID)
	column _sys_doc_id
		dataType: string
		lineageTag: aac4b0e9-c772-41a8-b2eb-4df9ba8d99fe
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the stage was set to deleted in the remote system
	column _sys_is_deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: eba745b4-6c4d-4172-a44d-5ba368421f73
		summarizeBy: none
		sourceColumn: _sys_is_deleted

		annotation SummarizationSetBy = Automatic

	/// The date of the last data modification in the platform
	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: fc7a742b-0bff-46b1-b26b-417d1377908e
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: d9b8dda1-0787-4bee-872f-22d1e2d7d1fb
			defaultHierarchy: LocalDateTable_55c45097-6e73-44e2-80fd-ee033e380a52.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Id of the SSR document the record belongs to
	column _sys_ssr_id
		dataType: string
		lineageTag: 297f8e97-d15c-4dbf-b7f1-302caa8cb8cc
		summarizeBy: none
		sourceColumn: _sys_ssr_id

		annotation SummarizationSetBy = Automatic

	/// Product's creation date in the CRM
	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 5f54cc75-dd33-45f7-ad0e-5b4462a58f5d
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: ca75a053-deec-4f50-b6db-bb225da1ff60
			defaultHierarchy: LocalDateTable_a227b0fe-f5fa-4728-87f1-db56fbfa585a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Product's currency in the CRM
	column crm_currency
		dataType: string
		lineageTag: 7d54979a-ad50-4bed-b385-3f6eec44b72e
		summarizeBy: none
		sourceColumn: crm_currency

		annotation SummarizationSetBy = Automatic

	/// Product's description in the CRM
	column crm_description
		dataType: string
		lineageTag: 78faa6eb-a603-4fb7-a624-c3516fb3b74c
		summarizeBy: none
		sourceColumn: crm_description

		annotation SummarizationSetBy = Automatic

	/// Product's list_price in the CRM
	column crm_list_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b580bdd1-32d0-4dbf-853a-d61c049c9230
		summarizeBy: sum
		sourceColumn: crm_list_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Product's modified on date in the CRM
	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: a1e718b8-27ac-4891-a08a-21a9f0699651
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: b612ecd9-875c-4225-b63e-47b253d3c519
			defaultHierarchy: LocalDateTable_60e8fbc2-ffbd-470a-a383-1a9e5abce9f3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Product name in the CRM
	column crm_name
		dataType: string
		lineageTag: a9cbdf95-35ff-4990-9323-c419983d6c7d
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	/// Product oppid in the CRM
	column crm_opp_id
		dataType: string
		lineageTag: 1b9af2a5-c81a-440f-95d4-0bf60f9fdc20
		summarizeBy: none
		sourceColumn: crm_opp_id

		annotation SummarizationSetBy = Automatic

	/// Product code in the CRM
	column crm_product_code
		dataType: string
		lineageTag: a97d0e9b-17af-403d-884a-c22d5192ddca
		summarizeBy: none
		sourceColumn: crm_product_code

		annotation SummarizationSetBy = Automatic

	/// Product product_id in the CRM
	column crm_product_id
		dataType: string
		lineageTag: ef195be1-c40e-4118-b89a-abf81f8e7633
		summarizeBy: none
		sourceColumn: crm_product_id

		annotation SummarizationSetBy = Automatic

	/// Product's qty in the CRM
	column crm_qty
		dataType: int64
		formatString: 0
		lineageTag: 32dc54ea-4c4d-4ffd-ab43-653c5e978117
		summarizeBy: sum
		sourceColumn: crm_qty

		annotation SummarizationSetBy = Automatic

	/// Product's total_price in the CRM
	column crm_total_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9355db5f-776e-453d-a931-b0bba0d70f3b
		summarizeBy: sum
		sourceColumn: crm_total_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Product's unit_price in the CRM
	column crm_unit_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2d5b9423-9fba-40be-8f68-0d0e6350a324
		summarizeBy: sum
		sourceColumn: crm_unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Product's total price
	column trueai_total_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0c3d576d-250d-4123-8dcb-567ef5aaaf02
		summarizeBy: sum
		sourceColumn: trueai_total_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Product's total price rule
	column trueai_total_price_rule
		dataType: int64
		formatString: 0
		lineageTag: 4ea514d4-2425-4fdc-8d6a-35411cf75619
		summarizeBy: sum
		sourceColumn: trueai_total_price_rule

		annotation SummarizationSetBy = Automatic

	/// Product's unit price
	column trueai_unit_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8d780822-d955-48ac-b3ae-645e40ea1378
		summarizeBy: sum
		sourceColumn: trueai_unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Product's unit price rule
	column trueai_unit_price_rule
		dataType: int64
		formatString: 0
		lineageTag: f7abe586-f21d-454a-81c9-66d49af7f96b
		summarizeBy: sum
		sourceColumn: trueai_unit_price_rule

		annotation SummarizationSetBy = Automatic

	/// Product's list price
	column trueai_list_price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0f97ca53-d3c4-47e6-9975-9a44999ee062
		summarizeBy: sum
		sourceColumn: trueai_list_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Product's list price rule
	column trueai_list_price_rule
		dataType: int64
		formatString: 0
		lineageTag: 5acd9ce0-3ce9-4400-98cf-a69956d999ab
		summarizeBy: sum
		sourceColumn: trueai_list_price_rule

		annotation SummarizationSetBy = Automatic

	/// Products quantity
	column trueai_qty
		dataType: double
		lineageTag: 1f577286-5272-4ddc-9066-3b9d9cc5e7cb
		summarizeBy: sum
		sourceColumn: trueai_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Product's discount amount
	column trueai_discount_amt
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 153178e7-aab4-4b7e-b9ef-0cc44e5ac731
		summarizeBy: sum
		sourceColumn: trueai_discount_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Product's discount percentage
	column trueai_discount_pct
		dataType: double
		lineageTag: 6205bc51-a321-4407-a619-d60cc68cf6de
		summarizeBy: sum
		sourceColumn: trueai_discount_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_text1
	column cust_text1
		dataType: string
		lineageTag: 7ad374b3-2c40-481b-805d-b7a48832c55b
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	/// cust_text2
	column cust_text2
		dataType: string
		lineageTag: a45ec35a-785c-4c58-9701-3141ac83a84c
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	/// cust_text3
	column cust_text3
		dataType: string
		lineageTag: ec671f23-f817-4c21-9200-3acd7794744e
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	/// cust_text4
	column cust_text4
		dataType: string
		lineageTag: 7f49269a-3c9f-4ea0-aa41-e8e7df0aa05a
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	/// cust_text5
	column cust_text5
		dataType: string
		lineageTag: eeb8651f-7cbc-4420-8dfd-e5656faaa38b
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	/// cust_num1
	column cust_num1
		dataType: double
		lineageTag: 49223c2f-e664-42c3-9af0-c1c211e0afbd
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num2
	column cust_num2
		dataType: double
		lineageTag: 867af920-4a62-4cc4-a25d-d132666beb84
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num3
	column cust_num3
		dataType: double
		lineageTag: 024818e1-980c-4103-9c3e-d90ae22bee40
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num4
	column cust_num4
		dataType: double
		lineageTag: 3eed6cc7-1ccb-4b73-891c-9342e0300365
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num5
	column cust_num5
		dataType: double
		lineageTag: a2252938-5032-4fe0-96ad-5dec91f37708
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num6
	column cust_num6
		dataType: double
		lineageTag: a9ae4deb-dfeb-4b3d-a8ce-595a331294de
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num7
	column cust_num7
		dataType: double
		lineageTag: 6d7f9ec4-2ba7-43fc-a5ff-5062f4eccfc1
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_bool1
	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 17c56d42-1fce-487e-b8a8-b51bdf513733
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	/// cust_bool2
	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e6d21a9d-1c64-4942-9899-d54ca5ea885f
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	/// Prompt Used To Classify Product Type
	column trueai_revenue_type_context
		dataType: string
		lineageTag: 2c0e22f6-4e91-4440-9c07-9ecaf30620f3
		summarizeBy: none
		sourceColumn: trueai_revenue_type_context

		annotation SummarizationSetBy = Automatic

	/// Revenue Type
	column trueai_revenue_type
		dataType: string
		lineageTag: bef02a48-7d17-4583-a28a-8d4ebfadf762
		summarizeBy: none
		sourceColumn: trueai_revenue_type

		annotation SummarizationSetBy = Automatic

	/// Revenue Type Rule
	column trueai_revenue_type_rule
		dataType: int64
		formatString: 0
		lineageTag: 0c7f1e9e-45c6-4c23-84b7-513cc23d63a9
		summarizeBy: sum
		sourceColumn: trueai_revenue_type_rule

		annotation SummarizationSetBy = Automatic

	/// Product Type
	column trueai_product_type
		dataType: string
		lineageTag: debf4e53-d719-4cfe-bff2-cf1acf296180
		summarizeBy: none
		sourceColumn: trueai_product_type

		annotation SummarizationSetBy = Automatic

	partition opp_line_items = m
		mode: import
		source =
				let
				
				
				
				    dbTable = getDBTable("opp_line_items"), // get the right table
				
				
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"_sys_as_of", type datetime},
				{"_sys_doc_id", type text},
				{"_sys_is_deleted", type logical},
				{"_sys_last_modified_on", type datetime},
				{"_sys_ssr_id", type text},
				{"crm_created_on", type datetime},
				{"crm_currency", type text},
				{"crm_description", type text},
				{"crm_list_price", type number},
				{"crm_modified_on", type datetime},
				{"crm_name", type text},
				{"crm_opp_id", type text},
				{"crm_product_code", type text},
				{"crm_product_id", type text},
				{"crm_qty", Int64.Type},
				{"crm_total_price", type number},
				{"crm_unit_price", type number},
				{"cust_bool1", type logical},
				{"cust_bool2", type logical},
				{"cust_num1", type number},
				{"cust_num2", type number},
				{"cust_num3", type number},
				{"cust_num4", type number},
				{"cust_num5", type number},
				{"cust_num6", type number},
				{"cust_num7", type number},
				{"cust_text1", type text},
				{"cust_text2", type text},
				{"cust_text3", type text},
				{"cust_text4", type text},
				{"cust_text5", type text},
				{"trueai_discount_amt", type number},
				{"trueai_discount_pct", type number},
				{"trueai_list_price", type number},
				{"trueai_list_price_rule", Int64.Type},
				{"trueai_product_type", type text},
				{"trueai_qty", type number},
				{"trueai_revenue_type", type text},
				{"trueai_revenue_type_context", type text},
				{"trueai_revenue_type_rule", Int64.Type},
				{"trueai_total_price", type number},
				{"trueai_total_price_rule", Int64.Type},
				{"trueai_unit_price", type number},
				{"trueai_unit_price_rule", Int64.Type}
				    })
				in
				    dbTableTyped

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

