/// CRM entity for opportunity records enriched with TrueAI predictive insights.
table opps
	description: "One row per opp record. Source fields include CRM, System, TrueAI prefixes. Related to LocalDateTable_29eafee9-9420-4f61-839f-959fae174886 (crm_close_date -> Date), LocalDateTable_b47d6e1a-e681-4cdc-968a-8ae0f1d92e8a (_sys_filt_end_date -> Date), LocalDateTable_28e862d0-6e5a-47c3-ae31-d7ff8503cf73 (crm_last_act_time -> Date). Supports measures such as meas.opp_trueai_completeness_improvement."
	lineageTag: 4277295b-2fd7-47a1-b82b-5de4b447fb12

	/// Measure meas.opp_trueai_completeness_improvement.
	measure 'meas.opp_trueai_completeness_improvement' = ```
			
			var crmval = CALCULATE(AVERAGE([crm_complt]))
			var aival = CALCULATE(AVERAGE([trueai_complt]))
			var impro = Divide(aival - crmval, crmval) 
			var res = If(impro > 0, "+" & FORMAT( impro, "###%"),  "No change")
			return res 
			
			```
			description: "Ratio measure. Respects the current filter context."
		formatString: 0 %
		lineageTag: 7282e887-bcaf-41aa-b41c-9e863ab86f59

	/// Id of the SSR document the record belongs to
	column _sys_ssr_id
		description: "System: Identifier for ssr."
		dataType: string
		lineageTag: 068c6a2d-be04-474a-a201-5f2bba17dbb3
		summarizeBy: none
		sourceColumn: _sys_ssr_id

		annotation SummarizationSetBy = Automatic

	/// Name of the opportunity
	column crm_name
		description: "CRM: Text label for name."
		dataType: string
		lineageTag: c2656224-81d4-4a43-8fa3-102dd26f2af1
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	/// Link to the opportunity in the remote system (such as Salesforce)
	column crm_deep_link
		description: "CRM: Text label for deep link."
		dataType: string
		lineageTag: 278fbcf3-b41a-44b4-b4b6-bf2c71b75301
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	/// Opportunity's booking amount in the CRM
	column crm_booking_amt
		description: "CRM: Amount for booking amt."
		dataType: double
		lineageTag: a1803061-2073-4961-b70a-eaf839c0b5b8
		summarizeBy: sum
		sourceColumn: crm_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's close date in the CRM
	column crm_close_date
		description: "CRM: Date/time when close date."
		dataType: dateTime
		formatString: General Date
		lineageTag: 48586531-6700-4b08-8a57-8f1269810656
		summarizeBy: none
		sourceColumn: crm_close_date

		variation Variation
			isDefault
			relationship: 58d304b7-072a-4034-b204-78d2e8d6fd75
			defaultHierarchy: LocalDateTable_29eafee9-9420-4f61-839f-959fae174886.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity's currency in the CRM
	column crm_currency
		description: "CRM: Text label for currency."
		dataType: string
		lineageTag: 1f4f6bac-98e9-4d9a-97b4-f6bfa484ac44
		summarizeBy: none
		sourceColumn: crm_currency

		annotation SummarizationSetBy = Automatic

	/// Opportunity's lead source in the CRM
	column crm_leadsource
		description: "CRM: Text label for leadsource."
		dataType: string
		lineageTag: 4f726618-6bc3-429c-9c16-a793fcf15ff5
		summarizeBy: none
		sourceColumn: crm_leadsource

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage name in the CRM
	column crm_stage_name
		description: "CRM: Text label for stage name."
		dataType: string
		lineageTag: 9513b2ce-c3bf-460b-ba1c-4266fd204493
		summarizeBy: none
		sourceColumn: crm_stage_name

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage number in the CRM
	column crm_stage_num
		description: "CRM: Count of stage num."
		dataType: int64
		formatString: 0
		lineageTag: f17033ff-a5c1-4337-9859-b134ebe61f28
		summarizeBy: sum
		sourceColumn: crm_stage_num

		annotation SummarizationSetBy = Automatic

	/// Opportunity's type in the CRM
	column crm_type
		description: "CRM: Text label for type."
		dataType: string
		lineageTag: a0467423-b728-42d4-a0fc-4483577a7442
		summarizeBy: none
		sourceColumn: crm_type

		annotation SummarizationSetBy = Automatic

	/// Opportunity's booking amount
	column trueai_booking_amt
		description: "TrueAI: Amount for booking amt."
		dataType: double
		lineageTag: 93945286-f8de-4b88-82cb-620bb5a23717
		summarizeBy: sum
		sourceColumn: trueai_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's close date
	column trueai_close_date
		description: "TrueAI: Date/time when close date."
		dataType: dateTime
		formatString: General Date
		lineageTag: 2e5c1281-317c-42fb-a734-123ba8852877
		summarizeBy: none
		sourceColumn: trueai_close_date

		variation Variation
			isDefault
			relationship: d8fe22e8-5b68-47f9-b823-cfb78e8f57cc
			defaultHierarchy: LocalDateTable_3e9628b4-fa22-4c3c-b272-3a06a0a0081b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized lead source
	column trueai_leadsource
		description: "TrueAI: Text label for leadsource."
		dataType: string
		lineageTag: 842625c6-762b-4147-85b3-b0c9c99e47db
		summarizeBy: none
		sourceColumn: trueai_leadsource

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized industry
	column trueai_industry
		description: "TrueAI: Text label for industry."
		dataType: string
		lineageTag: 696bf1ab-e6ed-4e10-8d8d-272e3ce0f730
		summarizeBy: none
		sourceColumn: trueai_industry

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized company size
	column trueai_company_size
		description: "TrueAI: Text label for company size."
		dataType: string
		lineageTag: c2557585-eaa5-406b-bc54-ec9d57b9900a
		summarizeBy: none
		sourceColumn: trueai_company_size

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is a new logo
	column trueai_is_new_logo
		description: "TrueAI: Indicates whether is new logo."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 989bf5b9-da0d-4ee6-bd02-2fe6b3c211f9
		summarizeBy: none
		sourceColumn: trueai_is_new_logo

		annotation SummarizationSetBy = Automatic

	/// Opportunity's sale type
	column trueai_sale_type
		description: "TrueAI: Text label for sale type."
		dataType: string
		lineageTag: 9b7d2e0e-4419-4aa0-9856-10dec214d42b
		summarizeBy: none
		sourceColumn: trueai_sale_type

		annotation SummarizationSetBy = Automatic

	/// Date when the opportunity entered the middle stage
	column trueai_opp_stage_mid_date
		description: "TrueAI: Date/time when opp stage mid date."
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d9a2a43-6a90-4d6f-8f50-edbd5eca1065
		summarizeBy: none
		sourceColumn: trueai_opp_stage_mid_date

		variation Variation
			isDefault
			relationship: fe1a26b3-49e7-4f88-8efb-e929f5358543
			defaultHierarchy: LocalDateTable_3cf76079-fb90-447d-bedf-f1e0abb80cc4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Date when the opportunity entered the late stage
	column trueai_opp_stage_late_date
		description: "TrueAI: Date/time when opp stage late date."
		dataType: dateTime
		formatString: General Date
		lineageTag: 9771a63b-f3ba-497c-87f3-72db5e810c54
		summarizeBy: none
		sourceColumn: trueai_opp_stage_late_date

		variation Variation
			isDefault
			relationship: b38b9523-7969-44ed-afc0-f99da6e567f4
			defaultHierarchy: LocalDateTable_76391fd4-8e95-484d-920c-152d60748974.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Quality bucket based on the probability of win
	column trueai_qual_bucket
		description: "TrueAI: Text label for qual bucket."
		dataType: string
		lineageTag: 33dacbdb-aa27-4569-842d-a68d5df4b162
		summarizeBy: none
		sourceColumn: trueai_qual_bucket

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized company size prediction rule
	column trueai_company_size_rule
		description: "TrueAI: Numeric value for company size rule."
		dataType: int64
		formatString: 0
		lineageTag: 70da4074-615d-4944-9b41-3ad644716b88
		summarizeBy: sum
		sourceColumn: trueai_company_size_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized industry prediction rule
	column trueai_industry_rule
		description: "TrueAI: Numeric value for industry rule."
		dataType: int64
		formatString: 0
		lineageTag: 405799e1-9e8f-4bd7-bb33-17e262116231
		summarizeBy: sum
		sourceColumn: trueai_industry_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized lead source prediction rule
	column trueai_leadsource_rule
		description: "TrueAI: Numeric value for leadsource rule."
		dataType: int64
		formatString: 0
		lineageTag: 5cf07be5-ea59-41d8-8ad1-149989c6d750
		summarizeBy: sum
		sourceColumn: trueai_leadsource_rule

		annotation SummarizationSetBy = Automatic

	/// Column _sys_docid.
	column _sys_docid
		description: "System: Text label for docid."
		dataType: string
		lineageTag: 4c4c765b-b094-4e78-9d2c-98e352479ee8
		summarizeBy: none
		sourceColumn: _sys_docid

		annotation SummarizationSetBy = Automatic

	/// The end date of the record, stripped of time
	column _sys_filt_end_date
		description: "System: Date/time when filt end date."
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5a5ab94b-7f4e-45a3-81d8-64ffdf11afac
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: af488047-3ecc-45b6-a976-68a40a0171c8
			defaultHierarchy: LocalDateTable_b47d6e1a-e681-4cdc-968a-8ae0f1d92e8a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The start date of the record, stripped of time
	column _sys_filt_start_date
		description: "System: Date/time when filt start date."
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb9b8be5-0fa7-44fc-8a1c-027d5b4a290e
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// CRM account id of the opportunity
	column crm_account_id
		description: "CRM: Identifier for account."
		dataType: string
		lineageTag: 8bfebe69-9b96-48b8-9b35-5c835a6fd81a
		summarizeBy: none
		sourceColumn: crm_account_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's completeness score based on the CRM data
	column crm_complt
		description: "CRM: Numeric value for complt."
		dataType: double
		lineageTag: 27d9c40c-eb3d-42bd-8255-2f953d6fdda7
		summarizeBy: sum
		sourceColumn: crm_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's contact information completeness score based on the CRM data
	column crm_complt_contact
		description: "CRM: Numeric value for complt contact."
		dataType: double
		lineageTag: 6182e8bb-f0e3-42e0-adc4-22ac2a3db69e
		summarizeBy: sum
		sourceColumn: crm_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's marketing completeness score based on the CRM data
	column crm_complt_marketing
		description: "CRM: Numeric value for complt marketing."
		dataType: double
		lineageTag: 1f82c4a7-7ee5-472e-b608-eda124921bdd
		summarizeBy: sum
		sourceColumn: crm_complt_marketing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity creator's id in the CRM
	column crm_creator_id
		description: "CRM: Identifier for creator."
		dataType: string
		lineageTag: 1a496b42-c56d-4d92-a34a-5b05eb365f85
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's last activity time in the CRM
	column crm_last_act_time
		description: "CRM: Date/time when last act time."
		dataType: dateTime
		formatString: General Date
		lineageTag: bc2ece06-5ac4-48ea-b430-43b83dff945c
		summarizeBy: none
		sourceColumn: crm_last_act_time

		variation Variation
			isDefault
			relationship: e347e02a-f7b9-41fe-9957-f6dc238dd14e
			defaultHierarchy: LocalDateTable_28e862d0-6e5a-47c3-ae31-d7ff8503cf73.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity owner's id in the CRM
	column crm_owner_id
		description: "CRM: Identifier for owner."
		dataType: string
		lineageTag: e79a1f42-a883-449c-921d-875121187958
		summarizeBy: none
		sourceColumn: crm_owner_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's city
	column trueai_addr_city
		description: "TrueAI: Text label for addr city."
		dataType: string
		lineageTag: acef1ff0-68ed-4269-bef1-6dd78cc44e6c
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	/// Opportunity's country
	column trueai_addr_country
		description: "TrueAI: Count of addr country."
		dataType: string
		lineageTag: 33e4cb1d-8d14-4178-b2d9-be3a5c89dfdc
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	/// Opportunity's postal code
	column trueai_addr_postal_code
		description: "TrueAI: Text label for addr postal code."
		dataType: string
		lineageTag: fb94a4e9-78e3-4849-93a6-0efc6bfa537f
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	/// Opportunity's address prediction rule
	column trueai_addr_rule
		description: "TrueAI: Numeric value for addr rule."
		dataType: int64
		formatString: 0
		lineageTag: 7178fae6-aa69-4f77-89e6-45524b20fb4b
		summarizeBy: sum
		sourceColumn: trueai_addr_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's state
	column trueai_addr_state
		description: "TrueAI: Text label for addr state."
		dataType: string
		lineageTag: c9a15770-da6c-4994-af38-906b6300864a
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	/// Opportunity's street
	column trueai_addr_street
		description: "TrueAI: Text label for addr street."
		dataType: string
		lineageTag: 8646f0d2-03e8-4294-a19d-7c283f323a6f
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	/// Completeness score of the opportunity based on the standardized data
	column trueai_complt
		description: "TrueAI: Numeric value for complt."
		dataType: double
		lineageTag: 86ab3cd5-4fe4-4f00-95c1-0767e56552c0
		summarizeBy: sum
		sourceColumn: trueai_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Contact information completeness score of the opportunity based on the standardized data
	column trueai_complt_contact
		description: "TrueAI: Numeric value for complt contact."
		dataType: double
		lineageTag: ef08d4c3-eb87-4137-8b93-782a2b6d0eda
		summarizeBy: sum
		sourceColumn: trueai_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Marketing completeness score of the opportunity based on the standardized data
	column trueai_complt_marketing
		description: "TrueAI: Numeric value for complt marketing."
		dataType: double
		lineageTag: 7a1114c8-a824-4fd0-8bc7-d572fbeef21d
		summarizeBy: sum
		sourceColumn: trueai_complt_marketing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity creator's id
	column trueai_creator_id
		description: "TrueAI: Identifier for creator."
		dataType: string
		lineageTag: b67881e7-dd9d-4671-9169-a5bb51140c9d
		summarizeBy: none
		sourceColumn: trueai_creator_id

		annotation SummarizationSetBy = Automatic

	/// Total duration of activities performed on the opportunity
	column trueai_dur
		description: "TrueAI: Numeric value for dur."
		dataType: int64
		formatString: 0
		lineageTag: fc30936e-9c80-418e-83bc-20dadaf45689
		summarizeBy: sum
		sourceColumn: trueai_dur

		annotation SummarizationSetBy = Automatic

	/// Opportunity's standardized industry prediction confidence
	column trueai_industry_conf
		description: "TrueAI: Numeric value for industry conf."
		dataType: double
		lineageTag: 65d477e3-23c9-4122-a7c1-5d7943da50c3
		summarizeBy: sum
		sourceColumn: trueai_industry_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's standardized lead source prediction confidence
	column trueai_leadsource_conf
		description: "TrueAI: Numeric value for leadsource conf."
		dataType: double
		lineageTag: 0cace160-468e-45dc-819b-bc4b273589f3
		summarizeBy: sum
		sourceColumn: trueai_leadsource_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity owner's id
	column trueai_owner_id
		description: "TrueAI: Identifier for owner."
		dataType: string
		lineageTag: d273f151-efd6-47b2-aabd-6bcf806b5fe2
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's sale type prediction confidence
	column trueai_sale_type_conf
		description: "TrueAI: Numeric value for sale type conf."
		dataType: double
		lineageTag: a02bebd0-7814-4f36-b65c-a18d636ea34f
		summarizeBy: sum
		sourceColumn: trueai_sale_type_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Custom categorical variable on the account
	column crm_account_custom_value_1
		description: "CRM: Count of account custom value 1."
		dataType: string
		isHidden
		lineageTag: e9d6d4d6-07ac-4b34-99b5-87d2e0176b13
		summarizeBy: none
		sourceColumn: crm_account_custom_value_1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable on the account
	column crm_account_custom_value_2
		description: "CRM: Count of account custom value 2."
		dataType: string
		lineageTag: af53eced-5aef-4585-bc13-a68a24452119
		summarizeBy: none
		sourceColumn: crm_account_custom_value_2

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable on the account
	column crm_account_custom_value_3
		description: "CRM: Count of account custom value 3."
		dataType: string
		lineageTag: c502b962-6875-442b-80d1-763563eee54a
		summarizeBy: none
		sourceColumn: crm_account_custom_value_3

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_1
		description: "CRM: Amount for custom value 1."
		dataType: string
		lineageTag: 5cc9d428-8116-4b40-8ce5-014af57251c4
		summarizeBy: none
		sourceColumn: crm_custom_value_1

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_2
		description: "CRM: Amount for custom value 2."
		dataType: string
		lineageTag: fd5e8882-a8d2-4311-af5a-c4b0cb0501f5
		summarizeBy: none
		sourceColumn: crm_custom_value_2

		annotation SummarizationSetBy = Automatic

	/// Custom categorical variable
	column crm_custom_value_3
		description: "CRM: Amount for custom value 3."
		dataType: string
		lineageTag: 1ad95fc2-dfac-47f4-a259-4d45f7c47147
		summarizeBy: none
		sourceColumn: crm_custom_value_3

		annotation SummarizationSetBy = Automatic

	/// Opportunity's latitude
	column trueai_addr_lat
		description: "TrueAI: Numeric value for addr lat."
		dataType: double
		lineageTag: 80713b91-8088-414c-b9f0-dc248e498a21
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's longitude
	column trueai_addr_long
		description: "TrueAI: Numeric value for addr long."
		dataType: double
		lineageTag: 1b6b9893-a061-40bf-95d0-12493c49fc5a
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's booking amount rule related to the presence or absence of opp line items and custom mappings
	column trueai_booking_amt_rule
		description: "TrueAI: Amount for booking amt rule."
		dataType: int64
		formatString: 0
		lineageTag: 5caf1296-2f16-4d9c-b9c3-813050765aef
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_rule

		annotation SummarizationSetBy = Automatic

	/// Quality bucket expressed as an integer from 1 to 5 based on the probability of win
	column trueai_qual_bucket_num
		description: "TrueAI: Count of qual bucket num."
		dataType: int64
		formatString: 0
		lineageTag: 0bafe83f-36cb-485e-a258-c4c53cb803a6
		summarizeBy: sum
		sourceColumn: trueai_qual_bucket_num

		annotation SummarizationSetBy = Automatic

	/// Opportunity's custom completeness score based on the CRM data
	column crm_complt_custom
		description: "CRM: Numeric value for complt custom."
		dataType: double
		lineageTag: c27d3ff1-0185-417e-ac64-792ba0006253
		summarizeBy: sum
		sourceColumn: crm_complt_custom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The date of the last data request from the platform
	column _sys_as_of
		description: "System: Date/time when as of."
		dataType: dateTime
		formatString: General Date
		lineageTag: bc7614c3-8503-49a2-8408-cc686c19960c
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: cd7469ff-1ad9-4d27-a088-f9d92df13881
			defaultHierarchy: LocalDateTable_6a25f2c9-f8db-4b53-b19f-c31b87f63ed9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is active
	column _sys_is_active
		description: "System: Indicates whether is active."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ba53617c-16b9-40c2-9537-694ffe30623d
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// The date of the last data modification in the platform
	column _sys_last_modified_on
		description: "System: Date/time when last modified on."
		dataType: dateTime
		formatString: General Date
		lineageTag: f54e24d3-aac3-49e1-8046-bf2fbcf5346a
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 7e84575d-ebfb-4b20-9577-9e73daabc4e0
			defaultHierarchy: LocalDateTable_d6c9441c-f5bf-474a-b755-76426451563e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity creation date in the CRM
	column crm_created_on
		description: "CRM: Date/time when created on."
		dataType: dateTime
		formatString: General Date
		lineageTag: 2f656dba-9955-4841-b328-16a370231d07
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 58ed177e-b8a0-4430-a353-3386331c5e25
			defaultHierarchy: LocalDateTable_b5a2c35e-e84f-42da-9db1-5ff88827db21.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is closed in the CRM
	column crm_is_closed
		description: "CRM: Indicates whether is closed."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ffb8b0ec-07a3-4582-8c13-e531cc902195
		summarizeBy: none
		sourceColumn: crm_is_closed

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is won in the CRM
	column crm_is_won
		description: "CRM: Indicates whether is won."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8526a248-f13a-4341-959a-d2a7a5d53bf8
		summarizeBy: none
		sourceColumn: crm_is_won

		annotation SummarizationSetBy = Automatic

	/// Opportunity modified on date in the CRM
	column crm_modified_on
		description: "CRM: Date/time when modified on."
		dataType: dateTime
		formatString: General Date
		lineageTag: aec9eeb8-bec8-4b92-babd-94c3c40e96da
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: 75381359-0703-40fb-9373-03d081e9e67a
			defaultHierarchy: LocalDateTable_bce856a2-bc85-4d4b-9a27-84618f90188c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Opportunity's prospecting entity
	column trueai_created_from_entity
		description: "TrueAI: Text label for created from entity."
		dataType: string
		lineageTag: af89d79f-a7bf-40cb-90f2-1ba80a19c81d
		summarizeBy: none
		sourceColumn: trueai_created_from_entity

		annotation SummarizationSetBy = Automatic

	/// Opportunity's prospecting object's id
	column trueai_created_from_id
		description: "TrueAI: Identifier for created from."
		dataType: string
		lineageTag: 89effb20-308b-4349-9417-3a0390fa5c9c
		summarizeBy: none
		sourceColumn: trueai_created_from_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity creation date
	column trueai_created_on
		description: "TrueAI: Date/time when created on."
		dataType: dateTime
		formatString: General Date
		lineageTag: 2843cefb-64b0-4e3e-a5dd-5531b0f11c3e
		summarizeBy: none
		sourceColumn: trueai_created_on

		variation Variation
			isDefault
			relationship: a172bfa4-1870-4bc8-b257-b82b92cfed41
			defaultHierarchy: LocalDateTable_dac1b4ea-2ca8-4599-bc50-bab7ddce298f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the opportunity is won
	column trueai_is_won
		description: "TrueAI: Indicates whether is won."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ab6f4266-be46-49b1-9aa5-8dfc92650ea9
		summarizeBy: none
		sourceColumn: trueai_is_won

		annotation SummarizationSetBy = Automatic

	/// Opportunity's normalized stage
	column trueai_stage
		description: "TrueAI: Text label for stage."
		dataType: string
		lineageTag: 31aeb6d1-40a2-4e47-8a25-935f89a8573e
		summarizeBy: none
		sourceColumn: trueai_stage

		annotation SummarizationSetBy = Automatic

	/// Probability of win
	column trueai_prob_of_win
		description: "TrueAI: Numeric value for prob of win."
		dataType: double
		lineageTag: a1d0c01d-8d25-4303-9f12-945e43fecd3a
		summarizeBy: sum
		sourceColumn: trueai_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity discount amount
	column trueai_discount_amt
		description: "TrueAI: Count of discount amt."
		dataType: double
		lineageTag: 4c4d1b13-ca33-47eb-8c2d-4221e15509b8
		summarizeBy: sum
		sourceColumn: trueai_discount_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity discount percentage
	column trueai_discount_pct
		description: "TrueAI: Count of discount pct."
		dataType: double
		lineageTag: 9277eec1-452b-49cc-83ca-ef7907d5829f
		summarizeBy: sum
		sourceColumn: trueai_discount_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Boolean flag indicating whether the opportunity should be treated as an order instead.
	column trueai_is_erp
		description: "TrueAI: Indicates whether is erp."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 017de80e-c49a-4333-a1f7-0f4f72d37bea
		summarizeBy: none
		sourceColumn: trueai_is_erp

		annotation SummarizationSetBy = Automatic

	/// Opportunity's booking amount currency conversion rule
	column trueai_booking_amt_currency_rule
		description: "TrueAI: Amount for booking amt currency rule."
		dataType: int64
		formatString: 0
		lineageTag: cad47743-e6a8-4028-ad99-91ea44a8111f
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_currency_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's account id
	column trueai_account_id
		description: "TrueAI: Identifier for account."
		dataType: string
		lineageTag: b361074d-2e04-434e-865b-785b04a1b5ce
		summarizeBy: none
		sourceColumn: trueai_account_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's account id rule
	column trueai_account_id_rule
		description: "TrueAI: Count of account id rule."
		dataType: int64
		formatString: 0
		lineageTag: 40cb1717-d850-47f1-a44d-6ed84ed4d0a7
		summarizeBy: sum
		sourceColumn: trueai_account_id_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's account id confidence
	column trueai_account_id_conf
		description: "TrueAI: Count of account id conf."
		dataType: double
		lineageTag: 441bc720-2a6c-416a-937f-a0364f63c616
		summarizeBy: sum
		sourceColumn: trueai_account_id_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Test model
	column trueai_test
		description: "TrueAI: Text label for test."
		dataType: string
		lineageTag: ae610465-1d85-4e27-be3e-157a0333b680
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	/// Test model confidence
	column trueai_test_conf
		description: "TrueAI: Numeric value for test conf."
		dataType: double
		lineageTag: 32c3aff2-227c-4caa-9777-92b446ce770e
		summarizeBy: sum
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Test model rule
	column trueai_test_rule
		description: "TrueAI: Text label for test rule."
		dataType: string
		lineageTag: ea3b8c35-8502-4b7b-bd57-fd215806bb87
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	/// Test model debug information
	column trueai_test_debug
		description: "TrueAI: Text label for test debug."
		dataType: string
		lineageTag: fdd82951-47f4-4190-b879-3a2a8e31224e
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	/// Opportunity's close date rule
	column trueai_close_date_rule
		description: "TrueAI: Date/time when close date rule."
		dataType: int64
		formatString: 0
		lineageTag: bb1bf736-b666-4d32-82a1-e97cb34f280a
		summarizeBy: sum
		sourceColumn: trueai_close_date_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity's start date rule
	column trueai_start_date_rule
		description: "TrueAI: Date/time when start date rule."
		dataType: int64
		formatString: 0
		lineageTag: 3951c187-168a-4a53-aab8-07547820d3a4
		summarizeBy: sum
		sourceColumn: trueai_start_date_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity creation date rule
	column trueai_created_on_rule
		description: "TrueAI: Numeric value for created on rule."
		dataType: int64
		formatString: 0
		lineageTag: 1cf4303b-6e94-4caf-82c1-0050d10a604d
		summarizeBy: sum
		sourceColumn: trueai_created_on_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity creator's id rule
	column trueai_creator_id_rule
		description: "TrueAI: Numeric value for creator id rule."
		dataType: int64
		formatString: 0
		lineageTag: 0ba1454d-e37c-4671-bc0b-bd906554582b
		summarizeBy: sum
		sourceColumn: trueai_creator_id_rule

		annotation SummarizationSetBy = Automatic

	/// Opportunity owner's id rule
	column trueai_owner_id_rule
		description: "TrueAI: Numeric value for owner id rule."
		dataType: int64
		formatString: 0
		lineageTag: e11373ab-6696-4f4b-88b9-cf1237cec1dc
		summarizeBy: sum
		sourceColumn: trueai_owner_id_rule

		annotation SummarizationSetBy = Automatic

	/// cust_text1
	column cust_text1
		description: "Text label for cust text1."
		dataType: string
		lineageTag: fe3cff9b-ca90-4d37-8657-b856c56ec451
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	/// cust_text2
	column cust_text2
		description: "Text label for cust text2."
		dataType: string
		lineageTag: f119aa48-2a30-4565-935b-3242c39339ec
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	/// cust_text3
	column cust_text3
		description: "Text label for cust text3."
		dataType: string
		lineageTag: 421a042d-5a6c-4151-a4c5-75fb48cc4d13
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	/// cust_text4
	column cust_text4
		description: "Text label for cust text4."
		dataType: string
		lineageTag: fe1ee96e-8099-4a00-b32c-869e5a3d379e
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	/// cust_text5
	column cust_text5
		description: "Text label for cust text5."
		dataType: string
		lineageTag: c96f83f9-bdd2-47ad-8465-f87a05307223
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	/// cust_num1
	column cust_num1
		description: "Count of cust num1."
		dataType: double
		lineageTag: 5a348056-2bca-4012-a5fb-9c91cc8e14a9
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num2
	column cust_num2
		description: "Count of cust num2."
		dataType: double
		lineageTag: b4e15cbb-9ea9-4fb5-aadb-caf347767268
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num3
	column cust_num3
		description: "Count of cust num3."
		dataType: double
		lineageTag: f43311cd-4a78-44bf-a75f-924dcc8a3e01
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num4
	column cust_num4
		description: "Count of cust num4."
		dataType: double
		lineageTag: 9a2127b8-fe5a-4345-8f43-e018c34f43b4
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num5
	column cust_num5
		description: "Count of cust num5."
		dataType: double
		lineageTag: 0e9e1ac1-3b76-4494-8efd-952b50238774
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num6
	column cust_num6
		description: "Count of cust num6."
		dataType: double
		lineageTag: 725861e0-4756-475e-b6db-5e0e528b4f5f
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_num7
	column cust_num7
		description: "Count of cust num7."
		dataType: double
		lineageTag: 9d2be5a9-2774-4697-9a0f-5ce54ac1d13c
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// cust_bool1
	column cust_bool1
		description: "Indicates whether cust bool1."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8f50bed2-78a0-48cd-9ffa-33a47ecc1fc5
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	/// cust_bool2
	column cust_bool2
		description: "Indicates whether cust bool2."
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9530aa93-5b86-4a46-83ea-a2302c85fa73
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	/// Opportunity's loss reason in the CRM
	column crm_loss_reason
		description: "CRM: Text label for loss reason."
		dataType: string
		lineageTag: c89e6b1f-5e75-40a4-adba-8c19d411ecb8
		summarizeBy: none
		sourceColumn: crm_loss_reason

		annotation SummarizationSetBy = Automatic

	/// CRM pipeline id of the opportunity
	column crm_pipeline_id
		description: "CRM: Identifier for pipeline."
		dataType: string
		lineageTag: c621778b-965e-4b68-9cf4-d1f8ccb8ec6d
		summarizeBy: none
		sourceColumn: crm_pipeline_id

		annotation SummarizationSetBy = Automatic

	/// CRM pipeline name of the opportunity
	column crm_pipeline_name
		description: "CRM: Text label for pipeline name."
		dataType: string
		lineageTag: cff75ad7-9162-4c31-8ca8-aae99f72eae1
		summarizeBy: none
		sourceColumn: crm_pipeline_name

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage ID in the CRM
	column crm_stage_id
		description: "CRM: Identifier for stage."
		dataType: string
		lineageTag: 686075b0-4f2c-453b-8d86-b59a631e5b25
		summarizeBy: none
		sourceColumn: crm_stage_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity Age
	column trueai_age
		description: "TrueAI: Numeric value for age."
		dataType: int64
		formatString: 0
		lineageTag: 6e9f9c2a-e416-4167-9042-9e430717223f
		summarizeBy: sum
		sourceColumn: trueai_age

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage ID
	column trueai_stage_id
		description: "TrueAI: Identifier for stage."
		dataType: string
		lineageTag: e4741ea0-94e0-4560-af27-48625f8f3f58
		summarizeBy: none
		sourceColumn: trueai_stage_id

		annotation SummarizationSetBy = Automatic

	/// Opportunity's stage name
	column trueai_stage_name
		description: "TrueAI: Text label for stage name."
		dataType: string
		lineageTag: cdb9c7a1-d855-4eba-9c11-f65755027c33
		summarizeBy: none
		sourceColumn: trueai_stage_name

		annotation SummarizationSetBy = Automatic

	/// Pipeline name of the opportunity
	column trueai_pipeline_name
		description: "TrueAI: Text label for pipeline name."
		dataType: string
		lineageTag: 5a0eaa5b-af49-4d22-80a5-8afdf9a8a48c
		summarizeBy: none
		sourceColumn: trueai_pipeline_name

		annotation SummarizationSetBy = Automatic

	/// Opportunity's loss reason
	column trueai_loss_reason
		description: "TrueAI: Text label for loss reason."
		dataType: string
		lineageTag: eb7e6e63-6e07-4999-a081-ae9516a7b504
		summarizeBy: none
		sourceColumn: trueai_loss_reason

		annotation SummarizationSetBy = Automatic

	/// Opportunity discount percentage tier
	column trueai_discount_pct_tier
		description: "TrueAI: Count of discount pct tier."
		dataType: string
		lineageTag: adbe027b-d27f-489b-8856-3d9280eaf4ad
		summarizeBy: none
		sourceColumn: trueai_discount_pct_tier

		annotation SummarizationSetBy = Automatic

	/// Opportunity's NNB amount
	column trueai_nnb_amt
		description: "TrueAI: Amount for nnb amt."
		dataType: double
		lineageTag: 15012e60-ba2f-461c-a7e3-1171df54a078
		summarizeBy: sum
		sourceColumn: trueai_nnb_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's downgrade amount
	column trueai_downgrade_amt
		description: "TrueAI: Amount for downgrade amt."
		dataType: double
		lineageTag: 2be34387-58f1-437c-a6d0-069b614aa0b0
		summarizeBy: sum
		sourceColumn: trueai_downgrade_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's Cross-Sale amount
	column trueai_cross_sale_amt
		description: "TrueAI: Amount for cross sale amt."
		dataType: double
		lineageTag: 408cc3c2-8405-4c2c-aacd-c4768e1b7786
		summarizeBy: sum
		sourceColumn: trueai_cross_sale_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's renewal amount
	column trueai_renewal_amt
		description: "TrueAI: Amount for renewal amt."
		dataType: double
		lineageTag: 19c8bd2d-2f54-445a-950d-ad49962d2e49
		summarizeBy: sum
		sourceColumn: trueai_renewal_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's expansion amount
	column trueai_expansion_amt
		description: "TrueAI: Amount for expansion amt."
		dataType: double
		lineageTag: ff8b6020-587d-4364-9205-30fdd2caed80
		summarizeBy: sum
		sourceColumn: trueai_expansion_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's one time amount
	column trueai_one_time_amt
		description: "TrueAI: Date/time when one time amt."
		dataType: double
		lineageTag: 7eed184c-b9f8-4277-a6e5-2c4f3b17fcac
		summarizeBy: sum
		sourceColumn: trueai_one_time_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's non determinable amount
	column trueai_nd_amt
		description: "TrueAI: Amount for nd amt."
		dataType: double
		lineageTag: ddc826d6-c947-4a12-bfcd-9c9ee4da67d0
		summarizeBy: sum
		sourceColumn: trueai_nd_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's ARR amount
	column trueai_arr_amt
		description: "TrueAI: Amount for arr amt."
		dataType: double
		lineageTag: 7715a470-91ba-4b02-9f44-fbcf563ca5a8
		summarizeBy: sum
		sourceColumn: trueai_arr_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Opportunity's last crm stage, before it was lost
	column trueai_lost_crm_stage
		description: "TrueAI: Text label for lost crm stage."
		dataType: string
		lineageTag: 12bc86dc-384d-4c28-990e-4943ea62dc8e
		summarizeBy: none
		sourceColumn: trueai_lost_crm_stage

		annotation SummarizationSetBy = Automatic

	/// Opportunity's Initial Subscription amount
	column trueai_initial_subscription_amt
		description: "TrueAI: Amount for initial subscription amt."
		dataType: double
		lineageTag: 34a3b594-8d4f-450a-9e6e-cb3b48b1332b
		summarizeBy: sum
		sourceColumn: trueai_initial_subscription_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition opps-7efea0ac-85ea-4ff0-8641-71292e110fb6 = m
		mode: import
		source =
				let
				  dbTable = getDBTable("opps"), // get the right table
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				    {"crm_pipeline_name", type text},
				{"crm_stage_id", type text},
				{"crm_stage_name", type text},
				{"crm_stage_num", Int64.Type},
				{"crm_type", type text},
				{"cust_bool1", type logical},
				{"cust_bool2", type logical},
				{"cust_num1", type number},
				{"cust_num2", type number},
				{"cust_num3", type number},
				{"cust_num4", type number},
				{"cust_num5", type number},
				{"cust_num6", type number},
				{"cust_num7", type number},
				{"cust_text1", type text},
				{"cust_text2", type text},
				{"cust_text3", type text},
				{"cust_text4", type text},
				{"cust_text5", type text},
				{"trueai_account_id", type text},
				{"trueai_account_id_conf", type number},
				{"trueai_account_id_rule", Int64.Type},
				{"trueai_addr_city", type text},
				{"trueai_addr_country", type text},
				{"trueai_addr_lat", type number},
				{"trueai_addr_long", type number},
				{"trueai_addr_postal_code", type text},
				{"trueai_addr_rule", Int64.Type},
				{"trueai_addr_state", type text},
				{"trueai_addr_street", type text},
				{"trueai_age", Int64.Type},
				{"trueai_arr_amt", type number},
				{"trueai_booking_amt", type number},
				{"trueai_booking_amt_currency_rule", Int64.Type},
				{"trueai_booking_amt_rule", Int64.Type},
				{"trueai_close_date", type datetime},
				{"trueai_close_date_rule", Int64.Type},
				{"trueai_company_size", type text},
				{"trueai_company_size_rule", Int64.Type},
				{"trueai_complt", type number},
				{"trueai_complt_contact", type number},
				{"trueai_complt_marketing", type number},
				{"trueai_created_from_entity", type text},
				{"trueai_created_from_id", type text},
				{"trueai_created_on", type datetime},
				{"trueai_created_on_rule", Int64.Type},
				{"trueai_creator_id", type text},
				{"trueai_creator_id_rule", Int64.Type},
				{"trueai_cross_sale_amt", type number},
				{"trueai_discount_amt", type number},
				{"trueai_discount_pct", type number},
				{"trueai_discount_pct_tier", type text},
				{"trueai_downgrade_amt", type number},
				{"trueai_dur", Int64.Type},
				{"trueai_expansion_amt", type number},
				{"trueai_industry", type text},
				{"trueai_industry_conf", type number},
				{"trueai_industry_rule", Int64.Type},
				{"trueai_initial_subscription_amt", type number},
				{"trueai_is_erp", type logical},
				{"trueai_is_new_logo", type logical},
				{"trueai_is_won", type logical},
				{"trueai_leadsource", type text},
				{"trueai_leadsource_conf", type number},
				{"trueai_leadsource_rule", Int64.Type},
				{"trueai_loss_reason", type text},
				{"trueai_lost_crm_stage", type text},
				{"trueai_nd_amt", type number},
				{"trueai_nnb_amt", type number},
				{"trueai_one_time_amt", type number},
				{"trueai_opp_stage_late_date", type datetime},
				{"trueai_opp_stage_mid_date", type datetime},
				{"trueai_owner_id", type text},
				{"trueai_owner_id_rule", Int64.Type},
				{"trueai_pipeline_name", type text},
				{"trueai_prob_of_win", type number},
				{"trueai_qual_bucket", type text},
				{"trueai_qual_bucket_num", Int64.Type},
				{"trueai_renewal_amt", type number},
				{"trueai_sale_type", type text},
				{"trueai_sale_type_conf", type number},
				{"trueai_stage", type text},
				{"trueai_stage_id", type text},
				{"trueai_stage_name", type text},
				{"trueai_start_date_rule", Int64.Type},
				{"trueai_test", type text},
				{"trueai_test_conf", type number},
				{"trueai_test_debug", type text},
				{"trueai_test_rule", type text},
				{"_sys_as_of", type datetime},
				{"_sys_doc_id", type text},
				{"_sys_filt_end_date", type date},
				{"_sys_filt_start_date", type date},
				{"_sys_is_active", type logical},
				{"_sys_last_modified_on", type datetime},
				{"_sys_ssr_id", type text},
				{"crm_account_custom_value_1", type text},
				{"crm_account_custom_value_2", type text},
				{"crm_account_custom_value_3", type text},
				{"crm_account_id", type text},
				{"crm_booking_amt", type number},
				{"crm_close_date", type datetime},
				{"crm_complt", type number},
				{"crm_complt_contact", type number},
				{"crm_complt_custom", type number},
				{"crm_complt_marketing", type number},
				{"crm_created_on", type datetime},
				{"crm_creator_id", type text},
				{"crm_currency", type text},
				{"crm_custom_value_1", type text},
				{"crm_custom_value_2", type text},
				{"crm_custom_value_3", type text},
				{"crm_deep_link", type text},
				{"crm_is_closed", type logical},
				{"crm_is_won", type logical},
				{"crm_last_act_time", type datetime},
				{"crm_leadsource", type text},
				{"crm_loss_reason", type text},
				{"crm_modified_on", type datetime},
				{"crm_name", type text},
				{"crm_owner_id", type text},
				{"crm_pipeline_id", type text}
				
				
				  }),
				
				dbTableTypedRenamed = Table.RenameColumns(dbTableTyped,{ // rename one more time to not have to redo column names in reports
				
				{"_sys_doc_id", "_sys_docid"}
				})
				in
				    dbTableTypedRenamed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

