table opps
	lineageTag: 4277295b-2fd7-47a1-b82b-5de4b447fb12

	measure 'meas.opp_trueai_completeness_improvement' = ```
			
			var crmval = CALCULATE(AVERAGE([crm_complt]))
			var aival = CALCULATE(AVERAGE([trueai_complt]))
			var impro = Divide(aival - crmval, crmval) 
			var res = If(impro > 0, "+" & FORMAT( impro, "###%"),  "No change")
			return res 
			
			```
		formatString: 0 %
		lineageTag: 7282e887-bcaf-41aa-b41c-9e863ab86f59

	column _sys_ssr_id
		dataType: string
		lineageTag: 068c6a2d-be04-474a-a201-5f2bba17dbb3
		summarizeBy: none
		sourceColumn: _sys_ssr_id

		annotation SummarizationSetBy = Automatic

	column crm_name
		dataType: string
		lineageTag: c2656224-81d4-4a43-8fa3-102dd26f2af1
		summarizeBy: none
		sourceColumn: crm_name

		annotation SummarizationSetBy = Automatic

	column crm_deep_link
		dataType: string
		lineageTag: 278fbcf3-b41a-44b4-b4b6-bf2c71b75301
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	column crm_booking_amt
		dataType: decimal
		lineageTag: a1803061-2073-4961-b70a-eaf839c0b5b8
		summarizeBy: sum
		sourceColumn: crm_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 48586531-6700-4b08-8a57-8f1269810656
		summarizeBy: none
		sourceColumn: crm_close_date

		variation Variation
			isDefault
			relationship: 58d304b7-072a-4034-b204-78d2e8d6fd75
			defaultHierarchy: LocalDateTable_29eafee9-9420-4f61-839f-959fae174886.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_currency
		dataType: string
		lineageTag: 1f4f6bac-98e9-4d9a-97b4-f6bfa484ac44
		summarizeBy: none
		sourceColumn: crm_currency

		annotation SummarizationSetBy = Automatic

	column crm_leadsource
		dataType: string
		lineageTag: 4f726618-6bc3-429c-9c16-a793fcf15ff5
		summarizeBy: none
		sourceColumn: crm_leadsource

		annotation SummarizationSetBy = Automatic

	column crm_stage_name
		dataType: string
		lineageTag: 9513b2ce-c3bf-460b-ba1c-4266fd204493
		summarizeBy: none
		sourceColumn: crm_stage_name

		annotation SummarizationSetBy = Automatic

	column crm_stage_num
		dataType: int64
		formatString: 0
		lineageTag: f17033ff-a5c1-4337-9859-b134ebe61f28
		summarizeBy: sum
		sourceColumn: crm_stage_num

		annotation SummarizationSetBy = Automatic

	column crm_type
		dataType: string
		lineageTag: a0467423-b728-42d4-a0fc-4483577a7442
		summarizeBy: none
		sourceColumn: crm_type

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt
		dataType: decimal
		lineageTag: 93945286-f8de-4b88-82cb-620bb5a23717
		summarizeBy: sum
		sourceColumn: trueai_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_pred_booking_amt
		dataType: decimal
		lineageTag: e4ce187a-225d-4b44-87bb-df2bb5d7d05e
		summarizeBy: sum
		sourceColumn: trueai_pred_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 2e5c1281-317c-42fb-a734-123ba8852877
		summarizeBy: none
		sourceColumn: trueai_close_date

		variation Variation
			isDefault
			relationship: e39668f7-aa9e-4a33-bf31-3f12965785b4
			defaultHierarchy: LocalDateTable_29323c1d-ac48-43e6-b585-07bebbf9c8ce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource
		dataType: string
		lineageTag: 842625c6-762b-4147-85b3-b0c9c99e47db
		summarizeBy: none
		sourceColumn: trueai_leadsource

		annotation SummarizationSetBy = Automatic

	column trueai_industry
		dataType: string
		lineageTag: 696bf1ab-e6ed-4e10-8d8d-272e3ce0f730
		summarizeBy: none
		sourceColumn: trueai_industry

		annotation SummarizationSetBy = Automatic

	column trueai_company_size
		dataType: string
		lineageTag: c2557585-eaa5-406b-bc54-ec9d57b9900a
		summarizeBy: none
		sourceColumn: trueai_company_size

		annotation SummarizationSetBy = Automatic

	column trueai_is_new_logo
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 989bf5b9-da0d-4ee6-bd02-2fe6b3c211f9
		summarizeBy: none
		sourceColumn: trueai_is_new_logo

		annotation SummarizationSetBy = Automatic

	column trueai_sale_type
		dataType: string
		lineageTag: 9b7d2e0e-4419-4aa0-9856-10dec214d42b
		summarizeBy: none
		sourceColumn: trueai_sale_type

		annotation SummarizationSetBy = Automatic

	column trueai_vi_repeat_value
		dataType: decimal
		lineageTag: 353f015c-8b9b-4263-8845-12c391a7be7e
		summarizeBy: sum
		sourceColumn: trueai_vi_repeat_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_vi_post_sales_value
		dataType: decimal
		lineageTag: 99b33eda-53ff-49e1-85ff-dbbf6b838844
		summarizeBy: sum
		sourceColumn: trueai_vi_post_sales_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_vi_prospecting_value
		dataType: decimal
		lineageTag: a3b7bdcd-a978-4d7e-9b30-6aee3ff88bd3
		summarizeBy: sum
		sourceColumn: trueai_vi_prospecting_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_vi_opp_value
		dataType: decimal
		lineageTag: 1d00ad62-9169-425b-b4e6-1057cfa271dd
		summarizeBy: sum
		sourceColumn: trueai_vi_opp_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_opp_stage_mid_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d9a2a43-6a90-4d6f-8f50-edbd5eca1065
		summarizeBy: none
		sourceColumn: trueai_opp_stage_mid_date

		variation Variation
			isDefault
			relationship: 0f20103f-04d7-45fa-be03-42ff31a10622
			defaultHierarchy: LocalDateTable_ac18bf8a-f848-4d1a-9994-87cb3c102203.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_opp_stage_late_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9771a63b-f3ba-497c-87f3-72db5e810c54
		summarizeBy: none
		sourceColumn: trueai_opp_stage_late_date

		variation Variation
			isDefault
			relationship: aff3dfab-6438-42e7-864e-ec42bd73db4a
			defaultHierarchy: LocalDateTable_72c98827-7095-4224-8a98-7ff8a40d066f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_discount
		dataType: decimal
		lineageTag: 0da79087-e97b-40ee-a06d-caa9ea3ca715
		summarizeBy: sum
		sourceColumn: trueai_discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_qual_bucket
		dataType: string
		lineageTag: 33dacbdb-aa27-4569-842d-a68d5df4b162
		summarizeBy: none
		sourceColumn: trueai_qual_bucket

		annotation SummarizationSetBy = Automatic

	column trueai_company_size_rule
		dataType: int64
		formatString: 0
		lineageTag: 70da4074-615d-4944-9b41-3ad644716b88
		summarizeBy: sum
		sourceColumn: trueai_company_size_rule

		annotation SummarizationSetBy = Automatic

	column trueai_industry_rule
		dataType: int64
		formatString: 0
		lineageTag: 405799e1-9e8f-4bd7-bb33-17e262116231
		summarizeBy: sum
		sourceColumn: trueai_industry_rule

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource_rule
		dataType: int64
		formatString: 0
		lineageTag: 5cf07be5-ea59-41d8-8ad1-149989c6d750
		summarizeBy: sum
		sourceColumn: trueai_leadsource_rule

		annotation SummarizationSetBy = Automatic

	column _sys_docid
		dataType: string
		lineageTag: 4c4c765b-b094-4e78-9d2c-98e352479ee8
		summarizeBy: none
		sourceColumn: _sys_docid

		annotation SummarizationSetBy = Automatic

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5a5ab94b-7f4e-45a3-81d8-64ffdf11afac
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: af488047-3ecc-45b6-a976-68a40a0171c8
			defaultHierarchy: LocalDateTable_b47d6e1a-e681-4cdc-968a-8ae0f1d92e8a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb9b8be5-0fa7-44fc-8a1c-027d5b4a290e
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column crm_account_id
		dataType: string
		lineageTag: 8bfebe69-9b96-48b8-9b35-5c835a6fd81a
		summarizeBy: none
		sourceColumn: crm_account_id

		annotation SummarizationSetBy = Automatic

	column crm_complt
		dataType: double
		lineageTag: 27d9c40c-eb3d-42bd-8255-2f953d6fdda7
		summarizeBy: sum
		sourceColumn: crm_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_contact
		dataType: double
		lineageTag: 6182e8bb-f0e3-42e0-adc4-22ac2a3db69e
		summarizeBy: sum
		sourceColumn: crm_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_marketing
		dataType: double
		lineageTag: 1f82c4a7-7ee5-472e-b608-eda124921bdd
		summarizeBy: sum
		sourceColumn: crm_complt_marketing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_creator_id
		dataType: string
		lineageTag: 1a496b42-c56d-4d92-a34a-5b05eb365f85
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_last_act_time
		dataType: dateTime
		formatString: General Date
		lineageTag: bc2ece06-5ac4-48ea-b430-43b83dff945c
		summarizeBy: none
		sourceColumn: crm_last_act_time

		variation Variation
			isDefault
			relationship: e347e02a-f7b9-41fe-9957-f6dc238dd14e
			defaultHierarchy: LocalDateTable_28e862d0-6e5a-47c3-ae31-d7ff8503cf73.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_owner_id
		dataType: string
		lineageTag: e79a1f42-a883-449c-921d-875121187958
		summarizeBy: none
		sourceColumn: crm_owner_id

		annotation SummarizationSetBy = Automatic

	column trueai_addr_city
		dataType: string
		lineageTag: acef1ff0-68ed-4269-bef1-6dd78cc44e6c
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	column trueai_addr_country
		dataType: string
		lineageTag: 33e4cb1d-8d14-4178-b2d9-be3a5c89dfdc
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	column trueai_addr_postal_code
		dataType: string
		lineageTag: fb94a4e9-78e3-4849-93a6-0efc6bfa537f
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column trueai_addr_rule
		dataType: int64
		formatString: 0
		lineageTag: 7178fae6-aa69-4f77-89e6-45524b20fb4b
		summarizeBy: sum
		sourceColumn: trueai_addr_rule

		annotation SummarizationSetBy = Automatic

	column trueai_addr_state
		dataType: string
		lineageTag: c9a15770-da6c-4994-af38-906b6300864a
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	column trueai_addr_street
		dataType: string
		lineageTag: 8646f0d2-03e8-4294-a19d-7c283f323a6f
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	column trueai_complt
		dataType: double
		lineageTag: 86ab3cd5-4fe4-4f00-95c1-0767e56552c0
		summarizeBy: sum
		sourceColumn: trueai_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_complt_contact
		dataType: double
		lineageTag: ef08d4c3-eb87-4137-8b93-782a2b6d0eda
		summarizeBy: sum
		sourceColumn: trueai_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_complt_marketing
		dataType: double
		lineageTag: 7a1114c8-a824-4fd0-8bc7-d572fbeef21d
		summarizeBy: sum
		sourceColumn: trueai_complt_marketing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_creator_id
		dataType: string
		lineageTag: b67881e7-dd9d-4671-9169-a5bb51140c9d
		summarizeBy: none
		sourceColumn: trueai_creator_id

		annotation SummarizationSetBy = Automatic

	column trueai_dur
		dataType: int64
		lineageTag: fc30936e-9c80-418e-83bc-20dadaf45689
		summarizeBy: sum
		sourceColumn: trueai_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_industry_conf
		dataType: double
		lineageTag: 65d477e3-23c9-4122-a7c1-5d7943da50c3
		summarizeBy: sum
		sourceColumn: trueai_industry_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_leadsource_conf
		dataType: double
		lineageTag: 0cace160-468e-45dc-819b-bc4b273589f3
		summarizeBy: sum
		sourceColumn: trueai_leadsource_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_owner_id
		dataType: string
		lineageTag: d273f151-efd6-47b2-aabd-6bcf806b5fe2
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	column trueai_sale_type_conf
		dataType: double
		lineageTag: a02bebd0-7814-4f36-b65c-a18d636ea34f
		summarizeBy: sum
		sourceColumn: trueai_sale_type_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_account_custom_value_1
		dataType: string
		isHidden
		lineageTag: e9d6d4d6-07ac-4b34-99b5-87d2e0176b13
		summarizeBy: none
		sourceColumn: crm_account_custom_value_1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column crm_account_custom_value_2
		dataType: string
		lineageTag: af53eced-5aef-4585-bc13-a68a24452119
		summarizeBy: none
		sourceColumn: crm_account_custom_value_2

		annotation SummarizationSetBy = Automatic

	column crm_account_custom_value_3
		dataType: string
		lineageTag: c502b962-6875-442b-80d1-763563eee54a
		summarizeBy: none
		sourceColumn: crm_account_custom_value_3

		annotation SummarizationSetBy = Automatic

	column crm_custom_value_1
		dataType: string
		lineageTag: 5cc9d428-8116-4b40-8ce5-014af57251c4
		summarizeBy: none
		sourceColumn: crm_custom_value_1

		annotation SummarizationSetBy = Automatic

	column crm_custom_value_2
		dataType: string
		lineageTag: fd5e8882-a8d2-4311-af5a-c4b0cb0501f5
		summarizeBy: none
		sourceColumn: crm_custom_value_2

		annotation SummarizationSetBy = Automatic

	column crm_custom_value_3
		dataType: string
		lineageTag: 1ad95fc2-dfac-47f4-a259-4d45f7c47147
		summarizeBy: none
		sourceColumn: crm_custom_value_3

		annotation SummarizationSetBy = Automatic

	column trueai_addr_lat
		dataType: double
		lineageTag: 80713b91-8088-414c-b9f0-dc248e498a21
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_long
		dataType: double
		lineageTag: 1b6b9893-a061-40bf-95d0-12493c49fc5a
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_booking_amt_rule
		dataType: int64
		formatString: 0
		lineageTag: 5caf1296-2f16-4d9c-b9c3-813050765aef
		summarizeBy: sum
		sourceColumn: trueai_booking_amt_rule

		annotation SummarizationSetBy = Automatic

	column trueai_qual_bucket_num
		dataType: int64
		formatString: 0
		lineageTag: 0bafe83f-36cb-485e-a258-c4c53cb803a6
		summarizeBy: sum
		sourceColumn: trueai_qual_bucket_num

		annotation SummarizationSetBy = Automatic

	column crm_complt_custom
		dataType: double
		lineageTag: c27d3ff1-0185-417e-ac64-792ba0006253
		summarizeBy: sum
		sourceColumn: crm_complt_custom

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: bc7614c3-8503-49a2-8408-cc686c19960c
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: cd7469ff-1ad9-4d27-a088-f9d92df13881
			defaultHierarchy: LocalDateTable_6a25f2c9-f8db-4b53-b19f-c31b87f63ed9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ba53617c-16b9-40c2-9537-694ffe30623d
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: f54e24d3-aac3-49e1-8046-bf2fbcf5346a
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 7e84575d-ebfb-4b20-9577-9e73daabc4e0
			defaultHierarchy: LocalDateTable_d6c9441c-f5bf-474a-b755-76426451563e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 2f656dba-9955-4841-b328-16a370231d07
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 58ed177e-b8a0-4430-a353-3386331c5e25
			defaultHierarchy: LocalDateTable_b5a2c35e-e84f-42da-9db1-5ff88827db21.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_is_closed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ffb8b0ec-07a3-4582-8c13-e531cc902195
		summarizeBy: none
		sourceColumn: crm_is_closed

		annotation SummarizationSetBy = Automatic

	column crm_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8526a248-f13a-4341-959a-d2a7a5d53bf8
		summarizeBy: none
		sourceColumn: crm_is_won

		annotation SummarizationSetBy = Automatic

	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: aec9eeb8-bec8-4b92-babd-94c3c40e96da
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: 75381359-0703-40fb-9373-03d081e9e67a
			defaultHierarchy: LocalDateTable_bce856a2-bc85-4d4b-9a27-84618f90188c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_created_from_entity
		dataType: string
		lineageTag: af89d79f-a7bf-40cb-90f2-1ba80a19c81d
		summarizeBy: none
		sourceColumn: trueai_created_from_entity

		annotation SummarizationSetBy = Automatic

	column trueai_created_from_id
		dataType: string
		lineageTag: 89effb20-308b-4349-9417-3a0390fa5c9c
		summarizeBy: none
		sourceColumn: trueai_created_from_id

		annotation SummarizationSetBy = Automatic

	column trueai_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 2843cefb-64b0-4e3e-a5dd-5531b0f11c3e
		summarizeBy: none
		sourceColumn: trueai_created_on

		variation Variation
			isDefault
			relationship: 76a33ae6-4d13-47a1-9146-b187efeae260
			defaultHierarchy: LocalDateTable_8d9c2ad2-afbe-49ff-aed4-db4a012c6a94.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ab6f4266-be46-49b1-9aa5-8dfc92650ea9
		summarizeBy: none
		sourceColumn: trueai_is_won

		annotation SummarizationSetBy = Automatic

	column trueai_stage
		dataType: string
		lineageTag: 31aeb6d1-40a2-4e47-8a25-935f89a8573e
		summarizeBy: none
		sourceColumn: trueai_stage

		annotation SummarizationSetBy = Automatic

	column trueai_prob_of_next_opp
		dataType: double
		lineageTag: 9f7f7dd5-6464-4d87-9714-a55d949009db
		summarizeBy: sum
		sourceColumn: trueai_prob_of_next_opp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_prob_of_next_opp_explained
		dataType: string
		lineageTag: b78637ba-d959-415f-af1d-5c48af558faa
		summarizeBy: none
		sourceColumn: trueai_prob_of_next_opp_explained

		annotation SummarizationSetBy = Automatic

	column trueai_prob_of_win
		dataType: double
		lineageTag: a1d0c01d-8d25-4303-9f12-945e43fecd3a
		summarizeBy: sum
		sourceColumn: trueai_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_prob_of_win_explained
		dataType: string
		lineageTag: fe83202d-d69e-418b-97e7-8d96dbf515d7
		summarizeBy: none
		sourceColumn: trueai_prob_of_win_explained

		annotation SummarizationSetBy = Automatic

	column trueai_discount_amt
		dataType: decimal
		lineageTag: 4c4d1b13-ca33-47eb-8c2d-4221e15509b8
		summarizeBy: sum
		sourceColumn: trueai_discount_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_discount_pct
		dataType: double
		lineageTag: 9277eec1-452b-49cc-83ca-ef7907d5829f
		summarizeBy: sum
		sourceColumn: trueai_discount_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_is_erp
		dataType: string
		lineageTag: 017de80e-c49a-4333-a1f7-0f4f72d37bea
		summarizeBy: none
		sourceColumn: trueai_is_erp

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt_currency_rule
		dataType: string
		lineageTag: cad47743-e6a8-4028-ad99-91ea44a8111f
		summarizeBy: none
		sourceColumn: trueai_booking_amt_currency_rule

		annotation SummarizationSetBy = Automatic

	column trueai_account_id
		dataType: string
		lineageTag: b361074d-2e04-434e-865b-785b04a1b5ce
		summarizeBy: none
		sourceColumn: trueai_account_id

		annotation SummarizationSetBy = Automatic

	column trueai_account_id_rule
		dataType: string
		lineageTag: 40cb1717-d850-47f1-a44d-6ed84ed4d0a7
		summarizeBy: none
		sourceColumn: trueai_account_id_rule

		annotation SummarizationSetBy = Automatic

	column trueai_account_id_conf
		dataType: string
		lineageTag: 441bc720-2a6c-416a-937f-a0364f63c616
		summarizeBy: none
		sourceColumn: trueai_account_id_conf

		annotation SummarizationSetBy = Automatic

	column trueai_test
		dataType: string
		lineageTag: ae610465-1d85-4e27-be3e-157a0333b680
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	column trueai_test_conf
		dataType: string
		lineageTag: 32c3aff2-227c-4caa-9777-92b446ce770e
		summarizeBy: none
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

	column trueai_test_rule
		dataType: string
		lineageTag: ea3b8c35-8502-4b7b-bd57-fd215806bb87
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	column trueai_test_debug
		dataType: string
		lineageTag: fdd82951-47f4-4190-b879-3a2a8e31224e
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	column trueai_close_date_rule
		dataType: string
		lineageTag: bb1bf736-b666-4d32-82a1-e97cb34f280a
		summarizeBy: none
		sourceColumn: trueai_close_date_rule

		annotation SummarizationSetBy = Automatic

	column trueai_start_date_rule
		dataType: string
		lineageTag: 3951c187-168a-4a53-aab8-07547820d3a4
		summarizeBy: none
		sourceColumn: trueai_start_date_rule

		annotation SummarizationSetBy = Automatic

	column trueai_created_on_rule
		dataType: string
		lineageTag: 1cf4303b-6e94-4caf-82c1-0050d10a604d
		summarizeBy: none
		sourceColumn: trueai_created_on_rule

		annotation SummarizationSetBy = Automatic

	column trueai_creator_id_rule
		dataType: string
		lineageTag: 0ba1454d-e37c-4671-bc0b-bd906554582b
		summarizeBy: none
		sourceColumn: trueai_creator_id_rule

		annotation SummarizationSetBy = Automatic

	column trueai_owner_id_rule
		dataType: string
		lineageTag: e11373ab-6696-4f4b-88b9-cf1237cec1dc
		summarizeBy: none
		sourceColumn: trueai_owner_id_rule

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: fe3cff9b-ca90-4d37-8657-b856c56ec451
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: f119aa48-2a30-4565-935b-3242c39339ec
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: 421a042d-5a6c-4151-a4c5-75fb48cc4d13
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: fe1ee96e-8099-4a00-b32c-869e5a3d379e
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: c96f83f9-bdd2-47ad-8465-f87a05307223
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: string
		lineageTag: 5a348056-2bca-4012-a5fb-9c91cc8e14a9
		summarizeBy: none
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

	column cust_num2
		dataType: string
		lineageTag: b4e15cbb-9ea9-4fb5-aadb-caf347767268
		summarizeBy: none
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

	column cust_num3
		dataType: string
		lineageTag: f43311cd-4a78-44bf-a75f-924dcc8a3e01
		summarizeBy: none
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

	column cust_num4
		dataType: string
		lineageTag: 9a2127b8-fe5a-4345-8f43-e018c34f43b4
		summarizeBy: none
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

	column cust_num5
		dataType: string
		lineageTag: 0e9e1ac1-3b76-4494-8efd-952b50238774
		summarizeBy: none
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

	column cust_num6
		dataType: string
		lineageTag: 725861e0-4756-475e-b6db-5e0e528b4f5f
		summarizeBy: none
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

	column cust_num7
		dataType: string
		lineageTag: 9d2be5a9-2774-4697-9a0f-5ce54ac1d13c
		summarizeBy: none
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

	column cust_bool1
		dataType: string
		lineageTag: 8f50bed2-78a0-48cd-9ffa-33a47ecc1fc5
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: string
		lineageTag: 9530aa93-5b86-4a46-83ea-a2302c85fa73
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	column crm_loss_reason
		dataType: string
		lineageTag: c89e6b1f-5e75-40a4-adba-8c19d411ecb8
		summarizeBy: none
		sourceColumn: crm_loss_reason

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_id
		dataType: string
		lineageTag: c621778b-965e-4b68-9cf4-d1f8ccb8ec6d
		summarizeBy: none
		sourceColumn: crm_pipeline_id

		annotation SummarizationSetBy = Automatic

	column crm_pipeline_name
		dataType: string
		lineageTag: cff75ad7-9162-4c31-8ca8-aae99f72eae1
		summarizeBy: none
		sourceColumn: crm_pipeline_name

		annotation SummarizationSetBy = Automatic

	column crm_stage_id
		dataType: string
		lineageTag: 686075b0-4f2c-453b-8d86-b59a631e5b25
		summarizeBy: none
		sourceColumn: crm_stage_id

		annotation SummarizationSetBy = Automatic

	column trueai_age
		dataType: string
		lineageTag: 6e9f9c2a-e416-4167-9042-9e430717223f
		summarizeBy: none
		sourceColumn: trueai_age

		annotation SummarizationSetBy = Automatic

	column trueai_stage_id
		dataType: string
		lineageTag: e4741ea0-94e0-4560-af27-48625f8f3f58
		summarizeBy: none
		sourceColumn: trueai_stage_id

		annotation SummarizationSetBy = Automatic

	column trueai_stage_name
		dataType: string
		lineageTag: cdb9c7a1-d855-4eba-9c11-f65755027c33
		summarizeBy: none
		sourceColumn: trueai_stage_name

		annotation SummarizationSetBy = Automatic

	column trueai_pipeline_name
		dataType: string
		lineageTag: 5a0eaa5b-af49-4d22-80a5-8afdf9a8a48c
		summarizeBy: none
		sourceColumn: trueai_pipeline_name

		annotation SummarizationSetBy = Automatic

	column trueai_loss_reason
		dataType: string
		lineageTag: eb7e6e63-6e07-4999-a081-ae9516a7b504
		summarizeBy: none
		sourceColumn: trueai_loss_reason

		annotation SummarizationSetBy = Automatic

	column trueai_discount_pct_tier
		dataType: string
		lineageTag: adbe027b-d27f-489b-8856-3d9280eaf4ad
		summarizeBy: none
		sourceColumn: trueai_discount_pct_tier

		annotation SummarizationSetBy = Automatic

	partition opps-7efea0ac-85ea-4ff0-8641-71292e110fb6 = m
		mode: import
		source =
				let
				  dbTable = getDBTable("opps"), // get the right table
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				    {"_sys_as_of", type datetime},
				{"_sys_doc_id", type text},
				{"_sys_filt_end_date", type date},
				{"_sys_filt_start_date", type date},
				{"_sys_is_active", type logical},
				{"_sys_last_modified_on", type datetime},
				{"_sys_ssr_id", type text},
				{"crm_account_custom_value_1", type text},
				{"crm_account_custom_value_2", type text},
				{"crm_account_custom_value_3", type text},
				{"crm_account_id", type text},
				{"crm_booking_amt",   Currency.Type},
				{"crm_close_date", type datetime},
				{"crm_complt",  type number},
				{"crm_complt_contact",  type number},
				{"crm_complt_custom",  type number},
				{"crm_complt_marketing",  type number},
				{"crm_created_on", type datetime},
				{"crm_creator_id", type text},
				{"crm_currency", type text},
				{"crm_custom_value_1", type text},
				{"crm_custom_value_2", type text},
				{"crm_custom_value_3", type text},
				{"crm_deep_link", type text},
				{"crm_is_closed", type logical},
				{"crm_is_won", type logical},
				{"crm_last_act_time", type datetime},
				{"crm_leadsource", type text},
				{"crm_modified_on", type datetime},
				{"crm_name", type text},
				{"crm_owner_id", type text},
				{"crm_stage_name", type text},
				{"crm_stage_num", Int64.Type},
				{"crm_type", type text},
				{"trueai_addr_city", type text},
				{"trueai_addr_country", type text},
				{"trueai_addr_lat",  type number},
				{"trueai_addr_long",  type number},
				{"trueai_addr_postal_code", type text},
				{"trueai_addr_rule", Int64.Type},
				{"trueai_addr_state", type text},
				{"trueai_addr_street", type text},
				{"trueai_booking_amt",   Currency.Type},
				{"trueai_booking_amt_rule", Int64.Type},
				{"trueai_close_date", type datetime},
				{"trueai_company_size", type text},
				{"trueai_company_size_rule", Int64.Type},
				{"trueai_complt",  type number},
				{"trueai_complt_contact",  type number},
				{"trueai_complt_marketing",  type number},
				{"trueai_created_from_entity", type text},
				{"trueai_created_from_id", type text},
				{"trueai_created_on", type datetime},
				{"trueai_creator_id", type text},
				{"trueai_discount",   Currency.Type},
				{"trueai_discount_amt",   Currency.Type},
				{"trueai_discount_pct",  type number},
				{"trueai_dur", Int64.Type},
				{"trueai_industry", type text},
				{"trueai_industry_conf",  type number},
				{"trueai_industry_rule", Int64.Type},
				{"trueai_is_new_logo", type logical},
				{"trueai_is_won", type logical},
				{"trueai_leadsource", type text},
				{"trueai_leadsource_conf",  type number},
				{"trueai_leadsource_rule", Int64.Type},
				{"trueai_opp_stage_late_date", type datetime},
				{"trueai_opp_stage_mid_date", type datetime},
				{"trueai_owner_id", type text},
				{"trueai_pred_booking_amt",   Currency.Type},
				{"trueai_prob_of_next_opp",  type number},
				{"trueai_prob_of_next_opp_explained", type text},
				{"trueai_prob_of_win",  type number},
				{"trueai_prob_of_win_explained", type text},
				{"trueai_qual_bucket", type text},
				{"trueai_qual_bucket_num", Int64.Type},
				{"trueai_sale_type", type text},
				{"trueai_sale_type_conf",  type number},
				{"trueai_stage", type text},
				{"trueai_vi_opp_value",   Currency.Type},
				{"trueai_vi_post_sales_value",   Currency.Type},
				{"trueai_vi_prospecting_value",   Currency.Type},
				{"trueai_vi_repeat_value",   Currency.Type}
				
				
				  }),
				
				dbTableTypedRenamed = Table.RenameColumns(dbTableTyped,{ // rename one more time to not have to redo column names in reports
				
				{"_sys_doc_id", "_sys_docid"}
				})
				in
				    dbTableTypedRenamed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

