/// Derived entity for monthly snapshots of user-level performance. One row per user per month. Includes User metadata, Deal Intelligence (DI), Coaching Intelligence (CI), and Automatic Data Enhancement (ADE) metrics. Historical depth: 6 years retroactive.
table users_history
	lineageTag: 44776101-2806-4700-a1fe-2ddb9f44c42c

	measure 'meas.users_history_duration_hrs' =
		description: "Purpose: Compute the measure result from the DAX expression and current filter context.\nCalculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..\nDynamic Behavior: No explicit conditional branching detected.\nFormat/Type: ###,###,###  hrs"
			
			var dur = CALCULATE(sum(users_history[ci_time_alloc_tot_dur]))
			var res =  dur / 3600
			return res
			// act_tot_dur
		formatString: ###,###,###  hrs
		displayFolder: _users_history_analysis
		lineageTag: c0955f41-6d5c-4dc1-a7af-02b99e36f0e7

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.users_history_duration_per_act_min' = ```
			
			var dur = CALCULATE(sum(users_history[ci_time_alloc_tot_dur]))		//get the allocated total duration
			var act = CALCULATE(sum(users_history[ci_time_alloc_tot]))			// get the allocated total count
			
			var res =  divide(dur, act) / 60
			return res
			// act_tot_dur 
			// act_tot_count --> ci_time_alloc_tot
			```
		description: "Purpose: Compute the measure result from the DAX expression and current filter context.\nCalculation Logic: VAR blocks define intermediate values (dur, act, res) used later in the expression. Dependencies: Columns: users_history[ci_time_alloc_tot], users_history[ci_time_alloc_tot_dur].\nDynamic Behavior: Uses CALCULATE/CALCULATETABLE to modify filter context with its filter arguments.\nFormat/Type: ###  min"
		formatString: ###  min
		displayFolder: _users_history_analysis
		lineageTag: 6a291487-586f-4a27-872b-622feaa62c57

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.users_history_duration_adjusted_hrs' =
		description: "Purpose: Compute the measure result from the DAX expression and current filter context.\nCalculation Logic: No VAR blocks. Dependencies: No explicit column or measure references detected..\nDynamic Behavior: No explicit conditional branching detected.\nFormat/Type: ###,###,###  hrs"
			
			var dur = CALCULATE(sum(users_history[ci_time_alloc_tot_dur]))
			var prep = CALCULATE(average(users_history[ci_time_alloc_prep_adjustment]))
			var capture_level = CALCULATE(average(users_history[ci_time_alloc_act_capt_lvl_adjustment]))
			var res =  dur *  prep * capture_level / 3600
			return res
			
			//act_tot_dur -- > ci_time_alloc_tot_dur
		formatString: ###,###,###  hrs
		displayFolder: _users_history_analysis
		lineageTag: e3babb0b-a347-4944-8356-1f921b214979

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.rep_count_avg' = ```
			
			var periods_tbl = SUMMARIZE(calculatetable(users_history), users_history[_sys_user_id], users_history[_sys_filt_start_date]) // get the total number of periods in the selection group by rep and month
			var reps_tbl = SUMMARIZE(calculatetable(users_history), users_history[_sys_user_id]) // get just the unique reps
			var periods =  divide(COUNTROWS(periods_tbl) , COUNTROWS( reps_tbl)) 
			var reps =  divide(COUNTROWS(periods_tbl) , periods) // get the avg number of "active" reps per period
			return  reps
			```
		description: "Purpose: Compute the measure result from the DAX expression and current filter context.\nCalculation Logic: VAR blocks define intermediate values (periods_tbl, reps_tbl, periods, reps) used later in the expression. Dependencies: Columns: users_history[_sys_filt_start_date], users_history[_sys_user_id].\nDynamic Behavior: No explicit conditional branching detected.\nFormat/Type: 0.0"
		formatString: 0.0
		displayFolder: _users_history_analysis
		lineageTag: ecb23497-da79-4ea3-89dd-235cfeda7437

		changedProperty = FormatString

	/// The ID of the document in the remote system (such as Salesforce ID)
	column _sys_user_id
		dataType: string
		lineageTag: c16b37d5-fde5-4ff3-9836-e2cd50095d15
		summarizeBy: none
		sourceColumn: _sys_user_id

		annotation SummarizationSetBy = Automatic

	/// Average quarterly sum of the booking amounts of opportunities won by the user's peers in the period
	column ci_perf_qtly_avg_bookings_peers
		dataType: string
		lineageTag: cbb4d31c-6672-4a28-b2cd-8ffa4f61deda
		summarizeBy: none
		sourceColumn: ci_perf_qtly_avg_bookings_peers

		annotation SummarizationSetBy = Automatic

	/// Average quarterly sum of the booking amounts of opportunities created by the user's peers in the period
	column ci_perf_qtly_avg_pipeline_peers
		dataType: string
		lineageTag: 918e2bcd-8e04-4025-aee5-a8ad560362bb
		summarizeBy: none
		sourceColumn: ci_perf_qtly_avg_pipeline_peers

		annotation SummarizationSetBy = Automatic

	/// Quarterly sum of the booking amounts of opportunities won by the user in the period
	column ci_perf_qtly_bookings_user
		dataType: string
		lineageTag: 689cabe3-699c-4a41-beab-98b1e73b1514
		summarizeBy: none
		sourceColumn: ci_perf_qtly_bookings_user

		annotation SummarizationSetBy = Automatic

	/// Quarterly sum of the booking amounts of opportunities created by the user in the period
	column ci_perf_qtly_pipeline_user
		dataType: string
		lineageTag: c4085f53-2e95-42b3-b010-266e16555d36
		summarizeBy: none
		sourceColumn: ci_perf_qtly_pipeline_user

		annotation SummarizationSetBy = Automatic

	/// User's ramping status indicating whether the user's tenure is lower than 6 months
	column ci_perf_ramping_status
		dataType: string
		lineageTag: 91f47d93-351f-450c-bb4f-38b70eaf39b6
		summarizeBy: none
		sourceColumn: ci_perf_ramping_status

		annotation SummarizationSetBy = Automatic

	/// The Cien company ID
	column _sys_co_id
		dataType: string
		lineageTag: 314eac44-5973-4ca3-a4f7-d380a0cc9d57
		summarizeBy: none
		sourceColumn: _sys_co_id

		annotation SummarizationSetBy = Automatic

	/// Unique record identifier, based on the ID of the document in the remote system (such as Salesforce ID) and date
	column _sys_doc_id
		dataType: string
		lineageTag: 5722934e-452b-460b-b415-69b57f6c6d16
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	/// The last date of the month that the record applies to (for past months) or the last date of aggregated data (for the present month), stripped of time
	column _sys_filt_end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: ef6830d5-15fe-4f06-a179-e6038249a3a2
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 018e1ada-7d5d-4184-aadc-5c3df98d9eda
			defaultHierarchy: LocalDateTable_60e552db-bfc5-4819-b0b1-e522c77b3586.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The first date of the month that the records applies to, stripped of time
	column _sys_filt_start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4118bcbe-2f3b-4563-b9e6-00051b6a9810
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// User's act_capture_level score in the period
	column ci_act_capt_lvl
		dataType: double
		lineageTag: f85460a5-ae84-498c-abc7-d9834a2b3fa2
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's act_capture_level score confidence in the period
	column ci_act_capt_lvl_conf
		dataType: double
		lineageTag: ef7ef305-4422-44ad-8538-e4245a1cfac0
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of owner activities performed on new logo selling steps that completed in the period
	column ci_act_capt_lvl_pi_new_logo_owner_act
		dataType: int64
		formatString: 0
		lineageTag: 62f96d6d-3c80-4bf6-84d1-c6b6c6bbff13
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_new_logo_owner_act

		annotation SummarizationSetBy = Automatic

	/// Duration of activities performed on new logo selling steps that completed in the period
	column ci_act_capt_lvl_pi_new_logo_owner_dur
		dataType: double
		lineageTag: d284c5a2-3759-4ba5-a202-04638e1eeac6
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_new_logo_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of new logo selling steps that completed in the period
	column ci_act_capt_lvl_pi_new_logo_steps
		dataType: int64
		formatString: 0
		lineageTag: 63a74506-5225-45d1-9689-d0e01e2467f7
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_new_logo_steps

		annotation SummarizationSetBy = Automatic

	/// Expected duration of activities performed on post-sales support steps that completed in the period
	column ci_act_capt_lvl_pi_post_sales_expect_owner_dur
		dataType: double
		lineageTag: 611cef01-95df-4082-af53-657eca34248f
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_post_sales_expect_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of owner activities performed on post-sales support steps that completed in the period
	column ci_act_capt_lvl_pi_post_sales_owner_act
		dataType: int64
		formatString: 0
		lineageTag: d843b7e1-eb32-4c91-8f6d-e6989601c14e
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_post_sales_owner_act

		annotation SummarizationSetBy = Automatic

	/// Duration of activities performed on post-sales support steps that completed in the period
	column ci_act_capt_lvl_pi_post_sales_owner_dur
		dataType: double
		lineageTag: 6a4c9c69-ffaa-4eb2-a936-b912d34550b4
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_post_sales_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of post-sales support steps that completed in the period
	column ci_act_capt_lvl_pi_post_sales_steps
		dataType: int64
		formatString: 0
		lineageTag: 0d05b8bf-d362-4afc-b059-c9c60a4a342b
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_post_sales_steps

		annotation SummarizationSetBy = Automatic

	/// Expected duration of activities performed on prospecting steps that completed in the period
	column ci_act_capt_lvl_pi_prospecting_expect_owner_dur
		dataType: double
		lineageTag: f8c7585b-9a70-4a0f-9940-904e86daeb89
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_prospecting_expect_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of owner activities performed on prospecting steps that completed in the period
	column ci_act_capt_lvl_pi_prospecting_owner_act
		dataType: int64
		formatString: 0
		lineageTag: 3caaadcb-2e43-4e5b-80d2-883e04787a6e
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_prospecting_owner_act

		annotation SummarizationSetBy = Automatic

	/// Duration of activities performed on prospecting steps that completed in the period
	column ci_act_capt_lvl_pi_prospecting_owner_dur
		dataType: double
		lineageTag: c572a7dd-f7d4-4329-bbb5-229da2b6e38d
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_prospecting_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of prospecting steps that completed in the period
	column ci_act_capt_lvl_pi_prospecting_steps
		dataType: int64
		formatString: 0
		lineageTag: 5c3817c5-7752-40ce-a7d6-d362f6945d6c
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_prospecting_steps

		annotation SummarizationSetBy = Automatic

	/// User's timeliness score in the period
	column ci_act_capt_lvl_pi_timeliness
		dataType: double
		lineageTag: 08d849af-e37f-4d35-92b7-d95bf93c2d0c
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_timeliness

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// act_capture_level adjustment factor to account for the user's act_capture_level score
	column ci_time_alloc_act_capt_lvl_adjustment
		dataType: double
		lineageTag: 65e00ff5-00de-4015-8943-42912fa1b72e
		summarizeBy: sum
		sourceColumn: ci_time_alloc_act_capt_lvl_adjustment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's time allocation values confidence in the period
	column ci_time_alloc_conf
		dataType: double
		lineageTag: dae890b6-ff9d-4907-a160-cb042c5e3388
		summarizeBy: sum
		sourceColumn: ci_time_alloc_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on internal activities in the period
	column ci_time_alloc_internal
		dataType: double
		lineageTag: d3c4a321-0d49-4805-84b7-cf5ec3607084
		summarizeBy: sum
		sourceColumn: ci_time_alloc_internal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged internal activities in the period
	column ci_time_alloc_internal_eng
		dataType: double
		lineageTag: 7c98cd0a-31d5-4a2c-9190-1777a772ba48
		summarizeBy: sum
		sourceColumn: ci_time_alloc_internal_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Week adjustment factor to convert monthly to weekly
	column ci_time_alloc_month_to_week_adjustment
		dataType: double
		lineageTag: aa3affb4-1ad9-4307-b695-a80dfd7a1bac
		summarizeBy: sum
		sourceColumn: ci_time_alloc_month_to_week_adjustment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on new logo selling activities in the period
	column ci_time_alloc_new_logo
		dataType: double
		lineageTag: bcc46bf6-70d9-4b72-83c4-07378be563bf
		summarizeBy: sum
		sourceColumn: ci_time_alloc_new_logo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged new logo selling activities in the period
	column ci_time_alloc_new_logo_eng
		dataType: double
		lineageTag: 4e26dbcb-710e-41d6-9233-de9bc04dc851
		summarizeBy: sum
		sourceColumn: ci_time_alloc_new_logo_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on post-sales support activities in the period
	column ci_time_alloc_post_sales
		dataType: double
		lineageTag: 4aef1953-b88b-4934-8ef3-87956771e0e4
		summarizeBy: sum
		sourceColumn: ci_time_alloc_post_sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged post-sales support activities in the period
	column ci_time_alloc_post_sales_eng
		dataType: double
		lineageTag: e9bb5836-1c9d-4773-9bd9-6505c879cd9d
		summarizeBy: sum
		sourceColumn: ci_time_alloc_post_sales_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Prep adjustment factor to account for the preparation time needed apart from sales related activities
	column ci_time_alloc_prep_adjustment
		dataType: double
		lineageTag: 4c6b0b75-d305-41f5-ac2c-a67de391db81
		summarizeBy: sum
		sourceColumn: ci_time_alloc_prep_adjustment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on prospecting activities in the period
	column ci_time_alloc_prospecting
		dataType: double
		lineageTag: 6158c6f7-b5da-45ba-bf48-519c55decdbd
		summarizeBy: sum
		sourceColumn: ci_time_alloc_prospecting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged prospecting activities in the period
	column ci_time_alloc_prospecting_eng
		dataType: double
		lineageTag: 00d79857-d85e-4fff-9adb-b0c204a2be1a
		summarizeBy: sum
		sourceColumn: ci_time_alloc_prospecting_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on activities in the period
	column ci_time_alloc_tot
		dataType: double
		lineageTag: 626b5240-7fda-49e8-b3ee-d8b59a6e9a6e
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Duration of the activities the user performed in the period
	column ci_time_alloc_tot_dur
		dataType: double
		lineageTag: 9e665165-5a8a-4d72-9802-1cca4c3ea94e
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged activities in the period
	column ci_time_alloc_tot_eng
		dataType: double
		lineageTag: f90a4921-9c10-460a-b6e2-d360fb872bd1
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Duration of the engaged activities the user performed in the period
	column ci_time_alloc_tot_eng_dur
		dataType: double
		lineageTag: e2168d2d-5e39-4206-bb14-b94f36471aca
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on sales related activities in the period
	column ci_time_alloc_tot_selling
		dataType: double
		lineageTag: b1270359-5b0f-4d7b-b9e8-54a6342e1f96
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_selling

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged sales related activities in the period
	column ci_time_alloc_tot_selling_eng
		dataType: double
		lineageTag: 4fe3ab45-58d7-4e02-96d8-144e6bcc28a1
		summarizeBy: sum
		sourceColumn: ci_time_alloc_tot_selling_eng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's last login time in the CRM
	column crm_last_login_time
		dataType: string
		lineageTag: b7c0e460-951b-4ace-9267-e49e8eafb853
		summarizeBy: none
		sourceColumn: crm_last_login_time

		annotation SummarizationSetBy = Automatic

	/// User's group
	column trueai_group
		dataType: string
		lineageTag: 847c70c5-0216-49f4-aa55-246d9339e902
		summarizeBy: none
		sourceColumn: trueai_group

		annotation SummarizationSetBy = Automatic

	/// User's hire date
	column trueai_hire_date
		dataType: string
		lineageTag: 6e02a613-1804-4335-8f58-45a5d66d1fc3
		summarizeBy: none
		sourceColumn: trueai_hire_date

		annotation SummarizationSetBy = Automatic

	/// Number of months since the user's hire date
	column trueai_tenure
		dataType: string
		lineageTag: 6214be4b-0508-4fe6-b8c7-8eb00382499c
		summarizeBy: none
		sourceColumn: trueai_tenure

		annotation SummarizationSetBy = Automatic

	/// User's termination date
	column trueai_termination_date
		dataType: string
		lineageTag: 592e7254-d423-42ed-b9e8-29720d48f4d2
		summarizeBy: none
		sourceColumn: trueai_termination_date

		annotation SummarizationSetBy = Automatic

	/// User's standardized and combined role
	column trueai_user_role
		dataType: string
		lineageTag: 9736a032-8ebd-448f-8c36-5bf93a1fa193
		summarizeBy: none
		sourceColumn: trueai_user_role

		annotation SummarizationSetBy = Automatic

	/// User's function derived from the standardized and combined role
	column trueai_user_role_function
		dataType: string
		lineageTag: e3fbd7af-798b-475a-8909-223141fdc45d
		summarizeBy: none
		sourceColumn: trueai_user_role_function

		annotation SummarizationSetBy = Automatic

	/// Column 'col.full_name' = ```.
	column 'col.full_name' = ```
			
			var temp = If(ISBLANK(users_history[trueai_last_name]), users_history[crm_username], users_history[crm_first_name] &  " " &  users_history[crm_last_name])
			var res = If(ISBLANK(temp) , users_history[_sys_user_id], temp)
			return res 
			
			```
		lineageTag: 45671f7c-293b-4df2-ab8e-79285fe5231c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// User's performance tier expressed as "underperformer", "overperformer" or "performer", based on their quarterly sum of booking amounts of won opportunities compared to their peers
	column ci_perf_qtly_performance_tier
		dataType: string
		lineageTag: 63ba2ab9-0367-4d27-9527-863d1250bb7e
		summarizeBy: none
		sourceColumn: ci_perf_qtly_performance_tier

		annotation SummarizationSetBy = Automatic

	/// User's performance tier expressed as an integer from 1 to 3, based on their quarterly sum of booking amounts of won opportunities compared to their peers
	column ci_perf_qtly_performance_tier_num
		dataType: string
		lineageTag: 95ec2f1a-938c-41b4-aa64-57ebd4003955
		summarizeBy: none
		sourceColumn: ci_perf_qtly_performance_tier_num

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_closing_ability_actual_vs_predicted
		dataType: string
		lineageTag: 4be74fbc-1749-4a1a-affb-c79660476274
		summarizeBy: none
		sourceColumn: ci_sb_closing_ability_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_closing_ability_conf
		dataType: string
		lineageTag: 75f56955-b52d-4789-b4d8-6e0df619d73a
		summarizeBy: none
		sourceColumn: ci_sb_closing_ability_conf

		annotation SummarizationSetBy = Automatic

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_closing_ability_peer_actual_vs_predicted
		dataType: string
		lineageTag: 17b58608-52af-4d3f-80d9-6b6593e89d63
		summarizeBy: none
		sourceColumn: ci_sb_closing_ability_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_discov_skills_actual_vs_predicted
		dataType: string
		lineageTag: ab4ad593-f47d-4464-9c5c-b6cecdb602ed
		summarizeBy: none
		sourceColumn: ci_sb_discov_skills_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_discov_skills_conf
		dataType: string
		lineageTag: 92d686ea-def1-4f18-8654-a98c90130706
		summarizeBy: none
		sourceColumn: ci_sb_discov_skills_conf

		annotation SummarizationSetBy = Automatic

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_discov_skills_peer_actual_vs_predicted
		dataType: string
		lineageTag: 7646f421-93a7-4a2d-90ee-a2caad6ac637
		summarizeBy: none
		sourceColumn: ci_sb_discov_skills_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_max
		dataType: string
		lineageTag: 16d16c30-62b9-4fb3-b79d-a9c882ae471d
		summarizeBy: none
		sourceColumn: ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_min
		dataType: string
		lineageTag: cf04174f-6343-4fc7-8363-ae35fc9ba78c
		summarizeBy: none
		sourceColumn: ci_sb_closing_ability_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_deal_maxing_conf
		dataType: string
		lineageTag: 5bbf1d8c-2ad3-42b0-ae5a-df573ab2dd49
		summarizeBy: none
		sourceColumn: ci_sb_deal_maxing_conf

		annotation SummarizationSetBy = Automatic

	/// Deal maximizing final score as compared to peers.
	column ci_sb_deal_maxing_num
		dataType: string
		lineageTag: de73914b-486f-48f7-816b-2e88ed422549
		summarizeBy: none
		sourceColumn: ci_sb_deal_maxing_num

		annotation SummarizationSetBy = Automatic

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_engmt_ability_conf
		dataType: string
		lineageTag: e671de42-8ff0-4695-aca8-0d66fb2b2189
		summarizeBy: none
		sourceColumn: ci_sb_engmt_ability_conf

		annotation SummarizationSetBy = Automatic

	/// Engagement ability final score as compared to peers.
	column ci_sb_engmt_ability_num
		dataType: string
		lineageTag: 2920261b-f644-4deb-a64b-7aa0b4aff223
		summarizeBy: none
		sourceColumn: ci_sb_engmt_ability_num

		annotation SummarizationSetBy = Automatic

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_work_effort_conf
		dataType: string
		lineageTag: c87f8857-291d-4af3-be73-91cfe2c9c1f9
		summarizeBy: none
		sourceColumn: ci_sb_work_effort_conf

		annotation SummarizationSetBy = Automatic

	/// Work effort final score as compared to peers.
	column ci_sb_work_effort_num
		dataType: string
		lineageTag: ec66a13f-d77d-4121-9cff-c544cbf2e762
		summarizeBy: none
		sourceColumn: ci_sb_work_effort_num

		annotation SummarizationSetBy = Automatic

	/// The date of the last data request from the platform in UTC
	column trueai_end_date
		dataType: string
		lineageTag: ed8fc91a-5470-4860-8bef-b20ea005f0c0
		summarizeBy: none
		sourceColumn: trueai_end_date

		annotation SummarizationSetBy = Automatic

	/// The last date of the month that the record applies to (for past months) or the last date of aggregated data (for the present month)
	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: c10eb0a3-cb38-4e76-b8b6-a9f3965e55fb
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: b3c72d8f-529b-4009-b537-d279c3fdf6c6
			defaultHierarchy: LocalDateTable_b49010bd-82d9-4a61-8169-e4a8a1a6fc33.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the record was set to inactive in the remote system
	column _sys_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 28400eeb-59e1-4038-90e8-72ad6dca1bde
		summarizeBy: none
		sourceColumn: _sys_is_active

		annotation SummarizationSetBy = Automatic

	/// Boolean flag that indicates whether the record was set to deleted in the remote system
	column _sys_is_deleted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e03acb85-00cd-4496-a050-983ef37ba109
		summarizeBy: none
		sourceColumn: _sys_is_deleted

		annotation SummarizationSetBy = Automatic

	/// Expected duration of activities performed on new logo selling steps that completed in the period
	column ci_act_capt_lvl_pi_new_logo_expected_owner_dur
		dataType: double
		lineageTag: f4abd9f2-b8ab-4335-9582-ecba18cbf9bf
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_new_logo_expected_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// User's creation date in the CRM
	column crm_created_on
		dataType: string
		lineageTag: d5bb34ba-d8bd-4ab9-96f9-b09d97df284c
		summarizeBy: none
		sourceColumn: crm_created_on

		annotation SummarizationSetBy = Automatic

	/// Column 'col.act_monthly_count' =.
	column 'col.act_monthly_count' =
			
			//look up the counts from the users activities table so they can be used in aggs on user history
			var userId = users_history[_sys_user_id]  // grab the user id
			var startDate = users_history[_sys_filt_start_date]  // grab start/ end date of the period (1 month)
			var endDate = users_history[_sys_filt_end_date]
			 // sum hte accoutivity count for the period and the user
			var res = CALCULATE(
			        SUM(users_activities[trueai_count]),
			        FILTER(
			            ALL(users_activities),
			            users_activities[_sys_user_id] = userId
			            && users_activities[_sys_filt_start_date] >= startDate
			            && users_activities[_sys_filt_end_date] <= endDate
			        )
			    )
			return res
		formatString: 0
		lineageTag: f9302854-73ae-4912-9ea9-95d45fad3baa
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Column 'col.act_monthly_duration' =.
	column 'col.act_monthly_duration' =
			
			//look up the counts from the users activities table so they can be used in aggs on user history
			var userId = users_history[_sys_user_id]  // grab the user id
			var startDate = users_history[_sys_filt_start_date]  // grab start/ end date of the period (1 month)
			var endDate = users_history[_sys_filt_end_date]
			 // sum hte accoutivity count for the period and the user
			var res = CALCULATE(
			        SUM(users_activities[trueai_dur]),
			        FILTER(
			            ALL(users_activities),
			            users_activities[_sys_user_id] = userId
			            && users_activities[_sys_filt_start_date] >= startDate
			            && users_activities[_sys_filt_end_date] <= endDate
			        )
			    )
			return res
		formatString: 0
		lineageTag: dbb6d065-31a0-483b-830a-77636d6f036c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Expected duration of activities performed on existing customer selling steps that completed in the period
	column ci_act_capt_lvl_pi_exist_cust_expect_owner_dur
		dataType: double
		lineageTag: 1838d7d9-1713-47c2-a08b-11c7c1f763d4
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_exist_cust_expect_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of owner activities performed on existing customer selling steps that completed in the period
	column ci_act_capt_lvl_pi_exist_cust_owner_act
		dataType: int64
		formatString: 0
		lineageTag: 7abdbeec-9e9d-4f47-adfd-70a9fd23fef4
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_exist_cust_owner_act

		annotation SummarizationSetBy = Automatic

	/// Duration of activities performed on existing customer selling steps that completed in the period
	column ci_act_capt_lvl_pi_exist_cust_owner_dur
		dataType: double
		lineageTag: 597fa759-7b62-430c-a538-d50ff6943f38
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_exist_cust_owner_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of existing customer selling steps that completed in the period
	column ci_act_capt_lvl_pi_exist_cust_steps
		dataType: int64
		formatString: 0
		lineageTag: c9ebd80b-ae60-4a74-bd3f-64bcc3a1a85c
		summarizeBy: sum
		sourceColumn: ci_act_capt_lvl_pi_exist_cust_steps

		annotation SummarizationSetBy = Automatic

	/// Average number of weekly hours the user spent on existing customer selling activities in the period
	column ci_time_alloc_existing_customer_selling
		dataType: double
		lineageTag: 32909a2e-4903-4c9c-a8a8-989775fff42f
		summarizeBy: sum
		sourceColumn: ci_time_alloc_existing_customer_selling

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average number of weekly hours the user spent on engaged existing customer selling activities in the period
	column ci_time_alloc_existing_customer_selling_eng
		dataType: string
		lineageTag: 82e0f432-d2f4-461b-8aa8-0e64b1f0fed5
		summarizeBy: none
		sourceColumn: ci_time_alloc_existing_customer_selling_eng

		annotation SummarizationSetBy = Automatic

	/// User's standardized and combined role aliased
	column trueai_user_role_alias
		dataType: string
		lineageTag: ba104943-7317-45d8-a647-eec85ebd3112
		summarizeBy: none
		sourceColumn: trueai_user_role_alias

		annotation SummarizationSetBy = Automatic

	/// User's performance tier confidence
	column ci_perf_qtly_performance_tier_conf
		dataType: string
		lineageTag: d635a3ce-02be-4270-a064-24e7daee3f02
		summarizeBy: none
		sourceColumn: ci_perf_qtly_performance_tier_conf

		annotation SummarizationSetBy = Automatic

	/// Number of peers the user was compared to when determining the performance tier
	column ci_perf_qtly_performance_peer_count
		dataType: string
		lineageTag: 1245fa9e-bacd-455e-85b5-a8b80e403a84
		summarizeBy: none
		sourceColumn: ci_perf_qtly_performance_peer_count

		annotation SummarizationSetBy = Automatic

	/// Potential number of hours a user can put in during a given month
	column ci_time_alloc_potential
		dataType: double
		lineageTag: fa905145-5e97-481e-8e5d-d8db51ef5eed
		summarizeBy: sum
		sourceColumn: ci_time_alloc_potential

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Closing ability final score tier as compared to peers.
	column ci_sb_closing_ability_tier
		dataType: string
		lineageTag: dc9533f9-6ed2-44fa-9324-c776b46d0a8c
		summarizeBy: none
		sourceColumn: ci_sb_closing_ability_tier

		annotation SummarizationSetBy = Automatic

	/// Closing ability final score as compared to peers.
	column ci_sb_closing_ability_num
		dataType: string
		lineageTag: b9193620-401e-4524-94cd-c5407938eb3f
		summarizeBy: none
		sourceColumn: ci_sb_closing_ability_num

		annotation SummarizationSetBy = Automatic

	/// Discovery skills final score tier as compared to peers.
	column ci_sb_discov_skills_tier
		dataType: string
		lineageTag: 6a07644f-7004-4620-adb6-ebaeaca190b7
		summarizeBy: none
		sourceColumn: ci_sb_discov_skills_tier

		annotation SummarizationSetBy = Automatic

	/// Discovery skills final score as compared to peers.
	column ci_sb_discov_skills_num
		dataType: string
		lineageTag: ce68a793-14f3-41f1-81d2-4aaafdf6c9e6
		summarizeBy: none
		sourceColumn: ci_sb_discov_skills_num

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_max
		dataType: string
		lineageTag: 93bc3d33-940d-45ed-b9a4-0849d61943e0
		summarizeBy: none
		sourceColumn: ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_min
		dataType: string
		lineageTag: ef6bdd2e-4c58-49dc-9900-bc2adcde6723
		summarizeBy: none
		sourceColumn: ci_sb_discov_skills_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

	/// Engagement ability final score tier as compared to peers.
	column ci_sb_engmt_ability_tier
		dataType: string
		lineageTag: 21b07de4-83f7-417f-8b3c-b5fa1b600f7e
		summarizeBy: none
		sourceColumn: ci_sb_engmt_ability_tier

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_engmt_ability_actual_vs_predicted
		dataType: string
		lineageTag: 7eeeb462-65bf-4577-8b36-10e94d667d74
		summarizeBy: none
		sourceColumn: ci_sb_engmt_ability_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_max
		dataType: string
		lineageTag: e724708a-8d09-45fd-a236-dae8883e53b8
		summarizeBy: none
		sourceColumn: ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_min
		dataType: string
		lineageTag: 110183ad-e9d5-4b78-bb6a-b070e65023ae
		summarizeBy: none
		sourceColumn: ci_sb_engmt_ability_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_engmt_ability_peer_actual_vs_predicted
		dataType: string
		lineageTag: f7058cad-8cc9-4f41-ad89-e621fb459b20
		summarizeBy: none
		sourceColumn: ci_sb_engmt_ability_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Deal maximizing final score tier as compared to peers.
	column ci_sb_deal_maxing_tier
		dataType: string
		lineageTag: d7485c8e-bf3f-4b4e-b86b-f06ac2a9fe37
		summarizeBy: none
		sourceColumn: ci_sb_deal_maxing_tier

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_deal_maxing_actual_vs_predicted
		dataType: string
		lineageTag: a069c900-f270-441c-a0e2-5a53148e83fa
		summarizeBy: none
		sourceColumn: ci_sb_deal_maxing_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_max
		dataType: string
		lineageTag: 8b4379c4-d414-4a16-82b9-b99360a9c925
		summarizeBy: none
		sourceColumn: ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_min
		dataType: string
		lineageTag: 93cead05-07ef-4244-87ea-cdd3cd6f157a
		summarizeBy: none
		sourceColumn: ci_sb_deal_maxing_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_deal_maxing_peer_actual_vs_predicted
		dataType: string
		lineageTag: 9d81916d-42dc-4552-9f74-99168b098b00
		summarizeBy: none
		sourceColumn: ci_sb_deal_maxing_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Work effort final score tier as compared to peers.
	column ci_sb_work_effort_tier
		dataType: string
		lineageTag: 0829a21a-2791-41f8-ab5b-14898a0a8452
		summarizeBy: none
		sourceColumn: ci_sb_work_effort_tier

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_work_effort_actual_vs_predicted
		dataType: string
		lineageTag: 78edf241-7623-4f58-ad3c-37d83e40f7b1
		summarizeBy: none
		sourceColumn: ci_sb_work_effort_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_max
		dataType: string
		lineageTag: 409f5d8c-d7c9-4a8b-b448-a3513994e197
		summarizeBy: none
		sourceColumn: ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_min
		dataType: string
		lineageTag: cbd9f008-dfc4-4437-bd1e-26905b62c520
		summarizeBy: none
		sourceColumn: ci_sb_work_effort_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_work_effort_peer_actual_vs_predicted
		dataType: string
		lineageTag: 56b09175-6f6c-4625-b624-47b47b58e21c
		summarizeBy: none
		sourceColumn: ci_sb_work_effort_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Time management final score tier as compared to peers.
	column ci_sb_time_management_tier
		dataType: string
		lineageTag: 80e74577-b71d-41fe-b459-3a69e212d567
		summarizeBy: none
		sourceColumn: ci_sb_time_management_tier

		annotation SummarizationSetBy = Automatic

	/// Time management final score as compared to peers.
	column ci_sb_time_management_num
		dataType: string
		lineageTag: ae748c1b-456b-483f-8e3c-872d627e68c5
		summarizeBy: none
		sourceColumn: ci_sb_time_management_num

		annotation SummarizationSetBy = Automatic

	/// The confidence value based on the number of actual samples vs. number of expected samples, adjusted with an exponent factor.
	column ci_sb_time_management_conf
		dataType: string
		lineageTag: 2ffa2ae3-c403-43b1-aab3-921bbdd68ba1
		summarizeBy: none
		sourceColumn: ci_sb_time_management_conf

		annotation SummarizationSetBy = Automatic

	/// The ratio between actual and expected success rate. Over 1 indicates an overperformance, lower than 1 indicates underperformance.
	column ci_sb_time_management_actual_vs_predicted
		dataType: string
		lineageTag: e1ec761e-9045-4f31-be33-277444007c0f
		summarizeBy: none
		sourceColumn: ci_sb_time_management_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations above the mean of the average vs expected success rate of the peer group.
	column ci_sb_time_management_peer_actual_vs_pred_ratio_derived_max
		dataType: string
		lineageTag: e209cfd6-eac2-4090-838d-71e353d3dea1
		summarizeBy: none
		sourceColumn: ci_sb_time_management_peer_actual_vs_pred_ratio_derived_max

		annotation SummarizationSetBy = Automatic

	/// Two standard deviations below the mean of the average vs expected success rate of the peer group.
	column ci_sb_time_management_peer_actual_vs_pred_ratio_derived_min
		dataType: string
		lineageTag: a42d07a0-6cd6-4588-960e-e1cd29bd2744
		summarizeBy: none
		sourceColumn: ci_sb_time_management_peer_actual_vs_pred_ratio_derived_min

		annotation SummarizationSetBy = Automatic

	/// Mean of the average vs expected success rate of the peer group.
	column ci_sb_time_management_peer_actual_vs_predicted
		dataType: string
		lineageTag: f44df4c5-ff6c-427f-9068-648590a1266d
		summarizeBy: none
		sourceColumn: ci_sb_time_management_peer_actual_vs_predicted

		annotation SummarizationSetBy = Automatic

	/// User's department derived from the standardized and combined role
	column trueai_user_role_department
		dataType: string
		lineageTag: 30a6f02b-1dba-482f-bde9-3654a001f313
		summarizeBy: none
		sourceColumn: trueai_user_role_department

		annotation SummarizationSetBy = Automatic

	partition users_history-ed435d05-4999-4c6f-9051-d88bab5a91ed = m
		mode: import
		source = ```
				let
				  
				  dbTable = getDBTable("users_history"), // get the right table
				
				
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{ // change types to what we're expecting
				 {"_sys_as_of", type datetime},
				    {"_sys_co_id", type text},
				    {"_sys_doc_id", type text},
				    {"_sys_filt_end_date", type date},
				    {"_sys_filt_start_date", type date},
				    {"_sys_is_active", type logical},
				    {"_sys_is_deleted", type logical},
				    {"_sys_user_id", type text},
				
				    {"ci_act_capt_lvl", type number},
				    {"ci_act_capt_lvl_conf", type number},
				
				    // Existing Customer Selling (base only)
				    {"ci_act_capt_lvl_pi_exist_cust_expect_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_exist_cust_owner_act", Int64.Type},
				    {"ci_act_capt_lvl_pi_exist_cust_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_exist_cust_steps", Int64.Type},
				
				    // New Logo (base only)
				    {"ci_act_capt_lvl_pi_new_logo_expected_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_new_logo_owner_act", Int64.Type},
				    {"ci_act_capt_lvl_pi_new_logo_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_new_logo_steps", Int64.Type},
				
				    // Post-Sales (base only)
				    {"ci_act_capt_lvl_pi_post_sales_expect_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_post_sales_owner_act", Int64.Type},
				    {"ci_act_capt_lvl_pi_post_sales_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_post_sales_steps", Int64.Type},
				
				    // Prospecting (base only)
				    {"ci_act_capt_lvl_pi_prospecting_expect_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_prospecting_owner_act", Int64.Type},
				    {"ci_act_capt_lvl_pi_prospecting_owner_dur", type number},
				    {"ci_act_capt_lvl_pi_prospecting_steps", Int64.Type},
				
				    {"ci_act_capt_lvl_pi_timeliness", type number},
				
				    // Time allocation (keeping only those NOT excluded)
				    {"ci_time_alloc_act_capt_lvl_adjustment", type number},
				    {"ci_time_alloc_conf", type number},
				    {"ci_time_alloc_existing_customer_selling", type number},
				    {"ci_time_alloc_internal", type number},
				    {"ci_time_alloc_internal_eng", type number},
				    {"ci_time_alloc_month_to_week_adjustment", type number},
				    {"ci_time_alloc_new_logo", type number},
				    {"ci_time_alloc_new_logo_eng", type number},
				    {"ci_time_alloc_post_sales", type number},
				    {"ci_time_alloc_post_sales_eng", type number},
				    {"ci_time_alloc_potential", type number},
				    {"ci_time_alloc_prep_adjustment", type number},
				    {"ci_time_alloc_prospecting", type number},
				    {"ci_time_alloc_prospecting_eng", type number},
				    {"ci_time_alloc_tot", type number},
				    {"ci_time_alloc_tot_dur", type number},
				    {"ci_time_alloc_tot_eng", type number},
				    {"ci_time_alloc_tot_eng_dur", type number},
				    {"ci_time_alloc_tot_selling", type number},
				    {"ci_time_alloc_tot_selling_eng", type number}
				
				 
				    })
				in
				    dbTableTyped
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

