EVALUATE
VAR __Result =
    SUMMARIZECOLUMNS(
        'Stakeholder Segments'[Stakeholder Segment Bucket],
        "Present in Won Deals",
            SUM('Stakeholder Segments'[Present in Won Deals])
    )

RETURN
    SELECTCOLUMNS(
        TOPN(
            501,
            __Result,
            [Present in Won Deals], DESC,
            'Stakeholder Segments'[Stakeholder Segment Bucket], ASC
        ),
        "Stakeholder Segment", 'Stakeholder Segments'[Stakeholder Segment Bucket],
        "Present in Won Deals", [Present in Won Deals],
        "v_Present in Won Deals_FormatString", "0.00%"
    )

ORDER BY
    [Present in Won Deals] DESC,
    [Stakeholder Segment] ASC