table aliasing
	lineageTag: 5369c9af-f905-41c3-b40f-56d9d04e79b6

	column alias
		dataType: string
		lineageTag: b72bbab7-8fc7-46a1-a269-087239d21a35
		summarizeBy: none
		sourceColumn: alias

		annotation SummarizationSetBy = Automatic

	column label
		dataType: string
		lineageTag: b93549f0-dd2f-4fe6-8e5b-c636661ded59
		summarizeBy: none
		sourceColumn: label

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 859c91ed-f537-48ef-8ce9-34620c79b42e
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	partition aliasing = m
		mode: import
		source =
				let
				
				
				    dbTable = getDBTable("aliasing"), // get the right table
				
				
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				        {"alias", type text},
				        {"label", type text},
				        {"model", type text}
				    })
				in
				    dbTableTyped

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

