table contacts
	lineageTag: 12d25e83-1771-4b85-8824-18867f8a08d7

	column _sys_as_of
		dataType: dateTime
		formatString: General Date
		lineageTag: 788cba25-0ac4-4cf7-ac60-0dccc7cc90f9
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 748308c8-7bdd-4160-9797-2181716d1010
			defaultHierarchy: LocalDateTable_ca679c41-5719-42ef-b23c-1ba9cbb22dd7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_doc_id
		dataType: string
		lineageTag: 8dc745ec-35f1-420c-807b-f309d56ba26e
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9dbba169-9f24-4273-aad8-e94dbcf0f48d
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 62f5350e-67fa-472c-82f0-5b80c714e312
			defaultHierarchy: LocalDateTable_629aaadb-44ab-4d91-80a2-143a4b2f4dec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1c7ab788-5fdb-4050-98d0-848ffb3da500
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_last_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 440948f9-9467-439c-8c92-24e2323aa7d6
		summarizeBy: none
		sourceColumn: _sys_last_modified_on

		variation Variation
			isDefault
			relationship: 894e38d4-2259-42e2-80a6-9e1d6d58a34a
			defaultHierarchy: LocalDateTable_04dd5e02-996e-48f6-909b-db8015a7ac9e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_ssr_id
		dataType: string
		lineageTag: 4695b4e2-6758-45c3-895e-f2bbf9c30def
		summarizeBy: none
		sourceColumn: _sys_ssr_id

		annotation SummarizationSetBy = Automatic

	column crm_account_id
		dataType: string
		lineageTag: 9242fa91-3ffb-4cc8-ab11-7c83dfc91dfa
		summarizeBy: none
		sourceColumn: crm_account_id

		annotation SummarizationSetBy = Automatic

	column crm_addr_city
		dataType: string
		lineageTag: 5553bdb3-09a3-481d-b5d2-3351fe0ea587
		summarizeBy: none
		sourceColumn: crm_addr_city

		annotation SummarizationSetBy = Automatic

	column crm_addr_country
		dataType: string
		lineageTag: d2fc62d6-2734-4418-8fe5-99d93d588284
		summarizeBy: none
		sourceColumn: crm_addr_country

		annotation SummarizationSetBy = Automatic

	column crm_addr_postal_code
		dataType: string
		lineageTag: 82e76aac-a4ff-4cf7-b1d1-036641eecca3
		summarizeBy: none
		sourceColumn: crm_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column crm_addr_state
		dataType: string
		lineageTag: ad5b20f0-4492-4184-9f05-9461f741ef6f
		summarizeBy: none
		sourceColumn: crm_addr_state

		annotation SummarizationSetBy = Automatic

	column crm_addr_street
		dataType: string
		lineageTag: 9bcbb41f-6cff-4938-8212-c5e96a891353
		summarizeBy: none
		sourceColumn: crm_addr_street

		annotation SummarizationSetBy = Automatic

	column crm_complt
		dataType: double
		lineageTag: 3c9bba0a-8e10-48e5-8138-eb82aa604f9c
		summarizeBy: sum
		sourceColumn: crm_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_contact
		dataType: double
		lineageTag: 3ec0e6e3-c3f8-4935-9978-5feaaf76c9ee
		summarizeBy: sum
		sourceColumn: crm_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_contact_method
		dataType: double
		lineageTag: 7a3de01c-acc4-4e96-b9c4-806071736746
		summarizeBy: sum
		sourceColumn: crm_complt_contact_method

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_geo
		dataType: double
		lineageTag: eb24696b-ee3f-4c09-b783-4135ecb6058a
		summarizeBy: sum
		sourceColumn: crm_complt_geo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_complt_marketing
		dataType: double
		lineageTag: 73341651-8305-4fe6-9a88-9c968b9c4bcd
		summarizeBy: sum
		sourceColumn: crm_complt_marketing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 94895f48-c8d3-4a9c-96f4-5bb18182043d
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: 61b67b9c-7d6d-4ad9-b92a-f4bae15fb5cb
			defaultHierarchy: LocalDateTable_b7f04eb7-8249-435e-9ed0-5444639dd355.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: 6d089c0d-ea68-4183-8636-8c17e21599ff
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_deep_link
		dataType: string
		lineageTag: cab0580c-a500-4e4c-9352-f9bc9737f14c
		summarizeBy: none
		sourceColumn: crm_deep_link

		annotation SummarizationSetBy = Automatic

	column crm_email
		dataType: string
		lineageTag: 02794a10-1498-483d-bb74-5c0f990fbf58
		summarizeBy: none
		sourceColumn: crm_email

		annotation SummarizationSetBy = Automatic

	column crm_first_name
		dataType: string
		lineageTag: 66da5e58-54c3-4d16-a4bc-5da06f3444cc
		summarizeBy: none
		sourceColumn: crm_first_name

		annotation SummarizationSetBy = Automatic

	column crm_last_act_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 612dd363-80b3-4c9c-bcba-0fbaa60f2075
		summarizeBy: none
		sourceColumn: crm_last_act_time

		variation Variation
			isDefault
			relationship: 38a3b099-d6da-4921-aa9d-7659aeab45ca
			defaultHierarchy: LocalDateTable_188faa52-af75-45fa-966c-3435fdb0ce4e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_last_name
		dataType: string
		lineageTag: 3ac24246-2581-4ec7-8880-5c3affcbd1b1
		summarizeBy: none
		sourceColumn: crm_last_name

		annotation SummarizationSetBy = Automatic

	column crm_leadsource
		dataType: string
		lineageTag: 9529adaa-94bc-4917-aa92-c26df61aaa85
		summarizeBy: none
		sourceColumn: crm_leadsource

		annotation SummarizationSetBy = Automatic

	column crm_modified_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 56877b18-b85f-4742-bde4-7334ae583aba
		summarizeBy: none
		sourceColumn: crm_modified_on

		variation Variation
			isDefault
			relationship: b09e0ba9-1d8f-411b-a287-31e900976cfd
			defaultHierarchy: LocalDateTable_c17feb74-44ba-4443-abac-6145592049ec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_owner_id
		dataType: string
		lineageTag: 892a1d5d-129c-4170-aadd-94257c5f2c2d
		summarizeBy: none
		sourceColumn: crm_owner_id

		annotation SummarizationSetBy = Automatic

	column crm_phone
		dataType: string
		lineageTag: be4b4186-d82b-48bf-a2c7-02fd7f27dbb6
		summarizeBy: none
		sourceColumn: crm_phone

		annotation SummarizationSetBy = Automatic

	column crm_salutation
		dataType: string
		lineageTag: a70671e2-cffa-447b-9b17-8a3756882fe0
		summarizeBy: none
		sourceColumn: crm_salutation

		annotation SummarizationSetBy = Automatic

	column crm_title
		dataType: string
		lineageTag: 435291e6-a485-4f36-b4d4-88dfed7452b7
		summarizeBy: none
		sourceColumn: crm_title

		annotation SummarizationSetBy = Automatic

	column trueai_addr_city
		dataType: string
		lineageTag: 8453a7f4-f981-420e-bf99-272e2ce427ce
		summarizeBy: none
		sourceColumn: trueai_addr_city

		annotation SummarizationSetBy = Automatic

	column trueai_addr_country
		dataType: string
		lineageTag: 56c71b06-4258-4f6e-84d6-026c2a829816
		summarizeBy: none
		sourceColumn: trueai_addr_country

		annotation SummarizationSetBy = Automatic

	column trueai_addr_lat
		dataType: double
		lineageTag: e71cbd9c-ec28-4c5f-bb7a-7033bb768ac2
		summarizeBy: sum
		sourceColumn: trueai_addr_lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_long
		dataType: double
		lineageTag: 05fd41a5-e2d6-4274-a7eb-d111a8568010
		summarizeBy: sum
		sourceColumn: trueai_addr_long

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_addr_postal_code
		dataType: string
		lineageTag: a4af9c17-6dfe-4e4b-9f07-cb5c64aaeb34
		summarizeBy: none
		sourceColumn: trueai_addr_postal_code

		annotation SummarizationSetBy = Automatic

	column trueai_addr_rule
		dataType: int64
		formatString: 0
		lineageTag: fde8ff2f-ef99-48ec-b358-af04c8c97a23
		summarizeBy: sum
		sourceColumn: trueai_addr_rule

		annotation SummarizationSetBy = Automatic

	column trueai_addr_state
		dataType: string
		lineageTag: 0e874f9a-0420-4200-af1b-45f2cbc60fa3
		summarizeBy: none
		sourceColumn: trueai_addr_state

		annotation SummarizationSetBy = Automatic

	column trueai_addr_street
		dataType: string
		lineageTag: ee74d8ce-8994-4555-904e-c7a5416c2e8b
		summarizeBy: none
		sourceColumn: trueai_addr_street

		annotation SummarizationSetBy = Automatic

	column trueai_complt
		dataType: double
		lineageTag: ebc8d421-c45a-4790-8b9b-d0c95322fc1c
		summarizeBy: sum
		sourceColumn: trueai_complt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_complt_contact
		dataType: double
		lineageTag: 4aacbe78-ebe4-42c8-884b-5f37b9e8830d
		summarizeBy: sum
		sourceColumn: trueai_complt_contact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_complt_contact_method
		dataType: double
		lineageTag: a01c298a-f352-4da4-b919-e3581aef196d
		summarizeBy: sum
		sourceColumn: trueai_complt_contact_method

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_complt_geo
		dataType: double
		lineageTag: deef5a71-5e1e-4a06-8b08-b36ca0b89a10
		summarizeBy: sum
		sourceColumn: trueai_complt_geo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_complt_marketing
		dataType: double
		lineageTag: a4db6a50-9e45-4b6b-ac37-f2b146920aea
		summarizeBy: sum
		sourceColumn: trueai_complt_marketing

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_created_on
		dataType: dateTime
		formatString: Long Date
		lineageTag: 39d40ae9-0d6a-49fb-bf54-ea810806250f
		summarizeBy: none
		sourceColumn: trueai_created_on

		variation Variation
			isDefault
			relationship: adf0e996-a514-4f86-9cb2-ff1288bf3999
			defaultHierarchy: LocalDateTable_eed38ef4-6d22-4c0e-8c9a-faef030bc4d7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column trueai_creator_id
		dataType: string
		lineageTag: af865ba0-0c9c-4c6b-a142-61ab35b21a34
		summarizeBy: none
		sourceColumn: trueai_creator_id

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource
		dataType: string
		lineageTag: 31fead20-5a51-4ef1-b695-ceccf2eb4004
		summarizeBy: none
		sourceColumn: trueai_leadsource

		annotation SummarizationSetBy = Automatic

	column trueai_leadsource_conf
		dataType: double
		lineageTag: 5fae00e9-b359-49d0-b79b-601b93c8337e
		summarizeBy: sum
		sourceColumn: trueai_leadsource_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_leadsource_rule
		dataType: int64
		formatString: 0
		lineageTag: 77f77f69-d96e-46ac-ae2e-d623fe60a0e5
		summarizeBy: sum
		sourceColumn: trueai_leadsource_rule

		annotation SummarizationSetBy = Automatic

	column trueai_owner_id
		dataType: string
		lineageTag: adb27186-4732-446f-889f-893a7fdb53d2
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	column trueai_title_dept
		dataType: string
		lineageTag: cba3fb66-d83e-4645-ac63-0fe9d6fed0fd
		summarizeBy: none
		sourceColumn: trueai_title_dept

		annotation SummarizationSetBy = Automatic

	column trueai_title_dept_conf
		dataType: double
		lineageTag: 0c9f904c-b2d0-456a-99a8-467ad77527bc
		summarizeBy: sum
		sourceColumn: trueai_title_dept_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_title_seniority
		dataType: string
		lineageTag: 4cc9d84b-5c5f-4546-aec3-d7a04fac9715
		summarizeBy: none
		sourceColumn: trueai_title_seniority

		annotation SummarizationSetBy = Automatic

	column trueai_title_seniority_conf
		dataType: double
		lineageTag: fc94f00a-4745-40fa-b5e8-7ffdd46b5b8b
		summarizeBy: sum
		sourceColumn: trueai_title_seniority_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_test
		dataType: string
		lineageTag: 50117995-c700-4165-88c1-472c67137e0c
		summarizeBy: none
		sourceColumn: trueai_test

		annotation SummarizationSetBy = Automatic

	column trueai_test_conf
		dataType: double
		lineageTag: b722d172-25bf-498e-bc06-bf9441e30962
		summarizeBy: sum
		sourceColumn: trueai_test_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_test_rule
		dataType: string
		lineageTag: c6b3d0a4-4dc8-43ee-bdd3-92147eaf3173
		summarizeBy: none
		sourceColumn: trueai_test_rule

		annotation SummarizationSetBy = Automatic

	column trueai_test_debug
		dataType: string
		lineageTag: 59ba8437-5480-432f-964a-b2de02afb674
		summarizeBy: none
		sourceColumn: trueai_test_debug

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: 7c505489-34c0-4143-af56-a0552aee9f86
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: ed35b37b-f468-4089-a080-64ae3c65f31c
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: c56a413d-3c32-4687-b483-16eae272b332
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: ddff58d5-ed3a-4f57-b289-f3f0ed63e3fd
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: 63657f57-4385-48ce-a29b-148e6d018459
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: double
		lineageTag: 5fab2b26-344f-494e-a5dd-3b0900b3b6c5
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num2
		dataType: double
		lineageTag: 89d44aca-9191-4f70-9c74-588be9f4484f
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num3
		dataType: double
		lineageTag: ceefd9d5-d11c-434a-9671-d03211151340
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num4
		dataType: double
		lineageTag: 0ca09b10-2b13-4925-893c-0bed6b03cb24
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num5
		dataType: double
		lineageTag: cf455820-87c5-44eb-8708-4f5649abe678
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num6
		dataType: double
		lineageTag: 0c463683-2c21-4032-82ad-e06e3b4da903
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num7
		dataType: double
		lineageTag: 63363b93-0a35-44e1-b171-0e1d83003d4a
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ab1cfae8-3b12-4293-a268-7adcd17e2872
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d39b58c7-8887-4845-bae5-90bf8d1185cb
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	partition contacts = m
		mode: import
		source =
				let
				
				  dbTable = getDBTable("contacts"), // get the right table
				  dbTableTyped = Table.TransformColumnTypes(dbTable,{
				{"_sys_as_of", type datetime},
				{"_sys_doc_id", type text},
				{"_sys_filt_end_date", type date},
				{"_sys_filt_start_date", type date},
				{"_sys_last_modified_on", type datetime},
				{"_sys_ssr_id", type text},
				{"crm_account_id", type text},
				{"crm_addr_city", type text},
				{"crm_addr_country", type text},
				{"crm_addr_postal_code", type text},
				{"crm_addr_state", type text},
				{"crm_addr_street", type text},
				{"crm_complt", type number},
				{"crm_complt_contact", type number},
				{"crm_complt_contact_method", type number},
				{"crm_complt_geo", type number},
				{"crm_complt_marketing", type number},
				{"crm_created_on", type datetime},
				{"crm_creator_id", type text},
				{"crm_deep_link", type text},
				{"crm_email", type text},
				{"crm_first_name", type text},
				{"crm_last_act_time", type datetime},
				{"crm_last_name", type text},
				{"crm_leadsource", type text},
				{"crm_modified_on", type datetime},
				{"crm_owner_id", type text},
				{"crm_phone", type text},
				{"crm_salutation", type text},
				{"crm_title", type text},
				{"cust_bool1", type logical},
				{"cust_bool2", type logical},
				{"cust_num1", type number},
				{"cust_num2", type number},
				{"cust_num3", type number},
				{"cust_num4", type number},
				{"cust_num5", type number},
				{"cust_num6", type number},
				{"cust_num7", type number},
				{"cust_text1", type text},
				{"cust_text2", type text},
				{"cust_text3", type text},
				{"cust_text4", type text},
				{"cust_text5", type text},
				{"trueai_addr_city", type text},
				{"trueai_addr_country", type text},
				{"trueai_addr_lat", type number},
				{"trueai_addr_long", type number},
				{"trueai_addr_postal_code", type text},
				{"trueai_addr_rule", Int64.Type},
				{"trueai_addr_state", type text},
				{"trueai_addr_street", type text},
				{"trueai_complt", type number},
				{"trueai_complt_contact", type number},
				{"trueai_complt_contact_method", type number},
				{"trueai_complt_geo", type number},
				{"trueai_complt_marketing", type number},
				{"trueai_created_on", type date},
				{"trueai_creator_id", type text},
				{"trueai_leadsource", type text},
				{"trueai_leadsource_conf", type number},
				{"trueai_leadsource_rule", Int64.Type},
				{"trueai_owner_id", type text},
				{"trueai_test", type text},
				{"trueai_test_conf", type number},
				{"trueai_test_debug", type text},
				{"trueai_test_rule", type text},
				{"trueai_title_dept", type text},
				{"trueai_title_dept_conf", type number},
				{"trueai_title_seniority", type text},
				{"trueai_title_seniority_conf", type number}
				
				})
				in
				dbTableTyped

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

