table open_pipeline
	lineageTag: 63e68162-90ed-40cd-8e52-99f2a6d679a2

	measure 'meas.open_opps_dur_hrs' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			VAR temp_tbl = CALCULATETABLE(open_pipeline, opps[_sys_filt_end_date] > sel_date)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE(
			        MAX(open_pipeline[trueai_sort_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id])
			            && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[crm_created_on] <= sel_date
			        )
			    )
			)
			
			Var res  = AVERAGEX(filter_tbl,[trueai_act_dur] )
			RETURN res/3600
			```
		formatString: #,##0.0" hrs"
		displayFolder: _open_opps_pipeline
		lineageTag: 6a45d4e5-bc9f-4cbc-a81a-7ca586f55139

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_engagement_ratio' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			VAR temp_tbl = CALCULATETABLE(open_pipeline, opps[_sys_filt_end_date] > sel_date)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE(
			        MAX(open_pipeline[trueai_sort_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id])
			            && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[crm_created_on] <= sel_date
			        )
			    )
			)
			var _count = CALCULATE(SUMX(filter_tbl,[trueai_act_count] ))           // get the total act count
			var _eng_count = CALCULATE(SUMX(filter_tbl,[trueai_act_eng_count] ))            // get the act eng count
			var res = DIVIDE(
			    _eng_count,                 // get the ratio
			    _count
			)
			
			RETURN
			res+0
			```
		formatString: 0%;-0%;0%
		displayFolder: _open_opps_pipeline
		lineageTag: d0568ec4-480e-4596-8dfa-b70cc86cc8a5

	measure 'meas.open_opps_last_eng_days' =
			
			var last_eng = CALCULATE(MAX(opps[crm_last_act_time]))            // get the last eng date
			var _current_date =[meas.sel_date]              // get the current date
			var res = IF(
			    ISBLANK(last_eng),
			    BLANK(),
			    DATEDIFF(_current_date, last_eng, DAY)
			)
			
			RETURN
			res
		formatString: """+""#"" days"";""-""#"" days"";""-"""
		displayFolder: _open_opps_pipeline
		lineageTag: e2b00476-ab70-45d6-931d-701631f83f49

		annotation PBI_FormatHint = {"isCustom":true}

	measure open_opps__sys_doc_count = COUNT(open_pipeline[_sys_doc_id])
		formatString: #,0
		displayFolder: _open_opps_pipeline
		lineageTag: 28fc3a6b-76c7-4342-90d2-1d1ac2e41b38

	measure 'meas.open_opps_sel_date_count' = ```
			
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			VAR temp_tbl = CALCULATETABLE(open_pipeline, opps[_sys_filt_end_date] >= sel_date)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE(
			        MAX(open_pipeline[trueai_sort_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id]) 
			            && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[crm_created_on] <=sel_date
			        )
			    )
			)
			
			var res =  CALCULATE(COUNTX(filter_tbl, [_sys_doc_id]))
			
			
			RETURN
			res
			
			```
		formatString: #,0
		displayFolder: _open_opps_pipeline
		lineageTag: e9d52ce3-8497-4ab0-94db-791065dcd7bb

	measure 'meas.open_opp_sel_date_count_rob' = ```
			//*** This is the "earlier" measure sub filtere approach for TS data  - use to get a filter measure and a count only (counts can be used in pie charts etc)
			
			-- function that through multiple steps get the most recent records in a table for each coid and then allow u to do agg ops on it 
			var sel_date = [meas.sel_date] // get the selected date 
			
			//var temp_res =  CALCULATE(COUNT(ssr_history[_sys_doc_id]))
			var temp_tbl = CALCULATETABLE(open_pipeline , opps[_sys_filt_end_date] >= sel_date  ) // start by filtering the table to the appropriate period and override the end date to include open item,s 
			
			var filter_tbl  =
			FILTER (
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE (
			          MAX ( open_pipeline[trueai_sort_id] ),
			        FILTER (
			            all(open_pipeline),
			            open_pipeline[crm_opp_id] = EARLIER ( open_pipeline[crm_opp_id] ) // this checks all the other values if it is the relevant one
			            //&&  opps_histories[col._sys_filt_end_date] <= sel_date 
			            &&  open_pipeline[_sys_filt_end_date] <= sel_date  
			            //&&  ssr_history[step_end_date] < sel_date &&  ssr_history[_sys_filt_start_date] < sel_date  // this ensures that we exclude anything after the selected date - important!  this measure is doing both step outcome and trueai added on date filtering 
			        )
			    )
			)
			Var res  = countx(filter_tbl,[_sys_doc_id] )
			RETURN res
			
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: e2464022-caf0-4ce8-bdf3-5bd3ae240186

	measure 'meas.open_opps_last_eng_act' =
			
			var sel_date = CALCULATE(MAX(cal_start_dates[Date]))
			var res =  CALCULATE(
			    MAX(open_pipeline[trueai_last_eng_act])
			)
			
			RETURN
			res
		formatString: Short Date
		displayFolder: _open_opps_pipeline
		lineageTag: eb720c10-21e8-4cd2-b827-189df4909e8e

	measure 'meas.open_opps_stkhlds_involved' =
			
			MAX(ssr_history[stkhlds_all_contacts_count])
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 10044456-c905-4aaf-bb68-c235a7242c78

	measure 'meas.open_opps_quality_bucket' =
			
			Var res  = MAXX(opps, opps[trueai_qual_bucket] )
			RETURN res
		displayFolder: _open_opps_pipeline
		lineageTag: a0f1fe2d-9a8c-4f78-997c-e3802c7c466d

	measure 'meas.open_opps_pipeline_current_stage' =
			
			Var res  = MAXX(open_pipeline, open_pipeline[trueai_stage] )
			RETURN res
		displayFolder: _open_opps_pipeline
		lineageTag: 10887f14-fee8-45c1-9ec1-2e1f778a459c

	measure 'meas.open_opps_tbl_title' =
			
			var _date = FORMAT([meas.sel_date], "MM/dd/yyyy")           // get the formatted date
			var _str = "Open Opps List as of "              // table title text
			
			 var res = _str & _date
			
			RETURN
			res
		displayFolder: _open_opps_pipeline
		lineageTag: 3fed2c8f-0873-44c6-8b3f-b26f87d92022

	measure 'meas.open_opps_expected_value' =
			
			var _pipeline_amt = [meas.open_opps_pipeline_amt]           // get the pipeline amt
			var _win_prob = [meas.open_opps_avg_win_prob]              // get the avg win prob
			var _expected_amount = _pipeline_amt*_win_prob
			RETURN
			_expected_amount
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _open_opps_pipeline
		lineageTag: 4672c69a-d174-4726-ae84-a7811ec79108

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.open_opps_total_expected_value' = ```
			
			var _pipeline_amt = [meas.open_opps_pipeline_amt]           // get the pipeline amt
			var _win_prob = [meas.open_opps_avg_win_prob]              // get the avg win prob
			var _expected_amount = _pipeline_amt*_win_prob
			RETURN
			_expected_amount
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _open_opps_pipeline
		lineageTag: f6f5f311-dee6-4166-82e4-5396749b8afb

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.open_opps_total_expected_value_sply_diff' = ```
			
			
			var _current = CALCULATE([meas.open_opps_total_expected_value],open_pipeline[trueai_stage] in {"Early", "Mid", "Late"})          // get the current booking amt
			var _sply_amt = [meas.open_opps_total_expected_value_sply]          // get tge sply 
			
			var res = DIVIDE(
			    (_current - _sply_amt),
			    _sply_amt
			)
			
			RETURN
			res
			```
		formatString: +0 %;-0 %;"-"
		displayFolder: _open_opps_pipeline
		lineageTag: bcf22a5a-dc4a-4dd5-95a6-6140f6154c4e

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_avg_win_prob' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			VAR temp_tbl = CALCULATETABLE(open_pipeline, opps[_sys_filt_end_date] >= sel_date)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE(
			        MAX(open_pipeline[trueai_sort_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id]) 
			            && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[crm_created_on] <= sel_date
			        )
			    )
			)
			
			var res =  CALCULATE(AVERAGEX(filter_tbl, [trueai_success_prob]))
			
			
			RETURN
			res
			```
		formatString: 0%;-0%;0%
		displayFolder: _open_opps_pipeline
		lineageTag: 09563c27-7a16-47f1-b1db-9b88b120a9c1

	measure 'meas.open_opps_total_expected_value_sply' =
			
			var _pipeline_amt = [meas.open_opps_pipeline_amt_sply]           // get the pipeline amt
			var _win_prob = [meas.open_opps_avg_win_prob_sply]               // get the avg win prob
			var _expected_amount = _pipeline_amt*_win_prob
			RETURN
			_expected_amount
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _open_opps_pipeline
		lineageTag: 27bc090d-3507-41d7-ab3a-2678f1aaa5d0

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.open_opps_count' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			VAR temp_tbl = CALCULATETABLE(open_pipeline, opps[_sys_filt_end_date] >= sel_date)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE(
			        MAX(open_pipeline[trueai_sort_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id]) 
			            && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[crm_created_on] <= sel_date
			        )
			    )
			)
			
			var res =  CALCULATE(COUNTX(filter_tbl, [_sys_doc_id]), open_pipeline[trueai_stage] in {"Early", "Mid", "Late"})
			
			
			RETURN
			res
			```
		formatString: #,0
		displayFolder: _open_opps_pipeline
		lineageTag: 5887f433-2566-4a32-b1b4-3fce64f6b252

	measure 'meas.open_opps_count_sply' =
			
			CALCULATE(
			    [meas.open_opps_count],             // get the sply open opps count
			    open_pipeline[trueai_stage] in {"Early", "Mid", "Late"},
			    SAMEPERIODLASTYEAR(cal_start_dates[Date])
			)
		formatString: #,0
		displayFolder: _open_opps_pipeline
		lineageTag: 1364f987-e2fc-4a19-aa1a-6793b825a130

	measure 'meas.open_opps_count_sply_diff' =
			
			var _current = CALCULATE([meas.open_opps_count],open_pipeline[trueai_stage] in {"Early", "Mid", "Late"})           // currently open opps count
			var _sply  = [meas.open_opps_count_sply]       // get the sply open opps cou nt
			var res = DIVIDE(
			    (_current-_sply),
			    _sply
			)
			
			
			RETURN
			res
		formatString: +0 %;-0 %;"-"
		displayFolder: _open_opps_pipeline
		lineageTag: 847f07b1-8fa4-449e-b982-0b4257a69757

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_avg_win_prob_sply' =
			
			CALCULATE(
			    [meas.open_opps_avg_win_prob],
			    open_pipeline[trueai_stage] in {"Early", "Mid", "Late"},
			    DATEADD(cal_start_dates[Date], -1, YEAR)
			)
		formatString: 0%;-0%;0%
		displayFolder: _open_opps_pipeline
		lineageTag: bec26611-00c2-4632-a584-4ba4e1d29146

	measure 'meas.open_opps_avg_win_prob_sply_diff' =
			
			var _current = CALCULATE([meas.open_opps_avg_win_prob],open_pipeline[trueai_stage] in {"Early", "Mid", "Late"})            // get the current prob
			var _sply = [meas.open_opps_avg_win_prob_sply]              // get the sply prob
			
			var res = DIVIDE(
			            (_current - _sply),
			            _sply
			)
			
			RETURN
			res
		formatString: +0 %;-0 %;"-"
		displayFolder: _open_opps_pipeline
		lineageTag: bf752ab9-241b-4989-a052-9cdb5a8b1615

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_pipeline_amt' = ```
			
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			VAR temp_tbl = CALCULATETABLE(open_pipeline, opps[_sys_filt_end_date] >= sel_date)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE(
			        MAX(open_pipeline[trueai_sort_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id]) 
			            && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[crm_created_on] <=sel_date
			        )
			    )
			)
			
			
			var res =  CALCULATE(sumx(filter_tbl, [trueai_booking_amt]))
			
			
			RETURN
			res
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _open_opps_pipeline
		lineageTag: ee5a9b16-a525-485b-a196-4a906df32704

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.open_opps_pipeline_amt_sply' =
			
			CALCULATE(
			    [meas.open_opps_pipeline_amt],
			    open_pipeline[trueai_stage] in {"Early", "Mid", "Late"},
			    SAMEPERIODLASTYEAR(cal_start_dates[Date])
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _open_opps_pipeline
		lineageTag: dd4d4f41-a8cb-431f-af87-090fffea3092

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'meas.open_opps_pushed_pulled_day' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			VAR temp_tbl = CALCULATETABLE(open_pipeline, opps[_sys_filt_end_date] >= sel_date)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE(
			        MAX(open_pipeline[trueai_sort_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id]) 
			            && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[crm_created_on] <=sel_date
			        )
			    )
			)
			
			Var res  = AVERAGEX(filter_tbl,[trueai_days_pushed_pulled] )
			RETURN res
			
			```
		formatString: """+""#"" days"";""-""#"" days"";""-"""
		displayFolder: _open_opps_pipeline
		lineageTag: 0a3752cf-4a5e-495f-b062-18254a01d722

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_pushed_pulled_day_sply' =
			
			CALCULATE(
			    [meas.open_opps_pushed_pulled_day],             // get the sply open opps pipeline amt
			    DATEADD(cal_start_dates[Date], -1, YEAR)
			)
		formatString: """+""#"" days"";""-""#"" days"";""-"""
		displayFolder: _open_opps_pipeline
		lineageTag: 0fdc3b1b-d2b2-466f-88fa-5b5212fa2ab2

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_pushed_pulled_day_sply_diff' =
			
			var _current = [meas.open_opps_pushed_pulled_day]           // currently open opps pushed pulled day
			var _sply  = [meas.open_opps_pushed_pulled_day_sply]            // get the sply open opps pushed pulled day
			var res = DIVIDE(
			    (_current-_sply),
			    _sply
			)
			
			
			RETURN
			res
		formatString: +0 %;-0 %;"-"
		displayFolder: _open_opps_pipeline
		lineageTag: 503232e7-d329-4f73-ab02-afe03361dcc7

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_avg_pace_score' =
			
			var _avg =  ROUND(CALCULATE(AVERAGEX(open_pipeline, [trueai_pace_score]*5)),0)      // get the rounded avg of [trueai_pace_score] multply with 5
			var _capped_avg = IF(_avg > 5, 5, _avg)  // Cap the value at 5
			var res = SWITCH(
			    _capped_avg,
			    0, "0 - Static",
			    1, "1 - Slow-Moving",
			    2, "2 - Progressing",
			    3, "3 - Advancing",
			    4, "4 - Accelerated",
			    5, "5 - Rapid",
			    BLANK()
			)
			
			RETURN
			res
		displayFolder: _open_opps_pipeline
		lineageTag: 2cd78355-abb5-4625-b982-0a2fc4036aff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.open_opps_items_trueai_stage' = ```
			
			var opps_latest_row  = CALCULATETABLE(TOPN(1,opps, opps[_sys_as_of], DESC))  // get the most recent entries
			var opps_res =  CALCULATE(MAXX(opps_latest_row, opps[trueai_stage]))             // get the trueai stage name
			
			var open_pipeline_latest_row  = CALCULATETABLE(TOPN(1,open_pipeline, open_pipeline[_sys_as_of], DESC))  // get the most recent entries
			var open_pipeline_res =  CALCULATE(MAXX(open_pipeline_latest_row, open_pipeline[trueai_stage]))             // get the trueai stage name
			
			
			var res = IF(
			    opps_res=BLANK(),
			    open_pipeline_res,
			    opps_res
			)
			RETURN  
			res
			```
		displayFolder: _open_opps_pipeline
		lineageTag: 776d0094-a304-43f4-a8d7-79ccd778ca7c

	measure 'meas.open_opps_list_dur_hrs' =
			
			var dur = calculate(sum(open_pipeline[trueai_act_dur])) / 3600 // turn to hours
			var res  = dur
			return res
		formatString: #,##0.0" hrs"
		displayFolder: _open_opps_pipeline
		lineageTag: 2a7338c6-36d5-46af-9656-83ca8abf9e9b

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_avg_pace_score_sply' = ```
			
			var _sply = CALCULATE(
			    [meas.trueai_pace_score],       
			    DATEADD(cal_start_dates[Date], -1, YEAR)            // SPLY 
			)
			var _avg =  ROUND(_sply,0)
			var res = SWITCH(
			    _avg,
			    0, "0 - Static",
			    1, "1 - Slow-Moving",
			    2, "2 - Progressing",
			    3, "3 - Advancing",
			    4, "4 - Accelerated",
			    5, "5 - Rapid",
			    BLANK()
			)
			
			RETURN
			res
			```
		displayFolder: _open_opps_pipeline
		lineageTag: e7cd5e66-6316-4e65-a0ca-8afcbaddce17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.open_opps_avg_pace_score_sply_diff' = ```
			
			var _avg = [meas.trueai_pace_score]             /// current
			var _sply = CALCULATE(
			    [meas.trueai_pace_score],       
			    DATEADD(cal_start_dates[Date], -1, YEAR)            // SPLY 
			)
			
			var res = DIVIDE(
			    (_avg - _sply),
			    _sply,
			    0
			)
			
			RETURN
			res+0
			```
		formatString: +0 %;-0 %;"0%"
		displayFolder: _open_opps_pipeline
		lineageTag: 41d3a2d1-6046-441d-a9fa-40eebb66c5a5

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_act_count' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			VAR temp_tbl = CALCULATETABLE(open_pipeline, opps[_sys_filt_end_date] > sel_date)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[trueai_sort_id] = 
			    CALCULATE(
			        MAX(open_pipeline[trueai_sort_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id])
			            && open_pipeline[_sys_filt_end_date] >= sel_date && open_pipeline[crm_created_on] <= sel_date
			        )
			    )
			)
			
			Var res  = SUMX(filter_tbl,[trueai_act_count] )
			RETURN 
			res
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 6a434a8f-008e-4cae-9c06-610797cb5790

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'meas.open_opps_pipeline_amt_sply_diff' =
			
			var _current = CALCULATE([meas.open_opps_pipeline_amt],open_pipeline[trueai_stage] in {"Early", "Mid", "Late"})
			var _sply = [meas.open_opps_pipeline_amt_sply]
			
			var res = DIVIDE(
			    (_current - _sply),
			    _sply
			)
			RETURN
			res
		formatString: +0 %;-0 %;"-"
		displayFolder: _open_opps_pipeline
		lineageTag: d6256281-bb95-4002-b9dc-f549b83adb97

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_age_days' =
			
			var res =  CALCULATE(MAX(opps[col.opp_age]))
			
			RETURN
			res
		formatString: #" days"
		displayFolder: _open_opps_pipeline
		lineageTag: ad1da48a-6e54-4e91-a08c-c7bc384cc905

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_age_days_sply' = ```
			
			var res = CALCULATE(
			    [meas.open_opps_age_days], 
			    DATEADD(cal_start_dates[Date], -1, YEAR)
			)
			RETURN
			res
			```
		formatString: #" days"
		displayFolder: _open_opps_pipeline
		lineageTag: 20796ce7-2bb9-4d4f-aff7-29c4f18cf0f2

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_age_days_sply_diff' =
			
			var _current = [meas.open_opps_age_days]
			var _sply = [meas.open_opps_age_days_sply]
			
			var res = DIVIDE(
			    (_current - _sply),
			    _sply
			)
			
			RETURN
			res
		formatString: +0 %;-0 %;"-"
		displayFolder: _open_opps_pipeline
		lineageTag: e0d8f8e6-07e4-438e-bc93-43c5cb5bc567

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_initial_close_date' =
			
			CALCULATE(MAX(open_pipeline[trueai_init_close_date]))
		formatString: Short Date
		displayFolder: _open_opps_pipeline
		lineageTag: 666cb7ed-c316-4ced-91d8-b12470cd140d

	measure 'meas.open_opps_items_all_act_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 5351b99b-b4f0-4a02-8a1c-1c05896763fb

	measure 'meas.open_opps_items_all_act_eng_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_eng_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 562e4c2a-cc4b-490a-a288-8d995335aa69

	measure 'meas.opps_detail_sale_type' =
			
			CALCULATE(
			    MAX(opps[trueai_sale_type])
			)
		displayFolder: _opps_details
		lineageTag: 86fe027a-e93e-4386-b548-e6b4c760d472

	measure 'meas.open_opps_trueai_stage' =
			
			CALCULATE(
			    MAX(open_pipeline[trueai_stage])
			)
		displayFolder: _opps_details
		lineageTag: c2aee211-195c-4a6d-a5b3-137bd1443ee5

	measure 'meas.open_opps_items_meeting_act_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_type_meeting_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: ff73db87-015f-42d0-8c66-7f7b9b86f4cc

	measure 'meas.open_opps_items_meeting_act_eng_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_type_meeting_eng_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: e284c69f-4727-47a1-8c86-d4a75cd2d286

	measure 'meas.open_opps_items_phone_act_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_type_call_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: ed3ac908-6a96-432a-bc09-6e6cbb6d6bc7

	measure 'meas.open_opps_items_phone_act_eng_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_type_call_eng_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 68a59106-ced4-4531-9692-5b9c2766f25d

	measure 'meas.open_opps_items_email_act_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_type_email_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 5b2295a4-b13a-4594-801f-de41eb83f281

	measure 'meas.open_opps_items_email_act_eng_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_type_email_eng_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 6925d7b9-faf4-4665-89f6-3a97c20739bd

	measure 'meas.open_opps_items_social_act_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_type_social_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: a09784e8-3f24-46db-a1c2-6e5b74ffcc18

	measure 'meas.open_opps_items_social_act_eng_count' =
			
			CALCULATE(
			    SUM(open_pipeline[trueai_act_type_social_eng_count])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: ba11a93f-9048-4bea-b2f0-6fee3754c1cf

	measure 'meas.open_opps_items_all_act-non_eng_count' = ```
			
			var all_count = [meas.open_opps_items_all_act_count]            // get all the counts 
			var _eng_count = [meas.open_opps_items_all_act_eng_count]               // get the eng count
			var res = (all_count - _eng_count)
			
			RETURN
			res
			```
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 9b8f7cff-0382-4b11-bdf0-7e343e55d69f

	measure 'meas.open_opps_items_phone_act-non_eng_count' = ```
			
			var all_count = [meas.open_opps_items_phone_act_count]            // get all the counts 
			var _eng_count = [meas.open_opps_items_phone_act_eng_count]               // get the eng count
			var res = (all_count - _eng_count)
			
			RETURN
			res
			```
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 49836b2b-33de-4e7b-9379-d4e695c67745

	measure 'meas.open_opps_items_email_act-non_eng_count' = ```
			
			var all_count = [meas.open_opps_items_email_act_count]            // get all the counts 
			var _eng_count = [meas.open_opps_items_email_act_eng_count]               // get the eng count
			var res = (all_count - _eng_count)
			
			RETURN
			res
			```
		formatString: 0
		displayFolder: _opps_details
		lineageTag: f393c148-a960-480e-9a2c-393abd7eb640

	measure 'meas.open_opps_items_meeting_act-non_eng_count' = ```
			
			var all_count = [meas.open_opps_items_meeting_act_count]            // get all the counts 
			var _eng_count = [meas.open_opps_items_meeting_act_eng_count]               // get the eng count
			var res = (all_count - _eng_count)
			
			RETURN
			res
			```
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 345deff2-6a35-4fa5-b7dc-9672dbd4c758

	measure 'meas.open_opps_items_social_act-non_eng_count' = ```
			
			var all_count = [meas.open_opps_items_social_act_count]            // get all the counts 
			var _eng_count = [meas.open_opps_items_social_act_eng_count]               // get the eng count
			var res = (all_count - _eng_count)
			
			RETURN
			res
			```
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 6bfaea9e-b5e3-430d-9ac4-7824f78d80f6

	measure 'meas.open_opps_items_act_eng_counts' =
			
			
			SWITCH(TRUE(),
			    MAX(all_act_support[order])=1, [meas.open_opps_items_all_act_eng_count],
			    MAX(all_act_support[order])=2, [meas.open_opps_items_phone_act_eng_count],
			    MAX(all_act_support[order])=3, [meas.open_opps_items_email_act_eng_count],
			    MAX(all_act_support[order])=4, [meas.open_opps_items_meeting_act_eng_count],
			    MAX(all_act_support[order])=5, [meas.open_opps_items_social_act_eng_count]
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: cb8a841a-7579-4716-997f-4d32193b4f51

	measure 'meas.open_opps_items_act_non_eng_counts' =
			
			
			SWITCH(TRUE(),
			    MAX(all_act_support[order])=1, [meas.open_opps_items_all_act-non_eng_count],
			    MAX(all_act_support[order])=2, [meas.open_opps_items_phone_act-non_eng_count],
			    MAX(all_act_support[order])=3, [meas.open_opps_items_email_act-non_eng_count],
			    MAX(all_act_support[order])=4, [meas.open_opps_items_meeting_act-non_eng_count],
			    MAX(all_act_support[order])=5, [meas.open_opps_items_social_act-non_eng_count]
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 9b0454a2-e77d-45a6-acf0-2e9e84b9639a

	measure 'meas.open_opps_items_act_eng_rate' =
			
			var _all_act = [meas.open_opps_items_all_act_count]         // get the all act count
			var _eng_count = [meas.open_opps_items_all_act_eng_count]           // get the eng count
			var res = DIVIDE(_eng_count, _all_act, 0)
			
			RETURN
			res
		formatString: 0%;-0%;0%
		displayFolder: _opps_details
		lineageTag: bc15b784-1974-4c5a-a31d-e5c14f89a0ef

	measure 'meas.closed_opps_age_days' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			
			
			VAR _age = 
			    CALCULATE(
			        AVERAGEX(
			            opps,
			            opps[col.opp_age]
			        )
			    )
			
			RETURN
			    _age
			```
		formatString: #" days"
		displayFolder: _opps_details
		lineageTag: 41a9e006-5351-4ec8-a506-fd7469bcf761

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.step_sub_type' = CALCULATE(MAX(ssr_history[step_sub_type]))
		displayFolder: _opps_details
		lineageTag: b47a791b-611d-4c41-bed6-d76b0df5fe8c

	measure 'meas.opps_creator_name' =
			CALCULATE(
			    MAX(opps[col.creator_name])
			)
		displayFolder: _opps_details
		lineageTag: e8050285-8de1-458d-9c75-d7bfaa7f7806

	measure 'meas.opps_details_screen_age' = ```
			
			VAR SelectedDate = MAX('cal_start_dates'[Date])
			
			var _age =  MAXX(
			        'open_pipeline', 
			        DATEDIFF('open_pipeline'[crm_created_on], SelectedDate, DAY)
			    )
			
			var _closed_opps_age = [meas.closed_opps_age_days]             // get the closed opps list
			var _step_outcome = CALCULATE(FIRSTNONBLANK(ssr_history[step_outcome],1))
			var _cond = IF(
			    NOT _step_outcome  in {"Closed Won", "Closed Lost"},
			    _age,
			    _closed_opps_age
			)
			
			
			RETURN
			_cond
			```
		formatString: #" days"
		displayFolder: _opps_details
		lineageTag: 739619e9-cbe2-42f5-ab90-fc0688874c9e

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.opps_details_screen_pushed_pulled' =
			
			
			VAR _age = [meas.open_opps_pushed_pulled_day]
			var _step_outcome = CALCULATE(FIRSTNONBLANK(ssr_history[step_outcome],1))
			var closed_opp = CALCULATE(
			    MAX(ssr_history[trueai_days_pushed_pulled]),
			    ssr_history[step_outcome] in {"Closed Won", "Closed Lost"}
			)
			var _cond = IF(
			    _step_outcome  in {"Closed Won", "Closed Lost"},
			    closed_opp,
			    _age
			)
			
			RETURN
			_cond
		formatString: """+""#"" days"";""-""#"" days"";""-"""
		displayFolder: _opps_details
		lineageTag: 09e0b95c-4799-473c-a99c-6f69f3bfb86e

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.open_opps_last_eng_date_filter' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			
			
			 
			VAR MaxOppCreated = CALCULATE(MAX(cal_start_dates[Date]))
			RETURN
			IF (
			    MAX('open_pipeline'[crm_created_on]) <= MaxOppCreated &&
			    MAX(open_pipeline[trueai_last_eng_act]) <= MaxOppCreated,
			    1,
			    0
			)
			
			
			```
		displayFolder: _open_opps_pipeline
		lineageTag: 3cf39ace-fd7b-4393-b313-238b3d23680b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.closed_opps_pushed_pulled_days' = CALCULATE(MAX(ssr_history[step_days_pushed_pulled]))
		formatString: 0
		displayFolder: _opps_details
		lineageTag: e493b4b2-b983-453f-b401-dcd092339cf5

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.opps_crm_deep_link' =
			
			var res = IF(CONTAINSSTRING(MAX(opps[crm_deep_link]), "http"), "#11BDFC", "#11BDFC")
			
			RETURN
			res
		displayFolder: _opps_details
		lineageTag: 78bf53a1-8293-4c3c-b17b-9476ef792ed5

	measure 'meas.opp_details_opps_rep_involved' =
			
			CALCULATE(
			    DISTINCTCOUNT(ssr_history[col.step_owner_full_name]),
			    REMOVEFILTERS(ssr_history[step_name])
			)
		formatString: 0
		displayFolder: _opps_details
		lineageTag: 87aae354-3872-4fc5-ba22-bb59bbceb983

	measure 'meas.open_opps_account_name' =
			
			CALCULATE(
			    MAX(ssr[crm_name])
			)
		displayFolder: _open_opps_pipeline
		lineageTag: 3398574e-569e-43e9-b8fd-6ace23959662

	measure 'meas.opp_details_most_recent_step_outcome' =
			
			var _max_step_id = MAX(ssr_history[step_sequence])          // get the most recent step sequence number
			var temp_res = CALCULATE(
			    Max(ssr_history[step_outcome]),
			    ssr_history[step_sequence] = _max_step_id           // get the most recent step outcome
			)
			var res = IF(
			    temp_res=BLANK(),
			    CALCULATE(
			        Max(ssr_history[step_outcome]),
			        ssr_history[step_sequence] = (_max_step_id -1)          // get the most recent step outcome
			    ),
			    temp_res
			)
			
			
			RETURN
			res
		displayFolder: _opps_details
		lineageTag: aa15574a-fd7d-482f-a3cd-7eab0b46de95

	measure 'meas.opp_details_most_recent_step_sub_type' =
			
			var _max_step_id = MAX(ssr_history[step_sequence])          // get the most recent step sequence number
			var res = CALCULATE(
			    Max(ssr_history[step_sub_type]),
			    ssr_history[step_sequence] = _max_step_id           // get the most recent step sub type
			)
			
			
			RETURN
			res
		displayFolder: _opps_details
		lineageTag: 1fbb5ddc-25e3-4ee3-ba4c-8c4ff9c461d2

	measure 'meas.open_opps_count_tbl_filter' = ```
			
			VAR sel_end_date =CALCULATE(MAX(cal_start_dates[Date])) // get the selected max date 
			VAR sel_start_date =CALCULATE(MIN(cal_start_dates[Date])) // get the selected max date 
			
			VAR temp_tbl = CALCULATETABLE(
			    open_pipeline, 
			    opps[_sys_filt_start_date] >= sel_start_date,
			    opps[_sys_filt_end_date] >= sel_end_date
			)
			
			VAR filter_tbl = 
			FILTER(
			    temp_tbl,
			    open_pipeline[_sys_doc_id] = 
			    CALCULATE(
			        MAX(open_pipeline[_sys_doc_id]),
			        FILTER(
			            ALL(open_pipeline),         // get the most recent open opps items
			            open_pipeline[crm_opp_id] = EARLIER(open_pipeline[crm_opp_id])
			        )
			    )
			)
			
			var res =  CALCULATE(COUNTX(filter_tbl, [_sys_doc_id]))
			
			
			RETURN
			res
			
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 2ca20c71-4d42-4429-98e2-916ffaec97bc

	measure 'meas.open_pipeline_concate_measure' =
			
			MAX(open_pipeline[crm_stage_name]) & " (" & MAX(open_pipeline[trueai_stage]) & ") "
		displayFolder: _open_opps_pipeline
		lineageTag: 915b5124-4bd9-48e1-8943-5510c93e3cbe

	measure 'meas.open_opps_age_days_filter' = ```
			
			VAR sel_date = [meas.sel_date] // get the selected date 
			
			VAR _age = 
			    CALCULATE(
			        AVERAGEX(
			            opps,
			            DATEDIFF(
			                opps[crm_created_on],
			                sel_date,
			                DAY
			            )
			        )
			    )
			
			RETURN
			   _age+0
			
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 2c01d1ac-22ff-4dae-8709-b616872b9996

	measure 'Days Difference' = ```
			
			VAR SelectedDate = MAX('cal_start_dates'[Date])
			RETURN
			    AVERAGEX(
			        'open_pipeline', 
			        DATEDIFF('open_pipeline'[crm_created_on], SelectedDate, DAY)
			    )
			
			```
		displayFolder: _open_opps_pipeline
		lineageTag: 84e7f3d8-2a2e-47d3-a51b-f715450dda50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.open_opps_trueai_booking_amt' = sum(open_pipeline[trueai_booking_amt])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _open_opps_pipeline
		lineageTag: 95540529-8f00-4fa5-977f-e450852f352c

	measure 'meas.opp_details_most_recent_sales_type' =
			
			var _max_step_id = MAX(ssr_history[step_sequence])          // get the most recent step sequence number
			var temp_res = CALCULATE(
			    Max(ssr_history[opp_sale_type]),
			    ssr_history[step_sequence] = _max_step_id           // get the most recent step outcome
			)
			var res = IF(
			    temp_res=BLANK(),
			    CALCULATE(
			        Max(ssr_history[opp_sale_type]),
			        ssr_history[step_sequence] = (_max_step_id -1)          // get the most recent step outcome
			    ),
			    temp_res
			)
			
			
			RETURN
			res
		displayFolder: _opps_details
		lineageTag: eef20aec-590d-4d8c-aaea-4ff2369b0fee

	measure 'meas.trueai_pace_score' =
			
			var _avg =  ROUND(CALCULATE(AVERAGEX(open_pipeline, [trueai_pace_score]*5)),0)      // get the rounded avg of [trueai_pace_score] multply with 5
			var _capped_avg = IF(_avg > 5, 5, _avg)  // Cap the value at 5
			
			RETURN
			_avg
		displayFolder: _open_opps_pipeline
		lineageTag: 67d7db70-6bf3-4fd8-8315-2e7cefc258f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_details_avg_pace_score' =
			
			
			var _avg =  ROUND(CALCULATE(AVERAGEX(open_pipeline, [trueai_pace_score]*5)),0)
			
			var res = SWITCH(
			    _avg,
			    0, "0 - Static",
			    1, "1 - Slow-Moving",
			    2, "2 - Progressing",
			    3, "3 - Advancing",
			    4, "4 - Accelerated",
			    5, "5 - Rapid"
			)
			
			RETURN
			res
		displayFolder: _opps_details
		lineageTag: 7a4fcb97-150c-44be-9490-680fa978ba2f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.open_opps_items_trueai_booking_amt' = ```
			
			var latest_row  = CALCULATETABLE(TOPN(1,open_pipeline, open_pipeline[_sys_as_of], DESC))  // get the most recent entries
			var res =  CALCULATE(MAXX(latest_row, open_pipeline[trueai_booking_amt]))             // get the total trueai booking amt
			RETURN  
			res
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _open_opps_pipeline
		lineageTag: f86e3bdf-05a5-4e3a-8fe9-7889136e011e

	measure 'meas.trueai_pace_score_test' =
			
			
			var _avg =  ROUND(CALCULATE(AVERAGEX(open_pipeline, [trueai_pace_score]*5)),0)      // get the rounded avg of [trueai_pace_score] multply with 5
			var _capped_avg = IF(_avg > 5, 5, _avg)  // Cap the value at 5
			var res = SWITCH(
			    _capped_avg,
			    0, "0 - Static",
			    1, "1 - Slow-Moving",           // creating switch to display the pace
			    2, "2 - Progressing",
			    3, "3 - Advancing",
			    4, "4 - Accelerated",
			    5, "5 - Rapid"
			)
			
			RETURN
			res
		displayFolder: _open_opps_pipeline
		lineageTag: 227888e3-aabf-42c0-9433-a0c33babd0aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.open_pipeline_stage_sort_index' = ```
			
			var avg_seq = CALCULATE(AVERAGE(open_pipeline[trueai_step_sequence])) // lower avg indidctes earlier stage
			var close_boost =  If(CALCULATE(FIRSTNONBLANK(open_pipeline[trueai_is_closed],"") =true) , 100, 0) // add 100 to the closed steps, otherwise 0 
			var res  = avg_seq + close_boost
			return res
			```
		formatString: 0
		lineageTag: bfe9fd21-6834-4474-b340-ffb9829e416f

	measure 'meas.open_pipeline_avg_days_in_stage' =
			
			var res = CALCULATE(AVERAGE(open_pipeline[trueai_days_in_stage]))
			return res
		lineageTag: 8421c8c5-50f2-4b5d-96d9-77f070c95c08

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.open_pipeline_deals_reached_next_stage_count' =
			
			VAR raw_stage = SELECTEDVALUE(open_pipeline[trueai_avg_step_sequence])
			VAR stage_num = VALUE(raw_stage) + 1
			
			VAR reached_stage_count =
			    CALCULATE(
			        DISTINCTCOUNT(open_pipeline[crm_opp_id]),
			        ISNUMBER(VALUE(open_pipeline[trueai_avg_step_sequence])) &&
			        VALUE(open_pipeline[trueai_avg_step_sequence]) >= stage_num,
			        open_pipeline[trueai_is_closed] = FALSE(),
			        open_pipeline[trueai_stage] <> "abc",
			        open_pipeline[trueai_stage_name] <> "abc",
			        open_pipeline[trueai_stage_num] <> -999
			    )
			
			RETURN reached_stage_count + 0
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 45f80dbb-99fb-49e4-a0ca-804b1a6dc6b0

	measure 'meas.open_pipeline_deals_reached_stage_count' = ```
			
			VAR stage_num =     SELECTEDVALUE(open_pipeline[trueai_avg_step_sequence])   // add one because we want to look at the next stage 
			var reached_stage_count = CALCULATE(DISTINCTCOUNT(open_pipeline[crm_opp_id]) , open_pipeline[trueai_avg_step_sequence] >= stage_num && open_pipeline[trueai_is_closed] =false &&  open_pipeline[trueai_stage] <> "abc"  && open_pipeline[trueai_stage_name] <> "abc"  && open_pipeline[trueai_stage_num] <> -999) // do greater than to cathc skipped steps
			return reached_stage_count + 0
			
			```
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 5b76cd85-e359-444f-920b-8bccf3a3081d

	measure 'meas.open_pipeline_lost_deals_in_stage_tot_pct' =
			
			DIVIDE( [meas.open_pipeline_lost_deals_in_stage], [meas.open_pipeline_total_deals])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _open_opps_pipeline
		lineageTag: 387d7496-7688-434e-930b-dd08ae451126

	measure 'meas.open_pipeline_lost_deals_in_stage' =
			
			var res = [meas.open_pipeline_deals_reached_stage_count] - [meas.open_pipeline_deals_reached_next_stage_count]
			return res
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 9ce4e60f-1a95-4b12-aedf-0822ef95bdde

	measure 'meas.open_pipeline_total_deals' =
			
							VAR stage_num = SELECTEDVALUE(open_pipeline[trueai_avg_step_sequence])
							VAR res =
			    			CALCULATE(
			        		DISTINCTCOUNT(open_pipeline[crm_opp_id]),
			        		VALUE(open_pipeline[trueai_avg_step_sequence]) <> -999,
			        		VALUE(open_pipeline[trueai_stage_num]) <> -999,
			        		open_pipeline[trueai_stage] <> "abc",
			        		open_pipeline[trueai_stage_name] <> "abc"
			    			)
							RETURN res
		formatString: 0
		displayFolder: _open_opps_pipeline
		lineageTag: 6edf0fca-e41a-4470-9a2e-7c396135f38b

	measure 'meas.open_pipeline_lost_amt' = CALCULATE(sum(open_pipeline[trueai_booking_amt]), open_pipeline[trueai_is_won] = false)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _open_pipeline
		lineageTag: 41ec1f6d-2ebd-499d-b232-7de1b984e328

	measure 'meas.open_pipeline_won_count' = CALCULATE(count(open_pipeline[trueai_booking_amt]), open_pipeline[trueai_is_won] = true)
		formatString: 0
		displayFolder: _open_pipeline
		lineageTag: 8f56ffd7-2b00-478e-98ab-5f9e7bd66765

	measure 'meas.open_pipeline_lost_count' = CALCULATE(count(open_pipeline[trueai_booking_amt]), open_pipeline[trueai_is_won] = false)
		formatString: 0
		displayFolder: _open_pipeline
		lineageTag: 4a836a7c-fa82-462b-9d0f-4bd5a72bd987

	measure 'meas.open_pipeline_booking_amt' = CALCULATE(sum(open_pipeline[trueai_booking_amt]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _open_pipeline
		lineageTag: a852f06f-7ef4-4074-a500-b847c05e29e6

	measure 'meas.open_pipeline_won_amt' = CALCULATE(sum(open_pipeline[trueai_booking_amt]), open_pipeline[trueai_is_won] = true)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _open_pipeline
		lineageTag: 9b11582e-23e3-4c87-b262-f2c6c548bda0

	measure 'meas.open_pipeline_booking_amt_avg' = CALCULATE(AVERAGE((open_pipeline[trueai_booking_amt])))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _open_pipeline
		lineageTag: 461b9e80-02df-467a-a442-d4a22edefb0c

	measure 'meas.open_pipeline_count_id' = COUNT(open_pipeline[_sys_doc_id])
		formatString: 0
		displayFolder: _open_pipeline
		lineageTag: 45a2df27-31e4-4b0f-9e84-bce4843d7a29

	measure 'meas.open_pipeline_discount_id' = DISTINCTCOUNT(open_pipeline[_sys_doc_id])
		formatString: 0
		displayFolder: _open_pipeline
		lineageTag: 1b1912dd-eaf7-4d0a-9f3c-e7837c30a89e

	measure 'meas.open_pipeline_crm_opp_id' = CALCULATE(DISTINCTCOUNT(open_pipeline[crm_opp_id]))
		formatString: 0
		displayFolder: _open_pipeline
		lineageTag: 7b6292df-4f86-40ec-a3a8-8a9126a9c3ee

	measure 'meas.open_pipeline_deals_reached_stage_count_pct' =
			
			DIVIDE( [meas.open_pipeline_deals_reached_stage_count], [meas.open_pipeline_total_deals])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _open_pipeline
		lineageTag: b1343ea0-8007-4eed-aebf-3aa0716f50fa

	measure 'meas.open_pipeline_lost_deals_in_stage_pct' =
			
			DIVIDE( [meas.open_pipeline_lost_deals_in_stage], [meas.open_pipeline_deals_reached_stage_count])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _open_pipeline
		lineageTag: 69c96034-6487-4773-aeb2-26c2adbde284

	measure 'meas.open_pipeline_lost_booking_amt_in_stage' = [meas.opps_booking_lost_amt] - [meas.opps_booking_amt_reached_next_stage]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _open_opps_pipeline
		lineageTag: 7cfad227-8096-4d3c-867e-ecb6cb164339

	measure 'meas.open_pipeline_stages_avg' =
			
			DIVIDE (
			    [meas.opps_max_stages],
			    [meas.open_pipeline_deals_reached_stage_count]
			)
		formatString: 0.00
		displayFolder: _open_pipeline
		lineageTag: 10d10955-21db-49f5-9e8d-c442e26e9976

	measure 'meas.open_pipeline_deals_skip_count' =
			
			CALCULATE (
			    [meas.open_pipeline_deals_reached_stage_count],
			     opps[col.trueai_opp_stages_recorded] < 5
			)
		formatString: 0
		displayFolder: _open_pipeline
		lineageTag: 857f871b-8f2b-4feb-9647-751d2205a62d

	measure 'meas.open_pipeline_deals_skip_pct' = DIVIDE([meas.open_pipeline_deals_skip_count],[meas.open_pipeline_total_deals])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _open_pipeline
		lineageTag: 7f9662b6-0c94-479c-a6be-031d130f7b5e

	measure 'meas.open_pipeline_win_rate' =
			
			DIVIDE (
			    [meas.open_pipeline_deals_stage_count_won],
			    CALCULATE ( [meas.open_pipeline_total_deals], ALL (opps) ),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: _open_pipeline
		lineageTag: 331c9e02-103a-4157-8d38-3973872187be

	measure 'meas.open_pipeline_total_deals_won' =
			
			CALCULATE( [meas.open_pipeline_total_deals],
			            open_pipeline[trueai_is_won] = true)
		formatString: 0
		displayFolder: _open_pipeline
		lineageTag: d708d33c-4eb9-4961-9c8e-b3a39fd4c457

	measure 'meas.open_pipeline_deals_stage_count_won' = ```
			
			var res = CALCULATE( open_pipeline[meas.open_pipeline_deals_reached_stage_count], opps[trueai_is_won] = TRUE()) 
			return res
			```
		formatString: 0
		displayFolder: _open_pipeline
		lineageTag: b44ee7e1-dd92-49fa-8551-420880d4e58d

	measure 'meas.ssr_history_duration_hrs_deals_accumulated' = ```
			
			VAR CurIdx = MAX ( 'open_pipeline'[trueai_avg_step_sequence] ) RETURN SUMX ( FILTER ( ALL ( 'open_pipeline'[trueai_avg_step_sequence] ), 
			
			'open_pipeline'[trueai_avg_step_sequence] <= CurIdx ), CALCULATE ( [meas.ssr_history_duration_hrs_new_logo] + [meas.ssr_history_duration_hrs_existing_customer_selling] )
			)
			```
		displayFolder: _open_pipeline
		lineageTag: d82ce027-846a-4f66-b154-2612252fd977

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_histories_crm_stage_names' = ```
			
			-- concats all the crm values for trueai value
			
			-- summarize the currect context and sort by count desc
			var tbl_summarized = TOPN(10,SUMMARIZE(CALCULATETABLE(open_pipeline), [trueai_stage_name], "count", Count(open_pipeline[_sys_doc_id]) ),[count], DESC)
			
			-- use the summarized data and concat
			var str_crm_vals = CONCATENATEX(tbl_summarized,  [trueai_stage_name], ", ") 
			
			var res = str_crm_vals -- output string
			return res
			```
		displayFolder: opps_histories_To_open_pipeline
		lineageTag: f1f1de1f-d2b1-440d-9e81-9ec440e9d3d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'meas.opps_details_screen_trueai_pushed_pulled' =
			
			VAR _age =
			    AVERAGE ( open_pipeline[trueai_days_pushed_pulled] )
			VAR _step_outcome =
			    CALCULATE ( FIRSTNONBLANK ( ssr_history[step_outcome], 1 ) )
			VAR closed_opp =
			    CALCULATE (
			        MAX ( ssr_history[trueai_days_pushed_pulled] ),
			        ssr_history[step_outcome] IN { "Closed Won", "Closed Lost" }
			    )
			VAR _cond =
			    IF (
			        _step_outcome IN { "Closed Won", "Closed Lost" },
			        closed_opp,
			        _age
			    )
			RETURN
			    _cond
		lineageTag: c5ec0e68-cb24-4f7f-afa1-0d61eb1d2a5c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _sys_as_of
		dataType: dateTime
		formatString: Short Date
		lineageTag: 84c24770-04d5-464e-a640-80d113916b47
		summarizeBy: none
		sourceColumn: _sys_as_of

		variation Variation
			isDefault
			relationship: 99b03212-c52e-44c7-8fdf-aea664fee9ec
			defaultHierarchy: LocalDateTable_4b69b310-23d2-44f1-9978-e70ef1041da8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _sys_filt_end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4a2b3a16-6caf-448b-97d0-b89705d4a70e
		summarizeBy: none
		sourceColumn: _sys_filt_end_date

		variation Variation
			isDefault
			relationship: 3f7017f7-ad4d-4f77-8229-c58a6cb688d5
			defaultHierarchy: LocalDateTable_ea0b5414-aa5a-40bb-88a1-4082690bfe5d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _sys_filt_start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5c3452b5-751c-4957-87f6-fc6a034c2d04
		summarizeBy: none
		sourceColumn: _sys_filt_start_date

		variation Variation
			isDefault
			relationship: 9a764f24-6f10-4bec-910a-196d10dc78cb
			defaultHierarchy: LocalDateTable_a4b161a4-9c3c-47fd-8831-043f7e377c42.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column crm_booking_amt
		dataType: double
		lineageTag: a7ab38e7-7bd8-45db-bb44-69c4b7610fb1
		summarizeBy: sum
		sourceColumn: crm_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column crm_close_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: b021503a-2e22-41cc-9f37-d47159daaeca
		summarizeBy: none
		sourceColumn: crm_close_date

		variation Variation
			isDefault
			relationship: 7cd62e2c-8fd1-416d-b9a4-e598467f6902
			defaultHierarchy: LocalDateTable_a43e65ea-ad4c-4de1-855f-264fb88ad27d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_created_on
		dataType: dateTime
		formatString: Short Date
		lineageTag: c0c04d63-3c6e-4287-84ed-197863ad7cbf
		summarizeBy: none
		sourceColumn: crm_created_on

		variation Variation
			isDefault
			relationship: d35858e0-d45c-4b85-9a05-ad88b7158cfe
			defaultHierarchy: LocalDateTable_1ce22bbd-cf2b-452d-8add-87818a4e85bf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_creator_id
		dataType: string
		lineageTag: 494afd3f-f2e0-4ceb-a0b9-f3443d5b5e50
		summarizeBy: none
		sourceColumn: crm_creator_id

		annotation SummarizationSetBy = Automatic

	column crm_opp_id
		dataType: string
		lineageTag: 93982bca-9859-4daf-a8ed-156b4116a9c8
		summarizeBy: none
		sourceColumn: crm_opp_id

		annotation SummarizationSetBy = Automatic

	column crm_stage_name
		dataType: string
		lineageTag: 39e0679f-55fa-4214-ba46-2e60c6db3f6d
		summarizeBy: none
		sourceColumn: crm_stage_name
		sortByColumn: trueai_stage_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column crm_stage_num
		dataType: string
		lineageTag: 7108c05b-c9ec-49e4-928b-8306a3b40ffb
		summarizeBy: none
		sourceColumn: crm_stage_num

		annotation SummarizationSetBy = Automatic

	column trueai_booking_amt
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e3654569-5198-42f6-976e-9e3f9bf085ff
		summarizeBy: sum
		sourceColumn: trueai_booking_amt

		annotation SummarizationSetBy = Automatic

	column trueai_is_won
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 727dc425-47c4-4aa5-a460-8e57d31b12a2
		summarizeBy: none
		sourceColumn: trueai_is_won

		annotation SummarizationSetBy = Automatic

	column trueai_stage
		dataType: string
		lineageTag: c17ed2a6-cfca-487a-ac22-9503016d5f4a
		summarizeBy: none
		sourceColumn: trueai_stage
		sortByColumn: trueai_stage_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column cust_text1
		dataType: string
		lineageTag: 8f57c040-d45f-4d28-a473-b7ae83e69aac
		summarizeBy: none
		sourceColumn: cust_text1

		annotation SummarizationSetBy = Automatic

	column cust_text2
		dataType: string
		lineageTag: d3257e95-78c9-4e2e-bfff-5d015ae5c915
		summarizeBy: none
		sourceColumn: cust_text2

		annotation SummarizationSetBy = Automatic

	column cust_text3
		dataType: string
		lineageTag: fc4b49db-8ddc-445d-8138-675c178fa5d4
		summarizeBy: none
		sourceColumn: cust_text3

		annotation SummarizationSetBy = Automatic

	column cust_text4
		dataType: string
		lineageTag: e9b1480c-d57a-40aa-85b0-45760008f056
		summarizeBy: none
		sourceColumn: cust_text4

		annotation SummarizationSetBy = Automatic

	column cust_text5
		dataType: string
		lineageTag: 916899fd-466f-4c8f-80d7-fcb22780f7e3
		summarizeBy: none
		sourceColumn: cust_text5

		annotation SummarizationSetBy = Automatic

	column cust_num1
		dataType: double
		lineageTag: 1cf5190a-c739-410d-8672-e8ff0973aead
		summarizeBy: sum
		sourceColumn: cust_num1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num2
		dataType: double
		lineageTag: 7f1e3962-4286-4dff-95ab-40aacb3a7d26
		summarizeBy: sum
		sourceColumn: cust_num2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num3
		dataType: double
		lineageTag: 896ccf0e-7518-4c84-8a41-50098cabd965
		summarizeBy: sum
		sourceColumn: cust_num3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num4
		dataType: double
		lineageTag: 4c00df42-2f71-490c-937b-ed53235548fe
		summarizeBy: sum
		sourceColumn: cust_num4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num5
		dataType: double
		lineageTag: d863f2c3-d442-4ef5-a7f2-0e8d0979ce99
		summarizeBy: sum
		sourceColumn: cust_num5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num6
		dataType: double
		lineageTag: e6d6a9ca-43ba-4b90-8daa-2237c3d103bd
		summarizeBy: sum
		sourceColumn: cust_num6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_num7
		dataType: double
		lineageTag: 28d39190-860c-438b-ab66-9181b90c5eff
		summarizeBy: sum
		sourceColumn: cust_num7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cust_bool1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 63f7944c-5262-4e42-94ad-3c73020d389a
		summarizeBy: none
		sourceColumn: cust_bool1

		annotation SummarizationSetBy = Automatic

	column cust_bool2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c9709a3e-9d8e-4613-b037-16e184dc65ef
		summarizeBy: none
		sourceColumn: cust_bool2

		annotation SummarizationSetBy = Automatic

	column trueai_step_sequence
		dataType: int64
		formatString: 0
		lineageTag: 31663b45-26e1-4adf-8e87-f498a1e56124
		summarizeBy: sum
		sourceColumn: trueai_step_sequence

		annotation SummarizationSetBy = Automatic

	column _sys_doc_id
		dataType: string
		lineageTag: 7914c411-03dd-4a71-8ac6-9e3b59348131
		summarizeBy: none
		sourceColumn: _sys_doc_id

		annotation SummarizationSetBy = Automatic

	column trueai_act_count
		dataType: int64
		formatString: 0
		lineageTag: 30dfadc6-f2b0-4727-99b4-9bc0e8f66632
		summarizeBy: sum
		sourceColumn: trueai_act_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_dur
		dataType: double
		lineageTag: f6face08-bd35-4899-b1b0-400d1e7326d2
		summarizeBy: sum
		sourceColumn: trueai_act_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_eng_count
		dataType: int64
		formatString: 0
		lineageTag: dece7dd9-e5a3-44d9-a6a1-6aa742ba4e27
		summarizeBy: sum
		sourceColumn: trueai_act_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_eng_dur
		dataType: double
		lineageTag: b27ae1b9-dcf3-4ae3-aa2a-d1114a7bff1e
		summarizeBy: sum
		sourceColumn: trueai_act_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_stage_num
		dataType: int64
		formatString: 0
		lineageTag: dea5d0ac-bfdf-4814-9bf3-3a56c97060c7
		summarizeBy: sum
		sourceColumn: trueai_stage_num

		annotation SummarizationSetBy = Automatic

	column trueai_can_be_excluded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7a312381-3cb6-4767-b9c1-296dfc5e5a03
		summarizeBy: none
		sourceColumn: trueai_can_be_excluded

		annotation SummarizationSetBy = Automatic

	column trueai_current_prob_of_win
		dataType: double
		lineageTag: a83f703e-0b45-4cb0-85b9-e96c24ea7d01
		summarizeBy: sum
		sourceColumn: trueai_current_prob_of_win

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_is_closed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b39fc385-703a-45ec-8162-08af49dcdcd2
		summarizeBy: none
		sourceColumn: trueai_is_closed

		annotation SummarizationSetBy = Automatic

	column trueai_owner_prep_factor
		dataType: double
		lineageTag: 11b787c2-dc72-4a6a-a47f-de4ddfc71b1d
		summarizeBy: sum
		sourceColumn: trueai_owner_prep_factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_owner_act_capt_lvl
		dataType: double
		lineageTag: 8e2b4033-afbe-4d3c-9c9f-c626065a0af2
		summarizeBy: sum
		sourceColumn: trueai_owner_act_capt_lvl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_owner_act_capt_lvl_conf
		dataType: double
		lineageTag: 9dc4ff5e-3bfb-4ea4-8298-55260ff334be
		summarizeBy: sum
		sourceColumn: trueai_owner_act_capt_lvl_conf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_auto_email_count
		dataType: int64
		formatString: 0
		lineageTag: fec509b9-2090-4688-83f2-a75ceb55c3ce
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_auto_email_dur
		dataType: double
		lineageTag: b6aa685e-4fb6-4acb-8b15-bcd081783d05
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_auto_email_eng_count
		dataType: int64
		formatString: 0
		lineageTag: ac556dd3-6a8e-4ca4-8775-4353fd4133c9
		summarizeBy: sum
		sourceColumn: trueai_act_type_auto_email_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_call_count
		dataType: int64
		formatString: 0
		lineageTag: e6b7ea6c-15ce-4d61-b861-4f54c8be953a
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_call_dur
		dataType: double
		lineageTag: 65e500d7-c167-407b-94ad-4522436920a4
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_call_eng_count
		dataType: int64
		formatString: 0
		lineageTag: e3a3f6aa-70fe-45ca-be3e-c710f6e6f052
		summarizeBy: sum
		sourceColumn: trueai_act_type_call_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_email_count
		dataType: int64
		formatString: 0
		lineageTag: bc1feca5-6286-47a4-a7c0-6fe0d53afa67
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_email_dur
		dataType: double
		lineageTag: 6508514d-f2d8-4515-a3b9-c7ebe949a71b
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_email_eng_count
		dataType: int64
		formatString: 0
		lineageTag: f9a64fba-f629-418f-97c9-c05811b5eaaf
		summarizeBy: sum
		sourceColumn: trueai_act_type_email_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_meeting_count
		dataType: int64
		formatString: 0
		lineageTag: 2ffac20e-1983-447e-8a2b-136cfd11f930
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_meeting_dur
		dataType: double
		lineageTag: 63fb6b62-6271-4f6c-ab69-470e671eeedc
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_meeting_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 604dfd3f-b77e-461d-bf33-21f40bb109c0
		summarizeBy: sum
		sourceColumn: trueai_act_type_meeting_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_nd_count
		dataType: int64
		formatString: 0
		lineageTag: 0033078f-30f7-465b-be9e-ac4e047dfdc5
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_nd_dur
		dataType: double
		lineageTag: 907ceb27-9e2e-4e04-8416-e80397279002
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_nd_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 1d32d31a-d978-4845-8d51-49caebdf5fd9
		summarizeBy: sum
		sourceColumn: trueai_act_type_nd_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_no_interaction_count
		dataType: int64
		formatString: 0
		lineageTag: c679b5ba-f268-457b-bc13-72d7fdb2529b
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_no_interaction_dur
		dataType: double
		lineageTag: 53d03c90-02e1-496e-8045-1001a254b42c
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_no_interaction_eng_count
		dataType: int64
		formatString: 0
		lineageTag: d500819e-63b7-4bd2-a303-77cfa9b6c373
		summarizeBy: sum
		sourceColumn: trueai_act_type_no_interaction_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_social_count
		dataType: int64
		formatString: 0
		lineageTag: b01b755f-3d94-4dde-8942-e57a26fb3505
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_type_social_dur
		dataType: double
		lineageTag: 1957ea43-4d9b-4029-b171-1542dd3d214f
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_type_social_eng_count
		dataType: int64
		formatString: 0
		lineageTag: 90e3b2fe-504c-438c-ae72-f325f5287093
		summarizeBy: sum
		sourceColumn: trueai_act_type_social_eng_count

		annotation SummarizationSetBy = Automatic

	column trueai_act_adj_dur
		dataType: double
		lineageTag: 62f8f7cc-4073-443b-8ed9-1392a213a397
		summarizeBy: sum
		sourceColumn: trueai_act_adj_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_adj_eng_dur
		dataType: double
		lineageTag: b966ae9b-84a6-4a7a-b3ba-5d8dad58e75f
		summarizeBy: sum
		sourceColumn: trueai_act_adj_eng_dur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_act_adj_dur_rule
		dataType: int64
		formatString: 0
		lineageTag: 35e72331-7a15-4838-b34f-8ff501c53094
		summarizeBy: sum
		sourceColumn: trueai_act_adj_dur_rule

		annotation SummarizationSetBy = Automatic

	column trueai_last_eng_act =
			
			var _id = [crm_opp_id]
			var res  = CALCULATE(
			    MAX(ssr_history[stkhlds_all_last_eng]),
			    ssr_history[entity_opp_id]=_id
			)
			
			RETURN
			res
		formatString: Short Date
		lineageTag: ec9e5e54-a2ee-4917-aaab-505ce2223b3b
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 9a772f5f-7f00-4ff9-a678-e2d928266396
			defaultHierarchy: LocalDateTable_20544d6b-282d-4183-b0d2-0483e6e844b6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column crm_stage_id
		dataType: string
		lineageTag: 794cd384-506b-463d-a43d-b6b242e374f5
		summarizeBy: none
		sourceColumn: crm_stage_id

		annotation SummarizationSetBy = Automatic

	column trueai_stage_id
		dataType: string
		lineageTag: a22456f8-dc7e-448e-ac75-166c5ceddac5
		summarizeBy: none
		sourceColumn: trueai_stage_id

		annotation SummarizationSetBy = Automatic

	column trueai_stage_name
		dataType: string
		lineageTag: 1819dcf2-878d-4ecf-ad48-516fc28898e0
		summarizeBy: none
		sourceColumn: trueai_stage_name

		annotation SummarizationSetBy = Automatic

	column trueai_pipeline_name
		dataType: string
		lineageTag: ebdbabfd-ae67-4d27-ac0e-324d87542d91
		summarizeBy: none
		sourceColumn: trueai_pipeline_name

		annotation SummarizationSetBy = Automatic

	column trueai_sort_id
		dataType: string
		lineageTag: b5868077-1537-4949-8e9b-08f991c61b96
		summarizeBy: none
		sourceColumn: trueai_sort_id

		annotation SummarizationSetBy = Automatic

	column trueai_success_prob
		dataType: double
		lineageTag: 44d41e39-4a3a-4227-acb5-4ba13109fe17
		summarizeBy: sum
		sourceColumn: trueai_success_prob

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_owner_id
		dataType: string
		lineageTag: 38926ce8-7bd7-42a4-847b-cadfa7f02a6f
		summarizeBy: none
		sourceColumn: trueai_owner_id

		annotation SummarizationSetBy = Automatic

	column trueai_days_in_stage
		dataType: int64
		formatString: 0
		lineageTag: 8bc470f9-c3d4-490a-bb62-2f0291f12485
		summarizeBy: sum
		sourceColumn: trueai_days_in_stage

		annotation SummarizationSetBy = Automatic

	column trueai_days_in_opp
		dataType: int64
		formatString: 0
		lineageTag: 69aba56d-0596-4208-9332-017c0b5661b8
		summarizeBy: sum
		sourceColumn: trueai_days_in_opp

		annotation SummarizationSetBy = Automatic

	column trueai_pace_score_days_in_stage
		dataType: double
		lineageTag: 7329a950-5c17-4ea0-9167-e971631c43d8
		summarizeBy: sum
		sourceColumn: trueai_pace_score_days_in_stage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_pace_score_days_in_opp
		dataType: double
		lineageTag: b252ccb5-627f-4ff6-a989-dcdcb2da6d09
		summarizeBy: sum
		sourceColumn: trueai_pace_score_days_in_opp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_pace_score
		dataType: double
		lineageTag: 52f2efd6-71a0-4d3b-bf9e-78a00b8fb46c
		summarizeBy: sum
		sourceColumn: trueai_pace_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_pace_tier
		dataType: int64
		formatString: 0
		lineageTag: 10f9fe0e-a498-4239-bafd-d5c0c464a947
		summarizeBy: sum
		sourceColumn: trueai_pace_tier

		annotation SummarizationSetBy = Automatic

	column trueai_act_last_eng
		dataType: dateTime
		formatString: General Date
		lineageTag: 811e5918-000e-4bb6-8441-f90c896d9696
		summarizeBy: none
		sourceColumn: trueai_act_last_eng

		variation Variation
			isDefault
			relationship: a635b966-5289-417d-b87b-d365446ce68f
			defaultHierarchy: LocalDateTable_25a95f19-ccbf-4c7d-9861-1dac5d493b19.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_init_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: cadd40c0-a914-40c0-ba2e-8962ac22da6c
		summarizeBy: none
		sourceColumn: trueai_init_close_date

		variation Variation
			isDefault
			relationship: 5472189e-552d-4fac-aff4-82f7c834d86b
			defaultHierarchy: LocalDateTable_09f77811-0a2c-422d-88d7-09bbcd68e6c8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_avg_step_sequence
		dataType: int64
		formatString: 0
		lineageTag: 3337e4f5-5b5f-46f0-8e61-431dd3cb9932
		summarizeBy: sum
		sourceColumn: trueai_avg_step_sequence

		annotation SummarizationSetBy = Automatic

	column trueai_pred_booking_amt
		dataType: double
		lineageTag: 90f0aa66-a06f-4b9f-be32-3214df6c30ca
		summarizeBy: sum
		sourceColumn: trueai_pred_booking_amt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_pred_close_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1ab1f353-fe6a-4171-b1e9-0b4eefa801fe
		summarizeBy: none
		sourceColumn: trueai_pred_close_date

		variation Variation
			isDefault
			relationship: c23e475a-e09d-4192-8550-2a40e6cb7cd4
			defaultHierarchy: LocalDateTable_b4aa4367-5677-4901-844f-94529d18272e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column trueai_attention_value_success_prob
		dataType: double
		lineageTag: 535d8d6c-b8ba-459f-8f5d-38ccc6546908
		summarizeBy: sum
		sourceColumn: trueai_attention_value_success_prob

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_attention_value_expected_success_prob
		dataType: double
		lineageTag: ce98edad-d7c6-419c-9a3f-b6cef978691c
		summarizeBy: sum
		sourceColumn: trueai_attention_value_expected_success_prob

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_attention_value_score
		dataType: double
		lineageTag: 043b4fb9-fc99-4d9c-8b4e-cdce1c5ed155
		summarizeBy: sum
		sourceColumn: trueai_attention_value_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trueai_attention_value_text
		dataType: string
		lineageTag: ec0e3163-e5bd-4104-94f6-1f513d6485f7
		summarizeBy: none
		sourceColumn: trueai_attention_value_text

		annotation SummarizationSetBy = Automatic

	column trueai_days_pushed_pulled
		dataType: int64
		formatString: 0
		lineageTag: 3a282143-9d18-4108-9e30-5af76f854596
		summarizeBy: sum
		sourceColumn: trueai_days_pushed_pulled

		annotation SummarizationSetBy = Automatic

	partition open_pipeline = m
		mode: import
		source =
				let
				
				
				    dbTable = getDBTable("open_pipeline"), // get the right table
				    dbTableTyped = Table.TransformColumnTypes(dbTable,{
				       {"_sys_as_of", type datetime},
				{"_sys_doc_id", type text},
				{"_sys_filt_end_date", type date},
				{"_sys_filt_start_date", type date},
				{"crm_booking_amt", type number},
				{"crm_close_date", type datetime},
				{"crm_created_on", type datetime},
				{"crm_creator_id", type text},
				{"crm_opp_id", type text},
				{"crm_stage_id", type text},
				{"crm_stage_name", type text},
				{"crm_stage_num", type text},
				{"cust_bool1", type logical},
				{"cust_bool2", type logical},
				{"cust_num1", type number},
				{"cust_num2", type number},
				{"cust_num3", type number},
				{"cust_num4", type number},
				{"cust_num5", type number},
				{"cust_num6", type number},
				{"cust_num7", type number},
				{"cust_text1", type text},
				{"cust_text2", type text},
				{"cust_text3", type text},
				{"cust_text4", type text},
				{"cust_text5", type text},
				{"trueai_act_adj_dur", type number},
				{"trueai_act_adj_dur_rule", Int64.Type},
				{"trueai_act_adj_eng_dur", type number},
				{"trueai_act_count", Int64.Type},
				{"trueai_act_dur", type number},
				{"trueai_act_eng_count", Int64.Type},
				{"trueai_act_eng_dur", type number},
				{"trueai_act_type_auto_email_count", Int64.Type},
				{"trueai_act_type_auto_email_dur", type number},
				{"trueai_act_type_auto_email_eng_count", Int64.Type},
				{"trueai_act_type_call_count", Int64.Type},
				{"trueai_act_type_call_dur", type number},
				{"trueai_act_type_call_eng_count", Int64.Type},
				{"trueai_act_type_email_count", Int64.Type},
				{"trueai_act_type_email_dur", type number},
				{"trueai_act_type_email_eng_count", Int64.Type},
				{"trueai_act_type_meeting_count", Int64.Type},
				{"trueai_act_type_meeting_dur", type number},
				{"trueai_act_type_meeting_eng_count", Int64.Type},
				{"trueai_act_type_nd_count", Int64.Type},
				{"trueai_act_type_nd_dur", type number},
				{"trueai_act_type_nd_eng_count", Int64.Type},
				{"trueai_act_type_no_interaction_count", Int64.Type},
				{"trueai_act_type_no_interaction_dur", type number},
				{"trueai_act_type_no_interaction_eng_count", Int64.Type},
				{"trueai_act_type_social_count", Int64.Type},
				{"trueai_act_type_social_dur", type number},
				{"trueai_act_type_social_eng_count", Int64.Type},
				{"trueai_booking_amt", type number},
				{"trueai_can_be_excluded", type logical},
				{"trueai_current_prob_of_win", type number},
				{"trueai_days_in_opp", Int64.Type},
				{"trueai_days_in_stage", Int64.Type},
				{"trueai_is_closed", type logical},
				{"trueai_is_won", type logical},
				{"trueai_owner_act_capt_lvl", type number},
				{"trueai_owner_act_capt_lvl_conf", type number},
				{"trueai_owner_id", type text},
				{"trueai_owner_prep_factor", type number},
				{"trueai_pace_score", type number},
				{"trueai_pace_score_days_in_opp", type number},
				{"trueai_pace_score_days_in_stage", type number},
				{"trueai_pace_tier", Int64.Type},
				{"trueai_pipeline_name", type text},
				{"trueai_sort_id", type text},
				{"trueai_stage", type text},
				{"trueai_stage_id", type text},
				{"trueai_stage_name", type text},
				{"trueai_step_sequence", Int64.Type},
				{"trueai_success_prob", type number}
				    }),
				     addedStageNum = Table.AddColumn(dbTableTyped, "trueai_stage_num", each if [trueai_stage] = "Early" then 1 else if [trueai_stage] = "Mid" then 2 else if [trueai_stage] = "Late" then 3 else if [trueai_stage] = "Closed Won" then 4 else if [trueai_stage] = "Closed Lost" then 5 else 7),
				    ChangedType = Table.TransformColumnTypes(addedStageNum,{{"trueai_stage_num", Int64.Type}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(ChangedType,{{"_sys_doc_id", "_sys_doc_id"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

