table ssr_history_success_prob_factors
	lineageTag: 6d0d1645-2b04-4700-87d8-13fed799fb4d

	measure 'meas.ssr_history_success_prob_impact' =
			
			var _prob = CALCULATE(
			    AVERAGE(
			        ssr_history_success_prob_factors[impact]        // get the average prob
			    )
			)
			
			var res = ROUND(_prob, 2)
			
			RETURN
			res
		formatString: +0%;-0%;0%
		displayFolder: success_prob_factors
		lineageTag: 8c898ccc-8056-4912-ac3e-ce6afbb43143

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'meas.ssr_history_success_prob_impact_positive' =
			
			var positiveVal = CALCULATE(MAX(ssr_history_success_prob_factors[impact]))
			RETURN
			IF(positiveVal > 0, positiveVal,BLANK())
		formatString: 0%;-0%;0%
		displayFolder: success_prob_factors
		lineageTag: 565e0f38-f6ce-4548-a88e-9b6de987e2fa

	measure 'meas.ssr_history_success_prob_impact_negative' =
			
			var Val = CALCULATE(MAX(ssr_history_success_prob_factors[impact]))
			RETURN
			IF(Val < 0, Val,BLANK())
		formatString: 0%;-0%;0%
		displayFolder: success_prob_factors
		lineageTag: 9148a5ce-e1ea-4877-a07c-e9990c3e02af

	measure 'meas.ssr_history_success_prob_impact_neutral' =
			
			var positiveVal = CALCULATE(MAX(ssr_history_success_prob_factors[impact]))
			RETURN
			IF(positiveVal = 0, positiveVal,BLANK())
		formatString: 0%;-0%;0%
		displayFolder: success_prob_factors
		lineageTag: be309515-4d9a-4856-ad6a-8d0c3dad396e

	measure 'meas.ssr_history_success_prob_factors_count' = ```
			
			var res = CALCULATE(count(ssr_history_success_prob_factors[_sys_ssr_history_id]))
			RETURN res
			
			```
		formatString: #,0
		displayFolder: success_prob_factors
		lineageTag: ffbf4531-12c0-4a82-889e-ed353a5a1a5e

	measure 'meas.ssr_history_success_prob_factors_all_count' = ```
			
			var res = CALCULATE(count(ssr_history_success_prob_factors[_sys_ssr_history_id]), ssr_history_success_prob_factors[name] <> "aaa" &&  ssr_history_success_prob_factors[value] <> "aaa" ) // get the count of all outside the filter
			RETURN res
			
			```
		formatString: 0
		displayFolder: success_prob_factors
		lineageTag: bb952828-5ff6-4ce1-8186-7124fb7627ac

	measure 'meas.ssr_history_success_prob_factors_pct' = ```
			
			
			// this is our old measure
			var res = DIVIDE([meas.ssr_history_success_prob_factors_count], [meas.ssr_history_success_prob_factors_all_count])  // ratio of the factors count
			RETURN res
			
			```
		formatString: #%
		displayFolder: success_prob_factors
		lineageTag: fbebdf1c-4075-4d59-9b9d-7cae7d96dee0

	measure 'meas.success_prob_factors_most_impact_str' = ```
			
			
			// changes for git check
			
			// // get most impct. 
			// VAR FactorImpactCount = 
			//     ADDCOLUMNS(
			//         SUMMARIZE(
			//             ssr_history_success_prob_factors, 
			//             ssr_history_success_prob_factors[name] ,ssr_history_success_prob_factors[value] ,
			//                         ssr_history_success_prob_factors[impact]
			//         ),
			//         "Count", CALCULATE(COUNTROWS(ssr_history_success_prob_factors))
			//     )
			// VAR RankedFactors = 
			//     ADDCOLUMNS(
			//         FactorImpactCount,
			//         "Rank", RANKX(ALL(FactorImpactCount), [impact] * 10000 + [Count], , DESC, Dense)
			//     )
			// VAR Top4Factors = 
			//     FILTER(
			//         RankedFactors,
			//         [Rank] <= 4
			//     )
			// RETURN
			//     CONCATENATEX(
			//         Top4Factors,
			//         ssr_history_success_prob_factors[name] & " (Impact: " & ssr_history_success_prob_factors[Impact] & ", Count: " & [Count] & ")",
			//         ", ",
			//         [Rank],
			//         ASC
			//     )
			```
		formatString: 0
		displayFolder: success_prob_factors
		lineageTag: d3d03bb1-d585-4650-afcf-21178f54a977

	measure 'meas.ssr_history_success_prob_feature_impact' = ```
			
			CALCULATE(
			    AVERAGEX(
			        ssr_history_success_prob_factors, 
			        ssr_history_success_prob_factors[feature_impact]        // get the average feature impact
			    )
			)
			```
		formatString: 0%;-0%;0%
		displayFolder: success_prob_factors
		lineageTag: ca2857e0-3196-408f-8103-8b2b7f7460ba

	measure 'meas.ssr_history_success_prob_factors_pct_how_many' =
			
			
			var step_count = [meas.ssr_history_step_count]           // get the converted leads count from ssr_history table
			
			var _success_prob_count = [meas.ssr_history_success_prob_factors_count]         // get the success prob count from ssr_history success prob table
			
			
			var res = DIVIDE(_success_prob_count, step_count,0)     // get the ratio
			RETURN
			res
		formatString: 0%;-0%;0%
		displayFolder: success_prob_factors
		lineageTag: 0162ca58-4bf0-4d0b-8b9b-11e1cccf55ea

	measure 'meas.top_factor_name_by_impact' = ```
			
			VAR MaxImpact = 
			    MAXX(
			        'ssr_history_success_prob_factors', 
			        'ssr_history_success_prob_factors'[impact]
			    )
			-- Now find the corresponding name with that max impact
			RETURN
			CALCULATE(
			    MAX('ssr_history_success_prob_factors'[name]),
			    'ssr_history_success_prob_factors'[impact] = MaxImpact
			)
			
			```
		displayFolder: success_prob_factors
		lineageTag: f24a5b64-818e-42df-920a-3a818a663c56

	column _sys_ssr_history_id
		dataType: string
		lineageTag: 9cb59373-1b86-4c62-88de-26ae0e1a56f7
		summarizeBy: none
		sourceColumn: _sys_ssr_history_id

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: bfbc048b-0b56-465d-91b7-80a65d148931
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		lineageTag: b2494608-3e14-405f-b1d5-861bc94f733d
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: double
		formatString: 0.00
		lineageTag: 49b6ba24-8721-4a28-9c5e-6dab02735605
		summarizeBy: sum
		sourceColumn: impact
		sortByColumn: sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column sig
		dataType: string
		lineageTag: 15569c69-8bd1-4b2e-bd2d-c724ed528454
		summarizeBy: none
		sourceColumn: sig

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 9f36353a-9eb2-4a46-a79b-497ef291ad90
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column sort
		dataType: double
		lineageTag: 4fa38c3e-0abe-4e6b-827b-57c4ae757d58
		summarizeBy: sum
		sourceColumn: sort

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column feature_impact
		dataType: double
		lineageTag: fb6ad995-f6e7-4ab8-a86c-118420567574
		summarizeBy: sum
		sourceColumn: feature_impact

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ordering_factor
		dataType: double
		lineageTag: 4a04b91f-0def-4729-b0de-3a51e76b058d
		summarizeBy: sum
		sourceColumn: ordering_factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column step_name
		dataType: string
		lineageTag: 99753aa6-88c5-43ea-87fc-41c04f9ab483
		summarizeBy: none
		sourceColumn: step_name

		annotation SummarizationSetBy = Automatic

	column display
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e0145790-ed1d-4597-a220-acc20ec6673a
		summarizeBy: none
		sourceColumn: display

		annotation SummarizationSetBy = Automatic

	partition ssr_history_success_prob_factors = m
		mode: import
		source = ```
				let
				    Source2 = let
				    Source = ssr_history,
				    tblFactors = Table.SelectColumns(Source,{"_sys_doc_id","step_name", "step_success_prob_factors"}),
				    tblFactorsFiltered = Table.SelectRows(tblFactors, each ([step_success_prob_factors] <> null)),
				    tblFactorsFiltered2 = Table.SelectRows(tblFactorsFiltered, each ([step_success_prob_factors] <> "[null]")),
				    parsed_JSON = Table.TransformColumns(tblFactorsFiltered2,{{"step_success_prob_factors", Json.Document}})
				    
				in
				    parsed_JSON,
				    tblExpandToList = Table.ExpandListColumn(Source2, "step_success_prob_factors"),
				    tblExpandToCols = Table.ExpandRecordColumn(tblExpandToList, "step_success_prob_factors", {"model", "value", "impact", "sig", "name", "display", "feature_impact", "ordering_factor"}, {"model", "value", "impact", "sig", "name", "display", "feature_impact", "ordering_factor"}),
				    RenamedSysDocId = Table.RenameColumns(tblExpandToCols,{{"_sys_doc_id", "_sys_ssr_history_id"}}),
				    ReplacedNull = Table.ReplaceValue(RenamedSysDocId,null,0,Replacer.ReplaceValue,{"impact"}),
				    ChangedDtype = Table.TransformColumnTypes(ReplacedNull,{{"impact", type number}}),
				    AddedSortCol = Table.AddColumn(ChangedDtype, "sort", each if [impact] = 0 then -9999 else [impact]),
				    ChangedTyp = Table.TransformColumnTypes(AddedSortCol,{{"sort", type number}}),
				    CapitalizedEachWord = Table.TransformColumns(ChangedTyp,{{"sig", Text.Proper, type text}}),
				    ChangeddataType = Table.TransformColumnTypes(CapitalizedEachWord,{{"ordering_factor", type number}, {"feature_impact", type number}, {"display", type logical}})
				in
				    ChangeddataType
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

