DEFINE
    -- 1. UDF to create the Virtual Table
    FUNCTION fnGenerateRepTable = (_measure: expr) => 
	
    	VAR tbl =  SUMMARIZECOLUMNS(
			users[trueai_full_name],
			"Measure_Pre_AGG", _measure
			
        )
		var perf_metric_avg = AVERAGEX( tbl, [Measure_Pre_AGG] )
		RETURN perf_metric_avg
		
EVALUATE
 fnGenerateRepTable([meas.ssr_history_won_amt])
