DEFINE
    -- 1. UDF to create the Virtual Table
    FUNCTION fnGenerateRepTable = (_measure: expr) => 
	
    	VAR tbl =  SUMMARIZECOLUMNS(
			ssr_history[col.step_owner_group],
			ssr_history[trueai_user_role_alias],
			"Measure_Pre_AGG", _measure
			
        )
		// var perf_metric_avg = AVERAGEX( tbl, [Measure_Pre_AGG] )
		// RETURN perf_metric_avg
		RETURN tbl
		
EVALUATE
 fnGenerateRepTable([meas.ssr_history_won_amt])
