DEFINE
    TABLE RowTest = 
        DATATABLE (
            "metric_name", STRING, 
            "metric_prefix", STRING, 
            "metric_format", STRING,
            {
                {"Renewal Bookings", "Renew", "Currency"},
                {"Total Bookings Won Amt.", "Tot._Amt.", "Currency"} -- Match this exactly to your table cell
            }
        )

    MEASURE RowTest[Value] = 7612673 -- Sample number

    MEASURE RowTest[FormatString] = 
        VAR _prefix = SELECTEDVALUE(RowTest[metric_prefix])
        VAR _fmtMeta = SELECTEDVALUE(RowTest[metric_format])
        VAR _withPrefix = NOT ISBLANK(_prefix)
        VAR _p = IF(_withPrefix, _prefix & " ", "")
        
        VAR _isRevenue = NOT ISBLANK(_fmtMeta) && CONTAINSSTRING( LOWER(_fmtMeta), "currency" )
        RETURN IF(_isRevenue, _p & "$#,0", "#,0")

EVALUATE
    ADDCOLUMNS(
        RowTest,
        "Generated String", [FormatString],
        "Final Result", FORMAT([Value], [FormatString])
    )