DEFINE
    -- Updated UDF to calculate Peer Average
    FUNCTION fnGeneratePeerTable = (_measure: expr) => 
        CALCULATE(
            VAR tbl = SUMMARIZECOLUMNS(
                ssr_history[col.step_owner_group],
                ssr_history[trueai_user_role_alias],
                "Measure_Pre_AGG", _measure
            )
            // RETURN AVERAGEX( tbl, [Measure_Pre_AGG] ),
			RETURN tbl,
            
            -- THE MAGIC STEP:
            -- This removes any filter specifically on the Rep's name
            REMOVEFILTERS(users[trueai_full_name]) 
        )

EVALUATE
    -- When you test this, even if you added a FILTER(users[trueai_full_name] = "John Doe"),
    -- this function will return the average for John's entire Group/Role.
fnGeneratePeerTable([meas.ssr_history_won_amt])