DEFINE
    -- 1. UDF to create the Virtual Table
    FUNCTION fnGenerateRepTable = (meas1: expr, meas2: expr) => 
        SUMMARIZECOLUMNS(
			users[trueai_full_name],
            users[trueai_group],
            users[trueai_user_role_alias],
			
			"Measure1", meas1, 
            "Measure2", meas2
			
        )

/* After defining the table logic, we use it to calculate the Stats */
EVALUATE
fnGenerateRepTable( [meas.won_amt], [meas.stkhlds_all_act_meeting_count])
