DEFINE
    -- This function creates the table AND averages it internally
    FUNCTION fnAvgByRep = (_measure) =>
        AVERAGEX(
            SUMMARIZECOLUMNS(
                users[trueai_full_name],
                "PreAgg", _measure
            ),
            [PreAgg]
        )

EVALUATE
    {
        ("Average", fnAvgByRep([meas.stkhlds_all_act_email_count]))
    }